dfe-analytical-services/explore-education-statistics

src/GovUk.Education.ExploreEducationStatistics.Data.Model/Database/StatisticsDbContext.cs
This PR makes a small change reducing the _statistics_ database `CommandTimeout` to 5 minutes.
If this isn't set in the connection string or configured separately then the default `CommandTimeout` of the SqlClient is 30 seconds. We see this in logging of _content_ database queries where we haven't overridden it:
`Executing DbCommand [Parameters=[], CommandType='Text', CommandTimeout='30']`
However for the _statistics_ database we've currently set this to `int.MaxValue`
`Executing DbCommand [], CommandType='Text', CommandTimeout='2147483647']`
That's 68 years.
Timeouts such as the [Azure App Service Load Balancer timeout of 4 minutes](https://learn.microsoft.com/en-us/troubleshoot/azure/app-service/web-apps-performance-faqs#why-does-my-request-time-out-after-230-seconds) are going to occur …
=> Reduce statistics database connection timeout to 5 minutes

src/explore-education-statistics-admin/src/pages/release/content/components/ReleasePreviewTableTool.tsx, src/explore-education-statistics-admin/src/pages/release/datablocks/components/DataBlockSourceWizard.tsx, src/explore-education-statistics-admin/src/pages/release/pre-release/PreReleaseTableToolPage.tsx, src/explore-education-statistics-admin/src/prototypes/components/PrototypeTableToolWizard.tsx, src/explore-education-statistics-common/src/modules/table-tool/components/FiltersForm.tsx, src/explore-education-statistics-common/src/modules/table-tool/components/SubjectStep.tsx, src/explore-education-statistics-common/src/modules/table-tool/components/TableToolWizard.tsx, src/explore-education-statistics-common/src/modules/table-tool/components/Wizard.tsx, src/explore-education-statistics-common/src/modules/table-tool/components/__tests__/TableToolWizard.test.tsx, src/explore-education-statistics-frontend/src/modules/table-tool/TableToolPage.tsx, tests/robot-tests/tests/general_public/table_tool_absence_by_characteristic.robot
Changes the behaviour when you click the browser back button while using  the table tool.
When I click the back button from:
- a featured table
- if got there from step 2 > go back to step 2
- if followed a direct link to the table > normal back button behaviour
- step 2 (subject)
- if publication step was the initial step > go back to publication step
- if subject step was the initial step (i.e. came from release page) > normal back button behaviour
- steps 3, 4, 5 & 6 (location, time, filters and final) > go back to step 2
- I ended up with a combination of the two approaches suggested on the ticket - it updates the url when you choose a publication and subject, and intercepts the back click using `beforePopState` to activate the correct step. I initially tried just using …
=> EES-2465 back button behaviour on table tool

src/GovUk.Education.ExploreEducationStatistics.Content.Model.Tests/Extensions/FileExtensionTests.cs, src/GovUk.Education.ExploreEducationStatistics.Content.Model.Tests/Extensions/ReleaseFileExtensionTests.cs, src/GovUk.Education.ExploreEducationStatistics.Content.Model/Extensions/ReleaseFileExtensions.cs, src/GovUk.Education.ExploreEducationStatistics.Data.Api.Tests/Services/PermalinkCsvMetaServiceTests.cs, src/GovUk.Education.ExploreEducationStatistics.Data.Api/Services/PermalinkCsvMetaService.cs, src/GovUk.Education.ExploreEducationStatistics.Data.Services.Tests/SubjectCsvMetaServiceTests.cs, src/GovUk.Education.ExploreEducationStatistics.Data.Services/SubjectCsvMetaService.cs
This PR fixes exceptions occurring streaming the data file blob in `SubjectCsvMetaService` and `PermalinkCsvMetaService` where within the `GetCsvStream` methods the `ReleaseFile` predicate was not constrained by type `FileType.Data`.
This led to the exception `Sequence contains more than one element.` due to the existence of the other `ReleaseFile` of type `FileType.Metadata`.
There was also an exception occurring streaming the blob using `releaseFile.PublicPath()` due to its reliance on the `releaseFile.Release` being loaded. This is changed to only rely on `releaseFile.ReleaseId`.
- Fix exception logging which was missing the `SubjectId`
=> EES-4225 Fix exceptions streaming data file blob in `GetCsvStream` methods

src/GovUk.Education.ExploreEducationStatistics.Data.Api.Tests/Controllers/PermalinkControllerTests.cs, src/GovUk.Education.ExploreEducationStatistics.Data.Api.Tests/Services/PermalinkServiceTests.cs, src/GovUk.Education.ExploreEducationStatistics.Data.Api/Controllers/PermalinkController.cs, src/GovUk.Education.ExploreEducationStatistics.Data.Api/Services/Interfaces/IPermalinkService.cs, src/GovUk.Education.ExploreEducationStatistics.Data.Api/Services/PermalinkService.cs
This PR: 
* Renames existing permalink services, controllers, interfaces, etc. to have a prefix of 'Legacy'. This is to support the work in EES-3753 when moving to permalink snapshots. We've found that a lot of code is being shared from the existing `permalinkService` so the plan going forward is to merge the separate permalink snapshot service into the existing `permalinkService`. To distinguish what methods are legacy and what methods relate to the new snapshot view model, we are now prefixing existing permalink related stuff with 'Legacy'
=> EES-4229 - permalink naming changes in support of EES-3753 (#3966)

src/GovUk.Education.ExploreEducationStatistics.Admin/Migrations/ContentMigrations/20230406082108_EES3753AddMigrationFields.Designer.cs, src/GovUk.Education.ExploreEducationStatistics.Admin/Migrations/ContentMigrations/20230406082108_EES3753AddMigrationFields.cs, src/GovUk.Education.ExploreEducationStatistics.Content.Model/Permalink.cs, src/GovUk.Education.ExploreEducationStatistics.Data.Api.Tests/Services/PermalinkServiceTests.cs, src/GovUk.Education.ExploreEducationStatistics.Data.Api/Services/PermalinkService.cs
This PR sets up a couple of fields relevant to the future work to implement Permalink snapshots and the work to migrate all existing Permalinks to snapshot format.
`Permalink.Legacy`
`Permalink.LegacyHasSnapshot`
As soon as [EES-3753 - BE work required to support new Permalinks with table snapshots](https://dfedigital.atlassian.net/browse/EES-3753) is completed, there will for a time being, exist two sets of routes for creating and accessing Permalinks:
- Creating and fetching a Permalink or Permalink CSV _with_ a table snapshot (new)
- Creating and fetching a Permalink or Permalink CSV _without_ a table snapshot (legacy)
Until the legacy routes are removed, they should only allow access to Permalinks which exist in legacy format.
The new routes will be designed to only allow access to …
=> EES-4240 Add Permalink migration fields and check Permalink exists

src/GovUk.Education.ExploreEducationStatistics.Admin/GovUk.Education.ExploreEducationStatistics.Admin.csproj, src/GovUk.Education.ExploreEducationStatistics.Admin/web.config
This PR attempts to switch the Admin App service from the out-out-process hosting model using IIS and Kestrel to in-process hosting using just IIS.
In-process has been the default hosting model for new App Services since ASP .Net Core 3.0 and we use it for the Data API and Content API.
In the out-of-process hosting model, IIS (w3wp.exe) running ANCM proxies HTTP requests to Kestrel (Admin.exe) which is a separate dotnet process.
We’d like to switch Admin to using in-process because it’s more performant - there’s no network communication between two servers and it should be less resource intensive.
> In-process hosting runs an ASP.NET Core app in the same process as its IIS worker process. In-process hosting provides improved performance over out-of-process hosting because requests aren't …
=> EES-4274 Switch Admin App Service from out-of-process hosting model to in-process

useful-scripts/permalink-snapshot-migration/migrate_legacy_permalinks.py
This PR adds SSL certificate verification, so that we can use a Data API URL with https and not see a `InsecureRequestWarning` repeated in the log output with every request.
>connectionpool.py:1045: InsecureRequestWarning: Unverified HTTPS request is being made to host '...'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
=> EES-3754 Add SSL certificate verification

infrastructure/templates/template.json, src/GovUk.Education.ExploreEducationStatistics.Data.Api/Startup.cs, src/GovUk.Education.ExploreEducationStatistics.Data.Api/appsettings.Development.json
This PR allows adding a Basic auth header by default to all requests made by the HttpClient used in the `FrontendService`.
This will be added when basic auth is enabled for the Public app service in the environment, controlled by environment properties.
The environment properties already exist in the infrastructure and are applied to the Data API with a slight tweak to `template.json`.
To be clear, this change isn't adding Basic auth to the Data API service. It's allowing the `FrontendService` to make HTTP requests to the Public App service if the Public App service is protected by Basic auth.
=> EES-3754 Add support for Basic Authorization header to frontend `HttpClient`

src/GovUk.Education.ExploreEducationStatistics.Admin/Services/DataBlockService.cs, src/explore-education-statistics-admin/src/pages/release/datablocks/components/DataBlockDetailsForm.tsx, src/explore-education-statistics-admin/src/pages/release/datablocks/components/__tests__/DataBlockDetailsForm.test.tsx
This prevents a bug where by allowing a whitespace featured table name, potentially a featured table with no title could appear on be published and appear on the public site.
This work is done in preparation for splitting featured tables details out of the ContentBlocks table and into their own entity.
=> EES-4277 Trim leading and trailing spaces for featured table names and descriptions

src/GovUk.Education.ExploreEducationStatistics.Admin.Tests/Controllers/Api/Statistics/FootnoteControllerTests.cs, src/GovUk.Education.ExploreEducationStatistics.Data.Api.Tests/Controllers/PublicationControllerTests.cs, src/GovUk.Education.ExploreEducationStatistics.Data.Services.Tests/ReleaseServiceTests.cs, src/GovUk.Education.ExploreEducationStatistics.Data.Services/ReleaseService.cs, src/GovUk.Education.ExploreEducationStatistics.Data.Services/ViewModels/FeaturedTableViewModel.cs, src/GovUk.Education.ExploreEducationStatistics.Data.Services/ViewModels/SubjectViewModel.cs
This PR provides changes to give the frontend the information it needs to render the new featured tables design.
It seems this requires just two changes:
- Return the `subjectId` alongside featured tables.
- Return filter and indicator labels alongside subjects.
:rotating_light: After this is merged, we will need to clear the public cache `subject.json` files. I'll create a faffy deploy ticket to track this. (Edit: EES-4266) :rotating_light:
I'll also put do not merge on this ticket. In theory, we could merge it immediately - it doesn't affect existing functionality - but it might make sense for these changes to go in alongside the frontend changes for featured tables in EES-4048.
=> EES-4231 Backend work to support new featured tables

src/explore-education-statistics-frontend/src/modules/api/permalink/__tests__/createPermalinkTable.test.ts, src/explore-education-statistics-frontend/src/modules/api/permalink/createPermalinkTable.ts
Rename `table` to `json` and `title` to `caption` in the response from the Next.js permalink endpoint.
=> EES-4291 rename to json and caption in the permalink endpoint

tests/robot-tests/scripts/create_snapshots.py
This PR:
* Removes the success slack notification from `create_snapshots.py` in order to reduce spam of the channel & to enable us to run this workflow more frequently
=> EES-4295 - remove success notification for snapshots

src/explore-education-statistics-common/src/modules/table-tool/components/DataTableCaption.tsx, src/explore-education-statistics-common/src/modules/table-tool/components/DownloadTable.tsx, src/explore-education-statistics-common/src/modules/table-tool/components/utils/downloadTableOdsFile.ts, src/explore-education-statistics-common/src/services/permalinkSnapshotService.ts, src/explore-education-statistics-frontend/src/modules/permalink/PermalinkPageOld.tsx, src/explore-education-statistics-frontend/src/modules/permalink/__data__/testPermalinkData.ts, src/explore-education-statistics-frontend/src/modules/permalink/__tests__/PermalinkPage.test.tsx, src/explore-education-statistics-frontend/src/modules/permalink/__tests__/__snapshots__/PermalinkPage.test.tsx.snap, src/explore-education-statistics-frontend/src/modules/table-tool/TableToolPage.tsx, src/explore-education-statistics-frontend/src/modules/table-tool/components/TableToolFinalStep.tsx, src/explore-education-statistics-frontend/src/modules/table-tool/components/TableToolShare.tsx, src/explore-education-statistics-frontend/src/modules/table-tool/components/__tests__/TableToolShare.test.tsx
Adds the new permalink creation process and permalink page under a feature flag.
Add the query param `newPermalinks=true` to see the new version:
- to create new permalinks `/data-tables?newPermalinks=true`
- to view new permalinks `/data-tables/permalink<id>?newPermalinks=true`
=> EES-3792 new permalink snapshots under feature flag

src/explore-education-statistics-common/src/modules/table-tool/components/FiltersForm.module.scss, src/explore-education-statistics-common/src/modules/table-tool/components/FiltersForm.tsx, src/explore-education-statistics-common/src/modules/table-tool/components/__tests__/FiltersForm.test.tsx
Shows additional help text on the filters form in the table tool when any filters have a 'Total' option.
=> EES-4086 show extra filter help text when have totals

src/explore-education-statistics-common/src/modules/find-statistics/components/KeyStatTile.module.scss
Makes sure that all text in key stat blocks will wrap rather than overflow the block.
=> EES-4212 wrap text in key stats

src/explore-education-statistics-frontend/.env, src/explore-education-statistics-frontend/src/modules/table-tool/TableToolPage.tsx, src/explore-education-statistics-frontend/src/modules/table-tool/components/TableToolShare.tsx
This PR makes a frontend change to suffix the value of `PUBLIC_URL` with '/' to match the value set in Azure environments where the public url is suffixed.
This fixes a bug with the generated Permalink url seen below, highlighted by a failing UI test 
>Generated permalink "dev.explore-education-statistics.service.gov.uk//data-tables/permalink/21e47af1-1171-4ceb-b618-08db55cac306" is invalid! Should start with "dev.explore-education-statistics.service.gov.uk/data-tables/permalink/"
This code had been recently changed from `${window.location.origin}/data-tables/permalink...` to `${process.env.PUBLIC_URL}/data-tables/permalink...` in #4035.
- Remove console logging in `TableToolPage.tsx`.
=> EES-3792 FE - Suffix value of PUBLIC_URL with '/' to match the value set in Azure environments

src/GovUk.Education.ExploreEducationStatistics.Data.Processor.Tests/Functions/ProcessorStage1Tests.cs, src/GovUk.Education.ExploreEducationStatistics.Data.Processor.Tests/Functions/ProcessorStage2Tests.cs, src/GovUk.Education.ExploreEducationStatistics.Data.Processor.Tests/Functions/ProcessorStage3Tests.cs, src/GovUk.Education.ExploreEducationStatistics.Data.Processor/Functions/Processor.cs, src/GovUk.Education.ExploreEducationStatistics.Data.Processor/host.json, tests/performance-tests/dashboards/ees-dashboard.json, tests/performance-tests/src/tests/admin/table-tool/adminTableBuilderQuery.test.ts, tests/performance-tests/src/tests/public/table-tool/publicTableBuilderQuery.test.ts, tests/performance-tests/src/utils/adminService.ts, tests/performance-tests/src/utils/dataService.ts, tests/performance-tests/src/utils/tableQueries.ts, tests/performance-tests/src/utils/types.ts
This PR contains some miscellaneous changes that were made during the performance testing of EES-4192 but were never committed as a part of that work.  These changes include:
* removing "ProcessUploads" overload method in `Processor.cs` due to startup warnings in Functions project when the overload exists
* adding the `maxPollingInterval` config parameter to `host.json` allow importer to dequeue messages faster.
* amending `adminTableBuilderQuery.test.ts` and `publicTableBuilderQuery.test.ts` to be more closely aligned in their behaviour with more shared code after one was left working and the other was no longer working. Hopefully this will be easier to maintain.
* updating various panels' `Unit` configuration in the Grafana "EES Dashboard" to display response times in seconds rather …
=> EES-4192 - misc additional changes made whilst performance testing EES-4192

src/explore-education-statistics-common/src/services/util/__tests__/combineMeasuresWithDuplicateLocationCodes.test.ts, src/explore-education-statistics-common/src/services/util/combineMeasuresWithDuplicateLocationCodes.ts
This PR fixes a frontend bug returning combined table results for locations that have been deduplicated.
After deduplicating the locations and then merging table results of the affected locations we should always expect less table rows in the returned result, but in the case of 6 permalinks found which contain multiple duplicate provider codes (codes for which one or more different provider names exist) we can see the number of table results after deduplication far exceeds the original number of results.
The bug occurs while processing the table results that are affected by every deduplicated location.
For each deduplicated location, instead of returning the deduplicated table results, the function was returning the deduplicated table results combined with the array of unaffected results. …
=> EES-4245 Fix bug returning combined table results for deduplicated locations

src/explore-education-statistics-common/src/modules/table-tool/utils/Header.ts, src/explore-education-statistics-common/src/modules/table-tool/utils/__data__/testTableData.ts, src/explore-education-statistics-common/src/modules/table-tool/utils/__tests__/Header.test.ts, src/explore-education-statistics-common/src/modules/table-tool/utils/__tests__/mapTableToJson.test.ts, src/explore-education-statistics-common/src/modules/table-tool/utils/__tests__/optimizeFilters.test.ts, src/explore-education-statistics-common/src/modules/table-tool/utils/optimizeFilters.ts
This fixes a bug in EES-4246 where filter groups with duplicate labels (e.g. 'Total') are not being inserted into the filters from the `optimizeFilters` function. This was preventing the entire table from rendering as the table header tree would not be correctly constructed in `mapTableToJson`, consequently throwing a null pointer.
Various tests have been also been added to test this more thoroughly.
This change also fixes an issue highlighted by a test data set from EES-3408 where there previously alignment issues due to incorrect cross spans being calculated. 
Using the `EES-3408.csv` data set, we can get a table like this:
This has now been fixed so the table looks like:
This has also been tested with the `grouped-filters-and-indicators.csv` data set which seems fine:
=> EES-4246, EES-3408 Fix filter groups with duplicate labels not being inserted into optimised filters

src/GovUk.Education.ExploreEducationStatistics.Common.Tests/Cache/CacheAspectThreadManagementIntegrationTests.cs, src/GovUk.Education.ExploreEducationStatistics.Common.Tests/Extensions/WebHostBuilderExtensions.cs, src/GovUk.Education.ExploreEducationStatistics.Common.Tests/Fixtures/TestApplicationFactory.cs, src/GovUk.Education.ExploreEducationStatistics.Common.Tests/TestStartup.cs
This PR:
* Adds in tests to detect that thread exhaustion issues are no long occurring after moving to the new Universal Wrapper-based CacheAspect / CacheAttribute code
There are 2 broad approaches that are being used to test the new behaviour.
The first approach gathers a list of the events that occur when a Cache-annotated controller method is called, and asserts that it is what we expect to see when the aspect is non-blocking.  We do this for both a scenario when there is no previously cached item and a scenario when there is.
The second approach is a brute-force attempt to cause thread escalation and excessive processing time, by generating several concurrent HTTP requests and monitoring the thread pool and total processing time.
Between these 2 approaches, we should be relatively …
=> EES-3516 - added tests to assert that thread exhaustion issues are no longer occurring

src/explore-education-statistics-common/src/modules/table-tool/components/AllFeaturedTables.tsx, src/explore-education-statistics-common/src/modules/table-tool/components/DataSetStepContent.tsx
This PR removes the large fonts used for guidance text across the data set step. This now looks like:
We have also removed the unneeded grid column styling from `AllFeaturedTables` as this has been replaced by the `govuk-width-container` applied to the `DataSetContent` container div.
=> EES-4048 Tweak font sizes and remove unneeded grid columns from data set step

src/explore-education-statistics-common/src/components/form/FormCheckboxSearchGroup.module.scss
This fix prevents the entire browser window from overflowing when there are many filter options in any of table tool's checkbox groups. 
This was primarily being caused by the the checkbox groups containing visually hidden text. Visually hidden elements are absolutely positioned and for some reason, this causes height calculations to break out of the nearest overflow context (i.e. the checkbox group) and target the entire browser window.
Interestingly, the issue was only present in Chromium browsers (not Firefox) so there may be a bug here or divergence in how the browsers calculate height. Either way, this can just be fixed by adding `position: relative` to the checkbox group container.
=> EES-4157 Fix window overflow when many filter options in table tool

src/explore-education-statistics-frontend/src/pages/api/permalink.ts
This PR increases the body size limit of the frontend `CreatePermalinkTable` endpoint.
See [Custom config](https://nextjs.org/docs/pages/building-your-application/routing/api-routes#custom-config).
[EES-4247](https://dfedigital.atlassian.net/browse/EES-4247) will establish if this limit needs to be any higher, and if we should compress the request between the backend and the frontend, but for now to attempt creating Permalink snapshots where the table request is any bigger than 1mb we need to increase this limit.
=> EES-4236 Increase the body size limit of the FE CreatePermalinkTable endpoint

src/GovUk.Education.ExploreEducationStatistics.Data.Api.Tests/Services/PermalinkServiceTests.cs, src/GovUk.Education.ExploreEducationStatistics.Data.Api.Tests/Services/__snapshots__/PermalinkServiceTests.MigratePermalink_SubjectMetaHasNoLocationIds_csv.snap, src/GovUk.Education.ExploreEducationStatistics.Data.Api.Tests/Services/__snapshots__/PermalinkServiceTests.MigratePermalink_SubjectMetaHasNoLocationIds_json.snap, src/GovUk.Education.ExploreEducationStatistics.Data.Api/Services/PermalinkService.cs
This PR fixes a bug where the `MapCsvRow` method needs to check for both the presence of a `observation.locationId`, AND locations returned from the table subject meta.
There's a scenario where a permalink table subject meta has no location id's but the observations do have location id's.
This is the case for Permalinks created in the window between deploying #3182 (EES-3203) which added location id's into the
`ObservationViewModel`, and #3196 (EES-2955) which added location id's to the subject meta locations.
=> 🐛 EES-4282 Fix bug handling scenario where table subject meta has no location

src/GovUk.Education.ExploreEducationStatistics.Data.Api.Tests/Services/PermalinkCsvMetaServiceTests.cs, src/GovUk.Education.ExploreEducationStatistics.Data.Api/Services/PermalinkCsvMetaService.cs, src/GovUk.Education.ExploreEducationStatistics.Data.Services/ViewModels/Meta/FilterCsvMetaViewModels.cs, src/GovUk.Education.ExploreEducationStatistics.Data.Services/ViewModels/Meta/FilterMetaViewModels.cs, src/GovUk.Education.ExploreEducationStatistics.Data.Services/ViewModels/Meta/IndicatorCsvMetaViewModel.cs, src/GovUk.Education.ExploreEducationStatistics.Data.Services/ViewModels/Meta/IndicatorMetaViewModels.cs
This PR fixes table CSV generation for Permalinks created before EES-613 change #1572  was deployed.
This bug affects early permalinks - approximately the first month of permalinks created in Prod after the service went live.
Prior to EES-613, `FilterMetaViewModel` and `IndicatorMetaViewModel` had no `Name` property which is used by CSV generation for the filter/indicator column names.
These early permalinks currently fail with server error 500 when selecting the Download table ‘Table in CSV format’ option.
We add a fallback for the filter and indicator view model names to use snake case of the label instead.
- Change `FilterMetaViewModel.Legend` to be not nullable.
=> EES-4318 Fix table CSV generation for Permalinks created before EES-613

src/GovUk.Education.ExploreEducationStatistics.Admin/Migrations/ContentMigrations/ContentDbContextModelSnapshot.cs
Corrects the type of `LastProcessedRowIndex` in `ContentDbContextModelSnapshot`.
=> EES-4192 Fix `ContentDbContextModelSnapshot` for nullable `LastProcessedRowIndex`

src/explore-education-statistics-common/src/modules/charts/components/MapBlockInternal.tsx, src/explore-education-statistics-common/src/styles/utils/_text.scss
Adds a util class for `word-break: break-word` and applies it to the key heading on maps to prevent text overflowing.
=> EES-3251 force text wrapping on map key

useful-scripts/permalink-snapshot-migration/.gitignore, useful-scripts/permalink-snapshot-migration/migrate_legacy_permalinks.py, useful-scripts/permalink-snapshot-migration/time_permalink_requests.py
This PR adds a new python script `time_permalink_requests.py` which can be used to measure the response times for permalinks.
It's the script which has already been used to measure the response times of the permalinks identified in [EES-4247](https://dfedigital.atlassian.net/browse/EES-4247) and will be used in future to measure the response times when they are migrated to snapshot format.
- Remove the `ignored` column from the `migrate_legacy_permalink.py` script.
=> EES-4247 Permalink request timing script

src/explore-education-statistics-common/src/services/permalinkService.ts, src/explore-education-statistics-common/src/services/util/permalinkServiceUtils.ts, src/explore-education-statistics-frontend/src/modules/api/permalink/createPermalinkTable.ts
When the create permalink table api endpoint was added we didn’t include the code to deduplicate locations for old permalinks. This adds it so the old permalinks with duplicate locations will display correctly.
=> EES-4340 add locations dedupe code to createPermalinkTable endpoint

src/explore-education-statistics-frontend/src/pages/accessibility-statement.tsx
This is a simple text based update to update the accessibility statement page, based on the latest DAC report and fixes we have made since then.
Also a few minor typographic styling header size tweaks have been made to make it consistent with the latest GDS accessibility statement template
Text updates
------------------
=> Updated accessibility statement

src/explore-education-statistics-frontend/src/pages/help-support.tsx
This change is a review and update of the help and support page. It was last refreshed early in the project so still had references to GOV.UK and us not having all of the publications on the service. I've updated the text for this page.
I've not got npm installed, so haven't run the npm ci commands or edited tests as suggested in the PR template, and it's also worth double checking formatting around the text that's been added.
=> EES-4169 Update help and support page

src/explore-education-statistics-frontend/web.config
This PR changes the value of `maxAllowedContentLength` from the default value of `30000000`  to `78643200` bytes for creating permalink snapshots. That's an increase from 28.6mb to 75mb.
See [Request Limits](https://learn.microsoft.com/en-us/iis/configuration/system.webServer/security/requestFiltering/requestLimits/#configuration).
This is being done to allow creating permalink snapshots with a frontend request body content length above the current max limit of 28.6mb.
This follows a change already made by https://github.com/dfe-analytical-services/explore-education-statistics/pull/4086 which has been effective when running locally but not effective in Azure environments where we use iisnode to host the node.js application in IIS.
=> EES-4345 Increase `maxAllowedContentLength` of public frontend service

src/explore-education-statistics-frontend/web.config
This PR fixes the position of the `requestLimits` element following on from https://github.com/dfe-analytical-services/explore-education-statistics/pull/4097.
See [Request Limits](https://learn.microsoft.com/en-us/iis/configuration/system.webServer/security/requestFiltering/requestLimits/#configuration).
=> 🐛 EES-4345 Fix position of `requestLimits` element.

infrastructure/parameters/dev.parameters.json, infrastructure/parameters/pre-prod.parameters.json, infrastructure/parameters/prod.parameters.json, infrastructure/parameters/test.parameters.json, infrastructure/templates/template.json
This PR updates the `devopsSPN` parameter used in the ARM template to the new SPNs' objectIds.
One thing to note is that previously both preprod and prod were using the same SPN. Now they are not.
=> EES-4323 Update devopsSPN values to new SPNs' objectIds

src/GovUk.Education.ExploreEducationStatistics.Admin.Tests/Services/DataBlockServiceTests.cs, src/GovUk.Education.ExploreEducationStatistics.Admin/Services/DataBlockService.cs, src/GovUk.Education.ExploreEducationStatistics.Admin/ViewModels/DataBlockViewModels.cs, src/explore-education-statistics-admin/src/components/Page.tsx, src/explore-education-statistics-admin/src/pages/release/__data__/testEditableRelease.ts, src/explore-education-statistics-admin/src/pages/release/content/contexts/__tests__/ReleaseContentContext.test.tsx, src/explore-education-statistics-admin/src/pages/release/datablocks/ReleaseDataBlockEditPage.tsx, src/explore-education-statistics-admin/src/pages/release/datablocks/__tests__/ReleaseDataBlockEditPage.test.tsx, src/explore-education-statistics-admin/src/pages/release/datablocks/components/DataBlockPageTabs.tsx, src/explore-education-statistics-admin/src/pages/release/datablocks/components/__tests__/DataBlockPageTabs.test.tsx, src/explore-education-statistics-admin/src/pages/release/pre-release/__tests__/PreReleaseTableToolPage.test.tsx, src/explore-education-statistics-admin/src/services/dataBlockService.ts, src/explore-education-statistics-common/src/components/Banner.tsx, src/explore-education-statistics-common/src/modules/find-statistics/components/__tests__/DataBlockTabs.test.tsx, src/explore-education-statistics-common/src/services/types/blocks.ts, src/explore-education-statistics-frontend/src/tsconfig.json, tests/robot-tests/tests/admin_and_public/bau/publish_content.robot, tests/robot-tests/tests/admin_and_public_2/bau/publish_amend_and_cancel.robot, tests/robot-tests/tests/admin_and_public_2/bau/publish_release_and_amend.robot, tests/robot-tests/tests/libs/admin-common.robot
This PR:
* amends the data block page to display the data set name of a given data block. 
Other changes:
* Amended UI tests to check for this new field
* Added a new keyword to close the admin survey banner due to it causing intermittent failures in various suites
=> EES-4049 - add data file info to view datablock page

src/GovUk.Education.ExploreEducationStatistics.Admin/Controllers/Api/FeaturedTableController.cs, src/GovUk.Education.ExploreEducationStatistics.Data.Api.Tests/Controllers/PublicationControllerTests.cs, src/GovUk.Education.ExploreEducationStatistics.Data.Services/ReleaseService.cs, src/GovUk.Education.ExploreEducationStatistics.Data.Services/ViewModels/FeaturedTableViewModel.cs, src/explore-education-statistics-admin/src/pages/release/datablocks/ReleaseDataBlocksPage.tsx, src/explore-education-statistics-admin/src/pages/release/datablocks/__tests__/ReleaseDataBlocksPage.test.tsx, src/explore-education-statistics-admin/src/pages/release/datablocks/components/FeaturedTablesTable.tsx, src/explore-education-statistics-admin/src/pages/release/pre-release/__tests__/PreReleaseTableToolPage.test.tsx, src/explore-education-statistics-admin/src/queries/dataBlockQueries.ts, src/explore-education-statistics-admin/src/queries/featuredTableQueries.ts, src/explore-education-statistics-admin/src/queries/permissionQueries.ts, src/explore-education-statistics-admin/src/services/dataBlockService.ts, src/explore-education-statistics-common/src/modules/table-tool/components/DataSetStep.tsx, src/explore-education-statistics-common/src/modules/table-tool/components/__tests__/DataSetStep.test.tsx, src/explore-education-statistics-common/src/services/tableBuilderService.ts, tests/robot-tests/tests/admin/bau/create_data_block_with_chart.robot, tests/robot-tests/tests/admin_and_public/bau/publish_data.robot, tests/robot-tests/tests/admin_and_public_2/bau/publish_amend_and_cancel.robot, tests/robot-tests/tests/admin_and_public_2/bau/publish_release_and_amend.robot
Adds the ability to reorder featured tables:
- on the data blocks tab featured tables are split out into their own table and can be reordered
- the order is reflected in the data set step of the table tool
Also:
- I made a couple of backend tweaks to fix the endpoint and expose the order to the frontend
- I've replaced `useAsyncHandledRetry` with `react-query` in `ReleaseDataBlocksPage`
**Data blocks tab**
**Reordering**
=> EES-4090 reorder featured tables

tests/robot-tests/run_tests.py
This PR:
* logs the body to the console if a SlugNotUnique error is encountered
=> EES-4392 - log info if SlugNotUnique error is thrown

renovate.json
This PR:
* implements automated dependency upgrade management via [renovate](https://renovatebot.com/). 
For now, we've decided to disable renovate running on the frontend packages until the majority of the frontend dependencies have been upgraded.
At the moment the latest version of `renovate` isn't compatible with the version of node that the project is on so I've decided to not add a pre-commit hook to validate the `renovate.json` file with `renovate-config-validator`. If the config is invalid, an issue will be created via renovate to let us know that something is wrong with the renovate config
⚠️IMPORTANT NOTE⚠️
* It's very important to note that if you push to a given branch that renovate has created, renovate will force push your changes away. This means that if you have to fix up a …
=> EES-4020 - implement automated dependency upgrades

renovate.json
This PR:
* fixes the renovate config by removing an incompatible rule in the `packageRules` field. To disable python updates, we've instead added an object outside of the `packageRules` field to tell renovate not to attempt to upgrade python dependencies
=> EES-4396 - fix renovate config

tests/performance-tests/README.md, tests/performance-tests/src/configuration/rampingRequestRateProfile.ts, tests/performance-tests/src/configuration/sequentialRequestsProfile.ts, tests/performance-tests/src/configuration/spikeProfile.ts, tests/performance-tests/src/configuration/steadyRequestRateProfile.ts, tests/performance-tests/src/tests/public/getReleasePage.test.ts, tests/performance-tests/src/utils/utils.ts
This PR:
- corrects some of the K6 load parameter types to accept floats rather than just ints
- adds support for choosing a "standard" load profile from the `getReleasePage.test.ts`
- updates the README with details around test options
=> EES-4332 - K6 improvements

src/GovUk.Education.ExploreEducationStatistics.Admin.Tests/Services/ReleaseChecklistServiceTests.cs, src/GovUk.Education.ExploreEducationStatistics.Admin/Services/ReleaseChecklistService.cs, src/GovUk.Education.ExploreEducationStatistics.Admin/Validators/ValidationErrorMessages.cs, src/explore-education-statistics-admin/src/pages/release/components/ReleaseStatusChecklist.tsx, src/explore-education-statistics-admin/src/pages/release/components/__tests__/ReleaseStatusChecklist.test.tsx, src/explore-education-statistics-admin/src/services/releaseService.ts, tests/robot-tests/tests/admin/analyst/edit_and_approve_release_as_publication_approver.robot, tests/robot-tests/tests/admin/analyst/role_ui_permissions/release_and_publication_role_end_to_end_permissions.robot, tests/robot-tests/tests/admin/bau/create_methodology_amendment.robot, tests/robot-tests/tests/admin/bau/prerelease_and_amend.robot, tests/robot-tests/tests/admin/bau/release_status.robot, tests/robot-tests/tests/admin_and_public/bau/archive_publication.robot, tests/robot-tests/tests/admin_and_public/bau/data_catalogue.robot, tests/robot-tests/tests/admin_and_public/bau/data_reordering.robot, tests/robot-tests/tests/admin_and_public/bau/legacy_releases.robot, tests/robot-tests/tests/admin_and_public/bau/prerelease_visibility.robot, tests/robot-tests/tests/admin_and_public/bau/publish_content.robot, tests/robot-tests/tests/admin_and_public/bau/publish_data.robot, tests/robot-tests/tests/admin_and_public/bau/publish_methodology.robot, tests/robot-tests/tests/admin_and_public/bau/publish_publication_update.robot, tests/robot-tests/tests/admin_and_public/bau/subject_reordering.robot, tests/robot-tests/tests/admin_and_public_2/bau/publish_amend_and_cancel.robot, tests/robot-tests/tests/admin_and_public_2/bau/publish_release_and_amend_2.robot, tests/robot-tests/tests/libs/admin/manage-content-common.robot
This PR adds a checklist warning if a release has no key statistic or headline text block, preventing the user from publishing the release. The UI tests have been updated so that they pass given this change.
There is one failing UI test unrelated to this ticket. This will be fixed in EES-4393.
=> EES-4195 Add checklist warning if release has no key stat or headline text block

src/GovUk.Education.ExploreEducationStatistics.Common/Model/Chart/ChartAxisConfiguration.cs, src/explore-education-statistics-admin/src/pages/release/datablocks/components/chart/ChartAxisConfiguration.tsx, src/explore-education-statistics-admin/src/pages/release/datablocks/components/chart/ChartReferenceLinesConfiguration.tsx, src/explore-education-statistics-admin/src/pages/release/datablocks/components/chart/__tests__/ChartReferenceLinesConfiguration.test.tsx, src/explore-education-statistics-common/src/modules/charts/components/HorizontalBarBlock.tsx, src/explore-education-statistics-common/src/modules/charts/components/LineChartBlock.tsx, src/explore-education-statistics-common/src/modules/charts/components/VerticalBarBlock.tsx, src/explore-education-statistics-common/src/modules/charts/components/utils/__tests__/getReferenceLineLabelPosition.test.ts, src/explore-education-statistics-common/src/modules/charts/components/utils/createReferenceLine.tsx, src/explore-education-statistics-common/src/modules/charts/components/utils/getReferenceLineLabelPosition.ts, src/explore-education-statistics-common/src/modules/charts/types/chart.ts
Adds the ability to create a reference line between two data points, for example to explain why there's a gap in the chart:
When adding a reference line on the major axis:
- you can now select 'Between data points' in the Position dropdown
- this reveals dropdowns for start and end points for the line
- you can adjust the other axis position, label and style as normal.
=> EES-4362 add reference lines between two points

infrastructure/templates/template.json
This PR: 
* Fixes the recent deployment issues after the switchover to the hybrid container app service plan for the public frontend. This problem stemmed from the fact that we didn't have `reserved` set to true in the public app's service plan and site settings. If you use Linux then `reserved` needs to always be set to true (see https://learn.microsoft.com/en-us/troubleshoot/azure/app-service/faqs-app-service-linux#how-can-i-create-a-linux-app-service-plan-through-an-sdk-or-an-azure-resource-manager-template- and https://github.com/hashicorp/terraform-provider-azurerm/issues/3379 for more details)
=> EES-4398 - fix deployment of public app via docker

src/explore-education-statistics-admin/src/components/PageHeader.tsx, src/explore-education-statistics-frontend/src/components/PageHeader.tsx
Alternative text for the <img> element has text that duplicates the existing text.
Element Location:
.govuk-header__logotype-crown-fallback-image
=> EES-4400 : Accessibility -Alt-text should not be repeated

infrastructure/templates/template.json
This PR:
* Removes the prototype PNPM app from the allowed cors origins since it is no longer being used
=> EES-4398 - remove prototype PNPM app from cors allow list

src/GovUk.Education.ExploreEducationStatistics.Admin.Tests/Resources/FilterMigrationFiles/blank-filter-label.meta.csv, src/GovUk.Education.ExploreEducationStatistics.Admin.Tests/Resources/FilterMigrationFiles/blank-filter-name.meta.csv, src/GovUk.Education.ExploreEducationStatistics.Admin.Tests/Resources/FilterMigrationFiles/test-data.meta.csv, src/GovUk.Education.ExploreEducationStatistics.Admin.Tests/Services/FilterMigrationServicePermissionTests.cs, src/GovUk.Education.ExploreEducationStatistics.Admin.Tests/Services/FilterMigrationServiceTests.cs, src/GovUk.Education.ExploreEducationStatistics.Admin/Controllers/Api/Bau/FilterMigrationController.cs, src/GovUk.Education.ExploreEducationStatistics.Admin/Services/FilterMigrationService.cs, src/GovUk.Education.ExploreEducationStatistics.Admin/Services/Interfaces/IFilterMigrationService.cs, src/GovUk.Education.ExploreEducationStatistics.Admin/Startup.cs, src/GovUk.Education.ExploreEducationStatistics.Admin/ViewModels/FilterMigrationReport.cs, src/GovUk.Education.ExploreEducationStatistics.Common.Tests/Extensions/MockBlobStorageServiceExtensions.cs, src/GovUk.Education.ExploreEducationStatistics.Common/Utils/CsvUtils.cs, src/GovUk.Education.ExploreEducationStatistics.Data.Model.Tests/Fixtures/FilterGeneratorExtensions.cs, src/GovUk.Education.ExploreEducationStatistics.Data.Model.Tests/Fixtures/FilterGroupGeneratorExtensions.cs, src/GovUk.Education.ExploreEducationStatistics.Data.Model.Tests/Fixtures/IndicatorGroupGeneratorExtensions.cs, src/GovUk.Education.ExploreEducationStatistics.Data.Model/FilterGroup.cs, src/GovUk.Education.ExploreEducationStatistics.Data.Processor/Models/FilterAndIndicatorValuesReader.cs
⚠️ This has an associated faffy deploy ticket [EES-4371](https://dfedigital.atlassian.net/browse/EES-4371) ⚠️ 
This PR adds a migration endpoint which copies `filter_grouping_column` from all meta csv files for every filter which has non-default groups.
This follows the change made by #4112 which added a new field `GroupCsvColumn` to `Filter` and began setting the value for every filter with non-default filter groups when importing data. 
When importing data, filters which are defined in the meta csv file without a value for `filter_grouping_column` will have their filter items added to a single filter group labelled "Default".
The `filter_grouping_column` in the meta csv file allows analysts to define  the name of a column to be found in the data csv file which contains the group for …
=> EES-4364 - Migrate all existing data sets filters to have group csv column values

infrastructure/templates/template.json
This PR follows https://github.com/dfe-analytical-services/explore-education-statistics/pull/4173.
It changes the `dependsOn` to reference the container registry resource which is in a nested deployment template and potentially in an alternate resource group, by providing the subscription id and resource group name.
This attempts to fix the deployment error `Deployment template validation failed: 'The resource 'Microsoft.ContainerRegistry/registries/eesacr' is not defined in the template.`
=> EES-4398 Change `dependsOn` to reference resource in alternate resource group

package.json
This PR:
* reintroduces the `check-node-version` responsible for restraining what PNPM + node version everyone is allowed to use on the project. This was previously removed due to the fact that PNPM comes with this functionality out of the box via the `engines` field. It's been discovered that while this is respected and works as expected on Linux + Mac, Windows bypasses this restriction and lets you use whatever Node + PNPM version you want. To prevent this, We've reintroduced `check-node-version` which works cross-platform
=> EES-4415 - reintroduce check-node-version

infrastructure/templates/template.json
This PR follows https://github.com/dfe-analytical-services/explore-education-statistics/pull/4174.
It changes the `dependsOn` to reference the container registry nested deployment.
=> EES-4398 Change `dependsOn` to reference the container registry nested deployment

infrastructure/templates/template.json
This PR removes the `dependsOn` which appears to not work when deploying the parent template to a different resource group than the nested template.
Providing this works, we'll have to look at alternative ways of making sure the container registry exists.
=> EES-4398 Remove dependsOn for shared container registry deployment

azure-pipelines.dfe.yml, docker/Dockerfile.public-frontend
This PR: 
* fixes the build number not being displayed on the public frontend. This stemmed from it not being explicitly set when the docker image is built
=> EES-4420 - fix build number environment variable not being set

azure-pipelines.dfe.yml
This PR:
* attempts to fix the `BUILD_BUILDNUMBER` environment variable not being set for the public frontend. based on the comment on https://blog.geralexgr.com/docker/pass-secrets-as-env-variables-on-docker-build-azure-devops, this should fix it
=> EES-4420 - attempt to fix build number environment var not being set

infrastructure/parameters/dev.parameters.json
This PR:
* Temporarily changes the `maxTableCellsAllowed` to 3 million for the development environment. We're temporarily changing this to test how the new hybrid Linux container app service behaves when Next.js is doing heaving lifting when server-side rendering on content-heavy pages such as the table tool page and permalink page
=> EES-3976 - change dev max table cells to 3 million

infrastructure/parameters/dev.parameters.json
This PR: reverts the changes made in https://github.com/dfe-analytical-services/explore-education-statistics/pull/4183 after the testing of EES-3976
=> EES-3976 - change max table cell size back to default for dev

pnpm-lock.yaml, src/explore-education-statistics-common/package.json, src/explore-education-statistics-common/src/modules/table-tool/utils/Header.ts, src/explore-education-statistics-common/src/modules/table-tool/utils/__data__/testTableData.ts, src/explore-education-statistics-common/src/modules/table-tool/utils/__data__/testTableDataWithDuplicateLabels.ts, src/explore-education-statistics-common/src/modules/table-tool/utils/__data__/testTableDataWithMergedCells.ts, src/explore-education-statistics-common/src/modules/table-tool/utils/__tests__/createExpandedColumnHeaders.test.ts, src/explore-education-statistics-common/src/modules/table-tool/utils/__tests__/createExpandedRowHeaders.test.ts, src/explore-education-statistics-common/src/modules/table-tool/utils/__tests__/mapTableToJson.test.ts, src/explore-education-statistics-common/src/modules/table-tool/utils/__tests__/utils/debugTable.tsx, src/explore-education-statistics-common/src/modules/table-tool/utils/createExpandedColumnHeaders.ts, src/explore-education-statistics-common/src/modules/table-tool/utils/createExpandedRowHeaders.ts, src/explore-education-statistics-common/src/modules/table-tool/utils/mapTableToJson.ts, src/explore-education-statistics-common/test/openPlaygroundUrl.ts
The permalinks snapshot testing found two discrepancies in the table html which exposed bugs related to having filters and filter groups with the same name.
After this fix goes in there will still be a difference in the table html as the rowspans were wrong in the before version as well.
Permalink id: 4a378c3c-6443-4af8-393f-08db371965b6
Here the `All state-funded mainstream institutions` filter is in filter group `All state-funded mainstream institutions` and `All institutions that are not academies` is in the filter group `All institutions that are not academies`, this caused the scope to be incorrectly set to `colgroup` in the after version (using table Json). In both the before and after versions the `rowspan` was incorrectly set to 2. 
Permalink before and after diff:
With this fix …
=> EES-4358 Fix table html for filter name related bugs

src/GovUk.Education.ExploreEducationStatistics.Admin.Tests/Services/ReleaseServiceAmendmentTests.cs, src/GovUk.Education.ExploreEducationStatistics.Content.Model/Extensions/ReleaseAmendmentExtensions.cs, tests/robot-tests/tests/admin/bau/create_data_block_with_chart.robot, tests/robot-tests/tests/admin/bau/prerelease_and_amend.robot, tests/robot-tests/tests/admin_and_public_2/bau/publish_release_and_amend.robot, tests/robot-tests/tests/libs/charts.robot
Previously, when amending a release with a public prerelease list, that list would be removed from the amendment, leaving it with no public prerelease list initially.
This PR changes this behaviour so that amendments now have a copy of the previous release's public prerelease list.
I also fixed a UI test unrelated to these changes that were causing a failure in `create_data_block_with_chart.robot` in `Validate basic line chart preview` on the line `user mouses over line chart point    id:chartBuilderPreview    1    1`. I switched to using an xpath selector to avoid `nth-of-type` and how it selects tags not classes.
=> EES-4422 Copy public prerelease list when creating an amendment

src/explore-education-statistics-admin/src/pages/release/datablocks/components/chart/ChartConfiguration.tsx, src/explore-education-statistics-common/src/modules/charts/components/HorizontalBarBlock.tsx, src/explore-education-statistics-common/src/modules/charts/components/VerticalBarBlock.tsx, src/explore-education-statistics-common/src/modules/charts/components/__tests__/VerticalBarBlock.test.tsx, src/explore-education-statistics-common/src/utils/colour/__tests__/getAccessibleTextColour.test.ts, src/explore-education-statistics-common/src/utils/colour/getAccessibleTextColour.ts
Labels placed inside bars in charts can have insufficient colour contrast, to try to prevent this we:
- check the contrast between the text and background colour, if the contrast isn't good enough then change the text colour to white.
- remove the option to place labels inside vertical bars as the text is likely to overflow the bar making it difficult to find a text colour with sufficient contrast for the bar colour and the white background.
=> EES-4256 accessible colour for bar chart data labels

src/explore-education-statistics-admin/src/pages/users/components/InviteUserPublicationRoleForm.tsx, src/explore-education-statistics-admin/src/pages/users/components/InviteUserReleaseRoleForm.tsx, src/explore-education-statistics-admin/src/prototypes/components/PrototypePublicationForm.tsx, src/explore-education-statistics-admin/src/services/hubs/utils/retryPolicies.ts, src/explore-education-statistics-common/src/modules/table-tool/components/PublicationForm.tsx, src/explore-education-statistics-frontend/src/modules/methodologies/MethodologyIndexPage.tsx, src/explore-education-statistics-frontend/src/modules/methodologies/__tests__/MethodologyIndexPage.test.tsx
This PR fixes a bug where methodologies could appear multiple times on the public Methodologies page if a single methodology was associated with multiple publications under the same theme.
I went with the simplest fix for this issue. I did consider updating the  `GET /methodology-themes` call in the backend, since I believe we only use this endpoint for the Methodologies page, and since we now only group methodologies by theme, there is no reason for the backend to return methodologies grouped by theme -> topic -> publication.
I discussed this with Dunc. This endpoint will be changed if/when remove topics (as part of EES-4260) so I believe it's ok to leave this for now. If others disagree, I'm happy to discuss / change the approach.
=> EES-4425 Prevent duplicate methodologies appearing on public Methodologies page

src/explore-education-statistics-admin/src/pages/methodology/edit-methodology/status/MethodologyStatusPage.tsx
This fixes an issue where the Methodology status history table wasn't being refreshed after submitting the form on the `MethodologyStatusPage`. Previously, you had to refresh the page for the new status history table entries to appear.
=> EES-4385 Refetch methodology statuses on MethodologyStatusPage submit

tests/robot-tests/tests/admin/bau/adopt_methodology.robot, tests/robot-tests/tests/admin/bau/invite_new_users.robot, tests/robot-tests/tests/admin/bau/manage_users_page.robot, tests/robot-tests/tests/admin/bau/prerelease.robot, tests/robot-tests/tests/admin/bau/upload_files.robot, tests/robot-tests/tests/admin_and_public/bau/prerelease_visibility.robot, tests/robot-tests/tests/admin_and_public/bau/subject_reordering.robot, tests/robot-tests/tests/admin_and_public_2/bau/publish_release_and_amend_2.robot, tests/robot-tests/tests/general_public/statistics_page.robot, tests/robot-tests/tests/libs/admin-common.robot, tests/robot-tests/tests/libs/admin/analyst/role_ui_permissions.robot, tests/robot-tests/tests/libs/common.robot, tests/robot-tests/tests/libs/public-common.robot
This PR adds more UI tests around prerelease access for methodologies.
- Add a content section / content block to the prerelease methodology in `prerelease.robot`
- Check an adopted methodology appears correctly in prerelease in `adopt_methodology.robot`
- Check a methodology doesn't appear publically during prerelease in `prerelease_visibility.robot`
Other things are checked during these things, such as that a methodology correctly publishes alongside a specific release if that publishing strategy was chosen for the methodology.
This work was undertaken in response to the bug EES-4379. As a side note, the `Create and validate methodology` test case in `prerelease.robot` previously failed to spot this bug because the created methodology to test prerelease had no content sections/content …
=> EES-4380 Add more UI tests around methodology prerelease

src/explore-education-statistics-frontend/next.config.js
We're enabling this to investigate an issue with prerelease_visibility.robot where the `Check methodology has been published` test case is failing. It appears to click the link to the methodology, the link gets highlighted, but the browser doesn't actually go to the page. This seems to only happen inside a webdriver-created window.
=> Enable productionBrowserSourceMaps for public frontend

src/GovUk.Education.ExploreEducationStatistics.Admin.Tests/Services/GlossaryServiceTests.cs, src/GovUk.Education.ExploreEducationStatistics.Admin/Controllers/Api/GlossaryController.cs, src/GovUk.Education.ExploreEducationStatistics.Admin/Services/GlossaryService.cs, src/GovUk.Education.ExploreEducationStatistics.Admin/Services/Interfaces/IGlossaryService.cs, src/GovUk.Education.ExploreEducationStatistics.Common/ViewModels/GlossaryViewModels.cs, src/GovUk.Education.ExploreEducationStatistics.Content.Api.Tests/Controllers/GlossaryControllerTests.cs, src/GovUk.Education.ExploreEducationStatistics.Content.Api/Controllers/GlossaryController.cs, src/GovUk.Education.ExploreEducationStatistics.Content.Model.Tests/Utils/GlossaryUtilsTests.cs, src/GovUk.Education.ExploreEducationStatistics.Content.Model/Utils/GlossaryUtils.cs, src/GovUk.Education.ExploreEducationStatistics.Content.Services.Tests/Cache/GlossaryCacheServiceTests.cs, src/GovUk.Education.ExploreEducationStatistics.Content.Services.Tests/GlossaryServiceTests.cs, src/GovUk.Education.ExploreEducationStatistics.Content.Services/Cache/GlossaryCacheService.cs, src/GovUk.Education.ExploreEducationStatistics.Content.Services/GlossaryService.cs, src/GovUk.Education.ExploreEducationStatistics.Content.Services/Interfaces/IGlossaryService.cs
This PR adds a new method to the Admin glossary controller to get the glossary.
This is largely a duplicate of the code in the Public glossary controller to get the glossary, with the exception of the code to build the glossary which is made common.
This PR also:
- Renames `GetAllGlossaryEntries` methods to `GetGlossary` since they return a list of categories rather than entries which collectively make up the glossary.
- Changes `GlossaryEntryViewModel` and `GlossaryCategoryViewModel` from `class` to `record` types.
- Changes `GlossaryCategoryViewModel.Heading` from `string` to `char` since we expect this to be a single character in the range A-Z.
- Adds new `GlossaryUtils.BuildGlossary(IReadOnlyList<GlossaryEntry> entries)` to build a glossary for a list of entries which is common to …
=> EES-4441 Add Admin endpoint to get glossary

src/explore-education-statistics-frontend/next.config.js
This undoes the change made in https://github.com/dfe-analytical-services/explore-education-statistics/pull/4205
This should be merged before the next cut to master.
=> Disable productionBrowserSourceMaps for public frontend

tests/robot-tests/tests/general_public/table_tool_exclusions_by_geographic_level.robot
Fixing UI tests with the keywords -Validate the query could exceed the maximum allowable table size-
Changed the fie size for the release 'Exclusions by geographic level' to match with that on Dev.
=> Fixing UI test failure in general_public suite

src/explore-education-statistics-common/src/modules/table-tool/utils/__data__/testTableDataWithMergedCells.ts, src/explore-education-statistics-common/src/modules/table-tool/utils/__tests__/createExpandedColumnHeaders.test.ts, src/explore-education-statistics-common/src/modules/table-tool/utils/__tests__/createExpandedRowHeaders.test.ts, src/explore-education-statistics-common/src/modules/table-tool/utils/__tests__/mapTableToJson.test.ts, src/explore-education-statistics-common/src/modules/table-tool/utils/createExpandedRowHeaders.ts
The permalink migration testing exposed problems caused by our earlier table fixes in https://github.com/dfe-analytical-services/explore-education-statistics/pull/4110
The previous fix corrected row headers when there are collapsed cells (because of duplicate labels), it did this by checking if all the headers at a level were collapsed, so didn't need to span across 2 columns. However it only checked against other headers in the current `rowHeader` (A or B in the below example), it didn't take into account that rows which are excluded because of missing data could mean that all the headers are collapsed at a level in some rowHeaders but not in others. 
Example: there isn't any data for B > E > F/G so those rows have been excluded from the table, meaning that for B all the headers at level …
=> EES-4450 fix table rendering when data is missing

.eslintignore, .prettierignore, .stylelintignore, azure-pipelines-ui-tests.dfe.yml, azure-pipelines.dfe.yml
This PR switches the build pipelines to use our self-hosted runner pools:
- `ees-ubuntu2204-large` - 4 vCPUs, 16GB RAM
- `ees-ubuntu2204-xlarge` - 8 vCPUs, 32GB RAM
Note that:
- In some cases, we just use the default Microsoft runners as the tasks aren't very demanding and these runners can spin up really quickly from cold.
- The UI test pipeline has been throttled at 3 processors per test run for now in case it causes more flakiness. We can look into changing this further after some more testing.
=> EES-4352 Switch pipelines to self-hosted runners

.github/workflows/codeql.yml, azure-pipelines-ui-tests.dfe.yml, azure-pipelines.dfe.yml
This PR:
- Changes CodeQL to only run on commits to `dev`
- Cleans up the entire workspace before running any jobs to avoid artifacts and state leaking between builds
- Remove an unnecessary format step on the `Admin` job
- Prevents the Docker build tasks from running on manual triggers
=> EES-4352 Improvements to build pipeline

src/GovUk.Education.ExploreEducationStatistics.Notifier/GovUk.Education.ExploreEducationStatistics.Notifier.csproj
This PR fixes an error occurring in the Notifier function project when subscribing to a publication.
The error was occurring in TokenService.GenerateToken:L14:
`var securityKey = new SymmetricSecurityKey(Encoding.UTF8.GetBytes(secretKey));`
Exception:
`Could not load file or assembly 'Microsoft.IdentityModel.Tokens, Version=6.32.1.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'. The system cannot find the file specified.`
It was caused by the dependency upgrades in #4214, specifically the upgrade to `System.IdentityModel.Tokens.Jwt` from 6.9.0 to 6.32.1.
`System.IdentityModel.Tokens.Jwt` 6.32.1 has a dependency on `Microsoft.IdentityModel.Tokens` (>= 6.32.1). Without explicitly defining this dependency it appears to be picking up an older version 6.8.0 implicitly defined by other …
=> EES-4463 Fix Notifier subscriptions

docker/Dockerfile.public-frontend
This PR primarily fixes dependency hoisting being broken in the frontend Docker build due to not copying the `.npmrc` file.
Other changes:
- Made some performance improvements using cache mounts for the `pnpm install` steps
- Refactored build steps to use a common `base` step
- Removed unnecessary steps that were installing all dependencies
All these changes bring down the current image size down from ~1.2GB to 946MB.
=> EES-3409 Fix dependency hoisting in frontend Docker build

azure-pipelines.dfe.yml
This PR:
* Enables BuildKit for the docker build task. This is due to the introduction of cache mounts in `Dockerfile.public-frontend`
Full pipeline error: 
```
Step 15/42 : COPY src/tsconfig.json ./src/tsconfig.json
---> 6f397caddc58
Step 16/42 : RUN --mount=type=cache,id=pnpm,target=/pnpm/store     pnpm --filter=explore-education-statistics-frontend... --ignore-scripts --frozen-lockfile install
the --mount option requires BuildKit. Refer to https://docs.docker.com/go/buildkit/ to learn how to build images with BuildKit enabled
##[error]the --mount option requires BuildKit. Refer to https://docs.docker.com/go/buildkit/ to learn how to build images with BuildKit enabled
##[error]The process '/usr/bin/docker' failed with exit code 1
```
=> EES-3409 - enable buildkit for cache mounts in CI

src/explore-education-statistics-admin/src/pages/release/content/components/EditableKeyStatPreview.tsx, src/explore-education-statistics-admin/src/pages/release/content/components/KeyStatistics.tsx, src/explore-education-statistics-common/src/modules/find-statistics/components/KeyStat.module.scss, src/explore-education-statistics-common/src/modules/find-statistics/components/KeyStat.tsx
Changes Key Statistics so the widths are:
- when there's only one Key Stat, it's full width with centred text (I'll check Cam is ok with this before merging)
- when there are two or four Key Stats, they're half width
- any other number of Key Stats, they're one third width
Also, I renamed `column` / `hasColumn` to `wrapper` / `includeWrapper` as it's a wrapper around a single Key Stat rather that around a column of them.
=> EES-4447 adjust key stat widths

src/GovUk.Education.ExploreEducationStatistics.Notifier/GovUk.Education.ExploreEducationStatistics.Notifier.csproj
This PR makes a change to the Notifier functions project to include required dependencies which have been filtered out of the build.
The function project build performs a post build clean action which optimises the built output to remove any assemblies that are shared with the function host runtime.
The list of existing dependencies that will be filtered out by the clean includes `Microsoft.IdentityModel.Logging.dll`, `Microsoft.IdentityModel.Tokens.dll` and `System.IdentityModel.Tokens.Jwt.dll`.
This cleaning process works based on matching assemblies by name, not by version. This works and creates a smaller build, but causes a problem if the project depends on newer versions than those provided by the runtime.
It results in runtime exceptions like those we are seeing subscribing to …
=> EES-4463 Preserve function dependencies in build process

README.md, tests/robot-tests/README.md, tests/robot-tests/scripts/visual-testing/README.md
This PR updates the main README and makes some amends to the testing README
* Removes all references to previous VM and native azure storage emulator instructions
* Adds note on how to deal with libmagic on MacOS based machines
* Adds note on daily users used day to day with Keycloak
* Removes references to confluence for DBs due to the fact this isn't used anymore
=> EES-4459 - update README

src/GovUk.Education.ExploreEducationStatistics.Admin/Migrations/ContentMigrations/20230818085314_EES4483_AddMissingIndexes.Designer.cs, src/GovUk.Education.ExploreEducationStatistics.Admin/Migrations/ContentMigrations/20230818085314_EES4483_AddMissingIndexes.cs, src/GovUk.Education.ExploreEducationStatistics.Content.Model/Database/ContentDbContext.cs
This PR alters the columns of the following properties from type `nvarchar(max)` to `nvarchar(25)`and adds indexes to those fields to benefit database queries filtering on type.
- `File.Type`
- `ContentBlock.Type`
- `ContentSection.Type`
Columns with data type `nvarchar(max)` cannot be indexed.
=> EES-4483 Alter type columns from nvarchar(max) to nvarchar(25) and add indexes

src/GovUk.Education.ExploreEducationStatistics.Admin.Tests/Services/CommentServiceTests.cs, src/GovUk.Education.ExploreEducationStatistics.Admin/Mappings/MappingProfiles.cs, src/GovUk.Education.ExploreEducationStatistics.Admin/Migrations/ContentMigrations/20230817144249_EES4481_AlterCommentContentNotNull.Designer.cs, src/GovUk.Education.ExploreEducationStatistics.Admin/Migrations/ContentMigrations/20230817144249_EES4481_AlterCommentContentNotNull.cs, src/GovUk.Education.ExploreEducationStatistics.Admin/Services/ManageContent/CommentService.cs, src/GovUk.Education.ExploreEducationStatistics.Admin/Validators/ValidationErrorMessages.cs, src/GovUk.Education.ExploreEducationStatistics.Admin/ViewModels/CommentViewModel.cs, src/GovUk.Education.ExploreEducationStatistics.Admin/ViewModels/ManageContent/CommentSaveRequest.cs, src/GovUk.Education.ExploreEducationStatistics.Content.Model/Comment.cs
This PR improves the EF query efficiency getting comments and adding a new comment in the Admin `CommentService`.
It removes result set duplication by refactoring includes, splitting queries, and avoids returning content sections and blocks just check that a content block exists.
Previously, methods `GetComments` and `AddComment` both executed `CheckContentSectionExists` which in turn used method `HydrateContentSectionsAndBlocks`:
This method had a few different purposes:
- To allow checking a content block exists when navigated via the content sections and content blocks collections of the release.
- To include the comments of every content block. Only relevant to `GetComments`.
- To include the "created by" and "resolved by" users of each comment for populating the view model. Only …
=> EES-4481 Improved EF query efficiency getting comments.

src/explore-education-statistics-admin/src/components/editable/EditableContentBlock.module.scss, src/explore-education-statistics-admin/src/components/editable/EditableContentBlock.tsx, src/explore-education-statistics-admin/src/components/editable/EditableContentForm.module.scss, src/explore-education-statistics-admin/src/components/editable/EditableContentForm.tsx, src/explore-education-statistics-admin/src/types/ckeditor.ts, src/explore-education-statistics-common/src/components/ErrorSummary.tsx, src/explore-education-statistics-common/src/components/form/Form.tsx, src/explore-education-statistics-common/src/components/form/rhf/RHFForm.tsx, src/explore-education-statistics-common/src/styles/_content.scss, tests/robot-tests/tests/admin/bau/create_methodology_for_publication.robot, tests/robot-tests/tests/libs/admin/manage-content-common.robot
- Fixes the validation for images without alt text
- In addition to the standard error, it shows a warning message with a link to more info about writing alt text
- When editing a block, images without alt text are outline in red
- Adds a UI test to check the validation works
Also, fixes the bug where large images can overflow content blocks.
=> EES-4413 alt text validation

src/GovUk.Education.ExploreEducationStatistics.Admin.Tests/Services/Methodologies/MethodologyContentServiceTests.cs, src/GovUk.Education.ExploreEducationStatistics.Admin/Services/Methodologies/MethodologyContentService.cs, src/GovUk.Education.ExploreEducationStatistics.Admin/Validators/ValidationErrorMessages.cs
This PR changes the `MethodologyContentService` to always use `UserServiceExtensions.CheckCanUpdateMethodologyVersion` (which in turn uses `UpdateSpecificMethodologyAuthorizationHandler`) for checking permission to update methodology content unless the status  is `Approved` in which case a forbidden response is returned early.
Previously we returned a validation error early `MethodologyMustBeDraft` if the status was not `Draft`.
This resulted in a bug when the status was in `HigherLevelReview` where in certain circumstances already evaluated by the auth handler, users should still be able to update methodology content.
=> EES-4376 Defer to `CheckCanUpdateMethodologyVersion` to check permission updating methodology content

src/explore-education-statistics-admin/src/components/editable/EditablePageModeToggle.module.scss, src/explore-education-statistics-admin/src/components/editable/EditablePageModeToggle.tsx
The ‘Set page view’ panel on release content in the admin used to have a plus / minus icon on the top right, it’s disappeared as a result of the govuk-frontend update as the icon used, `govuk-accordion__icon`, no longer exists. This replaces it with the chevron icon used in the new accordions.
=> EES-4479 fix set page view panel icon

src/GovUk.Education.ExploreEducationStatistics.Common/Model/Chart/ChartAxisConfiguration.cs, src/explore-education-statistics-admin/src/pages/release/datablocks/components/chart/ChartAxisConfiguration.tsx, src/explore-education-statistics-admin/src/pages/release/datablocks/components/chart/ChartBuilder.tsx, src/explore-education-statistics-admin/src/pages/release/datablocks/components/chart/ChartLegendConfiguration.tsx, src/explore-education-statistics-admin/src/pages/release/datablocks/components/chart/__tests__/ChartAxisConfiguration.test.tsx, src/explore-education-statistics-common/src/modules/charts/components/HorizontalBarBlock.tsx, src/explore-education-statistics-common/src/modules/charts/components/VerticalBarBlock.tsx, src/explore-education-statistics-common/src/modules/charts/types/chart.ts, src/explore-education-statistics-common/src/modules/charts/util/__tests__/getDataSetCategoryConfigs.test.ts, src/explore-education-statistics-common/src/modules/charts/util/createDataSetCategories.ts, src/explore-education-statistics-common/src/modules/charts/util/getDataSetCategoryConfigs.ts
Currently using stacked bar charts when the chart is grouped by filters with filter groups doesn't work, you just get inidividual bars:
This PR adds an option to use filter groups in stacked bar charts. The option is added to the chart configuration tab and will only appear when you select 'Stacked bars' and the chart if grouped by a filter with filter groups.
When the option is selected the charts will now stack correctly.
=> EES-4355 use filter groups in stacked bar charts

src/explore-education-statistics-common/src/modules/find-statistics/components/ContactUsSection.tsx
Restores the anchor for the release page contact us link that was accidentally removed as part of https://github.com/dfe-analytical-services/explore-education-statistics/pull/4209
=> EES-4506 fix release contact us link

src/GovUk.Education.ExploreEducationStatistics.Admin.Tests/Services/ReleaseServiceTests.cs, src/GovUk.Education.ExploreEducationStatistics.Admin/Services/ReleaseService.cs, src/GovUk.Education.ExploreEducationStatistics.Admin/Services/TopicService.cs, src/GovUk.Education.ExploreEducationStatistics.Data.Model.Tests/Repository/ReleaseSubjectRepositoryTests.cs, src/GovUk.Education.ExploreEducationStatistics.Data.Model/Repository/Interfaces/IReleaseSubjectRepository.cs, src/GovUk.Education.ExploreEducationStatistics.Data.Model/Repository/ReleaseSubjectRepository.cs
This PR tidies up the methods of `ReleaseSubjectRepository` following an investigation into how a data set appears to have been imported successfully and then deleted except for leaving a `ReleaseSubject` and `Subject` remaining.
In that particular case the subject was not marked as soft deleted. After reviewing the code I was unable to spot how that could arise, since subjects are only not marked as soft deleted when bulk deleting a UI test topic which wouldn't occur in Production.
However as part of the review I've made the following changes to tidy up `ReleaseSubjectRepository`:
- Change methods to have the options `softDeleteOrphanedSubject` default `true` since this is the case everywhere except when bulk deleting a UI test topic. This simplifies `IReleaseSubjectRepository` to have …
=> EES-4495 Tidy ReleaseSubjectRepository, changing methods to soft delete orphaned subjects by default

src/explore-education-statistics-common/src/modules/table-tool/components/MultiHeaderTable.module.scss
Fixes a styling issue where the right border is missing on table header cells when a row above has a merged cell at the end.
I've gone for a slightly hacky CSS fix as it seemed the simplest way. It is possible using JS but would involve checking previous rows for merged cells at the end and adding a class to the affected cell to show the border, which seemed less efficient. Happy to discuss though.
**Before**
**After**
=> EES-4462 fix missing table header border style

.config/dotnet-tools.json, README.md, global.json
This PR adds version pins for .NET and the Entity Framework migrations tool (`dotnet ef`). 
Previously, we weren't doing this, potentially causing version conflicts with other projects where we don't use the same version of .NET.
=> EES-4514 Add project level .NET SDK version pins

.gitignore, README.md, src/GovUk.Education.ExploreEducationStatistics.Admin/Program.cs, src/GovUk.Education.ExploreEducationStatistics.Common.Tests/Resources/test-no-xml.svg, src/GovUk.Education.ExploreEducationStatistics.Common.Tests/Resources/test.svg, src/GovUk.Education.ExploreEducationStatistics.Common.Tests/Services/FileTypeServiceTests.cs, src/GovUk.Education.ExploreEducationStatistics.Common/GovUk.Education.ExploreEducationStatistics.Common.csproj, src/GovUk.Education.ExploreEducationStatistics.Common/Services/FileTypeService.cs, src/GovUk.Education.ExploreEducationStatistics.Content.Api/Program.cs, src/GovUk.Education.ExploreEducationStatistics.Data.Api/Program.cs, src/GovUk.Education.ExploreEducationStatistics.Data.Processor.Tests/Functions/ProcessorStage1Tests.cs, src/GovUk.Education.ExploreEducationStatistics.Data.Processor/GovUk.Education.ExploreEducationStatistics.Data.Processor.csproj, src/GovUk.Education.ExploreEducationStatistics.Data.Processor/Startup.cs, src/GovUk.Education.ExploreEducationStatistics.Publisher/GovUk.Education.ExploreEducationStatistics.Publisher.csproj, src/GovUk.Education.ExploreEducationStatistics.Publisher/Startup.cs
This PR fixes longstanding version mismatches between `libmagic` and the `magic.mgc` file distributed in the builds by allowing a custom `magic.mgc` file path to be configured.
This can be achieved simply by adding an `appsettings.Local.json` in a project which uses file validation (i.e. `Data.Processor` or `Admin`):
```json
{
"MagicFilePath": "/usr/lib/file/magic.mgc"
}
```
The above should work for Ubuntu, but you can change this to whatever path you want on your filesystem, as long as it's a working `magic.mgc` file.
- Upgraded Mime library and updated file type tests now that various file detections work correctly
- Added tests for SVG files now that they are correctly detected by upgrading Mime library. This also resolves [EES-4399](https://dfedigital.atlassian.net/browse/EES-4399).
=> EES-4021 Allow custom magic.mgc file paths to be configured via local appsettings

src/explore-education-statistics-admin/src/pages/release/datablocks/components/DataBlockPageTabs.tsx
Fixes a bug where when you edit an existing data block and save it the table and lists of selected filters etc revert to how they were before your changes. If you refreshed the changes had actually been saved.
=> EES-4507 fix data block save bug

renovate.json
This PR makes changes to the Renovate configuration.
- ~~It adds `ignoreDeps` configuration to ignore Moq.~~ We decided as a team to continue to receive Moq version updates.
- It removes the ignore on the Mime dependency which is not required after #4283.
- It switches ignored Mime-Detective to use `ignoreDeps` as a shorter way of ignoring dependencies than using `matchPackagePatterns` combined with `enabled`.
- It removes the ignore on ckeditor because all frontend dependencies are ignored.
- It removes the following config because that doesn't appear to be supported in the docs:
```
{
"packageNames": ["node"],
"enabled": false
},
```
=> chore: Remove ignored Mime dependency from Renovate and tidy up config

renovate.json, src/GovUk.Education.ExploreEducationStatistics.Admin/GovUk.Education.ExploreEducationStatistics.Admin.csproj, src/GovUk.Education.ExploreEducationStatistics.Common/GovUk.Education.ExploreEducationStatistics.Common.csproj, src/GovUk.Education.ExploreEducationStatistics.Data.Services/GovUk.Education.ExploreEducationStatistics.Data.Services.csproj
This PR removes a few unused / deprecated dependencies and changes the Renovate config to ignore major updates for nuget dependencies which are specific to major versions of .NET and EF.
=> chore: Remove unused dependencies and change Renovate to ignore major updates

renovate.json, src/GovUk.Education.ExploreEducationStatistics.Admin/GovUk.Education.ExploreEducationStatistics.Admin.csproj, src/GovUk.Education.ExploreEducationStatistics.Content.Api/GovUk.Education.ExploreEducationStatistics.Content.Api.csproj, src/GovUk.Education.ExploreEducationStatistics.Content.Model/ContentBlock.cs, src/GovUk.Education.ExploreEducationStatistics.Content.Services/GovUk.Education.ExploreEducationStatistics.Content.Services.csproj, src/GovUk.Education.ExploreEducationStatistics.Data.Api/GovUk.Education.ExploreEducationStatistics.Data.Api.csproj, src/GovUk.Education.ExploreEducationStatistics.Data.Services/GovUk.Education.ExploreEducationStatistics.Data.Services.csproj
This PR changes the Renovate config to restrict the versions of `Automapper` and `AutoMapper.Extensions.Microsoft.DependencyInjection` due to the versions of `Microsoft.AspNetCore.ApiAuthorization.IdentityServer:3.1.32`  -> `IdentityServer4.EntityFramework.Storage:3.0.0` -> that we use  in Admin depending on `AutoMapper` 9.0.0.
It's possible that if we did some additional work to upgrade `IdentityServer`, `IdentityServer4.EntityFramework` and `IdentityServer4.EntityFramework.Storage` to 3.1.4 then we might be able to use more recent versions (but still old) i.e. `AutoMapper` 10.1.1 and `AutoMapper.Extensions.Microsoft.DependencyInjection` 8.1.1.
However when I attempted this update I consistently got the following error:
```
IdentityServer4.Hosting.IdentityServerMiddleware[0]
Unhandled …
```
=> EES-4530 Change Renovate config to ignore upgrading Automapper

renovate.json, src/GovUk.Education.ExploreEducationStatistics.Admin/GovUk.Education.ExploreEducationStatistics.Admin.csproj
This PR makes a small change to the Renovate config to allow major version updates to the [.NET Core CLI](https://learn.microsoft.com/en-us/ef/core/cli/dotnet).
The tools are backwards compatible with EF 6. I tested creating a database migration using the latest tools and @markhiveit helped me check there is no dependency on having .NET 7 SDK installed.
After merging this Renovate should detect a change, updating .NET Command-line Tools 6.0.21 to .NET Command-line Tools 7.0.10.
- Remove Admin dependency on `Microsoft.VisualStudio.Web.CodeGeneration.Design` which is related to the .[NET Core scaffolding engine](https://learn.microsoft.com/en-us/aspnet/core/fundamentals/tools/dotnet-aspnet-codegenerator?view=aspnetcore-7.0). It provides the command line tool `dotnet aspnet-codegenerator` to …
=> EES-4530: Change Renovate config to allow major updates to EF CLI tools version

src/explore-education-statistics-admin/src/pages/release/data/ReleaseDataPage.tsx, src/explore-education-statistics-admin/src/pages/release/data/components/ReleaseFileUploadsSection.tsx, tests/robot-tests/tests/admin/analyst/edit_and_approve_release_as_publication_approver.robot, tests/robot-tests/tests/admin/bau/upload_files.robot, tests/robot-tests/tests/admin_and_public_2/bau/publish_amend_and_cancel.robot, tests/robot-tests/tests/admin_and_public_2/bau/publish_release_and_amend.robot
Changes the 'Ancillary file uploads' tab to ‘Supporting file uploads’ and updates the 'before you start' text.
=> EES-4511 update ancillary file tab and text

.dockerignore, useful-scripts/start.ts
This PR:
- Fixes non-locking services from preventing other services queued behind them from starting up. For example, `pnpm start db dataStorage` would never start up `dataStorage`.
- Changes running of explicit Docker services (e.g. `pnpm start db`) so they are no longer run as separate processes. We now just run all Docker services in daemonized mode before starting application services, then just output the container logs.
This means we avoid having to do any additional work to wait for Docker containers to shutdown gracefully. As the containers won't be killed on exiting the script, 'starting' the containers again will be immediate the next time the start script is ran. 
We've added the `--restart-docker` flag if you really want to restart the Docker containers upon startup …
=> EES-4133 Various start script improvements and fixes

src/explore-education-statistics-common/src/modules/find-statistics/components/DataBlockTabs.tsx, src/explore-education-statistics-common/src/modules/table-tool/components/TimePeriodDataTable.tsx
On the table tool the Footnotes heading had visually hidden text for screen reader users of “for undefined”. This removes the hidden text, it's only needed on the footnotes heading on data blocks as there can be multiple data blocks on a release page.
=> EES-4349 fix broken visually hidden footnotes heading text

src/explore-education-statistics-common/src/components/AccordionSection.tsx, src/explore-education-statistics-common/src/components/__tests__/__snapshots__/AccordionSection.test.tsx.snap, src/explore-education-statistics-frontend/src/modules/methodologies/MethodologyIndexPage.tsx, tests/robot-tests/scripts/create_snapshots.py
This fixes an issue caused when the methodologies page was reworked to remove topics and update to use the new GOV.UK accordions.
As we've added new id tags to elements to generate the methodologies' page snapshot, the snapshots for production can be updated once this has been deployed to production.
=> EES-4547 Fix snapshot generation for methodologies page

src/GovUk.Education.ExploreEducationStatistics.Admin.Tests/Services/Methodologies/MethodologyServiceTests.cs, src/GovUk.Education.ExploreEducationStatistics.Admin/Controllers/Api/Bau/MethodologyMigrationController.cs, src/GovUk.Education.ExploreEducationStatistics.Admin/Services/Methodologies/MethodologyService.cs, src/GovUk.Education.ExploreEducationStatistics.Common/Extensions/EnumerableExtensions.cs, src/GovUk.Education.ExploreEducationStatistics.Content.Model.Tests/Repository/MethodologyRepositoryTests.cs, src/GovUk.Education.ExploreEducationStatistics.Content.Model/Repository/Interfaces/IMethodologyRepository.cs, src/GovUk.Education.ExploreEducationStatistics.Content.Model/Repository/MethodologyRepository.cs, src/explore-education-statistics-admin/src/pages/methodology/adopt-methodology/components/AdoptMethodologyForm.tsx, src/explore-education-statistics-admin/src/pages/methodology/adopt-methodology/components/__tests__/AdoptMethodologyForm.test.tsx, src/explore-education-statistics-admin/src/pages/publication/__tests__/PublicationAdoptMethodologyPage.test.tsx, tests/robot-tests/tests/admin/bau/adopt_methodology.robot, tests/robot-tests/tests/admin/bau/release_status.robot
In testing for EES-4504, we noticed that we weren't covering this scenario:
- A unpublished publication creates a new methodology. That methodology remains unpublished.
- A live publication adopts that unpublished methodology.
In this instance, we might expect the methodology to be published as soon as it is adopted. And so we would need to set `LatestPublishedVersionId` alongside the methodology verison's published date, and publish related files.
This PR fixes this issue by only allowing published methodologies to be adopted. This means we don't have to cover the above scenario of potentially needing to publish a methodology at the moment it is adopted. 
This is more intuitive for users - someone adopting a methodology may not realise they're publishing it - and also simplifies the …
=> EES-4531 Only allow published methodologies to be adopted

src/explore-education-statistics-admin/src/components/form/FormEditor.tsx, src/explore-education-statistics-admin/src/config/ckEditorConfig.ts, src/explore-education-statistics-admin/src/hooks/useCKEditorConfig.ts, src/explore-education-statistics-admin/src/pages/release/content/components/EditableKeyStatDataBlockForm.tsx, src/explore-education-statistics-admin/src/pages/release/content/components/EditableKeyStatTextForm.tsx, src/explore-education-statistics-admin/src/pages/release/data/ReleaseDataFileReplacementCompletePage.tsx, src/explore-education-statistics-admin/src/pages/release/data/components/DataFileReplacementPlan.tsx, src/explore-education-statistics-admin/src/pages/release/data/components/ReleaseDataGuidanceSection.tsx, src/explore-education-statistics-admin/src/pages/release/footnotes/components/FootnoteForm.tsx, src/explore-education-statistics-admin/src/pages/release/footnotes/components/FootnotesList.tsx, src/explore-education-statistics-admin/src/types/ckeditor-ambient.d.ts, src/explore-education-statistics-admin/src/types/ckeditor.ts, src/explore-education-statistics-admin/src/utils/ckeditor/customUploadAdapterPlugin.ts, src/explore-education-statistics-common/src/components/FigureFootnotes.tsx, src/explore-education-statistics-common/src/modules/release/components/ReleaseDataGuidanceDataFile.tsx, src/explore-education-statistics-common/src/modules/table-tool/components/utils/__tests__/downloadTableOdsFile.test.ts, src/explore-education-statistics-common/src/modules/table-tool/components/utils/downloadTableOdsFile.ts, src/explore-education-statistics-common/src/utils/sanitizeHtml.ts, tests/robot-tests/tests/admin/bau/create_data_block_with_chart.robot, tests/robot-tests/tests/admin_and_public/bau/publish_data.robot, tests/robot-tests/tests/admin_and_public_2/bau/publish_release_and_amend_2.robot
Adds the ability to put links in footnotes by changing it to use a very cut down CKEditor and making sure that any other attributes are stripped out.
=> EES-4512 allow links in footnotes

src/explore-education-statistics-common/src/components/form/FormBaseInput.tsx, src/explore-education-statistics-common/src/components/form/FormSelect.tsx, src/explore-education-statistics-common/src/components/form/rhf/RHFFormField.tsx, src/explore-education-statistics-common/src/components/form/rhf/RHFFormFieldCheckboxGroup.tsx, src/explore-education-statistics-common/src/components/form/rhf/RHFFormFieldCheckboxMenu.tsx, src/explore-education-statistics-common/src/components/form/rhf/RHFFormFieldCheckboxSearchGroup.tsx, src/explore-education-statistics-common/src/components/form/rhf/RHFFormFieldRadioGroup.tsx, src/explore-education-statistics-common/src/components/form/rhf/RHFFormFieldSelect.tsx, src/explore-education-statistics-common/src/components/form/rhf/RHFFormFieldTextInput.tsx, src/explore-education-statistics-common/src/components/form/rhf/__tests__/RHFForm.test.tsx, src/explore-education-statistics-common/src/components/form/rhf/__tests__/RHFFormFieldCheckboxGroup.test.tsx, src/explore-education-statistics-common/src/components/form/rhf/__tests__/RHFFormFieldCheckboxSearchGroup.test.tsx, src/explore-education-statistics-common/src/components/form/rhf/__tests__/RHFFormFieldSelect.test.tsx, src/explore-education-statistics-common/src/components/form/rhf/util/getErrorMessage.ts, src/explore-education-statistics-common/src/modules/table-tool/components/DataSetStep.tsx, src/explore-education-statistics-common/src/modules/table-tool/components/FiltersForm.tsx, src/explore-education-statistics-common/src/modules/table-tool/components/LocationFiltersForm.tsx, src/explore-education-statistics-common/src/modules/table-tool/components/PublicationForm.tsx, src/explore-education-statistics-common/src/modules/table-tool/components/TimePeriodForm.tsx, src/explore-education-statistics-frontend/src/modules/cookies/CookiesPage.tsx, src/explore-education-statistics-frontend/src/modules/subscriptions/SubscriptionPage.tsx, tests/robot-tests/tests/general_public/table_tool_absence_in_prus.robot
Replaces uses of Formik with React Hook Form in the front end code base:
- table tool publication, location and time period steps
- cookies page
- subscription page
I haven't replaced Formik on the data catalogue page as this page will be changing fairly soon so it didn't seem worthwhile.
=> EES-4435 replace Formik with RHF in front end

src/GovUk.Education.ExploreEducationStatistics.Admin.Tests/Services/Methodologies/MethodologyApprovalServiceTests.cs, src/GovUk.Education.ExploreEducationStatistics.Admin.Tests/Services/Methodologies/MethodologyServiceTests.cs, src/GovUk.Education.ExploreEducationStatistics.Admin.Tests/Services/ReleaseServiceTests.cs, src/GovUk.Education.ExploreEducationStatistics.Admin/Migrations/ContentMigrations/20230915150510_EES4426_RemoveInternalReleaseNoteFromMethodologyVersionTable.Designer.cs, src/GovUk.Education.ExploreEducationStatistics.Admin/Migrations/ContentMigrations/20230915150510_EES4426_RemoveInternalReleaseNoteFromMethodologyVersionTable.cs, src/GovUk.Education.ExploreEducationStatistics.Admin/Services/Methodologies/MethodologyApprovalService.cs, src/GovUk.Education.ExploreEducationStatistics.Admin/Services/Methodologies/MethodologyService.cs, src/GovUk.Education.ExploreEducationStatistics.Admin/Services/ReleaseService.cs, src/GovUk.Education.ExploreEducationStatistics.Content.Model.Tests/MethodologyVersionTests.cs, src/GovUk.Education.ExploreEducationStatistics.Content.Model/MethodologyVersion.cs
This PR removes the InternalReleaseNote column from the MethodologyVersion table. This work was opened up by the creation of the MethodologyStatus table in EES-4385. Now that internal notes are stored in methodology statuses, there was no reason to also store them on methodology versions.
The only change to note is adding the `GetLatestMethodologyStatus` method which is called in `BuildMethodologyVersionViewModel`. `GetLatestMethodologyStatus` gets the latest `MethodologyStatus` for the specific version passed to it, rather than getting the latest status for the entire methodology. I reviewed the surrounding code and think this is the correct choice - although I suspect if we did pass the latest status for the entire methodology we would probably get the same result regardless.
=> EES-4426 Remove MethodologyVersion.InternalReleaseNote

src/explore-education-statistics-admin/src/pages/release/pre-release/components/PreReleaseUserAccessForm.tsx, src/explore-education-statistics-admin/src/pages/release/pre-release/components/__tests__/PreReleaseUserAccessForm.test.tsx
Replaces the custom email validation for PRA users with Yup email validation so that `gov.wales` and other valid TLDs are not rejected.
=> EES-4575 fix PRA email validation

src/explore-education-statistics-admin/src/pages/publication/components/PublicationDraftReleases.tsx, src/explore-education-statistics-admin/src/pages/publication/components/PublicationPublishedReleases.tsx, src/explore-education-statistics-admin/src/pages/release/content/components/ReleaseContent.tsx, src/explore-education-statistics-common/src/modules/release/components/ReleaseHelpAndSupportSection.tsx, src/explore-education-statistics-common/src/modules/release/components/ReleaseSummarySection.tsx, src/explore-education-statistics-frontend/src/modules/find-statistics/components/FiltersMobile.tsx
This PR fixes a bug where methodology links weren't being displayed in the Help and Support section on Admin content pages. This is because the `renderMethodologyLink` prop was being passed to `ReleaseHelpAndSupportSection` incorrectly .
As part of this PR, I've also ensured the Methodology section of `ReleaseHelpAndSupportSection` is displayed if the release only has an external release, and I've also removed various unused variables.
=> EES-4557 Fix how renderMethodologyLink prop is passed to ReleaseHelpAndSupportSection

src/GovUk.Education.ExploreEducationStatistics.Admin.Tests/Requests/ContactSaveRequestTests.cs, src/GovUk.Education.ExploreEducationStatistics.Admin.Tests/Services/PublicationServicePermissionTests.cs, src/GovUk.Education.ExploreEducationStatistics.Admin.Tests/Services/PublicationServiceTests.cs, src/GovUk.Education.ExploreEducationStatistics.Admin/Controllers/Api/PublicationController.cs, src/GovUk.Education.ExploreEducationStatistics.Admin/Migrations/ContentMigrations/20230920145213_EES4477_MakeContactTelNosNullable.Designer.cs, src/GovUk.Education.ExploreEducationStatistics.Admin/Migrations/ContentMigrations/20230920145213_EES4477_MakeContactTelNosNullable.cs, src/GovUk.Education.ExploreEducationStatistics.Admin/Requests/ContactSaveRequest.cs, src/GovUk.Education.ExploreEducationStatistics.Admin/Requests/PublicationCreateRequest.cs, src/GovUk.Education.ExploreEducationStatistics.Admin/Services/Interfaces/IPublicationService.cs, src/GovUk.Education.ExploreEducationStatistics.Admin/Services/PublicationService.cs, src/GovUk.Education.ExploreEducationStatistics.Admin/Services/ReleaseChecklistService.cs, src/GovUk.Education.ExploreEducationStatistics.Admin/ViewModels/ContactViewModels.cs, src/GovUk.Education.ExploreEducationStatistics.Admin/ViewModels/PublicationCreateViewModel.cs, src/GovUk.Education.ExploreEducationStatistics.Admin/ViewModels/ThemeViewModels.cs, src/GovUk.Education.ExploreEducationStatistics.Admin/ViewModels/TopicViewModels.cs, src/GovUk.Education.ExploreEducationStatistics.Common.Tests/Validators/PhoneNumberAttributeTests.cs, src/GovUk.Education.ExploreEducationStatistics.Common/Validators/PhoneNumberAttribute.cs, src/GovUk.Education.ExploreEducationStatistics.Content.Model/Contact.cs, src/explore-education-statistics-admin/src/pages/publication/__tests__/PublicationContactPage.test.tsx, src/explore-education-statistics-admin/src/pages/publication/components/PublicationContactForm.tsx, src/explore-education-statistics-admin/src/pages/publication/components/PublicationForm.tsx, src/explore-education-statistics-admin/src/pages/publication/components/__tests__/PublicationForm.test.tsx, src/explore-education-statistics-admin/src/services/publicationService.ts, src/explore-education-statistics-common/src/modules/find-statistics/components/ContactUsSection.tsx, src/explore-education-statistics-common/src/modules/table-tool/components/TableToolInfo.tsx, src/explore-education-statistics-common/src/services/publicationService.ts, tests/robot-tests/tests/admin/analyst/role_ui_permissions/publication_owner_ui_permissions.robot, tests/robot-tests/tests/admin_and_public/bau/publish_publication_update.robot
This PR makes a Contact telephone number optional. It also adds a migration to remove the DfE Enquiries telephone number from existing contacts, and frontend validation to prevent the DfE Enquiries number being added as a contact tel no in the future.
:rotating_light: NOTE: After the migration, to update the caches, we need to hit the `DELETE admin/api/bau/public-cache/publications` endpoint. :rotating_light: 
- I checked the Contact tel numbers currently in the Prod DB, and I wrote my migration to cover all cases, as the number was spaced differently in different rows.
- The frontend validation regex is designed to ensure nobody can get around the DfE Enquiries number validation by using spacing.
=> EES-4477 Make contact telephone number optional

src/explore-education-statistics-admin/src/pages/publication/components/PublicationMethodologyGuidance.tsx, src/explore-education-statistics-common/src/components/Modal.tsx, src/explore-education-statistics-common/src/components/ModalConfirm.tsx, src/explore-education-statistics-common/src/components/__tests__/ModalConfirm.test.tsx
This PR:
- Re-adds the modal button for the methodology type guidance that was accidentally omitted in #4319.
- Fixes `ModalConfirm` not calling `onExit` by default when no `onCancel`. This was causing the `ReleaseStatusForm` submit button to not re-trigger the modal on subsequent submissions after cancelling it once.
=> EES-4588 Fix missing methodology type modal guidance

src/GovUk.Education.ExploreEducationStatistics.Admin/Controllers/Api/PublicationController.cs, src/GovUk.Education.ExploreEducationStatistics.Common.Tests/Validators/PhoneNumberAttributeTests.cs, src/GovUk.Education.ExploreEducationStatistics.Common/Validators/PhoneNumberAttribute.cs, src/explore-education-statistics-admin/src/pages/publication/PublicationContactPage.tsx, src/explore-education-statistics-admin/src/pages/publication/PublicationCreatePage.tsx, src/explore-education-statistics-common/src/modules/find-statistics/components/ContactUsSection.tsx, src/explore-education-statistics-common/src/modules/table-tool/components/TableToolInfo.tsx, src/explore-education-statistics-common/src/styles/_typography.scss
This PR includes a publication contact's contact name in the Contact Us sections across the service. It previously wouldn't be present if the contact telephone wasn't present. We've also changed the layout of the contact details:
- I've used `<a href="tel:[...]">` for other phone numbers in the Contact Us section and used the `Telephone: <telNo>` format so it is aligned with how a publication contact's details are displayed. 
- I also fixed a backend validation issue with `PhoneNumberAttribute`. The validation was failing if the frontend provided an empty string or whitespace - we want to succeed in those cases because the contact telephone is now optional.
=> EES-4585 Include Contact name in Contact Us section

src/GovUk.Education.ExploreEducationStatistics.Admin/Startup.cs, src/GovUk.Education.ExploreEducationStatistics.Common.Tests/Extensions/HttpResponseMessageTestExtensions.cs, src/GovUk.Education.ExploreEducationStatistics.Common.Tests/Extensions/StringExtensionTests.cs, src/GovUk.Education.ExploreEducationStatistics.Common.Tests/ModelBinding/TrimStringModelBinderIntegrationTests.cs, src/GovUk.Education.ExploreEducationStatistics.Common.Tests/Rules/LowercasePathRuleIntegrationTests.cs, src/GovUk.Education.ExploreEducationStatistics.Common.Tests/Rules/LowercasePathRuleTests.cs, src/GovUk.Education.ExploreEducationStatistics.Common.Tests/Services/FileStoragePathUtilsTests.cs, src/GovUk.Education.ExploreEducationStatistics.Common.Tests/TestStartup.cs, src/GovUk.Education.ExploreEducationStatistics.Common/Extensions/MvcOptionsExtensions.cs, src/GovUk.Education.ExploreEducationStatistics.Common/Extensions/StringExtensions.cs, src/GovUk.Education.ExploreEducationStatistics.Common/ModelBinding/TrimStringModelBinder.cs, src/GovUk.Education.ExploreEducationStatistics.Common/ModelBinding/TrimStringModelBinderProvider.cs, src/GovUk.Education.ExploreEducationStatistics.Common/Rules/LowercasePathRule.cs, src/GovUk.Education.ExploreEducationStatistics.Common/Services/FileStoragePathUtils.cs, src/GovUk.Education.ExploreEducationStatistics.Content.Api.Tests/TestStartup.cs, src/GovUk.Education.ExploreEducationStatistics.Content.Api/Startup.cs, src/GovUk.Education.ExploreEducationStatistics.Content.Services/Cache/AllMethodologiesCacheKey.cs, src/GovUk.Education.ExploreEducationStatistics.Content.Services/Cache/PublicationTreeCacheKey.cs, src/GovUk.Education.ExploreEducationStatistics.Data.Api.Tests/TestStartup.cs, src/GovUk.Education.ExploreEducationStatistics.Data.Api/Startup.cs
This PR fixes a bug where backend API requests that use the blob cache internally could create additional cache entries for any resources which use string parameters as database and cache keys, by appending trailing spaces and/or by changing the case of those keys in the request path.
These keys are typically captured in route parameters.
E.g. for the public `GetRelease` endpoint `publications/{publication-slug}/releases/{release-slug}` the following variations will all fetch the same resource for the publication slug `pupil-attendance-in-schools` and release slug `2023-week-29`:
```
/api/publications/pupil-attendance-in-schools/releases/2023-week-29%20%20
/api/publications/pupil-attendance-in-schools%20%20/releases/2023-week-29
/api/publications/pupil-attendance-in-schools/releases/2023-W …
```
=> EES-3849 Lowercase API request paths and add Trim to string model binding

package.json
This PR changes the required pnpm version from exactly `8.6.7` to `>=8.8.0` to make the project work with the current latest version of pnpm.
As part of this change the `package.json` [packageManager](https://nodejs.org/dist/latest-v16.x/docs/api/packages.html#packagemanager) field is also updated, although I wasn't sure how this could be done without specifying the version to be exact.
=> chore: Update pnpm package manager to latest version

src/GovUk.Education.ExploreEducationStatistics.Common.Tests/Extensions/StringBuilderExtensionTests.cs, src/GovUk.Education.ExploreEducationStatistics.Common.Tests/Utils/HtmlToTextUtilsTests.cs, src/GovUk.Education.ExploreEducationStatistics.Common.Tests/Utils/__snapshots__/HtmlToTextUtilsTests.HtmlToText_MultipleElements_MixOfInlineAndBlocks_InlineFirst.snap, src/GovUk.Education.ExploreEducationStatistics.Common.Tests/Utils/__snapshots__/HtmlToTextUtilsTests.HtmlToText_MultipleElements_MixOfInlineAndBlocks_InlineFirst_InDiv.snap, src/GovUk.Education.ExploreEducationStatistics.Common.Tests/Utils/__snapshots__/HtmlToTextUtilsTests.HtmlToText_MultipleElements_MixOfInlineAndBlocks_InlineFirst_WithLineBreakElements.snap, src/GovUk.Education.ExploreEducationStatistics.Common/Extensions/StringBuilderExtensions.cs, src/GovUk.Education.ExploreEducationStatistics.Common/Utils/Html/HtmlToTextConverter.cs, src/GovUk.Education.ExploreEducationStatistics.Common/Utils/Html/HtmlToTextTableRenderer.cs, src/GovUk.Education.ExploreEducationStatistics.Common/Utils/HtmlToTextUtils.cs
This changes `HtmlToTextConverter` to only output Windows CRLF line endings. We're specifically only using CRLF as this will work best with the most users (who use Windows).
=> EES-4599 Fix `HtmlToTextConverter` outputting OS-dependent line endings

src/explore-education-statistics-common/src/modules/find-statistics/components/ContactUsSection.tsx
This PR converts the telephone number links implemented in #4333, back to plain text. This is based on guidance specified in the GOV.UK Design System.
=> EES-4605 Remove telephone number links from contact details

src/explore-education-statistics-common/src/contexts/NetworkActivityContext.tsx
This change re-implements request count tracking so that we use the state setter callbacks instead of a combination of refs and state setters.
Hopefully, this should provide a bit more atomicity, whereas previously it would be possible for the request count to change before it had been committed to state.
=> EES-4611 Re-implement request count tracking using state setter callbacks

src/GovUk.Education.ExploreEducationStatistics.Admin.Tests/Services/Methodologies/MethodologyServiceTests.cs, src/GovUk.Education.ExploreEducationStatistics.Admin/Services/Methodologies/MethodologyService.cs, src/GovUk.Education.ExploreEducationStatistics.Admin/ViewModels/Methodology/MethodologyUpdateRequest.cs, src/GovUk.Education.ExploreEducationStatistics.Content.Model/Repository/Interfaces/IMethodologyVersionRepository.cs, src/GovUk.Education.ExploreEducationStatistics.Content.Model/Repository/MethodologyVersionRepository.cs
This PR adds slug validation when creating a new methodology. It no longer allows a methodology to be created if the slug is already being used.
- As the `Create new methodology` button is a button and not a form, I'm not aware of an easy way to feed back the `SlugNotUnique` error from the backend to the user. So if someone did try to create a methodology with a duplicate slug, it now results in "Sorry, something went wrong" page - I figure this is better than a duplicate slug. Ultimately, this bug has been present for a long time and nobody has created a duplicate slug and the redirect work will fix this. So unless there is a quick fix, I'm inclined to leave this as it is for now.
- The code change to `MethodologyService#UpdateDetails`, whereby we only validate a slug if it has changed, …
=> EES-4602 Validate slug is unique when creating new methodology

src/explore-education-statistics-common/src/modules/charts/util/__tests__/createDataSetCategories.test.ts, src/explore-education-statistics-common/src/modules/charts/util/createDataSetCategories.ts
Removes commas in chart data which was causing charts to not render. The commas are added in error in the backend, see https://dfedigital.atlassian.net/browse/EES-4616.
=> EES-4614 handle commas in chart data

src/explore-education-statistics-common/src/modules/table-tool/components/PublicationForm.tsx, src/explore-education-statistics-common/src/modules/table-tool/components/TableToolWizard.tsx
Fixes a bug on the first step of a table tool where when you clicked 'Next step' without selecting anything you'd get an error message of 'themeId cannot be null'. This has been changed to 'Choose a theme'.
=> EES-4607 fix table tool publication form error message

infrastructure/parameters/dev.parameters.json, infrastructure/parameters/prod.parameters.json
This PR alters the Dev and Prod content database storage capacities.
<html>
<head>
</head>
<body>
Environment | Old capacity (bytes) | Old capacity (Gb) | New capacity (bytes) | New capacity (Gb)
-- | -- | -- | -- | --
Dev | 1073741824 | 1 | 2147483648 | 2
Prod | 2147483648 | 2 | 4294967296 | 4
</body>
</html>
Note: The Prod content database has recently been manually resized from 2Gb to 20Gb so this change will have the effect of reducing it in size from 20Gb to 4Gb when it's deployed.
=> EES-4629 Alter Dev and Prod content db storage capacities

tests/robot-tests/run_tests.py
This attempts to fix a rare intermittent UI test failure we've had with the error "SlugNotUnique".
We believe this is due to the `run_tests.py` script being invoked multiple times at the same time, and two of these runs coincidentally generating the same `runIdentifer` value. If this is correct, this fix should prevent this by adding additional random characters to the end of the `runIdentifier` variable.
=> EES-4392 Attempted fix for SlugNotUnique intermittent UI test failure

.github/workflows/validate-snapshots.yml
This PR updates the validate snapshots cron schedule intended to run at 9:35AM, 12:35PM & 4:35PM in advance of daylight saving time ending on 29/10/23.
Github Actions have no timezone support.
=> Update validate snapshots cron schedule

tests/robot-tests/run_tests.py
This fixes an issue where `runIdentifier`'s `randomStr` isn't lowercase. As slugs are always lowercase, this was causing test failures where strings weren't matching because of the difference in case.
=> EES-4392 runIdentifier's randomStr should be lowercase

.gitignore, tests/robot-tests/README.md
This PR updates the robot-tests README after https://github.com/dfe-analytical-services/explore-education-statistics/pull/4254 to avoid any confusion about where the WebDriver binary is downloaded.
The `tests\robot-tests\webdriver` folder is now redundant.
- Remove references to `chromedriver` and `webdriver` folders in `.gitignore`.
=> Update robot-tests README after changing from pyderman to webdriver-manager

.github/workflows/validate-snapshots.yml
This updates the reviewers for the snapshots comparison GitHub action to remove Tess (who has now left the DfE) and add Jen (who has recently joined).
=> Add Jen and remove Tess as snapshot reviewers

tests/robot-tests/tests/admin/analyst/manage_approvals_as_publication_approver.robot
Changed a Keyword in the file manage_approvals_as_publication_approver.robot to wait for the publications to load before checking the Approvals warning on Analyst Dashboard
=> EES-4642 Fixing UI tests failures in Admin suite

src/explore-education-statistics-admin/src/pages/methodology/components/MethodologySummaryForm.tsx, src/explore-education-statistics-admin/src/pages/methodology/components/__tests__/MethodologySummaryForm.test.tsx, src/explore-education-statistics-admin/src/pages/methodology/edit-methodology/summary/MethodologySummaryEditPage.tsx
Fixes the server error handling on the methodology summary form. Previously if you tried to change the title to one that is already taken you'd get an error page instead of the standard form error. I've converted the form to React Hook Form as part of this work.
=> EES-4638 fix server error handling on methodology form

tests/robot-tests/tests/general_public/glossary_page.robot, tests/robot-tests/tests/general_public/notifications_absence.robot, tests/robot-tests/tests/general_public/permalink_prod_1.robot, tests/robot-tests/tests/general_public/permalink_prod_2.robot, tests/robot-tests/tests/general_public/permalink_prod_3.robot
A few UI tests failed due to a mismatch of data from the live environment compared to the seed data for the UI tests. Additionally, a few xpaths are not valid anymore so they got replaced with ID selectors instead.
=> EES-4643 fixing Prod UI test failures in 'general_public' suite

src/explore-education-statistics-common/src/modules/release/components/OfficialStatisticsSection.tsx, src/explore-education-statistics-common/src/modules/release/components/__tests__/OfficialStatisticsSection.test.tsx
This PR expands the Official Statistics Section to include new copy from the OSR. This new copy is documented in https://dfedigital.atlassian.net/browse/EES-4621
Changes:
=> EES-4621/update offical statistics description

src/GovUk.Education.ExploreEducationStatistics.Admin.Tests/Services/ReleaseServiceTests.cs, src/GovUk.Education.ExploreEducationStatistics.Admin/Services/ReleaseService.cs, src/GovUk.Education.ExploreEducationStatistics.Content.Model/ContentSection.cs, src/GovUk.Education.ExploreEducationStatistics.Content.Model/Extensions/ReleaseAmendmentExtensions.cs, src/GovUk.Education.ExploreEducationStatistics.Content.Model/Release.cs
This PR:
- Fixes a problem whereby Data Blocks were being copied across into new Releases when they were being created from a template Release.
- Adds additional test steps into unit tests around creating Releases from templates to ensure that no Data Blocks have been copied over.
- Tackles the chunk of EES-4639 relating to creating Releases from templates, which was raised in part to prevent this very scenario from occurring!
This bug was introduced when removing ReleaseContentBlock and ReleaseContentSection from the model.  It was pointed out by @mmyoungman as having been a long-standing risky area of code whereby we were getting away with not copying Content Blocks into a Release generated from a template because we didn't hydrate them whilst pulling the template Release out of the …
=> EES-4654 - hotfix - prevent data blocks being copied to releases from templates

src/explore-education-statistics-admin/src/components/PageFooter.tsx, src/explore-education-statistics-frontend/src/components/PageFooter.tsx
Adds a line about the OSR to the footer.
=> EES-4623 add OSR line to footer

tests/robot-tests/tests/libs/common.robot, tests/robot-tests/tests/libs/utilities.py, tests/robot-tests/tests/libs/visual.py
This PR:
- allows Robot to take a screenshot of what it was actually seeing at the point that it failed, as well as a full-height version of that page as well.
Before, if we were getting for example an error whereby a test was not able to click on a Save button, all we were able to get was a full-height screenshot like so, which didn't help too much:
Now, we will also get a screenshot like this, which is what Robot actually sees at the point of failure and that will hopefully make the debugging process a lot easier:
Here we can easily see that we can't click on the "Save" button because it is covered over.
=> Updating Robot test harness to take non-resized screenshots as well as full-height screenshots

src/explore-education-statistics-admin/src/pages/release/datablocks/ReleaseDataBlockEditPage.tsx, src/explore-education-statistics-admin/src/pages/release/datablocks/__tests__/ReleaseDataBlockEditPage.test.tsx, src/explore-education-statistics-admin/src/pages/release/datablocks/components/__tests__/DataBlockPageTabs.test.tsx, src/explore-education-statistics-admin/src/pages/release/pre-release/__tests__/PreReleaseTableToolPage.test.tsx, src/explore-education-statistics-admin/src/services/dataBlockService.ts
This PR:
* fixes the Fast Track preview URL that is generated for a Data Block when in Admin.
I found during doing a quick test of Admin after the big EES-4467 PR went in that I'd not addressed the Public Fast Track link in Admin when a user creates a Featured Table.  This needs to be using the permanent DataBlockParent Id, rather than the versionable DataBlockVersion Id.
I had no idea that this URL preview was even a thing until now!
All passing saving for the usual Data Catalogue failure that we're currently getting on the dev branch.
=> EES-4467 - fixing Fast Track link generated in Admin

src/explore-education-statistics-admin/src/components/comments/Comment.tsx, src/explore-education-statistics-admin/src/components/comments/CommentAddForm.module.scss, src/explore-education-statistics-admin/src/components/comments/CommentAddForm.tsx, src/explore-education-statistics-admin/src/components/comments/CommentEditForm.tsx, src/explore-education-statistics-admin/src/components/comments/CommentsList.tsx, src/explore-education-statistics-admin/src/components/comments/CommentsWrapper.module.scss, src/explore-education-statistics-admin/src/components/comments/CommentsWrapper.tsx, src/explore-education-statistics-admin/src/components/comments/__tests__/Comment.test.tsx, src/explore-education-statistics-admin/src/components/comments/__tests__/CommentAddForm.test.tsx, src/explore-education-statistics-admin/src/components/comments/__tests__/CommentEditForm.test.tsx, src/explore-education-statistics-admin/src/components/comments/__tests__/CommentsList.test.tsx, src/explore-education-statistics-admin/src/components/comments/__tests__/CommentsWrapper.test.tsx, src/explore-education-statistics-admin/src/components/editable/EditableContentBlock.module.scss, src/explore-education-statistics-admin/src/components/editable/EditableContentBlock.tsx, src/explore-education-statistics-admin/src/components/editable/EditableContentForm.module.scss, src/explore-education-statistics-admin/src/components/editable/EditableContentForm.tsx, src/explore-education-statistics-admin/src/components/editable/__tests__/EditableContentBlock.test.tsx, src/explore-education-statistics-admin/src/components/editable/__tests__/EditableContentForm.test.tsx, src/explore-education-statistics-admin/src/contexts/CommentsContext.tsx, src/explore-education-statistics-admin/src/pages/release/content/ReleaseContentPage.module.scss, src/explore-education-statistics-admin/src/pages/release/content/ReleaseContentPage.tsx, src/explore-education-statistics-admin/src/pages/release/content/components/ReleaseEditableBlock.tsx, src/explore-education-statistics-admin/src/pages/release/content/components/__tests__/ReleaseEditableBlock.test.tsx, src/explore-education-statistics-admin/src/styles/_variables.scss, tests/robot-tests/tests/admin/bau/release_content_authoring.robot, tests/robot-tests/tests/libs/admin-common.robot
Adds the ability to comment on data blocks and embed blocks. The comments are on the while block, not on specific parts of it.
- there are two types of comment component now - `inline`, which is for inline comments in content blocks and includes the interactions with CKEditor, and `block`, a simpler version for comments on data & embed blocks. They both use a new `BaseComment` component.
- I've added a new `CommentsWrapper` component that's used for all the block types
- I've tidied it up a bit on smaller screens as previously the comments were pushed offscreen
- the UI for comments on content and data / embed blocks is a bit inconsistent as the comments UI always shows for data blocks but only shows when you edit content blocks, due to how it works with CKEditor. I've discussed this with …
=> EES-4544 comments on data and embed blocks

src/explore-education-statistics-common/src/modules/table-tool/utils/__data__/testTableDataWithMergedCells.ts, src/explore-education-statistics-common/src/modules/table-tool/utils/__tests__/mapTableToJson.test.ts, src/explore-education-statistics-common/src/modules/table-tool/utils/createExpandedRowHeaders.ts
Fixes a new table alignment bug caused by missing data and merged cells. The previous fix didn't work in this case as it didn't account for there being a mix of rows with different merged and unmerged cells in within a row group.
Before:
After:
=> EES-4674 fix table alignment bug

src/explore-education-statistics-admin/src/pages/publication/components/__tests__/PublicationPublishedReleases.test.tsx, src/explore-education-statistics-common/src/components/InfoIcon.tsx, src/explore-education-statistics-common/src/modules/table-tool/components/TableToolInfo.tsx, src/explore-education-statistics-common/src/modules/table-tool/components/__tests__/TableToolInfo.test.tsx
Two tweaks to this ticket have been discussed between myself, Nick, Nusrath and Cam:
* Both the release type text itself as well as the info icon are now clickable (previously only the icon was)
* The modal that opens when the button is clicked is now the specific one for that release type (previously it opened the explanatory one which lists all release types)
=> EES-4622 Button and Modal Tweaks

src/GovUk.Education.ExploreEducationStatistics.Admin.Tests/Services/DataGuidanceMigrationServicePermissionTests.cs, src/GovUk.Education.ExploreEducationStatistics.Admin.Tests/Services/DataGuidanceMigrationServiceTests.cs, src/GovUk.Education.ExploreEducationStatistics.Admin/Controllers/Api/Bau/DataGuidanceMigrationController.cs, src/GovUk.Education.ExploreEducationStatistics.Admin/Services/DataGuidanceMigrationService.cs, src/GovUk.Education.ExploreEducationStatistics.Admin/Services/Interfaces/IDataGuidanceMigrationService.cs, src/GovUk.Education.ExploreEducationStatistics.Admin/Startup.cs, src/GovUk.Education.ExploreEducationStatistics.Admin/ViewModels/DataGuidanceMigrationReport.cs, src/GovUk.Education.ExploreEducationStatistics.Content.Model.Tests/Fixtures/ReleaseGeneratorExtensions.cs, src/GovUk.Education.ExploreEducationStatistics.Data.Model.Tests/Fixtures/ReleaseSubjectGeneratorExtensions.cs
⚠️ This has an associated faffy deploy task [EES-4724](https://dfedigital.atlassian.net/browse/EES-4724) ⚠️ 
This PR follows on from https://github.com/dfe-analytical-services/explore-education-statistics/pull/4424.
It adds a migration endpoint which copies data guidance from the statistics database to the content database.
This needs to be run before we drop `ReleaseSubject.DataGuidance` in [EES-4661](https://dfedigital.atlassian.net/browse/EES-4661).
For every content database `ReleaseFile` of type `FileType.Data` which is also not a file replacement currently in progress, it copies `DataGuidance` from the corresponding `ReleaseSubject` found in the stattistics database.
Make a request to the secured BAU endpoint `PATCH /bau/migrate-data-guidance?dryRun={true|false}`.
When option …
=> EES-4660 Part 3 - Migrate existing data guidance to `ReleaseFile.Summary`

src/explore-education-statistics-admin/jest.config.js, src/explore-education-statistics-admin/test/EditorStub.js
JSDOM doesn't handle CSS well and seems to be particularly objecting to CKEditor, which is causing a ridiculous amount of errors in the log when running the admin tests. ~~As far as I can tell it shouldn't be trying to parse it anyway as all CSS files should be going through the transform we have configured in jest.config.js, but it is so I've just supressed this error.~~
As suggested by @ntsim below, I've stubbed out CKEditor to prevent errors from its CSS build polluting the test output.
=> EES-4715 suppress jsdom css errors

src/explore-education-statistics-admin/src/components/comments/Comment.tsx
Prevent long words in comments overflowing the comment.
=> EES-4544 ensure long words in comments wrap

tests/robot-tests/run_tests.py
This PR changes the path separators used in the declaration of the `data_changing_tests` variable in `run_tests.py`.
https://github.com/dfe-analytical-services/explore-education-statistics/blob/97033898811e7d508ff5e8b8879fe241e7f85ea9/tests/robot-tests/run_tests.py#L176
On Windows the value of `os.sep` is `\\`.
`print(f"tests{os.sep}")`  -> `tests\`
`print(f"{os.sep}admin")` ->  `\admin`
This doesn't match the separator in `args.tests` which is always a forward slash so we replace `{os.sep}` with a forward slash.
Without this change, `data_changing_tests` always evaluates to false on Windows, so `create_test_topic` is never run which lots of tests depend on.
=> 🐛 EES-4117 Change path separators in `run_tests.py`

src/GovUk.Education.ExploreEducationStatistics.Admin.Tests/Services/DataGuidanceMigrationServicePermissionTests.cs, src/GovUk.Education.ExploreEducationStatistics.Admin.Tests/Services/DataGuidanceMigrationServiceTests.cs, src/GovUk.Education.ExploreEducationStatistics.Admin.Tests/Services/DataGuidanceServiceTests.cs, src/GovUk.Education.ExploreEducationStatistics.Admin.Tests/Services/ReplacementServiceTests.cs, src/GovUk.Education.ExploreEducationStatistics.Admin/Controllers/Api/Bau/DataGuidanceMigrationController.cs, src/GovUk.Education.ExploreEducationStatistics.Admin/Services/DataGuidanceMigrationService.cs, src/GovUk.Education.ExploreEducationStatistics.Admin/Services/DataGuidanceService.cs, src/GovUk.Education.ExploreEducationStatistics.Admin/Services/Interfaces/IDataGuidanceMigrationService.cs, src/GovUk.Education.ExploreEducationStatistics.Admin/Services/ReplacementService.cs, src/GovUk.Education.ExploreEducationStatistics.Admin/Startup.cs, src/GovUk.Education.ExploreEducationStatistics.Admin/Validators/ValidationErrorMessages.cs, src/GovUk.Education.ExploreEducationStatistics.Admin/ViewModels/DataGuidanceMigrationReport.cs, src/GovUk.Education.ExploreEducationStatistics.Content.Model.Tests/Fixtures/ReleaseGeneratorExtensions.cs, src/GovUk.Education.ExploreEducationStatistics.Data.Model.Tests/Fixtures/ReleaseSubjectGeneratorExtensions.cs, src/GovUk.Education.ExploreEducationStatistics.Data.Services.Tests/DataGuidanceDataSetServiceTests.cs, src/GovUk.Education.ExploreEducationStatistics.Data.Services.Tests/ReleaseServiceTests.cs, src/GovUk.Education.ExploreEducationStatistics.Data.Services.Tests/TimePeriodServiceTests.cs, src/GovUk.Education.ExploreEducationStatistics.Data.Services/DataGuidanceDataSetService.cs, tests/robot-tests/tests/admin/bau/prerelease.robot, tests/robot-tests/tests/admin/bau/prerelease_and_amend.robot
This PR follows on from https://github.com/dfe-analytical-services/explore-education-statistics/pull/4420.
It begins setting data guidance in `ReleaseFile.Summary` for each data set updated in  `DataGuidanceService.UpdateDataGuidance`.
It also changes `ReplacementService` to begin copying data guidance from the original to the replacement `ReleaseFile` during the replace operation.
The current behaviour of setting and replacing data guidance in its original location in `ReleaseSubject.DataGuidance` is retained for now.
This PR will be followed up with a further change to migrate data guidance for all existing data sets from `ReleaseSubject` to `ReleaseFile`.
- Fixes an issue in `ReplacementService.RemoveOriginalSubjectAndFileFromRelease` which would ignore an error if the replacement file …
=> EES-4660 Part 2 - Begin setting Data Guidance on `ReleaseFile.Summary`

azure-pipelines-ui-tests.dfe.yml, tests/robot-tests/tests/libs/slack.py
This PR:
- makes the UI test pipeline fail when any tests fail (which does not include any tests that previously failed but were fixed in a rerun attempt).
- adds back in "Tests passed" into the Slack notification.
We now fail the "Publish Test Results" task on each of the 4 UI test jobs in the pipeline if any of the tests failed the initial run and any rerun attempts.  We configure the next task in the pipeline to run even if this "Publish Test Results" task fails, thus allowing the pipeline to complete regardless of this failure, but report the overall job as failed:
In this image, we see the "Publish Test Results" task failing.
These are the test results that are published in the failed "Publish Test Results" task.
Note the green ticks in the tasks following the failed "Publish Test …
=> Ees 4117 fail jobs on test failures

src/GovUk.Education.ExploreEducationStatistics.Admin.Tests/Services/ReplacementServiceTests.cs, src/GovUk.Education.ExploreEducationStatistics.Admin/Services/ReplacementService.cs
This PR fixes a bug generating the replacement plan for the 'replacement complete' page.
The frontend 'replacement complete' page runs the replacement plan against itself, i.e. using the file id of the new file for both the `originalFileId` and the `replacementFileId`, just so we can get the data blocks and footnotes in a convenient way to display in the summary.
https://github.com/dfe-analytical-services/explore-education-statistics/blob/34a0b6aeee57e1fd234c508a383c471b5885452f/src/explore-education-statistics-admin/src/pages/release/data/ReleaseDataFileReplacementCompletePage.tsx#L23-L28
#4424 introduced a bug into this when it added a new backend method `ReplacementService.CheckReleaseFilesExist` which was used by both `GetReplacementPlan` and `Replace` to check the original file and …
=> 🐛 EES-4660 Fix bug generating replacement plan for the replacement complete page

src/explore-education-statistics-common/src/components/form/FormCheckboxSearchGroup.tsx
Fixes a bug in the table tool where loading school data in the locations step was very slow and could cause the browser tab to crash. 
School data is very large, 28,000+ schools, so we don't render the checkboxes for them until you search and only show a maximum of 500. Or so we thought... it turns out that there's an `!isMounted` check in the component which renders the checkboxes without search that was kicking in first. I'm assuming was added so the component will work without JS enabled (though I'm dubious if you can actually get to anywhere it's used on the site without JS).
This fix adds a check for the `searchOnly` flag to prevent this happening.
=> EES-4732 fix slow locations rendering for schools

src/GovUk.Education.ExploreEducationStatistics.Admin.Tests/Controllers/Api/Bau/BauCacheControllerTests.cs, src/GovUk.Education.ExploreEducationStatistics.Admin/Controllers/Api/Bau/BauCacheController.cs
This PR:
- adds the `yyyy.json` filename format to the list of formats allowed in deleting Release JSON when using the Release JSON cache-clearing endpoint.
=> Allowing Release JSON files of format yyyy.json to be deleted using the /release-json cache clearing endpoint

src/GovUk.Education.ExploreEducationStatistics.Admin.Tests/Controllers/Api/Security/PermissionsControllerTests.cs, src/GovUk.Education.ExploreEducationStatistics.Admin.Tests/Controllers/Api/Statistics/TableBuilderControllerIntegrationTests.cs, src/GovUk.Education.ExploreEducationStatistics.Admin.Tests/Controllers/Api/Statistics/TableBuilderControllerTests.cs, src/GovUk.Education.ExploreEducationStatistics.Common.Tests/Cache/CacheAspectThreadManagementIntegrationTests.cs, src/GovUk.Education.ExploreEducationStatistics.Common.Tests/Fixtures/CacheServiceTestFixture.cs, src/GovUk.Education.ExploreEducationStatistics.Common.Tests/IntegrationTest.cs, src/GovUk.Education.ExploreEducationStatistics.Common.Tests/ModelBinding/TrimStringModelBinderIntegrationTests.cs, src/GovUk.Education.ExploreEducationStatistics.Common.Tests/Rules/LowercasePathRuleIntegrationTests.cs, src/GovUk.Education.ExploreEducationStatistics.Common/Cache/CacheAspect.cs, src/GovUk.Education.ExploreEducationStatistics.Content.Api.Tests/Controllers/PublicationControllerCachingTests.cs, src/GovUk.Education.ExploreEducationStatistics.Content.Api.Tests/Controllers/ReleaseControllerCachingTests.cs, src/GovUk.Education.ExploreEducationStatistics.Content.Api.Tests/Controllers/ReleaseControllerTests.cs, src/GovUk.Education.ExploreEducationStatistics.Content.Api.Tests/Controllers/ReleaseFileControllerTests.cs, src/GovUk.Education.ExploreEducationStatistics.Content.Api.Tests/Controllers/ThemeControllerCachingTests.cs, src/GovUk.Education.ExploreEducationStatistics.Content.Services.Tests/Cache/GlossaryCacheServiceTests.cs, src/GovUk.Education.ExploreEducationStatistics.Content.Services.Tests/Cache/MethodologyCacheServiceTests.cs, src/GovUk.Education.ExploreEducationStatistics.Content.Services.Tests/Cache/PublicationCacheServiceTests.cs, src/GovUk.Education.ExploreEducationStatistics.Content.Services.Tests/Cache/ReleaseCacheServiceTests.cs, src/GovUk.Education.ExploreEducationStatistics.Data.Api.Tests/Controllers/PermalinkControllerTests.cs, src/GovUk.Education.ExploreEducationStatistics.Data.Api.Tests/Controllers/PublicationControllerTests.cs, src/GovUk.Education.ExploreEducationStatistics.Data.Api.Tests/Controllers/TableBuilderControllerTests.cs, src/GovUk.Education.ExploreEducationStatistics.Data.Api.Tests/Controllers/TableBuilderMetaControllerTests.cs
This PR:
- fixes clashes between CacheServiceTestFixture tests and Integration Tests which, when running in parallel, can cause intermittent unit test failures on the pipeline by virtue of both types of tests injecting their own BlobCacheService into the static BlobCacheAttribute.Services field.
Historically, we've seen problems when multiple tests that enable the CacheAspect (by setting `CacheAspect.Enabled` to true) run in parallel, as they tend to interfere with each other in various ways e.g. they will set `CacheAspect.Enabled` back to false at in their teardowns, thus making the caching behaviour unreliable for other caching tests.
We've overcome this in the past by stopping them from running in parallel, by specifying a `Collection` to which these test suites belong.  When this is …
=> EES-4703 - fix caching test clashes

azure-pipelines-ui-tests.dfe.yml, tests/robot-tests/run_tests.py, tests/robot-tests/tests/libs/slack.py
This PR fixes a couple of outstanding issues with the UI tests running in the pipeline.
After the `rerun-attempts` work was put into the pipeline, the tests are very stable now in the pipeline, but often require an additional rerun or two in order to get a full set of greens on the test run.
If a rerun is necessary, the pipeline reports itself as failed, because the `xunit.xml` file contains test failure information in it, despite all tests finally passing.
The solution was to explicitly regenerate the `xunit.xml` file when merging rerun results from `rerun.xml` back into `output.xml` using Rebot.  [This commit](https://github.com/dfe-analytical-services/explore-education-statistics/pull/4451/commits/1624fecf1532bb7d06081950d6f7b8d3332f1c3a) specifies the generating of the `xunit.xml` …
=> EES-4117 - additional UI test pipeline tweaks

infrastructure/parameters/prod.parameters.json, infrastructure/templates/datafactory/template.json, infrastructure/templates/template.json
This PR is part 1 of EES-4222, where we are adding support to receive alerts from *all* environments, each with their own Slack channel.
This PR simply removes the `enableAlerts` flag from ARM templates altogether (previously only ever enabled for Prod).  I'd considered keeping it and simply setting its default to true, but there didn't seem to be any point, as anyone who's not interested in a given channel's alerts can simply not join or mute the channel.
This has been done in conjunction with setting up new webhook URLs for posting messages to a separate channel for each environment (#alerts-dev, #alerts-test, #alerts-preprod), and updating the "Slack Webhook" secret in each environment's Key Vault with the new URL.
Note that we are being told also that the way we have Slack alerts …
=> EES-4222 - enabling alerts for all Azure environments

src/GovUk.Education.ExploreEducationStatistics.Common/Model/Chart/Charts.cs, src/explore-education-statistics-admin/src/pages/release/datablocks/components/chart/ChartConfiguration.tsx, src/explore-education-statistics-admin/src/pages/release/datablocks/components/chart/__tests__/ChartConfiguration.test.tsx, src/explore-education-statistics-admin/src/pages/release/datablocks/components/chart/reducers/__tests__/chartBuilderReducer.test.ts, src/explore-education-statistics-admin/src/pages/release/datablocks/components/chart/reducers/chartBuilderReducer.ts, src/explore-education-statistics-common/src/components/form/FormBaseInput.tsx, src/explore-education-statistics-common/src/components/form/FormTextInput.tsx, src/explore-education-statistics-common/src/modules/charts/components/ChartRenderer.tsx, src/explore-education-statistics-common/src/modules/charts/types/chart.ts, tests/robot-tests/tests/admin/bau/create_data_block_with_chart.robot, tests/robot-tests/tests/admin_and_public_2/bau/publish_release_and_amend.robot, tests/robot-tests/tests/libs/charts.robot
Adds an optional subtitle to charts:
- the subtitle has a max length of 160 characters (this required adding a `maxLength` option to the `FormTextInput` component
- hint text has been added for title and subtitle
- the subtitle displays in the `figcaption` below the title
I haven't changed the form to use React Hook Form as part of this as having had a try I think it will require wider refactoring of the chart builder forms, see comment on https://dfedigital.atlassian.net/browse/EES-4534
=> EES-4675 add chart subtitles

tests/robot-tests/tests/admin/bau/release_content_authoring.robot
`release_content_authoring.robot` is frequently failing at `Add review comment for data block as bau1` because the add comment button is partially covered by the ‘Set page view’ button. This ensures it's visible.
=> EES-4742 fix flaky release content authoring ui test

src/explore-education-statistics-common/src/modules/table-tool/components/LocationFiltersForm.tsx
Currently in the table tool location step if the locations group doesn't have search the checkboxes are larger than if it does, e.g. the England option is larger than Regions etc. This sets them to always be small.
=> EES-4608 make all location filter checkboxes small

src/explore-education-statistics-admin/src/pages/admin-dashboard/components/DraftReleasesTable.tsx, src/explore-education-statistics-admin/src/pages/admin-dashboard/components/ScheduledReleasesTable.tsx, src/explore-education-statistics-admin/src/pages/publication/PublicationMethodologiesPage.tsx, src/explore-education-statistics-admin/src/pages/publication/components/PublicationDraftReleases.tsx, src/explore-education-statistics-admin/src/pages/publication/components/PublicationPublishedReleasesTable.tsx, src/explore-education-statistics-admin/src/pages/publication/components/PublicationScheduledReleases.tsx, src/explore-education-statistics-common/src/styles/utils/_text.scss
Prevents the modal icon in table headers from wrapping under the text in the following places:
- Dashboard - Draft releases - status column
- Dashboard - Scheduled releases - status and stages columns
- Publication - Methodologies - status and type columns
- Publication - Draft releases - status, errors and warnings columns
- Publication - Published releases - status column
- Publication - Scheduled releases - status and stages columns
=> EES-4636 prevent modal icon wrapping in table headers

src/explore-education-statistics-common/src/modules/table-tool/components/WizardStepHeading.tsx, src/explore-education-statistics-common/src/styles/utils/_text.scss
Prevents the 'Step X' tags on the table tool wrapping onto two lines on small screens.
=> EES-4641 prevent table tool step tag wrapping

infrastructure/templates/datafactory/components/db-maintenance-template.json, infrastructure/templates/datafactory/template.json, infrastructure/templates/template.json
This PR:
- adds success and failure messaging to Slack to each of our Data Factory pipelines.
- adds generic failure reporting for Data Factory activities.
Each main Data Factory job now has Success and Failure activities that follow on from the main activity.  Each success and failure is a new Web activity, and linked to the "Success" and "Failure" output paths from the main activity.
The image above shows specific success and failure messages from the "Remove Soft Deleted Subjects" Pipeline.
The above 2 images show success and failure messages from the "Rebuild Indexes" Pipeline.
This was added in a previous PR that is already on dev, but including details here.
The message above will be shown if any Data Factory errors occur. This will happen in conjunction with the specific success …
=> EES-4222 - adding success and failure Slack reporting to Data Factory jobs

src/explore-education-statistics-common/src/modules/charts/components/MapBlockInternal.tsx
Changes to the tooltip when you hover over areas on maps to make it more likely that the tooltip content will be visible:
- slightly reduced the width 
- made the tooltip 'sticky' - anchors the tooltip to the mouse pointer instead of it always being fixed in the middle of the area.
Videos to demonstrate the differences - in both of these I'm selecting Sheffield from the dropdown, then hovering over Sheffield, Derbyshire and Staffordshire.
Before:
https://github.com/dfe-analytical-services/explore-education-statistics/assets/81572860/6c66a3f0-547f-4545-96e9-ca57a80b38d2
After:
https://github.com/dfe-analytical-services/explore-education-statistics/assets/81572860/adcc625b-488f-4fb1-a773-0e7e5fa35f28
=> EES-4589 reduce map tooltip width and make sticky to mouse pointer

src/GovUk.Education.ExploreEducationStatistics.Public.Data.Api.Tests/Controllers/HelloWorldControllerTests.cs, src/GovUk.Education.ExploreEducationStatistics.Public.Data.Api/Config/SwaggerConfig.cs, src/GovUk.Education.ExploreEducationStatistics.Public.Data.Api/Controllers/HelloWorldController.cs, src/GovUk.Education.ExploreEducationStatistics.Public.Data.Api/GovUk.Education.ExploreEducationStatistics.Public.Data.Api.csproj, src/GovUk.Education.ExploreEducationStatistics.Public.Data.Api/Program.cs, src/GovUk.Education.ExploreEducationStatistics.Public.Data.Api/Startup.cs
This PR:
- Adds API versioning in the form of the [ASP.NET API Versioning](https://github.com/dotnet/aspnet-api-versioning) package.
- Integrates the API versioning with Swashbuckle.
- Reconfigures Swashbuckle to gather documentation from XML docblocks. This is better for formatting summaries and descriptions in a nice way.
These changes splits out all Swashbuckle config into `Program`, instead of `Startup`. 
This is necessary to get access to some of the extensions on `WebApplication` (in the newer minimal API format), but also streamlines the configuration in `Startup` and avoids having this configuration in integration tests.
=> EES-4748 Add API versioning with Swashbuckle integration

docker-compose.yml
This PR updates Azurite to 3.27.0. This is done to make it work with tables with newer versions of Azure Storage Explorer.
See https://github.com/microsoft/AzureStorageExplorer/issues/7485
=> EES-4761 Update Azurite to 3.27.0

src/GovUk.Education.ExploreEducationStatistics.Admin.Tests/Services/DataArchiveValidationServiceTests.cs, src/GovUk.Education.ExploreEducationStatistics.Admin.Tests/Services/FileUploadsValidatorServiceTests.cs, src/GovUk.Education.ExploreEducationStatistics.Admin/Services/DataArchiveValidationService.cs, src/GovUk.Education.ExploreEducationStatistics.Admin/Services/FileUploadsValidatorService.cs, src/GovUk.Education.ExploreEducationStatistics.Admin/Validators/ValidationErrorMessages.cs, src/explore-education-statistics-admin/src/pages/release/data/components/DataFileUploadForm.tsx
Limit the number of characters file names can have when uploading individual files and archives, and provide feedback to the user if their files exceed this limit.
This protects end users from hitting errors from having file names that are too long, for example there have been examples in the past where users can’t unzip files as the path is too long.
=> EES-4227 Add file name length validation to file uploads

src/explore-education-statistics-admin/src/pages/methodology/adopt-methodology/components/AdoptMethodologyForm.tsx, src/explore-education-statistics-admin/src/pages/methodology/edit-methodology/content/components/MethodologyNotesAddForm.tsx, src/explore-education-statistics-admin/src/pages/methodology/edit-methodology/content/components/MethodologyNotesEditForm.tsx, src/explore-education-statistics-admin/src/pages/methodology/edit-methodology/content/components/MethodologyNotesSection.tsx, src/explore-education-statistics-admin/src/pages/methodology/edit-methodology/status/MethodologyStatusEditPage.tsx, src/explore-education-statistics-admin/src/pages/methodology/edit-methodology/status/MethodologyStatusPage.tsx, src/explore-education-statistics-admin/src/pages/methodology/edit-methodology/status/components/MethodologyStatusForm.tsx, src/explore-education-statistics-admin/src/pages/methodology/edit-methodology/status/components/__tests__/MethodologyStatusForm.test.tsx, src/explore-education-statistics-admin/src/pages/methodology/external-methodology/components/ExternalMethodologyForm.tsx, src/explore-education-statistics-common/src/components/form/rhf/RHFFormFieldDateInput.tsx, src/explore-education-statistics-common/src/components/form/rhf/RHFFormFieldRadioSearchGroup.tsx, src/explore-education-statistics-common/src/components/form/rhf/__tests__/RHFFormFieldDateInput.test.tsx, src/explore-education-statistics-common/src/components/form/rhf/__tests__/RHFFormFieldRadioSearchGroup.test.tsx, src/explore-education-statistics-common/src/components/form/rhf/__tests__/__snapshots__/RHFFormFieldDateInput.test.tsx.snap
Converts the following forms to React Hook Form:
- Adopt Methodology Form
- Add and Edit Methodology Notes Forms (these have been split out from the `MethodologyNotesSection` component)
- Edit Methodology Status Form
- Add External Methodology Form
Two new RHF form components have been added as part of this:
- RHFFormFieldDateInput
- RHFFormFieldRadioSearchGroup
The tests for these are duplicated from the Formik versions to make sure they have featured parity, but we could probably tidy these up later on as there's a lot of duplcation across the form component tests.
=> EES-4753 RHF methodology forms

tests/robot-tests/tests/admin_and_public/bau/publish_publication_update.robot
As part of this PR,  robot scripts have been designed in order to test that 'Publication redirect' works even after the publication has been changed after the first release.
=> EES-3789 Add publication Redirects Robot scripts

src/GovUk.Education.ExploreEducationStatistics.Admin/Services/FileUploadsValidatorService.cs, src/GovUk.Education.ExploreEducationStatistics.Admin/Validators/ValidationErrorMessages.cs, src/GovUk.Education.ExploreEducationStatistics.Admin/web.config, src/explore-education-statistics-admin/src/pages/release/data/components/AncillaryFileForm.tsx, src/explore-education-statistics-admin/src/pages/release/data/components/ReleaseFileUploadsSection.tsx, src/explore-education-statistics-common/src/validation/yup/file.ts
The file limit of 100mb was found too restrictive for certain users when uploading ancillary data. These changes increase the limit to 2GB, and provide helpful messaging for information and validation.
- Client-side validation halts submission of files exceeding the limit before any transfer takes place
- If client validation were to fail, a file upload which exceeds the web server limit would result in a HTTP 400 (Bad Request), due to the endpoint restriction of int.MaxValue, which is ~2GB in bytes
- If the web server limit is increased (and the controller attributes removed, or the limit increased), and a file larger than 2GB is uploaded, the custom server-side validation will kick in and provide similar error feedback to the UI.
File streaming and chunking were considered as options, …
=> EES-3503: Increase max file upload size to 2GB

src/explore-education-statistics-frontend/src/middleware.ts
This is a speculative fix to a UI test failure we saw in `publish_publication_update.robot`'s `Validate publication redirect works` test case. 
The test case failed in all three pipeline UI test reruns, and all instances had a screenshot of a blank page - not a 404 or release page as we'd expect. 
We haven't seen this issue in any other case, whether running the UI tests locally or during manual testing.
=> EES-4775 Speculative fix for UI test redirect blank page issue

src/explore-education-statistics-frontend/src/middleware.ts
This reverts commit d07fe6e5b5642fefdca59fe138a65e0b894daf7e. Awaiting the redirectPages function lead to 404s when a page should have been redirected.
=> Revert "EES-4775 Speculative fix for UI test redirect blank page issue"

src/explore-education-statistics-frontend/src/middleware.ts, src/explore-education-statistics-frontend/src/middleware/pages/__tests__/redirectPages.test.ts, src/explore-education-statistics-frontend/src/middleware/pages/redirectPages.ts
This reverts commit bfe390ac68404b4417faa5bac17408a492562a00. Moving the code into the `middleware` function didn't solve the UI test failure.
=> Revert "EES-4775 Move redirectPages code into middleware.ts"

src/GovUk.Education.ExploreEducationStatistics.Public.Data.Api/Controllers/HelloWorldController.cs, src/GovUk.Education.ExploreEducationStatistics.Public.Data.Api/Startup.cs, src/GovUk.Education.ExploreEducationStatistics.Public.Data.Api/appsettings.Development.json, src/GovUk.Education.ExploreEducationStatistics.Public.Data.Model/Change.cs, src/GovUk.Education.ExploreEducationStatistics.Public.Data.Model/DataSet.cs, src/GovUk.Education.ExploreEducationStatistics.Public.Data.Model/DataSetVersion.cs, src/GovUk.Education.ExploreEducationStatistics.Public.Data.Model/Database/PublicDataDbContext.cs, src/GovUk.Education.ExploreEducationStatistics.Public.Data.Model/FilterMeta.cs, src/GovUk.Education.ExploreEducationStatistics.Public.Data.Model/FilterOptionMeta.cs, src/GovUk.Education.ExploreEducationStatistics.Public.Data.Model/IndicatorMeta.cs, src/GovUk.Education.ExploreEducationStatistics.Public.Data.Model/LocationOptionMeta.cs, src/GovUk.Education.ExploreEducationStatistics.Public.Data.Model/Migrations/20231221125422_InitialMigration.Designer.cs, src/GovUk.Education.ExploreEducationStatistics.Public.Data.Model/Migrations/20231221125422_InitialMigration.cs, src/GovUk.Education.ExploreEducationStatistics.Public.Data.Model/Migrations/PublicDataDbContextModelSnapshot.cs
This PR makes various tweaks to the `PublicDataDbContext` used by the public data API:
- New `PrivateId` and `PublicatId` properties added to location and filter option meta for use in querying Parquet data more efficiently
- `DataSetVersion.MetaSummary` is now required
- New `TotalResults` column added to `DataSetVersion`
- Renamed connection string name to `PublicDataDb`
=> EES-4751 Various public data API schema updates

.gitignore, src/GovUk.Education.ExploreEducationStatistics.Common.Tests/Extensions/AssemblyExtensionTests.cs, src/GovUk.Education.ExploreEducationStatistics.Common.Tests/Extensions/PathUtilsTests.cs, src/GovUk.Education.ExploreEducationStatistics.Common.Tests/Utils/GeographicLevelUtilTests.cs, src/GovUk.Education.ExploreEducationStatistics.Common/Converters/EnumToEnumLabelConverter.cs, src/GovUk.Education.ExploreEducationStatistics.Common/Converters/EnumToEnumValueConverter.cs, src/GovUk.Education.ExploreEducationStatistics.Common/Extensions/AssemblyExtensions.cs, src/GovUk.Education.ExploreEducationStatistics.Common/Utils/GeographicLevelUtils.cs, src/GovUk.Education.ExploreEducationStatistics.Common/Utils/PathUtils.cs, src/GovUk.Education.ExploreEducationStatistics.Public.Data.Scripts/Commands/SeedDataCommand.cs, src/GovUk.Education.ExploreEducationStatistics.Public.Data.Scripts/GovUk.Education.ExploreEducationStatistics.Public.Data.Scripts.csproj, src/GovUk.Education.ExploreEducationStatistics.Public.Data.Scripts/Models/MetaFileRow.cs, src/GovUk.Education.ExploreEducationStatistics.Public.Data.Scripts/Program.cs, src/GovUk.Education.ExploreEducationStatistics.Public.Data.Scripts/README.md, src/GovUk.Education.ExploreEducationStatistics.Public.Data.Scripts/SeedFiles/.gitignore, src/GovUk.Education.ExploreEducationStatistics.Public.Data.Scripts/Seeds/DataSetSeed.cs, src/GovUk.Education.ExploreEducationStatistics.Public.Data.Scripts/Utils/ShortId.cs, src/GovUk.Education.ExploreEducationStatistics.sln
:warning: Depends on #4489 and #4486 :warning: 
---
This PR adds a seed data script for the public data API. This script will seed data sets for the following publications:
- Schools, pupils and their characteristics
- Pupil characteristics - Ethnicity and Language
- Pupil characteristics - Year group and Gender
- Pupil absence in schools in England:
- Absence rates by pupil characteristic - full academic years
- Absence rates by geographic level - full academic years
- Absence rates by geographic level - school level - full academic years
- 16 to 18 school and college performance tables
- Destinations by qualification title, provision and sector subject area (QUA01)
- Destinations by demographics and provision (NAT01)
Note that the QUA01 and NAT01 data sets don't really belong in the '16 …
=> EES-4751 Add seed data script for public data API

.github/workflows/validate-snapshots.yml
**Change**
Add a job to run in the event of a snapshot validation workflow failure, which sends a notification to the applicable Slack channel.
**Motivation**
To ensure workflow failures can be picked up and resolved in a timely manner.
=> EES-4553: Add Slack notification for "Validate snapshots" workflow failures

tests/robot-tests/tests/admin_and_public/bau/publish_publication_update.robot
This PR:
- replaces standard Selenium keyword "go to" with basic auth-supporting equivalent keyword "user navigates to public frontend"
This stops the navigation of the failing test from becoming stuck on the basic auth popup when run against Dev, where basic auth access is enforced.
=> EES-4775 - swapped "go to" keyword for equivalent public page keyword that includes basic auth support

src/explore-education-statistics-frontend/src/modules/data-catalogue/DataCataloguePage.tsx
**Changes**
Replace "superseded by" React-style `<Link>` component with a standard HTML anchor tag.
**Motivation**
Resolve a state issue whereby superseded links didn't update other components on the page to match the newly-selected publication.
**Tradeoffs**
More complex work would be required to refactor the state management aspect of the multi-step form in order to get this working with the existing `Link` component. Changing the element to an anchor triggers a full page refresh, which isn't the ideal or preferred solution, but is still fast enough to be barely perceivable.
This solution was chosen as a quick, temporary fix due to the data catalogue section currently undergoing a full rewrite.
=> EES-4759: Replace "superseded by" link component with anchor

src/GovUk.Education.ExploreEducationStatistics.Publisher/Services/PublishingCompletionService.cs
This PR fixes a bug where if you schedule a release to be published, then change its publication's slug while it's scheduled, the publication's `LatestPublishedReleaseId` won't get updated when the release is published. This leads to the latest release incorrectly saying it's not the latest data on the public release page.
This happens because the Azure Storage `ReleaseStatus` table has a column called `PublicationSlug` that isn't updated when the Content DBs Publication table Slug is updated. `PublishingCompletionService#CompletePublishingIfAllPriorStagesComplete` used the `ReleaseStatus` table's out-of-date slug to determine what publication's `LatestPublishedReleaseId`s needed updating. So `LatestPublishedReleaseId` was not updated.
I decided against ensuring `ReleaseStatus`'s …
=> EES-4777 Get publications via releaseIds, not PublicationSlugs

src/explore-education-statistics-admin/src/components/editable/EditablePageModeToggle.module.scss, src/explore-education-statistics-admin/src/components/editable/EditablePageModeToggle.tsx, src/explore-education-statistics-admin/src/components/editable/__tests__/EditablePageModeToggle.test.tsx, src/explore-education-statistics-admin/src/pages/release/content/__tests__/ReleaseContentPage.test.tsx, tests/robot-tests/tests/admin/bau/create_data_block_with_chart.robot, tests/robot-tests/tests/admin/bau/create_methodology_amendment.robot, tests/robot-tests/tests/admin/bau/release_content.robot, tests/robot-tests/tests/admin/bau/release_content_authoring.robot, tests/robot-tests/tests/libs/admin-common.robot, tests/robot-tests/tests/libs/admin/analyst/role_ui_permissions.robot
Changes the page view controls on release and methodology content pages to be in a sticky bar at the top of the page (once you've scrolled past it).
Removes the `user closes Set Page View box` keyword from the UI tests as it's no longer needed.
Desktop:
Mobile:
=> EES-4754 change page view controls

src/explore-education-statistics-admin/src/components/editable/EditablePageModeToggle.module.scss, src/explore-education-statistics-admin/src/components/form/FormEditor.module.scss, src/explore-education-statistics-admin/src/pages/release/content/ReleaseContentPage.tsx
Fixes a couple of spacing issues with the new 'Change page view' bar:
- prevents it from covering the sticky toolbar in CKEditor
- moves the warnings about unresolved comments and unsaved changes to below the bar.
=> EES-4754 fix page mode bar covering ckeditor toolbar

src/explore-education-statistics-admin/src/pages/release/data/ReleaseDataFileReplacementCompletePage.tsx, src/explore-education-statistics-admin/src/pages/release/data/__tests__/ReleaseDataFileReplacementCompletePage.test.tsx
Shows an error message if `getReplacementPlan` fails on the data plan replacement complete page.
=> EES-4737 show error if get data file replacement plan fails

src/explore-education-statistics-admin/src/components/editable/EditablePageModeToggle.tsx
Fixes an accessibility issue spotted by @N-moh. 
The `pageViewToggleButton` is only shown on mobile (where the page controls can be expanded / collapsed) so the aria-labelledby tag is not needed on desktop.
=> EES-4754 remove unneeded aria-labelledby on desktop

src/GovUk.Education.ExploreEducationStatistics.Data.Services.Tests/ObservationServiceTests.cs, src/GovUk.Education.ExploreEducationStatistics.Data.Services/ObservationService.cs
This reverts commit c57be670ad40b19a52b26a186858224ae4dc59af.
I want to another get_datablock_responses run with the previous set up to help validate any difference we're seeing.
Explain the **motivation** for making this change. What existing problem does the pull request solve?
You might also want to think about the following:
- How did you solve complex parts of the problem? Other contributors may benefit from knowing more about your solution.
- Are there any potential tradeoffs that need mentioning, or edge cases that have not been covered?
- Have you added a reusable piece of functionality? Consider including some code snippets to better illustrate its usage.
Are there any changes that were closely related to this change but not directly part of the main work e.g. refactoring, fixes, …
=> Revert "EES-4522 Use RIGHT JOIN instead of IN in generated query"

src/explore-education-statistics-frontend/src/middleware.ts
Fixes two bugs caused by https://github.com/dfe-analytical-services/explore-education-statistics/pull/4540:
- it was trying to redirect build files because they weren't lower case
- it broke the back button handling we have in the table tool
=> EES-4606 specify redirect paths

src/GovUk.Education.ExploreEducationStatistics.Content.Services.Tests/Cache/PublicationCacheServiceTests.cs, src/GovUk.Education.ExploreEducationStatistics.Content.Services/Cache/PublicationCacheService.cs, src/explore-education-statistics-admin/src/prototypes/components/PrototypeTableToolWizard.tsx, src/explore-education-statistics-common/src/modules/table-tool/components/PublicationForm.tsx, src/explore-education-statistics-common/src/modules/table-tool/components/TableToolWizard.tsx, src/explore-education-statistics-common/src/modules/table-tool/components/__tests__/PublicationForm.test.tsx, src/explore-education-statistics-common/src/modules/table-tool/components/__tests__/TableToolWizard.test.tsx, src/explore-education-statistics-common/src/modules/table-tool/types/selectedPublication.ts, src/explore-education-statistics-frontend/src/modules/data-catalogue/DataCataloguePage.tsx, src/explore-education-statistics-frontend/src/modules/table-tool/TableToolPage.tsx, src/explore-education-statistics-frontend/src/modules/table-tool/__tests__/TableToolPage.test.tsx, src/explore-education-statistics-frontend/src/modules/table-tool/components/__tests__/__data__/tableData.ts, src/explore-education-statistics-frontend/src/pages/data-tables/fast-track/[dataBlockParentId].tsx, tests/robot-tests/tests/admin_and_public/bau/archive_publication.robot
Fixes direct links to the table tool for superseded publications:
- the superseded publication is selected
- a warning is shown
- you can progress through the table tool as usual
- step 1 of the table tool does not list superseded publications (as currently)
=> EES-4820 allow direct linking to superseded publications in the table tool

styleguides/styleguide-backend.md
Adding the following style sections:
* File Scoped Namespaces
* Implicitly Typed Local Variables
* Nullable Reference Types
I added these in alphabetical order so `2.1.1 Named Parameters` has moved to `2.1.3 Named Parameters`.
=> docs: Backend style guide updates

infrastructure/templates/template.json, src/GovUk.Education.ExploreEducationStatistics.Admin.Tests/Security/AuthorizationHandlers/ViewSpecificReleaseAuthorizationHandlersTests.cs, src/GovUk.Education.ExploreEducationStatistics.Admin.Tests/Services/PreReleaseServiceTests.cs, src/GovUk.Education.ExploreEducationStatistics.Admin.Tests/Services/PreReleaseUserServiceTests.cs, src/GovUk.Education.ExploreEducationStatistics.Admin.Tests/appsettings.IntegrationTest.json, src/GovUk.Education.ExploreEducationStatistics.Admin/Models/PreReleaseWindow.cs, src/GovUk.Education.ExploreEducationStatistics.Admin/Models/PreReleaseWindowStatus.cs, src/GovUk.Education.ExploreEducationStatistics.Admin/Security/AuthorizationHandlers/AuthorizationHandlerService.cs, src/GovUk.Education.ExploreEducationStatistics.Admin/Services/PreReleaseService.cs, src/GovUk.Education.ExploreEducationStatistics.Admin/appsettings.Development.json, src/GovUk.Education.ExploreEducationStatistics.Common/Extensions/DateTimeExtensions.cs, src/explore-education-statistics-admin/src/pages/release/pre-release/PreReleasePageContainer.tsx, src/explore-education-statistics-admin/src/pages/release/pre-release/__tests__/PreReleasePageContainer.test.tsx, src/explore-education-statistics-admin/src/services/permissionService.ts, tests/robot-tests/tests/admin/bau/prerelease.robot, tests/robot-tests/tests/admin/bau/prerelease_and_amend.robot
When scheduling a Release, the user is prompted to enter a date sans time, which is saved as its floor (midnight beginning of Publish Day). 
The Pre-Release Access period is calculated using config values, but typically runs from 1440 minutes before that midnight (= the previous midnight) through to 1 minute before. 
However the Release itself isn't available until 9:30 that day, and attempting to access it between midnight and 9:30 will yield a message saying the PRA period has ended. This PR aims to extend the PRA such that Releases are still viewable up to their actual release. 
The simpler route might be to simply change the calculation for the PRA end time. This is fraught with danger however as these are existing config values, and this period might be used for other calculations …
=> EES-3986 Extend PRA into Publish Day until Release is actually Published

src/GovUk.Education.ExploreEducationStatistics.Common.Tests/Fixtures/Generator.cs, src/GovUk.Education.ExploreEducationStatistics.Common.Tests/Fixtures/GeneratorTests.cs
This PR fixes a bug using `Generator.ForRange` when the range is empty.
For example, in the following test data setup, the range setter for range `[..0]` should not be applied:
```csharp
_fixture
.DefaultTheme()
.ForRange(..0, s => s.SetTitle("Theme title"))
.GenerateArray(2);
```
Without this fix we find that the range setter is applied to the first element in the array.
While we wouldn't normally have any reason to define a range with upper bound (exclusive) equal to zero, it's still possible that a zero value can be encountered when the upper bound is a calculated expression.
=> 🐛 Fix test data generator bug in `Generator.ForRange` when range is empty

infrastructure/parameters/dev.parameters.json
All references to the `preReleaseMinutesBeforeEnd` parameter should have been removed as part of 
https://github.com/dfe-analytical-services/explore-education-statistics/pull/4543
but this one was missed
=> Remove preReleaseMinutesBeforeEnd from dev parameters

src/GovUk.Education.ExploreEducationStatistics.Content.Model/NamingUtils.cs, src/explore-education-statistics-admin/src/pages/publication/PublicationDetailsPage.tsx, src/explore-education-statistics-admin/src/pages/publication/__tests__/PublicationDetailsPage.test.tsx, src/explore-education-statistics-admin/src/pages/publication/components/PublicationDetailsForm.tsx, src/explore-education-statistics-admin/src/pages/publication/components/PublicationUpdateConfirmModal.tsx, src/explore-education-statistics-common/src/utils/__tests__/slugFromTitle.test.tsx, src/explore-education-statistics-common/src/utils/slugFromTitle.ts
This PR adds extra details to the update publication confirmation modal in Admin.
When a publication is updated, it's possible that the title and slug are different. Currently, when a user updates a publication, the title and slug are always brought into alignment. 
Currently, users can only specify the title they want and the slug is generated from that title. In the future, it may be possible for users to also specify the particular slug they want - this work has been done with this potential future change in mind.
- `slugFromTitle` is a copy of the backend's `NamingUtils#SlugFromTitle`. The tests for `slugFromTitle` also also copied from the backend.
=> EES-4792 Create PublicationUpdateConfirmModal

src/GovUk.Education.ExploreEducationStatistics.Content.Model/Repository/ReleaseRepository.cs, src/GovUk.Education.ExploreEducationStatistics.Publisher/Services/PublishingCompletionService.cs
This PR simplifies the methods of determining latest release versions to use the new `ReleaseParent` which was added by #4558.
In #4541 we gathered all the current methods of determining latest release versions into a new common location in `IReleaseRepository`.
Those methods relied on loading all releases for a publication (or from a releases own publication if starting from a release) and then iterating through the releases to eliminate all but those which had no other release with `PreviousVersionId` equal to their own id.
This PR switches those methods to determining latest release versions based on the max version id for versions related to the same parent.
It's the final part of the implementation of the database queries originally proposed by @Dancemammal in …
=> EES-4667 EES-4487 EES-4549 Simplify methods of determining latest release versions

src/GovUk.Education.ExploreEducationStatistics.Public.Data.Api.Tests/Controllers/DataSetsControllerTests.cs, src/GovUk.Education.ExploreEducationStatistics.Public.Data.Api.Tests/Controllers/PublicationsControllerTests.cs, src/GovUk.Education.ExploreEducationStatistics.Public.Data.Api/Controllers/DataSetsController.cs, src/GovUk.Education.ExploreEducationStatistics.Public.Data.Api/Services/DataSetService.cs, src/GovUk.Education.ExploreEducationStatistics.Public.Data.Api/Services/Interfaces/IDataSetService.cs, src/GovUk.Education.ExploreEducationStatistics.Public.Data.Api/Services/PublicationService.cs
Adding an endpoint for retrieving the details of a single data-set via the Public API. 
The endpoint lives at `api/v1/data-sets/{dataSetId}`.
The endpoint returns the following status codes:
- 200
- 404
And returns the following JSON response when the response is a 200 OK:
```json
{
"id": "string(uuid)",
"title": "string",
"summary": "string",
"status": "string",
"latestVersion": {
"number": "string",
"published": "string(datetime)",
"totalResults": 0,
"timePeriods": {
"start": "string",
"end": "string"
},
"geographicLevels": [
"string"
],
"filters": [
"string"
],
"indicators": [
"string"
]
},
"supersedingDataSetId": "string"
}
```
=> EES-4708 Adding an endpoint to retrieve a summary for a single Data Set

src/GovUk.Education.ExploreEducationStatistics.Common.Tests/Utils/VersionUtilsTests.cs, src/GovUk.Education.ExploreEducationStatistics.Common/GovUk.Education.ExploreEducationStatistics.Common.csproj, src/GovUk.Education.ExploreEducationStatistics.Common/Utils/VersionUtils.cs, src/GovUk.Education.ExploreEducationStatistics.Public.Data.Api.Tests/Controllers/DataSetsControllerTests.cs, src/GovUk.Education.ExploreEducationStatistics.Public.Data.Api/Controllers/DataSetsController.cs, src/GovUk.Education.ExploreEducationStatistics.Public.Data.Api/Services/DataSetService.cs, src/GovUk.Education.ExploreEducationStatistics.Public.Data.Api/Services/Interfaces/IDataSetService.cs
Adding an endpoint for retrieving a single Data Set Version.
The endpoint lives at `api/v1/data-sets/{dataSetId}/versions/{version}`.
The endpoint returns the following status codes:
- 200
- 404
And returns the following JSON response when the response is a 200 OK:
```json
{
"number": "string",
"type": "string",
"status": "string",
"published": "string(datetime)",
"unpublished": "string(datetime)",
"notes": "string",
"totalResults": 0,
"timePeriods": {
"start": "string",
"end": "string"
},
"geographicLevels": [
"string"
],
"filters": [
"string"
],
"indicators": [
"string"
]
}
```
=> EES-4743 Adding endpoint to retrieve a single Data Set Version

docker/keycloak/keycloak-ees-realm.json, src/GovUk.Education.ExploreEducationStatistics.Admin.Tests/Controllers/Api/ConfigurationControllerTests.cs, src/GovUk.Education.ExploreEducationStatistics.Admin.Tests/Services/ClaimsPrincipalTransformationServiceTests.cs, src/GovUk.Education.ExploreEducationStatistics.Admin/Controllers/Api/ConfigurationController.cs, src/GovUk.Education.ExploreEducationStatistics.Admin/appsettings.Keycloak.json, src/explore-education-statistics-admin/src/auth/msal.ts, src/explore-education-statistics-admin/src/components/PageHeader.tsx, src/explore-education-statistics-admin/src/config.ts, src/explore-education-statistics-admin/src/contexts/ConfigContext.tsx, src/explore-education-statistics-admin/src/pages/admin-dashboard/AdminDashboardPage.tsx, src/explore-education-statistics-admin/src/routes/routes.ts, tests/robot-tests/run_tests.py, tests/robot-tests/tests/admin/authentication/login_and_logout.robot, tests/robot-tests/tests/libs/admin-common.robot, tests/robot-tests/tests/libs/fail_fast.py
:warning: Keycloak Docker containers and images need to be dropped and recreated when this PR goes in.
:warning: All App Registrations for Admin SPAs across each environment will need to be configured to return the optional "login_hint" Claim to enable silent logout.
This PR aims to fix issues that some team members are experiencing around inconsistent logout behaviour when running under Entra ID.
It also brings Keycloak logout behaviour more in line with Entra ID's logout by supplying a logout endpoint in the authority metadata so that a full logout redirect flow can be supported which results in the user being logged out of Keycloak as well as the app, thus ensuring they log in again instead of just hitting "Sign in" and being magically signed in again!
I've added a new login and logout …
=> EES-4814 - fixing Robot test run issues around logout under Entra ID.  Making logout under Keycloak more consistent.

src/explore-education-statistics-admin/src/components/form/FormFieldEditor.tsx
The URL validation on text blocks in releases was preventing adding `mailto` links, this prevents the validation from catching them.
=> EES-4923 prevent validation errors for emails in content blocks

src/explore-education-statistics-admin/src/App.tsx, src/explore-education-statistics-admin/src/index.tsx
Moves the import of the global styles to try to ensure that they get loaded before the module styles.
This fixes styling bugs in the admin caused by gov.uk styles overriding module styles.
=> EES-4935 ensure govuk styles are loaded first

.github/workflows/block-autosquash-commits.yml
This PR adds a GitHub workflow to prevent auto-squash commits (e.g. `fixup`) from being merged via pull requests.
To resolve this, these commits should be auto-squashed via `git rebase {branch} -i --autosquash` before the branch is merged.
=> Add 'Block auto-squash commits' GitHub workflow

src/GovUk.Education.ExploreEducationStatistics.Public.Data.Api/Services/DataSetService.cs, src/GovUk.Education.ExploreEducationStatistics.Public.Data.Api/Services/PublicationService.cs, src/GovUk.Education.ExploreEducationStatistics.Public.Data.Api/ViewModels/DataSetViewModels.cs, src/GovUk.Education.ExploreEducationStatistics.Public.Data.Api/ViewModels/PaginatedListViewModel.cs, src/GovUk.Education.ExploreEducationStatistics.Public.Data.Api/ViewModels/PublicationViewModels.cs
This simplifies the construction of `PaginatedListViewModel` and its subtypes as we can just use an object initializer for everything in combination with `required`.
=> EES-4716 Change PaginatedListViewModels to use `required` in public API

src/explore-education-statistics-common/src/components/ContentHtml.module.scss, src/explore-education-statistics-common/src/components/ContentHtml.tsx, src/explore-education-statistics-common/src/components/__tests__/ContentHtml.test.tsx
Fixes an accessibility issue where scrollable tables in content blocks couldn't be accessed by keyboard. This adds a `tabindex` and a focus style to fix that.
Also, the `renderTable` function in `ContentHtml.tsx` was resulting in different markup depending on if the table has a caption or not - without a caption it left in the unnecessary `figure` element that CKEditor adds. I've changed this so the `figure` is always removed.
=> EES-4407 improve keyboard accessibility for tables in content

src/explore-education-statistics-frontend/next.config.js, src/explore-education-statistics-frontend/server.js, tests/playwright-tests/tests/public/redirects.spec.ts, tests/robot-tests/tests/general_public/redirects.robot, tests/robot-tests/tests/libs/common.robot, tests/robot-tests/tests/libs/public-utilities.py
This PR reconfigures the public site to redirect using HTTP Status Code 301 rather than 308. 
NextJS uses Http Status 308 for permanent redirects, as oppose to the usual 301. This is a deliberate design choice as 308s preserve the HTTP Verb when redirecting, however 301s turn everything to a GET. Unfortunately, NextJS does not provide a configuration option to use 301s instead. Luckily, we are using a custom server, so we are able to configure redirects in Express JS before reaching Next at all. 
By default, Next sets the [trailingSlash](https://nextjs.org/docs/app/api-reference/next-config-js/trailingSlash) config to false, meaning urls ending with slashes get redirected with the slash curtailed. This behaviour is re-created in `server.js` with the 301 status code. 
We also have two …
=> EES- 4822/Use 301 for Redirects

src/explore-education-statistics-common/src/modules/table-tool/components/MultiHeaderTable.tsx, src/explore-education-statistics-common/src/modules/table-tool/components/__tests__/__snapshots__/FixedMultiHeaderDataTable.test.tsx.snap, src/explore-education-statistics-common/src/modules/table-tool/components/__tests__/__snapshots__/MultiHeaderTable.test.tsx.snap, src/explore-education-statistics-common/src/modules/table-tool/components/__tests__/__snapshots__/TimePeriodDataTable.test.tsx.snap, src/explore-education-statistics-frontend/src/modules/permalink/__tests__/__snapshots__/PermalinkPage.test.tsx.snap, src/explore-education-statistics-frontend/src/modules/table-tool/__tests__/__snapshots__/TableToolPage.test.tsx.snap, src/explore-education-statistics-frontend/src/modules/table-tool/components/__tests__/__snapshots__/TableToolFinalStep.test.tsx.snap
=> EES-4818 prevent negative numbers with symbols from wrapping

src/.editorconfig
This disables the [csharp_style_unused_value_expression_statement_preference](https://learn.microsoft.com/en-gb/dotnet/fundamentals/code-analysis/style-rules/ide0058) (IDE0058) rule as this creates lots of unnecessary suggestions where a method may return something, but nothing has been assigned to it. 
For example, given a builder like the following:
```cs
public class MyBuilder
{
public MyBuilder DoSomething()
{
return this;     
}
}
```
We'll get a suggestion for the rule:
```cs
var builder = new MyBuilder();
builder.DoSomething();  // IDE0058
// With the rule set to `discard_variable` (currently) it suggests:
_ = builder.DoSomething();
// With the rule set to `unused_local_variable` it suggests:
var unused = builder.DoSomething();
```
Either suggestions seems completely unnecessary …
=> Disable `csharp_style_unused_value_expression_statement_preference` (IDE0058)

.eslintignore
By default, Playwright will write a report to the `tests/playwright-tests/playwright-report` folder. This report contains generated javascript files which do not conform to our ES-Lint config, and cause failures when running `pnpm lint`. 
This PR simply tells ES-Lint to ignore the reports auto-generated by playwright, as we don't care about them being linted.
=> Tell ESLint to ignore the Playwright Report folder

src/explore-education-statistics-frontend/src/modules/data-catalogue/DataSetPage.module.scss, src/explore-education-statistics-frontend/src/modules/data-catalogue/DataSetPage.tsx, src/explore-education-statistics-frontend/src/modules/data-catalogue/__data__/testDataSets.ts, src/explore-education-statistics-frontend/src/modules/data-catalogue/__tests__/DataSetPage.test.tsx, src/explore-education-statistics-frontend/src/modules/data-catalogue/components/DataSetFootnotes.tsx, src/explore-education-statistics-frontend/src/modules/data-catalogue/components/DataSetPageNav.module.scss, src/explore-education-statistics-frontend/src/modules/data-catalogue/components/DataSetPageNav.tsx, src/explore-education-statistics-frontend/src/modules/data-catalogue/components/DataSetPageSection.tsx, src/explore-education-statistics-frontend/src/modules/data-catalogue/components/DataSetPreview.module.scss, src/explore-education-statistics-frontend/src/modules/data-catalogue/components/DataSetPreview.tsx, src/explore-education-statistics-frontend/src/modules/data-catalogue/components/DataSetSummary.tsx, src/explore-education-statistics-frontend/src/modules/data-catalogue/components/DataSetVariables.tsx, src/explore-education-statistics-frontend/src/modules/data-catalogue/components/__tests__/DataSetPageNav.test.tsx, src/explore-education-statistics-frontend/src/pages/data-catalogue/release/[releaseId]/data-set/[dataSetId].tsx, src/explore-education-statistics-frontend/src/queries/dataSetQueries.ts, src/explore-education-statistics-frontend/src/services/dataSetService.ts, tests/robot-tests/tests/admin_and_public/bau/data_catalogue.robot
Adds the new data set details page. The backend work is still in progress so:
- it only shows the details and 'using this data' sections
- I've created the preview, variables and footnotes sections using example data but commented them out for now.
=> EES-4959 data set details page

src/GovUk.Education.ExploreEducationStatistics.Common.Tests/Extensions/EnumUtilsTests.cs, src/GovUk.Education.ExploreEducationStatistics.Common.Tests/Utils/TimeIdentifierUtilsTests.cs, src/GovUk.Education.ExploreEducationStatistics.Common/Utils/EnumUtil.cs, src/GovUk.Education.ExploreEducationStatistics.Common/Utils/GeographicLevelUtils.cs, src/GovUk.Education.ExploreEducationStatistics.Common/Utils/TimeIdentifierUtils.cs, src/GovUk.Education.ExploreEducationStatistics.Public.Data.Api.Tests/Swagger/GeographicLevelSchemaFilterTests.cs, src/GovUk.Education.ExploreEducationStatistics.Public.Data.Api.Tests/Swagger/TimeIdentifierSchemaFilterTests.cs, src/GovUk.Education.ExploreEducationStatistics.Public.Data.Api/Swagger/GeographicLevelSchemaFilter.cs, src/GovUk.Education.ExploreEducationStatistics.Public.Data.Api/Swagger/SwaggerConfig.cs, src/GovUk.Education.ExploreEducationStatistics.Public.Data.Api/Swagger/TimeIdentifierSchemaFilter.cs, src/GovUk.Education.ExploreEducationStatistics.Public.Data.Model.Tests/Fixtures/LocationMetaGeneratorExtensions.cs
This PR provides various bits of prep work for EES-4716 by providing `TimeIdentifier` and `GeographicLevel` schema filters. These are commonly used throughout the public API and it consequently makes sense to modify their schemas so that they output their codes (instead of their default representations).
- Added various `EnumUtil` methods for extra convenience when getting enum values or labels. These are cached and should be used in preference to calling `EnumUtil.GetEnums` and iterating over it.
- Added `TimeIdentifierUtils` to separate out the `AYNTP` release-only time identifier from the rest. All other time identifiers can participate in data queries.
=> EES-4716 Part 1 - Add `TimeIdentifier` and `GeographicLevel` schema filters and enum utils

infrastructure/templates/public-api/application/virtualNetwork.bicep, infrastructure/templates/public-api/components/blobStore.bicep, infrastructure/templates/public-api/components/containerRegistry.bicep, infrastructure/templates/public-api/components/fileShares.bicep, infrastructure/templates/public-api/components/keyVault.bicep, infrastructure/templates/public-api/components/keyVaultAccessPolicy.bicep, infrastructure/templates/public-api/components/keyVaultSecret.bicep, infrastructure/templates/public-api/components/network.bicep, infrastructure/templates/public-api/components/storageAccount.bicep, infrastructure/templates/public-api/main.bicep
This PR:
- applies multiple Renovate-raised PRs to bring the API versions of various resource definitions up to date in Bicep templates
This has been tested in a test Resource Group as seen here:
=> EES-4683 - applying Renovate updates to pipeline to bring Azure resource versions up-to-date

src/GovUk.Education.ExploreEducationStatistics.Common.Tests/ModelBinding/SeparateQueryModelBinderTests.cs, src/GovUk.Education.ExploreEducationStatistics.Common.Tests/ModelBinding/TrimStringModelBinderTests.cs, src/GovUk.Education.ExploreEducationStatistics.Common/ModelBinding/QuerySeparatorAttribute.cs, src/GovUk.Education.ExploreEducationStatistics.Common/ModelBinding/SeparatedQueryModelBinder.cs, src/GovUk.Education.ExploreEducationStatistics.Common/ModelBinding/SeparatedQueryModelBinderProvider.cs
:warning: Depends on #4640 
This changes `SeparatedQueryModelBinder` so that it can bind enumerable string types from a query parameter containing comma separated strings e.g. `?items=option-1,option-2`.
Previously, this was not possible as the model binder would ignore these model types on the basis that strings often contain commas without being intended to be used as comma-separated list.
We can now enable binding to enumerable string types by adding the `QuerySeparator` attribute to the property or parameter. Note that `FromQuery` is also required.
For example:
```cs
[HttpGet("api/test")]
public ActionResult MyEndpoint([FromQuery, QuerySeparator] IList<string> items)
{
}
```
We can make a request like `GET /api/test?items=item1,item2`, and the `items` list will now be bound with …
=> EES-4716 Part 2 - Allow `SeparatedQueryModelBinder` to bind on string lists via attribute

tests/robot-tests/tests/general_public/prod_only/redirects.robot
There are two specific redirects that are remaining for now, but want to be removed once Google agrees that there is no longer any traffic going to the old route. 
For now these are tested in redirects.robot but these tests require the use of seed data. This is currently being ran in prod where there isn't any seed data. This PR effectively removes those tests for Prod (but leaves the other redirects tests).
=> EES-4987 Create Prod-Only Redirects.robot test

infrastructure/templates/public-api/components/functionApp.bicep, infrastructure/templates/public-api/components/postgresqlDatabase.bicep, infrastructure/templates/public-api/main.bicep
This PR:
- Temporarily renames some Public API resources whilst we wait for deleted resources in our test Resource Group to be purged (after 30 days)
- Adds the "WEBSITE_CONTENTOVERVNET" setting to the Function App to allow it to connect correctly to pre-existing and locked-down Core Storage accounts in the real EES Resource Groups.
The reason we need to amend the names of some resources whilst deploying to the EES Dev Resource Group is that previously we had trialled this deploy process in a Hive Resource Group to prove that it would all work, but in doing so we inadvertently reserved the names of the PSQL server and Function App within that group.
Even after deleting from the test Resource Group, the names remain reserved until a 30 day cooling off period whereby Azure will purge the …
=> EES-4683 - temp renaming of resources to avoid name clashes with deleted resources. Configuring Function App for connection to secure core storage.

infrastructure/parameters/dev.parameters.json, infrastructure/parameters/pre-prod.parameters.json, infrastructure/parameters/test.parameters.json, infrastructure/templates/template.json, src/GovUk.Education.ExploreEducationStatistics.Publisher/Functions/PublishScheduledReleasesFunction.cs, src/GovUk.Education.ExploreEducationStatistics.Publisher/Functions/StageScheduledReleasesFunction.cs, src/GovUk.Education.ExploreEducationStatistics.Publisher/README.md, tests/robot-tests/tests/libs/admin-utilities.py
This change is being made after @N-moh raised the issue of the Publisher README instructions about forcing of immediate publishing of scheduled release version's being outdated.
After the renaming of `Release` -> `ReleaseVersion` made by #4611, the key `releaseIds` in the body of the requests was changed to `releaseVersionIds`.
This means all examples in the README such as...
```
"releaseIds": ["6f6d5510-9f16-40ce-bc39-0dd88aa5e6ea", "c540405b-dc86-42fe-9420-3c3f007a48ef"]
```
needed to become...
```
"releaseVersionIds": ["6f6d5510-9f16-40ce-bc39-0dd88aa5e6ea", "c540405b-dc86-42fe-9420-3c3f007a48ef"]
```
At the same time as updating the README for this change I have also renamed the functions themselves to be consistently named for release versions rather than releases.
=> EES-4668 Update names of Publisher functions and README

src/explore-education-statistics-admin/src/components/editable/EditableContentBlock.tsx, src/explore-education-statistics-admin/src/components/editable/EditableContentForm.tsx, src/explore-education-statistics-admin/src/components/editable/__tests__/EditableContentForm.test.tsx, src/explore-education-statistics-common/src/utils/sanitizeHtml.ts
Fixes a bug where the tags around comments in release content were sometimes being lost on save. This was due to inconsistent sanitisation on the content on manual save and autosaving.
=> EES-4988 consistent sanitising of editable content

src/explore-education-statistics-common/src/components/Tabs.tsx, src/explore-education-statistics-common/src/modules/charts/components/MapGeoJSON.tsx, src/explore-education-statistics-common/src/modules/find-statistics/components/DataBlockTabs.tsx
Fixed two issues with maps:
1. Maps in release headlines weren't loading correctly. Making the tab `lazy` fixes this but caused an issue with maps in content accordions, to handle this I've updated `Tabs.tsx` to check for a hash in the url before setting the selected tab.
2. The order of the svg paths isn't stable - sometimes the whole UK path is loaded first, sometimes last, causing the UK outline to sometimes overlap the individual areas resulting in a blurry effect. Trying to set the UK to always be at the back didn't work so instead I've removed the outline on the UK as it was barely visible anyway.
=> EES-5005 fix maps in release headlines

src/explore-education-statistics-common/src/components/Tabs.tsx
Release pages with tabs on were erroring when they were server rendered. This fixes that by moving the check for the `window.location.hash` into a `useEffect`, with a check that `window` exists to be doubly safe.
=> EES-5020 fix server rendered release pages

src/GovUk.Education.ExploreEducationStatistics.Common.Tests/Extensions/ValidationProblemViewModelTestExtensions.cs, src/GovUk.Education.ExploreEducationStatistics.Public.Data.Api.Tests/Controllers/DataSetsControllerTests.cs, src/GovUk.Education.ExploreEducationStatistics.Public.Data.Api.Tests/Controllers/PublicationsControllerTests.cs, src/GovUk.Education.ExploreEducationStatistics.Public.Data.Api.Tests/Fixture/IntegrationTestFixture.cs, src/GovUk.Education.ExploreEducationStatistics.Public.Data.Api.Tests/Services/ContentApiClientTests.cs, src/GovUk.Education.ExploreEducationStatistics.Public.Data.Api/Controllers/DataSetsController.cs, src/GovUk.Education.ExploreEducationStatistics.Public.Data.Api/Controllers/PublicationsController.cs, src/GovUk.Education.ExploreEducationStatistics.Public.Data.Api/Model/DataSetMetaType.cs, src/GovUk.Education.ExploreEducationStatistics.Public.Data.Api/Model/MetadataType.cs, src/GovUk.Education.ExploreEducationStatistics.Public.Data.Api/Requests/DataSetMetaRequest.cs, src/GovUk.Education.ExploreEducationStatistics.Public.Data.Api/Security/AnonymousAuthenticationHandler.cs, src/GovUk.Education.ExploreEducationStatistics.Public.Data.Api/Services/ContentApiClient.cs, src/GovUk.Education.ExploreEducationStatistics.Public.Data.Api/Services/DataSetService.cs, src/GovUk.Education.ExploreEducationStatistics.Public.Data.Api/Services/Interfaces/IDataSetService.cs, src/GovUk.Education.ExploreEducationStatistics.Public.Data.Api/Services/PublicationService.cs, src/GovUk.Education.ExploreEducationStatistics.Public.Data.Api/Startup.cs
Adding an optional query parameter, `types`, to the endpoint for retrieving the metadata for a single Data Set Version.
The endpoint lives at `api/v1/data-sets/{dataSetId}/meta?types=Filters,Indicators,Locations,TimePeriods`.
The `types` query parameter is _optional_, and expects a comma-separated list of metadata types to filter the results by. The accepted values are:
- `Filters` - include all metadata associated with the *filters* of the requested data set version
- `Indicators` - include all metadata associated with the *indicators* of the requested data set version
- `Locations` - include all metadata associated with the *locations* of the requested data set version
- `TimePeriods` - include all metadata associated with the *time periods* of the requested data set version
_(Any …
=> EES-4711 Adding optional query parameter `types` to the metadata endpoint

src/explore-education-statistics-frontend/src/middleware/pages/__tests__/redirectPages.test.ts, src/explore-education-statistics-frontend/src/middleware/pages/redirectPages.ts
Routes such as https://explore-education-statistics.service.gov.uk/methodology/%5bpublication%5d are getting infinitely redirected in the live environments (but not locally). 
In the Azure Portal we can see that on each redirect, characters that need to be URL encoded are being encoded with capitals (see attached pic 1). I still don't know why this is, but I suspect it might be getting picked up by the Redirects middleware which tries to redirect to a lowercased URL every time (see attached pic 2). 
This PR attempts to only invoke that redirect if the decoded URL contains capitals, hoping to leave url encoding alone. It also updates the redirects to use status code 301 rather than 307 while we're at it.
=> Only perform URL lowercasing on decoded strings

infrastructure/templates/template.json
This PR makes a slight amendment to two Notifier email template id's to make them consistent with the other template id variable names.
=> EES-4535 Make Notifier template id variable naming consistent

infrastructure/templates/template.json
This PR enables "Always on" for the Notifier Azure Function app in the same way that it's enabled for the other two apps.
The documentation says the following:
> If you run on an App Service plan, you should enable the Always on setting so that your function app runs correctly.
It should also fix this warning we see in Azure Portal:
=> EES-4535 Enable "Always on" in Notifier Azure Function app

infrastructure/parameters/test.parameters.json
This PR will allow us to test whether we can still disable the Azure Functions which trigger scheduled publishing of release versions immediately after the switch to use the 'Isolated worker' model by #4673.
With the switch from using the ‘In process’ model to the ‘Isolated worker’ model there is some uncertainty about whether functions using the ‘Isolated worker' model can be disabled, so we need to test this.
The functions which we allow to be disabled are `StageScheduledReleaseVersionsImmediately` and `PublishStagedReleaseVersionContentImmediately`.
The functions and how to use them are documented in the [Publisher's README](https://github.com/dfe-analytical-services/explore-education-statistics/tree/dev/src/GovUk.Education.ExploreEducationStatistics.Publisher#readme).
We will test the …
=> EES-5012 Test disabling the ability to trigger scheduled publishing of release versions immediately

infrastructure/parameters/test.parameters.json
This reverts commit 67fde93c775d6288793ee64b15cc03814a271097 made by #4693.
That was a test to ensure we can disable some of the Publisher's Azure Functions after #4673.
The test was successful and we don't need to make any further changes.
=> Revert config change made for EES-5012 in #4693

global.json
This PR lowers the required .NET version from `8.0.203` to `8.0.202`. This is necessary as no `8.0.203` has been published to the Microsoft PPA on Linux, meaning any `dotnet` commands bail upon detecting the wrong installed version.
=> EES-5029 Downgrade .NET 8 version to acceptable number for Linux

src/GovUk.Education.ExploreEducationStatistics.Public.Data.Api/Startup.cs
Previously we were seeing the error `System.InvalidOperationException: No service for type 'GovUk.Education.ExploreEducationStatistics.Public.Data.Api.Options.ContentApiOptions' has been registered.`
This PR changes the type of service from `ContentApiOptions` to `IOptions<ContentApiOptions>` in order to retrieve the options.
=> EES-4705 EES-4706 Fix accessing ContentApiOptions while configuring ContentApiClient

src/explore-education-statistics-frontend/src/components/UserTestingBanner.tsx, src/explore-education-statistics-frontend/src/hooks/useCookies.ts
Updates the link in the user testing banner and the cookie version so it will be re-shown to all users.
=> EES-5034 update user testing banner

src/explore-education-statistics-common/src/modules/charts/components/CustomTooltip.tsx, src/explore-education-statistics-common/src/modules/charts/components/HorizontalBarBlock.tsx, src/explore-education-statistics-common/src/modules/charts/components/LineChartBlock.tsx, src/explore-education-statistics-common/src/modules/charts/components/VerticalBarBlock.tsx, src/explore-education-statistics-common/src/modules/charts/components/hooks/useLegend.ts
Fixes issues with inconsistent ordering in tooltips and legends
**Before:** three different orders!
- tooltip list is ordered by value
- legend list is ordered by data set order
- bars are ordered by reversed data set order
**After:** they are now consistently ordered by reversed data set order  (note that it's the reversed data set order as that's how recharts stacks them, it could be changed but not without affecting existing charts).
**Before:** tootlip list order is wrong
- tooltip list is ordered by value
- legend list is ordered by data set order
- bars are ordered by data set order
**After:** tooltip, legend and bars are ordered by data set order
No change - tooltip is ordered by value and legend is ordered by data set order.
=> EES-4865 consistent order in bar chart tooltip, bars and legend

src/GovUk.Education.ExploreEducationStatistics.Admin.Tests/Controllers/Api/Security/SignInControllerTests.cs
This fixes a backend unit test that started failing when we started daylight savings time.
=> EES-5035 Change backend unit test to handle daylight savings time

azure-pipelines.dfe.yml
This PR:
- Fixes the issue whereby no Content or Data API artifacts were published for consumption by the Release pipeline.  Added the "Publish Public frontend API Artifacts" Task back in to fix this.
- Separates out the "buildAndPush" Docker tasks into "build" and "push" tasks, as the combined "buildAndPush" command ignores the "arguments" parameter and so we lose the Build Number form the public frontend :angry: 
- Removes some unnecessary parameters from the "push" commands, as previously we were including several parameters that were only applicable to the "build" comment
- Removes "addPipelineData", as this defaults to true anyway.
=> EES-4807 - fixes to main EES build pipeline

.husky/pre-commit, package.json
Removes the `.next` folder during a `pnpm clean` command. Also checks for the existence of `node_modules` before running `lint-staged`, as this command otherwise throws an error if you haven't ever ran `pnpm i`.
=> Remove the .next folder during the pnpm clean command

tests/playwright-tests/.env.example, tests/playwright-tests/playwright.config.ts, tests/playwright-tests/tests/public/redirects.spec.ts, tests/playwright-tests/utils/env.ts
Whilst we were reviewing Playwright as a tool and deciding whether or not to proceed, I used it to automate my testing of all the new SEO redirects locally. 
I then forgot to go back and remove this before the Playwright tests were included in the pipelines. 
This PR skips the big lengthy redirect test, and also replaces an occurrence of `localhost` with the correct environment base url.
=> Remove ad hoc Playwright test from pipeline

src/explore-education-statistics-admin/src/pages/release/datablocks/components/chart/ChartAxisConfiguration.tsx, src/explore-education-statistics-admin/src/pages/release/datablocks/components/chart/ChartReferenceLineConfigurationForm.tsx, src/explore-education-statistics-admin/src/pages/release/datablocks/components/chart/ChartReferenceLinesConfiguration.tsx, src/explore-education-statistics-admin/src/pages/release/datablocks/components/chart/__tests__/ChartAxisConfiguration.test.tsx, src/explore-education-statistics-admin/src/pages/release/datablocks/components/chart/__tests__/ChartReferenceLinesConfiguration.test.tsx, src/explore-education-statistics-common/src/modules/charts/components/CustomReferenceLineLabel.tsx, src/explore-education-statistics-common/src/modules/charts/components/VerticalBarBlock.tsx, src/explore-education-statistics-common/src/modules/charts/components/utils/createReferenceLine.tsx, src/explore-education-statistics-common/src/modules/charts/types/chart.ts, src/explore-education-statistics-common/src/modules/charts/types/referenceLinePosition.ts
Adds the ability to position reference lines between data points on the major axis on vertical bar charts (they can't be added on other types of chart).
Recharts doesn't allow reference lines to be positioned like this: "If the specified x-axis is a category axis, the value of x must be one of the categorys (sic), otherwise no line will be drawn" (https://recharts.org/en-US/api/ReferenceLine), so I've had to be a bit 'creative':
- the reference line is added to the major axis configuration
- when the chart is rendered it:
- moves the line to the minor axis, so the line is rendered horizontally between the two points
- in `CustomReferenceLineLabel` it draws a new line perpendicular to the existing one, using the `viewbox`, chart height and margin to calculate its position
-  hides the …
=> EES-5067 add ref lines between data points on major axis

src/explore-education-statistics-frontend/src/components/FilterClearButton.module.scss
Each time we start the frontend project we're currently getting warnings produced by the `GovUk Frontend` package because we're using a font value that will be deprecated in the next version. Following the guidance here - https://design-system.service.gov.uk/get-started/new-type-scale/ - this PR updates the font to the next lowest value.
=> Resolve GovUk-Frontend warnings

.github/workflows/validate-snapshots.yml, infrastructure/parameters/dev.parameters.json, infrastructure/parameters/pre-prod.parameters.json, infrastructure/parameters/prod.parameters.json, infrastructure/parameters/test.parameters.json, infrastructure/templates/datafactory/components/db-maintenance-template.json, infrastructure/templates/datafactory/template.json, infrastructure/templates/template.json, tests/robot-tests/.env.example, tests/robot-tests/scripts/create_snapshots.py, tests/robot-tests/tests/libs/slack.py
Various webhooks were implemented by a colleague who has since left the team. Deactivating their Slack account causes the integrations to be removed, thus losing the various features integrated by custom scripts and third party apps. The independent "Incoming Webhooks" Slack app is also deprecated, and has been superseded by webhooks and APIs which can be implemented by a custom Slack workspace app. This method also allows additional "collaborators" to view and edit the app's config, and reinstall to the workspace when necessary, without the reliance on a single user account.
The changes replace existing "Incoming Webook" and custom app behaviour with a single custom app, currently named EESBot".
The options considered during development were:
1. Custom hand-written API, implementing the …
=> EES-4704: Rewrite existing Slack Integrations from webhooks to Slack Apps

pnpm-lock.yaml, src/explore-education-statistics-admin/package.json, src/explore-education-statistics-admin/src/pages/release/pre-release/PreReleasePageContainer.tsx, src/explore-education-statistics-admin/src/pages/release/pre-release/__tests__/PreReleasePageContainer.test.tsx, src/explore-education-statistics-common/package.json, src/explore-education-statistics-frontend/package.json, tests/robot-tests/tests/admin/bau/prerelease.robot, tests/robot-tests/tests/libs/utilities.py
There's a frontend bug caused by the Pre-Release Access screen not correctly accommodating GMT/BST changes. 
The `start` date of the PRA period comes from the backend as GMT. During winter this will be midnight on the first day of PRA, but during summer this will be 23:00 on the day BEFORE the start of PRA. The frontend needs to convert the GMT time to BST, but only during BST dates. 
Native Javascript dates don't accommodate timezones at all, and neither does the `date-fns` package that we use out of the box. Luckily, there's an extension to it which lets us do this -> https://www.npmjs.com/package/date-fns-tz
=> EES-5036 Accomodate BST and GMT changes in PRA frontend

src/GovUk.Education.ExploreEducationStatistics.Public.Data.Model.Tests/Fixtures/DataSetVersionGeneratorExtensions.cs, src/GovUk.Education.ExploreEducationStatistics.Public.Data.Model.Tests/Fixtures/DataSetVersionImportGeneratorExtensions.cs, src/GovUk.Education.ExploreEducationStatistics.Public.Data.Model/DataSetVersion.cs, src/GovUk.Education.ExploreEducationStatistics.Public.Data.Model/DataSetVersionImport.cs, src/GovUk.Education.ExploreEducationStatistics.Public.Data.Model/DataSetVersionImportStatus.cs, src/GovUk.Education.ExploreEducationStatistics.Public.Data.Model/Database/PublicDataDbContext.cs, src/GovUk.Education.ExploreEducationStatistics.Public.Data.Model/Migrations/20240416122016_InitialMigration.Designer.cs, src/GovUk.Education.ExploreEducationStatistics.Public.Data.Model/Migrations/20240416122016_InitialMigration.cs, src/GovUk.Education.ExploreEducationStatistics.Public.Data.Model/Migrations/PublicDataDbContextModelSnapshot.cs
This PR adds `DataSetVersionImport` to the Public Data model in advance of the Public Data Processor being developed to allow files to be imported.
This is being added early to unblock other tickets which are going to rely on checking the status of imports.
[EES-4905 - Create an endpoint for API dataset import statuses](https://dfedigital.atlassian.net/browse/EES-4905)
[EES-4906 - Create an endpoint for listing subjects that can become API datasets](https://dfedigital.atlassian.net/browse/EES-4906)
[EES-4909 - Include API Datasets in the publishing model](https://dfedigital.atlassian.net/browse/EES-4909)
After the new database table is added there is a new version of `InitialMigration` and a new seed data database `public-api-8.zip`.
=> EES-5070 Add `DataSetVersionImport` to the Public Data model

src/explore-education-statistics-admin/src/pages/release/datablocks/components/chart/ChartReferenceLinesConfiguration.tsx, src/explore-education-statistics-common/src/modules/charts/components/CustomReferenceLineLabel.tsx, src/explore-education-statistics-common/src/modules/charts/components/utils/getReferenceLineLabelPosition.ts
Fixes two issues found in testing reference lines between data points on the x axis:
- when the y axis is in percentages and the y axis position is not the top value the label was being positioned in the wrong place. 
- if you added a line between data points and changed to a chart type that doesn't support them the line would still be in the list.
=> EES-5067 fix perpendicular ref line bugs

infrastructure/templates/template.json
This change is an attempt to prevent Infra deploys that use the ARM templates from trying to remove Public API subnets when the shared VNet is being "deployed".
Previously, using the "subnets" array field of the VNet resource itself would cause the deploy to attempt to remove any subnets that weren't referenced there.
This change in structure now breaks this reliance, and instead maintains subnets as separate standalone Resources to set up after the VNet is in place.  As we're using Incremental deploy, this should leave the subnets that don't get a mention here alone.
=> EES-4806 - updating ARM template structure to define subnets as standalone resources

infrastructure/templates/template.json
Placeholder until support for https://techcommunity.microsoft.com/t5/azure-networking-blog/azure-virtual-network-now-supports-updates-without-subnet/ba-p/4067952 is available to us.
=> EES-4806 - reinstated "subnets" property of VNet declaration, with additional Public API subnets

infrastructure/parameters/dev.parameters.json, infrastructure/parameters/pre-prod.parameters.json, infrastructure/parameters/prod.parameters.json, infrastructure/parameters/test.parameters.json, infrastructure/templates/template.json, src/GovUk.Education.ExploreEducationStatistics.Admin/Startup.cs, src/GovUk.Education.ExploreEducationStatistics.Admin/appsettings.Development.json
This PR configures the Admin's connection to the Public Data PostgreSQL database in Azure environments.
It builds on configuration for the Admin's connection to this database already added by EES-4908 in https://github.com/dfe-analytical-services/explore-education-statistics/pull/4745. This added configuration for the database connection in the local environment.
Connecting in Azure environments depends on the Admin having its own database principal in the Public Data database.
This is a manual step that will happen when the database is available in each environment.
It also relies on the Admin's database principal being granted permissions on tables in the database. Configuration to add this automatically was added by https://github.com/dfe-analytical-services/explore-education-statistics …
=> EES-5049 Configure Admin's connection to the Public Data PostgreSQL database in Azure environments

infrastructure/templates/logic-app-template.json, infrastructure/templates/template.json
This PR adds the logic app linked template which was missing from the commit on https://github.com/dfe-analytical-services/explore-education-statistics/pull/4779
=> EES-4704 Move logic app to linked template

src/GovUk.Education.ExploreEducationStatistics.Admin.Tests/Services/ReleaseAmendmentServiceTests.cs, src/GovUk.Education.ExploreEducationStatistics.Admin.Tests/Services/ReplacementServiceHelperTests.cs, src/GovUk.Education.ExploreEducationStatistics.Admin.Tests/Services/ReplacementServiceTests.cs, src/GovUk.Education.ExploreEducationStatistics.Admin/Controllers/Api/Bau/ReleaseFileSequenceMigrationController.cs, src/GovUk.Education.ExploreEducationStatistics.Admin/Migrations/ContentMigrations/20240412142956_EES5062_AddFilterSequenceAndIndicatorSequenceToReleaseFile.Designer.cs, src/GovUk.Education.ExploreEducationStatistics.Admin/Migrations/ContentMigrations/20240412142956_EES5062_AddFilterSequenceAndIndicatorSequenceToReleaseFile.cs, src/GovUk.Education.ExploreEducationStatistics.Admin/Services/ReleaseAmendmentService.cs, src/GovUk.Education.ExploreEducationStatistics.Admin/Services/ReplacementService.cs, src/GovUk.Education.ExploreEducationStatistics.Admin/Services/ReplacementServiceHelper.cs, src/GovUk.Education.ExploreEducationStatistics.Content.Model/Database/ContentDbContext.cs, src/GovUk.Education.ExploreEducationStatistics.Content.Model/ReleaseFile.cs, src/GovUk.Education.ExploreEducationStatistics.Data.Model/Database/StatisticsDbContext.cs, src/GovUk.Education.ExploreEducationStatistics.Data.Model/GovUk.Education.ExploreEducationStatistics.Data.Model.csproj, src/GovUk.Education.ExploreEducationStatistics.Data.Model/ReleaseSubject.cs, src/GovUk.Education.ExploreEducationStatistics.Data.Services.Tests/ReleaseServiceTests.cs, src/GovUk.Education.ExploreEducationStatistics.Data.Services.Tests/SubjectMetaServicePermissionTests.cs, src/GovUk.Education.ExploreEducationStatistics.Data.Services.Tests/SubjectMetaServiceTests.cs, src/GovUk.Education.ExploreEducationStatistics.Data.Services.Tests/Utils/FiltersMetaViewModelBuilderTests.cs, src/GovUk.Education.ExploreEducationStatistics.Data.Services.Tests/Utils/IndicatorsMetaViewModelBuilderTests.cs, src/GovUk.Education.ExploreEducationStatistics.Data.Services/ReleaseService.cs, src/GovUk.Education.ExploreEducationStatistics.Data.Services/SubjectMetaService.cs, src/GovUk.Education.ExploreEducationStatistics.Data.Services/SubjectResultMetaService.cs, src/GovUk.Education.ExploreEducationStatistics.Data.Services/Utils/FiltersMetaViewModelBuilder.cs, src/GovUk.Education.ExploreEducationStatistics.Data.Services/Utils/IndicatorsMetaViewModelBuilder.cs
This PR moves `ReleaseSubject.FilterSequence` and `IndicatorSequence` into `ReleaseFile`.
This is being done in preparation for introducing `DataSetFileMeta`. Without moving these values first, when listing all data sets on the Data catalogue page, we'd be forced to query both the content and statistics databases.
After this work is deployed, we can then remove `FilterSequence` and `IndicatorSequence` from `ReleaseSubject`.
=> EES-5062 Move FilterSequence and IndicatorSequence from ReleaseSubject to ReleaseFile

.eslintrc.json
We currently see a warning when running `pnpm lint` or `pnpm start frontend`, telling us that the "Pages directory cannot be found at .". This is because of a rule in the `@next/next/recommended` plugin which requires the root of the pages directory in a NextJS app. If the pages directory does not live in the project route, it needs to be given a manual path.
We have to configure two paths in our case, because `pnpm lint` runs from the repository root, but `pnpm start frontend` will ultimately end up running from `src/explore-education-statistics-frontend/`. Luckily, it's smart enough to accept an array and not complain about incorrect paths so long as one of them finds a `pages` directory.  
https://nextjs.org/docs/messages/no-html-link-for-pages#options
=> Ees xxxx/resolve no html link for pages error

src/GovUk.Education.ExploreEducationStatistics.Notifier/Functions/SubscriptionManager.cs, src/explore-education-statistics-frontend/src/modules/subscriptions/VerificationErrorPage.tsx, src/explore-education-statistics-frontend/src/pages/subscriptions/verification-error.tsx
Public website users subscribing to publication notifications were presented with a generic, non-user-friendly error message if they attempted to verify their email address after the verification token had expired.
This change adds an error page matching existing error page format and style (and meeting the GDS standards) to inform users of the issue, and how to resolve it.
=> EES-3192: Add error page redirection to Notifier on verification failure

src/GovUk.Education.ExploreEducationStatistics.Content.Model.Tests/NamingUtilTests.cs, src/explore-education-statistics-common/src/utils/__tests__/slugFromTitle.test.tsx, src/explore-education-statistics-common/src/utils/slugFromTitle.ts, tests/robot-tests/tests/admin_and_public_2/bau/publish_methodology_publication_update.robot
This PR fixes incorrect slugs being shown when updating publication titles. Previously, titles like `My test - publication` would result in a slug like `my-test---publication`. With the fix, this is now `my-test-publication`.
As part of this, we've also updated the `publish_methodology_publication_update.robot` suite, which would previously fail on parallel test runs due to having a publication title that is a duplicate of another test suite (`publish_publication_update.robot`). It's likely that the publication title used in `publish_methodology_publication_update.robot` had previously been non-standard to avoid this slug issue.
=> EES-5085 Fix incorrect slugs for updated publication titles with dashes and spaces

src/explore-education-statistics-common/src/modules/charts/components/HorizontalBarBlock.tsx, src/explore-education-statistics-common/src/modules/charts/components/LineChartBlock.tsx, src/explore-education-statistics-common/src/modules/charts/components/VerticalBarBlock.tsx, src/explore-education-statistics-common/src/modules/charts/components/hooks/useLegend.ts
Fixes a bug where the 'Explore data' link on data blocks sometimes didn't work. This was caused by vertical bar charts with stacked bars constantly re-rendering, which blocked the thread and prevented the link working. The re-renders were caused by  the changes to `useLegend` in https://github.com/dfe-analytical-services/explore-education-statistics/pull/4705 so I've reverted that change and implemented legend item ordering differently.
=> EES-5080 fix vertical bar chart re-rendering

tests/robot-tests/tests/admin_and_public_2/bau/publish_release_and_amend.robot, tests/robot-tests/tests/libs/utilities.py
This PR fixes a failing test in `publish_release_and_amend.robot` - specifically `Verify Dates data block accordion section`.
What I believe was happening was that `${section}` was being loaded before the accordion content section had finished loading. This meant that when it went to check for the chart title inside `${section}` it failed.
The fix is to ensure that the accordion content section has loaded.
I also fixed an amusing mistake in a comment - I'll leave it as a puzzle for the reader as to how the brackets made their way into the comment.
=> EES-5090 Fix failing UI test

src/explore-education-statistics-common/src/components/form/FormFieldset.tsx, src/explore-education-statistics-common/test/render.tsx, src/explore-education-statistics-frontend/src/modules/data-catalogue/DataCataloguePageNew.tsx, src/explore-education-statistics-frontend/src/modules/data-catalogue/__data__/testDataSets.ts, src/explore-education-statistics-frontend/src/modules/data-catalogue/components/DataSetFileSummary.tsx, src/explore-education-statistics-frontend/src/modules/data-catalogue/components/Filters.module.scss, src/explore-education-statistics-frontend/src/modules/data-catalogue/components/Filters.tsx, src/explore-education-statistics-frontend/src/modules/data-catalogue/components/__tests__/DataSetSummary.test.tsx, src/explore-education-statistics-frontend/src/modules/data-catalogue/components/__tests__/Filters.test.tsx, src/explore-education-statistics-frontend/src/modules/data-catalogue/utils/createDataSetFileListRequest.ts, src/explore-education-statistics-frontend/src/services/dataSetFileService.ts, tests/robot-tests/tests/admin_and_public/bau/data_catalogue.robot
- Adds an 'Available by API' tag to data sets with APIs on the data catalogue page. 
- Adds a filter to toggle between all data sets and only those with APIs
- Needs to be tested with the backend once that's ready
=> EES-4995 show API data sets tag and allow filtering

src/explore-education-statistics-frontend/server.js, tests/playwright-tests/tests/public/redirects.spec.ts, tests/robot-tests/tests/general_public/redirects.robot
These redirects have been present on the site for several months now (much longer if you count the time for which they were 307s/308s). This should've been long enough for Google to pick up the new canonical address.
=> EES-4979 Remove meta-guidance and data-guidance redirects

src/GovUk.Education.ExploreEducationStatistics.Common.Tests/Extensions/HttpResponseMessageTestExtensions.cs, src/GovUk.Education.ExploreEducationStatistics.Content.Api.Tests/Controllers/SecurityHeadersTests.cs, src/GovUk.Education.ExploreEducationStatistics.Content.Api/SeoSecurityHeaderMiddleware.cs, src/GovUk.Education.ExploreEducationStatistics.Content.Api/Startup.cs, src/GovUk.Education.ExploreEducationStatistics.sln.DotSettings
One of Michael's briefs from the SEO document asks us to implement security headers in [these urls](https://docs.google.com/spreadsheets/d/1Hqha2UHV-0L0dqOFFIo-UJRsLUgzFK3Lhz9Uq57k_6U/edit#gid=1737967479). 
They all come from the Content API, and are links that Google has picked up on whilst trawling the site. 
I don't think adding these headers actually makes a lick of difference to an API that just returns JSON, but if it makes the SEO gods happy :shrug:
=> EES-5002 Add content security headers to the Content API for SEO reasons

pnpm-lock.yaml, src/explore-education-statistics-admin/package.json, src/explore-education-statistics-common/package.json
Updates react-lazyload now they've published the React 18 version.
=> chore (deps): update react-lazyload

src/explore-education-statistics-frontend/src/modules/data-catalogue/DataCataloguePageNew.tsx
Adjusts the position of the 'View this release' link on the new data catalogue page so it's always positioned under the tags.
=> EES-4881 adjust view release link position on data catalogue

src/explore-education-statistics-frontend/redirects.js, src/explore-education-statistics-frontend/server.js
Marking this as DRAFT because I really think there must be a different way of handling this. 
Google has picked up a slew of incorrect routes, which return a 404 because they don't match a path that NextJS can serve. Michael's brief requests us to add a redirect map (in [ticket](https://dfedigital.atlassian.net/browse/EES-4802)) with a status code of 301, for long enough that Google removes them from its indexes. 
We could do this in the custom server or in the NextJS middleware, but I'm using the custom server for full control over the status code, and the ability to redirect the trailingSlash with a 301 rather than a 307. 
What I don't quite see is why this is necessary, and what stops Google from just picking up more incorrect routes, given that there are literally infinite incorrect …
=> DRAFT: EES-4802 Re-apply redirect map

src/GovUk.Education.ExploreEducationStatistics.Admin/Requests/FootnoteCreateRequest.cs, src/explore-education-statistics-admin/src/pages/release/content/components/EditableKeyStatDataBlockForm.tsx, src/explore-education-statistics-admin/src/pages/release/content/components/EditableKeyStatTextForm.tsx, src/explore-education-statistics-admin/src/pages/release/content/components/__tests__/EditableKeyStatDataBlockForm.test.tsx, src/explore-education-statistics-admin/src/pages/release/content/components/__tests__/EditableKeyStatText.test.tsx, src/explore-education-statistics-admin/src/pages/release/content/components/__tests__/EditableKeyStatTextForm.test.tsx, src/explore-education-statistics-admin/src/pages/release/data/components/ReleaseDataGuidanceSection.tsx
- Trim whitespace from release footnotes
- Convert key stat guidance fields (text and data block) from CKEditor to standard textareas to remove formatting options and enforce simple text content.
=> EES-4353: Trim whitespace and convert fields from CKEditor to textareas.

infrastructure/templates/public-api/api-infrastructure-pipeline.yml, infrastructure/templates/public-api/application/virtualNetwork.bicep, infrastructure/templates/public-api/components/containerAppEnvironment.bicep, infrastructure/templates/public-api/components/postgresqlDatabase.bicep, infrastructure/templates/public-api/deploy-stage-template.yml, infrastructure/templates/public-api/main.bicep, infrastructure/templates/public-api/validate-stage-template.yml, infrastructure/templates/template.json, src/GovUk.Education.ExploreEducationStatistics.Public.Data.Model/Migrations/20240427023845_InitialMigration.cs
This PR:
- changes Container App Environment to be internal rather than having a Public IP address, in preparation for adding an Application Gateway in front, as requested by the Security Architecture group.
- adds in a conditional flag to omit the Container App from deployment until a user-assigned managed identity has been created and assigned the AcrPull role.
- swaps out the conditional inclusion of chunks of YAML in the pipeline for different environments (which turned out not to be working!) with "condition" property on Stages based on the current branch.
- removes PSQL VNet integration in favour of enabling public SQL access to whitelisted IP address ranges, as per existing SQL Server setups.  In the future this will be resolved for VNet traffic by EES-5052, by adding a Private …
=> Ees 4807 small tweaks after merge

src/GovUk.Education.ExploreEducationStatistics.Common.Tests/Extensions/ValidationFailureExtensionsTests.cs, src/GovUk.Education.ExploreEducationStatistics.Common.Tests/ViewModels/ErrorViewModelTests.cs, src/GovUk.Education.ExploreEducationStatistics.Common/Config/FluentValidationActionFilter.cs, src/GovUk.Education.ExploreEducationStatistics.Common/Extensions/FluentValidationExtensions.cs, src/GovUk.Education.ExploreEducationStatistics.Common/Extensions/ValidationFailureExtensions.cs, src/GovUk.Education.ExploreEducationStatistics.Common/ViewModels/ErrorViewModel.cs, src/GovUk.Education.ExploreEducationStatistics.Public.Data.Processor/Functions/ProcessorFunction.cs
This PR adds the ability to construct `ErrorViewModel` directly from FluentValidation's `ValidationFailure` outside of `FluentValidationActionFilter` i.e. when calling `IValidator.Validate` manually.
We've also added an extension for `IValidator<T>` that returns a `Task<Either<ActionResult, T>`, which allows the validation call to integrate into Either returning chains.
=> EES-5095 Add ability to create ErrorViewModels from ValidationFailure directly

src/explore-education-statistics-common/src/components/form/rhf/RHFFormFieldCheckboxGroupsMenu.tsx, src/explore-education-statistics-common/src/components/form/rhf/RHFFormFieldCheckboxMenu.tsx, src/explore-education-statistics-common/src/modules/table-tool/components/LocationFiltersForm.tsx, src/explore-education-statistics-frontend/src/modules/table-tool/TableToolPage.tsx, src/explore-education-statistics-frontend/src/modules/table-tool/__tests__/TableToolPage.test.tsx
Allows you to link directly to the table tool at step 3 (locations) with the publication, release (optional) and data set pre-selected. 
- `/data-tables/<publication-slug>?subjectId=<subject-id>`
- `/data-tables/<publication-slug>/<release-slug>?subjectId=<subject-id>`
I've added ids to `RHFFormFieldCheckboxGroupsMenu` and `RHFFormFieldCheckboxMenu` as without them the generated ids on the `Details` component cause a hydration error.
=> EES-5122 allow linking to step 3 of table tool

src/GovUk.Education.ExploreEducationStatistics.Admin/GovUk.Education.ExploreEducationStatistics.Admin.csproj, src/GovUk.Education.ExploreEducationStatistics.Admin/appsettings.Development.json, src/GovUk.Education.ExploreEducationStatistics.Publisher/appsettings.json
This PR:
- defaults "PublicDataDbExists" to false in local development
- allows overriding by adding the following to a new `appsettings.Local.json` in Admin and Publisher:
```
{
"PublicDataDbExists": true
}
```
=> EES-4909 - defaulting PublicDataDbExists to false, and allowing overriding in Admin and Publisher

tests/robot-tests/tests/libs/admin-common.robot
Fixes adding data guidance in the UI tests now CKeditor has been removed. I'm not sure if there are other failures as my local won't publish!
=> Fix data guidance in Ui tests

src/explore-education-statistics-admin/src/pages/release/data/components/ReleaseDataGuidanceSection.tsx
The main data guidance field was inadvertently changed in https://github.com/dfe-analytical-services/explore-education-statistics/pull/4819 to remove CKEditor, this reverts that change. 
The individual file data guidance fields should still use normal text fields not CKEditor.
=> EES-4353 use ckeditor for main data guidance field

tests/robot-tests/tests/admin_and_public/bau/data_catalogue.robot, tests/robot-tests/tests/admin_and_public_2/bau/publish_release_and_amend.robot, tests/robot-tests/tests/libs/admin-common.robot
Fixes some more UI tests for data guidance (now ckeditor has been removed) and data catalogue (now the indicators etc are populated).
=> Fix data guidance and data catalogue UI tests

infrastructure/templates/public-api/api-infrastructure-pipeline.yml, infrastructure/templates/public-api/application/virtualNetwork.bicep, infrastructure/templates/public-api/components/postgresqlDatabase.bicep, infrastructure/templates/public-api/deploy-stage-template.yml, infrastructure/templates/public-api/main.bicep, src/GovUk.Education.ExploreEducationStatistics.Admin/Startup.cs, src/GovUk.Education.ExploreEducationStatistics.Common/Functions/ConnectionUtils.cs, src/GovUk.Education.ExploreEducationStatistics.Public.Data.Api/Startup.cs, src/GovUk.Education.ExploreEducationStatistics.Public.Data.Processor/Functions/CountDataSetsFunction.cs, src/GovUk.Education.ExploreEducationStatistics.Public.Data.Processor/ProcessorHostBuilder.cs, src/GovUk.Education.ExploreEducationStatistics.Publisher/PublisherHostBuilderExtensions.cs
This PR:
- Adds a private endpoint to allow PSQL Flexible Server to be access securely directly from the VNet.
- Corrects the feeding of connection strings to the Data Processor function on deploy.
- Corrects the lookup of PSQL connection strings in Azure environment in the codebase by adding additional helpers to ConnectionUtils.
The resulting deployment shows that the `CountDataSets` Function can successfully look up the connection string and use it to query PSQL over the VNet.
=> Ees 5052 add private endpoint to connect psql to vnet

src/GovUk.Education.ExploreEducationStatistics.Common.Tests/Extensions/ValidationProblemViewModelTestExtensions.cs, src/GovUk.Education.ExploreEducationStatistics.Common.Tests/Utils/JsonPathUtilsTests.cs, src/GovUk.Education.ExploreEducationStatistics.Common/Utils/JsonPathUtils.cs, src/GovUk.Education.ExploreEducationStatistics.Common/Validators/ValidationMessages.cs, src/GovUk.Education.ExploreEducationStatistics.Public.Data.Api.Tests/Controllers/DataSetsControllerQueryTests.cs, src/GovUk.Education.ExploreEducationStatistics.Public.Data.Api.Tests/Filters/InvalidRequestInputResultFilterTests.cs, src/GovUk.Education.ExploreEducationStatistics.Public.Data.Api/Extensions/MvcOptionsExtensions.cs, src/GovUk.Education.ExploreEducationStatistics.Public.Data.Api/Filters/InvalidRequestInputResultFilter.cs, src/GovUk.Education.ExploreEducationStatistics.Public.Data.Api/Startup.cs, src/GovUk.Education.ExploreEducationStatistics.Public.Data.Api/ViewModels/Converters/LocationOptionMetaJsonConverter.cs
This PR adds an `InvalidRequestInputFilter` to the public API. This filter can convert errors that were caused by invalid request input into a standard validation error response.
The out-of-the-box errors are not adequate as they:
- Leak internals by reporting types that could not be deserialized from the JSON
- Don't have full paths to the part of the request causing the error (typically only reported partial paths)
- Don't have error codes
Importantly, fixing these issues provides a better user experience for the public API's data set query POST endpoint. As users can create highly nested queries, it's crucial that they get detailed validation errors that pinpoint precisely where any mistakes have been made.
- Fixed incorrect error paths in `LocationOptionMetaJsonConverter` when …
=> EES-5130 Add `InvalidRequestInputResultFilter` to handle invalid input

src/explore-education-statistics-frontend/next.config.js, src/explore-education-statistics-frontend/src/components/Page.tsx, src/explore-education-statistics-frontend/src/components/__tests__/Breadcrumbs.test.tsx, src/explore-education-statistics-frontend/src/components/__tests__/ButtonLink.test.tsx, src/explore-education-statistics-frontend/src/components/__tests__/Link.test.tsx, src/explore-education-statistics-frontend/src/modules/ErrorPage.tsx, src/explore-education-statistics-frontend/src/pages/index.tsx
Minor housekeeping in @frontend 
- Disabling SWC minification is no longer necessary, and generates a warning. This has been removed
- The Covid-era temporary notice on the home page has been removed. This also removes the dependency on `useRouter`. 
- Some relative imports in frontend have been replaced with package-relative ones
=> EES-XXXX: Frontend housekeeping

src/GovUk.Education.ExploreEducationStatistics.Admin.Tests/Controllers/Api/Public.Data/DataSetCandidatesControllerTests.cs, src/GovUk.Education.ExploreEducationStatistics.Admin/Migrations/ContentMigrations/20240514011937_EES5139_ReplaceFilePublicDataSetVersionIdWithSeparateColumns.Designer.cs, src/GovUk.Education.ExploreEducationStatistics.Admin/Migrations/ContentMigrations/20240514011937_EES5139_ReplaceFilePublicDataSetVersionIdWithSeparateColumns.cs, src/GovUk.Education.ExploreEducationStatistics.Admin/Services/Public.Data/ReleaseService.cs, src/GovUk.Education.ExploreEducationStatistics.Content.Api.Tests/Controllers/DataSetFilesControllerCachingTests.cs, src/GovUk.Education.ExploreEducationStatistics.Content.Api.Tests/Controllers/DataSetFilesControllerTests.cs, src/GovUk.Education.ExploreEducationStatistics.Content.Api/Controllers/DataSetFilesController.cs, src/GovUk.Education.ExploreEducationStatistics.Content.Model.Tests/Fixtures/FileGeneratorExtensions.cs, src/GovUk.Education.ExploreEducationStatistics.Content.Model/Database/ContentDbContext.cs, src/GovUk.Education.ExploreEducationStatistics.Content.Model/File.cs, src/GovUk.Education.ExploreEducationStatistics.Content.Services/DataSetFileService.cs, src/GovUk.Education.ExploreEducationStatistics.Content.ViewModels/DataSetFileApiViewModel.cs, src/GovUk.Education.ExploreEducationStatistics.Content.ViewModels/DataSetFileSummaryViewModel.cs, src/GovUk.Education.ExploreEducationStatistics.Content.ViewModels/DataSetFileViewModel.cs, src/GovUk.Education.ExploreEducationStatistics.Public.Data.Model/DataSetVersion.cs, src/GovUk.Education.ExploreEducationStatistics.Public.Data.Processor/Services/DataSetService.cs, src/explore-education-statistics-frontend/src/modules/data-catalogue/__data__/testDataSets.ts, src/explore-education-statistics-frontend/src/modules/data-catalogue/components/DataSetFileSummary.tsx, src/explore-education-statistics-frontend/src/services/dataSetFileService.ts
This PR adds missing API data set details to view models returned from the data set file endpoints in the content API. This essentially adds the following to the respective view models:
```json
{
"api": {
"id": "api-data-set-id",
"version": "1.0"
}
}
```
To implement this, we have updated `File` entity to have `PublicApiDataSetId` and `PublicApiDataSetVersion` columns instead of a single `PublicDataSetVersionId` column. This allows us to circumvent making an additional public API query to get the version number.
=> EES-5139 Add API data set details to data set file endpoints

src/GovUk.Education.ExploreEducationStatistics.Admin.Tests/Controllers/Api/Statistics/TableBuilderControllerTests.cs, src/GovUk.Education.ExploreEducationStatistics.Admin.Tests/Services/DataImportServiceTests.cs, src/GovUk.Education.ExploreEducationStatistics.Admin/Controllers/Api/Bau/DataSetFileMetaMigrationController.cs, src/GovUk.Education.ExploreEducationStatistics.Common/Converters/GeographicLevelsListJsonConverter.cs, src/GovUk.Education.ExploreEducationStatistics.Common/Utils/TimePeriodLabelFormatter.cs, src/GovUk.Education.ExploreEducationStatistics.Content.Api.Tests/Controllers/DataSetFilesControllerCachingTests.cs, src/GovUk.Education.ExploreEducationStatistics.Content.Api.Tests/Controllers/DataSetFilesControllerTests.cs, src/GovUk.Education.ExploreEducationStatistics.Content.Model.Tests/Fixtures/DataSetFileMetaGeneratorExtensions.cs, src/GovUk.Education.ExploreEducationStatistics.Content.Model.Tests/Fixtures/FileGeneratorExtensions.cs, src/GovUk.Education.ExploreEducationStatistics.Content.Model.Tests/Fixtures/TimePeriodRangeMetaGeneratorExtensions.cs, src/GovUk.Education.ExploreEducationStatistics.Content.Model/DataSetFileMeta.cs, src/GovUk.Education.ExploreEducationStatistics.Content.Model/Database/ContentDbContext.cs, src/GovUk.Education.ExploreEducationStatistics.Content.Services/DataSetFileService.cs, src/GovUk.Education.ExploreEducationStatistics.Content.ViewModels/DataSetFileMetaViewModel.cs, src/GovUk.Education.ExploreEducationStatistics.Data.Model.Tests/Fixtures/ObservationGeneratorExtensions.cs, src/GovUk.Education.ExploreEducationStatistics.Data.Processor.Tests/Functions/ProcessorStage3Tests.cs, src/GovUk.Education.ExploreEducationStatistics.Data.Processor.Tests/Services/DataImportServiceTests.cs, src/GovUk.Education.ExploreEducationStatistics.Data.Processor/Services/DataImportService.cs, src/explore-education-statistics-frontend/src/modules/data-catalogue/__data__/testDataSets.ts, src/explore-education-statistics-frontend/src/modules/data-catalogue/components/DataSetFileDetails.tsx, src/explore-education-statistics-frontend/src/modules/data-catalogue/components/DataSetFileSummary.tsx, src/explore-education-statistics-frontend/src/services/dataSetFileService.ts
Copy of this PR, since I accidentally blitzed my changes :fearful: 
This PR fixes an issue where DataSetFileMeta only stored one TimeIdentifier for a whole data set. This assumption I made is incorrect - a data set can have multiple TimeIdentifier's e.g. months.
File.DataSetFileMeta now has a TimePeriodRangeMeta which stores the data set's starting and ending TimeIdentifier/Year.
We are finished with the DataSetFileMeta migration endpoint, so I repurposed it in this PR to set the new TimePeriodRange field and remove TimeIdentifier and Years.
The TimeIdentifier and Year fields in DataSetFileMeta can be removed after this migration. I've added a note to do so to EES-4918.
=> EES-5140 Fix DataSetFileMeta / Add TimePeriodRangeMeta

src/explore-education-statistics-common/src/components/UrlContainer.tsx, src/explore-education-statistics-frontend/server.js, src/explore-education-statistics-frontend/src/modules/data-catalogue/components/__tests__/DataSetFileApiVersionHistory.test.tsx
This PR:
- Fixes inefficient `findByRole` selectors being used in unit tests
- Fixes CSP `connect-src` URLs being incorrect - these require a trailing slash to work correctly. This currently prevents fetching data from most of the APIs in the public frontend when running in production mode.
- Fixes missing `UrlContainer` testids causing lots of failures across Robot tests
=> EES-4996 Fix various test issues from data catalogue work

tests/robot-tests/tests/admin/bau/create_data_block_with_chart.robot, tests/robot-tests/tests/libs/common.robot
This fixes a UI test case where we weren't actually checking that the reference line had been removed.
=> EES-5143 Fix remove ref line check in UI test

src/explore-education-statistics-admin/src/prototypes/PrototypeDashboard.tsx, src/explore-education-statistics-admin/src/prototypes/PrototypeDashboard2.tsx, src/explore-education-statistics-admin/src/prototypes/PrototypeRelease.tsx, src/explore-education-statistics-admin/src/prototypes/PrototypeReleaseData.tsx, src/explore-education-statistics-admin/src/prototypes/PrototypeReleaseData2.tsx, src/explore-education-statistics-admin/src/prototypes/components/PrototypeSectionExamples.tsx, src/explore-education-statistics-frontend/src/pages/accessibility-statement.tsx, tests/robot-tests/tests/general_public/release_page_absence.robot
My last PR changed the route for requesting a new subscription from `subscriptions?slug=[slug]` to `subscriptions/new-subscription/[slug]`.
I missed a robot test which asserts on the link contained within the email to users, so this PR corrects that. 
I've also noticed some of the admin prototypes have links to this page so have updated those too.
=> EES-5129: Update missed link in robot test

src/GovUk.Education.ExploreEducationStatistics.Public.Data.Api/Properties/launchSettings.json, src/explore-education-statistics-frontend/.env
This PR updates the public API ports yet again to avoid collisions with Windows service host (`svchost`) which runs on TCP 5040 and UDP 5050. 
Note that we had previously tried updating the public API port to 5040 and 5041 in #4889 to avoid collisions with the IDP container.
Whilst the public API would end up sharing 5050 with the service host's UDP 5050, there (hopefully) shouldn't be any problems as they'd be on different protocols.
In the future, we might want to consider changing our port range to avoid these types of collisions some more.
=> Update public API ports to avoid collisions with Windows service host

src/explore-education-statistics-admin/public/index.html, src/explore-education-statistics-frontend/src/components/PageMeta.tsx, src/explore-education-statistics-frontend/src/modules/subscriptions/ConfirmSubscriptionPage.tsx, src/explore-education-statistics-frontend/src/modules/subscriptions/ConfirmUnsubscriptionPage.tsx
As the [brief ](https://dfedigital.atlassian.net/browse/EES-5161) says, all sites on the `dev` and `pre-production` environments should bear the `noindex, nofollow` tags for all robots.
=> EES-5161 Add noindex,nofollow tags to all pages in non-production environments

src/GovUk.Education.ExploreEducationStatistics.Public.Data.Processor.Tests/ProcessorFunctionsIntegrationTest.cs, src/GovUk.Education.ExploreEducationStatistics.Public.Data.Services.Tests/DataSetVersionPathResolverTests.cs, src/GovUk.Education.ExploreEducationStatistics.Public.Data.Services.Tests/TestDataSetVersionPathResolver.cs, src/GovUk.Education.ExploreEducationStatistics.Public.Data.Services/DataSetVersionPathResolver.cs, src/GovUk.Education.ExploreEducationStatistics.Public.Data.Services/Interfaces/IDataSetVersionPathResolver.cs
This PR changes the `DataSetVersionPathResolver` to append a unique directory to the base path for tests running in an integration test environment to ensure isolation of files created between tests.
An `IDisposable.Dispose` is added to the base `ProcessorFunctionsIntegrationTest` class which deletes this directory after every test.
It also corrects the `ProcessorFunctionsIntegrationTestFixture.ConfigureTestHostBuilder` method to not swap out the default `DataSetVersionPathResolver` with an instance of `TestDataSetVersionPathResolver`. This is because `TestDataSetVersionPathResolver` is only intended to be used where we need to fix the directory path to be a specific directory, e.g. `Resources/ParquetFiles/AbsenceSchool` where files in that directory have been source controlled to provide …
=> EES-5164 Ensure isolation of files created between tests

src/GovUk.Education.ExploreEducationStatistics.Common/Database/UuidV7ValueGenerator.cs, src/GovUk.Education.ExploreEducationStatistics.Common/GovUk.Education.ExploreEducationStatistics.Common.csproj, src/GovUk.Education.ExploreEducationStatistics.Common/Model/Either.cs, src/GovUk.Education.ExploreEducationStatistics.Common/Utils/UuidUtils.cs, src/GovUk.Education.ExploreEducationStatistics.Public.Data.Model/Change.cs, src/GovUk.Education.ExploreEducationStatistics.Public.Data.Model/ChangeSet.cs, src/GovUk.Education.ExploreEducationStatistics.Public.Data.Model/DataSet.cs, src/GovUk.Education.ExploreEducationStatistics.Public.Data.Model/DataSetVersion.cs, src/GovUk.Education.ExploreEducationStatistics.Public.Data.Model/DataSetVersionImport.cs, src/GovUk.Education.ExploreEducationStatistics.Public.Data.Processor/Services/DataSetService.cs
This PR adds UUID v7s for the various public API DB models instead of the default UUID v4s used by Guids.
UUID v7s are a better format for database performance as they can be sorted and cluster better, leading to better index performance. This was originally part of the database model proposed by Paul.
- Added transaction around `DataSetService.CreateDataSetVersion`, which could previously result in inconsistent state if any of its constituent saves failed to commit their changes.
=> EES-5162 Add UUID v7 IDs to public API DB models

tests/robot-tests/tests/general_public/prod_only/methodologies_page.robot
Couple of UI tests were failing in 'Prod-only' tests in` Methodology_page.robot.`because the slug got updated on the live website.
=> EES-5171 - Fixing Prod-only UI tests

src/explore-education-statistics-frontend/src/modules/data-catalogue/DataSetFilePage.tsx
Fixes an issue where following a link to the table tool from the data set page and then clicking the browser back button did not work. This seems to be a bug in Next.js when you've changed the hash using `window.history`  (see https://github.com/vercel/next.js/issues/56112 for more info), changing it to use Next Router to update the hash appears to fix it.
=> EES-4974 fix going back to data set page from table tool

src/explore-education-statistics-frontend/src/modules/data-catalogue/DataCataloguePage.tsx, src/explore-education-statistics-frontend/src/modules/data-catalogue/DataCataloguePageNew.tsx, src/explore-education-statistics-frontend/src/modules/data-catalogue/components/Filters.tsx, src/explore-education-statistics-frontend/src/modules/data-catalogue/components/__tests__/Filters.test.tsx
Checks to see if there are any API data sets before showing the 'Type of data' filter on the new Data Catalogue.
=> EES-4995 only show type filter if there are api data sets

src/GovUk.Education.ExploreEducationStatistics.Content.Model/Database/ContentDbContext.cs
This fixes an issue where the Last updated date for data set files weren't being adjusted from UTC to GMT. This was because we weren't saving the date into the DB as UTC - which meant no `Z` at the end of the date:
```
"published": "2024-05-23T23:30:03.3859034Z",
"lastUpdated": "2024-05-23T23:30:03.3859034",
```
This meant the frontend wouldn't treat the date as UTC and so wouldn't adjust it to local time.
=> EES-5183 Use UTC for ReleaseFiles.Published

src/explore-education-statistics-frontend/redirects.js, src/explore-education-statistics-frontend/server.js, tests/playwright-tests/tests/public/redirects.spec.ts
We have a new set of redirects to upload from Michael - we need to add the fast track data table urls to the list of redirects, as well as a few others which have crept in over time. 
We are also converting the redirects from an array to an object so we can iterate through them slightly faster. 
As usual, I've isolated any redirects that aren't already up on the live site and ran them through the Postman tools to ensure they do actually 404. There were two in there which actually were genuine links to live publications so naturally I've omitted those.
=> EES-5167 Upload new redirects and use an object instead of an array

src/explore-education-statistics-frontend/src/modules/data-catalogue/DataCataloguePageNew.tsx, src/explore-education-statistics-frontend/src/modules/data-catalogue/__tests__/DataCataloguePage.test.tsx
Fixes the download all data sets button on the data catalogue so it downloads all the data sets for the release, not just the ones currently shown on the page.
=> EES-5174 fix data catalogue download all button

infrastructure/templates/public-api/api-infrastructure-pipeline.yml
This small change is an attempt to stop multiple parallel runs of the Public API Infrastructure pipeline from running together and competing for resources.
=> EES-5119 - prevent parallel runs of API infrastructure pipeline

infrastructure/parameters/dev.parameters.json
This PR will allow Admin and Publisher to start using the Public Data DB connection on Dev.
As far as Admin goes, it'll use this endpoint for populating part of the Release Checklist (to make sure that there are no non-complete Public API Data Set imports) as well as dedicated Public API work like the new tab, and as far as Publisher goes, it'll use this connection to publish Data Sets along with the Releases / amendments as they go live.
=> EES-XXXX - enabling Public Data DB connection on Dev for Admin and Publisher

src/GovUk.Education.ExploreEducationStatistics.Public.Data.Services.Tests/DataSetVersionPathResolverTests.cs, src/GovUk.Education.ExploreEducationStatistics.Public.Data.Services/DataSetVersionPathResolver.cs
This PR changes the `DataSetVersionPathResolver` which is used to resolve the path of all Public API data set version files so that 
when running in an integration test environment the path of the current operating system user's 'temp' directory is used as the base file path. The directory `ExploreEducationStatistics` is also appended to that temp path.
Previously the base path was made up of the location of the executing assembly which can already be long depending on the location of the project source code but is made even longer by the `GovUk.Education.ExploreEducationStatistics...` namespace. In integration tests we also append a random test instance directory to the path which adds an additional 36 characters (plus separator) to the length.
An example Windows file path being created …
=> EES-5197 Use temp directory rather than assembly directory for Public API data set version files

src/GovUk.Education.ExploreEducationStatistics.Publisher/PublisherHostBuilderExtensions.cs
This PR is a hotifx to disable the Publisher config of the `PublicDataDbContext` if the Public API database does not exist which is currently the case in Test/Pre-Prod/Prod.
This matches similar config that we have for the Admin service.
=> EES-5203 Disable Publisher config of `PublicDataDbContext` if the Public API database does not exist

src/GovUk.Education.ExploreEducationStatistics.Admin.Tests/Controllers/Api/Public.Data/DataSetsControllerTests.cs, src/GovUk.Education.ExploreEducationStatistics.Admin.Tests/Services/Public.Data/ProcessorClientTests.cs, src/GovUk.Education.ExploreEducationStatistics.Admin/Services/Interfaces/Public.Data/IProcessorClient.cs, src/GovUk.Education.ExploreEducationStatistics.Admin/Services/Public.Data/DataSetService.cs, src/GovUk.Education.ExploreEducationStatistics.Admin/Services/Public.Data/ProcessorClient.cs, src/GovUk.Education.ExploreEducationStatistics.Public.Data.Processor.Requests/DataSetCreateRequest.cs, src/GovUk.Education.ExploreEducationStatistics.Public.Data.Processor.Tests/Functions/CopyCsvFilesFunctionTests.cs, src/GovUk.Education.ExploreEducationStatistics.Public.Data.Processor.Tests/Functions/CreateDataSetFunctionTests.cs, src/GovUk.Education.ExploreEducationStatistics.Public.Data.Processor.Tests/Functions/CreateInitialDataSetVersionFunctionTests.cs, src/GovUk.Education.ExploreEducationStatistics.Public.Data.Processor.Tests/Functions/HandleProcessingFailureFunctionTests.cs, src/GovUk.Education.ExploreEducationStatistics.Public.Data.Processor.Tests/Functions/ImportMetadataFunctionTests.cs, src/GovUk.Education.ExploreEducationStatistics.Public.Data.Processor.Tests/Functions/ProcessInitialDataSetVersionFunctionTests.cs, src/GovUk.Education.ExploreEducationStatistics.Public.Data.Processor.Tests/ProcessorFunctionsIntegrationTest.cs, src/GovUk.Education.ExploreEducationStatistics.Public.Data.Processor.Tests/ProcessorTestData.cs, src/GovUk.Education.ExploreEducationStatistics.Public.Data.Processor.ViewModels/CreateDataSetResponseViewModel.cs, src/GovUk.Education.ExploreEducationStatistics.Public.Data.Processor/Functions/ActivityNames.cs, src/GovUk.Education.ExploreEducationStatistics.Public.Data.Processor/Functions/CopyCsvFilesFunction.cs, src/GovUk.Education.ExploreEducationStatistics.Public.Data.Processor/Functions/CreateDataSetFunction.cs, src/GovUk.Education.ExploreEducationStatistics.Public.Data.Processor/Functions/HandleProcesssingFailureFunction.cs, src/GovUk.Education.ExploreEducationStatistics.Public.Data.Processor/Functions/ImportMetadataFunction.cs, src/GovUk.Education.ExploreEducationStatistics.Public.Data.Processor/Functions/ProcessInitialDataSetVersionFunction.cs, src/GovUk.Education.ExploreEducationStatistics.Public.Data.Processor/ProcessorHostBuilder.cs, src/GovUk.Education.ExploreEducationStatistics.Public.Data.Processor/Services/DataSetService.cs, src/GovUk.Education.ExploreEducationStatistics.Public.Data.Processor/Services/Interfaces/IDataSetService.cs
Some of the functions developed as part of EES-4903 for processing the initial data set version will be reusable by functions developed for other activity sequences responsible for creating subsequent data set versions.
The function `CopyCsvFilesTests` was already written with this in mind, but other functions like `ImportMetadata` and probably `HandleProcessingFailure` will end up being used by multiple orchestrators for processing the initial data set version and creating/processing subsequent versions.
This task is to refactor these functions to make them available to multiple different orchestrator functions.
Doing this early will make it easier to work on EES-5152 (writing function tests) and EES-4953 (creating the next data set version) in parallel.
- Rename …
=> EES-5201 Refactor functions in preparation for creating next data set versions

src/explore-education-statistics-frontend/src/modules/data-catalogue/DataSetFilePage.tsx, src/explore-education-statistics-frontend/src/modules/data-catalogue/components/DataSetFilePreview.tsx, src/explore-education-statistics-frontend/src/modules/data-catalogue/components/DataSetFileVariables.tsx, src/explore-education-statistics-frontend/src/modules/data-catalogue/components/__tests__/DataSetFileVariables.test.tsx
Fixes the following issues on the data sets page:
- weird scrolling behaviour caused by the hash change. It seems that there are known issues with Next router and updating the hash which cause reloading (even when `shallow` is true) and jerky scroll behaviour. We can't use `window.history.pushState` to update the hash as that causes a problem with the back button (see https://github.com/dfe-analytical-services/explore-education-statistics/pull/4895). I've ended up just removing updating the hash as you scroll, the navigation items are still highlighted to show where you are which was the original requirement I think.
- fix the variables list when there are fewer than 5
- makes sure the total number of csv rows is correct
=> EES-5159 data set page fixes

src/explore-education-statistics-frontend/src/modules/data-catalogue/DataCataloguePage.tsx, src/explore-education-statistics-frontend/src/modules/data-catalogue/DataCataloguePageNew.tsx, src/explore-education-statistics-frontend/src/modules/data-catalogue/utils/getUpdatedQueryParams.ts, tests/robot-tests/tests/admin_and_public/bau/data_catalogue.robot
Release pages have links to the data catalogue on using publication and release slugs, e.g. `/data-catalogue/<publication-slug>/<release-slug>`. This PR adds a redirect on the new version of the data catalogue page so that these links will work correctly. The link itself will be updated as part of the tidy up ticket, [EES-4781](https://dfedigital.atlassian.net/browse/EES-4781), but we'll want to keep the redirect so that bookmarked links will still work.
Also:
- fixes a bug where removing a release filter wasn't updating the data sets list to show all releases
- fixes a UI test that broke when I changed 'clear filters' to 'reset filters'
=> EES-5182 redirect data catalogue slug urls

src/explore-education-statistics-frontend/server.js
The new subscription-verification page contains the verification token as part of its route. This token is case sensitive.
I've recently refactored the code that implements SEO redirects, and because the redirectService is lowercasing any Content API redirects it finds, I chose to be consistent in the SEO redirects.
This, understandably, is a pretty fatal but entirely predictable change for the subscription-verification page 🤦
(If we care about the lowercasing, we could be more explicit about the path itself and still lowercase any parts of the path that aren't the token itself, but I actually don't think it's necessary).
=> Permit uppercase characters in URL path without redirecting

src/explore-education-statistics-frontend/redirects.js
As discussed on Slack, this redirect is actually a valid publication slug and has been erroneously included in the redirects.
=> EES-5225 Erroneous key-stage-4-performance redirect

tests/robot-tests/tests/general_public/prod_only/redirects.robot, tests/robot-tests/tests/general_public/redirects.robot, tests/robot-tests/tests/general_public/redirects_www.robot
The dev, test, and pre-production environments aren't set up with the required certificates to host `www....` urls. 
There is a test to assert that hostnames included www are redirected - this test should run only against local and production. 
Also, some tests recently added to redirects.robot should also have been added to the prod_only version of redirects.robot, but weren't. So this PR also adds them in.
=> EES-5160 - Only run www tests against prod and local

src/explore-education-statistics-admin/src/pages/release/api-data-sets/ReleaseApiDataSetDetailsPage.tsx, src/explore-education-statistics-admin/src/pages/release/api-data-sets/__tests__/ReleaseApiDataSetDetailsPage.test.tsx, src/explore-education-statistics-admin/src/pages/release/api-data-sets/utils/getVersionStatusColour.ts
This PR adds the data set's status and summary information to the admin's details page:
=> EES-5196 Add data set status and summary to admin details page

src/GovUk.Education.ExploreEducationStatistics.Content.Api.Tests/Controllers/MethodologyControllerTests.cs, src/GovUk.Education.ExploreEducationStatistics.Content.Api.Tests/Controllers/PublicationControllerTests.cs, src/GovUk.Education.ExploreEducationStatistics.Content.Api/Controllers/DataSetFilesController.cs, src/GovUk.Education.ExploreEducationStatistics.Content.Api/Controllers/MethodologyController.cs, src/GovUk.Education.ExploreEducationStatistics.Content.Api/Controllers/PublicationController.cs, src/GovUk.Education.ExploreEducationStatistics.Content.Services.Tests/MethodologyServiceTests.cs, src/GovUk.Education.ExploreEducationStatistics.Content.Services.Tests/PublicationServiceTests.cs, src/GovUk.Education.ExploreEducationStatistics.Content.Services/DataSetFileService.cs, src/GovUk.Education.ExploreEducationStatistics.Content.Services/Interfaces/IDataSetFileService.cs, src/GovUk.Education.ExploreEducationStatistics.Content.Services/Interfaces/IMethodologyService.cs, src/GovUk.Education.ExploreEducationStatistics.Content.Services/Interfaces/IPublicationService.cs, src/GovUk.Education.ExploreEducationStatistics.Content.Services/MethodologyService.cs, src/GovUk.Education.ExploreEducationStatistics.Content.Services/PublicationService.cs
The Dev environment is encountering Null Argument Exceptions when trying to fetch the dynamic sitemap. 
For some bizarre reason this works when running locally, but our query should be properly loading the Methodology of the MethodologyVersion through a `.ThenInclude`. 
This PR also adds cancellation tokens to all ListSitemapItems routes.
=> Improve Methodology Sitemap Item query

src/explore-education-statistics-common/src/components/Modal.tsx, src/explore-education-statistics-common/src/components/__tests__/ContentHtml.test.tsx, src/explore-education-statistics-common/src/components/__tests__/Modal.test.tsx, src/explore-education-statistics-frontend/src/components/Breadcrumbs.tsx, src/explore-education-statistics-frontend/src/components/Page.tsx, src/explore-education-statistics-frontend/src/components/PageMeta.tsx, src/explore-education-statistics-frontend/src/modules/data-catalogue/DataCataloguePage.tsx, src/explore-education-statistics-frontend/src/modules/data-catalogue/DataCataloguePageNew.tsx, src/explore-education-statistics-frontend/src/modules/data-catalogue/__tests__/DataCataloguePage.test.tsx, src/explore-education-statistics-frontend/src/modules/data-catalogue/components/Filters.tsx, src/explore-education-statistics-frontend/src/modules/data-catalogue/components/__tests__/DataSetFileDetails.test.tsx, src/explore-education-statistics-frontend/src/modules/data-catalogue/components/__tests__/Filters.test.tsx, src/explore-education-statistics-frontend/src/modules/find-statistics/FindStatisticsPage.tsx, src/explore-education-statistics-frontend/src/modules/find-statistics/__tests__/FindStatisticsPage.test.tsx, src/explore-education-statistics-frontend/src/modules/find-statistics/components/ThemeFilters.tsx
Fixes the following accessibility issues on the data catalogue (new version) and find statistics pages:
Currently:
- when filter or search:
- the page title is updated with the new number of pages and is announced before the number of results, e.g. "Data catalogue (page 1 of 27) – Explore education statistics – GOV.UK" followed by "25 results". The DAC report highlighted this as an issue as a lot is read before the useful information - the number of results, see p.130
- the page title that's announced is actually wrong, it's the title from before the filter happened
- the number of results is read twice
- when use the pagination
- the full page title is announced and has the previous page number in, e.g. if you go to page 2 it'll announce "Data catalogue (page 1 of 27) – Explore education …
=> EES-5176 accessibility improvements for data catalogue and find stats

src/explore-education-statistics-admin/src/hooks/useCKEditorConfig.ts, src/explore-education-statistics-common/src/components/ContentHtml.tsx, src/explore-education-statistics-common/src/components/__tests__/ContentHtml.test.tsx
- removes the option to set if links open in new tabs or not in CK Editor
- external links now automatically open in a new tab and have the text `(opens in a new tab)` added to them
- internal links open in the same tab
=> EES-5208 automatically open external links in new tabs

src/explore-education-statistics-common/src/components/Details.tsx, src/explore-education-statistics-common/src/components/__tests__/__snapshots__/Details.test.tsx.snap
Removes the role `group` from `details` elements following advice from DAC that it can cause accessibility issues.
=> EES-5211 remove group role on details element

src/GovUk.Education.ExploreEducationStatistics.Admin.Tests/Controllers/Api/Public.Data/DataSetCandidatesControllerTests.cs, src/GovUk.Education.ExploreEducationStatistics.Admin.Tests/Services/ReleaseAmendmentServiceTests.cs, src/GovUk.Education.ExploreEducationStatistics.Admin/Controllers/Api/Bau/BauMigrationController.cs, src/GovUk.Education.ExploreEducationStatistics.Admin/Migrations/ContentMigrations/20240617005412_EES4993_AddPublicApiDataSetIdVersionToReleaseFile.Designer.cs, src/GovUk.Education.ExploreEducationStatistics.Admin/Migrations/ContentMigrations/20240617005412_EES4993_AddPublicApiDataSetIdVersionToReleaseFile.cs, src/GovUk.Education.ExploreEducationStatistics.Admin/Services/Public.Data/DataSetCandidateService.cs, src/GovUk.Education.ExploreEducationStatistics.Admin/Services/ReleaseAmendmentService.cs, src/GovUk.Education.ExploreEducationStatistics.Content.Api.Tests/Controllers/DataSetFilesControllerTests.cs, src/GovUk.Education.ExploreEducationStatistics.Content.Model.Tests/Fixtures/FileGeneratorExtensions.cs, src/GovUk.Education.ExploreEducationStatistics.Content.Model.Tests/Fixtures/ReleaseFileGeneratorExtensions.cs, src/GovUk.Education.ExploreEducationStatistics.Content.Model/Database/ContentDbContext.cs, src/GovUk.Education.ExploreEducationStatistics.Content.Model/File.cs, src/GovUk.Education.ExploreEducationStatistics.Content.Model/ReleaseFile.cs, src/GovUk.Education.ExploreEducationStatistics.Content.Services/DataSetFileService.cs, src/GovUk.Education.ExploreEducationStatistics.Public.Data.Processor.Tests/Functions/DeleteDataSetVersionFunctionTests.cs, src/GovUk.Education.ExploreEducationStatistics.Public.Data.Processor/Services/DataSetService.cs, src/GovUk.Education.ExploreEducationStatistics.Public.Data.Processor/Services/DataSetVersionService.cs
This PR moves the `PublicApiDataSetId` and `PublicApiDataSetVersion` columns from the content DB's `Files` table to `ReleaseFiles`.
This fixes an issue where creating a draft API data set for a `ReleaseFile` in an amendment can immediately show in the Data Catalogue as an API data set. This was due to the `PublicApiDataSet*` columns previously being on the `Files` table, meaning any changes would be shared between all `ReleaseFiles` sharing the same `File`.
:warning: **Note** - To implement this, we also require an endpoint migration to unset the `PublicApiDataSet*` columns for any amendment `ReleaseFiles` that have already been created with this issue.
=> EES-4993 Move `PublicApiDataSet*` columns from `Files` to `ReleaseFiles`

src/explore-education-statistics-common/src/modules/charts/components/MapBlock.module.scss
Uses `forced-color-adjust: none` to prevent the map legend colours from disappearing in high contrast mode.
=> EES-5214 ensure map legends are visible in high contrast mode

src/explore-education-statistics-common/src/components/CollapsibleList.module.scss, src/explore-education-statistics-common/src/components/CollapsibleList.tsx, src/explore-education-statistics-common/src/modules/table-tool/components/__tests__/__snapshots__/FiltersForm.test.tsx.snap
Updates the CollapsibleList component so that when the list is expanded the first revealed item is focused and when it's collapsed the first item is focused. This will make the content more accessible for screen reader users.
=> EES-5216 improve CollapsibleList accessibility

src/explore-education-statistics-common/src/components/Tabs.tsx
Fixes the tabs markup on mobile - they display as links on mobile so don't need `tablist` etc.
=> EES-5218 fix tab markup on mobile

src/GovUk.Education.ExploreEducationStatistics.Content.Api.Tests/Controllers/DataSetFilesControllerCachingTests.cs, src/GovUk.Education.ExploreEducationStatistics.Content.Api.Tests/Controllers/DataSetFilesControllerTests.cs, src/GovUk.Education.ExploreEducationStatistics.Content.Services/DataSetFileService.cs, src/GovUk.Education.ExploreEducationStatistics.Content.ViewModels/DataSetFileSummaryViewModel.cs, src/GovUk.Education.ExploreEducationStatistics.Content.ViewModels/DataSetFileViewModel.cs, src/explore-education-statistics-frontend/src/modules/data-catalogue/DataCataloguePageNew.tsx, src/explore-education-statistics-frontend/src/modules/data-catalogue/DataSetFilePage.tsx, src/explore-education-statistics-frontend/src/modules/data-catalogue/__data__/testDataSets.ts, src/explore-education-statistics-frontend/src/services/dataSetFileService.ts
This PR adds `IsSuperseded` to `DataSetFileSummaryViewModel` and `DataSetFileViewModel`. We're doing this so that on the new Data catalogue and Data set details pages we can label data sets from superseded publications as `Not the latest data`.
=> EES-5231 Add IsSuperseded to Data catalogue view models

infrastructure/templates/public-api/components/containerApp.bicep, infrastructure/templates/public-api/main.bicep, infrastructure/templates/public-api/parameters/main-dev.bicepparam, infrastructure/templates/public-api/parameters/main-preprod.bicepparam, infrastructure/templates/public-api/parameters/main-prod.bicepparam, infrastructure/templates/public-api/parameters/main-test.bicepparam, renovate.json
This PR adds a CORS policy for the public API so that clients from the public frontend can access it.
- Disabled Renovate for Bicep resources as this was suggesting incorrect versions that do not have official documentation and consequently have broken intellisense. In the future, we should manually upgrade these resource as required.
=> EES-5243 Add CORS policy to allow access to public API from public frontend

src/explore-education-statistics-frontend/.env, src/explore-education-statistics-frontend/.env.production, src/explore-education-statistics-frontend/next-sitemap.config.js, src/explore-education-statistics-frontend/src/services/sitemapService.ts, tests/playwright-tests/tests/public/seoMetadataFiles.spec.ts, tests/robot-tests/.env.example, tests/robot-tests/tests/general_public/prod_only/redirects.robot, tests/robot-tests/tests/general_public/redirects_www.robot
Quick intermediary PR which fixes a few niggles ahead of the next deploy to master -
- The `PUBLIC_URL_WITH_WWW` environment variable was incorrectly named, and has been corrected (this will require renaming the similarly incorrectly named pipeline variable).
- To combat the issue of the robots/sitemap files being constructed at build time, which only occurs once and does not have access to environment variables configured for each environment, we introduced `.env.production` so that the build would have access to the correct `PUBLIC_URL` both when running locally and on the pipeline. This however has consequences for the redirect tests, because the redirects are now going to the production url when testing locally. There's a few ways we could resolve this and keep `.env.production`, but …
=> EES-5003 - Minor fixes

src/GovUk.Education.ExploreEducationStatistics.Admin/Services/ReleaseApprovalService.cs, src/GovUk.Education.ExploreEducationStatistics.Admin/Services/ReleaseDataFileService.cs, src/GovUk.Education.ExploreEducationStatistics.Admin/Services/ReleaseFileService.cs, src/GovUk.Education.ExploreEducationStatistics.Content.Model/Repository/Interfaces/IReleaseFileRepository.cs, src/GovUk.Education.ExploreEducationStatistics.Content.Model/Repository/ReleaseFileRepository.cs, src/GovUk.Education.ExploreEducationStatistics.Content.Services/ReleaseService.cs, src/GovUk.Education.ExploreEducationStatistics.Public.Data.Processor.Requests/Validators/ValidationMessages.cs, src/GovUk.Education.ExploreEducationStatistics.Public.Data.Processor.Tests/Functions/BulkDeleteDataSetVersionsFunctionTests.cs, src/GovUk.Education.ExploreEducationStatistics.Public.Data.Processor.Tests/Functions/DeleteDataSetVersionFunctionTests.cs, src/GovUk.Education.ExploreEducationStatistics.Public.Data.Processor.Tests/ProcessorFunctionsIntegrationTest.cs, src/GovUk.Education.ExploreEducationStatistics.Public.Data.Processor/Functions/BulkDeleteDataSetVersionsFunction.cs, src/GovUk.Education.ExploreEducationStatistics.Public.Data.Processor/ProcessorHostBuilder.cs, src/GovUk.Education.ExploreEducationStatistics.Public.Data.Processor/Services/DataSetVersionService.cs, src/GovUk.Education.ExploreEducationStatistics.Public.Data.Processor/Services/Interfaces/IDataSetVersionService.cs
We need to add an endpoint to the Processor to delete multiple data set versions in bulk. 
We will be using this endpoint within the deletion plan for an entire release version.
The deletion is blocked if ANY data set versions linked to the target release version are not in a state which can be deleted.
Similar to the existing Processor endpoint which is used to delete SINGLE data set versions, this endpoint is wrapped in a transaction such that all changes will be rolled back if any single deletion step fails. It will attempt to delete the following:
- The `DataSets` linked to the release version
- The `DataSetVersions`, and any related metadata, linked to the release version
- The `DataSetVersionImports` for all the `DataSetVersions` being deleted
- The parquet files (used by DuckDB) …
=> EES-5194 Add Processor bulk delete endpoint for multiple API data set versions

src/explore-education-statistics-common/src/modules/table-tool/components/LocationStep.tsx
This fixes the `LocationStep` component not awaiting in its `onSubmit` handler for its form. This means that currently, users move straight to the time period step without the meta filtering completing.
This compounds with the backend performance regression (introduced by EF's use of `OPENJSON`) where the meta filtering takes so long that the user is essentially able to complete the rest of their table query before it resolves. In this situation, the query will be persisted to the database with an empty `locationIds` array.
=> EES-5256 Fix `LocationStep` not awaiting form submission

src/GovUk.Education.ExploreEducationStatistics.Admin.Tests/GovUk.Education.ExploreEducationStatistics.Admin.Tests.csproj, src/GovUk.Education.ExploreEducationStatistics.Admin/GovUk.Education.ExploreEducationStatistics.Admin.csproj, src/GovUk.Education.ExploreEducationStatistics.Common.Tests/GovUk.Education.ExploreEducationStatistics.Common.Tests.csproj, src/GovUk.Education.ExploreEducationStatistics.Common/GovUk.Education.ExploreEducationStatistics.Common.csproj, src/GovUk.Education.ExploreEducationStatistics.Content.Api.Tests/GovUk.Education.ExploreEducationStatistics.Content.Api.Tests.csproj, src/GovUk.Education.ExploreEducationStatistics.Content.Api/GovUk.Education.ExploreEducationStatistics.Content.Api.csproj, src/GovUk.Education.ExploreEducationStatistics.Content.Model.Tests/GovUk.Education.ExploreEducationStatistics.Content.Model.Tests.csproj, src/GovUk.Education.ExploreEducationStatistics.Content.Model/GovUk.Education.ExploreEducationStatistics.Content.Model.csproj, src/GovUk.Education.ExploreEducationStatistics.Content.Security.Tests/GovUk.Education.ExploreEducationStatistics.Content.Security.Tests.csproj, src/GovUk.Education.ExploreEducationStatistics.Content.Security/GovUk.Education.ExploreEducationStatistics.Content.Security.csproj, src/GovUk.Education.ExploreEducationStatistics.Data.Api/GovUk.Education.ExploreEducationStatistics.Data.Api.csproj, src/GovUk.Education.ExploreEducationStatistics.Data.Model.Tests/GovUk.Education.ExploreEducationStatistics.Data.Model.Tests.csproj, src/GovUk.Education.ExploreEducationStatistics.Data.Model/GovUk.Education.ExploreEducationStatistics.Data.Model.csproj, src/GovUk.Education.ExploreEducationStatistics.Data.Processor.Tests/GovUk.Education.ExploreEducationStatistics.Data.Processor.Tests.csproj, src/GovUk.Education.ExploreEducationStatistics.Data.Services.Tests/GovUk.Education.ExploreEducationStatistics.Data.Services.Tests.csproj, src/GovUk.Education.ExploreEducationStatistics.Data.Services/GovUk.Education.ExploreEducationStatistics.Data.Services.csproj, src/GovUk.Education.ExploreEducationStatistics.Data.Services/SubjectMetaService.cs, src/GovUk.Education.ExploreEducationStatistics.Public.Data.Api/GovUk.Education.ExploreEducationStatistics.Public.Data.Api.csproj, src/GovUk.Education.ExploreEducationStatistics.Public.Data.Model/GovUk.Education.ExploreEducationStatistics.Public.Data.Model.csproj, src/GovUk.Education.ExploreEducationStatistics.Publisher.Tests/GovUk.Education.ExploreEducationStatistics.Publisher.Tests.csproj
This PR opts-out of the `OPENJSON` subquery transformation of the location id's in the time periods metadata query and revert back to using an SQL `IN` clause as was the behaviour prior to updating to Entity Framework Core 8.
Prior to this change the query is translated using an `OPENJSON` subquery
```
SELECT DISTINCT [o].[Year], [o].[TimeIdentifier]
FROM [Observation] AS [o]
WHERE [o].[SubjectId] = @__8__locals1_query_SubjectId_0
AND [o].[LocationId] IN (
SELECT [l].[value]
FROM OPENJSON(@__locationIds_1) WITH ([value] uniqueidentifier '$') AS [l]
)
```
With this change, for multiple location id's the query is translated using `IN`
```
SELECT DISTINCT [o].[Year], [o].[TimeIdentifier]
FROM [Observation] AS [o]
WHERE [o].[SubjectId] = @__8__locals1_query_SubjectId_0
AND [o].[LocationId] IN …
```
=> EES-5256 Opt-out of OPENJSON subquery transformation in time periods query and revert #5002

src/explore-education-statistics-common/src/components/ContentHtml.tsx
This PR fixes an issue where in methodology content, the entire methodology fails if it tries to process a link without a `href` attribute.
In the methodology that is failing on Prod, there was no link without a `href` attribute, so I'm suspicious that `sanitizeHtml` is removing the `href` attribute from a link, leading to the methodology not rendering.
I tried to recreate the problem locally but failed. I was not able to replicate the Content/Annexes of the failing methodology locally (it was too long to copy into my local db). And I tried copying a few of the links from the failing methodology into my own local db's methodology Content, and they seemed to render fine.
This PR ensures that methodology pages will always load even if no `href` attribute is found in a link, but it will not …
=> EES-5277 Quick fix for methodology page href issue

tests/robot-tests/tests/general_public/prod_only/statistics_page.robot, tests/robot-tests/tests/libs/common.robot
Updated UI tests that run against Prod to fix a failure due to change in text of links under 'Related Information' on Find Stats page.
Also removed an unused library in `common.robot` as an error was popping up in console.
=> EES-5269- Fix prod-only UI test failure

src/GovUk.Education.ExploreEducationStatistics.Data.Processor/Program.cs, src/GovUk.Education.ExploreEducationStatistics.Data.Processor/appsettings.json, src/GovUk.Education.ExploreEducationStatistics.Data.Processor/host.json, src/GovUk.Education.ExploreEducationStatistics.Notifier/Program.cs, src/GovUk.Education.ExploreEducationStatistics.Notifier/appsettings.json, src/GovUk.Education.ExploreEducationStatistics.Notifier/host.json, src/GovUk.Education.ExploreEducationStatistics.Publisher/PublisherHostBuilderExtensions.cs, src/GovUk.Education.ExploreEducationStatistics.Publisher/appsettings.json, src/GovUk.Education.ExploreEducationStatistics.Publisher/host.json
This PR suppresses the `DbCommand` SQL console logging seen in our Azure Function apps when running locally that started occurring after either the change to use the Isolated Worker Model in #4673 or the .NET 8 update in #4639.
This has been making it difficult to spot exceptions and other log messages because they are surrounded by superfluous SQL command logging.
This PR brings the logging config in sync with the Public Data Processor function app where this fix has already been applied.
Note that this doesn't completely close the issue as we still leave a `TODO` in the code to answer why we can’t we filter `Microsoft.EntityFrameworkCore.Database.Command` using standard logging config in app settings.
We normally control SQL command logging by setting the …
=> EES-5013 Suppress SQL command console logging in Function apps

src/GovUk.Education.ExploreEducationStatistics.Admin.Tests/Controllers/Api/Public.Data/DataSetVersionMappingControllerTests.cs, src/GovUk.Education.ExploreEducationStatistics.Admin/Controllers/Api/Public.Data/DataSetVersionMappingController.cs, src/GovUk.Education.ExploreEducationStatistics.Admin/Requests/Public.Data/BatchMappingUpdateRequests.cs, src/GovUk.Education.ExploreEducationStatistics.Admin/Services/Interfaces/Public.Data/IDataSetVersionMappingService.cs, src/GovUk.Education.ExploreEducationStatistics.Admin/Services/Public.Data/DataSetVersionMappingService.cs, src/GovUk.Education.ExploreEducationStatistics.Admin/ViewModels/Public.Data/BatchMappingUpdateViewModels.cs
This PR:
- adds an endpoint for updating the mappings for Filter Options via a debounced autosave mechansim.
Much the same as the PR for autosaving Location mappings!
=> EES-5115 - Filter Option mapping endpoint

src/GovUk.Education.ExploreEducationStatistics.Admin.Tests/Controllers/Api/Public.Data/DataSetVersionMappingControllerTests.cs, src/GovUk.Education.ExploreEducationStatistics.Admin/Services/Public.Data/DataSetVersionMappingService.cs, src/GovUk.Education.ExploreEducationStatistics.Admin/Validators/ValidationMessages.cs, src/GovUk.Education.ExploreEducationStatistics.Common/Model/JsonDtos.cs, src/GovUk.Education.ExploreEducationStatistics.Common/Services/Interfaces/IPostgreSqlRepository.cs, src/GovUk.Education.ExploreEducationStatistics.Common/Services/PostgreSqlRepository.cs, src/GovUk.Education.ExploreEducationStatistics.Public.Data.Model/Database/PublicDataDbContext.cs
This PR:
- adds in validation for the selected candidate keys for update requests, for both Locations and Filter Options.
This validation is pretty simple.  We only need to take the "Level" supplied in the update request, and see if there is a candidate Location within that same Level with the given CandidateKey.
This validation is a little more involved.  In order to validate, we:
1. Take the "FilterKey" from the update request, which identifies the owning filter of the filter option being updated.
2. Find the filter that that owning filter is mapped to.
3. If the owning filter has not yet been mapped, return an error.
4. If the owning filter has been mapped, look for the candidate filter option underneath the filter that the owning filter has been mapped to.
This is an optimised method …
=> EES-5112 - adding validation to ensure Candidate Keys are valid

src/GovUk.Education.ExploreEducationStatistics.Public.Data.Model/DataSetVersionMapping.cs
This PR:
- adds a Newtonsoft JSON converter to allow the MappingType enum to be serialised as a string over MVC
We already use System.Text.Json.Serialisation's JsonConverter to handle conversion for the database, as this is what is used by Entity Framework.
=> EES-5111 - added Newtonsoft JSON converter

src/explore-education-statistics-admin/src/pages/release/data/ReleaseApiDataSetDetailsPage.tsx, src/explore-education-statistics-admin/src/pages/release/data/__tests__/ReleaseApiDataSetDetailsPage.test.tsx, src/explore-education-statistics-admin/src/pages/release/data/components/ApiDataSetCreateForm.tsx, src/explore-education-statistics-admin/src/pages/release/data/components/ApiDataSetCreateModal.tsx, src/explore-education-statistics-admin/src/pages/release/data/components/DeleteDraftVersionButton.tsx, src/explore-education-statistics-admin/src/pages/release/data/components/DraftApiDataSetsTable.module.scss, src/explore-education-statistics-admin/src/pages/release/data/components/DraftApiDataSetsTable.tsx, src/explore-education-statistics-admin/src/pages/release/data/components/LiveApiDataSetsTable.module.scss, src/explore-education-statistics-admin/src/pages/release/data/components/LiveApiDataSetsTable.tsx, src/explore-education-statistics-admin/src/pages/release/data/components/ReleaseApiDataSetsSection.tsx, src/explore-education-statistics-admin/src/pages/release/data/components/__tests__/ApiDataSetCreateModal.test.tsx, src/explore-education-statistics-admin/src/pages/release/data/components/__tests__/DeleteDraftVersionButton.test.tsx, src/explore-education-statistics-admin/src/pages/release/data/components/__tests__/DraftApiDataSetsTable.test.tsx, src/explore-education-statistics-admin/src/pages/release/data/components/__tests__/LiveApiDataSetsTable.test.tsx, src/explore-education-statistics-admin/src/pages/release/data/components/__tests__/ReleaseApiDataSetsSection.test.tsx, src/explore-education-statistics-admin/src/services/apiDataSetVersionService.ts, src/explore-education-statistics-common/src/components/ModalConfirm.tsx
- Hooks up the UI to create new API data set versions
- Adds the create new API data set version button to the API data set details page
- Changes the 'delete' modal to 'remove' as per the Figma
- If you're viewing a published release I've removed the option to edit / remove drafts for API data sets that have been created on a later release 
- Some tidying up of alignment in the live and draft tables.
=> EES-4373 create new api data set version

infrastructure/parameters/dev.parameters.json, infrastructure/parameters/prod.parameters.json
Preventative measure to accommodate growing statistics database to ensure we don't encounter issues inserting/updating data.
=> EES-5337: Increase dev/prod statistics DB size to 600GB/1.5TB respectively

infrastructure/parameters/prod.parameters.json
This PR changes the statistics primary and replica databases in the Prod environment from provisioned 6 to 10 vCores.
This is a code change to reflect the same change that's already been made to the databases manually on 10/07/24.
=> EES-5339 Temporarily increase statistics database scale after slow running observed

src/explore-education-statistics-common/src/modules/charts/components/MapBlock.tsx, src/explore-education-statistics-common/src/modules/charts/components/MapGeoJSON.tsx, src/explore-education-statistics-common/src/modules/charts/components/__tests__/__data__/testMapBlockData.ts, src/explore-education-statistics-common/src/modules/charts/components/utils/createMapDataSetCategories.ts, src/explore-education-statistics-common/src/services/tableBuilderService.ts
Updates the `GeoJsonFeatureProperties` type to expect the same casing of parameter names as is returned by the back end and updates the test data to fix failing unit tests.
It would be preferable if the back end returned the parameters in camelCase but there are some issues here that mean it's not necessarily as simple to do so as we'd like.
=> EES-5170 handle geojson param casing

src/explore-education-statistics-frontend/src/modules/data-catalogue/__tests__/DataCataloguePage.test.tsx
Adds missing awaits and moves test setup out of beforeEachs.
=> EES-5344 fix flaky data catalogue tests

src/explore-education-statistics-admin/src/pages/bau/BoundaryDataPage.tsx
Move out from from collapsible info section to always be visible.
=> EES-5170: Boundary level admin instructions should always be visible.

src/GovUk.Education.ExploreEducationStatistics.Admin.Tests/Controllers/Api/Public.Data/DataSetVersionsControllerTests.cs, src/GovUk.Education.ExploreEducationStatistics.Admin.Tests/Controllers/Api/Public.Data/DataSetsControllerTests.cs, src/GovUk.Education.ExploreEducationStatistics.Admin.Tests/Services/Public.Data/ProcessorClientTests.cs, src/GovUk.Education.ExploreEducationStatistics.Admin/Services/Interfaces/Public.Data/IProcessorClient.cs, src/GovUk.Education.ExploreEducationStatistics.Admin/Services/Public.Data/ProcessorClient.cs, src/GovUk.Education.ExploreEducationStatistics.Common.Tests/Extensions/ActionResultTestExtensions.cs, src/GovUk.Education.ExploreEducationStatistics.Common.Tests/Extensions/ValidationProblemViewModelTestExtensions.cs, src/GovUk.Education.ExploreEducationStatistics.Common/Validators/ValidationUtils.cs, src/GovUk.Education.ExploreEducationStatistics.Public.Data.Model/DataSetVersionImportStage.cs, src/GovUk.Education.ExploreEducationStatistics.Public.Data.Processor.Requests/DataSetVersionProcessRequest.cs, src/GovUk.Education.ExploreEducationStatistics.Public.Data.Processor.Requests/NextDataSetVersionCompleteImportRequest.cs, src/GovUk.Education.ExploreEducationStatistics.Public.Data.Processor.Requests/NextDataSetVersionCreateMappingsRequest.cs, src/GovUk.Education.ExploreEducationStatistics.Public.Data.Processor.Requests/Validators/ValidationMessages.cs, src/GovUk.Education.ExploreEducationStatistics.Public.Data.Processor.Tests/Functions/CompleteNextDataSetVersionImportFunctionTests.cs, src/GovUk.Education.ExploreEducationStatistics.Public.Data.Processor.Tests/Functions/CreateDataSetFunctionTests.cs, src/GovUk.Education.ExploreEducationStatistics.Public.Data.Processor.Tests/Functions/CreateNextDataSetVersionMappingsFunctionTests.cs, src/GovUk.Education.ExploreEducationStatistics.Public.Data.Processor.Tests/Functions/ProcessCompletionOfNextDataSetVersionImportFunctionTests.cs, src/GovUk.Education.ExploreEducationStatistics.Public.Data.Processor.Tests/Functions/ProcessInitialDataSetVersionFunctionTests.cs, src/GovUk.Education.ExploreEducationStatistics.Public.Data.Processor.Tests/Functions/ProcessNextDataSetVersionMappingsFunctionTests.cs, src/GovUk.Education.ExploreEducationStatistics.Public.Data.Processor.Tests/ProcessorFunctionsIntegrationTest.cs, src/GovUk.Education.ExploreEducationStatistics.Public.Data.Processor.ViewModels/ProcessDataSetVersionResponseViewModel.cs, src/GovUk.Education.ExploreEducationStatistics.Public.Data.Processor/Functions/ActivityNames.cs, src/GovUk.Education.ExploreEducationStatistics.Public.Data.Processor/Functions/CompleteNextDataSetVersionImportFunction.cs, src/GovUk.Education.ExploreEducationStatistics.Public.Data.Processor/Functions/CompleteNextDataSetVersionProcessingFunction.cs, src/GovUk.Education.ExploreEducationStatistics.Public.Data.Processor/Functions/CreateDataSetFunction.cs, src/GovUk.Education.ExploreEducationStatistics.Public.Data.Processor/Functions/CreateNextDataSetVersionMappingsFunction.cs, src/GovUk.Education.ExploreEducationStatistics.Public.Data.Processor/Functions/ProcessCompletionOfNextDataSetVersionFunction.cs, src/GovUk.Education.ExploreEducationStatistics.Public.Data.Processor/Functions/ProcessNextDataSetVersionMappingsFunction.cs, src/GovUk.Education.ExploreEducationStatistics.Public.Data.Processor/Services/DataSetService.cs, src/GovUk.Education.ExploreEducationStatistics.Public.Data.Processor/Services/DataSetVersionService.cs
This PR:
- adds an HTTP trigger for kicking off the completion of the next data set version import after mapping is complete.
- adds an orchestration that is triggered by the HTTP trigger.  Currently the additional logic to use the mappings to complete the import is not implemented, but will be added into this workflow as part of EES-4954.
- adds validation and tests around the new trigger and orchestration.
All 3 of the HTTP trigger Functions were returning the same response details, so I renamed `CreateDataSetResponseViewModel` to `ProcessDataSetVersionResponseViewModel` and reused across all 3.  This has led to a few little changes in other miscellaneous files.
As the import process is effectively "paused" at this stage of processing until the user finishes the manual mapping, I added …
=> EES-5238 - adding new HTTP trigger and orchestration for completing the next data set version import

src/GovUk.Education.ExploreEducationStatistics.Admin.Tests/Services/ReleaseDataFileServiceTest.cs, src/GovUk.Education.ExploreEducationStatistics.Admin/Models/DataFileInfo.cs, src/GovUk.Education.ExploreEducationStatistics.Admin/Services/ReleaseDataFileService.cs, src/GovUk.Education.ExploreEducationStatistics.Content.Model/ReleaseFile.cs
This is the small backend change to add the `IsLinkedToApiDataSet` flag to the `DataFileInfo` View Model. This will be used by the 'Data Uploads' page to detect whether or not it should hide the 'Delete files' and 'Replace data' buttons for a subject. If the subject is linked to an API data set, we will hide these buttons. Otherwise, we will show them.
This was a quick solution, trying to avoid making any major changes/refactors.
=> EES-5281-backend Adding `IsLinkedToApiDataSet` flag to the `DataFileInfo` View Model

src/GovUk.Education.ExploreEducationStatistics.Public.Data.Model/DataSetVersion.cs, src/GovUk.Education.ExploreEducationStatistics.Public.Data.Model/Database/PublicDataDbContext.cs, src/GovUk.Education.ExploreEducationStatistics.Public.Data.Model/Migrations/20240711142913_EE5239_AddPreviewTokenTable.Designer.cs, src/GovUk.Education.ExploreEducationStatistics.Public.Data.Model/Migrations/20240711142913_EE5239_AddPreviewTokenTable.cs, src/GovUk.Education.ExploreEducationStatistics.Public.Data.Model/Migrations/PublicDataDbContextModelSnapshot.cs, src/GovUk.Education.ExploreEducationStatistics.Public.Data.Model/PreviewToken.cs
This PR adds and configures the `PreviewToken` entity type to the Public API data model, following the writeup of the model in [EES-5239](https://dfedigital.atlassian.net/browse/EES-5239).
There is a zero-to-many relationship between `DataSetVersions` and `PreviewTokens`. `PreviewTokens` is made up of:
- **Id** (uuid) - The primary key of the table and also the security token, assuming that EES-4913 decides to secure the Public API with unique tokens.
- **Label** (character, max 100) - Label of the PreviewToken.
- **DataSetVersionId** (uuid) - Foreign key of the DataSetVersion which owns the PreviewToken.
- **CreatedByUserId** (uuid) - Id of the user in the Admin’s Identity model who created the PreviewToken. This is going to be used when building the view model to get or list …
=> EES-5239 Add `PreviewToken` to Public API data model

src/GovUk.Education.ExploreEducationStatistics.Admin/GovUk.Education.ExploreEducationStatistics.Admin.csproj, src/GovUk.Education.ExploreEducationStatistics.Admin/Services/LoggingNotificationClient.cs, src/GovUk.Education.ExploreEducationStatistics.Notifier/GovUk.Education.ExploreEducationStatistics.Notifier.csproj
This PR is part of the work to update all minor backend dependencies.
The change from GovukNotify 7.0.0 to 7.1.0 includes a change to `SendEmail`, which now includes an additional optional string argument, `oneClickSubscribeURL`.
This addition prevents Admin from building due to `LoggingNotificationClient` implementing `INotificationClient`.
=> EES-4529 Update GovukNotify to 7.1.0

src/GovUk.Education.ExploreEducationStatistics.Admin.Tests/Controllers/Api/Public.Data/PreviewTokenControllerTests.cs, src/GovUk.Education.ExploreEducationStatistics.Admin/Controllers/Api/Public.Data/PreviewTokenController.cs, src/GovUk.Education.ExploreEducationStatistics.Admin/Requests/Public.Data/PreviewTokenCreateRequest.cs, src/GovUk.Education.ExploreEducationStatistics.Admin/Services/Interfaces/Public.Data/IPreviewTokenService.cs, src/GovUk.Education.ExploreEducationStatistics.Admin/Services/Public.Data/PreviewTokenService.cs, src/GovUk.Education.ExploreEducationStatistics.Admin/Startup.cs, src/GovUk.Education.ExploreEducationStatistics.Admin/Validators/ValidationMessages.cs, src/GovUk.Education.ExploreEducationStatistics.Admin/ViewModels/Public.Data/PreviewTokenViewModel.cs, src/GovUk.Education.ExploreEducationStatistics.Common.Tests/Extensions/HttpResponseMessageTestExtensions.cs, src/GovUk.Education.ExploreEducationStatistics.Public.Data.Model.Tests/Fixtures/DataSetVersionGeneratorExtensions.cs, src/GovUk.Education.ExploreEducationStatistics.Public.Data.Model.Tests/Fixtures/PreviewTokenGeneratorExtensions.cs
This PR adds two new secured Admin endpoints to create a `PreviewToken` and get a `PreviewToken`.
Creating a new token is a `POST` request which accepts:
- `dataSetVersionId (Guid, required)`: Id of the `DataSetVersion` which the token is being created for and will be owned by.
- `label (string, required, max length 100 characters)` -  Label of the token. 
Example request:
```http
POST https://localhost:5021/api/public-data/preview-tokens
Content-Type: application/json
{
"dataSetVersionId": "00000000-0000-0000-0000-000000000000",
"label": "Label"
}
```
If successful it responds with a 201 Created Response including a `Location` header containing a URL to the `PreviewToken` entity.
Example response:
```http
HTTP/1.1 201 Created
Content-Type: application/json; charset=utf-8
Location: …
```
=> EES-4914 Add endpoints to create a `PreviewToken` and get a `PreviewToken`

src/GovUk.Education.ExploreEducationStatistics.Admin.Tests/Controllers/Api/Public.Data/PreviewTokenControllerTests.cs, src/GovUk.Education.ExploreEducationStatistics.Admin/Controllers/Api/Public.Data/PreviewTokenController.cs, src/GovUk.Education.ExploreEducationStatistics.Admin/Services/Interfaces/Public.Data/IPreviewTokenService.cs, src/GovUk.Education.ExploreEducationStatistics.Admin/Services/Public.Data/PreviewTokenService.cs, src/GovUk.Education.ExploreEducationStatistics.Admin/Startup.cs
This PR adds a new secured Admin endpoint to list the `PreviewToken`'s for a data set version.
Listing preview tokens is a `GET` request which accepts `dataSetVersionId` appended as a query parameter.
Example request:
```http
GET https://localhost:5021/api/public-data/preview-tokens?dataSetVersionId=00000000-0000-0000-0000-000000000000
```
If the request is valid a 200 OK response is returned with a body containing the list of preview tokens for the specified data set version in descending expiry date order.
Example response:
```http
HTTP/1.1 200 OK
Content-Type: application/json; charset=utf-8
[
{
"id": "71c09001-0af7-9d71-bd1b-5f01e8d3d131",
"label": "Token for Cam's testing",
"status": "Active",
"createdByEmail": "first.last@education.gov.uk",
"created": …
```
=> EES-4916 Add endpoint to list `PreviewToken`'s

src/explore-education-statistics-admin/src/components/PageHeader.tsx, src/explore-education-statistics-admin/src/pages/publishers-guide/PublishersGuide.tsx, src/explore-education-statistics-admin/src/routes/routes.ts
This will give a clear set of links and guidance so that all users on the service can be aware of the surrounding support offering on the service.
=> EES-5345: Add Publisher's Guide page.

src/GovUk.Education.ExploreEducationStatistics.Admin.Tests/Controllers/Api/Public.Data/PreviewTokenControllerTests.cs, src/GovUk.Education.ExploreEducationStatistics.Admin/Controllers/Api/Public.Data/PreviewTokenController.cs, src/GovUk.Education.ExploreEducationStatistics.Admin/Services/Interfaces/Public.Data/IPreviewTokenService.cs, src/GovUk.Education.ExploreEducationStatistics.Admin/Services/Public.Data/PreviewTokenService.cs, src/GovUk.Education.ExploreEducationStatistics.Admin/Startup.cs, src/GovUk.Education.ExploreEducationStatistics.Admin/Validators/ValidationMessages.cs
This PR adds a new secured Admin endpoint to revoke a `PreviewToken`.
Revoking a token is a `POST` request which accepts the `PreviewToken` id appended as a path parameter.
Example request:
```http
POST https://localhost:5021/api/public-data/preview-tokens/00000000-0000-0000-0000-000000000000/revoke
```
If the request is valid the preview token is revoked by updating the `Expiry` to the current date, and a 200 OK response is returned with body containing the updated preview token resource. 
Example response:
```http
HTTP/1.1 200 OK
{
"id": "00000000-0000-0000-0000-000000000000",
"label": "Label",
"status": "Expired",
"createdByEmail": "ees-test.bau1@education.gov.uk",
"created": "2024-07-19T12:42:30.762579+00:00",
"expiry": "2024-07-19T12:42:39.7281552+00:00",
"updated": …
```
=> EES-4915 Add endpoint to revoke a `PreviewToken`

src/GovUk.Education.ExploreEducationStatistics.Common/Requests/QueryRequests.cs, src/explore-education-statistics-admin/src/pages/release/content/contexts/__tests__/ReleaseContentContext.test.tsx, src/explore-education-statistics-admin/src/pages/release/datablocks/__tests__/ReleaseDataBlockEditPage.test.tsx, src/explore-education-statistics-admin/src/pages/release/datablocks/components/DataBlockPageReadOnlyTabs.tsx, src/explore-education-statistics-admin/src/pages/release/datablocks/components/DataBlockPageTabs.tsx, src/explore-education-statistics-admin/src/pages/release/datablocks/components/__tests__/DataBlockPageTabs.test.tsx, src/explore-education-statistics-admin/src/pages/release/datablocks/components/chart/ChartBuilder.tsx, src/explore-education-statistics-common/src/modules/table-tool/components/__tests__/TimePeriodDataTable.test.tsx, src/explore-education-statistics-common/src/services/tableBuilderService.ts, src/explore-education-statistics-frontend/src/modules/table-tool/__tests__/TableToolPage.test.tsx
This PR fixes a bug introduced in EES-5275.
While fixing this, I noticed that the `includeGeoJson` wasn't being used, so I've also removed that as part of this PR.
=> EES-5258 Fix blank map charts bug

src/GovUk.Education.ExploreEducationStatistics.Admin.Tests/Controllers/Api/Public.Data/DataSetsControllerTests.cs, src/GovUk.Education.ExploreEducationStatistics.Admin/Services/Public.Data/DataSetService.cs, src/GovUk.Education.ExploreEducationStatistics.Admin/ViewModels/Public.Data/DataSetVersionViewModels.cs, src/GovUk.Education.ExploreEducationStatistics.Admin/ViewModels/Public.Data/DataSetViewModels.cs, src/explore-education-statistics-admin/src/services/apiDataSetService.ts
This PR:
- adds flags to the DataSetDraftVersionViewModel to support the rendering of the "Draft version tasks" section of the Data Set Details page in Admin.
We make sure only to fetch the necessary columns themselves from the db to prevent having to load any expensive JSON from the mapping columns that are in the same table.
=> EES-5346 add mapping complete flags to data set

src/GovUk.Education.ExploreEducationStatistics.Notifier.Tests/Functions/ApiSubscriptionFunctionsTests.cs, src/GovUk.Education.ExploreEducationStatistics.Notifier/Functions/ApiSubscriptionFunctions.cs, src/GovUk.Education.ExploreEducationStatistics.Notifier/Services/ApiSubscriptionService.cs, src/GovUk.Education.ExploreEducationStatistics.Notifier/Services/Interfaces/IApiSubscriptionService.cs, src/GovUk.Education.ExploreEducationStatistics.Notifier/Validators/ValidationMessages.cs
This PR adds an endpoint to the Notifier project to allow users to unsubscribe from API data sets.
The status codes that the endpoint returns are:
- `204` the subscription was successfully deleted in the database (hence, the user is now unsubscribed)
- `400` either the token supplied is invalid, **or** the subscription has not yet been verified (you can't unsubscribe to something you were never subscribed to!)
- `404` the subscription does not exist (applies to both pending and verified subscriptions)
=> EES-4929 Adding endpoint to unsubscribe users from API data sets

data/public-api-db/00-init.sh
This PR is a bugfix for https://github.com/dfe-analytical-services/explore-education-statistics/pull/5044. It ensures that the application user role `app_public_data_api` has USAGE privilege to access objects in the public schema.
The init script ran the equivalent of the following:
```sql
GRANT CREATE ON SCHEMA public TO app_public_data_api;
GRANT USAGE ON SCHEMA public TO app_public_data_processor;
GRANT USAGE ON SCHEMA public TO app_admin;
GRANT USAGE ON SCHEMA public TO app_publisher;
CREATE ROLE public_data_read_write WITH NOLOGIN;
GRANT public_data_read_write TO app_public_data_api;
GRANT public_data_read_write TO app_public_data_processor;
GRANT public_data_read_write TO app_admin;
GRANT public_data_read_write TO app_publisher;
```
Application user role `app_public_data_api` is …
=> 🐛 EES-5329 Ensure `app_public_data_api` has `USAGE` privilege on public schema

src/GovUk.Education.ExploreEducationStatistics.Admin/Startup.cs
This PR fixes a bug where amendment cancelling resulted in a 500.
This happened because in `ReleaseService#DeleteReleaseVersion`, `_processorClient.BulkDeleteDataSetVersions` tries to interact with Public API infrastructure that isn't currently deployed to environments.
This PR adds `NoOpProcessorClient`, which is used instead of `ProcessorClient` based on the value of the `PublicDataDbExists` configuration variable.
=> EES-5361 Fix amendment cancelling

src/GovUk.Education.ExploreEducationStatistics.Public.Data.Api/GovUk.Education.ExploreEducationStatistics.Public.Data.Api.csproj, src/GovUk.Education.ExploreEducationStatistics.Public.Data.Model/GovUk.Education.ExploreEducationStatistics.Public.Data.Model.csproj, src/GovUk.Education.ExploreEducationStatistics.Public.Data.Processor/GovUk.Education.ExploreEducationStatistics.Public.Data.Processor.csproj, src/GovUk.Education.ExploreEducationStatistics.Public.Data.Processor/Repository/LocationsDuckDbRepository.cs, src/GovUk.Education.ExploreEducationStatistics.Public.Data.Scripts/Commands/SeedDataCommand.cs, src/GovUk.Education.ExploreEducationStatistics.Public.Data.Scripts/GovUk.Education.ExploreEducationStatistics.Public.Data.Scripts.csproj
This PR updates projects related to the Public API to use `DuckDB.NET.Data.Full` 1.0.2.
It fixes the incorrect placement of `CreateRow` in methods `LocationsDuckDbRepository.CreateLocationsTable` and `SeedDataCommand.Seeder.CreateParquetLocationMetaTable` which was causing an error when upgrading between 0.10.2 and 1.0.0.
> System.IndexOutOfRangeException : The table location_options has 9 columns but you are trying to append value for column 10
=> EES-5365 Update to `DuckDB.NET.Data.Full` 1.0.2

src/GovUk.Education.ExploreEducationStatistics.Admin.Tests/Services/ReleaseDataFileServiceTests.cs, src/GovUk.Education.ExploreEducationStatistics.Admin/Models/DataFileInfo.cs, src/GovUk.Education.ExploreEducationStatistics.Admin/Services/ReleaseDataFileService.cs, src/GovUk.Education.ExploreEducationStatistics.Content.Api.Tests/Controllers/DataSetFilesControllerTests.cs, src/GovUk.Education.ExploreEducationStatistics.Content.Model/ReleaseFile.cs, src/GovUk.Education.ExploreEducationStatistics.Content.Services/DataSetFileService.cs, src/explore-education-statistics-admin/src/pages/release/data/components/ReleaseDataUploadsSection.tsx, src/explore-education-statistics-admin/src/pages/release/data/components/__tests__/ReleaseDataUploadsSection.test.tsx, src/explore-education-statistics-admin/src/services/releaseDataFileService.ts
Shows a modal informing the user that they can't replace data / delete data files if the files are linked to an API data set.
=> EES-5281 prevent deleting and replacing data for files with api data sets

src/GovUk.Education.ExploreEducationStatistics.Admin/GovUk.Education.ExploreEducationStatistics.Admin.csproj, src/GovUk.Education.ExploreEducationStatistics.Content.Api/GovUk.Education.ExploreEducationStatistics.Content.Api.csproj, src/GovUk.Education.ExploreEducationStatistics.Data.Api/GovUk.Education.ExploreEducationStatistics.Data.Api.csproj, src/GovUk.Education.ExploreEducationStatistics.Public.Data.Api.Tests/Swagger/RequiredPropertySchemaFilterTests.cs, src/GovUk.Education.ExploreEducationStatistics.Public.Data.Api/GovUk.Education.ExploreEducationStatistics.Public.Data.Api.csproj
This PR updates `Swashbuckle.AspNetCore` from `6.5.0 --> 6.6.2`.
Prior to this, there was a bug whereby a `required` but `nullable` property (both for reference and non-reference types) was being flagged as non-nullable by swashbuckle. Issue described here https://github.com/domaindrivendev/Swashbuckle.AspNetCore/issues/2877
A fix for this was made here https://github.com/domaindrivendev/Swashbuckle.AspNetCore/pull/2879
=> EES-5366 Updating Swashbuckle.AspNetCore

infrastructure/templates/template.json, src/GovUk.Education.ExploreEducationStatistics.Admin.Tests/Controllers/Api/Public.Data/DataSetVersionsControllerTests.cs, src/GovUk.Education.ExploreEducationStatistics.Admin.Tests/appsettings.IntegrationTest.json, src/GovUk.Education.ExploreEducationStatistics.Admin/Controllers/Api/Public.Data/DataSetVersionsController.cs, src/GovUk.Education.ExploreEducationStatistics.Admin/Services/Interfaces/Public.Data/IDataSetVersionService.cs, src/GovUk.Education.ExploreEducationStatistics.Admin/Services/Interfaces/Public.Data/IPublicDataApiClient.cs, src/GovUk.Education.ExploreEducationStatistics.Admin/Services/Public.Data/DataSetVersionService.cs, src/GovUk.Education.ExploreEducationStatistics.Admin/Services/Public.Data/PublicDataApiClient.cs, src/GovUk.Education.ExploreEducationStatistics.Admin/Settings/PublicDataApiOptions.cs, src/GovUk.Education.ExploreEducationStatistics.Admin/Settings/PublicDataProcessorOptions.cs, src/GovUk.Education.ExploreEducationStatistics.Admin/Startup.cs, src/GovUk.Education.ExploreEducationStatistics.Admin/appsettings.Development.json, src/GovUk.Education.ExploreEducationStatistics.Public.Data.Api.Tests/Security/AuthorizationHandlers/ViewDataSetVersionAuthorizationHandlerTests.cs, src/GovUk.Education.ExploreEducationStatistics.Public.Data.Api/Options/ContentApiOptions.cs, src/GovUk.Education.ExploreEducationStatistics.Public.Data.Api/Options/MiniProfilerOptions.cs, src/GovUk.Education.ExploreEducationStatistics.Public.Data.Api/Security/AuthorizationHandlers/ViewDataSetVersionAuthorizationHandler.cs
This PR adds the admin endpoint for fetching a data set version's changelog.
The endpoint is accessed via: `GET /api/public-data/data-set-versions/{dataSetVersionId}/changes`
We have implemented this by proxying requests to the public API's changelog endpoint via the admin. We have implemented it like this to avoid sharing view models and other code between the public API and the admin (keeping separation of concerns). Additionally, we can optimise by streaming the public API's response directly to the client rather than re-serialising into a second JSON response.
**Note** - This endpoint will not be fully functional until authentication is added to the public API to allow the admin API to fetch changelogs for draft data set versions. This should be implemented in …
=> EES-5362 Add admin endpoint for data set version changelog

src/GovUk.Education.ExploreEducationStatistics.Admin.Tests/Controllers/Api/Public.Data/DataSetVersionMappingControllerTests.cs, src/GovUk.Education.ExploreEducationStatistics.Admin/Services/Public.Data/DataSetVersionMappingService.cs, src/GovUk.Education.ExploreEducationStatistics.Common/Model/JsonDtos.cs, src/GovUk.Education.ExploreEducationStatistics.Public.Data.Model.Tests/Fixtures/FilterMappingPlanGeneratorExtensions.cs, src/GovUk.Education.ExploreEducationStatistics.Public.Data.Model.Tests/Fixtures/LocationMappingPlanGeneratorExtensions.cs, src/GovUk.Education.ExploreEducationStatistics.Public.Data.Model/Database/PublicDataDbContext.cs, src/GovUk.Education.ExploreEducationStatistics.Public.Data.Model/Dtos/FilterAndOptionMappingTypeDto.cs, src/GovUk.Education.ExploreEducationStatistics.Public.Data.Model/Migrations/PublicDataDbContextModelSnapshot.cs, src/GovUk.Education.ExploreEducationStatistics.Public.Data.Processor.Tests/Functions/ProcessNextDataSetVersionMappingsFunctionTests.cs, src/GovUk.Education.ExploreEducationStatistics.Public.Data.Processor/Services/DataSetVersionMappingService.cs
This PR:
- adds in code to more intelligently guess the next version number of the next data set version after auto-mapping has completed.
- adds in code to update the "LocationMappingsComplete" and "FilterMappingsComplete" columns after autosaves complete.
- adds in code to update the guessed version number of the next data set version after autosaves complete.
The main idea behind this PR is that we update the expected version number of the next data set version whenever we can, so we can always see what the next version number should be based upon the mapping work undertaken so far.
The other secondary part of this PR ensures that our "MappingsComplete" flags are always up-to-date after autosaves have completed. 
When we very first create the skeleton entry for the next DataSetVersion, …
=> EES-4947 - updating version number after saves

src/GovUk.Education.ExploreEducationStatistics.Admin.Tests/Controllers/Api/Public.Data/DataSetVersionsControllerTests.cs, src/GovUk.Education.ExploreEducationStatistics.Admin/Controllers/Api/Public.Data/DataSetVersionsController.cs, src/GovUk.Education.ExploreEducationStatistics.Admin/Requests/Public.Data/DataSetVersionUpdateRequest.cs, src/GovUk.Education.ExploreEducationStatistics.Admin/Services/Interfaces/Public.Data/IDataSetVersionService.cs, src/GovUk.Education.ExploreEducationStatistics.Admin/Services/Public.Data/DataSetService.cs, src/GovUk.Education.ExploreEducationStatistics.Admin/Services/Public.Data/DataSetVersionService.cs, src/GovUk.Education.ExploreEducationStatistics.Admin/Startup.cs, src/GovUk.Education.ExploreEducationStatistics.Admin/Validators/ValidationMessages.cs, src/GovUk.Education.ExploreEducationStatistics.Admin/ViewModels/Public.Data/DataSetVersionViewModels.cs, src/GovUk.Education.ExploreEducationStatistics.Public.Data.Model.Tests/Fixtures/DataSetVersionGeneratorExtensions.cs, src/GovUk.Education.ExploreEducationStatistics.Public.Data.Model/DataSetVersion.cs, src/GovUk.Education.ExploreEducationStatistics.Public.Data.Processor/Services/DataSetVersionService.cs
This PR adds a generic PATCH endpoint for BAU users to update a `DataSetVersion`.
Currently, the only properties that can be updated through this endpoint are the changelog `Notes`. In the future, we may add more properties to the request model. The idea is that the request parameters are all optional (aside from the `DataSetVersionId`) - and only the non-null fields will be updated.
The endpoint will return the following HTTP status codes:
- `200` 
- with a body of `DataSetDraftVersionViewModel` when successfully updated
- `400`
- when either:
- the target `DataSetVersion` is in a status whereby it cannot be updated. Namely: `Processing`/`Published`/`Deprecated`/`Withdrawn`
- the `DataSetVersion` is the **first** version, `1.0`, and we are trying to update the `Notes`. Only versions …
=> EES-4952 - Changelog: Save user inputted Changelog notes

src/explore-education-statistics-admin/src/pages/release/ReleasePageContainer.tsx, src/explore-education-statistics-admin/src/pages/release/data/ReleaseApiDataSetDetailsPage.tsx, src/explore-education-statistics-admin/src/pages/release/data/ReleaseApiDataSetPreviewTokenLogPage.tsx, src/explore-education-statistics-admin/src/pages/release/data/ReleaseApiDataSetPreviewTokenPage.tsx, src/explore-education-statistics-admin/src/pages/release/data/__tests__/ReleaseApiDataSetPreviewTokenLogPage.test.tsx, src/explore-education-statistics-admin/src/routes/releaseRoutes.ts, src/explore-education-statistics-admin/src/services/previewTokenService.ts
Adds the preview token log page.
=> EES-4368 api data set preview token log

src/explore-education-statistics-admin/src/pages/release/data/ReleaseApiDataSetPreviewTokenPage.tsx
This PR fixes a bug on the release API data set preview token page where all instances of the data set Id are currently displaying a data set version Id.
=> 🐛 EES-4367 Change data set version id to data set id on release API data set preview token page

src/GovUk.Education.ExploreEducationStatistics.Admin.Tests/Controllers/Api/Public.Data/DataSetVersionsControllerTests.cs, src/GovUk.Education.ExploreEducationStatistics.Admin.Tests/Controllers/Api/Public.Data/DataSetsControllerTests.cs, src/GovUk.Education.ExploreEducationStatistics.Admin/Controllers/Api/Public.Data/DataSetVersionsController.cs, src/GovUk.Education.ExploreEducationStatistics.Admin/Requests/Public.Data/DataSetVersionListRequest.cs, src/GovUk.Education.ExploreEducationStatistics.Admin/Services/Interfaces/Public.Data/IDataSetVersionService.cs, src/GovUk.Education.ExploreEducationStatistics.Admin/Services/Public.Data/DataSetService.cs, src/GovUk.Education.ExploreEducationStatistics.Admin/Services/Public.Data/DataSetVersionService.cs, src/GovUk.Education.ExploreEducationStatistics.Admin/Startup.cs, src/GovUk.Education.ExploreEducationStatistics.Admin/ViewModels/Public.Data/DataSetVersionViewModels.cs, src/GovUk.Education.ExploreEducationStatistics.Public.Data.Api/Security/AuthorizationHandlers/ViewDataSetVersionAuthorizationHandler.cs, src/GovUk.Education.ExploreEducationStatistics.Public.Data.Api/Services/DataSetService.cs, src/GovUk.Education.ExploreEducationStatistics.Public.Data.Model/Extensions/DataSetAuthExtensions.cs, src/GovUk.Education.ExploreEducationStatistics.Public.Data.Model/Extensions/DataSetVersionAuthExtensions.cs
This PR adds a GET endpoint for BAU users to retrieve a **paginated** list of previously published Data Set Versions for a specific Data Set.
BAU Users should be able to see the version history for all previous versions of an API data set (but not any that are in draft status) within the “Api Datasets” tab under any current versions. 
For each version listed they will see its version number, related release, status and a link to view the changelog and a link to view details.
I have chosen to return slightly more data than necessary in the view model, in pursuit of trying to re-use the view-models we already have. I thought the tradeoff of re-using some view-models, on both the backend and client, outweighed the downside of returning more data than we need, for this particular view. In the …
=> EES-4920 Version History: Admin Endpoint to list published versions of an API dataset

src/explore-education-statistics-admin/src/pages/bau/BoundaryDataPage.tsx
"k" character added accidentally caused table head/body misalignment, this PR removes that character.
=> EES-5326: Remove "k" character from boundary level table markup.

infrastructure/templates/template.json
:warning: Added the "Do Not Merge" label to this until I'm back, as this could result in some downtime if it doesn't go 100% to plan!
This PR:
- is trying a change to how we add / update access policies in the ARM template's Key Vault deploy, to prevent it from removing any policies that aren't explicitly listed.
This is in an attempt to allow the Bicep templates to deploy any policies that it needs to separately from the main ARM template, by moving the access policies to be a child resource of the main Key Vault deploy.
The alternative is to add all the Public API Key Vault policies into the ARM template, but this isn't ideal, so fingers crossed!
=> EES-5382 - attempt to prevent ARM template deploy from clearing down other policies

src/explore-education-statistics-admin/src/pages/release/datablocks/components/chart/ChartBuilderTabSection.tsx, src/explore-education-statistics-admin/src/pages/release/datablocks/components/chart/__tests__/ChartBuilder.test.tsx, src/explore-education-statistics-admin/src/pages/release/datablocks/components/chart/__tests__/ChartBuilderTabSection.test.tsx
Fixes the issue where maps weren't displaying properly in the Chart Builder when you selected or changed boundary level. There could be more tests added for `ChartBuilderTabSection` but that's probably outside the remit of this PR.
=> EES-5412 fix map display in chart builder

infrastructure/templates/public-api/components/functionApp.bicep, infrastructure/templates/public-api/components/keyVaultRoleAssignment.bicep, infrastructure/templates/template.json
This PR:
- returns template.json back to its original state before EES-5387 work began
- adds a new keyVaultRoleAssignments.bicep module
- uses this instead of access policies to grant KV permissions to the Function App
If this all works, I'll also make this change in the "automating App Gateway" PR as well.
=> EES-5382 use key vault RBAC for public api

src/GovUk.Education.ExploreEducationStatistics.Admin.Tests/Controllers/Api/Public.Data/DataSetVersionsControllerTests.cs, src/GovUk.Education.ExploreEducationStatistics.Admin/Controllers/Api/Public.Data/DataSetVersionsController.cs, src/GovUk.Education.ExploreEducationStatistics.Admin/Requests/Public.Data/NextDataSetVersionCompleteImportRequest.cs, src/GovUk.Education.ExploreEducationStatistics.Admin/Services/Interfaces/Public.Data/IDataSetVersionService.cs, src/GovUk.Education.ExploreEducationStatistics.Admin/Services/Interfaces/Public.Data/IProcessorClient.cs, src/GovUk.Education.ExploreEducationStatistics.Admin/Services/Public.Data/DataSetVersionService.cs, src/GovUk.Education.ExploreEducationStatistics.Admin/Services/Public.Data/ProcessorClient.cs, src/GovUk.Education.ExploreEducationStatistics.Admin/Startup.cs, src/GovUk.Education.ExploreEducationStatistics.Public.Data.Processor.Requests/NextDataSetVersionMappingsCreateRequest.cs, src/GovUk.Education.ExploreEducationStatistics.Public.Data.Processor.Tests/Functions/CreateNextDataSetVersionMappingsFunctionTests.cs, src/GovUk.Education.ExploreEducationStatistics.Public.Data.Processor/Functions/CreateNextDataSetVersionMappingsFunction.cs, src/GovUk.Education.ExploreEducationStatistics.Public.Data.Processor/Services/DataSetVersionService.cs
This PR:
- adds a controller call to Admin to invoke the Data Processor endpoint that completes the import after mappings are complete.
- renames the original CreateNextDataSetVersion function to be CreateNextDataSetVersionMappings, to be more consistent with other naming around this function.
- adds some missing tests for CreateNextDataSetVersion in Admin.
=> EES-5238 - adding in controller call to invoke the completion of next data set version import

src/GovUk.Education.ExploreEducationStatistics.Data.Model/Migrations/20240802123234_Routine_RebuildIndexes.sql, src/GovUk.Education.ExploreEducationStatistics.Data.Model/Migrations/Current_Routine_RebuildIndexes.sql
This PR makes a couple of small changes to the RebuildIndexes stored procedure:
- We now set the the overall StartTime before fetching StartFragPercent values
- The ReportSent column has been removed
I've not created an additional migration for this PR, as so far this work has only been deployed to the dev environment. I will manually update the stored procedure on the dev.
=> EES-5368 On RebuildIndexes stored procedure, set start time before fetching StartFragPercent values

src/GovUk.Education.ExploreEducationStatistics.Admin.Tests/Controllers/Api/Public.Data/DataSetVersionMappingControllerTests.cs, src/GovUk.Education.ExploreEducationStatistics.Admin.Tests/Controllers/Api/Public.Data/DataSetVersionsControllerTests.cs, src/GovUk.Education.ExploreEducationStatistics.Admin.Tests/Controllers/Api/Public.Data/DataSetsControllerTests.cs, src/GovUk.Education.ExploreEducationStatistics.Admin.Tests/Services/ReleaseServiceTests.cs, src/GovUk.Education.ExploreEducationStatistics.Admin.Tests/Services/ReplacementServiceTests.cs, src/GovUk.Education.ExploreEducationStatistics.Admin/Services/Public.Data/DataSetService.cs, src/GovUk.Education.ExploreEducationStatistics.Admin/Services/Public.Data/DataSetVersionMappingService.cs, src/GovUk.Education.ExploreEducationStatistics.Admin/Services/Public.Data/DataSetVersionService.cs, src/GovUk.Education.ExploreEducationStatistics.Admin/Services/ReleaseService.cs, src/GovUk.Education.ExploreEducationStatistics.Admin/Services/ReplacementService.cs, src/GovUk.Education.ExploreEducationStatistics.Content.Model.Tests/Fixtures/ReleaseFileGeneratorExtensions.cs, src/GovUk.Education.ExploreEducationStatistics.Public.Data.Api.Tests/Controllers/DataSetVersionsControllerTests.cs, src/GovUk.Education.ExploreEducationStatistics.Public.Data.Api.Tests/Controllers/DataSetsControllerTests.cs, src/GovUk.Education.ExploreEducationStatistics.Public.Data.Api.Tests/Controllers/PublicationsControllerTests.cs, src/GovUk.Education.ExploreEducationStatistics.Public.Data.Api/Services/DataSetService.cs, src/GovUk.Education.ExploreEducationStatistics.Public.Data.Model.Tests/DataSetVersionTests.cs, src/GovUk.Education.ExploreEducationStatistics.Public.Data.Model/DataSetVersion.cs, src/GovUk.Education.ExploreEducationStatistics.Public.Data.Processor.Tests/Functions/BulkDeleteDataSetVersionsFunctionTests.cs, src/GovUk.Education.ExploreEducationStatistics.Public.Data.Processor.Tests/Functions/CreateNextDataSetVersionMappingsFunctionTests.cs, src/GovUk.Education.ExploreEducationStatistics.Public.Data.Processor.Tests/Functions/DeleteDataSetVersionFunctionTests.cs, src/GovUk.Education.ExploreEducationStatistics.Public.Data.Processor.Tests/Functions/ProcessNextDataSetVersionMappingsFunctionTests.cs, src/GovUk.Education.ExploreEducationStatistics.Public.Data.Processor/Services/DataSetVersionMappingService.cs, src/GovUk.Education.ExploreEducationStatistics.Public.Data.Processor/Services/DataSetVersionService.cs, src/GovUk.Education.ExploreEducationStatistics.Public.Data.Services.Tests/DataSetVersionPathResolverTests.cs, src/GovUk.Education.ExploreEducationStatistics.Public.Data.Services/DataSetVersionPathResolver.cs, src/GovUk.Education.ExploreEducationStatistics.Publisher/Services/DataSetPublishingService.cs
This PR fixes a bug where `ReleaseFiles` would continue to reference draft data set versions after they had been deleted. This was due to a couple of issues:
1. For v1+ data set versions, changes to the version number (e.g. when breaking changes are added) were not being made to the `ReleaseFile.PublicApiDataSetVersion` column as well. We now update this when the version number changes.
2. The incorrect version number was being used when querying for `ReleaseFile.PublicApiDataSetVersion`. We were querying with the 'public' version number (using non-standard `major.minor`), whereas the `PublicApiDataSetVersion` is stored with a standard semversion number (using `major.minor.patch`).
To help differentiate between these two version numbers better we've made the following changes to …
=> EES-5416 Fix release files not being unlinked when draft data set versions deleted

src/GovUk.Education.ExploreEducationStatistics.Common/Converters/GeographicLevelsListJsonConverter.cs, src/GovUk.Education.ExploreEducationStatistics.Content.Api.Tests/Controllers/PublicationControllerTests.cs, src/GovUk.Education.ExploreEducationStatistics.Content.Services.Tests/Cache/PublicationCacheServiceTests.cs, src/GovUk.Education.ExploreEducationStatistics.Content.Services/Cache/PublicationCacheService.cs, src/GovUk.Education.ExploreEducationStatistics.Content.Services/Requests/PublicationTreeFilter.cs
This PR reverts the change to remove unused Data Catalogue code - turns out it was being used!
=> EES-4670 Revert Data Catalogue code removal

src/GovUk.Education.ExploreEducationStatistics.Admin.Tests/Controllers/Api/Public.Data/DataSetVersionsControllerTests.cs, src/GovUk.Education.ExploreEducationStatistics.Admin/Controllers/Api/Public.Data/DataSetVersionsController.cs, src/GovUk.Education.ExploreEducationStatistics.Admin/Requests/Public.Data/DataSetVersionListRequest.cs, src/GovUk.Education.ExploreEducationStatistics.Admin/Services/Public.Data/DataSetService.cs, src/GovUk.Education.ExploreEducationStatistics.Admin/Services/Public.Data/DataSetVersionService.cs, src/GovUk.Education.ExploreEducationStatistics.Admin/ViewModels/Public.Data/DataSetVersionViewModels.cs
This PR changes data set version summaries in the admin to return file info:
- `DataSetVersionSummary.File.Id` (mapped from `ReleaseFile.File.DataSetFileId`)
- `DataSetVersionSummary.File.Title` (mapped from `ReleaseFile.Name`)
This can then be used in the frontend to link through to the data set page in the public frontend.
- Updated `ListVersions` endpoint to use a `dataSetId` query parameter instead of the parameter being inside of the URL. This was previously inconsistent with other data set version endpoints.
- Fixed `ListVersions` endpoint not 404ing if the data set can't be found.
=> EES-5427 Add file info to data set version summaries in admin

src/explore-education-statistics-admin/src/pages/release/ReleasePageContainer.tsx, src/explore-education-statistics-admin/src/pages/release/data/ReleaseApiDataSetDetailsPage.tsx, src/explore-education-statistics-admin/src/pages/release/data/ReleaseApiDataSetHistoryPage.tsx, src/explore-education-statistics-admin/src/pages/release/data/__tests__/ReleaseApiDataSetHistoryPage.test.tsx, src/explore-education-statistics-admin/src/pages/release/data/components/__tests__/DraftApiDataSetsTable.test.tsx, src/explore-education-statistics-admin/src/pages/release/data/components/__tests__/LiveApiDataSetsTable.test.tsx, src/explore-education-statistics-admin/src/pages/release/data/components/__tests__/ReleaseApiDataSetsSection.test.tsx, src/explore-education-statistics-admin/src/queries/apiDataSetVersionQueries.ts, src/explore-education-statistics-admin/src/routes/releaseRoutes.ts, src/explore-education-statistics-admin/src/services/apiDataSetService.ts, src/explore-education-statistics-admin/src/services/apiDataSetVersionService.ts
Adds the API data set history page in the admin. There are some TODOs pending a back end change (EES-5427).
The ticket doesn't mention pagination, but since the endpoint is paginated I thought I might as well add it in as it was quick to do.
=> EES-4382 api data set history page

src/GovUk.Education.ExploreEducationStatistics.Admin.Tests/Controllers/Api/Bau/BauCacheControllerTests.cs, src/GovUk.Education.ExploreEducationStatistics.Admin/Cache/LocationsForDataBlockCacheKey.cs, src/GovUk.Education.ExploreEducationStatistics.Admin/Controllers/Api/Bau/BauCacheController.cs, src/GovUk.Education.ExploreEducationStatistics.Admin/Controllers/Api/Statistics/TableBuilderController.cs, src/GovUk.Education.ExploreEducationStatistics.Admin/Startup.cs, src/GovUk.Education.ExploreEducationStatistics.Common.Tests/Services/FileStoragePathUtilsTests.cs, src/GovUk.Education.ExploreEducationStatistics.Common/Services/FileStoragePathUtils.cs, src/GovUk.Education.ExploreEducationStatistics.Data.Api/Cache/LocationsForDataBlockCacheKey.cs, src/GovUk.Education.ExploreEducationStatistics.Data.Api/Controllers/TableBuilderController.cs, src/GovUk.Education.ExploreEducationStatistics.Data.Api/Services/DataBlockService.cs, src/GovUk.Education.ExploreEducationStatistics.Data.Api/Services/Interfaces/IDataBlockService.cs, src/GovUk.Education.ExploreEducationStatistics.Data.Api/Startup.cs, src/GovUk.Education.ExploreEducationStatistics.Data.Services.Tests/LocationServiceTests.cs, src/GovUk.Education.ExploreEducationStatistics.Data.Services.Tests/SubjectResultMetaServiceTests.cs, src/GovUk.Education.ExploreEducationStatistics.Data.Services.Tests/TableBuilderServicePermissionTests.cs, src/GovUk.Education.ExploreEducationStatistics.Data.Services.Tests/TableBuilderServiceTests.cs, src/GovUk.Education.ExploreEducationStatistics.Data.Services/Interfaces/ILocationService.cs, src/GovUk.Education.ExploreEducationStatistics.Data.Services/Interfaces/ITableBuilderService.cs, src/GovUk.Education.ExploreEducationStatistics.Data.Services/LocationService.cs, src/GovUk.Education.ExploreEducationStatistics.Data.Services/SubjectResultMetaService.cs, src/GovUk.Education.ExploreEducationStatistics.Data.Services/TableBuilderService.cs, src/GovUk.Education.ExploreEducationStatistics.Data.ViewModels/Meta/LocationsMetaViewModels.cs
This PR adds a new endpoint which returns location data for a data block, based on the supplied boundary level. Once implemented, this will allow the frontend to have data blocks which reference numerous boundary levels (i.e. if the data spans a number of years, and the boundaries have changed over time), and then call the endpoint to retrieve the appropriate location data.
Due to the relatively large volume of data returned, this data is also cached in blob storage for efficiency/performance.
=> EES-5400: Create new endpoint to get GeoJSON for implementing multiple boundary files

src/GovUk.Education.ExploreEducationStatistics.Public.Data.Api.Tests/Controllers/DataSetsControllerTests.cs, src/GovUk.Education.ExploreEducationStatistics.Public.Data.Api/Services/DataSetService.cs
This PR fixes the public API's `/meta` endpoint not returning location options. This is likely a regression due to recent refactoring. 
Unfortunately, the tests were not sufficiently asserting on option counts, thus allowed this bug to sneak through. The tests have now been made more robust to check for this.
=> EES-5445 Fix data set meta endpoint not returning location options

src/GovUk.Education.ExploreEducationStatistics.Content.Services.Tests/Extensions/OrderedQueryableExtensionsTests.cs, src/GovUk.Education.ExploreEducationStatistics.Content.Services.Tests/PublicationServiceTests.cs, src/GovUk.Education.ExploreEducationStatistics.Content.Services/Extensions/OrderedQueryableExtensions.cs, src/GovUk.Education.ExploreEducationStatistics.Content.Services/PublicationService.cs
**EES-5254/5075**: Apply a secondary ordering to publications (i.e. after date/alphabetic ordering has taken place), which orders by the release type of the latest release version, using a pre-defined and hardcoded ordering rule.
**EES-5255**: Remove the time element from published dates during query execution. This ensures that publications published on the same date are ordered using the release type, rather than being based on the minutes/hours which may make one publication "newer" than another.
These changes allow users to see results ordered by release type when they share the same date, so that they can see the most relevant statistics first when searching.
=> EES-5254/5255/5075: Additionally order publications by latest release version type

src/explore-education-statistics-admin/src/pages/release/ReleasePageContainer.tsx, src/explore-education-statistics-admin/src/pages/release/data/ReleaseApiDataSetDetailsPage.tsx, src/explore-education-statistics-admin/src/pages/release/data/ReleaseApiDataSetPreviewTokenLogPage.tsx, src/explore-education-statistics-admin/src/pages/release/data/ReleaseApiDataSetVersionHistoryPage.tsx, src/explore-education-statistics-admin/src/pages/release/data/__tests__/ReleaseApiDataSetDetailsPage.test.tsx, src/explore-education-statistics-admin/src/pages/release/data/__tests__/ReleaseApiDataSetPreviewPage.test.tsx, src/explore-education-statistics-admin/src/pages/release/data/__tests__/ReleaseApiDataSetPreviewTokenLogPage.test.tsx, src/explore-education-statistics-admin/src/pages/release/data/__tests__/ReleaseApiDataSetPreviewTokenPage.test.tsx, src/explore-education-statistics-admin/src/pages/release/data/__tests__/ReleaseApiDataSetVersionHistoryPage.test.tsx, src/explore-education-statistics-admin/src/routes/releaseRoutes.ts
This PR hides the 'View changelog and guidance notes' button from v1 draft API data set versions.
- Hides draft data set version actions whilst a version is processing.
- Tidies up routes and naming for preview tokens and version history pages.
- Added 'Generate preview token' link button to preview token log page for convenience.
=> EES-5449 Hide changelog link for v1 draft API data set versions

src/GovUk.Education.ExploreEducationStatistics.Admin.Tests/Controllers/Api/Public.Data/DataSetVersionMappingControllerTests.cs, src/GovUk.Education.ExploreEducationStatistics.Admin/Services/Public.Data/DataSetVersionMappingService.cs, src/GovUk.Education.ExploreEducationStatistics.Public.Data.Processor.Tests/Functions/ProcessNextDataSetVersionMappingsFunctionTests.cs, src/GovUk.Education.ExploreEducationStatistics.Public.Data.Processor/Services/DataSetVersionMappingService.cs
This PR fixes a bug in the calculation of mapping states not considering deleted location levels correctly. Location levels are not mappable to one another, so only add or delete operations are possible if they are changed.
This impacts the following states during mapping:
- The `LocationMappingsComplete` flag in the mapping plan
- The data set version number i.e. was it a major or minor update
=> EES-5437 Fix deleted location levels not being considered in mapping state

src/GovUk.Education.ExploreEducationStatistics.Public.Data.Model/DataSetVersion.cs, src/GovUk.Education.ExploreEducationStatistics.Public.Data.Processor.Tests/Functions/ProcessCompletionOfNextDataSetVersionImportFunctionTests.cs, src/GovUk.Education.ExploreEducationStatistics.Public.Data.Processor/Functions/ActivityNames.cs, src/GovUk.Education.ExploreEducationStatistics.Public.Data.Processor/Functions/ProcessCompletionOfNextDataSetVersionFunction.cs, src/GovUk.Education.ExploreEducationStatistics.Public.Data.Processor/Services/DataSetVersionService.cs, src/GovUk.Education.ExploreEducationStatistics.Public.Data.Services.Tests/DataSetVersionPathResolverTests.cs, src/GovUk.Education.ExploreEducationStatistics.Public.Data.Services.Tests/TestDataSetVersionPathResolver.cs, src/GovUk.Education.ExploreEducationStatistics.Public.Data.Services/DataSetVersionPathResolver.cs, src/GovUk.Education.ExploreEducationStatistics.Public.Data.Services/Interfaces/IDataSetVersionPathResolver.cs
This PR:
- adds an additional stage to the final import orchestration of a next DataSetVersion, in which the storage directory path is updated to reflect any changes in the DataSetVersion's version number during its mapping phase.
- if the version number is unchanged from the default version number originally assigned when the next DataSetVersion was created, no path update is necessary.
Thereafter, the import process should continue as usual, using the now-updated file storage path.
I've added a convenience `DataSetVersion.DefautlNextVersion()" method which will give us the expected next version number of a DataSetVersion (using the existing implementation of updating the minor version).  We can then use this method to assign a default version number to a brand new next DataSetVersion, …
=> EES-5442 - updating file storage path to reflect updates to a next DataSetVersion's version number

src/explore-education-statistics-common/src/styles/_typography.scss
This PR fixes a regression in list styling (caused by #5135) causing breadcrumb and footer items being too big.
We had attempted to apply `govuk-list` styling globally to `ul` and `ol` elements to provide better support for nested lists, but unfortunately, this set a default font size that would require additional component-level styles to fix.
Instead, we've now opted to bring in the specific `govuk-list` styles needed for nested lists (the original intention) and removed applying all the styles globally.
=> EES-5453 Fix list styling for breadcrumbs and footer items

infrastructure/templates/template.json
:warning: Adding "Do Not Merge" on this until Mark Nelson has had a chance to add the new role assignments for the EDAP and EES Admin groups. :warning:  
This PR:
- switches Key Vault to RBAC mode instead of Access Policies
- migrates all existing Access Policies that supply "Get" and "List" secrets privileges to be "Key Vault Secrets User" role assignments instead
As for the EDAP team and the EES Admin Group, we will not have the privileges to assign the appropriate roles for these permissions ourselves or via the DevOps SPN, so this will be done manually by Mark Nelson for us.  The following role assignments should give each group the equivalent of what they currently have in their Access Policies:
* Key Vault Certificates Officer
* Key Vault Secrets Officer
* Key Vault Crypto Officer
* …
=> EES-5382 - switch Key Vault to RBAC mode.  Migrate "Get/List secrets" policies to "Key Vault Secrets User" role assignments

src/explore-education-statistics-admin/src/pages/release/data/ReleaseApiDataSetChangelogPage.tsx, src/explore-education-statistics-admin/src/pages/release/data/ReleaseApiDataSetVersionHistoryPage.tsx, src/explore-education-statistics-admin/src/pages/release/data/__tests__/ReleaseApiDataSetVersionHistoryPage.test.tsx
This PR fixes the 'View changelog' links in the API data set version history page.
- Tweaked layout of version tags in the changelog page to be horizontal.
=> EES-5456 Fix broken changelog link in API data set version history

infrastructure/templates/public-api/api-infrastructure-pipeline.yml, infrastructure/templates/public-api/application/virtualNetwork.bicep, infrastructure/templates/public-api/assign-app-role-to-service-principal-template.yml, infrastructure/templates/public-api/components/appGateway.bicep, infrastructure/templates/public-api/components/containerApp.bicep, infrastructure/templates/public-api/components/keyVaultRoleAssignment.bicep, infrastructure/templates/public-api/components/wafPolicy.bicep, infrastructure/templates/public-api/deploy-stage-template.yml, infrastructure/templates/public-api/main.bicep, infrastructure/templates/public-api/parameters/main-dev.bicepparam, infrastructure/templates/public-api/parameters/main-preprod.bicepparam, infrastructure/templates/public-api/parameters/main-prod.bicepparam, infrastructure/templates/public-api/parameters/main-test.bicepparam
:warning: The testing of this automation will require some time without an App Gateway on Dev, as the existing one is replaced.  No doubt this'll take a couple of days!  Therefore I've put the "Do No Merge" label on until we agree a window of time to do this.
This PR:
- adds modules for the Bicep App Gateway and its WAF policy.
- adds configuration to host the Public API Container Apps through it.
This PR assumes that a pre-existing certificate for the Container App will have been set up prior to standing up the App Gateway. I've added instructions to do this in the Devops Wiki on the "Rolling out Public API infrastructure" page.
=> EES-5024 - adding App Gateway to Bicep deployment

infrastructure/templates/public-api/api-infrastructure-pipeline.yml, infrastructure/templates/public-api/components/containerRegistryRoleAssignment.bicep, infrastructure/templates/public-api/components/keyVaultRoleAssignment.bicep, infrastructure/templates/public-api/main.bicep
This PR:
- Adds the creation and the role assignments of the Container App managed identity into Bicep rather than being a manual task.
This is made possible now by the work of Mark Nelson to allow our DevOps SPNs to be able to assign a subset of common roles.
=> EES-5480 - handling creation of container app managed identity and its role assignments in Bicep

infrastructure/templates/public-api/application/privateDnsZones.bicep, infrastructure/templates/public-api/application/virtualNetwork.bicep, infrastructure/templates/public-api/components/appGateway.bicep, infrastructure/templates/public-api/components/functionApp.bicep, infrastructure/templates/public-api/components/postgresqlDatabase.bicep, infrastructure/templates/public-api/components/privateDnsZone.bicep, infrastructure/templates/public-api/components/privateEndpoint.bicep, infrastructure/templates/public-api/components/storageAccount.bicep, infrastructure/templates/public-api/main.bicep, infrastructure/templates/template.json
This PR:
- creates and maintains a private endpoint to allow inbound traffic to the data processor from the VNet.
This replaces a manually created one that we created when it turned out that simply linking the function app to the VNet via a subnet wasn't enough to allow inbound requests from Admin.
We now have new modules for setting up DNS zones and private endpoints.
This PR also sets up ahead of time a couple of special private DNS zones which are used to resolve IP addresses for private link services of different kinds.  They are specially-named zones as per this guide (and currently only support sites and PostgreSQL in out templates):
https://learn.microsoft.com/en-us/azure/private-link/private-endpoint-dns
Previously, a lot of Bicep code resided in the `postgresqlDatabase.bicep` …
=> Ees 5408 automate private endpoint creation for data procesor

tests/robot-tests/tests/libs/public-common.robot, tests/robot-tests/tests/public_api/public_api_dataset_cancel_and_removal.robot, tests/robot-tests/tests/public_api/public_api_dataset_preview_token.robot, tests/robot-tests/tests/public_api/public_api_restricted.robot
This PR:
- adds fail-fast behaviour to all Public API test suites
- adds more resilience to the Publication search on the Find Statistics page, so that we are guaranteed to find the correct Publication even if we end up with paginated results (due to lots of data piling up from multiple test runs with `--disable-teardown` enabled
Prior to this, the Publication search would not guarantee to bring up the correct Publication to the top of the search list if we did multiple runs while disabling teardown.  By adding "Relevance" to the search results, it'll then search by the closest matching name to the Publication title we're looking for.
=> EES-XXXX - Robot test improvements

tests/robot-tests/tests/libs/admin-common.robot
This PR:
- removes an (I think) unnecessary cache expiry wait whilst looking for a file to enter "Importing" status.
Cache expiries don't affect this code so I don't believe it should be here.  In addition it was causing Robot tests (`release_status.robot`) to fail, as on my local machine the file finished "Importing" before the sleep finished, and so the test got stuck on this step.
=> Ees xxxx robot test improvements 2

src/explore-education-statistics-admin/src/pages/release/content/components/ReleaseContent.tsx, src/explore-education-statistics-admin/src/prototypes/page-view/PrototypeReleaseContent.tsx, src/explore-education-statistics-common/src/modules/release/components/ReleaseSummarySection.tsx, src/explore-education-statistics-frontend/src/components/PageFooter.tsx, src/explore-education-statistics-frontend/src/modules/find-statistics/PublicationReleasePage.tsx
Following feedback from the Official Statistics Regulator, we need to make it clear who the producer of platform's content is.
This PR includes two small changes:
1. to identify DfE as the maintainer of the service (in the footer), and
2. to identify the DfE as the content producer on release pages.
These changes help assure users of the quality of the work, and identify who to direct queries to if the need arises.
=> EES-5477: Add text to footer/release page to identify DfE as the content's producer

infrastructure/templates/template.json
This PR:
- removes the Key Vault Secrets User assignment from the DevOps SPN deploy user, as they must have this role at least prior to being able to start a successful inf deploy.
It would not necessarily have been a problem to keep it if the role assignments our code produces resulted in the same GUID-based name for the assignment that manual assignment produced, but they don't and as a result it would otherwise cause a "RoleASssignmentAlreadyExists" error.
=> EES-5382 hotfix remove devops spn from key vault role assignment

infrastructure/templates/template.json
This PR:
- reverts the change to KV permission model until it has been manually switched
=> Ees 5382 hotfix remove devops spn from key vault role assignment disable rbac switch

src/explore-education-statistics-frontend/src/modules/data-catalogue/components/DataSetFileFootnotes.tsx
Fixes Footnotes rendering html as plain text in data catalogue pages.  
Implementation now follows suit with  other footnote rendering using `<ContentHtml / >` to render footnote labels
=> EES-5506 fix data-catalogue footnotes rendering html as plain text

src/GovUk.Education.ExploreEducationStatistics.Public.Data.Model/Migrations/20240902104511_InitialMigration.cs
This PR is (another) bugfix for https://github.com/dfe-analytical-services/explore-education-statistics/pull/5044.
While testing the `public_data_read_write` role added by EES-5329 I found that we can't insert/update/delete data in the Public API `__EFMigrationsHistory` database table.
The `InitialMigration` has grants at the beginning which affect all tables created subsequently by that migration and further migrations, i.e. all of our tables, allowing us to modify data. However these grants don't cover existing tables. The `__EFMigrationsHistory` table is created prior to the `InitialMigration` being run.
This PR adds an explicit grant in `InitialMigration` for the `__EFMigrationsHistory` table.
I was able to test this locally with the following steps to force the migration to run:
1. …
=> 🐛 EES-5505 Allow modifying data in Public API `__EFMigrationsHistory` database table

src/GovUk.Education.ExploreEducationStatistics.Admin.Tests/Services/ThemeServicePermissionTests.cs, src/GovUk.Education.ExploreEducationStatistics.Admin.Tests/Services/ThemeServiceTests.cs, src/GovUk.Education.ExploreEducationStatistics.Admin/Controllers/Api/ThemeController.cs, src/GovUk.Education.ExploreEducationStatistics.Admin/Services/Interfaces/IThemeService.cs, src/GovUk.Education.ExploreEducationStatistics.Admin/Services/ThemeService.cs
Robot UI tests generate themes and topics as part of their process, which are then removed during the teardown phase. This phase uses an existing endpoint which accepts an ID to target the removal of an individual resource.
UI test execution occasionally fails, or is cancelled prematurely, meaning that the teardown phase isn't triggered. This results in test resources remaining in the system and causing bloat.
This PR adds an endpoint which removes all themes and associated topics created during UI tests in one go, using the same logic to identify tests as is used for individual removal. The intended use for this endpoint is as part of a manual clean-up process when a notification is received regarding test execution failure, or eventually implemented into an automated process.
_The PR …
=> EES-4489: Add endpoint to remove all themes created by UI tests

infrastructure/parameters/test.parameters.json, infrastructure/templates/public-api/api-infrastructure-pipeline.yml, infrastructure/templates/public-api/application/public-api/publicApiApp.bicep, infrastructure/templates/public-api/application/public-api/publicApiAppIdentity.bicep, infrastructure/templates/public-api/application/shared/appGateway.bicep, infrastructure/templates/public-api/application/shared/containerAppEnvironment.bicep, infrastructure/templates/public-api/application/shared/postgreSqlFlexibleServer.bicep, infrastructure/templates/public-api/application/shared/privateDnsZones.bicep, infrastructure/templates/public-api/components/appGateway.bicep, infrastructure/templates/public-api/components/appGatewayBackendDns.bicep, infrastructure/templates/public-api/components/containerApp.bicep, infrastructure/templates/public-api/components/containerAppEnvironment.bicep, infrastructure/templates/public-api/components/postgresqlDatabase.bicep, infrastructure/templates/public-api/components/privateDnsZone.bicep, infrastructure/templates/public-api/deploy-stage-template.yml, infrastructure/templates/public-api/main.bicep, infrastructure/templates/public-api/types.bicep, infrastructure/templates/public-api/validate-stage-template.yml
This PR:
- contains all of the additional tweaks that were necessary to get the Public API infrastructure rollout successfully to the Test Resource Group, which prior to this did not have any Public API rollout attempts done to it.
Notable changes:
- The conditions evaluated to determine which stages to run in the pipeline have been updated to no longer rely on `succeeded()`, as this fails when a prior stage has been skipped.  Instead we explicitly check for `not(failed(), canceled())` instead.
- The Container App Docker Image pull credentials use the same shared SPN as we currently use for the Public Site.  This is in lieu of creating a shared Resource Group with an ACR instance in that all RGs can pull from.
-  A missing piece in the automation was a Private DNS Zone that links the …
=> Ees 5479 modularise bicep to test env

infrastructure/parameters/prod.parameters.json
This PR changes the statistics primary and replica databases in the Prod environment from provisioned 10 to 6 vCores. This is a code change to reflect the same change that's already been made to the databases manually on 19/09/24.
In EES-5339 we temporarily increased the scale of the Prod primary and replica statistics databases after slow running of the table tool was observed. That was found to be caused by long running table reindexing, and multiple days worth of scheduled reindexing runs overlapping.
In EES-5205 we aimed to prevent this by stopping further reindexing tasks from starting once a set time limit has been reached.
In EES-5368 we added logging for the reindexing so that we can observe which tasks ran to completion and their duration, and which tasks were skipped due to …
=> EES-5515 Reverting increase in number of provisioned vCores of Prod statistics databases made for EES-5339

src/GovUk.Education.ExploreEducationStatistics.Public.Data.Model/DataSetFilenames.cs, src/GovUk.Education.ExploreEducationStatistics.Public.Data.Processor.Tests/Functions/DeleteDataSetVersionFunctionTests.cs, src/GovUk.Education.ExploreEducationStatistics.Public.Data.Scripts/Commands/SeedDataCommand.cs, src/GovUk.Education.ExploreEducationStatistics.Public.Data.Services.Tests/DataSetVersionPathResolverTests.cs, src/GovUk.Education.ExploreEducationStatistics.Public.Data.Services/DataSetVersionPathResolver.cs, src/GovUk.Education.ExploreEducationStatistics.Public.Data.Services/Interfaces/IDataSetVersionPathResolver.cs
This PR updates public API file storage paths to group data set directories under a root `data-sets` directory.
This simplifies clearing down test data as we can just remove the `data-sets` directory in one go, rather than have to delete potentially hundreds (or thousands) of individual data set directories.
=> EES-5520 Group public API data sets in root `data-sets` dir

infrastructure/templates/public-api/api-infrastructure-pipeline.yml, infrastructure/templates/public-api/application/public-api/publicApiApp.bicep, infrastructure/templates/public-api/main.bicep
This corrects a bug introduced in the modularisation of the Bicep templates whereby the Public API URL was accidentally substituted in in place of the Public Site URL, leading to results in the Public Site not being allowed to include results from the Public API URL.
This also fixes the `isDev` branch test in `api-infrastructure-pipeline.yml` which had been accidentally left at the old Bicep modularisation branch whilst being tested off-branch.
=> EES-5512 - correcting Container App CORS policy to include public site URL rather than Public API url!

src/GovUk.Education.ExploreEducationStatistics.Public.Data.Api.Tests/Controllers/DataSetsControllerGetQueryTests.cs, src/GovUk.Education.ExploreEducationStatistics.Public.Data.Api.Tests/Controllers/DataSetsControllerPostQueryTests.cs, src/GovUk.Education.ExploreEducationStatistics.Public.Data.Api/Requests/DataSetQuerySort.cs, src/GovUk.Education.ExploreEducationStatistics.Public.Data.Api/Services/DataSetQueryService.cs
This PR updates the sort field format to:
- `filter|{id}` (for filters) 
- `indicator|{id}` (for indicators)
We need to change the format as filter and indicator public IDs can potentially collide using sqids so we need to remove any ambiguity by specifying the type.
We've also added a bunch of sorting tests that had been accidentally omitted.
=> EES-5511 Update data set query sorts to handle public IDs correctly

infrastructure/templates/public-api/application/public-api/publicApiApp.bicep, infrastructure/templates/public-api/main.bicep, src/GovUk.Education.ExploreEducationStatistics.Public.Data.Api.Tests/RequestTimeoutTests.cs, src/GovUk.Education.ExploreEducationStatistics.Public.Data.Api.Tests/appsettings.IntegrationTest.json, src/GovUk.Education.ExploreEducationStatistics.Public.Data.Api/Options/AppInsightsOptions.cs, src/GovUk.Education.ExploreEducationStatistics.Public.Data.Api/Options/AppSettingsOptions.cs, src/GovUk.Education.ExploreEducationStatistics.Public.Data.Api/Options/RequestTimeoutOptions.cs, src/GovUk.Education.ExploreEducationStatistics.Public.Data.Api/Startup.cs, src/GovUk.Education.ExploreEducationStatistics.Public.Data.Api/Swagger/SwaggerConfig.cs, src/GovUk.Education.ExploreEducationStatistics.Public.Data.Api/appsettings.Development.json, src/GovUk.Education.ExploreEducationStatistics.Public.Data.Api/appsettings.json
This PR adds the server URL to the OpenAPI docs so that it can be used independently of where it's hosted. The URL is passed into the docs via the `AppSettings.HostUrl` app setting.
- Simplified `ApplicationInsightsOptions` to `AppInsightsOptions`
- Refactored public API `Startup` to use typed options instead of getting values directly from `IConfiguration`.
=> EES-5518 Add server URL to OpenAPI docs

src/GovUk.Education.ExploreEducationStatistics.Public.Data.Api.Tests/RequestTimeoutTests.cs, src/GovUk.Education.ExploreEducationStatistics.Public.Data.Api/Startup.cs, src/GovUk.Education.ExploreEducationStatistics.Public.Data.Api/appsettings.json
This was accidentally set to 300 seconds instead of 30 seconds.
=> Fix incorrect default request timeout for public API

src/explore-education-statistics-common/src/components/CodeBlock.tsx, src/explore-education-statistics-frontend/src/modules/data-catalogue/DataSetFilePage.tsx, src/explore-education-statistics-frontend/src/modules/data-catalogue/components/DataSetFileUsage.tsx
This PR fixes:
- The main content column not taking the full 3/4th width (was 2/3rd)
- Incorrect use of `ChevronCard` wrapping the 'Download this data using code' section
- Incorrect heading markup for example code tabs
- Unneeded capitalisation of 'code' in 'Copy code'
=> EES-5536 Fix styling and markup issues in data set file usage section

infrastructure/templates/public-api/application/public-api/publicApiApp.bicep
This PR makes the following updates to the public API's Bicep template:
- `AppSettings__HostUrl` is now `App_Url` to match `AppOptions` changes in #5285
- Changes app settings parameter keys to use `:` syntax instead of `__`
=> EES-5531 Update public API Bicep params with renamed `App` options

README.md, infrastructure/templates/template.json, src/GovUk.Education.ExploreEducationStatistics.Admin/Migrations/ContentMigrations/20240927152418_EES5537_CreateNotifierUserAndGrantPermissions.Designer.cs, src/GovUk.Education.ExploreEducationStatistics.Admin/Migrations/ContentMigrations/20240927152418_EES5537_CreateNotifierUserAndGrantPermissions.cs, src/GovUk.Education.ExploreEducationStatistics.Notifier.Model/ReleaseNotificationMessage.cs, src/GovUk.Education.ExploreEducationStatistics.Notifier.Tests/Functions/PublicationSubscriptionFunctionsTests.cs, src/GovUk.Education.ExploreEducationStatistics.Notifier.Tests/Functions/ReleaseNotifierTests.cs, src/GovUk.Education.ExploreEducationStatistics.Notifier.Tests/GovUk.Education.ExploreEducationStatistics.Notifier.Tests.csproj, src/GovUk.Education.ExploreEducationStatistics.Notifier/Functions/PublicationSubscriptionFunctions.cs, src/GovUk.Education.ExploreEducationStatistics.Notifier/Functions/ReleaseNotifier.cs, src/GovUk.Education.ExploreEducationStatistics.Notifier/GovUk.Education.ExploreEducationStatistics.Notifier.csproj, src/GovUk.Education.ExploreEducationStatistics.Notifier/NotifierHostBuilder.cs, src/GovUk.Education.ExploreEducationStatistics.Notifier/local.settings.json, src/GovUk.Education.ExploreEducationStatistics.Publisher.Tests/Services/NotificationsServiceTests.cs, src/GovUk.Education.ExploreEducationStatistics.Publisher/PublisherHostBuilderExtensions.cs, src/GovUk.Education.ExploreEducationStatistics.Publisher/Services/NotificationsService.cs
This PR does three things
- Allows the Notifier to connect to the Content DB
- When unsubscribing a user, we now also remove any subscriptions from associated archived subscriptions.
- Fixes the unsubscribe link for subscribers to archived publications
Details for why we decided to create the DB connection for Notifier are in the comments in EES-5500. The TLDR is that we consider it better to open a Content DB connection for Notifier than continue to pass everything Notifier needs in requests. And now we have a Content DB connection in Notifier, this opens up the possibility for other simplifications, as Notifier can now fetch the data it needs itself.
:rotating_light: This PR requires faffy deploy steps detailed in EES-5537 :rotating_light:
=> EES-5537 EES-5500 Notifier ContentDB connection and archived subscriptions fixes

src/explore-education-statistics-admin/src/pages/release/data/ReleaseApiDataSetPreviewPage.tsx, src/explore-education-statistics-admin/src/pages/release/data/ReleaseApiDataSetPreviewTokenLogPage.tsx, src/explore-education-statistics-admin/src/pages/release/data/ReleaseApiDataSetPreviewTokenPage.tsx, src/explore-education-statistics-admin/src/pages/release/data/__tests__/ReleaseApiDataSetPreviewPage.test.tsx, src/explore-education-statistics-admin/src/pages/release/data/__tests__/ReleaseApiDataSetPreviewTokenLogPage.test.tsx, src/explore-education-statistics-admin/src/pages/release/data/__tests__/ReleaseApiDataSetPreviewTokenPage.test.tsx, src/explore-education-statistics-admin/src/pages/release/data/components/ApiDataSetPreviewTokenCreateForm.tsx, src/explore-education-statistics-common/src/components/CodeBlock.tsx, src/explore-education-statistics-common/src/components/CopyLinkModal.module.scss, src/explore-education-statistics-common/src/components/CopyLinkModal.tsx, src/explore-education-statistics-common/src/components/CopyTextButton.module.scss, src/explore-education-statistics-common/src/components/CopyTextButton.tsx, src/explore-education-statistics-common/src/components/UrlContainer.module.scss, src/explore-education-statistics-common/src/components/UrlContainer.tsx, src/explore-education-statistics-common/src/components/__tests__/CopyLinkModal.test.tsx, src/explore-education-statistics-common/src/components/__tests__/CopyTextButton.test.tsx, src/explore-education-statistics-common/src/styles/utils/_flex.scss, src/explore-education-statistics-frontend/src/modules/data-catalogue/components/DataSetFileUsage.tsx, src/explore-education-statistics-frontend/src/modules/data-catalogue/components/__tests__/DataSetFileUsage.test.tsx, tests/robot-tests/tests/libs/public-api-common.robot, tests/robot-tests/tests/public_api/public_api_cancel_and_removal.robot, tests/robot-tests/tests/public_api/public_api_dataset_preview_token.robot, tests/robot-tests/tests/public_api/public_api_preview_token.robot, tests/robot-tests/tests/public_api/public_api_resolve_mapping_statuses.robot, tests/robot-tests/tests/public_api/public_api_restricted.robot
This PR adds the preview token guidance for API data sets. This looks like:
- Fixed various issues with `UrlContainer` and `CopyTextButton`:
- Makes `label` required for `UrlContainer` so that the copy input is labelled correctly by the consumer.
- Allowes inline styling to be correctly toggled using the `inline` prop for `UrlContainer`.
- Changes `UrlContainer` and `CopyTextButton` to fill the parent's space as much as possible instead of being limited to 500px.
- Fixed incorrect flex styling causing the input in `CopyTextButton` to not take up the correct amount of space.
- Adds the GOV.UK focus style to the `UrlContainer` input.
- Improves how `CopyTextButton` responds at mobile / tablet.
- Updates `CopyTextButton` to show the `confirmMessage` in the button itself rather than in a …
=> EES-5497 Add API data set preview token guidance

src/GovUk.Education.ExploreEducationStatistics.Admin.Tests/Controllers/Api/UserManagement/UserManagementControllerTests.cs, src/GovUk.Education.ExploreEducationStatistics.Admin.Tests/Services/UserManagementServicePermissionTests.cs, src/GovUk.Education.ExploreEducationStatistics.Admin.Tests/Services/UserManagementServiceTests.cs, src/GovUk.Education.ExploreEducationStatistics.Admin/Database/UsersAndRolesDbContext.cs, src/GovUk.Education.ExploreEducationStatistics.Admin/Migrations/UsersAndRolesMigrations/20240924102651_EES2468_AddSetNullToUserInviteCreatedById.Designer.cs, src/GovUk.Education.ExploreEducationStatistics.Admin/Migrations/UsersAndRolesMigrations/20240924102651_EES2468_AddSetNullToUserInviteCreatedById.cs, src/GovUk.Education.ExploreEducationStatistics.Admin/Services/UserManagementService.cs, src/explore-education-statistics-admin/src/pages/bau/BauUsersPage.module.scss, src/explore-education-statistics-admin/src/pages/bau/BauUsersPage.tsx, src/explore-education-statistics-admin/src/pages/bau/__tests__/BauUsersPage.test.tsx, src/explore-education-statistics-admin/src/services/userService.ts
PR changes:
- Added ability to delete user on user management page
- Added frontend tests to BAU User Page (backend tests were already implemented for deleting a user)
- Updated `CreatedById` column in UserInvites table to set to null on deletion
=> EES-2468 Added Ability To Delete User

.husky/pre-commit, package.json, pnpm-lock.yaml
This PR fixes the pre-commit hooks that were previously not running and allowing various formatting and linting issues through (particularly in Python and Robot Framework code).
We've now fixed this by simply upgrading husky and lint-staged to the latest versions.
=> EES-5555 Fix pre-commit hooks

infrastructure/parameters/prod.parameters.json
This PR increases the number of provisions vCores of the Stats DB for Production. We're doing this to hopefully help the database reindexing.
This is a hotfix to master.
=> EES-5557 Hotfix: Revert decrease in number of provisioned vCores of Stats DB made for EES-5515

src/explore-education-statistics-admin/src/pages/release/data/ReleaseApiDataSetPreviewTokenPage.tsx, tests/robot-tests/tests/admin/bau/prerelease.robot, tests/robot-tests/tests/admin/bau/prerelease_and_amend.robot, tests/robot-tests/tests/libs/utilities.py, tests/robot-tests/tests/public_api/public_api_preview_token.robot
This PR:
- fixes issues around the effects of timezones when displaying expiry times of preview tokens.
- removes unnecessary timezone-wangling code in Robot tests, opting for simpler approach.
The React code that displays the expiry time is executed in the users' browsers and shows the time local to the browsers' timezones.  This has the effect of breaking tests in the pipeline where the Robot tests are run on a UTC runner, as the Robot tests were all geared towards asserting that the time was explicitly in the `Europe/London` timezone.
We are now explicitly deciding to show the expiry time in a user's local timezone, and so have additionally added the `(local time)` text to the expiry time as well to make this clear.  To ensure we're checking for the correct timezone for the user, we …
=> Ees 5526 fix timezone issues

tests/robot-tests/args_and_variables.py, tests/robot-tests/reports.py, tests/robot-tests/run_tests.py, tests/robot-tests/test_runners.py, tests/robot-tests/tests/libs/common.robot
This PR:
- fixes issues in the Robot run scripts whereby certain combinations Pabot vs Robot runner, `--rerun-failed-suites` and `-rerun-attempts` options were not working as expected.
- also fixes an issue whereby the `--processes` Pabot option was not being passed to the Pabot executor.
Now all combinations of these parameters work fine together as expected, plus there is additional error checking prior to starting a rerun attempt using `--rerun-failed-suites` that there was indeed a previous report generated from which failed suites can be gathered.
=> EES-5540 - additional changes to improve interoperability between --rerun-failed-suites and --rerun-attempts options

azure-pipelines-ui-tests.dfe.yml, tests/robot-tests/tests/admin/analyst/edit_and_approve_release_as_publication_approver.robot, tests/robot-tests/tests/admin/analyst/role_ui_permissions/release_and_publication_role_end_to_end_permissions.robot, tests/robot-tests/tests/admin/bau/adopt_methodology.robot, tests/robot-tests/tests/admin/bau/create_methodology_amendment.robot, tests/robot-tests/tests/admin/bau/prerelease.robot, tests/robot-tests/tests/admin/bau/prerelease_and_amend.robot, tests/robot-tests/tests/admin/bau/release_content.robot, tests/robot-tests/tests/admin_and_public/bau/prerelease_visibility.robot, tests/robot-tests/tests/admin_and_public/bau/publish_methodology.robot, tests/robot-tests/tests/admin_and_public_2/bau/publish_amend_and_cancel.robot, tests/robot-tests/tests/admin_and_public_2/bau/publish_release_and_amend.robot, tests/robot-tests/tests/admin_and_public_2/bau/publish_release_and_amend_2.robot, tests/robot-tests/tests/general_public/table_tool_exclusions_by_geographic_level.robot, tests/robot-tests/tests/libs/admin-common.robot, tests/robot-tests/tests/libs/common.robot, tests/robot-tests/tests/libs/dates_and_times.py, tests/robot-tests/tests/libs/utilities.py, tests/robot-tests/tests/public_api/public_api_preview_token.robot, tests/robot-tests/tests/public_api/public_api_restricted.robot, tests/robot-tests/tests/seed_data/seed_data_common.robot
The "Public Suite" tests are failing for an unrelated reason, because the back button in the table tool in the public site isn't doing what is expected. 
This PR:
- simplifies the datetime wrangling code that we use in the Robot tests, by offering more targeted keywords.
- moves the default timezone of dates and times that are used for checking dates and times shown in the browser to be Europe/London by default, as that is the default timezone that EES displays dates in.
- adds specific keywords for getting individual date portions e.g. day, month, month word, year.
- splits keywords into "get london" and "get local browser" keywords, depending on whether we expect them to be displayed in Europe/London time or in time that is local to the browser.
- removes the need to use datetimes in …
=> Ees 5526 part 2 - making date time handling code in Robot tests easier

src/explore-education-statistics-admin/src/components/editable/InvalidContentDetails.tsx, src/explore-education-statistics-admin/src/components/editable/__tests__/InvalidContentDetails.test.tsx, src/explore-education-statistics-admin/src/components/editable/utils/__tests__/getInvalidContent.test.tsx, src/explore-education-statistics-admin/src/components/editable/utils/getInvalidContent.ts
This PR updates the validation by removing the single-word rule, and updating the "click here" rule to instead check against a larger list of words which would be considered unacceptable from an accessibility standpoint.
=> EES-5502: Replace WYSIWYG link text validation with pre-defined list of banned words.

src/GovUk.Education.ExploreEducationStatistics.Common.Tests/Extensions/CloneExtensionsTests.cs, src/GovUk.Education.ExploreEducationStatistics.Common/Extensions/CloneExtensions.cs, src/GovUk.Education.ExploreEducationStatistics.Common/GovUk.Education.ExploreEducationStatistics.Common.csproj, src/GovUk.Education.ExploreEducationStatistics.Public.Data.Model.Tests/Fixtures/FilterMappingPlanGeneratorExtensions.cs, src/GovUk.Education.ExploreEducationStatistics.Public.Data.Model/DataSetVersionMapping.cs, src/GovUk.Education.ExploreEducationStatistics.Public.Data.Processor.Tests/Functions/ImportMetadataFunctionTests.cs, src/GovUk.Education.ExploreEducationStatistics.Public.Data.Processor.Tests/ProcessorTestData.cs, src/GovUk.Education.ExploreEducationStatistics.Public.Data.Processor/Repository/FilterMetaRepository.cs, src/GovUk.Education.ExploreEducationStatistics.Public.Data.Processor/Repository/IndicatorMetaRepository.cs
This PR fixes filters and indicators not re-using the public IDs of existing filters / indicators  when preparing new API data set versions. This was due to the `ImportMetadataFunction` code only really handling public ID mappings for filter options and location options.
As the public IDs were not being re-used, this was leading to the changelog reporting that _all_ filters and indicators were being deleted and re-added. By re-using the public IDs correctly, we now no longer see this.
We've importantly added a lot more tests for `ImportaMetadataFunction`, however, we still need to cover the other meta types more comprehensively. In the interest of time, this will be handled in a subsequent ticket - EES-5560.
- Added `CloneExtensions` for shallow / deep clone extension methods. This uses …
=> EES-5559 Fix filters and indicators not re-using public IDs for new versions

src/explore-education-statistics-common/src/modules/table-tool/components/PublicationForm.tsx
Fixes the link in the error message when you haven't selected a publication on the first step of the table tool (the id was overriding the expected one generated from the field name).
=> EES-5307 fix table tool publication error link

tests/robot-tests/args_and_variables.py, tests/robot-tests/reports.py, tests/robot-tests/run_tests.py, tests/robot-tests/scripts/create_snapshots.py, tests/robot-tests/test_runners.py, tests/robot-tests/tests/libs/fail_fast.py, tests/robot-tests/tests/libs/utilities.py
During some battles with text selector changes, I broke the Robot code a few times but noticed that misconfigured keywords and errors within our own keyword code didn't cause our tests to fail fast (nothing new, as the `run_on_failure` that we use to trigger failures only kicks in within SeleniumLibrary's own keywords as has always been the case). This would mean that some suites ultimately failed but didn't get recorded by our fail-fast mechanism.
They were however captured in output.xml and so I changed the code up to use this as the ultimate source of truth instead, should we accidentally introduce keyword changes that break them but don't get caught by our fail-fast mechanism.
Ultimately to fix the fail-fast issue we could do with setting `run_on_failure=None` to prevent Selenium-only …
=> EES-XXXX - amending run_tests.py to detect failed suites from output.xml

src/explore-education-statistics-common/src/modules/charts/components/MapBlock.tsx, src/explore-education-statistics-common/src/modules/charts/components/MapControls.tsx
Adds the chart title as visually hidden text to the map control dropdowns so that it is clear to screen reader users what the dropdowns refer to.
=> EES-5297 add visually hidden text to map control labels

src/explore-education-statistics-common/src/components/FigureFootnotes.tsx, src/explore-education-statistics-common/src/modules/table-tool/components/FixedMultiHeaderDataTable.tsx, src/explore-education-statistics-frontend/src/modules/permalink/PermalinkPage.tsx
Fixes a skipped heading level on permalink pages when footnotes are present - it was skipping from h1 to h3, now the footnotes heading is h2.
=> EES-5434 fix footnotes heading level on permalinks

src/explore-education-statistics-common/src/modules/charts/components/MapBlock.module.scss
Adds a border to map legend colours to make them more distinguishable for low vision users.
=> EES-5284 add border to map legend colours

src/GovUk.Education.ExploreEducationStatistics.Admin/Controllers/Api/UserManagement/PrereleaseUsersController.cs, src/GovUk.Education.ExploreEducationStatistics.Admin/Services/UserManagementService.cs, tests/robot-tests/tests/libs/admin_api.py
This PR fixes a UI test failure we were seeing due to an additional prerelease user being created on an environment alongside `ees-prerelease1` and `ees-prerelease2`.
Previously the tests passed as this would happen:
- `user_resets_user_roles_via_api_if_required` is called. This removes the global prerelease role for both ees-prerelease1 and ees-prerelease2. This means both users no longer appear in the list of prerelease users, but in the list of all other users.
- `_get_prerelease_user_details_via_api` is called. This results in `admin_client.get("/api/user-management/pre-release")` returning a 404 (as they are no other prerelease users) and so it throws an exception when `.json()` is called on the response.
- This 404 is caught and in the `except` block we go on to call …
=> EES-5565 Fix UI test failure due to existence of other prerelease users

src/GovUk.Education.ExploreEducationStatistics.Admin.Tests/Controllers/Api/Public.Data/DataSetVersionMappingControllerTests.cs, src/GovUk.Education.ExploreEducationStatistics.Public.Data.Processor.Tests/Functions/ProcessNextDataSetVersionMappingsFunctionTests.cs
This PR performs various cleanup across two test suites relating to `DataSetVersionMappings`.
This primarily does things like:
- Refactoring common test methods for assertion and getting things from the DB
- Renaming plural `mappings` variable to `mapping` singular
=> EES-5570 Cleanup various tests related to `DataSetVersionMappings`

src/GovUk.Education.ExploreEducationStatistics.Admin.Tests/Controllers/Api/Public.Data/DataSetVersionMappingControllerTests.cs, src/GovUk.Education.ExploreEducationStatistics.Admin/Services/Public.Data/DataSetVersionMappingService.cs, src/GovUk.Education.ExploreEducationStatistics.Public.Data.Model.Tests/Fixtures/DataSetVersionMappingGeneratorExtensions.cs, src/GovUk.Education.ExploreEducationStatistics.Public.Data.Model/DataSetVersionMapping.cs, src/GovUk.Education.ExploreEducationStatistics.Public.Data.Model/Migrations/20241013014815_EES5563_AddDeletedMetaFlagsToDataSetVersionMapping.Designer.cs, src/GovUk.Education.ExploreEducationStatistics.Public.Data.Model/Migrations/20241013014815_EES5563_AddDeletedMetaFlagsToDataSetVersionMapping.cs, src/GovUk.Education.ExploreEducationStatistics.Public.Data.Processor.Tests/Functions/ProcessNextDataSetVersionMappingsFunctionTests.cs, src/GovUk.Education.ExploreEducationStatistics.Public.Data.Processor/Model/DataSertVersionMappingMeta.cs, src/GovUk.Education.ExploreEducationStatistics.Public.Data.Processor/Models/DataSetVersionMappingMeta.cs, src/GovUk.Education.ExploreEducationStatistics.Public.Data.Processor/Repository/FilterMetaRepository.cs, src/GovUk.Education.ExploreEducationStatistics.Public.Data.Processor/Repository/GeographicLevelMetaRepository.cs, src/GovUk.Education.ExploreEducationStatistics.Public.Data.Processor/Repository/IndicatorMetaRepository.cs, src/GovUk.Education.ExploreEducationStatistics.Public.Data.Processor/Repository/Interfaces/IIndicatorMetaRepository.cs, src/GovUk.Education.ExploreEducationStatistics.Public.Data.Processor/Services/DataSetMetaService.cs, src/GovUk.Education.ExploreEducationStatistics.Public.Data.Processor/Services/DataSetVersionMappingService.cs, src/GovUk.Education.ExploreEducationStatistics.Public.Data.Processor/Services/Interfaces/IDataSetMetaService.cs
:warning: Depends on #5331
---
This PR primarily fixes deletions of indicator, geographic level and time periods previously not being considered by the data set's version number as a major update.
We have implemented this as new flag columns on `DataSetVersionMapping` in the form of:
- `HasDeletedIndicators`
- `HasDeletedGeographicLevels`
- `HasDeletedTimePeriods`
This is not necessarily an optimum way of implementing this as a better solution may be to structure this information in a similar to the mappings for filters and locations. Unfortunately, we're quite time constrained to get this working for private testing and have gone with this as a simpler solution for now.
In the future, we'll probably need to replace these columns if we want to implement things like indicator mappings.
- …
=> EES-5563 Fix not all meta deletions being considered as major version updates

src/GovUk.Education.ExploreEducationStatistics.Public.Data.Api.Tests/Controllers/DataSetVersionsControllerTests.cs, src/GovUk.Education.ExploreEducationStatistics.Public.Data.Api/Services/DataSetVersionChangeService.cs, src/GovUk.Education.ExploreEducationStatistics.Public.Data.Processor/Services/DataSetVersionChangeService.cs, src/explore-education-statistics-admin/src/pages/release/data/__tests__/ReleaseApiDataSetChangelogPage.test.tsx, src/explore-education-statistics-common/src/modules/data-catalogue/components/ChangeSection.tsx, src/explore-education-statistics-common/src/modules/data-catalogue/components/FilterChangeLabel.tsx, src/explore-education-statistics-common/src/modules/data-catalogue/components/IndicatorChangeLabel.tsx, src/explore-education-statistics-common/src/modules/data-catalogue/components/__tests__/ApiDataSetChangelog.test.tsx, src/explore-education-statistics-common/src/modules/data-catalogue/components/__tests__/ChangeSection.test.tsx, src/explore-education-statistics-common/src/services/types/apiDataSetMeta.ts, src/explore-education-statistics-frontend/src/modules/data-catalogue/__tests__/DataSetFilePage.test.tsx, src/explore-education-statistics-frontend/src/modules/data-catalogue/components/__tests__/DataSetFileApiChangelog.test.tsx
This PR:
- Removes frontend ordering of changelog entries. This is now deferred to the backend when the changelog is initially generated.
- Adds filter and indicator column names to changelog
- Fixes time periods being naturally ordered in the changelog
- Adds explicit ordering of geographic levels by label in changelog
- Adds missing service mock to `DataSetFilePage` tests which was previously causing console errors due to real HTTP requests being attempted
=> EES-5572 Various tweaks to changelog page

src/explore-education-statistics-admin/src/pages/bau/BauUsersPage.tsx, src/explore-education-statistics-admin/src/pages/bau/__tests__/BauUsersPage.test.tsx
This PR hides the delete user button we previously added to the BauUserPage.
We've done this as there is currently a bug with deleting a user due to the userId being references in many other table's CreatedById/UpdatedById/DeletedById/etc. columns.
We decided to just comment out the delete user button so that we could deploy current changes and give us more time to consider the best approach to solving this issue.
=> EES-5573 Hide delete user button

tests/robot-tests/tests/admin/analyst/manage_publication_as_publication_owner.robot, tests/robot-tests/tests/admin/bau/create_publication_and_release.robot, tests/robot-tests/tests/libs/admin-common.robot, tests/robot-tests/tests/libs/admin-utilities.py, tests/robot-tests/tests/public_api/public_api_preview_token.robot
This PR fixes UI tests following the merging in of Topic deletion.
This includes:
- fixing selectors for the Theme selection dropdown.
- using the `TEST_THEME_NAME` variable in Robot tests now that a new Theme is created for every run.
I did also take a stab at changing `user selects dashboard theme if possible` to `user selects dashboard theme` and just not trying to interact with a non-existent Theme dropdown if the user under test was an analyst (by creating new navigational keywords that didn't expect to use the Theme dropdown) but this would cause an explosion of changes!
=> EES-4491 - fixing UI tests after changes in navigation controls

tests/robot-tests/scripts/create_snapshots.py, tests/robot-tests/tests/snapshots/data_catalogue_snapshot.json, tests/robot-tests/tests/snapshots/find_statistics_snapshot.json
This PR fixes an issue where the snapshots for the table tool was returning no publications. This was fixed by updating a CSS selector.
I also fixed an issue where if a snapshot file didn't exist, the script would fail. I've changed it so now the script will generate a snapshot file if none exists.
I also updated the snapshots.
=> EES-5582 Fix snapshots script and update snapshots

src/explore-education-statistics-admin/src/components/editable/utils/__tests__/getInvalidContent.test.tsx, src/explore-education-statistics-admin/src/components/editable/utils/getInvalidContent.ts
Removing the requirement for the first heading of a text block to be a level `<h3>` header. 
It will still check for the logical header ordering, taking the first heading level found within the text block as the starting heading level - i.e. you can still not 'jump' header levels from say `<h3>` to `<h5>`.
=> EES-5571 Remove heading level accessibility check for first heading of a text block

src/GovUk.Education.ExploreEducationStatistics.Admin.Tests/Services/DataArchiveValidationServiceTests.cs, src/GovUk.Education.ExploreEducationStatistics.Admin.Tests/Services/FileUploadsValidatorServiceTests.cs, src/GovUk.Education.ExploreEducationStatistics.Admin/Models/ArchiveDataSetFile.cs, src/GovUk.Education.ExploreEducationStatistics.Admin/Services/DataArchiveValidationService.cs, src/GovUk.Education.ExploreEducationStatistics.Admin/Services/FileUploadsValidatorService.cs, src/GovUk.Education.ExploreEducationStatistics.Admin/Services/Interfaces/IFileUploadsValidatorService.cs, src/GovUk.Education.ExploreEducationStatistics.Admin/Services/ReleaseDataFileService.cs, src/GovUk.Education.ExploreEducationStatistics.Admin/Validators/ValidationMessages.cs, src/GovUk.Education.ExploreEducationStatistics.Content.Model/ReleaseFile.cs, src/explore-education-statistics-admin/src/pages/release/data/components/ReleaseDataUploadsSection.tsx
> PR raised on behalf of @mmyoungman in his absence
Currently, a bulk import will fail if one the data sets contained in the zip has the same title as an already-imported data set. These changes allow users to initiate a data replacement for those data sets that have the same title as an existing data set.
=> EES-5546: Allow bulk imports to start replacements

tests/robot-tests/tests/admin/analyst/invite_contributor_as_publication_owner.robot
This PR fixes UI test failures in `invite_contributor_as_publication_owner.robot` .
Analyst3 account was deleted while testing 'Delete Users' functionality.
It was added back with a new account, created in the Hive AD . This PR updates the email address in the UI tests.
=> EES-Analyst3-Email change

src/explore-education-statistics-admin/src/pages/release/datablocks/components/chart/ChartBoundaryLevelsConfiguration.tsx, src/explore-education-statistics-admin/src/pages/release/datablocks/components/chart/ChartBoundaryLevelsForm.tsx, src/explore-education-statistics-admin/src/pages/release/datablocks/components/chart/ChartBuilder.tsx, src/explore-education-statistics-admin/src/pages/release/datablocks/components/chart/ChartDataGroupingsConfiguration.tsx, src/explore-education-statistics-admin/src/pages/release/datablocks/components/chart/contexts/ChartBuilderFormsContext.tsx, src/explore-education-statistics-admin/src/pages/release/datablocks/components/chart/reducers/chartBuilderReducer.ts, src/explore-education-statistics-admin/src/pages/release/datablocks/components/chart/types/mapConfig.ts, src/explore-education-statistics-common/src/modules/charts/components/MapBlock.tsx, src/explore-education-statistics-common/src/modules/charts/components/MapGeoJSON.tsx, src/explore-education-statistics-common/src/modules/charts/components/utils/generateFeaturesAndDataGroups.ts, src/explore-education-statistics-common/src/modules/charts/util/__tests__/getMapDataSetCategoryConfigs.test.ts, src/explore-education-statistics-common/src/modules/charts/util/getDataSetCategoryConfigs.ts, src/explore-education-statistics-common/src/modules/charts/util/getMapDataSetCategoryConfigs.ts
- Hoists initialization of map `dataSetConfigs` into `chartBuilderReducer`
- Refactors form types for boundary level and data grouping tabs
- Fixes boundary level tab not showing invalid form errors for other tabs
- Refactors out new `getMapDataSetCategoryConfigs` function from `getDataSetCategoryConfigs`
- Check if map state needs to be initialised in `UPDATE_CHART_DEFINITION` when map config already exists i.e. `if (draft.definition.type === 'map' && !draft.map)`
- Stop legend tab firing `UPDATE_CHART_LEGEND` seemingly more than necessary
- If you change data sets (on 'Data sets' tab) after setting some data set boundary levels, you can end up with stale state in 'Boundary levels' tab where some options will still be selected:
1. Add data set
2. Change boundary levels for some of those …
=> EES-5541 Various fixes across boundary level and data groupings

src/explore-education-statistics-common/src/modules/data-catalogue/components/ApiDataSetQuickStart.tsx, src/explore-education-statistics-frontend/src/modules/data-catalogue/components/__tests__/DataSetFileApiQuickStart.test.tsx
This PR adds the URL for downloading a data set as CSV to the API guidance:
=> EES-5600 Add download data set CSV URL to API guidance

.github/workflows/validate-snapshots.yml
Quick one to shift the snapshots workflow back to UTC for winter. Just edited directly in GitHub as shouldn't affect anything else.
Reminder that went off
New reminder set for March to move to daylight savings time
=> Move snapshots back to UTC for winter

tests/robot-tests/tests/admin/analyst/invite_contributor_as_publication_owner.robot
This PR fixes few UI tests failures that were occurring in `tests/admin/analyst/invite_contributor_as_publication_owner.robot ` due 
to casing difference in the new email address for Analyst3.
=> EES-5611 Fix UI test failure in Admin

infrastructure/templates/public-api/components/wafPolicy.bicep
This PR disables an Azure Web Application Firewall (WAF) default rule set rule.
This change is being made after finding that Public API requests with certain `User-Agent` headers were being blocked with 403 Forbidden responses by the Azure Application Gateway.
Rule set group: `REQUEST-913-SCANNER-DETECTION`
Rule:  `913101 - 'Found User-Agent associated with scripting/generic HTTP client`
=> EES-5614 Disable Azure Web Application Firewall rule

infrastructure/templates/public-api/api-infrastructure-pipeline.yml
This PR:
- provides a way to force a deploy of the Public API pipeline to the Dev or Test environment from any branch.
A new radiofield will be available when manually running the Pipeline in DevOps - by default it will be "none" meaning that the environment selection will be base on the branch being run from, but alternatively this can be set to "dev" to deploy the pipeline from any branch to Dev, and the same for Test.
Note that "Resources" still need to be selected during a manual pipeline run so that the pipeline has some code to deploy.  We would go to Resources -> EESMainBuildPipeline -> and then search for "dev" in the search field to pull up the latest build pipeline artifacts with which to run the pipeline (if deploying to the Dev environment, that is).  This selects the ZIP …
=> EES-5241 - allow Public API deploys to occur into the Dev or Test env from any branch

infrastructure/templates/public-api/application/public-api/publicApiApp.bicep, infrastructure/templates/public-api/application/public-api/publicApiDocs.bicep, infrastructure/templates/public-api/application/shared/appGateway.bicep, infrastructure/templates/public-api/application/shared/virtualNetwork.bicep, infrastructure/templates/public-api/components/appGateway.bicep, infrastructure/templates/public-api/components/appGatewayPathRules.bicep, infrastructure/templates/public-api/components/containerApp.bicep, infrastructure/templates/public-api/components/containerAppEnvironment.bicep, infrastructure/templates/public-api/components/containerAppPrivateDns.bicep, infrastructure/templates/public-api/components/staticWebApp.bicep, infrastructure/templates/public-api/main.bicep, infrastructure/templates/public-api/types.bicep, src/GovUk.Education.ExploreEducationStatistics.Public.Data.Api/Program.cs, src/GovUk.Education.ExploreEducationStatistics.Public.Data.Api/Properties/launchSettings.json
This PR adds the public API docs app to the App Gateway via a `/docs` route.
To enable this, we've made significant modifications to the App Gateway to enable us to configure all the required parts i.e. path rules, rewrites and redirects.
We've also moved the private DNS zone (and records) out of the `appGateway` module and into the `containerApp` module. The private DNS configuration was previously necessary for Container Apps to make them accessible to the App Gateway without opening them to the public internet. However, a private DNS is not necessary (or possible) with a Static Web App, which is used for the public API docs, and did not fit the previous abstraction.
- Updated Swagger endpoints in public API to `/swagger` instead of `/docs` (which conflicts with the API docs app)
- …
=> EES-5617 Add public API docs to App Gateway via `/docs` route

src/explore-education-statistics-common/src/components/ContentHtml.tsx, src/explore-education-statistics-common/src/components/__tests__/ContentHtml.test.tsx
We currently add '(opens in new tab) 'to any external links added in the admin system. However this is also treating `mailto:` links as external, and while that is partially true, it’s not technically true, and is not an expected behaviour for users.
This PR prevents `mailto:` links from having the '(opens in new tab)' text appended to them inside the release content.
=> EES-5597 Ensuring that `mailto:` links DO NOT HAVE '(opens in new tab)' added to them

src/explore-education-statistics-admin/src/components/editable/utils/getInvalidContent.ts
This PR aligns badLinkTextWords with the new "this link" string added to the dfeshiny repository here: https://github.com/dfe-analytical-services/dfeshiny/pull/60
I've added the string to the end of the array, to keep it aligned it's associated string in the dfeshiny repo.
=> EES-5599 Add 'this link' to badLinkTextWords

infrastructure/templates/public-api/application/public-api/publicApiApp.bicep, infrastructure/templates/public-api/application/public-api/publicApiAppIdentity.bicep, infrastructure/templates/public-api/application/public-api/publicApiAppInsights.bicep, infrastructure/templates/public-api/application/public-api/publicApiDataProcessor.bicep, infrastructure/templates/public-api/application/public-api/publicApiDocs.bicep, infrastructure/templates/public-api/application/public-api/publicApiStorage.bicep, infrastructure/templates/public-api/application/shared/appGateway.bicep, infrastructure/templates/public-api/application/shared/containerAppEnvironment.bicep, infrastructure/templates/public-api/application/shared/coreStorage.bicep, infrastructure/templates/public-api/application/shared/logAnalyticsWorkspace.bicep, infrastructure/templates/public-api/application/shared/postgreSqlFlexibleServer.bicep, infrastructure/templates/public-api/application/shared/privateDnsZones.bicep, infrastructure/templates/public-api/application/shared/virtualNetwork.bicep, infrastructure/templates/public-api/components/appServiceSlotConfig.bicep, infrastructure/templates/public-api/components/containerApp.bicep, infrastructure/templates/public-api/components/containerRegistryRoleAssignment.bicep, infrastructure/templates/public-api/components/functionApp.bicep, infrastructure/templates/public-api/components/keyVaultRoleAssignment.bicep, infrastructure/templates/public-api/components/postgresqlDatabase.bicep, infrastructure/templates/public-api/components/privateDnsZone.bicep, infrastructure/templates/public-api/components/privateEndpoint.bicep, infrastructure/templates/public-api/components/staticWebApp.bicep, infrastructure/templates/public-api/components/storageAccount.bicep, infrastructure/templates/public-api/main.bicep, infrastructure/templates/public-api/types.bicep
This PR updates our custom Bicep type names to be PascalCased to avoid confusion with variables. This also removes the unnecessary '*Type' suffix we were previously adding as well.
=> EES-5617 Update custom Bicep type names to be PascalCased

README.md, src/GovUk.Education.ExploreEducationStatistics.Public.Data.Scripts/README.md, tests/performance-tests/README.md, tests/performance-tests/package.json, useful-scripts/start.ts
This PR removes any references to the deprecated / removed Docker Compose v1 commands in favour of the newer v2 commands across the project. This means that any `docker-compose` commands have been changed to `docker compose`.
This was mostly brought to my attention upon upgrading to Ubuntu 24.04 where it appears that Docker Compose v1 has been dropped completely (which broke the project `start` script for me). 
See [Compose v2 migration](https://docs.docker.com/compose/releases/migrate) for further reading.
=> Remove references to deprecated / removed Docker Compose v1 commands

infrastructure/parameters/dev.parameters.json, infrastructure/parameters/pre-prod.parameters.json, infrastructure/parameters/prod.parameters.json, infrastructure/parameters/test.parameters.json, infrastructure/templates/template.json, src/GovUk.Education.ExploreEducationStatistics.Admin.Tests/Controllers/Api/ConfigControllerTests.cs, src/GovUk.Education.ExploreEducationStatistics.Admin/appsettings.Development.json, src/explore-education-statistics-frontend/.env, src/explore-education-statistics-frontend/src/modules/data-catalogue/components/__tests__/DataSetFileUsage.test.tsx
This PR updates the public API docs URLs in the public frontend and admin to our App Gateway URLs - `https://*.statistics.api.education.gov.uk/docs`.
=> EES-5617 Update public API docs URLs in public frontend and admin

src/GovUk.Education.ExploreEducationStatistics.Admin/Migrations/ContentMigrations/20241112114310_EES5631_CreateReleaseRedirectsTable.Designer.cs, src/GovUk.Education.ExploreEducationStatistics.Admin/Migrations/ContentMigrations/20241112114310_EES5631_CreateReleaseRedirectsTable.cs, src/GovUk.Education.ExploreEducationStatistics.Content.Model/Database/ContentDbContext.cs, src/GovUk.Education.ExploreEducationStatistics.Content.Model/ReleaseRedirect.cs
This PR adds a `ReleaseRedirects` table to the Content DB.
With the introduction of a new `Label` concept in [EES-5626](https://dfedigital.atlassian.net/jira/software/c/projects/EES/boards/105?selectedIssue=EES-5626), and the ability to edit that `Label` in [EES-5637](https://dfedigital.atlassian.net/jira/software/c/projects/EES/boards/105?selectedIssue=EES-5637), we will now be introducing the ability to change the `Slug` for a Release, which necessitates the introduction of Release Redirects.
The `ReleaseRedirects` schema is as the following:
- `Slug` - the previous slug of the Release
- `ReleaseId` - a foreign key to the `Id` primary key of the `Releases` table. Used to redirect to the **new** `Slug`
- `Created` - timestamp of when this redirect was created
We follow the same pattern …
=> EES-5631 Adding `ReleaseRedirects` table to the Content DB

azure-pipelines-ui-tests.yml
Commented out all the Playwright tests from the yml file so that they do not run in pipelines.
These tests are not maintained anymore resulting in failures that reported as 'failed' on slack even though all other tests were passing.
=> EES-5657 Pause Playwright tests in azure-pipelines-ui-tests.yml

tests/robot-tests/tests/admin/bau/release_content.robot, tests/robot-tests/tests/libs/admin/manage-content-common.robot
Fixes UI test failures in `release_content.robot` and `create_methodology_amendment.robot` by tweaking the scrolling to make sure the elements are clickable. As noted on https://dfedigital.atlassian.net/browse/EES-5383 we should try to find a more robust solution to the flakiness of tests involving content accordions at some point.
=> EES-5672 5673 fix ui tests

infrastructure/templates/template.json, src/GovUk.Education.ExploreEducationStatistics.Admin/Services/Public.Data/PublicDataApiClient.cs, src/GovUk.Education.ExploreEducationStatistics.Public.Data.Api.Tests/Controllers/DataSetVersionsControllerTests.cs, src/GovUk.Education.ExploreEducationStatistics.Public.Data.Api.Tests/Controllers/DataSetsControllerGetQueryTests.cs, src/GovUk.Education.ExploreEducationStatistics.Public.Data.Api.Tests/Controllers/DataSetsControllerPostQueryTests.cs, src/GovUk.Education.ExploreEducationStatistics.Public.Data.Api.Tests/Controllers/DataSetsControllerTests.cs, src/GovUk.Education.ExploreEducationStatistics.Public.Data.Api.Tests/Controllers/PublicationsControllerTests.cs, src/GovUk.Education.ExploreEducationStatistics.Public.Data.Api.Tests/Swagger/VersionedPathsDocumentFilterTests.cs, src/GovUk.Education.ExploreEducationStatistics.Public.Data.Api/Controllers/DataSetVersionsController.cs, src/GovUk.Education.ExploreEducationStatistics.Public.Data.Api/Controllers/DataSetsController.cs, src/GovUk.Education.ExploreEducationStatistics.Public.Data.Api/Controllers/PublicationsController.cs, src/GovUk.Education.ExploreEducationStatistics.Public.Data.Api/Program.cs, src/GovUk.Education.ExploreEducationStatistics.Public.Data.Api/Swagger/SwaggerConfig.cs, src/GovUk.Education.ExploreEducationStatistics.Public.Data.Api/Swagger/VersionedPathsDocumentFilter.cs, src/explore-education-statistics-frontend/.env
This PR makes the following tweaks to the versioning in the public API:
- Removes minor versions as they are unnecessary. We only need to communicate major changes to API consumers.
- Removes `version` path parameters from the generated OpenAPI documents. This was previously quite confusing as it would not enumerate or constrain what version number you should use.
- Prefixes generated OpenAPI document version paths with `v` e.g. `/swagger/v1/openapi.json`
- Removes `/api` prefix from routes as it's redundant to declare it in the path due to the app already being an API
=> EES-5663 Tweaks to public API versioning

src/GovUk.Education.ExploreEducationStatistics.Admin/Migrations/ContentMigrations/20241122105739_EES5625_CopyReleaseVersionFieldsToRelease.sql
This PR fixes a bug in the releases migration query added as part of #5409. It excludes soft deleted release versions from being evaluated.
Prior to this change, there can be duplicate releases in the query due to each release potentially being matched on a soft deleted release version and a non-soft deleted release version, both with the same version number.
=> 🐛 EES-5625 Exclude soft deleted release versions in releases migration query

src/GovUk.Education.ExploreEducationStatistics.Admin.Tests/Services/Methodologies/MethodologyApprovalServiceTests.cs, src/GovUk.Education.ExploreEducationStatistics.Admin.Tests/Services/Methodologies/MethodologyServiceTests.cs, src/GovUk.Education.ExploreEducationStatistics.Admin.Tests/Services/PublicationServiceTests.cs, src/GovUk.Education.ExploreEducationStatistics.Content.Api.Tests/Controllers/RedirectsControllerTests.cs, src/GovUk.Education.ExploreEducationStatistics.Content.Model.Tests/Fixtures/MethodologyGeneratorExtensions.cs, src/GovUk.Education.ExploreEducationStatistics.Content.Model.Tests/Fixtures/MethodologyRedirectGeneratorExtensions.cs, src/GovUk.Education.ExploreEducationStatistics.Content.Model.Tests/Fixtures/MethodologyVersionGeneratorExtensions.cs, src/GovUk.Education.ExploreEducationStatistics.Content.Model.Tests/Fixtures/PublicationRedirectGeneratorExtensions.cs, src/GovUk.Education.ExploreEducationStatistics.Content.Model.Tests/Fixtures/ReleaseRedirectGeneratorExtensions.cs, src/GovUk.Education.ExploreEducationStatistics.Content.Services/RedirectsService.cs, src/GovUk.Education.ExploreEducationStatistics.Content.ViewModels/RedirectViewModels.cs
⚠️ This PR depends on https://github.com/dfe-analytical-services/explore-education-statistics/pull/5409 ⚠️ 
In this PR we add the release redirects to the `RedirectsViewModel`, to be returned in the Content API's `GET api/redirects` endpoint.
We also add some integration tests for the `api/redirects` endpoint - testing all types of redirects and the caching. No tests previously existed.
We have **TEMPORARILY** added a `Slug` field to the `Release` model as a necessity so that we can create the release redirect view models. This **IS** where the `Slug` field belongs, but is actually going to be introduced as part of [EES-5625](https://dfedigital.atlassian.net/jira/software/c/projects/EES/boards/105?selectedIssue=EES-5625). So, this PR **IS BLOCKED** by EES-5625, and the `Slug` has only …
=> EES 5632 - Return the Release redirects from the `api/redirects` endpoint

src/explore-education-statistics-admin/src/pages/release/datablocks/components/chart/__tests__/ChartBuilder.test.tsx
Interesting test failure was occurring in the pipeline but not locally: this should fix that
https://dfe-gov-uk.visualstudio.com/s101-Explore-Education-Statistics/_build/results?buildId=158310&view=logs&j=162a6ba4-ad57-5676-4ad4-d7205bec5953&t=93e8a875-14c6-5986-c630-7bcc873b903e&l=4568
Also fixed 2 typos
=> EES-5541 tiny test fixes

src/explore-education-statistics-admin/src/pages/release/data/ReleaseApiDataSetChangelogPage.tsx, src/explore-education-statistics-admin/src/pages/release/data/__tests__/ReleaseApiDataSetChangelogPage.test.tsx
This PR:
- adds error handling to Admin's data set changelog page.  Rather than failing to fetch the changelog results from the Public API and silently failing without showing any changes, instead we now show an warning message saying "Could not load changelog".  This is in keeping with the wording of other failure messages around the site e.g. `Could not load methodology`.
=> EES-5564 - added error handling when fetching data set details or changelog results

infrastructure/templates/template.json, src/GovUk.Education.ExploreEducationStatistics.Admin/Migrations/Custom/ICustomMigration.cs, src/GovUk.Education.ExploreEducationStatistics.Admin/Startup.cs, src/GovUk.Education.ExploreEducationStatistics.Common.Tests/Extensions/EnumerableExtensionsTests.cs, src/GovUk.Education.ExploreEducationStatistics.Common/Database/ICustomMigration.cs, src/GovUk.Education.ExploreEducationStatistics.Common/Extensions/EnumerableExtensions.cs, src/GovUk.Education.ExploreEducationStatistics.Public.Data.Api.Tests/Migrations/EES5660_MigrateDraftDataSetVersionFolderNamesTests.cs, src/GovUk.Education.ExploreEducationStatistics.Public.Data.Api/Migrations/EES5660_MigrateDraftDataSetVersionFolderNames.cs, src/GovUk.Education.ExploreEducationStatistics.Public.Data.Api/Startup.cs, src/GovUk.Education.ExploreEducationStatistics.Public.Data.Model.Tests/Fixtures/DataSetGeneratorExtensions.cs, src/GovUk.Education.ExploreEducationStatistics.Public.Data.Model.Tests/Fixtures/DataSetVersionGeneratorExtensions.cs, src/GovUk.Education.ExploreEducationStatistics.Public.Data.Model/DataSetVersionStatus.cs, src/GovUk.Education.ExploreEducationStatistics.Public.Data.Model/Extensions/DataSetVersionAuthExtensions.cs, src/GovUk.Education.ExploreEducationStatistics.Public.Data.Model/GovUk.Education.ExploreEducationStatistics.Public.Data.Model.csproj, src/GovUk.Education.ExploreEducationStatistics.Public.Data.Processor.Tests/Functions/ProcessCompletionOfNextDataSetVersionFunctionsTests.cs, src/GovUk.Education.ExploreEducationStatistics.Public.Data.Processor.Tests/Functions/ProcessCompletionOfNextDataSetVersionOrchestrationTests.cs, src/GovUk.Education.ExploreEducationStatistics.Public.Data.Processor/Functions/ActivityNames.cs, src/GovUk.Education.ExploreEducationStatistics.Public.Data.Processor/Functions/ProcessCompletionOfNextDataSetVersionFunctions.cs, src/GovUk.Education.ExploreEducationStatistics.Public.Data.Processor/Functions/ProcessCompletionOfNextDataSetVersionOrchestration.cs, src/GovUk.Education.ExploreEducationStatistics.Public.Data.Services.Tests/DataSetVersionPathResolverTests.cs, src/GovUk.Education.ExploreEducationStatistics.Public.Data.Services.Tests/TestDataSetVersionPathResolver.cs, src/GovUk.Education.ExploreEducationStatistics.Public.Data.Services/DataSetVersionPathResolver.cs, src/GovUk.Education.ExploreEducationStatistics.Public.Data.Services/Interfaces/IDataSetVersionPathResolver.cs, src/GovUk.Education.ExploreEducationStatistics.Publisher.Tests/Services/DataSetPublishingServiceTests.cs, src/GovUk.Education.ExploreEducationStatistics.Publisher.Tests/appsettings.IntegrationTest.json, src/GovUk.Education.ExploreEducationStatistics.Publisher/GovUk.Education.ExploreEducationStatistics.Publisher.csproj, src/GovUk.Education.ExploreEducationStatistics.Publisher/PublisherHostBuilderExtensions.cs, src/GovUk.Education.ExploreEducationStatistics.Publisher/Services/DataSetPublishingService.cs, src/GovUk.Education.ExploreEducationStatistics.Publisher/appsettings.json
This PR:
- fixes a bug around draft DataSetVersions whereby a draft (unpublished) DataSetVersion that was being deleted left its fileshare folder behind if its version changed to a major version, due to the delete code not expecting to look for a folder with a minor version name.
This is the second implementation to fix this issue, the first being an attempt whereby the delete code would attempt to look for both a minor AND major version-named folder and delete either if they exist, which felt untidy.
More importantly, it introduced complexity to an area of the codebase that has already generated 2 bugs, and the crux of the issue seemed to be that it was difficult to rely on a folder name that is version-based during a time where a DataSetVersion's version can fluctuate between minor and …
=> Ees 5660 replace versioned draft folder with static folder

styleguides/styleguide-frontend.md
This updates the FE style guide with a new section on avoiding loops and logic in unit tests.
Various tidy up has also been performed across the style guide.
=> Add section on loops and logic in tests to FE style guide

src/GovUk.Education.ExploreEducationStatistics.Admin.Tests/Services/UserManagementServicePermissionTests.cs, src/GovUk.Education.ExploreEducationStatistics.Admin.Tests/Services/UserManagementServiceTests.cs, src/GovUk.Education.ExploreEducationStatistics.Admin.Tests/Services/UserRoleServicePermissionTests.cs, src/GovUk.Education.ExploreEducationStatistics.Admin.Tests/Services/UserRoleServiceTests.cs, src/GovUk.Education.ExploreEducationStatistics.Admin/Controllers/Api/UserManagement/UserManagementController.cs, src/GovUk.Education.ExploreEducationStatistics.Admin/Services/Interfaces/IUserRoleService.cs, src/GovUk.Education.ExploreEducationStatistics.Admin/Services/UserManagementService.cs, src/GovUk.Education.ExploreEducationStatistics.Admin/Services/UserRoleService.cs, src/GovUk.Education.ExploreEducationStatistics.Content.Model.Tests/Repository/ReleaseVersionRepositoryTests.cs, src/GovUk.Education.ExploreEducationStatistics.Content.Model/Repository/Interfaces/IReleaseVersionRepository.cs, src/GovUk.Education.ExploreEducationStatistics.Content.Model/Repository/ReleaseVersionRepository.cs
This PR simplifies two of Admin's BAU User Management screens for inviting users and managing user release access which both use a call to `UserManagementService.ListReleases` to list all releases in a dropdown using labels with the format `<publication title - release title>`.
This has been relying on the table of all release versions to produce a list of all the releases in all publications using the titles of the latest release versions in every release.
Since #5409, this can be simplified to use the table of all releases to do the same thing which means we no longer need to evaluate the latest release version for every release to produce the list.
With this change we can now remove the method `IReleaseVersionRepository.ListLatestReleaseVersions(CancellationToken cancellationToken)` …
=> EES-5656 Remove `IReleaseVersionRepository.ListLatestReleaseVersions`

src/GovUk.Education.ExploreEducationStatistics.Common/Model/Chart/ChartAxisConfiguration.cs, src/explore-education-statistics-admin/src/pages/release/datablocks/components/chart/ChartAxisConfiguration.tsx, src/explore-education-statistics-admin/src/pages/release/datablocks/components/chart/__tests__/ChartAxisConfiguration.test.tsx, src/explore-education-statistics-common/src/modules/charts/components/HorizontalBarBlock.tsx, src/explore-education-statistics-common/src/modules/charts/components/LineChartBlock.tsx, src/explore-education-statistics-common/src/modules/charts/components/VerticalBarBlock.tsx, src/explore-education-statistics-common/src/modules/charts/types/chart.ts, src/explore-education-statistics-common/src/modules/charts/util/getMinorAxisDecimalPlaces.ts
> Retarget of [Amy B's PR](https://github.com/dfe-analytical-services/explore-education-statistics/pull/5431)
Adds a field to the chart minor axis configuration to set the number of decimal places that show on the axis.
I've not been able to run the UI tests because of issues with my local setup, but I don't think it'll cause problem
=> EES-5717 set number of decimal places on chart minor axis

infrastructure/templates/template.json
This PR:
- fixes a problem that was causing Inf Releases to complete.
We had some "[variables]" within a `dependsOn` block, which is only expecting to have resource or module names defined.  These are now removed.
=> EES-XXXX - fixed misplaced variable definitions in "dependsOn" array

infrastructure/templates/template.json
This PR enables `WEBSITE_CONTENTOVERVNET` for the Publisher App, without which it can successfully mount but not see or use the mounted Public API File Share.
Note that although this setting is stated as being a legacy setting that has been replaced by `vnetContentShareEnabled`, this setting doesn't work for the Publisher and the so the legacy setting is being used.
=> EES-5724 - enabling content-over-vnet for Publisher Function App

src/explore-education-statistics-admin/src/pages/publication/PublicationReleaseSeriesPage.tsx, src/explore-education-statistics-admin/src/pages/publication/__tests__/PublicationCreateReleaseSeriesLegacyLinkPage.test.tsx, src/explore-education-statistics-admin/src/pages/publication/__tests__/PublicationEditReleaseSeriesLegacyLinkPage.test.tsx, src/explore-education-statistics-admin/src/pages/publication/__tests__/PublicationPageContainer.test.tsx, src/explore-education-statistics-admin/src/pages/publication/__tests__/PublicationReleaseSeriesPage.test.tsx, src/explore-education-statistics-admin/src/pages/publication/components/__tests__/ReleaseSeriesTable.test.tsx, src/explore-education-statistics-admin/src/routes/publicationRoutes.ts, tests/robot-tests/tests/admin/analyst/analyst_absence_permissions.robot, tests/robot-tests/tests/admin/analyst/role_ui_permissions/publication_approver_ui_permissions.robot, tests/robot-tests/tests/admin/analyst/role_ui_permissions/publication_owner_ui_permissions.robot, tests/robot-tests/tests/admin/analyst/role_ui_permissions/release_approver_ui_permissions.robot, tests/robot-tests/tests/admin/analyst/role_ui_permissions/release_contributor_ui_permissions.robot, tests/robot-tests/tests/admin/analyst/role_ui_permissions/release_viewer_ui_permissions.robot, tests/robot-tests/tests/admin_and_public/bau/release_reordering.robot, tests/robot-tests/tests/seed_data/generate_seed_data_theme_1.robot
This PR renames the Admin 'Legacy releases' page to 'Release order'.
This is being done to make it more obvious that this page allows reordering releases which will become more commonly required when 'Release labelling' is made available by EES-5626.
When release labelling is introduced, we will allow a publication to contain multiple releases with the same year and time identifier.
Our traditional way of ordering releases within a publication in reverse chronological order by year and then by time period will no longer work after we lose this time period uniqueness. There will be no secondary sorting by label and analysts will decide which release should appear first or last.
The same possibility applies to the 'latest' release for a publication which is currently determined …
=> EES-5656 Rename Admin 'Legacy releases' to 'Release order'

src/GovUk.Education.ExploreEducationStatistics.Admin.Tests/Services/PublicationServicePermissionTests.cs, src/GovUk.Education.ExploreEducationStatistics.Admin.Tests/Services/PublicationServiceTests.cs, src/GovUk.Education.ExploreEducationStatistics.Admin/Requests/ReleaseSeriesItemRequests.cs, src/GovUk.Education.ExploreEducationStatistics.Admin/Services/ManageContent/ManageContentPageService.cs, src/GovUk.Education.ExploreEducationStatistics.Admin/Services/PublicationService.cs, src/GovUk.Education.ExploreEducationStatistics.Admin/Services/ReleaseService.cs, src/GovUk.Education.ExploreEducationStatistics.Admin/ViewModels/ReleaseSeriesTableEntryViewModel.cs, src/GovUk.Education.ExploreEducationStatistics.Common/ViewModels/ReleaseSeriesItemViewModel.cs, src/GovUk.Education.ExploreEducationStatistics.Content.Model/ReleaseSeriesItem.cs, src/GovUk.Education.ExploreEducationStatistics.Content.Services.Tests/Cache/PublicationCacheServiceTests.cs, src/GovUk.Education.ExploreEducationStatistics.Content.Services.Tests/PublicationServiceTests.cs, src/GovUk.Education.ExploreEducationStatistics.Content.Services/PublicationService.cs, src/explore-education-statistics-admin/src/pages/publication/PublicationEditReleaseSeriesLegacyLinkPage.tsx, src/explore-education-statistics-admin/src/pages/publication/__tests__/PublicationEditReleaseSeriesLegacyLinkPage.test.tsx, src/explore-education-statistics-admin/src/pages/release/content/components/ReleaseContent.tsx, src/explore-education-statistics-admin/src/prototypes/page-view/PrototypeReleaseContent.tsx, src/explore-education-statistics-admin/src/services/publicationService.ts, src/explore-education-statistics-admin/test/generators/releaseContentGenerators.ts, src/explore-education-statistics-common/src/services/publicationService.ts, src/explore-education-statistics-frontend/src/modules/find-statistics/PublicationReleasePage.tsx, src/explore-education-statistics-frontend/src/modules/find-statistics/__tests__/__data__/testReleaseData.ts
This PR contains mainly backend changes, separating out a few bits of tidy up ahead of the main changes in EES-5656.
There are two main changes amongst some other smaller improvements.
1. I attempted to remove `Id` from `ReleaseSeriesItem`, thinking that in cases where a publication has no legacy releases it would be nice if the `ReleaseSeries` field only contained an array of release id's. I backtracked on removing it entirely when I realised it's needed to be able to safely select the chosen legacy release from the release series array in the Admin UI when choosing to 'Edit' a legacy link. I've left in a lot of the changes where it doesn't need to be present though. For example, it's removed from `ReleaseSeriesItemViewModel` so it's no longer exposed to the public frontend. It's also …
=> EES-5656 Release series tidy up

tests/robot-tests/tests/general_public/table_tool_absence_by_characteristic.robot
Updated UI tests to look for an extra column header that got revealed in table creation in table_tool_absence_by_characteristic.robot due to new changes in 
https://dfedigital.atlassian.net/browse/EES-5149
=> EES-5730 Fix UI test failure in general_public suite

infrastructure/templates/logic-app-template.json, infrastructure/templates/template.json
This PR adds additional useful contextual information to alerts coming through to Slack from Azure Monitor.  This is achieved by amending the Logic App to post additional details of the alert to Slack. 
Once the alerts were drab, lifeless and unhappy:
But now, they spring with colour, details and joy!
Because getting alert details from several layers deep in the alert metric JSON body is very verbose in the Logic App, we now capture a few useful variables ahead of time before creating the Slack message.
We then include:
- colour-coding based on the severity of the alert if it is firing (red for critical and error, yellow for warning, and green for informational and verbose).
- colour-coding based on resolved alerts (green) 
- a detailed message about the condition that caused the alert …
=> EES-5685 - added many additional details to alerts being sent through to Slack

src/explore-education-statistics-admin/src/pages/release/data/components/ReleaseDataUploadsSection.tsx
`data_reordering.robot` is currently failing when it tries to go back to the 'Data and Files' tab after replacing the data files.
It errors because a request to the data file permissions endpoint fails because it uses the previous file id (from before the data was replaced). I can't replicate this manually at all so my guess is it's related to the speed of the UI tests.
This adds a check to `handleStatusChange` to check that the file still exists before calling the permissions service.
There might well be a better way to fix this. I initially tried adding a short `sleep` before clicking the 'Data and Files' tab but it didn't help.
=> EES-5732 prevent ui test failures after data replacement

src/explore-education-statistics-admin/src/pages/release/data/components/DataFileUploadForm.tsx
Attempting to replace a data set which has been created via the public API returns a 400 error, but currently only shows a generic error message to the user, but there is a more useful error message returned from the backend. This PR adds the missing error mapping to ensure users see the useful server response.
=> EES-5735: Add frontend error mapping for API data set replacement.

src/GovUk.Education.ExploreEducationStatistics.Common/Model/Chart/ChartDataSetConfig.cs
previous implementation was causing all chart dataset configs without boundaryLevel to be given boundaryLevel of 0 - unset boundaryLevels no remain unset
=> EES-5543 bugfix: dataSetConfig BoundaryLevels, no longer defaulted to 0

src/explore-education-statistics-frontend/src/middleware/pages/__tests__/redirectPages.test.ts, src/explore-education-statistics-frontend/src/middleware/pages/redirectPages.ts, src/explore-education-statistics-frontend/src/services/redirectService.ts
⚠️ This PR depends on some more BE changes we need to make on top of those in https://github.com/dfe-analytical-services/explore-education-statistics/pull/5391. The new changes will be made in another PR under [EES-5632](https://dfedigital.atlassian.net/jira/software/c/projects/EES/boards/105?selectedIssue=EES-5632). Please see https://github.com/dfe-analytical-services/explore-education-statistics/pull/5446 to see those BE changes. [THIS PR IS BLOCKED BY [#5446](https://github.com/dfe-analytical-services/explore-education-statistics/pull/5446) ]⚠️ 
This PR consists of the frontend changes necessary to allow **Release** redirects to work.
Previously, we only had the ability to be able to redirect the user when we detected an old **methodology/publication** slug in the URL. But now, with …
=> EES 5633 - FE - Redirect the user to the latest version of a page if using an old Release slug in the URL

src/explore-education-statistics-admin/src/components/editable/EditableContentForm.tsx, src/explore-education-statistics-admin/src/components/form/FormFieldEditor.tsx
Fixes a bug where it was possible to save inaccessible content in release content by switching to the preview view and back.
The custom accessibility validation relies on `elements` from the CKEditor content being available, it's set `onChange` but this isn't triggered when the form is reinitialised after switching back from preview mode. I've updated the form to `setElements` on `onElementsReady` as well which is triggered on reinitialisaiton.
=> EES-5580 validate EditableContentForm on submit after reinitialisation

infrastructure/templates/public-api/application/public-api/publicApiApp.bicep, infrastructure/templates/public-api/application/shared/containerAppEnvironment.bicep, infrastructure/templates/public-api/ci/azure-pipelines.yml, infrastructure/templates/public-api/ci/jobs/deploy-api-docs.yml, infrastructure/templates/public-api/ci/jobs/deploy-infrastructure.yml, infrastructure/templates/public-api/ci/tasks/deploy-bicep.yml, infrastructure/templates/public-api/components/containerApp.bicep, infrastructure/templates/public-api/components/containerAppEnvironment.bicep, infrastructure/templates/public-api/main.bicep, infrastructure/templates/public-api/parameters/main-dev.bicepparam, infrastructure/templates/public-api/types.bicep
This PR:
- adds in the ability to specify different workload profiles and container limits per environment for the Public API Container App Environment and Container App.
=> Ees xxxx add per environment scaling and workload profiles

src/explore-education-statistics-frontend/src/modules/data-catalogue/DataCataloguePage.tsx
This PR fixes an issue where on the Data Catalogue page, when selecting a geographic level filter in mobile view, the geographic level wouldn't be updated. This was because we're not passing it to the component when using the mobile view.
=> EES-5598 Fix changing geog lvl on mobile

src/GovUk.Education.ExploreEducationStatistics.Admin/Requests/DataBlockRequests.cs, src/explore-education-statistics-admin/src/pages/release/datablocks/components/DataBlockDetailsForm.tsx
This PR updates the data block table title character limit to 220.
=> EES-5758 Update data block table title limit to 220 chars

infrastructure/parameters/test.parameters.json, infrastructure/templates/template.json
This PR fixes an issue where on the "test" branch, we were still pulling the Data Factory ARM template from "dev".
To fix this, we simply add a new "test" options to the "branch" ARM template variable and use that on the test branch.
On an aside, this is due to the way we pull the Data Factory ARM template - fetching the ARM template from Github was necessary at the time we did it, but it's possible this could be cleaned up now.
=> EES-5757 Add ARM template branch variable option "test"

src/GovUk.Education.ExploreEducationStatistics.Admin/Controllers/Api/DataSetFileMetaMigrationController.cs, src/GovUk.Education.ExploreEducationStatistics.Admin/Migrations/ContentMigrations/20241230161603_EES5756_AddFilesColumnForMigration.Designer.cs, src/GovUk.Education.ExploreEducationStatistics.Admin/Migrations/ContentMigrations/20241230161603_EES5756_AddFilesColumnForMigration.cs, src/GovUk.Education.ExploreEducationStatistics.Content.Api.Tests/Controllers/DataSetFilesControllerTests.cs, src/GovUk.Education.ExploreEducationStatistics.Content.Model.Tests/Fixtures/DataSetFileMetaGeneratorExtensions.cs, src/GovUk.Education.ExploreEducationStatistics.Content.Model/DataSetFileMeta.cs, src/GovUk.Education.ExploreEducationStatistics.Content.Model/File.cs, src/GovUk.Education.ExploreEducationStatistics.Content.Services/DataSetFileService.cs, src/GovUk.Education.ExploreEducationStatistics.Data.Processor.Tests/Functions/ProcessorStage3Tests.cs, src/GovUk.Education.ExploreEducationStatistics.Data.Processor.Tests/Services/DataImportServiceTests.cs, src/GovUk.Education.ExploreEducationStatistics.Data.Processor/Services/DataImportService.cs
This PR sets DataSetFileMeta geographic levels to null. We do this because the same geographic levels are now cached in the new `DataSetFileVersionGeographicLevels` table.
This PR also makes changes to use the new `DataSetFileVersionGeographicLevels` table entries over `DataSetFileMeta.GeographicLevels`.
We set the geog lvls in JSON to null using a migration endpoint. There is no rush on using the endpoint after deploying. 
Unfortunately, we also needed a new temporary column in the Files table to record what entries have been migrated. This will be removed along with `DataSetFileMeta.GeographicLevels` in EES-5750.
=> EES-5756 Set DataSetFileMeta geographic levels to null

.config/dotnet-tools.json, azure-pipelines-main.yml, ci/scripts/public-api-openapi-diff.sh, infrastructure/templates/public-api/application/public-api/publicApiApp.bicep, infrastructure/templates/public-api/ci/jobs/deploy-api-docs.yml, infrastructure/templates/public-api/main.bicep, infrastructure/templates/public-api/parameters/main-dev.bicepparam, src/GovUk.Education.ExploreEducationStatistics.Public.Data.Api/GovUk.Education.ExploreEducationStatistics.Public.Data.Api.csproj, src/GovUk.Education.ExploreEducationStatistics.Public.Data.Api/Options/AppOptions.cs, src/GovUk.Education.ExploreEducationStatistics.Public.Data.Api/Program.cs, src/GovUk.Education.ExploreEducationStatistics.Public.Data.Api/Startup.cs, src/GovUk.Education.ExploreEducationStatistics.Public.Data.Api/appsettings.Development.json, src/explore-education-statistics-api-docs/.gitignore, src/explore-education-statistics-api-docs/config.rb, src/explore-education-statistics-api-docs/lib/utils/env.rb, src/explore-education-statistics-api-docs/source/openapi-v1.json
This PR adds a syncing mechanism to ensure that OpenAPI changes in the public API are documented in the API docs.
To enable this:
1. The public API now generates its OpenAPI documents at build time using the Swashbuckle CLI.
2. We use [oasdiff](https://github.com/Tufin/oasdiff) to diff between the OpenAPI documents used by the API docs and those generated by the public API.
3. If there are any changes in the diff, we fail the build pipeline as this means there are **undocumented** changes.
4. To resolve any undocumented changes, developers need to copy over any changes from the public API to the relevant OpenAPI document in the API docs.
Once this diff has been resolved, the build can pass and deployment can proceed.
The API docs deployment has now been adjusted so that they are built …
=> EES-5396 Sync public API OpenAPI changes with API docs

src/explore-education-statistics-admin/src/components/NavLink.tsx
This PR fixes a bug on the Release order page after #5442 which renamed the Admin's 'Legacy releases' page to 'Release order'.
The 'Release order' page was updated to use the route `/publication/:publicationId/releases/order` instead of `/publication/:publicationId/legacy` by that change.
However this meant the React router's nav link for the 'Releases' page on route `/publication/:publicationId/releases` also had the active style applied while on the 'Release order' page since it's matching on the first part of the location.
This PR adds `exact` to `RouterNavLinmk` in `NavLink` so that the active class/style is only be applied if the location is matched exactly.
**Before:**
**After:**
I checked to make sure I couldn't see any problems where `NavLink` is used but if any arise we could …
=> 🐛 EES-5656 Only apply active class for navigation links if the location is matched exactly

infrastructure/templates/public-api/ci/jobs/deploy-api-docs.yml, infrastructure/templates/public-api/main.bicep, src/explore-education-statistics-api-docs/source/404.html.md.erb, src/explore-education-statistics-api-docs/staticwebapp.config.json, src/explore-education-statistics-common/src/modules/data-catalogue/components/ApiDataSetQuickStart.tsx
:warning: Depends on #5445 :warning: 
---
This PR fixes the links to the public API docs on the API quick start guide of each API data set (in the public frontend).
The previously broken links also helped make it apparent that we:
- Aren't handling 404s and allow the generic Azure 404 page to render
- Dobn't redirect to paths with trailing slashes (which causes broken assets and relative links)
We've now addressed both of these issues by:
- Adding a custom 404 page which we've configured through `staticwebapp.config.json`
- Adding an automatic trailing slash redirection, also through `staticwebapp.config.json`
=> EES-5662 Fix public API docs URLs on API quick start guide

src/explore-education-statistics-admin/src/pages/release/data/ReleaseApiDataSetFiltersMappingPage.tsx, src/explore-education-statistics-admin/src/pages/release/data/ReleaseApiDataSetLocationsMappingPage.tsx, src/explore-education-statistics-admin/src/pages/release/data/__tests__/ReleaseApiDataSetFiltersMappingPage.test.tsx, src/explore-education-statistics-admin/src/pages/release/data/__tests__/ReleaseApiDataSetLocationsMappingPage.test.tsx, src/explore-education-statistics-admin/src/pages/release/data/components/ApiDataSetAutoMappedTable.tsx, src/explore-education-statistics-admin/src/pages/release/data/components/ApiDataSetMappableTable.tsx, src/explore-education-statistics-admin/src/pages/release/data/utils/__tests__/getUnmappedFilterErrors.test.ts, src/explore-education-statistics-admin/src/pages/release/data/utils/getUnmappedFilterErrors.ts, src/explore-education-statistics-admin/src/pages/release/data/utils/getUnmappedLocationErrors.ts, src/explore-education-statistics-admin/src/pages/release/data/utils/mappingTableIds.ts, tests/robot-tests/tests/public_api/public_api_minor_manual_changes.robot
This PR fixes inconsistent anchor IDs being used across the the public API filters and locations mapping pages. Previously, we were using hard-coded ID strings meaning that it was easy to forget to update them in all places. This would then lead to broken navigation links due to stale IDs being used.
We've not refactored both the filters and locations mappings pages to use common variables and functions to generate the necessary anchor IDs. This should hopefully keep things consistent and less bug-prone moving forward.
=> EES-5496 Fix inconsistent anchor IDs causing broken nav links in API data set mapping pages

src/explore-education-statistics-admin/src/pages/bau/BauDashboardPage.tsx, src/explore-education-statistics-admin/src/pages/bau/GlossaryPage.module.scss, src/explore-education-statistics-admin/src/pages/bau/GlossaryPage.tsx, src/explore-education-statistics-admin/src/routes/administrationRoutes.ts, src/explore-education-statistics-admin/src/services/glossaryService.ts
This PR adds a page to the "Platform administration" section to handle managing the Glossary. The only element available at the moment is a button which calls an existing endpoint to clear the cache, which may seem overkill, however since there are plans to add editing features as part of EES-280 it made sense to create the new page in preparation.
=> EES-5755: Add simple BAU glossary management page with button for clearing cache

src/GovUk.Education.ExploreEducationStatistics.Admin/Requests/DataBlockRequests.cs, src/explore-education-statistics-admin/src/pages/release/datablocks/components/chart/ChartConfiguration.tsx
This PR adds character limit validation and dynamic character counts to data block chart titles and alt text. This is to help ensure data is presented in a concise format, and maintain standards and consistency across the service.
=> EES-5731: Add character limit validation to data block chart title and alt text.

src/GovUk.Education.ExploreEducationStatistics.Admin.Tests/Controllers/Api/ReleasesControllerTests.cs, src/GovUk.Education.ExploreEducationStatistics.Admin.Tests/Fixture/TestApplicationFactory.cs, src/GovUk.Education.ExploreEducationStatistics.Admin.Tests/Services/ReleaseServicePermissionTests.cs, src/GovUk.Education.ExploreEducationStatistics.Admin/Requests/ReleaseRequests.cs, src/GovUk.Education.ExploreEducationStatistics.Admin/Services/ReleaseService.cs, src/GovUk.Education.ExploreEducationStatistics.Admin/Validators/ValidationErrorMessages.cs, src/GovUk.Education.ExploreEducationStatistics.Common.Tests/Fixtures/TestApplicationFactory.cs, src/GovUk.Education.ExploreEducationStatistics.Content.Model/NamingUtils.cs
As part of [EES-5351 - Release Labelling](https://dfedigital.atlassian.net/jira/software/c/projects/EES/boards/105?selectedIssue=EES-5351), we want to give the user the ability to give any Release a `Label`. This `Label` will be used to distinguish the Release from another Release with the same year and time period.
This PR is the back-end work for the associated [EES-5626](https://dfedigital.atlassian.net/jira/software/c/projects/EES/boards/105?selectedIssue=EES-5626) ticket, whereby we are adding the functionality to add and edit this `Label` for any **NEW** Release. Adding the ability to add/edit this `Label` for existing Releases will come later in another ticket; namely, [EES-5637](https://dfedigital.atlassian.net/jira/software/c/projects/EES/boards/105?selectedIssue=EES-5637).
- …
=> EES-5628 - Adding the ability to add an optional `Label` when creating a new Release (BE part)

src/GovUk.Education.ExploreEducationStatistics.Content.Api.Tests/Controllers/DataSetFilesControllerTests.cs, src/GovUk.Education.ExploreEducationStatistics.Content.Model.Tests/Fixtures/DataSetFileMetaGeneratorExtensions.cs, src/GovUk.Education.ExploreEducationStatistics.Content.Services/DataSetFileService.cs, src/GovUk.Education.ExploreEducationStatistics.Content.ViewModels/DataSetFileMetaViewModel.cs
This PR solves an issue where the updated ListDataSetFiles query wouldn't work when you include a `searchTerm`.
We believe this occurs because fetching DataSetFileGeographicLevels returns multiple results per data set, and so when this is joined with the free text rank table, there are multiple rows for each data set and that leads to issues. This is why HavingGeographicLevel didn't cause an issue, because even though it joins to DataSetFileGeographicLevels, the `Any` means it doesn't return multiple rows.
Credit goes to Ben for the sleuthing.
The solution we've decided on is to fetch the geographic levels in a separate query afterwards. 
We could consider simplifying the ListDataSetFiles in the future by having one query to identify which data sets to return - i.e. could just return ids …
=> EES-5763 Fetch geog lvls separately so LINQ can translate query

src/explore-education-statistics-common/src/modules/table-tool/components/DownloadTable.tsx
Updates the legend on the table download form to make it more descriptive, as per the DAC recommendation.
=> EES-5298 improve download file legend text

src/explore-education-statistics-common/src/modules/table-tool/components/TableHeadersForm.tsx
Updates the screen reader instructions for reordering table headers to make them more useful. Also adds reference to the 'move' buttons in the general instructions.
=> EES-5215 updated screen reader instructions for table header reordering

src/GovUk.Education.ExploreEducationStatistics.Admin/Services/DataBlockService.cs
This PR removes associated geo json cache files (controlled by `LocationsForDataBlockCacheKey`) after a data block is updated.
This is to prevent a bug where if someone caches geo json for a data set that has two locations with the same name, and then update the data block to include both locations of the same name, the user won't be able to look at the data block chart without getting a Sorry page. This would continue until the cache file had been removed. See EES-5704 for details.
This hasn't solved the issue entirely - if you update a data block the Content page may still lead to a Sorry page, but refreshing the page will fix this. This has been deemed acceptable for now.
=> EES-5707 Remove geojson cache file after updating data block with map

src/explore-education-statistics-common/src/modules/table-tool/components/FixedMultiHeaderDataTable.module.scss, src/explore-education-statistics-common/src/modules/table-tool/components/TableHeadersGroup.module.scss
Fixes two issues raised by DAC related to focus styles, for both I've made the focus style the same as when text inputs are focused.
EES-5285: table header groups when reordering
EES-5294: data block tables in releases
=> EES-5285 5294 focus styles for tables and table header groups

src/GovUk.Education.ExploreEducationStatistics.Content.Model/Release.cs
This PR changes the calculated `Title` property of `Release` to contain `Label` if it has been set.
Label is now settable but only in the back end create/update requests after https://github.com/dfe-analytical-services/explore-education-statistics/pull/5457.
The front-end work to allow setting a label is being added by EES-5629.
Further work in EES-5635 (to follow) will switch all remaining back-end view models from using `ReleaseVersion.Title` to `Release.Title` as it is currently only used in a limited number of places.
=> EES-5635 Change the calculated `Title` property of `Release` to contain `Label`

src/GovUk.Education.ExploreEducationStatistics.Admin/Requests/DataBlockRequests.cs
This fixes a bug introduced in EES-5731. A chart couldn't be created because the backend validation didn't allow a null chart title.
When creating a chart, the chart title is only provided in the request if the user is providing an alternative chart title. Otherwise, the chart title is generated by the backend (I believe).
=> EES-5787 Allow request Chart.Title to be null

src/explore-education-statistics-common/src/modules/table-tool/components/TableHeadersReorderableItem.tsx, src/explore-education-statistics-common/src/utils/__tests__/reorderMultiple.test.ts, src/explore-education-statistics-common/src/utils/reorderMultiple.ts
Fixes the styling when reordering table headers to make it obvious which items you've selected when moving multiple items.
Also fixes a bug where moving multiple items was sometimes moving them to the wrong place.
=> EES-5458 fix table headers multi select

tests/robot-tests/tests/admin/bau/create_publication_and_release.robot, tests/robot-tests/tests/admin_and_public_2/bau/publish_amend_and_cancel.robot, tests/robot-tests/tests/admin_and_public_2/bau/publish_release_and_amend.robot
This PR fixes the UI test failure on 'Release summary' page in Admin. 
It also fixes a flaky UI test failure at the testcase `Add data block to first accordion section` in 'admin_and_public_2' suite
=> Fix UI test failures in admin and admin_and_public_2 suites

src/explore-education-statistics-common/src/components/ErrorMessage.tsx, src/explore-education-statistics-common/src/components/form/FormBaseInput.tsx, src/explore-education-statistics-common/src/components/form/FormSearchBar.tsx, src/explore-education-statistics-frontend/src/components/SearchForm.tsx
Fixes an accessibility bug where search field errors were not announced to screen readers:
- Find stats and data catalogue search, also updated `SearchForm` to use a standard `Form` 
- Featured table search on step 2 of the table tool (this uses `FormSearchBar` instead of `SearchForm` as it's already inside a form)
=> EES-5299 announce search form errors to screen readers

src/explore-education-statistics-admin/src/pages/release/data/components/__tests__/ReleaseDataGuidanceSection.test.tsx, src/explore-education-statistics-admin/src/pages/release/datablocks/components/chart/__tests__/ChartLegendConfiguration.test.tsx, src/explore-education-statistics-common/src/components/form/Form.tsx, src/explore-education-statistics-common/src/components/form/__tests__/Form.test.tsx
Fixes an issue where the links in the error summary didn't work for nested form fields as the ids were incorrect, they were using the format `formId-fieldIdNestedFieldId` instead of the expected `formId-fieldId-nestedFieldId` because it didn't handle React Hook Form's naming of nested fields correctly.
This affected:
- table tool filters form (EES-3088)
- data guidance form (EES-5747)
- anywhere else with validation on nested fields
=> EES-3088 / EES-5747 fix error links for nested form fields

src/explore-education-statistics-common/src/modules/charts/components/MapBlock.module.scss
Improves the focus style of the zoom controls on maps
Before:
After:
=> EES-5301 focus style on map zoom controls

src/GovUk.Education.ExploreEducationStatistics.Admin.Tests/Services/ReleaseServiceTests.cs, src/GovUk.Education.ExploreEducationStatistics.Admin.Tests/Services/ReleaseVersionRepositoryTests.cs, src/GovUk.Education.ExploreEducationStatistics.Admin/Mappings/MappingProfiles.cs, src/GovUk.Education.ExploreEducationStatistics.Admin/Services/ReleaseService.cs, src/GovUk.Education.ExploreEducationStatistics.Admin/ViewModels/ReleaseViewModels.cs, src/GovUk.Education.ExploreEducationStatistics.Content.Model.Tests/Fixtures/UserReleaseInviteGeneratorExtensions.cs, src/GovUk.Education.ExploreEducationStatistics.Content.Model.Tests/Fixtures/UserReleaseRoleGeneratorExtensions.cs, src/explore-education-statistics-admin/src/pages/publication/__tests__/PublicationManageReleaseContributorsPage.test.tsx, src/explore-education-statistics-admin/src/pages/release/ReleaseCreatePage.tsx, src/explore-education-statistics-admin/src/pages/release/ReleaseSummaryEditPage.tsx, src/explore-education-statistics-admin/src/pages/release/__data__/testRelease.ts, src/explore-education-statistics-admin/src/pages/release/components/ReleaseSummaryForm.tsx, src/explore-education-statistics-admin/src/pages/release/components/__tests__/ReleaseSummaryForm.test.tsx, src/explore-education-statistics-admin/src/pages/release/datablocks/__tests__/ReleaseTableToolPage.test.tsx, src/explore-education-statistics-admin/src/pages/release/pre-release/__tests__/PreReleaseTableToolPage.test.tsx, src/explore-education-statistics-admin/src/services/releaseService.ts
These are the frontend changes associated with the backend changes in https://github.com/dfe-analytical-services/explore-education-statistics/pull/5499.
These changes allow the `Label` to be added to both NEW Releases, and existing Releases which are in DRAFT and only currently have 1 Version, via a new `Label` input field in the Release Summary Page.
For Releases which have **more** than 1 Version, or where the Release **is not** in DRAFT, we disable the time period coverage and label fields in the UI.
=> EES 5629 - Adding a new optional field for the `Label` when creating a new Release (FE)

infrastructure/templates/public-api/application/public-api/publicApiApp.bicep, infrastructure/templates/public-api/application/public-api/publicApiAppInsights.bicep, infrastructure/templates/public-api/application/public-api/publicApiDataProcessor.bicep, infrastructure/templates/public-api/application/shared/appGateway.bicep, infrastructure/templates/public-api/application/shared/postgreSqlFlexibleServer.bicep, infrastructure/templates/public-api/components/alerts/dynamicAlertConfig.bicep, infrastructure/templates/public-api/components/alerts/resourceMetrics.bicep, infrastructure/templates/public-api/components/appGateway.bicep, infrastructure/templates/public-api/components/appInsights.bicep, infrastructure/templates/public-api/components/containerApp.bicep, infrastructure/templates/public-api/components/fileShare.bicep, infrastructure/templates/public-api/components/functionApp.bicep, infrastructure/templates/public-api/components/postgresqlDatabase.bicep, infrastructure/templates/public-api/components/storageAccount.bicep, infrastructure/templates/public-api/main.bicep
This PR:
- adds alerts for errors and failures to various Azure resources in the Public API.
This PR also makes the assumption that certain "failure" HTTP response codes are expected to happen from our application code and so are treated as a lower priority than unexpected ones.  As an example, 403s are expected for failed authentication responses, whereas 401s aren't expected as our end-user interactions don't generally produce those whereas incorrectly configured infrastructure will.
=> EES-5689 - added various failure alerts

src/GovUk.Education.ExploreEducationStatistics.Content.Services/DataSetFileService.cs
Currently, if the DataSetFileMeta isn't valid for a data set, ListDataSetFiles can return a 500. When this happens, it is hard to determine which data set is responsible for the 500.
This change makes finding out trivial by including the subjectId in the exception message.
=> EES-5591 Improve exception message

src/explore-education-statistics-admin/src/pages/release/content/components/AddKeyStatistics.tsx, src/explore-education-statistics-admin/src/pages/release/content/components/EditableKeyStat.tsx, src/explore-education-statistics-admin/src/pages/release/content/components/EditableKeyStatDataBlock.tsx, src/explore-education-statistics-admin/src/pages/release/content/components/EditableKeyStatDataBlockForm.tsx, src/explore-education-statistics-admin/src/pages/release/content/components/EditableKeyStatText.tsx, src/explore-education-statistics-admin/src/pages/release/content/components/EditableKeyStatTextForm.tsx, src/explore-education-statistics-admin/src/pages/release/content/components/KeyStatistics.tsx, src/explore-education-statistics-admin/src/pages/release/content/components/__tests__/EditableKeyStat.test.tsx, src/explore-education-statistics-admin/src/pages/release/content/components/__tests__/EditableKeyStatDataBlock.test.tsx, src/explore-education-statistics-admin/src/pages/release/content/components/__tests__/EditableKeyStatDataBlockForm.test.tsx, src/explore-education-statistics-admin/src/pages/release/content/components/__tests__/EditableKeyStatText.test.tsx, src/explore-education-statistics-admin/src/pages/release/content/components/__tests__/EditableKeyStatTextForm.test.tsx
This PR primarily fixes a bug where the incorrect guidance titles from the other key stats was being passed to the validation in `EditableKeyStatDataBlockForm`. We now calculate the correct set of guidance titles by comparing all key stats with the current form's key stat.
=> EES-5719 Fix unique guidance title validation not triggering correctly

src/GovUk.Education.ExploreEducationStatistics.Admin.Tests/Controllers/Api/Bau/FeedbackControllerTests.cs, src/GovUk.Education.ExploreEducationStatistics.Admin/Controllers/Api/Bau/FeedbackController.cs, src/GovUk.Education.ExploreEducationStatistics.Admin/Migrations/ContentMigrations/20250116162758_EES5469_AddFeedbackTable.Designer.cs, src/GovUk.Education.ExploreEducationStatistics.Admin/Migrations/ContentMigrations/20250116162758_EES5469_AddFeedbackTable.cs, src/GovUk.Education.ExploreEducationStatistics.Common/FeedbackResponse.cs, src/GovUk.Education.ExploreEducationStatistics.Common/ViewModels/FeedbackViewModel.cs, src/GovUk.Education.ExploreEducationStatistics.Content.Api.Tests/Controllers/FeedbackControllerTests.cs, src/GovUk.Education.ExploreEducationStatistics.Content.Api/Controllers/FeedbackController.cs, src/GovUk.Education.ExploreEducationStatistics.Content.Api/Requests/FeedbackCreateRequest.cs, src/GovUk.Education.ExploreEducationStatistics.Content.Model/Database/ContentDbContext.cs, src/GovUk.Education.ExploreEducationStatistics.Content.Model/Feedback.cs, src/GovUk.Education.ExploreEducationStatistics.Content.Requests/FeedbackCreateRequest.cs, src/GovUk.Education.ExploreEducationStatistics.Content.Requests/PublicationsListGetRequest.cs, src/GovUk.Education.ExploreEducationStatistics.Content.Requests/PublicationsListPostRequest.cs, src/explore-education-statistics-admin/src/pages/admin-dashboard/components/FeedbackDetailsModal.tsx, src/explore-education-statistics-admin/src/pages/bau/BauDashboardPage.tsx, src/explore-education-statistics-admin/src/pages/bau/FeedbackPage.tsx, src/explore-education-statistics-admin/src/queries/feedbackQueries.ts, src/explore-education-statistics-admin/src/routes/administrationRoutes.ts, src/explore-education-statistics-admin/src/services/feedbackService.ts, src/explore-education-statistics-common/src/services/types/feedback.ts, src/explore-education-statistics-frontend/src/components/Feedback.module.scss, src/explore-education-statistics-frontend/src/components/Feedback.tsx, src/explore-education-statistics-frontend/src/components/Page.tsx, src/explore-education-statistics-frontend/src/components/__tests__/Feedback.test.tsx, src/explore-education-statistics-frontend/src/services/feedbackService.ts
This PR includes two pieces of work:
1. a banner above the footer on each page of the public website
2. an administrator page to view received feedback
The first part allows users to quickly and easily share feedback on specific areas of the site, and the second provides a simple UI to view this feedback in the "Platform administration" area. This work is to help ensure the product owner and publishers are better informed of user interactions in order to aid decision making, and consider suggestions which may include changes to the platform or publication content.
NB. The administrator page appearance and functionality was a small piece of additional work added for convenience, so there were no designs or specs - I'm happy to consider any suggestions which may improve the UI or UX of this …
=> EES-5469 - Add feedback submission banner and admin view

src/GovUk.Education.ExploreEducationStatistics.Admin.Tests/Services/ReleaseFileServiceTests.cs, src/GovUk.Education.ExploreEducationStatistics.Admin/Services/ReleaseFileService.cs, src/GovUk.Education.ExploreEducationStatistics.Content.Model.Tests/Fixtures/ReleaseVersionGeneratorExtensions.cs, src/GovUk.Education.ExploreEducationStatistics.Content.Services.Tests/DataGuidanceFileWriterTests.cs, src/GovUk.Education.ExploreEducationStatistics.Content.Services.Tests/ReleaseFileServicePermissionTests.cs, src/GovUk.Education.ExploreEducationStatistics.Content.Services.Tests/ReleaseFileServiceTests.cs, src/GovUk.Education.ExploreEducationStatistics.Content.Services.Tests/__snapshots__/DataGuidanceFileWriterTests.WriteToStream_EmptyDataSets.snap, src/GovUk.Education.ExploreEducationStatistics.Content.Services.Tests/__snapshots__/DataGuidanceFileWriterTests.WriteToStream_FileWithEmptyFootnote.snap, src/GovUk.Education.ExploreEducationStatistics.Content.Services.Tests/__snapshots__/DataGuidanceFileWriterTests.WriteToStream_FileWithEmptyProperties.snap, src/GovUk.Education.ExploreEducationStatistics.Content.Services.Tests/__snapshots__/DataGuidanceFileWriterTests.WriteToStream_FileWithEmptyTimePeriodEnd.snap, src/GovUk.Education.ExploreEducationStatistics.Content.Services.Tests/__snapshots__/DataGuidanceFileWriterTests.WriteToStream_FileWithEmptyTimePeriodStart.snap, src/GovUk.Education.ExploreEducationStatistics.Content.Services.Tests/__snapshots__/DataGuidanceFileWriterTests.WriteToStream_FileWithEmptyVariable.snap, src/GovUk.Education.ExploreEducationStatistics.Content.Services.Tests/__snapshots__/DataGuidanceFileWriterTests.WriteToStream_FileWithHtmlFootnotes.snap, src/GovUk.Education.ExploreEducationStatistics.Content.Services.Tests/__snapshots__/DataGuidanceFileWriterTests.WriteToStream_FileWithOverTenFootnotesAndMultiline.snap, src/GovUk.Education.ExploreEducationStatistics.Content.Services.Tests/__snapshots__/DataGuidanceFileWriterTests.WriteToStream_FileWithSingleProperties.snap, src/GovUk.Education.ExploreEducationStatistics.Content.Services.Tests/__snapshots__/DataGuidanceFileWriterTests.WriteToStream_MultipleDataSets.snap, src/GovUk.Education.ExploreEducationStatistics.Content.Services.Tests/__snapshots__/DataGuidanceFileWriterTests.WriteToStream_NoDataGuidance.snap, src/GovUk.Education.ExploreEducationStatistics.Content.Services.Tests/__snapshots__/DataGuidanceFileWriterTests.WriteToStream_SingleDataSet.snap, src/GovUk.Education.ExploreEducationStatistics.Content.Services/DataGuidanceFileWriter.cs, src/GovUk.Education.ExploreEducationStatistics.Content.Services/ReleaseFileService.cs
This PR updates the `DataGuidanceFileWriter.DoWrite` to write out `Release.Title` in the second line. Previously this consisted of properties of `ReleaseVersion` formatted as `{ReleaseVersion.Year} {ReleaseVersion.TimePeriodCoverage}`.
This fixes a problem where a release label (if set) is not present in the second line of the data guidance. `Release.Title` is a calculated property containing the label.
=> EES-5800 Update DataGuidanceFileWriter.DoWrite to use Release title

src/explore-education-statistics-admin/src/pages/release/ReleaseSummaryPage.tsx, src/explore-education-statistics-admin/src/pages/release/pre-release/ReleasePreReleaseAccessPage.tsx, tests/robot-tests/tests/admin/bau/create_publication_and_release.robot, tests/robot-tests/tests/admin_and_public/bau/publish_data.robot, tests/robot-tests/tests/admin_and_public_2/bau/publish_release_and_amend.robot, tests/robot-tests/tests/libs/admin-common.robot, tests/robot-tests/tests/libs/admin_api.py
This PR changes the release Summary page in the Admin to include the release label.
It adds in support into the UI test keywords `user creates test release via api` and `user creates release from publication page` for creating a release with a label.
It adds in suppport into the keyword `user verifies release summary` to verify the label.
Fixes a bug where the release label is cleared when a release is updated after saving a public pre-release access list.
=> EES-5799 Add release label to Admin's release summary page

infrastructure/templates/public-api/components/functionApp.bicep
This PR:
- upgrades the Public API Function App's minimum TLS level to 1.3.
This satisfies the following advisory:
and results in:
=> Ees 5399 upgrade function app tls

src/GovUk.Education.ExploreEducationStatistics.Public.Data.Api/GovUk.Education.ExploreEducationStatistics.Public.Data.Api.csproj
When starting the Public Data API, the following error message can break the application for windows users.
This change prevents this error from breaking the start up process.
Error:  
```
dotnet tool run swagger tofile --output bin\Debug\n…et8.0\wwwroot/openapi-v1.json bin\Debug\net8.0\GovUk.Education.ExploreEducationStatistics.Public.Data.Api.dll exited with code  -532462766.
``` 
(https://github.com/domaindrivendev/Swashbuckle.AspNetCore/issues/2761)
=> Fix start up Public API bug

tests/performance-tests/README.md, tests/performance-tests/src/configuration/rampingRequestRateProfile.ts, tests/performance-tests/src/tests/public-api/data-set-query/config.ts
This PR:
- adds a plateau period to our standard stress test profile, so that after the initial ramp-up period, the maximum RPS can be maintained for a period of time.
We have a common stress test profile that a number of our K6 performance tests support.  Prior to this PR, this would simply ramp up the RPS over time from zero to a maximum RPS, and see where the system under test snapped!
With this change, we can now add a period of time after the ramp-up period to maintain that max RPS.  This is useful for testing scenarios where you want to allow the system to scale gracefully prior to hitting it with maximum RPS, and then see how it handles that maximum RPS following on from that.
The following command produces the results shown below, ramping up traffic from 0 RPS to 10 RPS over the …
=> EES-4877 - added a "plateau" period to the end of the ramping up stage

src/explore-education-statistics-common/src/styles/_form.scss
Updates the hover style for small radio buttons to make it clearer for low vision users.
I've [suggested this as a change to the design system team](https://github.com/alphagov/govuk-design-system-backlog/issues/59#issuecomment-2610085003), if they agree I'll raise a PR for it in the design system repo and we can remove this override later on.
Current:
New:
=> EES-5308 improve small radio hover style

src/GovUk.Education.ExploreEducationStatistics.Common/Model/TimeIdentifierCategory.cs
Although the time period itself has been removed, the category shown in the dropdown list remained. This PR removes the empty category.
=> EES-5768: Remove "National tutoring programme" from time period categories

infrastructure/templates/public-api/abbreviations.bicep, infrastructure/templates/public-api/application/public-api/publicApiStorage.bicep, infrastructure/templates/public-api/ci/jobs/deploy-data-processor.yml, infrastructure/templates/public-api/ci/jobs/deploy-infrastructure.yml, infrastructure/templates/public-api/ci/tasks/check-function-app-exists.yml, infrastructure/templates/public-api/ci/tasks/wait-for-endpoint-success.yml, infrastructure/templates/public-api/components/durableFunctionApp.bicep, infrastructure/templates/public-api/components/fileShare.bicep, infrastructure/templates/public-api/components/storageAccount.bicep, infrastructure/templates/public-api/main.bicep, infrastructure/templates/public-api/types.bicep, infrastructure/templates/template.json
This PR:
- swaps the "Standard" storage account used for the Public API for a "Premium", File share-centric storage account.
Our Public API storage account is now set up as a Premium, `FileStorage` storage account, meaning that it is tailored towards providing file shares with extremely low latency.
Currently all environments are the same, each provisioning a file share of 100GBs (the minimum amount allowed in a Premium storage account.
All other existing storage accounts (e.g. the 3 used by the Data Processor) remain `StandardV2`.
In order to roll out these changes, existing Public API storage accounts firstly needed to be backed up, and then deleted completely, as these settings cannot be applied retrospectively.
As we had to rebuild any existing Public API storage accounts in Resource …
=> Ees 5814 add premium storage accounts

tests/robot-tests/tests/libs/common.robot
This PR changes the headless argument we use when opening google-chrome in the UI tests to not use "old".
We did this because we started seeing failures like this:
```
2025-01-28T10:26:13.8418368Z UI Tests.Glossary Page                                                        
2025-01-28T10:26:13.8418684Z ==============================================================================
2025-01-28T10:26:13.8418983Z Navigate to glossary page                                             | FAIL |
2025-01-28T10:26:13.8419220Z Parent suite setup failed:
2025-01-28T10:26:13.8419591Z SessionNotCreatedException: Message: session not created: probably user data directory is already in use, please specify a unique value for --user-data-dir argument, or don't use --user-data-dir
```
It seems like newer …
=> EES-5742 Fix UI tests

package.json, src/GovUk.Education.ExploreEducationStatistics.Admin/Validators/ValidationMessages.cs, src/explore-education-statistics-admin/src/pages/release/data/ReleaseDataFilePage.tsx, src/explore-education-statistics-admin/src/pages/release/data/__tests__/ReleaseDataFileReplacePage.test.tsx, src/explore-education-statistics-admin/src/pages/release/data/components/DataFileDetailsTable.tsx, src/explore-education-statistics-admin/src/pages/release/data/components/DataFileUploadForm.tsx, src/explore-education-statistics-admin/src/pages/release/data/components/DataFilesTable.module.scss, src/explore-education-statistics-admin/src/pages/release/data/components/DataFilesTable.tsx, src/explore-education-statistics-admin/src/pages/release/data/components/ImporterStatus.tsx, src/explore-education-statistics-admin/src/pages/release/data/components/ReleaseDataUploadsSection.tsx, src/explore-education-statistics-admin/src/pages/release/data/components/__tests__/ReleaseDataUploadsSection.test.tsx, src/explore-education-statistics-admin/src/prototypes/components/PrototypeDataReplace.tsx, src/explore-education-statistics-common/src/components/ButtonGroup.module.scss, src/explore-education-statistics-common/src/components/Tag.module.scss, src/explore-education-statistics-common/src/styles/_reset.scss, tests/robot-tests/tests/admin/analyst/edit_and_approve_release_as_publication_approver.robot, tests/robot-tests/tests/admin/bau/delete_subject.robot, tests/robot-tests/tests/admin/bau/release_status.robot, tests/robot-tests/tests/admin/bau/upload_files.robot, tests/robot-tests/tests/admin_and_public/bau/archive_publication.robot, tests/robot-tests/tests/admin_and_public/bau/data_reordering.robot, tests/robot-tests/tests/admin_and_public/bau/subject_reordering.robot, tests/robot-tests/tests/admin_and_public_2/bau/publish_amend_and_cancel.robot, tests/robot-tests/tests/admin_and_public_2/bau/publish_release_and_amend.robot, tests/robot-tests/tests/admin_and_public_2/bau/publish_release_and_amend_2.robot, tests/robot-tests/tests/general_public/methodology_page_absence.robot, tests/robot-tests/tests/libs/admin-common.robot, tests/robot-tests/tests/libs/common.robot, tests/robot-tests/tests/libs/tables-common.robot
See [Ticket EES-5544](https://dfedigital.atlassian.net/browse/EES-5544)
=> EES-5544 Change data set import page accordions into a table

src/explore-education-statistics-admin/src/pages/release/data/components/DataFilesTable.module.scss, src/explore-education-statistics-admin/src/pages/release/data/components/ReleaseDataUploadsSection.tsx, src/explore-education-statistics-common/src/components/ProgressBar.module.scss
- no wrapping on file upload file-size text
- stop importer status progress bar breaking out of the cell
- hide redundant reorder button when less than 2 files have been uploaded
- title overflow wrapping, stopping huge words breaking out of title cell
=> EES-5544 layout polish

src/GovUk.Education.ExploreEducationStatistics.Admin.Tests/Controllers/Api/ReleasesControllerTests.cs, src/GovUk.Education.ExploreEducationStatistics.Admin.Tests/Services/ReleaseServiceTests.cs, src/GovUk.Education.ExploreEducationStatistics.Admin/Migrations/ContentMigrations/20250123174256_EES5659_RemovePropertiesFromReleaseVersion.Designer.cs, src/GovUk.Education.ExploreEducationStatistics.Admin/Migrations/ContentMigrations/20250123174256_EES5659_RemovePropertiesFromReleaseVersion.cs, src/GovUk.Education.ExploreEducationStatistics.Admin/Services/ReleaseAmendmentService.cs, src/GovUk.Education.ExploreEducationStatistics.Admin/Services/ReleaseService.cs, src/GovUk.Education.ExploreEducationStatistics.Content.Model.Tests/Fixtures/ReleaseGeneratorExtensions.cs, src/GovUk.Education.ExploreEducationStatistics.Content.Model.Tests/Fixtures/ReleaseVersionGeneratorExtensions.cs, src/GovUk.Education.ExploreEducationStatistics.Content.Model/Database/ContentDbContext.cs, src/GovUk.Education.ExploreEducationStatistics.Content.Model/ReleaseVersion.cs
⚠️ This PR depends on https://github.com/dfe-analytical-services/explore-education-statistics/pull/5553 and should only be merged once that one has been tested and deployed.⚠️ 
This PR is a tidy-up to remove `ReleaseName`, `Slug`, and `TimePeriodCoverage` from `ReleaseVersion`, including a migration to drop these columns from the database.
[EES-5658](https://github.com/dfe-analytical-services/explore-education-statistics/pull/5553) completed swapping out the usage of these properties in `ReleaseVersion` with their equivalents in `Release`.
=> EES-5659 Remove `ReleaseName`, `Slug`, and `TimePeriodCoverage` from `ReleaseVersion`

.npmrc, README.md, azure-pipelines-main.yml
This PR fixes Corepack failing its integrity key check due to NPM recently rotating its keys. See: https://github.com/nodejs/corepack/issues/612
I believe the general gist is that older versions (bundled with Node) may have hard-coded NPM's public key, which expired last week and was rotated to a new one.
We resolve this by simply using the latest Corepack version which doesn't have this issue.
=> Fix corepack integrity key check

infrastructure/parameters/prod.parameters.json
This PR makes an ARM template parameter change to `prod.parameters.json` to increase the capacity of the statistics and statistics replica database in the Prod environment from 1500Gb to 2048Gb.
1536Gb is the max data size limit for a `GP_Gen5_6` scaled database, so when we increase and eventually allocate data above this limit we will not be able to scale back to `GP_Gen5_6`.
`GP_Gen5_8`  and `GP_Gen5_10` have a max data size limit of 2048Gb.
For a while now we’ve had the database scale set at `GP_Gen5_10`. Given that we need to increase the capacity, it seems sensible to set the new limit to match this at 2048Gb.
=> EES-5834 Increase capacity of statistics and statistics replica databases in Prod

src/explore-education-statistics-frontend/src/modules/find-statistics/PreReleaseAccessListPage.tsx, src/explore-education-statistics-frontend/src/modules/find-statistics/PublicationReleasePage.tsx, src/explore-education-statistics-frontend/src/modules/find-statistics/ReleaseDataGuidancePage.tsx
hotfix to:
pre-release access page (breadcrumbing)
data guidance page (breadcrumbing)
Undone accidental change to latest release link on the public release page
=> Ees-5835 release slug hotfix

docker/public-frontend/Dockerfile
Adds similar fix from #5580 to public frontend's Dockerfile.
Relates to: https://github.com/nodejs/corepack/issues/612
=> Fix corepack integrity key check for public frontend Dockerfile

src/explore-education-statistics-admin/src/pages/release/data/components/ReleaseDataUploadsSection.tsx, src/explore-education-statistics-admin/src/pages/release/data/components/__tests__/ReleaseDataUploadsSection.test.tsx
This PR performs some cleanup in preparation for a second PR for EES-5545 (#5571):
- Memoize callbacks in `ReleaseDataUploadsSection`
- Extract `DeleteDataFileModal` into its own component to stop it cluttering up `ReleaseDataUploadsSection`
- Clean up `ReleaseDataUploadsSection` tests:
- Fixing inefficient `waitFor` blocks using `getByRole` selectors
- Replacing `waitFor` blocks with `findBy*` selectors
- Reorganising various assertions 
- Removing `getTableRow` as it assumes a single table (there will be two tables in the next PR)
=> EES-5545 Cleanup for `ReleaseDataUploadsSection`

src/explore-education-statistics-frontend/src/modules/find-statistics/PublicationReleasePage.tsx
Fix to latest release link where the user would be redirected to the previously viewed release slug rather than the latest
=> EES-5835 fix to latest release link

src/explore-education-statistics-api-docs/source/getting-started/creating-advanced-data-set-queries/index.html.md.erb, src/explore-education-statistics-api-docs/source/getting-started/debugging-data-set-queries/index.html.md.erb, src/explore-education-statistics-api-docs/source/getting-started/how-to-get-csv-data/index.html.md.erb, src/explore-education-statistics-api-docs/source/getting-started/quick-start/index.html.md.erb, src/explore-education-statistics-api-docs/source/overview/versioning/index.html.md.erb
This PR simply strips the incorrect `/api` prefix from URLs in the public API.
=> EES-5841 Remove old `/api` prefix from URLs in public API docs

src/explore-education-statistics-admin/src/pages/release/data/ReleaseApiDataSetPreviewTokenPage.tsx, src/explore-education-statistics-admin/src/pages/release/data/__tests__/ReleaseApiDataSetPreviewTokenPage.test.tsx, tests/robot-tests/tests/public_api/public_api_preview_token.robot
After revoking an API preview token redirect to the preview token log page instead of the generate token page as users found this confusing.
=> EES-5808 go to preview log after api token revoked

src/explore-education-statistics-admin/src/pages/release/data/components/ApiDataSetCreateModal.tsx, src/explore-education-statistics-admin/src/pages/release/data/components/ApiDataSetCreateProcessing.tsx, src/explore-education-statistics-admin/src/pages/release/data/components/ReleaseApiDataSetsSection.tsx, src/explore-education-statistics-admin/src/pages/release/data/components/__tests__/ApiDataSetCreateModal.test.tsx, src/explore-education-statistics-admin/src/pages/release/data/components/__tests__/ReleaseApiDataSetsSection.test.tsx, tests/robot-tests/tests/public_api/public_api_cancel_and_removal.robot, tests/robot-tests/tests/public_api/public_api_major_auto_changes.robot, tests/robot-tests/tests/public_api/public_api_minor_manual_changes.robot, tests/robot-tests/tests/public_api/public_api_preview_token.robot, tests/robot-tests/tests/public_api/public_api_restricted.robot
When you create a new API data set, instead of being taken automatically to the data set details page, the modal updates to make it clearer that the data set is being processed. The list on the page under the modal is also updated so if you close the modal the new API data set will be visible there.
=> EES-5807 make it clearer new api data set is processing

src/explore-education-statistics-api-docs/source/partials/_parameter_table.html.erb, src/explore-education-statistics-api-docs/source/stylesheets/app.scss, src/explore-education-statistics-api-docs/source/stylesheets/components/_header.scss, src/explore-education-statistics-api-docs/source/stylesheets/components/_table.scss, src/explore-education-statistics-api-docs/source/stylesheets/components/_toc.scss, src/explore-education-statistics-api-docs/source/stylesheets/screen.css.scss, src/explore-education-statistics-api-docs/source/templates/reference/endpoint.html.md.erb, src/explore-education-statistics-api-docs/source/templates/reference/schema.html.md.erb
This PR fixes various accessibility issues that have been highlighted by @N-moh
- Added unique `aria-label` / `aria-labelledby` attributes for parameter tables
- Fixed header appearing really broken at 200%+ zoom
- Fixed overflowing text from large word breaking the entire layout at 200%+ zoom (using `word-break`)
- Fixed mobile TOC styling being mostly broken when 200%+ zoom
Additionally, I've made some more tweaks whilst in the area:
- Fixed 'Endpoints' and 'Schemas' child items not being displayed in the mobile TOC
- Fixed parameter table styling being mostly broken at 200%+ zoom
New header:
New TOC:
New parameter tables:
=> EES-5554 Fix accessibility issues in public API docs

infrastructure/templates/template.json, src/explore-education-statistics-admin/src/pages/release/data/ReleaseApiDataSetPreviewTokenPage.tsx, src/explore-education-statistics-common/src/modules/data-catalogue/components/ApiDataSetQuickStart.tsx, src/explore-education-statistics-common/src/services/api/index.ts, src/explore-education-statistics-frontend/.env, src/explore-education-statistics-frontend/src/modules/data-catalogue/components/__tests__/DataSetFileApiQuickStart.test.tsx
This PR fixes incorrect public API URLs being shown on the preview token page.
We also strip out the API version from `PUBLIC_API_BASE_URL` in favour of controlling the version from the frontend. This creates less opportunity for error if we eventually publish a new API version as we won't need to make updates in multiple places.
We've also added missing test assertions for the public API docs URLs in `DataSetFileApiQuickStart`.
=> EES-5846 Fix incorrect public API URLs on preview token page

src/explore-education-statistics-common/src/modules/charts/components/CustomTooltip.tsx, src/explore-education-statistics-common/src/modules/charts/components/HorizontalBarBlock.tsx, src/explore-education-statistics-common/src/modules/charts/components/LineChartBlock.tsx, src/explore-education-statistics-common/src/modules/charts/components/VerticalBarBlock.tsx, src/explore-education-statistics-common/src/modules/charts/components/__tests__/HorizontalBarBlock.test.tsx, src/explore-education-statistics-common/src/modules/charts/components/__tests__/LineChartBlock.test.tsx, src/explore-education-statistics-common/src/modules/charts/components/__tests__/VerticalBarBlock.test.tsx, src/explore-education-statistics-common/src/modules/charts/components/__tests__/__data__/testChartData.ts
Previously charts with no data would render as an empty white block, which errored on hover. I've changed it to show n message instead: 
The change to `CustomTooltip`, which was where the original error was, probably isn't necessary as after I added it I changed it so it doesn't try to render empty charts, but I thought I might as well leave it in just in case there are other circumstances in which `payload` can be undefined.
=> EES-5759 handle empty charts

src/explore-education-statistics-admin/src/pages/release/datablocks/components/chart/ChartAxisConfiguration.tsx, src/explore-education-statistics-admin/src/pages/release/datablocks/components/chart/__tests__/ChartAxisConfiguration.test.tsx, src/explore-education-statistics-common/src/utils/number/formatPretty.ts
Fixes a bug where charts errored if you tried to set the displayed decimal places to a negative number. Also, set the decimal places field to only show on the minor axis configuration tab, as it's irrelevant on the major axis.
=> EES-5720 fix chart decimal places bug

src/explore-education-statistics-admin/src/pages/release/datablocks/components/DataBlockDetailsForm.tsx, src/explore-education-statistics-admin/src/pages/release/datablocks/components/DataBlockPageTabs.tsx, src/explore-education-statistics-admin/src/pages/release/datablocks/components/DataBlockSourceWizard.tsx
Currently editing data blocks that were created before the alt text character limit was added (https://github.com/dfe-analytical-services/explore-education-statistics/pull/5497) can result in an unhandled error when the original alt text was longer than the new limit.
I've improved this by showing an error and telling users to check the Chart configuration:
As part of this I've removed the loading spinner that would show for at least 500ms after the form was submitted as I couldn't find a way to remove it when the form errors. This hopefully won't cause any problems as we have double-submit protection on forms now and don't seem to have performance issues creating / updating data blocks. If this is a problem we may need to reconsider how to handle this error.
=> EES-5824 handle alt text length error when saving data blocks

infrastructure/templates/public-api/main.bicep, infrastructure/templates/public-api/types.bicep
This PR:
- fixes issues where the Public API static webapp's trailing slash redirect were including the static webapp's FQDN in the redirect rather than the public FaUAPI FQDN.
Previously if navigating to a docs URL without a trailing slash, the static webapp (being configured with `"trailingSlash": "auto"`) would redirect to a version of the URL with a trailing slash added.  Unfortunately it would implement this as a redirect to an absolute URL with the static webapp's FQDN included.
Thus, navigating to:
https://pp-api.education.gov.uk/statistics-dev/docs/getting-started
would redirect to:
https://witty-bay-020052c03.4.azurestaticapps.net/getting-started/
It doesn't seem like there is any way to override this trailing slash redirect behaviour from the static webapp.
Looking into this, it …
=> EES-5820 - rewriting "Location" response headers to replace static webapp FQDN with public FQDN

infrastructure/templates/public-api/main.bicep, src/GovUk.Education.ExploreEducationStatistics.Public.Data.Api/Startup.cs
This PR:
- adds the full base URL of the Public API to the Swagger UI configuration, so that openapi.json docs can be fetched correctly.
Prior to this PR, visiting the Swagger UI through FaUAPI would result in failure.
Visiting `https://pp-api.education.gov.uk/statistics-dev/swagger/index.html` would result in:
Swagger UI was not including the full base URL of the Public API (https://pp-api.education.gov.uk/statistics-dev/swagger) in its request to find `openapi-v1.json`).
This PR adds that full URL onto the file request path.
=> EES-5802 - allowing base url of Public API to be added to Swagger UI document fetch

src/explore-education-statistics-admin/src/pages/release/datablocks/components/DataBlockPageTabs.tsx
Undo the removal of `return` of the updated datablock, thus preventing a new datablock being created in the same action
=> EES-5887 - Fix edit datablock 'duplication'

src/GovUk.Education.ExploreEducationStatistics.Public.Data.Api/Swagger/SwaggerConfig.cs
This PR:
- corrects the API server URL that Swagger uses to send the API requests to take into account the sub-url that we have on FaUAPI.
Before we were missing the `statistics-dev` portion of the Public API URL for requests being sent from FaUAPI's hosted URL:
This now updates the API server's base URL to use the correct Public API URL.
=> EES-5802 - updated Swagger API server URL to allow API requests through FaUAPI correctly on /statistics-dev/ sub-url.

src/explore-education-statistics-common/src/modules/data-catalogue/components/FilterOptionChangeLabel.tsx, src/explore-education-statistics-common/src/modules/data-catalogue/components/__tests__/ChangeList.test.tsx, src/explore-education-statistics-common/src/modules/data-catalogue/components/__tests__/ChangeSection.test.tsx, src/explore-education-statistics-common/src/services/types/apiDataSetMeta.ts, tests/robot-tests/tests/public_api/public_api_minor_manual_changes.robot
This PR removes any references to auto-selects and defaults from the public API changelog.
=> EES-5848 Remove references to auto-selects and defaults from public API changelog

src/explore-education-statistics-api-docs/config.rb, src/explore-education-statistics-api-docs/config/tech-docs.yml, src/explore-education-statistics-api-docs/lib/govuk_tech_docs/contribution_banner.rb, src/explore-education-statistics-api-docs/lib/govuk_tech_docs/path_helpers.rb
This PR fixes the 'View source' links at the bottom of each page. To fix this, we needed to monkey path the existing `GovukTechDocs.SourceUrls` class to provide the correct path. The default implementation expects the docs to live at the project root whilst ours are in `src/explore-education-statistics-api-docs`.
- Tidied up monkey patch for `GovukTechDocs.PathHelpers`.
=> EES-5866 Fix 'View source' links in public API docs

tests/robot-tests/tests/admin/bau/release_status.robot
This PR fixes a robot test that was failing because it was looking for 'Data uploads table' instead of 'Data file replacements table'
=> EES-5867 Fix UI test failure in release_status.robot

src/explore-education-statistics-admin/src/pages/release/data/components/DataFilesTable.tsx, src/explore-education-statistics-admin/src/pages/release/data/components/ImporterStatus.tsx, src/explore-education-statistics-admin/src/pages/release/data/components/__tests__/ImporterStatus.test.tsx
This PR hides the errors from the data files table to prevent it rendering in a really squashed way.
Note the user can still access the importer errors via the 'View details' button that will show the errors as normal.
- Cleaned up `ImporterStatus` tests to remove inefficient `waitFor` blocks
=> EES-5849 Hide importer errors from data files table

src/GovUk.Education.ExploreEducationStatistics.Content.Api.Tests/Builders/ContentSectionViewModelBuilder.cs, src/GovUk.Education.ExploreEducationStatistics.Content.Api.Tests/Builders/ThemeViewModelBuilder.cs, src/GovUk.Education.ExploreEducationStatistics.Content.Api.Tests/Controllers/ReleaseControllerTests.cs, src/GovUk.Education.ExploreEducationStatistics.Content.Api/Controllers/ReleaseController.cs, src/GovUk.Education.ExploreEducationStatistics.Content.ViewModels/Extensions/ReleaseTypeExtensions.cs, src/GovUk.Education.ExploreEducationStatistics.Content.ViewModels/Extensions/StringExtensions.cs, src/GovUk.Education.ExploreEducationStatistics.Content.ViewModels/ReleaseSearchViewModel.cs
In order for Azure AI Search to work effectively, we want to have the indexer trawl over a more searchable representation of a release. I have added an end point that provides this representation along with the associated metadata. This will be consumed by an Azure function that will upload the result to Azure storage for the indexer to process.
Note that the html content being created is subject to different new line representations depending on the runtime platform and the compiler. Therefore, I've standardised it to use Unix line endings to ensure a consistent output regardless of where it is being executed.
=> EES-5874 Create a searchable version of a release including associated metadata

src/GovUk.Education.ExploreEducationStatistics.Admin.Tests/Controllers/Api/ReleasesControllerTests.cs, src/GovUk.Education.ExploreEducationStatistics.Admin/Migrations/ContentMigrations/20250224184121_EES5868_ReduceReleaseLabelLimitTo20Characters.Designer.cs, src/GovUk.Education.ExploreEducationStatistics.Admin/Migrations/ContentMigrations/20250224184121_EES5868_ReduceReleaseLabelLimitTo20Characters.cs, src/GovUk.Education.ExploreEducationStatistics.Admin/Requests/ReleaseRequests.cs, src/GovUk.Education.ExploreEducationStatistics.Content.Model/Release.cs, src/explore-education-statistics-admin/src/pages/release/components/ReleaseSummaryForm.tsx, src/explore-education-statistics-admin/src/pages/release/components/__tests__/ReleaseSummaryForm.test.tsx
We currently have a release label limit of 50, we’d like to drop it to 20 before anyone adds anything. We can easily up it back up at a later date if needed but wanting to keep tight control as we start.
⚠️Blocked until https://github.com/dfe-analytical-services/explore-education-statistics/pull/5591 is merged⚠️
=> EES-5868 Reducing the Release `Label` character limit to 20

infrastructure/infrastructure-pipeline.yml, infrastructure/templates/search/abbreviations.bicep, infrastructure/templates/search/bicepconfig.json, infrastructure/templates/search/ci/azure-pipelines.yml, infrastructure/templates/search/ci/jobs/deploy-infrastructure.yml, infrastructure/templates/search/ci/stages/deploy.yml, infrastructure/templates/search/ci/tasks/deploy-bicep.yml, infrastructure/templates/search/main.bicep, infrastructure/templates/search/parameters/main-dev.bicepparam, infrastructure/templates/search/parameters/main-preprod.bicepparam, infrastructure/templates/search/parameters/main-prod.bicepparam, infrastructure/templates/search/parameters/main-test.bicepparam, infrastructure/templates/search/types.bicep
This PR adds an Azure DevOps pipeline to create and update Azure components defined as Bicep related to implementing site-wide search.
We would like to define the infrastructure for implementing site-wide search as Bicep, but up until now the Public API infrastructure pipeline is the only other pipeline setup to deploy configuration defined as Bicep.
At the moment we have a requirement to "Keep the Public API stable" so the intention here has been to make the least amount of changes to Public API infrastructure config in order to create a pipeline for deploying search components independently of the Public API. 
At a later date a larger renaming/refactoring exercise will probably be needed to organise common resources and variables.
=> EES-5896 Azure DevOps pipeline for Search infrastructure deployment

src/GovUk.Education.ExploreEducationStatistics.Public.Data.Api.Tests/Migrations/EES5660_MigrateDraftDataSetVersionFolderNamesTests.cs
These unit tests create an empty file and then attempts to move the folder it is in. Windows does not allow this because the file handle is still open. Linux is happy to do it. Fix is to close the file handle.
=> Fix Unit Tests on Windows

src/explore-education-statistics-admin/src/pages/release/datablocks/components/DataBlockPageReadOnlyTabs.tsx
Previously when you viewed a map on a read only data block (on a published release) it didn't load properly. Now it works.
=> EES-5403 fix map loading on readonly datablocks

src/explore-education-statistics-common/src/modules/charts/components/MapBlock.module.scss
Forces long words in map tooltips to break instead of overflowing.
=> EES-4359 force text wrapping in map tooltips

src/explore-education-statistics-common/src/modules/charts/components/MapGeoJSON.tsx
Handles when map areas have no data.
Before:
After:
=> EES-5224 handle empty map tooltips

src/explore-education-statistics-common/src/modules/find-statistics/components/KeyStatTile.tsx, src/explore-education-statistics-common/src/modules/find-statistics/components/__tests__/KeyStat.test.tsx, src/explore-education-statistics-common/src/queries/tableBuilderQueries.ts
When an indicator has `numberString` as the unit they should always be displayed as a string in Key Stats, with no formatting or rounding.
=> EES-5490 respect numStrings in key stats

src/explore-education-statistics-admin/src/pages/release/datablocks/components/DataBlockSelector.tsx
Removes the 'create another data block' button when viewing a published release.
=> EES-3232 remove create datablock button on published releases

src/GovUk.Education.ExploreEducationStatistics.Data.Api.Tests/Services/PermalinkServiceTests.cs, src/GovUk.Education.ExploreEducationStatistics.Data.Api/Requests/PermalinkCreateRequest.cs, src/GovUk.Education.ExploreEducationStatistics.Data.Api/Services/PermalinkService.cs
This PR fixes a mismatch in frontend/backend models relating to the `interface CreatePermalink` and `record PermalinkCreateRequest`.
This was preventing uses from creating permalinks in some cases.
=> Hotfix: EES-5907 Fix frontend/backend request model mismatch

infrastructure/parameters/prod.parameters.json, infrastructure/parameters/test.parameters.json, infrastructure/templates/public-api/ci/azure-pipelines.yml, infrastructure/templates/public-api/components/postgreSqlFlexibleServer.bicep
This PR:
- enables the Public API in Prod, so that Admin, Publisher and the Public Site become aware of the Public API.
- adds an automated deploy stage to the Public API pipeline to allow an optional deploy stage to Prod following on from a successful deploy to Pre-Prod.  This is protected from automated rollout by manual approvals that have been set up in the Prod DevOps environment.
- adds a manual deploy stage to be able to deploy directly to Prod.  This'll most likely be removed shortly after getting Public API fully deployed and running on Prod.
=> Ees 5802 add public api support to prod

src/explore-education-statistics-api-docs/source/getting-started/building-api-integrations/index.html.md.erb
This adds a link in the API docs to PowerBI sdk
=> EES-5917 Add extra link for power bi sdk users

src/explore-education-statistics-api-docs/source/getting-started/building-api-integrations/index.html.md.erb
This adds a link in the API docs to PowerBI sdk
=> Ees 5917 api docs sdk page to add link to powerbi sdk repository

infrastructure/templates/public-api/ci/azure-pipelines.yml
This PR removes the ability to deploy the Public API directly to the Prod environment.
This was previously used to perform manual rollouts of Public API infrastructure prior to integrating it with the rest of the service.
=> EES-5802 - removed the ability to roll out the Public API direct to the Prod environment from DevOps

src/explore-education-statistics-common/src/components/NotificationBanner.tsx, src/explore-education-statistics-frontend/src/components/Page.tsx, src/explore-education-statistics-frontend/src/modules/permalink/PermalinkPage.tsx
Adds a notification banner for the API on all pages except permalinks.
=> EES-5916 api notification banner

src/explore-education-statistics-frontend/src/modules/data-catalogue/DataSetFilePage.tsx, src/explore-education-statistics-frontend/src/modules/data-catalogue/components/DataSetFileDetails.tsx
- Makes sure the email button doesn't move depending on the length of the description.
- Adds the divider lines back to the data set details.
=> EES-5878 small FE tweaks to data set page

src/GovUk.Education.ExploreEducationStatistics.Content.Search.FunctionApp/Functions/HealthCheckFunction.cs, src/GovUk.Education.ExploreEducationStatistics.Content.Search.FunctionApp/Functions/HealthChecks/Dtos/HealthCheckResponseDto.cs, src/GovUk.Education.ExploreEducationStatistics.Content.Search.FunctionApp/Functions/HealthChecks/HealthCheckFunction.cs
This PR adds a basic `/api/HealthCheck` function to the Search Function App to be used with the Azure Function infrastructure deployment and for checking the resource health in the Azure Portal.
When healthy it returns HTTP response code 200 OK with content:
```json
{"healthy": true}
```
It currently makes no checks but we could improve on this, for example by checking the Azure Storage account blob container for searchable documents exists.
=> EES-5899 Add HealthCheck function to Search Function App

infrastructure/templates/template.json, src/GovUk.Education.ExploreEducationStatistics.Common/BlobContainers.cs
This PR changes management policies associated with the core Azure Storage instance so that any blob file in the `releases-temp` container is removed if it is not modified for a day.
This ensures that this does slowly fill up with blob files, which can happen if a user starting importing several data sets via a bulk import but then doesn't complete the process and/or if there is an error (maybe).
=> EES-5709 Delete core storage 'releases-temp' blobs after a day

azure-pipelines-main.yml, infrastructure/templates/common/abbreviations.bicep, infrastructure/templates/common/components/functionApp.bicep, infrastructure/templates/common/components/storageAccountRoleAssignment.bicep, infrastructure/templates/common/types.bicep, infrastructure/templates/public-api/ci/tasks/wait-for-endpoint-success.yml, infrastructure/templates/public-api/components/appInsights.bicep, infrastructure/templates/public-api/components/storageAccount.bicep, infrastructure/templates/search/application/searchApplicationInsights.bicep, infrastructure/templates/search/application/searchDocsFunction.bicep, infrastructure/templates/search/application/searchService.bicep, infrastructure/templates/search/ci/azure-pipelines.yml, infrastructure/templates/search/ci/jobs/deploy-infrastructure.yml, infrastructure/templates/search/ci/jobs/deploy-search-docs-function-app.yml, infrastructure/templates/search/ci/stages/deploy.yml, infrastructure/templates/search/ci/tasks/deploy-bicep.yml, infrastructure/templates/search/main.bicep, infrastructure/templates/search/parameters/main-dev.bicepparam, infrastructure/templates/search/parameters/main-preprod.bicepparam, infrastructure/templates/search/parameters/main-prod.bicepparam, infrastructure/templates/search/parameters/main-test.bicepparam, infrastructure/templates/search/types.bicep, infrastructure/templates/template.json
This PR adds new infrastructure for implementing site-wide search. It contains Bicep defining the infrastructure for the Search Docs Azure Function app added by #5630.
It also changes the DevOps Search pipeline to deploy this infrastructure and publish the built app.
At the moment we have a requirement to "Keep the Public API stable" so the intention here has been to make the least amount of changes to Public API infrastructure config.
Continuing with the approach taken by #5628, this PR continues to reference some Public API templates rather than refactoring them to make them common. At a later date a larger renaming/refactoring exercise will probably be needed.
This PR adds a new functionApp.bicep template since we don't currently have this in our library of components. This is added to …
=> EES-5899 Add infrastructure and deploy Search Docs Function App

src/GovUk.Education.ExploreEducationStatistics.Content.Search.FunctionApp/Exceptions/UnableToCreateSearchableDocumentException.cs, src/GovUk.Education.ExploreEducationStatistics.Content.Search.FunctionApp/Extensions/HostBuilderExtension.cs, src/GovUk.Education.ExploreEducationStatistics.Content.Search.FunctionApp/Extensions/ReleaseSearchableDocumentExtensions.cs, src/GovUk.Education.ExploreEducationStatistics.Content.Search.FunctionApp/Functions/CreateSearchableReleaseDocuments/CreateSearchableReleaseDocumentInAzureStorageFunction.cs, src/GovUk.Education.ExploreEducationStatistics.Content.Search.FunctionApp/Functions/CreateSearchableReleaseDocuments/Dtos/ReleasePublishedMessage.cs, src/GovUk.Education.ExploreEducationStatistics.Content.Search.FunctionApp/host.json
This PR makes some further tweaks to the Search Function App.
It renames the metadata keys in SearchableDocumentAzureBlobMetadataKeys  to use underscores instead of hyphens to make them valid C# identifiers. See [metadata-key-and-value-names](https://learn.microsoft.com/en-us/rest/api/storageservices/naming-and-referencing-containers--blobs--and-metadata#metadata-key-and-value-names)
It appears that Azurite will allow metadata keys containing hyphens, but when uploading to Azure these are causing an error:
```
<Error><Code>InvalidMetadata</Code><Message>The metadata specified is invalid. It has characters that are not permitted.
```
If we using the Function App in its current state to upload a blob locally with Azurite and view the properties of that blob in Storage Explorer, a warning …
=> EES-5874 Further Search Function App tweaks

src/explore-education-statistics-admin/src/components/editable/EditableAccordionSection.tsx, src/explore-education-statistics-common/src/components/form/FormBaseInput.tsx
Fixes https://dfedigital.atlassian.net/browse/EES-5911
Autofocus attribute ensures that the input is focussed as soon as it is rendered (when the user clicks the 'Edit Section title' button.
n.b I have had to disable the eslint rule for the autofocus attribute as I don't think it is relevant for this - autofocus is expected behaviour and would be implemented by us manually if it wasn't handled by the browser and the `autofocus` attribute.
=> EES-5911 Move focus to input after clicking 'Edit Section title'

src/GovUk.Education.ExploreEducationStatistics.Content.Api.Tests/Controllers/ReleaseControllerTests.cs, src/GovUk.Education.ExploreEducationStatistics.Content.Services.Tests/PublicationServiceTests.cs, src/GovUk.Education.ExploreEducationStatistics.Content.Services/PublicationService.cs, src/GovUk.Education.ExploreEducationStatistics.Content.ViewModels/PublicationCacheViewModel.cs, src/GovUk.Education.ExploreEducationStatistics.Content.ViewModels/ReleaseSearchViewModel.cs
Put Publication Summary in the metadata of the search blob instead of Release Version.
This involves bringing the summary into the cache so we'll need a faffy deploy ticket to invalidate the caches.
=> EES-5874 Put Publication Summary in the metadata of the search blob instead of Release Version

src/GovUk.Education.ExploreEducationStatistics.Admin.Tests/Services/ManageContent/ManageContentPageServiceTests.cs, src/GovUk.Education.ExploreEducationStatistics.Admin.Tests/Services/PublicationServiceTests.cs, src/GovUk.Education.ExploreEducationStatistics.Admin.Tests/Services/ReleaseVersionServiceTests.cs
test: Fix failing unit tests by converting PublishScheduled in generated data to UK timezone with ConvertUtcToUkTimeZone to match how PublishScheduled is set up in the view model by MappingProfile which uses ConvertUtcToUkTimeZone
=> Cherry-picking various test fixes related to timezone issues

src/GovUk.Education.ExploreEducationStatistics.Public.Data.Api.Tests/Controllers/DataSetsControllerTests.cs, src/GovUk.Education.ExploreEducationStatistics.Public.Data.Api.Tests/Controllers/PublicationsControllerTests.cs, src/GovUk.Education.ExploreEducationStatistics.Public.Data.Api.Tests/Security/AuthorizationHandlers/QueryDataSetVersionAuthorizationHandlerTests.cs, src/GovUk.Education.ExploreEducationStatistics.Public.Data.Api.Tests/Security/AuthorizationHandlers/ViewDataSetAuthorizationHandlerTests.cs, src/GovUk.Education.ExploreEducationStatistics.Public.Data.Api.Tests/Security/AuthorizationHandlers/ViewDataSetVersionAuthorizationHandlerTests.cs, src/GovUk.Education.ExploreEducationStatistics.Public.Data.Api.Tests/TheoryData/DataSetStatusTheoryData.cs, src/GovUk.Education.ExploreEducationStatistics.Public.Data.Api/Security/AuthorizationHandlers/QueryDataSetVersionAuthorizationHandler.cs, src/GovUk.Education.ExploreEducationStatistics.Public.Data.Api/Security/AuthorizationHandlers/ViewDataSetAuthorizationHandler.cs, src/GovUk.Education.ExploreEducationStatistics.Public.Data.Api/Security/AuthorizationHandlers/ViewDataSetVersionAuthorizationHandler.cs, src/GovUk.Education.ExploreEducationStatistics.Public.Data.Api/Services/DataSetService.cs, src/GovUk.Education.ExploreEducationStatistics.Public.Data.Api/Services/Interfaces/IPreviewTokenService.cs, src/GovUk.Education.ExploreEducationStatistics.Public.Data.Api/Services/Interfaces/Security/IAuthorizationHandlerService.cs, src/GovUk.Education.ExploreEducationStatistics.Public.Data.Api/Services/PreviewTokenService.cs, src/GovUk.Education.ExploreEducationStatistics.Public.Data.Api/Services/Security/AuthorizationHandlerService.cs, src/GovUk.Education.ExploreEducationStatistics.Public.Data.Api/ViewModels/DataSetViewModels.cs, src/explore-education-statistics-admin/src/pages/release/data/ReleaseApiDataSetPreviewTokenPage.tsx, src/explore-education-statistics-admin/src/pages/release/data/__tests__/ReleaseApiDataSetPreviewTokenPage.test.tsx, src/explore-education-statistics-api-docs/source/openapi-v1.json
This hotfix PR fixes various issues around the usage of Preview Tokens and the Preview Token page.
Specifically this PR fixes:
The Preview Tokens page was using the draft DataSetVersion Id in the code example tabs (e.g. the cURL example shown in the screenshot below).
This PR fixes this to use the DataSet Id instead, as per all of the other examples on the page.
This PR also adds Jest tests around the checking of the URLs and code example block on this page.
Previously we had support for using Preview Tokens to call API endpoints when targeting specific DataSetVersions on the DataSet (by using the dataSetVersion query parameter that is included in all of the example endpoints on this page other than the Data set summary endpoint).
We would also get away with being able to call the Data …
=> EES-5913 - fix issues with using Preview Tokens on draft DataSets

infrastructure/templates/search/ci/azure-pipelines.yml, infrastructure/templates/search/ci/stages/deploy.yml
This PR makes changes to the Search infrastructure and app deploy pipeline:
It adds the Prod deploy stage to the pipeline, dependent on the Pre-Prod stage so that we can deploy to Prod.
It switches from using the variable groups `Search Infrastructure - Common` and `Search Infrastructure - <env>` to use `Common` and `Common - <env>` which are new variable groups we are creating. A few pipelines for different parts of the service are all going to share the same common variables so this avoids having lots of duplicate 'Common' variable groups across all the different areas.
=> EES-5899 Search infrastructure pipeline - Add Prod deploy stage and switch to common variable groups

.gitignore, azure-pipelines-main.yml, infrastructure/templates/search/ci/azure-pipelines-build.yml, infrastructure/templates/search/ci/azure-pipelines.yml, infrastructure/templates/search/ci/jobs/deploy-infrastructure.yml, infrastructure/templates/search/ci/jobs/deploy-search-docs-function-app.yml, src/Directory.Build.props, src/GovUk.Education.ExploreEducationStatistics.Common.Tests/Extensions/AssemblyExtensionTests.cs
This PR create a separate pipeline to do the build, test, and publishing steps of the Search solution which currently consists of the  Searchable Documents Azure Function application.
In future any other projects added to the Search solution can be built and published by this pipeline.
It it set up to trigger the existing Search infrastructure and application deployment pipeline created by https://github.com/dfe-analytical-services/explore-education-statistics/pull/5628.
Long build times and build failures in the main service build pipeline are currently delaying PR’s from being merged and delaying deployments of the infrastructure and Searchable Documents Azure Function application.
This new pipeline allows projects in the Search solution to be built, tested and deployed independently of …
=> EES-5959 Create a dedicated DevOps build pipeline for Search

src/explore-education-statistics-frontend/src/modules/data-catalogue/components/DataSetFileApiChangelog.tsx
When no Public API dataset version 'Public guidance notes' exist, users of the public frontend will see a ‘0' in the place where guidance notes would usually appear on the API dataset details page 'API data set changelog' section.
This PR fixes this.
=> EES-5967 Public API data set details page - Fixing bug where empty guidance notes appears as a `0`

src/GovUk.Education.ExploreEducationStatistics.Content.Search.FunctionApp.Tests/Builders/EventGridEventBuilder.cs, src/GovUk.Education.ExploreEducationStatistics.Content.Search.FunctionApp.Tests/Builders/FunctionContextBuilder.cs, src/GovUk.Education.ExploreEducationStatistics.Content.Search.FunctionApp.Tests/Builders/HeathCheckStrategyBuilder.cs, src/GovUk.Education.ExploreEducationStatistics.Content.Search.FunctionApp.Tests/Builders/LoggerBuilder.cs, src/GovUk.Education.ExploreEducationStatistics.Content.Search.FunctionApp.Tests/Clients/AzureSearch/SearchIndexClientTests.cs, src/GovUk.Education.ExploreEducationStatistics.Content.Search.FunctionApp.Tests/Functions/HealthChecks/HealthCheckFunctionTests.cs, src/GovUk.Education.ExploreEducationStatistics.Content.Search.FunctionApp.Tests/GovUk.Education.ExploreEducationStatistics.Content.Search.FunctionApp.Tests.csproj, src/GovUk.Education.ExploreEducationStatistics.Content.Search.FunctionApp.Tests/ProgramTests.cs, src/GovUk.Education.ExploreEducationStatistics.Content.Search.FunctionApp.Tests/Services/EventGridEventHandlerTests.cs, src/GovUk.Education.ExploreEducationStatistics.Content.Search.FunctionApp/Clients/AzureSearch/AzureSearchIndexerClientFactory.cs, src/GovUk.Education.ExploreEducationStatistics.Content.Search.FunctionApp/Clients/AzureSearch/AzureSearchIndexerClientWrapper.cs, src/GovUk.Education.ExploreEducationStatistics.Content.Search.FunctionApp/Clients/AzureSearch/IAzureSearchIndexerClient.cs, src/GovUk.Education.ExploreEducationStatistics.Content.Search.FunctionApp/Clients/AzureSearch/IAzureSearchIndexerClientFactory.cs, src/GovUk.Education.ExploreEducationStatistics.Content.Search.FunctionApp/Clients/AzureSearch/ISearchIndexClient.cs, src/GovUk.Education.ExploreEducationStatistics.Content.Search.FunctionApp/Clients/AzureSearch/SearchIndexClient.cs, src/GovUk.Education.ExploreEducationStatistics.Content.Search.FunctionApp/Extensions/HostBuilderExtension.cs, src/GovUk.Education.ExploreEducationStatistics.Content.Search.FunctionApp/Extensions/ObjectExtensions.cs, src/GovUk.Education.ExploreEducationStatistics.Content.Search.FunctionApp/Extensions/ServiceCollectionExtensions.cs, src/GovUk.Education.ExploreEducationStatistics.Content.Search.FunctionApp/Functions/CreateSearchableReleaseDocuments/CreateSearchableReleaseDocumentInAzureStorageFunction.cs, src/GovUk.Education.ExploreEducationStatistics.Content.Search.FunctionApp/Functions/CreateSearchableReleaseDocuments/Dtos/ReleasePublishedMessage.cs, src/GovUk.Education.ExploreEducationStatistics.Content.Search.FunctionApp/Functions/CreateSearchableReleaseDocuments/Dtos/ReleaseVersionPublishedEventDto.cs, src/GovUk.Education.ExploreEducationStatistics.Content.Search.FunctionApp/Functions/CreateSearchableReleaseDocuments/Dtos/SearchDocumentCreatedMessageDto.cs, src/GovUk.Education.ExploreEducationStatistics.Content.Search.FunctionApp/Functions/CreateSearchableReleaseDocuments/Dtos/SearchableDocumentCreatedMessageDto.cs, src/GovUk.Education.ExploreEducationStatistics.Content.Search.FunctionApp/Functions/HealthChecks/Strategies/AzureSearchHealthCheckStrategy.cs, src/GovUk.Education.ExploreEducationStatistics.Content.Search.FunctionApp/Functions/ReindexSearchDocuments/ReindexSearchDocumentsFunction.cs, src/GovUk.Education.ExploreEducationStatistics.Content.Search.FunctionApp/Functions/ReindexSearchableDocuments/ReindexSearchableDocumentsFunction.cs, src/GovUk.Education.ExploreEducationStatistics.Content.Search.FunctionApp/GovUk.Education.ExploreEducationStatistics.Content.Search.FunctionApp.csproj, src/GovUk.Education.ExploreEducationStatistics.Content.Search.FunctionApp/Options/AzureSearchOptions.cs, src/GovUk.Education.ExploreEducationStatistics.Content.Search.FunctionApp/Services/EventGridEventHandler.cs, src/GovUk.Education.ExploreEducationStatistics.Content.Search.FunctionApp/appsettings.Development.json
The publisher raises an event signalling that a new release version has been published.
This event is subscribed to and queues for processing by a Function App.
That function creates the searchable document in Azure and then places its own message into a new queue signalling that a new document has been created in Azure storage.
This work is to implement the next part of the process, which is to consume that message and trigger a reindex.
Note that I needed to correct the dto of the message arriving from the publisher since I forgot that it would of course be a payload wrapped in an event envelope.
I also added another healthcheck strategy which reports back on whether the indexer is configured and can be reached.
=> Implement reindexer function

src/explore-education-statistics-admin/src/pages/release/data/components/AncillaryFileSummaryList.tsx, src/explore-education-statistics-admin/src/pages/release/data/components/ReleaseFileUploadsSection.tsx
This PR refactors the "delete supporting file upload" modal to be rendered for each file rather than shared in the top level section. 
This lets us use the `triggerButton` for handling focus, so focus can be restored to the 'Delete file' button when the modal is closed.
=> EES-5943 Fix delete ancillary file modal focus restoration

src/GovUk.Education.ExploreEducationStatistics.Admin.Tests/Controllers/Api/Public.Data/DataSetVersionsControllerTests.cs, src/GovUk.Education.ExploreEducationStatistics.Admin/Controllers/Api/Public.Data/DataSetVersionsController.cs, src/GovUk.Education.ExploreEducationStatistics.Admin/Mappings/MappingProfiles.cs, src/GovUk.Education.ExploreEducationStatistics.Admin/Services/Interfaces/Public.Data/IDataSetVersionService.cs, src/GovUk.Education.ExploreEducationStatistics.Admin/Services/Public.Data/DataSetVersionService.cs, src/GovUk.Education.ExploreEducationStatistics.Admin/Startup.cs, src/GovUk.Education.ExploreEducationStatistics.Admin/ViewModels/Public.Data/DataSetVersionViewModels.cs, src/explore-education-statistics-admin/src/pages/release/data/ReleaseApiDataSetChangelogPage.tsx, src/explore-education-statistics-admin/src/pages/release/data/__tests__/ReleaseApiDataSetChangelogPage.test.tsx, src/explore-education-statistics-admin/src/queries/apiDataSetVersionQueries.ts, src/explore-education-statistics-admin/src/services/apiDataSetService.ts, src/explore-education-statistics-admin/src/services/apiDataSetVersionService.ts
Previously, when an admin visited the Public API version history page for a particular API data set, and clicked to view the changelog for versions `1.1` and above, they were sometimes displayed with the incorrect version number and version 'type' (`Major`/`Minor`).
This was because the frontend had [some logic](https://github.com/dfe-analytical-services/explore-education-statistics/pull/5700/files#:~:text=const%20dataSetVersion%20%3D,%3F.latestLiveVersion%3B) which only ever showed the version number and type for either the **latest live** version of the data set, or the current **draft** version, depending on whether or not the version you selected is the **draft** one or not. It didn't display the details for the version you have specifically requested (**caveat** - it DID do this …
=> EES-5934 Fixing Admin Public API Data Set Changelog page

infrastructure/templates/common/components/containerisedFunctionApp.bicep, infrastructure/templates/public-api/components/storageAccount.bicep, infrastructure/templates/screener/application/screenerApplicationInsights.bicep, infrastructure/templates/screener/application/screenerContainerisedFunctionApp.bicep, infrastructure/templates/screener/bicepconfig.json, infrastructure/templates/screener/ci/azure-pipelines.yml, infrastructure/templates/screener/ci/jobs/deploy-infrastructure.yml, infrastructure/templates/screener/ci/jobs/deploy-screener-function-app.yml, infrastructure/templates/screener/ci/stages/deploy.yml, infrastructure/templates/screener/ci/tasks/deploy-bicep.yml, infrastructure/templates/screener/main.bicep, infrastructure/templates/screener/parameters/main-dev.bicepparam, infrastructure/templates/screener/parameters/main-preprod.bicepparam, infrastructure/templates/screener/parameters/main-prod.bicepparam, infrastructure/templates/screener/parameters/main-test.bicepparam, infrastructure/templates/screener/types.bicep, infrastructure/templates/template.json
This PR adds new infrastructure for implementing the data screener API, and contains Bicep templates defining the infrastructure for a containerised Azure Function app.
As per [Ben's recent PR for the site-wide search infrastructure](https://github.com/dfe-analytical-services/explore-education-statistics/pull/5673), this PR contains references to resources defined in the public-api directory - this is to avoid refactoring or changing directory structures during a key point in the Public API's initial release.
This PR adds a new containerisedFunctionApp.bicep template since we don't currently have this in our library of components. This is added to the 'common' folder so it can be used for any future work which may need to deploy function code to Azure as a container - it was required in …
=> EES-5881: Add templates for containerised Azure Function.

src/explore-education-statistics-admin/src/pages/release/datablocks/components/DataBlockPageReadOnlyTabs.tsx, src/explore-education-statistics-common/src/modules/charts/components/MapBlock.tsx, src/explore-education-statistics-common/src/modules/find-statistics/components/DataBlockTabs.tsx
This allows keyboard users to skip to/from the end of the map to/from the beginning, so they don't have to tab through all of the map regions to proceed down the page
=> EES-5938 Add skip links to bypass map regions

src/explore-education-statistics-common/src/modules/charts/components/MapGeoJSON.tsx
This PR fixes an issue where tooltips were sometimes not visible when tabbing through regions of a map block.
We detect tab presses and zoom the map out when this happens.
N.B I have also added handling for user pressing 'Enter' when focussing on a region, to 'select' the region and display the key stat block. If you think that is out of scope for this ticket or otherwise not wanted, let me know and I will remove it.
=> EES-5910 Ensure tooltips visible when tabbing through map regions

src/explore-education-statistics-admin/src/pages/publication/components/PublicationDetailsForm.tsx, src/explore-education-statistics-admin/src/queries/releaseDataFileQueries.ts
This PR fixes focus restoration when the 'edit publication' modal is closed in the admin site - returning focus to the modal trigger button.
Instead of refactoring to use 'triggerButton' like we do on other modals, we handle focus manually by focussing the button via a ref.
This is to keep the form validation/submit behaviour working as it currently does.
=> EES-5960 update publication modal focus close fix

azure-pipelines-main.yml, renovate.json
This PR updates the Renovate config to pin AspectInjector version to 2.8.1 for macOS compatibility.
It also excludes the renovate.json from the DevOps build pipeline CI and PR triggers.
=> EES-5981 Update Renovate config to pin AspectInjector version

renovate.json
This PR changes the Renovate config to exclude packages which need their major versions to be in sync with the .NET version or the EF Core version.
It also attempts to fix the AspectInjector package exclude which was added by #5722.
=> EES-5981 Update Renovate config to add more exclusions

.config/dotnet-tools.json, global.json
This PR updates the minimum Dotnet SDK version from 8.0.402 to 8.0.407.
It also updates to use the latest Entity Framework Core Tools (which should always be safe to update to the latest version because it is backwards compatible).
=> EES-5981 Update Dotnet SDK version

src/GovUk.Education.ExploreEducationStatistics.Common.Tests/Services/EventGrid/ConfiguredEventGridClientFactoryMockBuilder.cs, src/GovUk.Education.ExploreEducationStatistics.Common.Tests/Services/EventGrid/EventGridClientMockBuilder.cs, src/GovUk.Education.ExploreEducationStatistics.Publisher.Tests/Builders/Models/ReleaseVersionBuilder.cs, src/GovUk.Education.ExploreEducationStatistics.Publisher.Tests/Builders/Services/ContentDbContextMockBuilder.cs, src/GovUk.Education.ExploreEducationStatistics.Publisher.Tests/Builders/Services/ContentServiceMockBuilder.cs, src/GovUk.Education.ExploreEducationStatistics.Publisher.Tests/Builders/Services/DataSetPublishingServiceMockBuilder.cs, src/GovUk.Education.ExploreEducationStatistics.Publisher.Tests/Builders/Services/EventRaiserServiceMockBuilder.cs, src/GovUk.Education.ExploreEducationStatistics.Publisher.Tests/Builders/Services/MethodologyServiceMockBuilder.cs, src/GovUk.Education.ExploreEducationStatistics.Publisher.Tests/Builders/Services/NotificationsServiceMockBuilder.cs, src/GovUk.Education.ExploreEducationStatistics.Publisher.Tests/Builders/Services/PublicationCacheServiceMockBuilder.cs, src/GovUk.Education.ExploreEducationStatistics.Publisher.Tests/Builders/Services/RedirectsCacheServiceMockBuilder.cs, src/GovUk.Education.ExploreEducationStatistics.Publisher.Tests/Builders/Services/ReleasePublishingStatusServiceMockBuilder.cs, src/GovUk.Education.ExploreEducationStatistics.Publisher.Tests/Builders/Services/ReleaseServiceMockBuilder.cs, src/GovUk.Education.ExploreEducationStatistics.Publisher.Tests/Services/PublisherEventRaiserServiceTests.cs, src/GovUk.Education.ExploreEducationStatistics.Publisher.Tests/Services/PublishingCompletionServiceTests.cs
Renamed xxxBuilder to xxxMockBuilder - but removed MockBuilder suffix from usages - since all dependencies in the unit tests are mocks so seems superfluous to keep stating it.
Cleaned up PublishingCompletionServiceTests
=> Cleaning up unit tests

infrastructure/templates/public-api/components/storageAccount.bicep, infrastructure/templates/search/application/indexes/index-1.json, infrastructure/templates/search/application/searchDocsFunction.bicep, infrastructure/templates/search/application/searchService.bicep, infrastructure/templates/search/ci/azure-pipelines.yml, infrastructure/templates/search/ci/jobs/deploy-infrastructure.yml, infrastructure/templates/search/ci/tasks/deploy-bicep.yml, infrastructure/templates/search/components/searchService.bicep, infrastructure/templates/search/components/searchServiceConfig.bicep, infrastructure/templates/search/main.bicep, infrastructure/templates/search/scripts/SetupSearchService.ps1
This PR adds the Bicep infrastructure to create or update a Azure AI Search data source, index and indexer. The result of this is that we now have an Azure AI Search API endpoint that we can run search queries against.
It builds on #5668 which added the infrastructure to create the Azure AI Search Service and Search Storage account/container but did not go as far as configuring the Storage container as a data source within the Azure AI Search, or define the index or indexer.
There's no Bicep template support for Azure AI Search data plane operations like creating an data source or an index.
Instead, we create an Azure Deployment Script resource to use data plane operations of the Azure AI Search REST API. The Deployment Script uses a Container Instance to execute a Powershell script from …
=> EES-5940 Add infrastructure to deploy an Azure AI Search data source, index and indexer

src/explore-education-statistics-frontend/src/modules/find-statistics/PublicationReleasePage.tsx
This PR ensures that if a user visits a base publication URL they will be redirected to the latest release URL for that publication.
E.g. if user visits `https://base/find-statistics/[publication-slug]` they will be redirected to `https://base/find-statistics/[publication-slug]/[latest-release-slug]`.
N.B I had to change the type on L580 from `Props` as the TS compiler was complaining.
- it wouldn't complain if `getServerSideProps` wasn't wrapped with the `withAxiosHandler` HOC
- it wouldn't complain if we didn't return a redirect.
- it wouldn't complain if I amended the withAxiosHandler type annotations, but this would have wider effects on the codebase which I didn't want to introduce!
Any solution or alternative, let me know.
=> Ees 5951 redirect publication to latest release

src/GovUk.Education.ExploreEducationStatistics.Admin.Tests/MockBuilders/AdminEventRaiserServiceMockBuilder.cs, src/GovUk.Education.ExploreEducationStatistics.Admin.Tests/MockBuilders/ThemeBuilder.cs, src/GovUk.Education.ExploreEducationStatistics.Admin.Tests/MockBuilders/ThemeMockBuilder.cs, src/GovUk.Education.ExploreEducationStatistics.Admin.Tests/Services/AdminEventRaiserServiceTests.cs, src/GovUk.Education.ExploreEducationStatistics.Admin.Tests/Services/ThemeServicePermissionTests.cs, src/GovUk.Education.ExploreEducationStatistics.Admin.Tests/Services/ThemeServiceTests.cs, src/GovUk.Education.ExploreEducationStatistics.Admin/Events/ThemeChangedEventDto.cs, src/GovUk.Education.ExploreEducationStatistics.Admin/Services/AdminEventRaiserService.cs, src/GovUk.Education.ExploreEducationStatistics.Admin/Services/Interfaces/IAdminEventRaiserService.cs, src/GovUk.Education.ExploreEducationStatistics.Admin/Services/ThemeService.cs
As part of the on-going work with the new Search functionality, we need to signal whenever anything changes that affects the data that is stored and indexed by the search indexer.
The Searchable Document representation of a Release Version contains some Theme information. Therefore, if a Theme changes, we need to update any Searchable Documents that are a part of that Theme.
In this PR, we are raising an event when a Theme is updated. A future piece of work will subscribe to that event, look up the publications and therefore release versions that fall under that theme, and have the corresponding Searchable Documents updated.
=> When a theme is updated, raise a ThemeUpdated event

src/explore-education-statistics-frontend/src/middleware.ts, src/explore-education-statistics-frontend/src/middleware/pages/noIndexPagesWithParams.ts
This PR adds middleware for the frontend site to prevent duplicate indexing of pages with different query params.
We check if there are query params present in the request, and add a `noindex` header to the response if there are, unless the only query param is `page`, which we still want to be indexed.
I considered adding a noindex meta tag to the document `head` as an alternative, but this would need to be done in multiple templates in `getServerSideProps` and didn't seem as clean or global as a solution.
=> EES-5969 SEO noindex for query params

src/explore-education-statistics-admin/src/pages/publication/components/PublicationContactForm.tsx
This PR fixes a focus issue - ensuring that focus is returned to the 'Update contact details' button that triggers the modal when the modal is closed.
=> EES-5961 Focus contact form modal trigger button on modal close

src/explore-education-statistics-admin/src/pages/release/components/ReleaseStatusForm.tsx, src/explore-education-statistics-admin/src/pages/release/pre-release/components/PreReleaseUserAccessForm.tsx
Fix focus issue - when closing the 'update status' modal (for scheduling publishing of a release), focus is now returned to the trigger button.
Also addresses EES-5989 - Returning focus to PreRelease User Access Modal trigger button when modal closes.
=> EES-5986 Ensure focus is returned to modal trigger for publish date modal

infrastructure/templates/common/components/functionApp.bicep, infrastructure/templates/common/components/storageAccountRoleAssignment.bicep, infrastructure/templates/search/application/searchDocsFunction.bicep, infrastructure/templates/search/application/searchService.bicep, infrastructure/templates/search/components/searchServiceConfig.bicep, infrastructure/templates/search/components/searchServiceRoleAssignment.bicep, infrastructure/templates/search/main.bicep, infrastructure/templates/search/types.bicep, src/GovUk.Education.ExploreEducationStatistics.Content.Search.FunctionApp.Tests/Clients/AzureSearch/SearchIndexClientTests.cs, src/GovUk.Education.ExploreEducationStatistics.Content.Search.FunctionApp.Tests/ProgramTests.cs, src/GovUk.Education.ExploreEducationStatistics.Content.Search.FunctionApp/Clients/AzureSearch/AzureSearchIndexerClientWrapper.cs, src/GovUk.Education.ExploreEducationStatistics.Content.Search.FunctionApp/Clients/AzureSearch/IAzureSearchIndexerClient.cs, src/GovUk.Education.ExploreEducationStatistics.Content.Search.FunctionApp/Clients/AzureSearch/SearchIndexClient.cs, src/GovUk.Education.ExploreEducationStatistics.Content.Search.FunctionApp/Extensions/ServiceCollectionExtensions.cs, src/GovUk.Education.ExploreEducationStatistics.Content.Search.FunctionApp/Functions/HealthChecks/Strategies/AzureSearchHealthCheckStrategy.cs, src/GovUk.Education.ExploreEducationStatistics.Content.Search.FunctionApp/Options/AzureSearchOptions.cs, src/GovUk.Education.ExploreEducationStatistics.Content.Search.FunctionApp/appsettings.Development.json
This PR makes infrastructure changes for the Search Azure Function App to support changes made to it in EES-5875 by #5703. These changes are possible now that the configuration for the Azure AI Search resource was added by #5733.
- Rename the `indexName` app setting and parameter names to `indexerName` to match Azure's SearchIndexerClient class since the operation to retrieve indexer information requires the indexer name rather than the index name.
- Configure the app with the Azure AI search REST API endpoint.
- Configure the app with the Azure AI search indexer name.
- Enable the app's search indexer health check by uncommenting `AzureSearchHealthCheckStrategy`.
- Assign the app's system managed identity the 'Search Service Contributor' role required to list indexers.
- Break out a new …
=> EES-5974 infrastructure changes for search function app related to EES-5875

src/explore-education-statistics-admin/src/pages/release/datablocks/components/chart/ChartBuilder.tsx
Fix focus issue - when closing the 'delete chart' modal, focus is now returned to the trigger button.
=> EES-5985 Return focus to trigger btn on chart builder delete modal close

src/GovUk.Education.ExploreEducationStatistics.Admin/GovUk.Education.ExploreEducationStatistics.Admin.csproj, src/GovUk.Education.ExploreEducationStatistics.Analytics.Consumer/GovUk.Education.ExploreEducationStatistics.Analytics.Consumer.csproj, src/GovUk.Education.ExploreEducationStatistics.Common.Tests/GovUk.Education.ExploreEducationStatistics.Common.Tests.csproj, src/GovUk.Education.ExploreEducationStatistics.Common/GovUk.Education.ExploreEducationStatistics.Common.csproj, src/GovUk.Education.ExploreEducationStatistics.Data.Api/GovUk.Education.ExploreEducationStatistics.Data.Api.csproj, src/GovUk.Education.ExploreEducationStatistics.Data.Processor/GovUk.Education.ExploreEducationStatistics.Data.Processor.csproj, src/GovUk.Education.ExploreEducationStatistics.Notifier/GovUk.Education.ExploreEducationStatistics.Notifier.csproj, src/GovUk.Education.ExploreEducationStatistics.Public.Data.Api/GovUk.Education.ExploreEducationStatistics.Public.Data.Api.csproj, src/GovUk.Education.ExploreEducationStatistics.Public.Data.Model/GovUk.Education.ExploreEducationStatistics.Public.Data.Model.csproj, src/GovUk.Education.ExploreEducationStatistics.Public.Data.Processor/GovUk.Education.ExploreEducationStatistics.Public.Data.Processor.csproj, src/GovUk.Education.ExploreEducationStatistics.Publisher/GovUk.Education.ExploreEducationStatistics.Publisher.csproj
Lock all of the projects that had an implicit reference to System.Text.Json 7.0.0 to 8.0.5. 
The vulnerability was fixed in 8.0.4. See https://github.com/advisories/GHSA-hh2w-p6rv-4g7w
=> Fix vulnerability in System.Text.Json

src/explore-education-statistics-common/src/components/__tests__/Button.test.tsx, src/explore-education-statistics-common/src/components/__tests__/ButtonText.test.tsx, src/explore-education-statistics-common/src/components/__tests__/ModalConfirm.test.tsx, src/explore-education-statistics-common/src/hooks/useButton.ts
Don't set aria-disabled to true during 'double click prevention' phase, as this causes screen readers to announce 'unavailable' immediately on button click.
`aria-disabled` can still be passed in as a prop, as well as `disabled`
=> EES-5912 Prevent screenreader announcing unavailable after button click

src/explore-education-statistics-admin/src/components/form/FormEditor.tsx, src/explore-education-statistics-admin/src/pages/release/datablocks/components/chart/ChartBuilder.tsx, src/explore-education-statistics-common/src/modules/charts/components/MapGeoJSON.tsx, src/explore-education-statistics-common/src/modules/find-statistics/components/KeyStatTile.tsx, src/explore-education-statistics-frontend/src/modules/find-statistics/PublicationReleasePage.tsx
This PR returns focus back to the editor when an 'add glossary link' or 'add featured table' modal is closed.
It also fixes various misc lint warnings.
=> EES-5988 ckeditor insert modals focus on close

src/explore-education-statistics-common/src/modules/table-tool/components/LocationFiltersForm.tsx
This PR fixes the id of the 'locations' fieldset, so that the related error message links to the correct fieldset.
=> EES-5949 Fix fieldset id to match error target id

src/GovUk.Education.ExploreEducationStatistics.Admin.Tests/MockBuilders/AdminEventRaiserServiceMockBuilder.cs, src/GovUk.Education.ExploreEducationStatistics.Admin.Tests/Services/PublicationServicePermissionTests.cs, src/GovUk.Education.ExploreEducationStatistics.Admin.Tests/Services/PublicationServiceTests.cs, src/GovUk.Education.ExploreEducationStatistics.Admin.Tests/Services/ReleaseServiceTests.cs, src/GovUk.Education.ExploreEducationStatistics.Admin.Tests/Services/ThemeServiceTests.cs, src/GovUk.Education.ExploreEducationStatistics.Admin/Events/PublicationChangedEventDto.cs, src/GovUk.Education.ExploreEducationStatistics.Admin/Events/ReleaseSlugChangedEventDto.cs, src/GovUk.Education.ExploreEducationStatistics.Admin/Events/ThemeChangedEventDto.cs, src/GovUk.Education.ExploreEducationStatistics.Admin/Services/AdminEventRaiserService.cs, src/GovUk.Education.ExploreEducationStatistics.Admin/Services/Interfaces/IAdminEventRaiserService.cs, src/GovUk.Education.ExploreEducationStatistics.Admin/Services/PublicationService.cs, src/GovUk.Education.ExploreEducationStatistics.Admin/appsettings.Development.json, src/GovUk.Education.ExploreEducationStatistics.Publisher/Events/ReleaseVersionPublishedEventDto.cs, src/GovUk.Education.ExploreEducationStatistics.Publisher/appsettings.example.json
Note: There are 4 steps to this PR which I have left as easy to understand separate commits
1. Renamed Mock Builder asserts from xxCalled to xxRaised to refer to the events instead of the methods
2. Very subtle change: I had originally named the Topics xxxChanges to signify that it was a stream of changes. But it's too easy to transpose xxxChanged which is the name of the events and event handler etc
3. Add new Event Raiser function - to raise a Publication Changed event
4. Utilise the new event in Publication Service. Update some tests to also check for the events (or lack of them where appropriate).
=> Ees 5954 On Publication Changed

src/GovUk.Education.ExploreEducationStatistics.Content.Search.FunctionApp.Tests/Functions/OnPublicationChanged/OnReleaseSlugChangedFunctionTests.cs, src/GovUk.Education.ExploreEducationStatistics.Content.Search.FunctionApp.Tests/ProgramTests.cs, src/GovUk.Education.ExploreEducationStatistics.Content.Search.FunctionApp/Extensions/HostBuilderExtension.cs, src/GovUk.Education.ExploreEducationStatistics.Content.Search.FunctionApp/Functions/OnPublicationChanged/Dtos/PublicationChangedEventDto.cs, src/GovUk.Education.ExploreEducationStatistics.Content.Search.FunctionApp/Functions/OnPublicationChanged/OnPublicationChangedFunction.cs, src/GovUk.Education.ExploreEducationStatistics.Content.Search.FunctionApp/local.settings.json
Added the event handler azure function to consume the PublicationChanged event and output a refresh searchable document command.
Also, refactored the unit test that ensures the functions can be resolved to automagically discover the functions from the assembly. This saves the developer from having to remember to manually add a corresponding test for any new functions.
=> Ees 5954 On Publication Changed - Azure Function

src/GovUk.Education.ExploreEducationStatistics.Content.Search.FunctionApp.Tests/Functions/OnPublicationLatestPublishedReleaseVersionChanged/OnPublicationLatestPublishedReleaseVersionChangedFunctionTests.cs, src/GovUk.Education.ExploreEducationStatistics.Content.Search.FunctionApp/Functions/OnPublicationLatestPublishedReleaseVersionChanged/Dtos/PublicationLatestPublishedReleaseVersionChangedEventDto.cs, src/GovUk.Education.ExploreEducationStatistics.Content.Search.FunctionApp/Functions/OnPublicationLatestPublishedReleaseVersionChanged/OnPublicationLatestPublishedReleaseVersionChangedFunction.cs, src/GovUk.Education.ExploreEducationStatistics.Content.Search.FunctionApp/local.settings.json
Another event being raised by the admin system to catch. This time, the event is for when the latest published release version has changed for a publication.
=> EES-5955 - On publication latest published release version changed function

infrastructure/templates/search/application/searchDocsFunction.bicep
This PR follows on from https://github.com/dfe-analytical-services/explore-education-statistics/pull/5748 by making an infrastructure change to the Search Azure Function App to support changes made to it in EES-5954 by https://github.com/dfe-analytical-services/explore-education-statistics/pull/5756 and EES-5955 by https://github.com/dfe-analytical-services/explore-education-statistics/pull/5766.
This change adds `PublicationChangedQueueName` and `PublicationLatestPublishedReleaseVersionChangedQueueName` to the app settings, and creates the queues `publication-changed-queue` and `publication-latest-published-release-version-changed-queue` in the app's dedicated storage account queue service.
=> EES-5974 Infrastructure changes for search function app related to EES-5954 and EES-5955

src/GovUk.Education.ExploreEducationStatistics.Admin.Tests/MockBuilders/AdminEventRaiserServiceMockBuilder.cs, src/GovUk.Education.ExploreEducationStatistics.Admin.Tests/Services/PublicationServiceTests.cs, src/GovUk.Education.ExploreEducationStatistics.Admin/Events/PublicationLatestPublishedReleaseVersionChangedEventDto.cs, src/GovUk.Education.ExploreEducationStatistics.Admin/Services/AdminEventRaiserService.cs, src/GovUk.Education.ExploreEducationStatistics.Admin/Services/Interfaces/IAdminEventRaiserService.cs, src/GovUk.Education.ExploreEducationStatistics.Admin/Services/PublicationService.cs
The new search is based on the latest release of a publication. In our continuing adventures of event raising, another way in which the latest release can change is if the releases are reordered. This would mean that the search would need to pick up the new latest release if it has changed.
As part of this, I've made the event more specific to "publication latest release changed" instead of a generic "publication changed" which would indicate that anything had changed.
=> Ees 5955 - On release series change

src/explore-education-statistics-common/src/utils/file/__tests__/sanitiseFileName.test.ts, src/explore-education-statistics-common/src/utils/file/downloadFile.ts, src/explore-education-statistics-common/src/utils/file/sanitiseFileName.ts
Removes disallowed characters from the file names for downloads. This fixes a bug when exporting charts with titles containing special characters.
=> EES-6020 sanitise download file names

infrastructure/templates/common/components/event-grid/eventGridCustomTopic.bicep, infrastructure/templates/common/components/event-grid/eventGridCustomTopicQueueSubscription.bicep, infrastructure/templates/common/components/event-grid/eventGridMessaging.bicep, infrastructure/templates/search/application/searchDocsFunction.bicep, infrastructure/templates/search/application/searchDocsFunctionEventSubscriptions.bicep, infrastructure/templates/search/main.bicep, infrastructure/templates/search/types.bicep
This PR follows on from https://github.com/dfe-analytical-services/explore-education-statistics/pull/5768 which added Event Grid topics that the Admin and Publisher will use to publish events when certain conditions occur.
This PR subscribes the Search Function app to these topics.
Because the functions in the Search Function app have been configured to use queue trigger bindings rather than Event Grid trigger bindings, the Event Grid subscriptions are created using the storage queues as their destinations.
=> EES-5952 Add infrastructure for Event Grid topic subscriptions

infrastructure/templates/template.json
This PR makes an infrastructure change to the Publisher function app settings to support changes made to it in EES-5908 by #5694 and #5754. These added the ability to publish events to an Event Grid custom topic.
This PR adds the following app settings:
- `EventGrid__EventTopics__0__Key` - `ReleaseVersionChangedEvent`
- `EventGrid__EventTopics__0__TopicEndpoint` - `<Event Grid custom topic endpoint>`
The endpoint value references the endpoint of the `s101[d|t|p][01|02]-ees-evgt-release-version-changed` topic resource. It is set conditionally depending on whether the topic exists, since it is not deployed to all environments yet.
=> EES-5973 Infrastructure changes for Publisher related to EES-5908

tests/robot-tests/tests/general_public/prod_only/old_fast_track.robot
Added UI test `old_fast_track.robot` for creating a permalink from non latest data and visiting it 
Jira ticket: [EES-5966](https://dfedigital.atlassian.net/browse/EES-5966)
=> EES-5966: Add UI test for permalink generation from non-latest data

src/GovUk.Education.ExploreEducationStatistics.Analytics.Consumer.Tests/Functions/ConsumePublicApiQueriesFunctionTests.cs, src/GovUk.Education.ExploreEducationStatistics.Analytics.Consumer.Tests/TestAnalyticsPathResolver.cs, src/GovUk.Education.ExploreEducationStatistics.Analytics.Consumer/Functions/ConsumePublicApiQueriesFunction.cs, src/GovUk.Education.ExploreEducationStatistics.Analytics.Consumer/Functions/HealthCheckFunctions.cs, src/GovUk.Education.ExploreEducationStatistics.Analytics.Consumer/GovUk.Education.ExploreEducationStatistics.Analytics.Consumer.csproj, src/GovUk.Education.ExploreEducationStatistics.Analytics.Consumer/Options/AnalyticsOptions.cs, src/GovUk.Education.ExploreEducationStatistics.Analytics.Consumer/ProcessorHostBuilder.cs, src/GovUk.Education.ExploreEducationStatistics.Analytics.Consumer/Program.cs, src/GovUk.Education.ExploreEducationStatistics.Analytics.Consumer/Properties/launchSettings.json, src/GovUk.Education.ExploreEducationStatistics.Analytics.Consumer/Services/AnalyticsPathResolver.cs, src/GovUk.Education.ExploreEducationStatistics.Analytics.Consumer/Services/Interfaces/IAnalyticsPathResolver.cs
This PR remove "Requests" from the "Analytics.Consumer" namespace, so the namespace matches the directory name for the project.
=> EES-6026 Remove Requests from Analytics.Consumer namespace

tests/robot-tests/tests/libs/admin/manage-content-common.robot
CK Editor version was recently updated, which updated the aria-label of the editor element.
Our robot test `get editor` selector was using the old label, so I have updated the selector to match the new one.
Old aria-label: `Editor editing area: main`
New aria-label: `Editor editing area: main. Press Alt+0 for help.`
The new selector should cover cases if ever the a11y help plugin is not present for the editor, too.
=> EES-6029 Update robot test after ck editor version update

infrastructure/templates/search/application/searchDocsFunction.bicep, infrastructure/templates/search/application/searchDocsFunctionEventSubscriptions.bicep, infrastructure/templates/search/types.bicep
This PR
* Corrects the name and event type filter of the `release-version-published` event queue subscription.
Corresponding with the changes in in https://github.com/dfe-analytical-services/explore-education-statistics/pull/5786:
* Renames the subscription and event type filter of the `publication-latest-published-release-changed` queue subscription to `publication-latest-published-release-reordered`.
* Renames the Search Function App's storage account queue `publication-latest-published-release-version-changed-queue` to `publication-latest-published-release-reordered-queue`.
* Changes the Search Function App's app setting `PublicationLatestPublishedReleaseVersionChangedQueueName` to `PublicationLatestPublishedReleaseReorderedQueueName`.
=> EES-5952 Rename subscriptions, event type filters and a queue

src/GovUk.Education.ExploreEducationStatistics.Admin.Tests/Services/AdminEventRaiserTests.cs, src/GovUk.Education.ExploreEducationStatistics.Admin/Events/PublicationChangedEvent.cs, src/GovUk.Education.ExploreEducationStatistics.Admin/Events/PublicationLatestPublishedReleaseReorderedEvent.cs, src/GovUk.Education.ExploreEducationStatistics.Admin/Events/ReleaseSlugChangedEvent.cs, src/GovUk.Education.ExploreEducationStatistics.Admin/Events/ThemeChangedEvent.cs, src/GovUk.Education.ExploreEducationStatistics.Admin/Services/AdminEventRaiser.cs, src/GovUk.Education.ExploreEducationStatistics.Common.Tests/Services/EventGrid/EventRaiserMockBuilder.cs, src/GovUk.Education.ExploreEducationStatistics.Common.Tests/Services/EventGrid/EventRaiserTests.cs, src/GovUk.Education.ExploreEducationStatistics.Common/Extensions/ServiceCollectionExtensions.cs, src/GovUk.Education.ExploreEducationStatistics.Common/Services/EventGrid/EventRaiser.cs, src/GovUk.Education.ExploreEducationStatistics.Common/Services/EventGrid/IEvent.cs, src/GovUk.Education.ExploreEducationStatistics.Common/Services/EventGrid/IEventRaiser.cs, src/GovUk.Education.ExploreEducationStatistics.Publisher.Tests/Builders/Services/PublisherEventRaiserMockBuilder.cs, src/GovUk.Education.ExploreEducationStatistics.Publisher.Tests/Services/PublisherEventRaiserTests.cs, src/GovUk.Education.ExploreEducationStatistics.Publisher.Tests/Services/PublishingCompletionServiceTests.cs, src/GovUk.Education.ExploreEducationStatistics.Publisher/Events/ReleaseVersionPublishedEvent.cs, src/GovUk.Education.ExploreEducationStatistics.Publisher/Services/Interfaces/IPublisherEventRaiser.cs, src/GovUk.Education.ExploreEducationStatistics.Publisher/Services/PublisherEventRaiser.cs
As part of writing up my documentation on using and raising Event Grid Events, I realised it could be simplified even further. Hence this refactor, which strips out everything from the specific AdminEventRaiser and PublisherEventRaiser into a common IEventRaiser dependency. The specific event raisers now simply create the event and pass it to the new IEventRaiser. Super simple.
=> EES-5791 Event Grid Events

src/explore-education-statistics-admin/src/pages/methodology/edit-methodology/content/components/MethodologyAccordion.tsx, src/explore-education-statistics-admin/src/pages/methodology/edit-methodology/content/components/MethodologyAccordionSection.tsx, src/explore-education-statistics-admin/src/pages/methodology/edit-methodology/content/context/useMethodologyContentActions.ts, src/explore-education-statistics-admin/src/pages/release/content/components/DataBlockSelectForm.tsx, src/explore-education-statistics-admin/src/pages/release/content/components/ReleaseContentAccordion.tsx, src/explore-education-statistics-admin/src/pages/release/content/components/ReleaseContentAccordionSection.tsx, src/explore-education-statistics-admin/src/pages/release/content/contexts/useReleaseContentActions.ts, src/explore-education-statistics-common/src/components/form/FormSelect.tsx
This PR fixes multiple focus-related issues for the release and methodology content pages. 
Currently, many buttons which add items or show/close modals don't move the focus, so screen reader users can't see any change has happened, and keyboard users have to tab to access the next logical action.
- When adding a new content **section**, move focus to the added section accordion item, ready to expand it.
- When adding a **data block** to a section, move focus to the newly-appeared data block select (this change affects more places but all with this desired behaviour)
- When closing the **embed URL modal** on cancel or escape, move focus back to the 'Embed a URL' button
- When adding a new **text block**, move focus to the added block's 'Edit block' button, ready to edit the new block.
=> EES-5939 'add block/section' button focus behaviour

infrastructure/parameters/dev.parameters.json
This PR enables Event Grid events in the dev environment following creation and testing of the infrastructure for them in the following PR's:
- https://github.com/dfe-analytical-services/explore-education-statistics/pull/5768
- https://github.com/dfe-analytical-services/explore-education-statistics/pull/5773
- https://github.com/dfe-analytical-services/explore-education-statistics/pull/5788
- https://github.com/dfe-analytical-services/explore-education-statistics/pull/5771
- https://github.com/dfe-analytical-services/explore-education-statistics/pull/5772
- https://github.com/dfe-analytical-services/explore-education-statistics/pull/5789
The events are enabled by removing the `eventGridTopicsExist` parameter override from `dev.parameters.json` which has a default value of `true`.
This …
=> EES-5952 Enable Event Grid events in the dev environment

src/explore-education-statistics-admin/src/styles/_all.scss, src/explore-education-statistics-admin/src/styles/_ckeditor.scss
This PR fixes some overflow issues related to the recently-added CKEditor accessibility modal.
1 - Content was overflowing the modal container on small viewports
2 - Page could be scrolled after scrolling through the modal content, which made the modal disappear.
For more context - https://dfedigital.atlassian.net/browse/EES-5948?focusedCommentId=109935
=> EES-5948 ckeditor a11y modal scroll

infrastructure/templates/analytics/ci/jobs/deploy-infrastructure.yml, infrastructure/templates/analytics/ci/tasks/deploy-bicep.yml, infrastructure/templates/public-api/ci/jobs/deploy-infrastructure.yml, infrastructure/templates/public-api/ci/tasks/deploy-bicep.yml, infrastructure/templates/screener/ci/jobs/deploy-infrastructure.yml, infrastructure/templates/screener/ci/tasks/deploy-bicep.yml
ℹ️  This applies the same changes to the Public API, Analytics, and Data Screener pipelines that were already made to the Search infrastructure pipeline by https://github.com/dfe-analytical-services/explore-education-statistics/pull/5770 ℹ️ 
This PR adds a temporary workaround to stop Bicep deployments failing due to a bug in Azure CLI 2.71.0.
The error when starting the Bicep deployment is
```
No such file or directory: '/home/vsts/work/_temp/.azclitask/bin/bicep'
```
Between 08/04/25 and 09/04/25 version 2.71.0 with the bug appears to have rolled out gradually across all agents and now it's blocking all of our infrastructure deployments. We can see the last successful run of the Bicep deployment on 08/04/25 used Azure CLI 2.70.0.
**2.71.0**:
**2.70.0**:
- Add step to Upgrade Azure CLI …
=> EES-6044 infrastructure bicep deployments are failing due to bug in azure cli

src/GovUk.Education.ExploreEducationStatistics.Public.Data.Model/GovUk.Education.ExploreEducationStatistics.Public.Data.Model.csproj
This PR:
- fixes the import of CSVs with quote-escaped cells (e.g. "Kingston upon Hull, City of") by reverting to the previously-used version of DuckDB.
The change to the new version of Duck would, without further explicit configuration, result in the following errors when attempting to read form such a CSV:
```
Message: Invalid Input Error: CSV Error on Line: 34226
Original Line: 2024,Week 37,Monday,Local...authority,E92000001,England,E12000003,Yorkshire and The Humber,E06000010,"Kingston upon Hull, City of",810,2024-09-09,Primary,Attendance,Present,All present,37020,x,x
Expected Number of Columns:...
```
This is likely due to a change in DuckDB's default CSV behaviour since version 1.2.0 (we previously used 1.0.2 and the upgrades set the new version to 1.2.1).  From the DuckDB v1.2.0 …
=> Ees 6048 hotfix revert duckdb dependency version

src/GovUk.Education.ExploreEducationStatistics.Admin/Startup.cs, src/GovUk.Education.ExploreEducationStatistics.Publisher/PublisherHostBuilderExtensions.cs
Admin and Publisher, when starting up, look for the existence of a PublicDataDb flag to know whether to setup the PsqlDbContext. However, it does not check whether the connection string it uses has a value. This has led to issues where the flag is true but the connection string is null.
=> Fix PublicDataDb hack

infrastructure/parameters/pre-prod.parameters.json
This PR increases the capacity of the statistics and replica DBs on Pre-Prod, from 250GB to 350GB.
This is in response to capacity alerts showing that Pre-Prod's statistics dbs are now at 95% capacity.
=> EES-6050 - increasing Pre-Prods statistics db capacity from 250GB to 350GB

src/GovUk.Education.ExploreEducationStatistics.Analytics.Consumer.Tests/Services/PublicApiQueriesProcessorServiceTests.cs, src/GovUk.Education.ExploreEducationStatistics.Analytics.Consumer.Tests/TestAnalyticsPathResolver.cs, src/GovUk.Education.ExploreEducationStatistics.Analytics.Consumer/Functions/ConsumeAnalyticsRequestFilesFunction.cs, src/GovUk.Education.ExploreEducationStatistics.Analytics.Consumer/Services/AnalyticsPathResolver.cs, src/GovUk.Education.ExploreEducationStatistics.Analytics.Consumer/Services/Interfaces/IAnalyticsPathResolver.cs, src/GovUk.Education.ExploreEducationStatistics.Analytics.Consumer/Services/PublicApiQueriesProcessor.cs, src/GovUk.Education.ExploreEducationStatistics.Common/Utils/RandomUtils.cs, src/GovUk.Education.ExploreEducationStatistics.Public.Data.Api/Services/QueryAnalyticsWriter.cs
This PR is hopefully a fix for an analytics bug we've seen in the Dev environment.
This bug was revealed when running the performance tests with this command:
```
pnpm --environment=dev perftest dist/publicApiDataSetQuery.test.js -e QUERY_FILES=dev/api-tests-absence-query1.json,dev/api-tests-absence-query2.json -e PROFILE=load -e MAIN_TEST_STAGE_DURATION_MINS=10 -e RPS=10
```
This would in rare instances produce request files by the Public API's `QueryAnalyticWriter#ReportDataSetVersionQuery` that ended with an extra close curly bracket. We now believe this is due to the Public API container app scaling up, and then due to a clashing filename, `WriteAllTextAsync` running twice from two different containers writing to a single file at the same time. While I feel fairly confident this is …
=> EES-6035 Attempted fix of Dev env analytics bug

tests/robot-tests/tests/admin/bau/create_data_block_with_chart.robot, tests/robot-tests/tests/admin/bau/delete_subject.robot, tests/robot-tests/tests/libs/charts.robot, tests/robot-tests/tests/libs/common.robot
This PR:
- fixes `delete_subject.robot` by waiting for a delayed piece of text to appear when a modal in opened.
- patches `create_data_block_with_chart.robot` to get it reporting green again in lieu of 2 front-end bugs getting fixed.
In tackling `create_data_block_with_chart.robot` , I found the following genuine front-end bugs:
* EES-6052 - footnote updates not appearing in already-viewed data blocks.
* EES-6055 - incorrect default time periods being selected in map chart preview when changing data sets.
I have patched `create_data_block_with_chart.robot` for now to bypass these bugs, and added instructions into the bug tickets to remove the patch lines from the Robot test when the bug is fixed.
I've also added the option to bypass scrolling elements into view prior to checking for …
=> EES-6056 - getting create_data_block_with_chart.robot and delete_subject.robot working again

infrastructure/templates/search/application/indexes/index-1.json
This PR updates the Azure AI search index configuration to add search fields to match the searchable documents in the Azure Storage blob container data source.
EES-5940 in #5733 added the infrastructure to configure the Azure AI Search instance with an index, indexer and data source. However the index that it created was an empty sample with a single key field. Attempting to use the Azure AI search endpoint up to now will yield empty results containing only two fields `@search.score` and `rid`.
With the indexer and data source configured to use the Azure Storage blob container, by default the indexer will run with a `dataToExtract` parameter of `contentAndMetadata`. This means that all metadata and textual content extracted from the blob will be indexed. This is explained in [Configure …
=> EES-6045 Update Azure AI Search index configuration

infrastructure/templates/search/application/searchDocsFunction.bicep, infrastructure/templates/search/application/searchDocsFunctionEventSubscriptions.bicep, infrastructure/templates/search/types.bicep, src/GovUk.Education.ExploreEducationStatistics.Content.Search.FunctionApp.Tests/Builders/AzureBlobStorageClientMockBuilder.cs, src/GovUk.Education.ExploreEducationStatistics.Content.Search.FunctionApp.Tests/Builders/ContentApiClientMockBuilder.cs, src/GovUk.Education.ExploreEducationStatistics.Content.Search.FunctionApp.Tests/Builders/SearchableDocumentRemoverMockBuilder.cs, src/GovUk.Education.ExploreEducationStatistics.Content.Search.FunctionApp.Tests/Clients/ContentApi/ContentApiClientTests.cs, src/GovUk.Education.ExploreEducationStatistics.Content.Search.FunctionApp.Tests/Functions/OnPublicationArchived/OnPublicationArchivedFunctionTests.cs, src/GovUk.Education.ExploreEducationStatistics.Content.Search.FunctionApp.Tests/Functions/RemovePublicationSearchableDocuments/RemovePublicationSearchableDocumentsTests.cs, src/GovUk.Education.ExploreEducationStatistics.Content.Search.FunctionApp.Tests/ProgramTests.cs, src/GovUk.Education.ExploreEducationStatistics.Content.Search.FunctionApp.Tests/Services/SearchableDocumentRemoverTests.cs, src/GovUk.Education.ExploreEducationStatistics.Content.Search.FunctionApp/Clients/AzureBlobStorage/AzureBlobStorageClient.cs, src/GovUk.Education.ExploreEducationStatistics.Content.Search.FunctionApp/Clients/AzureBlobStorage/IAzureBlobStorageClient.cs, src/GovUk.Education.ExploreEducationStatistics.Content.Search.FunctionApp/Clients/ContentApi/ContentApiClient.cs, src/GovUk.Education.ExploreEducationStatistics.Content.Search.FunctionApp/Clients/ContentApi/Dtos/ReleaseSearchViewModelDto.cs, src/GovUk.Education.ExploreEducationStatistics.Content.Search.FunctionApp/Clients/ContentApi/Dtos/ReleaseSummaryViewModelDto.cs, src/GovUk.Education.ExploreEducationStatistics.Content.Search.FunctionApp/Clients/ContentApi/IContentApiClient.cs, src/GovUk.Education.ExploreEducationStatistics.Content.Search.FunctionApp/Domain/ReleaseInfo.cs, src/GovUk.Education.ExploreEducationStatistics.Content.Search.FunctionApp/Exceptions/UnableToGetReleasesForPublicationException.cs, src/GovUk.Education.ExploreEducationStatistics.Content.Search.FunctionApp/Extensions/HostBuilderExtension.cs, src/GovUk.Education.ExploreEducationStatistics.Content.Search.FunctionApp/Functions/OnPublicationArchived/Dtos/PublicationArchivedEventDto.cs, src/GovUk.Education.ExploreEducationStatistics.Content.Search.FunctionApp/Functions/OnPublicationArchived/OnPublicationArchivedFunction.cs, src/GovUk.Education.ExploreEducationStatistics.Content.Search.FunctionApp/Functions/RemovePublicationSearchableDocuments/Dto/RemovePublicationSearchableDocumentsDto.cs, src/GovUk.Education.ExploreEducationStatistics.Content.Search.FunctionApp/Functions/RemovePublicationSearchableDocuments/RemovePublicationSearchableDocumentsFunction.cs, src/GovUk.Education.ExploreEducationStatistics.Content.Search.FunctionApp/Services/ISearchableDocumentRemover.cs, src/GovUk.Education.ExploreEducationStatistics.Content.Search.FunctionApp/Services/RemovePublicationSearchableDocumentsRequest.cs, src/GovUk.Education.ExploreEducationStatistics.Content.Search.FunctionApp/Services/RemovePublicationSearchableDocumentsResponse.cs, src/GovUk.Education.ExploreEducationStatistics.Content.Search.FunctionApp/Services/SearchableDocumentRemover.cs, src/GovUk.Education.ExploreEducationStatistics.Content.Search.FunctionApp/local.settings.json, src/GovUk.Education.ExploreEducationStatistics.Search.sln.DotSettings
This PR adds event handling to the Search Function App for publication archiving events.
When subscribed to publication archiving events, on archiving of a publication the Search Function App will remove searchable documents from the Search blob storage account for any published releases of the publication.
It does this by making a call to the Content API to retrieve all published releases for the publication. Using the release id's it removes searchable documents from the Search blob storage account for any blobs matching the release id, if they exist.
=> EES-5956 Add event handling to Search function app for publication archiving events

src/explore-education-statistics-common/src/components/ExportMenu.module.scss, src/explore-education-statistics-common/src/modules/charts/components/ChartExportMenu.tsx
This PR fixes an issue where 'Copy to Clipboard' functionality didn't work on Safari.
After some research it seems Safari requires the blob value to be returned from a promise.
It also
- Fixes style issue of the export menu to display on the right (it was showing on the left on Safari and Firefox)
- Changes the button text to 'Copied' temporarily on copy success, in line with other copy functionality on the site.
References for the Safari issue:
- https://web.dev/articles/async-clipboard#demos:~:text=Warning%3A%20Safari,type%3A%20%27foo/bar%27%20%7D))%3B%20%7D)%2C%20%7D)
- https://www.bigbinary.com/blog/copy-generated-image-clipboard-javascript
- https://stackoverflow.com/questions/65356108/how-to-use-clipboard-api-to-write-image-to-clipboard-in-safari
- …
=> EES-6032 safari copy chart clipboard bug

src/explore-education-statistics-common/src/modules/table-tool/utils/__tests__/getDefaultTableHeadersConfig.test.ts, src/explore-education-statistics-common/src/modules/table-tool/utils/getDefaultTableHeadersConfig.ts
Previously single filters were hidden in table tool tables, which could cause some confusion. Now they are shown unless they are the default, usually 'Total', for the filter / filter group.
Before:
After:
Before:
After:
Before:
After:
=> EES-6000 show single item filters in tables

src/GovUk.Education.ExploreEducationStatistics.Common.Tests/Extensions/TheoryDataExtensions.cs, src/GovUk.Education.ExploreEducationStatistics.Common.Tests/Utils/DataSetVersionNumberTest.cs, src/GovUk.Education.ExploreEducationStatistics.Common/Utils/DataSetVersionNumber.cs, src/GovUk.Education.ExploreEducationStatistics.Public.Data.Api.Tests/Controllers/DataSetVersionsControllerTests.cs, src/GovUk.Education.ExploreEducationStatistics.Public.Data.Api.Tests/Controllers/DataSetsControllerGetQueryTests.cs, src/GovUk.Education.ExploreEducationStatistics.Public.Data.Api.Tests/Controllers/DataSetsControllerPostQueryTests.cs, src/GovUk.Education.ExploreEducationStatistics.Public.Data.Api.Tests/Controllers/DataSetsControllerTests.cs, src/GovUk.Education.ExploreEducationStatistics.Public.Data.Api.Tests/Fixture/IntegrationTestFixtureWithCommonTestDataSetup.cs, src/GovUk.Education.ExploreEducationStatistics.Public.Data.Api.Tests/TheoryData/DataSetVersionStatusTheoryData.cs, src/GovUk.Education.ExploreEducationStatistics.Public.Data.Api/Services/DataSetQueryService.cs, src/GovUk.Education.ExploreEducationStatistics.Public.Data.Api/Services/DataSetService.cs, src/GovUk.Education.ExploreEducationStatistics.Public.Data.Api/Services/DataSetVersionChangeService.cs, src/GovUk.Education.ExploreEducationStatistics.Public.Data.Model.Tests/Extensions/DataSetVersionQueryableExtensionsTests.cs, src/GovUk.Education.ExploreEducationStatistics.Public.Data.Model/Extensions/DataSetVersionAuthExtensions.cs, src/GovUk.Education.ExploreEducationStatistics.Public.Data.Model/Extensions/DataSetVersionQueryableExtensions.cs
This Pull Request fixes functionality that handles requests to the Public API with wildcard versions (e.g., 2.*) that was previously returning unpublished data set versions.
It tweaks logic of Public API endpoints that accept data set version that user specifies, that if the user a wildcard dataset version, that only published dataset versions are returned. 
Ensure that for wildcard data set version - only published data set versions are returned if present. 
Ensures 404 response if a non-published version exists and has been requested using wildcard parameter.
Added or updated test coverage for controllers handling wildcard dataset version queries.
Extended existing tests to check the behavior for both published and non-published versions.
Introduced a new method WherePublishedStatus in …
=> EES-6049 - Public API wildcard data set versions try to access unpublished data bug fix

src/explore-education-statistics-admin/src/components/FormModal.tsx, src/explore-education-statistics-admin/src/components/editable/EditableAccordion.tsx, src/explore-education-statistics-admin/src/pages/methodology/edit-methodology/content/components/MethodologyAccordion.tsx, src/explore-education-statistics-admin/src/pages/methodology/edit-methodology/content/components/MethodologyAccordionSection.tsx, src/explore-education-statistics-admin/src/pages/methodology/edit-methodology/content/context/useMethodologyContentActions.ts, src/explore-education-statistics-admin/src/pages/release/content/components/ReleaseContent.tsx, src/explore-education-statistics-admin/src/pages/release/content/components/ReleaseContentAccordion.tsx, src/explore-education-statistics-admin/src/pages/release/content/components/ReleaseContentAccordionSection.tsx, src/explore-education-statistics-admin/src/pages/release/content/components/ReleaseEditableBlock.tsx, src/explore-education-statistics-admin/src/pages/release/content/components/ReleaseHeadlines.tsx, src/explore-education-statistics-admin/src/pages/release/content/components/__tests__/ReleaseContentAccordionSection.test.tsx, src/explore-education-statistics-admin/src/pages/release/content/contexts/useReleaseContentActions.ts, src/explore-education-statistics-admin/src/utils/focus/focusAddedSectionBlockButton.ts
This PR handles many cases of focussing elements after content blocks and sections are added or removed.
Existing behaviour is that focus 'disappears' after removing (or sometimes adding) blocks/sections, so the user would have to tab all the way back to there point of interest in the page.
- When a **section** is removed, focus on the previous section if it exists, otherwise on the 'add section' button.
- When a content **block** is removed, focus on the applicable 'add' button.
- Similar for particular release content blocks, e.g. adding and removing **headlines block** and **release summary block**
=> EES-6033 content section focus handling

src/GovUk.Education.ExploreEducationStatistics.Admin.Tests/Services/ThemeServiceTests.cs, src/GovUk.Education.ExploreEducationStatistics.Admin/Mappings/MappingProfiles.cs, src/GovUk.Education.ExploreEducationStatistics.Admin/ViewModels/ThemeViewModels.cs
ThemeViewModel has a Publications property that was not being populated. Furthermore, inspection of the usage of ThemeViewModel reveals that we do not want the list of publications being returned under each themeViewModel instance, increasing the response size considerably.
=> EES-5962 - Remove the unused and broken ThemeViewModel.Publications

src/explore-education-statistics-common/src/modules/table-tool/utils/__tests__/getDefaultTableHeadersConfig.test.ts, src/explore-education-statistics-common/src/modules/table-tool/utils/getDefaultTableHeadersConfig.ts, tests/robot-tests/tests/admin_and_public/bau/data_reordering.robot, tests/robot-tests/tests/admin_and_public/bau/publish_data.robot, tests/robot-tests/tests/general_public/table_tool_absence_by_characteristic.robot, tests/robot-tests/tests/general_public/table_tool_absence_in_prus.robot, tests/robot-tests/tests/general_public/table_tool_exclusions_by_geographic_level.robot
Changes the default order for time periods in table tool column headers to latest - oldest.
=> EES-6006 reverse order for time period column headers

infrastructure/parameters/pre-prod.parameters.json, infrastructure/parameters/prod.parameters.json, infrastructure/templates/template.json
This PR adjusts the schedule of the `StageScheduledReleases` Publisher function to run every day at 00:05:00 instead of 00:00:00.
This is because we can't reliably guarantee when a function using a timer trigger will run and it might start running early a fraction of a second before midnight. There's currently a limitation that the `StageScheduledReleases` must be run in the same day as the `PublishScheduledReleases` function which goes on to publish the releases, as it only picks up releases to be published on that day. This is described in more detail and will be fixed by https://github.com/dfe-analytical-services/explore-education-statistics/pull/5823.
=> EES-6064 Adjust schedule of the `StageScheduledReleases` Publisher function

tests/robot-tests/tests/admin_and_public/bau/publish_data.robot
This PR:
* Fixes `publish_data.robot` by updating the expected table layout header expectations.
* Updates an autosave text block behaviour to consistently work (previously very buggy on my local environment due to speed).
=> EES-6078 - updated xpath for table headers and cells after EES-6000 changes

infrastructure/templates/template.json, src/GovUk.Education.ExploreEducationStatistics.Publisher/local.settings.json
* Rename parameter `timeZone` to `publisherFunctionAppTimeZone` in template.json as it wasn't clear that it only applies to the Publisher Function App.
* Add a description to the parameter to explain its impact on Cron triggered functions.
* Change the time zone from Windows time zone ID `GMT Standard Time` to IANA time zone `Europe/London`. The naming of `GMT Standard Time` doesn't reflect its daylight saving behaviour clearly and could cause confusion.
It should be possible to use `Europe/London` across different operating systems now starting with .NET6.
The [docs for Azure Function App settings ](https://learn.microsoft.com/en-us/azure/azure-functions/functions-app-settings#website_time_zone) still suggest needing to use `GMT Standard Time` for Windows but I think this is an …
=> EES-6064 Change Publisher function app time zone setting

infrastructure/parameters/dev.parameters.json, infrastructure/parameters/pre-prod.parameters.json, infrastructure/parameters/prod.parameters.json, infrastructure/parameters/test.parameters.json, infrastructure/templates/template.json, src/GovUk.Education.ExploreEducationStatistics.Admin.Tests/Services/ReleaseApprovalServiceTests.cs, src/GovUk.Education.ExploreEducationStatistics.Admin.Tests/appsettings.IntegrationTest.json, src/GovUk.Education.ExploreEducationStatistics.Admin/Options/ReleaseApprovalOptions.cs, src/GovUk.Education.ExploreEducationStatistics.Admin/Services/ReleaseApprovalService.cs, src/GovUk.Education.ExploreEducationStatistics.Admin/appsettings.Development.json, src/GovUk.Education.ExploreEducationStatistics.Publisher.Tests/Services/PublishingServiceTests.cs, src/GovUk.Education.ExploreEducationStatistics.Publisher/Functions/PublishScheduledReleasesFunction.cs, src/GovUk.Education.ExploreEducationStatistics.Publisher/Functions/StageReleaseContentFunction.cs, src/GovUk.Education.ExploreEducationStatistics.Publisher/Functions/StageScheduledReleasesFunction.cs, src/GovUk.Education.ExploreEducationStatistics.Publisher/Options/AppOptions.cs, src/GovUk.Education.ExploreEducationStatistics.Publisher/local.settings.json
This PR renames the Publisher app settings used to control the schedule of Cron triggered functions to match the function names.
The functions have been renamed in the past but the app settings and the definitions of those settings in the infrastructure have not caught up, and this is causing confusion.
- `PublishReleasesCronSchedule` is renamed to `StageScheduledReleasesFunctionCronSchedule`.
- `PublishReleaseContentCronSchedule` is renamed to `PublishScheduledReleasesFunctionCronSchedule`.
=> EES-6064 Rename the Publisher app settings used to control the schedule of Cron triggered functions to match the function names

infrastructure/templates/search/application/searchDocsFunctionEventSubscriptions.bicep, src/GovUk.Education.ExploreEducationStatistics.Content.Search.FunctionApp.Tests/Functions/OnPublicationArchived/OnPublicationArchivedFunctionTests.cs, src/GovUk.Education.ExploreEducationStatistics.Content.Search.FunctionApp/Functions/OnPublicationArchived/Dtos/PublicationArchivedEventDto.cs, src/GovUk.Education.ExploreEducationStatistics.Content.Search.FunctionApp/Functions/OnPublicationArchived/OnPublicationArchivedFunction.cs
This PR adds in the configuration to subscribe the Search Function App to publication archived events. This was missed from https://github.com/dfe-analytical-services/explore-education-statistics/pull/5808 which added the function and the storage queue but did not subscribe the function via the queue.
- Rename `Slug` to `PublicationSlug` in `PublicationArchivedEventDto` for clarity. Add `PreviousSupersededByPublicationId` and `NewSupersededByPublicationId` as extra information which will be in the event payload.
- Correct unit test `GivenEvent_WhenPayloadContainsSlug_ReturnsExpectedDto` to use `PublicationArchivedEventDto` instead of `PublicationChangedEventDto`.
=> EES-6103 Subscribe Search Function App to publication archived events

src/explore-education-statistics-frontend/src/components/PageMeta.tsx, src/explore-education-statistics-frontend/src/modules/data-catalogue/DataCataloguePage.tsx
- Remove hardcoded `data-catalogue` canonical link.
- Ensure canonical links are on all pages
- Ensure canonical links respect paginated pages, but ignore other query params.
The canonical path is generated automatically from the next router path, with all query params except for `page` stripped out.
I've left in the potential to override the canonical link as a prop on page meta, in case this functionality is useful or needed in future.
=> EES-6047 Ensure canonical links are on all pages

infrastructure/templates/template.json, src/GovUk.Education.ExploreEducationStatistics.Content.Api/Startup.cs
This PR fixes two things:
- The Content API's Startup.cs
- Sets WEBSITE_CONTENTOVERVNET to 1 for the Content App service. We needed to set this as otherwise the the Content API couldn't mount the analytics file share. (Solved by Dunc who also had the same error a while back related to the publisher.)
=> EES-5977 Fix Content API

infrastructure/templates/template.json, src/GovUk.Education.ExploreEducationStatistics.Publisher/local.settings.json
This PR partially reverts the changes made in https://github.com/dfe-analytical-services/explore-education-statistics/pull/5831 commit d404c28.
The `WEBSITE_TIME_ZONE` value needs to be a Windows time zone Id when running on Windows operating system as per the documentation for [WEBSITE_TIME_ZONE](https://learn.microsoft.com/en-us/azure/azure-functions/functions-app-settings#website_time_zone).
The ability to use Windows time zone id's and IANA/TZ time zone id's interchangeably is possible since .NET6 , for example, `TimeZoneInfo.FindSystemTimeZoneById("Europe/London")` will now return the same time zone as `TimeZoneInfo.FindSystemTimeZoneById("GMT Standard Time")` on Windows, but this benefit doesn't apply to the function app environment setting here.
=> EES-6064 Partially revert time zone change made by #5831

infrastructure/templates/search/application/indexes/index-1.json
This PR makes a couple of changes to the Azure Search Index config to support the local frontend development of the new search feature.
- Add CORS config to allow CORS preflight requests from localhost.
- Add Suggester config to provide the autocomplete and suggestions.
Documentation for both can be found in [Create Index](https://learn.microsoft.com/en-us/rest/api/searchservice/create-index) and [Configure a suggester for autocomplete and suggestions in a query](https://learn.microsoft.com/en-us/azure/search/index-add-suggesters).
- Reorder the top level keys in the json into alphabetical order.
=> EES-6108 Changes to the Azure Search index to support frontend development

src/explore-education-statistics-common/src/modules/find-statistics/components/DataBlockTabs.tsx, src/explore-education-statistics-common/src/modules/find-statistics/hooks/useDataBlock.ts, src/explore-education-statistics-frontend/src/modules/find-statistics/components/PublicationReleaseHeadlinesSection.tsx, src/explore-education-statistics-frontend/src/modules/find-statistics/components/PublicationSectionBlocks.tsx, tests/robot-tests/tests/admin/bau/create_data_block_with_chart.robot
Fixes a bug in the admin where if you updated a footnote included in a data block embedded in a release, then went back to the release content tab, the footnote would not be updated unless you refreshed the page. This was caused by the `staleTime` being set to `Infinity` which prevented the data block from being refetched. I've changed it so the `staleTime` is only set for data blocks in the public frontend.
=> EES-6052 fix updated footnotes in datablocks in admin release content

src/GovUk.Education.ExploreEducationStatistics.Admin.Tests/MockBuilders/AdminEventRaiserMockBuilder.cs, src/GovUk.Education.ExploreEducationStatistics.Admin.Tests/MockBuilders/PublicationCacheServiceMockBuilder.cs, src/GovUk.Education.ExploreEducationStatistics.Admin.Tests/Services/AdminEventRaiserTests.cs, src/GovUk.Education.ExploreEducationStatistics.Admin.Tests/Services/PublicationServiceTests.cs, src/GovUk.Education.ExploreEducationStatistics.Admin.Tests/Services/PublicationServiceTestsTheoryData.cs, src/GovUk.Education.ExploreEducationStatistics.Admin.Tests/Services/ThemeServiceTests.cs, src/GovUk.Education.ExploreEducationStatistics.Admin.Tests/Utils/PublicationArchiveStatusTransitionResolverTests.cs, src/GovUk.Education.ExploreEducationStatistics.Admin/Events/PublicationArchivedEvent.cs, src/GovUk.Education.ExploreEducationStatistics.Admin/Services/AdminEventRaiser.cs, src/GovUk.Education.ExploreEducationStatistics.Admin/Services/Interfaces/IAdminEventRaiser.cs, src/GovUk.Education.ExploreEducationStatistics.Admin/Services/PublicationService.cs, src/GovUk.Education.ExploreEducationStatistics.Admin/Utils/PublicationArchiveStatusTransitionResolver.cs
The Admin service allows updating publications including setting and un-setting a  'superseded by' publication for a publication. A publication is considered to be archived if it has a superseding publication which is live, i.e. the superseding publication has one or more published releases.
This PR changes the Admin service to raise an Event Grid event when publications are archived. The event is only raised if a publication was not previously archived, but now is.
To know whether to raise the event or not, we work out the transition of the publication's archived status and only raise it if the status is changing from not archived to archived.
The Search Function App is subscribed to these events and will manage searchable documents accordingly. This change was made to the Search …
=> EES-6105 Raise an event in Admin when publications are archived

tests/robot-tests/tests/general_public/prod_only/old_fast_track.robot
Fixing UI tests failures on Pre prod in `general_public` suite.
Chose different key words that do not rely on release name or x-path -So that the tests pass on both Pre prod and Prod even if the latest release name gets changed over time.
=> EES-6060-fix UI tests failing on Pre-prod

src/GovUk.Education.ExploreEducationStatistics.Admin.Tests/MockBuilders/AdminEventRaiserMockBuilder.cs, src/GovUk.Education.ExploreEducationStatistics.Admin.Tests/Services/AdminEventRaiserTests.cs, src/GovUk.Education.ExploreEducationStatistics.Admin.Tests/Services/PublicationServiceTests.cs, src/GovUk.Education.ExploreEducationStatistics.Admin.Tests/Services/PublicationServiceTestsTheoryData.cs, src/GovUk.Education.ExploreEducationStatistics.Admin/Events/PublicationRestoredEvent.cs, src/GovUk.Education.ExploreEducationStatistics.Admin/Services/AdminEventRaiser.cs, src/GovUk.Education.ExploreEducationStatistics.Admin/Services/Interfaces/IAdminEventRaiser.cs, src/GovUk.Education.ExploreEducationStatistics.Admin/Services/PublicationService.cs
This PR is a follow up to https://github.com/dfe-analytical-services/explore-education-statistics/pull/5848 and raises an event in Admin when archived publications are restored.
The Admin service allows updating publications including setting and un-setting a 'superseded by' publication for a publication. A publication is considered to be archived if it has a superseding publication which is live, i.e. the superseding publication has one or more published releases.
This PR changes the Admin service to raise an Event Grid event when archived publications are restored. The event is only raised if a publication was previously archived but now isn't.
To know whether to raise the event or not, we work out the transition of the publication's archived status and only raise it if the status is …
=> EES-6106 Raise an event in Admin when archived publications are restored

infrastructure/templates/search/application/searchDocsFunction.bicep, infrastructure/templates/search/types.bicep, src/GovUk.Education.ExploreEducationStatistics.Content.Search.FunctionApp.Tests/Builders/SearchableDocumentRemoverMockBuilder.cs, src/GovUk.Education.ExploreEducationStatistics.Content.Search.FunctionApp.Tests/Functions/RemoveSearchableDocument/RemoveSearchableDocumentTests.cs, src/GovUk.Education.ExploreEducationStatistics.Content.Search.FunctionApp.Tests/Services/SearchableDocumentRemoverTests.cs, src/GovUk.Education.ExploreEducationStatistics.Content.Search.FunctionApp/Functions/RemoveSearchableDocument/Dto/RemoveSearchableDocumentDto.cs, src/GovUk.Education.ExploreEducationStatistics.Content.Search.FunctionApp/Functions/RemoveSearchableDocument/RemoveSearchableDocumentFunction.cs, src/GovUk.Education.ExploreEducationStatistics.Content.Search.FunctionApp/Services/ISearchableDocumentRemover.cs, src/GovUk.Education.ExploreEducationStatistics.Content.Search.FunctionApp/Services/RemoveSearchableDocumentRequest.cs, src/GovUk.Education.ExploreEducationStatistics.Content.Search.FunctionApp/Services/RemoveSearchableDocumentResponse.cs, src/GovUk.Education.ExploreEducationStatistics.Content.Search.FunctionApp/Services/SearchableDocumentCreator.cs, src/GovUk.Education.ExploreEducationStatistics.Content.Search.FunctionApp/Services/SearchableDocumentRemover.cs, src/GovUk.Education.ExploreEducationStatistics.Content.Search.FunctionApp/local.settings.json
We introduced a new Azure function that removes specified searchable documents in preparation for removing searchable documents when there has been a reorder.
=> EES-6070 Remove Searchable Document Function

src/GovUk.Education.ExploreEducationStatistics.Content.Search.FunctionApp.Tests/Functions/OnPublicationArchived/OnPublicationArchivedFunctionTests.cs, src/GovUk.Education.ExploreEducationStatistics.Content.Search.FunctionApp.Tests/Functions/OnPublicationChanged/OnReleaseSlugChangedFunctionTests.cs, src/GovUk.Education.ExploreEducationStatistics.Content.Search.FunctionApp.Tests/Functions/OnPublicationLatestPublishedReleaseVersionChanged/OnPublicationLatestPublishedReleaseReorderedFunctionTests.cs, src/GovUk.Education.ExploreEducationStatistics.Content.Search.FunctionApp.Tests/Functions/OnPublicationRestored/OnPublicationRestoredFunctionTests.cs, src/GovUk.Education.ExploreEducationStatistics.Content.Search.FunctionApp.Tests/Functions/OnReleaseSlugChanged/OnReleaseSlugChangedFunctionTests.cs, src/GovUk.Education.ExploreEducationStatistics.Content.Search.FunctionApp.Tests/Functions/OnReleaseVersionPublished/OnReleaseVersionPublishedFunctionTests.cs, src/GovUk.Education.ExploreEducationStatistics.Content.Search.FunctionApp.Tests/Functions/RefreshSearchableDocument/RefreshSearchableDocumentFunctionTests.cs, src/GovUk.Education.ExploreEducationStatistics.Content.Search.FunctionApp.Tests/Functions/RemovePublicationSearchableDocuments/RemovePublicationSearchableDocumentsTests.cs, src/GovUk.Education.ExploreEducationStatistics.Content.Search.FunctionApp.Tests/Functions/RemoveSearchableDocument/RemoveSearchableDocumentTests.cs, src/GovUk.Education.ExploreEducationStatistics.Content.Search.FunctionApp.Tests/TheoryDataHelpers/BlankValues.cs, src/GovUk.Education.ExploreEducationStatistics.Content.Search.FunctionApp.Tests/TheoryDatas/Empty.cs, src/GovUk.Education.ExploreEducationStatistics.Content.Search.FunctionApp/Extensions/GuidExtensions.cs, src/GovUk.Education.ExploreEducationStatistics.Content.Search.FunctionApp/Functions/OnPublicationLatestPublishedReleaseReordered/OnPublicationLatestPublishedReleaseReorderedFunction.cs, src/GovUk.Education.ExploreEducationStatistics.Content.Search.FunctionApp/Functions/OnPublicationLatestPublishedReleaseReordered/OnPublicationLatestPublishedReleaseReorderedOutput.cs, src/GovUk.Education.ExploreEducationStatistics.Content.Search.FunctionApp/Functions/RemoveSearchableDocument/RemoveSearchableDocumentFunction.cs
Only the latest release of a publication is searchable.
Releases can be reordered so that a new release version becomes the "latest".
When this occurs, a new searchable document was being created for the new "latest" release version.
However, the previous "latest" searchable document was not being removed.
This PR looks to address that.
=> EES-6070 Remove previous "latest" release version's searachable document

src/explore-education-statistics-common/src/components/form/FormCheckbox.module.scss, src/explore-education-statistics-common/src/components/form/FormCheckbox.tsx, src/explore-education-statistics-common/src/components/form/__tests__/__snapshots__/FormCheckbox.test.tsx.snap, src/explore-education-statistics-common/src/components/form/__tests__/__snapshots__/FormCheckboxGroup.test.tsx.snap, src/explore-education-statistics-common/src/components/form/__tests__/__snapshots__/FormCheckboxSearchGroup.test.tsx.snap, src/explore-education-statistics-common/src/components/form/__tests__/__snapshots__/FormCheckboxSearchSubGroups.test.tsx.snap, src/explore-education-statistics-common/src/components/form/__tests__/__snapshots__/FormFieldCheckboxGroupsMenu.test.tsx.snap, src/explore-education-statistics-common/src/modules/table-tool/components/FilterHierarchy.module.scss, src/explore-education-statistics-common/src/modules/table-tool/components/FilterHierarchy.tsx, src/explore-education-statistics-common/src/modules/table-tool/components/FilterHierarchyOptions.module.scss, src/explore-education-statistics-common/src/modules/table-tool/components/FilterHierarchyOptions.tsx, src/explore-education-statistics-common/src/modules/table-tool/components/FiltersForm.tsx, src/explore-education-statistics-common/src/modules/table-tool/components/TableToolWizard.tsx, src/explore-education-statistics-frontend/src/modules/table-tool/TableToolPage.tsx
Takes the Filter Hierarchy work further with UI layout bells & whistles.
Notable changes:
- includes feature flag search param `fh` appending `?subjectId=....&fh=true` will show filter hierarchies (when hierarchied data is used in the table tool)
- UI dropdowns & modal with associated styling
- Sub category tier level search for tiers with 7 or more options to filter long option lists
- Refactor / reverted option render method to go for a option tree generation first approach to cater for upcoming search (option tree filtering) functionality
=> EES-5741 - Filter Hierarchies UI & Layout

infrastructure/templates/search/application/indexes/index-1.json
This PR fixes the `themeTitle` field name in the Azure AI Search configuration which should have been renamed from `theme` to `themeTitle` by https://github.com/dfe-analytical-services/explore-education-statistics/pull/5856.
=> EES-6123 Fix themeTitle field name which was missed during rename

infrastructure/templates/template.json
This PR:
- grants the Public Site App Service's Managed Identity the "Key Vault Certificate User" role within its environment's Key Vault.
This is the prerequisite step in order for us to be able to connect an auto-renewing GlobalSign certificate from Production's Key Vault with the Production Public Site.
For those interested, the "magic GUID" in this PR comes from https://learn.microsoft.com/en-us/azure/role-based-access-control/built-in-roles/security#key-vault-certificate-user.
=> EES-6147 - hotfix to give Public Site access to Key Vault certificates

infrastructure/templates/search/application/searchService.bicep, infrastructure/templates/search/main.bicep
This PR sets `publicNetworkAccessEnabled` to true on the Search storage account. This is the equivalent to Network option 'Enabled from selected virtual networks and IP addresses') in the UI when firewallRules is set.
This prevents us needing to manually change the option to ‘Enabled from selected virtual networks and IP addresses’ to allow access from the maintenance range of IP addresses with every deploy.
- Tidy up TODO in searchService.bicep. Search service remains publicly accessible.
=> EES-6152 Alter Search storage account Network option

src/GovUk.Education.ExploreEducationStatistics.Content.Search.FunctionApp.Tests/Functions/OnReleaseVersionPublished/OnReleaseVersionPublishedFunctionTests.cs, src/GovUk.Education.ExploreEducationStatistics.Content.Search.FunctionApp/Functions/EventHandlers/OnReleaseVersionPublished/Dtos/ReleaseVersionPublishedEventDto.cs, src/GovUk.Education.ExploreEducationStatistics.Content.Search.FunctionApp/Functions/EventHandlers/OnReleaseVersionPublished/OnReleaseVersionPublishedFunction.cs
The OnReleaseVersionPublished function now handles the scenario
where a newly published release version is for a different release
than the previous latest release.
In this case, the function removes the searchable document
for the previous latest release.
It also identifies the case when the newly published release version is
not the Publication's latest, in which case we can ignore the event.
=> Ees 6071 Delete old searchable doc when release changes

src/GovUk.Education.ExploreEducationStatistics.Common/GovUk.Education.ExploreEducationStatistics.Common.csproj, src/GovUk.Education.ExploreEducationStatistics.Events.Tests/EventGrid/Builders/EventRaiserMockBuilder.cs, src/GovUk.Education.ExploreEducationStatistics.Events/ReleaseVersionPublishedEvent.cs, src/GovUk.Education.ExploreEducationStatistics.Publisher.Tests/Builders/Models/PublicationBuilder.cs, src/GovUk.Education.ExploreEducationStatistics.Publisher.Tests/Builders/Services/PublicationCacheServiceMockBuilder.cs, src/GovUk.Education.ExploreEducationStatistics.Publisher.Tests/Builders/Services/PublisherEventRaiserMockBuilder.cs, src/GovUk.Education.ExploreEducationStatistics.Publisher.Tests/Services/PublisherEventRaiserTests.cs, src/GovUk.Education.ExploreEducationStatistics.Publisher.Tests/Services/PublishingCompletionServiceTests.cs, src/GovUk.Education.ExploreEducationStatistics.Publisher/Services/Interfaces/IPublisherEventRaiser.cs, src/GovUk.Education.ExploreEducationStatistics.Publisher/Services/PublishedPublicationInfo.cs, src/GovUk.Education.ExploreEducationStatistics.Publisher/Services/PublishedReleaseVersionInfo.cs, src/GovUk.Education.ExploreEducationStatistics.Publisher/Services/PublisherEventRaiser.cs, src/GovUk.Education.ExploreEducationStatistics.Publisher/Services/PublishingCompletionService.cs
This PR refactors the Publisher's `PublishingCompletionService.CompletePublishingIfAllPriorStagesComplete` method to improve handling when publications are archived.
It adds a new `HandleArchivedPublications` method which is called with a list of publications that have been affected by publishing (i.e. they are related to releases just published).
Within `HandleArchivedPublications`, it only performs actions for publications which it finds are newly archived. These are publications which are replaced by any of the publications affected by publishing that were not already published (i.e. they had no published releases prior to publishing). If the publications they are replaced by were already published, their archive status is not changing, and no action is necessary.
Currently the only …
=> EES-6107 Refactor `PublishingCompletionService` to improve handling when publications are archived

infrastructure/templates/template.json, src/GovUk.Education.ExploreEducationStatistics.Publisher.Tests/Builders/Services/PublisherEventRaiserMockBuilder.cs, src/GovUk.Education.ExploreEducationStatistics.Publisher.Tests/Services/PublisherEventRaiserTests.cs, src/GovUk.Education.ExploreEducationStatistics.Publisher.Tests/Services/PublishingCompletionServiceTests.cs, src/GovUk.Education.ExploreEducationStatistics.Publisher/Services/Interfaces/IPublisherEventRaiser.cs, src/GovUk.Education.ExploreEducationStatistics.Publisher/Services/PublisherEventRaiser.cs, src/GovUk.Education.ExploreEducationStatistics.Publisher/Services/PublishingCompletionService.cs, src/GovUk.Education.ExploreEducationStatistics.Publisher/appsettings.example.json
This PR raises an event when publishing causes publications to be archived.
- Add more comments explaining setting latest published release versions in `PublishingCompletionServiceTests`.
- Rename `IPublisherEventRaiser.RaiseReleaseVersionPublishedEvents` to `OnReleaseVersionsPublished`.
- Remove sample topic endpoint URL from `appsettings.example.json`.
- Reformat `PublishingCompletionServiceTests`.
=> EES-6107 Raise event when publishing causes publications to be archived

src/GovUk.Education.ExploreEducationStatistics.Content.Search.FunctionApp.Tests/Builders/TestableCommandHandler.cs, src/GovUk.Education.ExploreEducationStatistics.Content.Search.FunctionApp.Tests/Clients/AzureBlobStorage/AzureBlobStorageIntegrationClient.cs, src/GovUk.Education.ExploreEducationStatistics.Content.Search.FunctionApp.Tests/Functions/FullReset/FullResetFunctionTests.cs, src/GovUk.Education.ExploreEducationStatistics.Content.Search.FunctionApp.Tests/Functions/RefreshSearchableDocument/RefreshSearchableDocumentFunctionTests.cs, src/GovUk.Education.ExploreEducationStatistics.Content.Search.FunctionApp.Tests/Functions/ReindexSearchableDocuments/ReindexSearchableDocumentsFunctionTests.cs, src/GovUk.Education.ExploreEducationStatistics.Content.Search.FunctionApp.Tests/Functions/RemovePublicationSearchableDocuments/RemovePublicationSearchableDocumentsTests.cs, src/GovUk.Education.ExploreEducationStatistics.Content.Search.FunctionApp.Tests/Functions/RemoveSearchableDocument/RemoveSearchableDocumentTests.cs, src/GovUk.Education.ExploreEducationStatistics.Content.Search.FunctionApp/Exceptions/AzureBlobStorageException.cs, src/GovUk.Education.ExploreEducationStatistics.Content.Search.FunctionApp/Exceptions/UnableToGetPublicationLatestReleaseSearchViewModelException.cs, src/GovUk.Education.ExploreEducationStatistics.Content.Search.FunctionApp/Exceptions/UnableToGetReleasesForPublicationException.cs, src/GovUk.Education.ExploreEducationStatistics.Content.Search.FunctionApp/Extensions/HostBuilderExtension.cs, src/GovUk.Education.ExploreEducationStatistics.Content.Search.FunctionApp/Functions/CommandHandlers/FullReset/FullResetFunction.cs, src/GovUk.Education.ExploreEducationStatistics.Content.Search.FunctionApp/Functions/CommandHandlers/RefreshSearchableDocument/RefreshSearchableDocumentFunction.cs, src/GovUk.Education.ExploreEducationStatistics.Content.Search.FunctionApp/Functions/CommandHandlers/ReindexSearchableDocuments/ReindexSearchableDocumentsFunction.cs, src/GovUk.Education.ExploreEducationStatistics.Content.Search.FunctionApp/Functions/CommandHandlers/RemovePublicationSearchableDocuments/RemovePublicationSearchableDocumentsFunction.cs, src/GovUk.Education.ExploreEducationStatistics.Content.Search.FunctionApp/Functions/CommandHandlers/RemoveSearchableDocument/RemoveSearchableDocumentFunction.cs, src/GovUk.Education.ExploreEducationStatistics.Content.Search.FunctionApp/Functions/EventHandlers/OnPublicationArchived/OnPublicationArchivedFunction.cs, src/GovUk.Education.ExploreEducationStatistics.Content.Search.FunctionApp/Functions/EventHandlers/OnPublicationChanged/OnPublicationChangedFunction.cs, src/GovUk.Education.ExploreEducationStatistics.Content.Search.FunctionApp/Functions/EventHandlers/OnPublicationLatestPublishedReleaseReordered/OnPublicationLatestPublishedReleaseReorderedFunction.cs, src/GovUk.Education.ExploreEducationStatistics.Content.Search.FunctionApp/Functions/EventHandlers/OnPublicationRestored/OnPublicationRestoredFunction.cs, src/GovUk.Education.ExploreEducationStatistics.Content.Search.FunctionApp/Functions/EventHandlers/OnReleaseSlugChanged/OnReleaseSlugChangedFunction.cs, src/GovUk.Education.ExploreEducationStatistics.Content.Search.FunctionApp/Functions/EventHandlers/OnReleaseVersionPublished/OnReleaseVersionPublishedFunction.cs, src/GovUk.Education.ExploreEducationStatistics.Content.Search.FunctionApp/Functions/EventHandlers/OnThemeUpdated/OnThemeUpdatedFunction.cs, src/GovUk.Education.ExploreEducationStatistics.Content.Search.FunctionApp/Services/Core/CommandHandler.cs, src/GovUk.Education.ExploreEducationStatistics.Content.Search.FunctionApp/Services/Core/ICommandHandler.cs
Our event handlers all pass through a common component that handles logging.
Added a similar component for handling all of the commands.
The primary driver for this was to add logging to all of our command handlers to aid troubleshooting in dev.
=> Ees 6071 add logging to command handlers

src/GovUk.Education.ExploreEducationStatistics.Content.Search.FunctionApp.Tests/Builders/HeathCheckStrategyBuilder.cs, src/GovUk.Education.ExploreEducationStatistics.Content.Search.FunctionApp.Tests/Functions/HealthChecks/HealthCheckFunctionTests.cs, src/GovUk.Education.ExploreEducationStatistics.Content.Search.FunctionApp.Tests/Functions/HealthChecks/Strategies/AzureBlobStorageHealthCheckStrategyIntegrationTests.cs, src/GovUk.Education.ExploreEducationStatistics.Content.Search.FunctionApp.Tests/Functions/HealthChecks/Strategies/ContentApiHealthCheckStrategyIntegrationTests.cs, src/GovUk.Education.ExploreEducationStatistics.Content.Search.FunctionApp/Clients/AzureSearch/AzureSearchIndexerClientFactory.cs, src/GovUk.Education.ExploreEducationStatistics.Content.Search.FunctionApp/Extensions/ServiceCollectionExtensions.cs, src/GovUk.Education.ExploreEducationStatistics.Content.Search.FunctionApp/Functions/CommandHandlers/FullReset/FullResetFunction.cs, src/GovUk.Education.ExploreEducationStatistics.Content.Search.FunctionApp/Functions/CommandHandlers/ReindexSearchableDocuments/ReindexSearchableDocumentsFunction.cs, src/GovUk.Education.ExploreEducationStatistics.Content.Search.FunctionApp/Functions/HealthChecks/Dtos/HealthCheckResponse.cs, src/GovUk.Education.ExploreEducationStatistics.Content.Search.FunctionApp/Functions/HealthChecks/HealthCheckFunction.cs, src/GovUk.Education.ExploreEducationStatistics.Content.Search.FunctionApp/Functions/HealthChecks/Strategies/AzureBlobStorageHealthCheckStrategy.cs, src/GovUk.Education.ExploreEducationStatistics.Content.Search.FunctionApp/Functions/HealthChecks/Strategies/AzureSearchHealthCheckStrategy.cs, src/GovUk.Education.ExploreEducationStatistics.Content.Search.FunctionApp/Functions/HealthChecks/Strategies/ContentApiHealthCheckStrategy.cs, src/GovUk.Education.ExploreEducationStatistics.Content.Search.FunctionApp/Functions/HealthChecks/Strategies/HeathCheckResult.cs, src/GovUk.Education.ExploreEducationStatistics.Content.Search.FunctionApp/Functions/HealthChecks/Strategies/IHeathCheckStrategy.cs, src/GovUk.Education.ExploreEducationStatistics.Content.Search.FunctionApp/GovUk.Education.ExploreEducationStatistics.Content.Search.FunctionApp.csproj
Added logging into the healthcheck strategies. A helpful way to induce some logging from the function app to test whether logs are being received in Application Insights.
=> Ees 6071 Add logging to health check strategies

infrastructure/templates/common/components/functionApp.bicep, infrastructure/templates/common/components/monitoring/functionAppDiagnosticSetting.bicep, infrastructure/templates/public-api/components/appInsights.bicep, infrastructure/templates/search/application/monitoring.bicep, infrastructure/templates/search/application/searchDocsFunction.bicep, infrastructure/templates/search/main.bicep, infrastructure/templates/search/types.bicep
This PR makes the following infrastructure changes:
When deploying  the Search Application Insights resource, we see the deployment automatically attempting to create a managed Log Analytics workspace with the name format `ai_<APPINSIGHTS RESOURCE NAME>_<APPINSIGHTS RESOURCE ID>_manage`.
In order to prevent it from attempting to create an additional workspace and make it to use our existing shared workspace for the Resource Group we now associate it using the `WorkspaceResourceId` parameter . Currently the Public API deployment is responsible for creating the shared Resource Group workspace. See the changes in module `monitoring.bicep` which has been renamed from `searchApplicationInsights.bicep`.
This adds a new parameter to the common Function App template which can enable sending logs …
=> EES-6169 Search infrastructure changes for Application Insights and Log Analytics

tests/robot-tests/tests/admin/bau/manage_users_page.robot
This PR fixes recent UI tests failure in `Admin` - Lead role was deleted , updated tests accordingly.
=> Fixing UI test failure in manage_users_page.robot

src/GovUk.Education.ExploreEducationStatistics.Content.Search.FunctionApp.Tests/Builders/SearchableDocumentCreatorMockBuilder.cs, src/GovUk.Education.ExploreEducationStatistics.Content.Search.FunctionApp.Tests/Builders/SearchableDocumentRemoverMockBuilder.cs, src/GovUk.Education.ExploreEducationStatistics.Content.Search.FunctionApp.Tests/Functions/FullReset/FullResetFunctionTests.cs, src/GovUk.Education.ExploreEducationStatistics.Content.Search.FunctionApp.Tests/Functions/OnPublicationArchived/OnPublicationArchivedFunctionTests.cs, src/GovUk.Education.ExploreEducationStatistics.Content.Search.FunctionApp.Tests/Functions/OnPublicationChanged/OnReleaseSlugChangedFunctionTests.cs, src/GovUk.Education.ExploreEducationStatistics.Content.Search.FunctionApp.Tests/Functions/OnPublicationLatestPublishedReleaseVersionChanged/OnPublicationLatestPublishedReleaseReorderedFunctionTests.cs, src/GovUk.Education.ExploreEducationStatistics.Content.Search.FunctionApp.Tests/Functions/OnPublicationRestored/OnPublicationRestoredFunctionTests.cs, src/GovUk.Education.ExploreEducationStatistics.Content.Search.FunctionApp.Tests/Functions/OnReleaseSlugChanged/OnReleaseSlugChangedFunctionTests.cs, src/GovUk.Education.ExploreEducationStatistics.Content.Search.FunctionApp.Tests/Functions/OnThemeUpdated/OnThemeUpdatedFunctionTests.cs, src/GovUk.Education.ExploreEducationStatistics.Content.Search.FunctionApp.Tests/Functions/RefreshSearchableDocument/RefreshSearchableDocumentFunctionTests.cs, src/GovUk.Education.ExploreEducationStatistics.Content.Search.FunctionApp.Tests/ProgramTests.cs, src/GovUk.Education.ExploreEducationStatistics.Content.Search.FunctionApp/Extensions/HostBuilderExtension.cs, src/GovUk.Education.ExploreEducationStatistics.Content.Search.FunctionApp/Extensions/ServiceCollectionExtensions.cs, src/GovUk.Education.ExploreEducationStatistics.Content.Search.FunctionApp/GovUk.Education.ExploreEducationStatistics.Content.Search.FunctionApp.csproj, src/GovUk.Education.ExploreEducationStatistics.Content.Search.FunctionApp/appsettings.Development.json, src/GovUk.Education.ExploreEducationStatistics.Content.Search.FunctionApp/appsettings.json, src/GovUk.Education.ExploreEducationStatistics.Content.Search.FunctionApp/host.json
This has been an ordeal!
It is recommended that the 3 commits are reviewed one at a time in order for added clarity of intention.
Replace the default logging to the console and Application Insights with Serilog.
Retain metrics measurements sent to App Insights.
The primary reason is that Serilog adds the ability to destructure objects into their constituent properties within the logs.
Logging settings in appsettings.json, appsettings.development.json and host.json are unused and therefore removed.
Remove unused using declarations across the solution
=> EES-6071 Delegate logging to Serilog

infrastructure/parameters/test.parameters.json
This PR sets the `eventGridTopicsExist` parameter in the infrastructure ARM template to `true` in the Test environment causing the topic endpoint app settings to be applied for the Admin and Publisher services.
The parameter has a default value of `true`.
=> EES-6166 Set the `eventGridTopicsExist` param to true in the Test environment

src/GovUk.Education.ExploreEducationStatistics.Content.Search.FunctionApp.Tests/Functions/HealthChecks/HealthCheckFunctionTests.cs, src/GovUk.Education.ExploreEducationStatistics.Content.Search.FunctionApp/Functions/HealthChecks/HealthCheckFunction.cs
Move the current healthcheck to a new `Full health check` so that we can still test config and security with it. And reduce the default heathcheck `Are you alive` to a simple returning of OK result.
=> New simple Healthcheck call

infrastructure/templates/search/application/searchDocsFunction.bicep, infrastructure/templates/search/components/searchService.bicep, infrastructure/templates/search/components/searchServiceConfig.bicep, infrastructure/templates/search/components/searchServiceRoleAssignment.bicep, infrastructure/templates/search/main.bicep
This PR updates the API version for for Microsoft.Search/searchservices from `2024-06-01-preview` to `2025-02-01-preview` allowing us to use new property `endpoint` in `searchService.bicep` and `searchDocsFunction.bicep`.
API version `2025-05-01` is latest but there is a change to `UserAssignedManagedIdentities` type in this version which we will need to update for. Being relatively new it does not have Bicep type definitions generated yet and deploying using `2025-05-01` results in warnings:
```
Warning BCP081: Resource type "Microsoft.Search/searchServices@2025-05-01" does not have types available. Bicep is unable to validate resource properties prior to deployment, but this will not block the resource from being deployed.
```
=> Update `Microsoft.Search/searchservices` API version

src/GovUk.Education.ExploreEducationStatistics.Content.Api/Controllers/DataSetFilesController.cs, src/GovUk.Education.ExploreEducationStatistics.Public.Data.Api/Controllers/DataSetsController.cs
This PR adds X-Robots-Tag="noindex" no index header to the two "/csv" endpoints we have - one is used with API data sets and the other for non-API data sets.
One of the backend endpoints actually ends "/download", in the backend, but that is invisible to the user. The frontend redirects to that endpoint from "/csv", so as far as the user is concerned it is still a "/csv" endpoint.
The requirements suggested we eventually remove these noindex headers after 6 months and instead use robots.txt to disallow indexing of these uris. But I'm not sure this will work well - I believe it would need to be `Disallow: /csv$`, which is fairly broad.
=> EES-5872 Add noindex header to /csv endpoints

src/GovUk.Education.ExploreEducationStatistics.Content.Search.FunctionApp/Extensions/LoggerConfigurationExtensions.cs, src/GovUk.Education.ExploreEducationStatistics.Content.Search.FunctionApp/Extensions/ServiceCollectionExtensions.cs, src/GovUk.Education.ExploreEducationStatistics.Content.Search.FunctionApp/GovUk.Education.ExploreEducationStatistics.Content.Search.FunctionApp.csproj, src/GovUk.Education.ExploreEducationStatistics.Content.Search.FunctionApp/appsettings.Development.json, src/GovUk.Education.ExploreEducationStatistics.Content.Search.FunctionApp/appsettings.Production.json, src/GovUk.Education.ExploreEducationStatistics.Content.Search.FunctionApp/appsettings.json
- Removed hardcoded Application Insights sink. 
- Add appsettings.Production.json to format the logs when deployed differently to when running locally. Note: having the prod Serilog config in appsettings.json meant it was also read in when running locally.
- Prevent default logger from logging to console, duplicating Serilog logs.
=> Troubleshooting Logging

src/GovUk.Education.ExploreEducationStatistics.Admin.Tests/Controllers/Api/ReleaseVersionsControllerTests.cs, src/GovUk.Education.ExploreEducationStatistics.Admin.Tests/MockBuilders/DataSetFileBuilder.cs, src/GovUk.Education.ExploreEducationStatistics.Admin.Tests/Services/DataSetFileStorageTests.cs, src/GovUk.Education.ExploreEducationStatistics.Admin.Tests/Services/ReleaseDataFileServicePermissionTests.cs, src/GovUk.Education.ExploreEducationStatistics.Admin.Tests/Services/ReleaseDataFileServiceTests.cs, src/GovUk.Education.ExploreEducationStatistics.Admin/Controllers/Api/ReleaseVersionsController.cs, src/GovUk.Education.ExploreEducationStatistics.Admin/Services/DataSetFileStorage.cs, src/GovUk.Education.ExploreEducationStatistics.Admin/Services/DataSetValidator.cs, src/GovUk.Education.ExploreEducationStatistics.Admin/Services/IDataSetFileStorage.cs, src/GovUk.Education.ExploreEducationStatistics.Admin/Services/Interfaces/IReleaseDataFileService.cs, src/GovUk.Education.ExploreEducationStatistics.Admin/Services/ReleaseDataFileService.cs, src/GovUk.Education.ExploreEducationStatistics.Admin/ViewModels/DataSetUploadResultViewModel.cs, src/explore-education-statistics-admin/src/pages/release/data/ReleaseDataFileReplacePage.tsx, src/explore-education-statistics-admin/src/pages/release/data/components/DataSetUploadModalConfirm.tsx, src/explore-education-statistics-admin/src/pages/release/data/components/ReleaseDataUploadsSection.tsx, src/explore-education-statistics-admin/src/pages/release/data/components/__tests__/ReleaseDataUploadsSection.test.tsx, src/explore-education-statistics-admin/src/services/releaseDataFileService.ts, tests/robot-tests/tests/admin/bau/upload_files.robot, tests/robot-tests/tests/libs/admin-common.robot, tests/robot-tests/tests/libs/tables-common.robot
This work applies a staged approach to data set uploads for the remaining upload methods (CSV file pair, and zipped CSV file pair), to match the process created for bulk zip uploads in preparation for the screener integration.
The process is; the files are uploaded to the server, validated, then uploaded into a temp container with a result returned to the user. When the screener is integrated, the result will be included in this response. When validation succeeds, the user can then manually trigger the import - this process used to be performed automatically as part of the upload.
- I renamed the bulk zip-specific view model to `DataSetUploadResultViewModel` to represent consolidation. The name might stay the same when the screener is integrated, but the structure will change to include …
=> EES-5708: Consolidate remaining data set upload methods to use a shared approach

src/GovUk.Education.ExploreEducationStatistics.Content.Search.FunctionApp/GovUk.Education.ExploreEducationStatistics.Content.Search.FunctionApp.csproj
This PR fixes the build error seen during the CodeQL autobuild action:
'Could not copy the file obj\GovUk.Education.ExploreEducationStatistics.Content.Search.FunctionApp\release\extensions.json' because it was not found.'
It was reproducible locally with `dotnet clean` followed by `dotnet publish` on the Search solution file.
```
$ dotnet publish GovUk.Education.ExploreEducationStatistics.Search.sln
Determining projects to restore...
Restored C:\Users\BenOutram\dev\ees\src\GovUk.Education.ExploreEducationStatistics.Content.Search.FunctionApp\GovUk.Education.ExploreEducationStatistics.Content.Search.FunctionApp.csproj (in 333 ms).
Restored C:\Users\BenOutram\dev\ees\src\GovUk.Education.ExploreEducationStatistics.Content.Search.FunctionApp.Tests\GovUk.Education.ExploreEducationStatistics.Con …
```
=> EES-6046 Fix build error seen in CodeQL Github action build

src/GovUk.Education.ExploreEducationStatistics.Admin/Services/Public.Data/PublicDataApiClient.cs, src/GovUk.Education.ExploreEducationStatistics.Public.Data.Api.Tests/Controllers/DataSetVersionsControllerTests.cs, src/GovUk.Education.ExploreEducationStatistics.Public.Data.Api.Tests/Controllers/DataSetsControllerGetQueryTests.cs, src/GovUk.Education.ExploreEducationStatistics.Public.Data.Api.Tests/Controllers/DataSetsControllerPostQueryTests.cs, src/GovUk.Education.ExploreEducationStatistics.Public.Data.Api.Tests/Controllers/DataSetsControllerTests.cs, src/GovUk.Education.ExploreEducationStatistics.Public.Data.Api.Tests/Extensions/HttpClientExtensions.cs, src/GovUk.Education.ExploreEducationStatistics.Public.Data.Api.Tests/Fixture/IntegrationTestFixture.cs, src/GovUk.Education.ExploreEducationStatistics.Public.Data.Api.Tests/Fixture/TestApplicationFactory.cs, src/GovUk.Education.ExploreEducationStatistics.Public.Data.Api.Tests/Security/AuthorizationHandlers/QueryDataSetVersionAuthorizationHandlerTests.cs, src/GovUk.Education.ExploreEducationStatistics.Public.Data.Api.Tests/Security/AuthorizationHandlers/ViewDataSetAuthorizationHandlerTests.cs, src/GovUk.Education.ExploreEducationStatistics.Public.Data.Api.Tests/Security/AuthorizationHandlers/ViewDataSetVersionAuthorizationHandlerTests.cs, src/GovUk.Education.ExploreEducationStatistics.Public.Data.Api/Constants/RequestHeaderNames.cs, src/GovUk.Education.ExploreEducationStatistics.Public.Data.Api/Security/AuthorizationHandlers/QueryDataSetVersionAuthorizationHandler.cs, src/GovUk.Education.ExploreEducationStatistics.Public.Data.Api/Services/AnalyticsService.cs, src/GovUk.Education.ExploreEducationStatistics.Public.Data.Api/Services/DataSetService.cs, src/GovUk.Education.ExploreEducationStatistics.Public.Data.Api/Services/DataSetVersionChangeService.cs, src/GovUk.Education.ExploreEducationStatistics.Public.Data.Api/Services/PreviewTokenService.cs, src/GovUk.Education.ExploreEducationStatistics.Public.Data.Api/Services/Security/AuthorizationHandlerService.cs, src/GovUk.Education.ExploreEducationStatistics.Public.Data.Utils/Requests/RequestHeaderNames.cs, src/explore-education-statistics-common/src/services/api/index.ts
This PR:
- adds the capturing of Public API "Get Changes" calls to analytics.
- refactors AnalyticsService to deal with its own exceptions rather than client code, allowing for cleaner calls from dependent services.
In addition to the above, this PR also adds filtering out of Public API calls from Analytics that originated from the EES service itself.  For example, Admin calls the Public API to generate the changelog when creating a new version of a data set, the Public Site's "API data set" pages call the API to list data set versions etc.  These calls all now pass a special header indicating that they originated from components of the EES service itself, and therefore they are filtered out in AnalyticsService.
There is also an incidental change in TestApplicationFactory to make the …
=> EES-6091 - added capturing of Public API "Get Changes" calls to analytics

infrastructure/templates/common/components/event-grid/eventGridMessaging.bicep, infrastructure/templates/public-api/components/fileShare.bicep, infrastructure/templates/public-api/components/storageAccount.bicep, infrastructure/templates/search/application/eventMessaging.bicep
This PR fixes the following Bicep linter rule warnings seen in the Search Infrastructure and Deploy pipeline.
```
eventGridMessaging.bicep(1,10) : Warning no-unused-imports: Import "abbreviations" is declared but never used. [https://aka.ms/bicep/linter/no-unused-imports]
eventMessaging.bicep(6,10) : Warning no-unused-imports: Import "abbreviations" is declared but never used. [https://aka.ms/bicep/linter/no-unused-imports]
fileShare.bicep(1,10) : Warning no-unused-imports: Import "responseTimeConfig" is declared but never used. [https://aka.ms/bicep/linter/no-unused-imports]
fileShare.bicep(2,40) : Warning no-unused-imports: Import "staticMaxGreaterThanZero" is declared but never used. [https://aka.ms/bicep/linter/no-unused-imports]
fileShare.bicep(2,96) : Warning no-unused-imports: …
```
=> Fix linter warnings in Search pipeline

src/GovUk.Education.ExploreEducationStatistics.Publisher/Services/MethodologyService.cs
If controller requests a methodology using an unknown key then the Methodology service is returning null - despite the interface being non-nullable. The controller does not check this value and passes it into a method that will encounter an null ref exception almost immediately. Instead, if the methodology isn't found, raise a more appropriate exception with a useful message at that point.
=> Find unknown methodology

src/GovUk.Education.ExploreEducationStatistics.Events/Extensions/ServiceCollectionExtensions.cs
Whilst the cast is not strictly necessary, it helps to inform the compiler (and the reader!) that this is a factory method. The compiler suggests that we've provided the method name and it looks like we might have meant to invoke it - which is a fair assumption.
=> Add explicit cast to aid compiler

src/GovUk.Education.ExploreEducationStatistics.Events.Tests/EventGrid/Builders/EventRaiserMockBuilder.cs
Prevent null event being added to the list of mock events, since a null event doesn't make sense. 
Then we can safely assume that none of the events stored in the list are null after that.
=> Event Raiser Mock

src/GovUk.Education.ExploreEducationStatistics.Admin/Security/SecurityUtils.cs, src/GovUk.Education.ExploreEducationStatistics.Admin/Services/Methodologies/MethodologyContentService.cs
- SecurityUtils is using nullable notation but nullable was not enabled. Fixed.
- If a content block could not be created then throw immediately instead of waiting for a null ref
=> Simple fixes.

src/GovUk.Education.ExploreEducationStatistics.Admin/Extensions/ConfigurationExtensions.cs, src/GovUk.Education.ExploreEducationStatistics.Admin/Extensions/StringExtensions.cs, src/GovUk.Education.ExploreEducationStatistics.Admin/Startup.cs
These config values are all assumed to exist and the code goes on to fail at some point if they are missing. Instead, fail fast and indicate that the config value is missing immediately:
- CoreStorage
- PublicStorage
- PublisherStorage
- OpenIdConnectIdentityFramework.Authority
Plus some other minor changes. See my comments.
=> Make config required

src/GovUk.Education.ExploreEducationStatistics.Events/PublicationChangedEvent.cs, src/GovUk.Education.ExploreEducationStatistics.Events/ReleaseSlugChangedEvent.cs, src/GovUk.Education.ExploreEducationStatistics.Events/ThemeChangedEvent.cs
The new event payloads all have non-optional properties. These needed to be marked as `required`.
=> Event properties are non-optional therefore mark as required

src/explore-education-statistics-admin/src/pages/release/pre-release/components/PreReleaseUserAccessForm.tsx
Quick suggested content change as we have some analysts still adding jobshare or mailbox accounts instead of individual emails and then finding on pre-release day people can't access the preview.
Needs a dev to pick up and make sure builds / tests run, and formatting is appropriate (line might want splitting into two depending on our styling rules).
=> Add jobshare warning to PreReleaseUserAccessForm

src/GovUk.Education.ExploreEducationStatistics.Public.Data.Api.Tests/Analytics/AnalyticsTestUtils.cs, src/GovUk.Education.ExploreEducationStatistics.Public.Data.Api.Tests/Controllers/DataSetVersionsControllerTests.cs, src/GovUk.Education.ExploreEducationStatistics.Public.Data.Api.Tests/Controllers/DataSetsControllerGetQueryTests.cs, src/GovUk.Education.ExploreEducationStatistics.Public.Data.Api.Tests/Controllers/DataSetsControllerPostQueryTests.cs, src/GovUk.Education.ExploreEducationStatistics.Public.Data.Api.Tests/Controllers/DataSetsControllerTests.cs, src/GovUk.Education.ExploreEducationStatistics.Public.Data.Api/Services/DataSetService.cs
This PR:
- adds the capture of the final DataSetVersion-level Public API call to analytics - that of the version "summary".  This is in the `DataSetService.GetVersion()` method.
- breaks out common assertions around analytics into a reusable assertions class.
- breaks out common Theory data around analytics testing into a reusable class.
=> EES-6089 - capture Public API "data set version summary" call

tests/robot-tests/tests/general_public/statistics_page_azure_search.robot
This PR adds a robot test for the find stats page when azure search is enabled (behind the feature flag).
It doesn't run locally, only on dev, preprod and prod environments as the azure search should already be configured for those environments. 
When this feature work goes live, we can replace the existing `statistics_page.robot` tests with this. 
We are intentionally not checking for search result _content_ as we can't guarantee what will be returned by azure search.
=> EES-6174 Add robot test for azure search find stats page

src/GovUk.Education.ExploreEducationStatistics.Public.Data.Api.Tests/Analytics/AnalyticsTestUtils.cs, src/GovUk.Education.ExploreEducationStatistics.Public.Data.Api.Tests/Controllers/DataSetVersionsControllerTests.cs, src/GovUk.Education.ExploreEducationStatistics.Public.Data.Api.Tests/Controllers/DataSetsControllerGetQueryTests.cs, src/GovUk.Education.ExploreEducationStatistics.Public.Data.Api.Tests/Controllers/DataSetsControllerPostQueryTests.cs, src/GovUk.Education.ExploreEducationStatistics.Public.Data.Api.Tests/Controllers/DataSetsControllerTests.cs, src/GovUk.Education.ExploreEducationStatistics.Public.Data.Api.Tests/Extensions/HttpClientExtensions.cs, src/GovUk.Education.ExploreEducationStatistics.Public.Data.Api.Tests/Services/TestAnalyticsPathResolver.cs, src/GovUk.Education.ExploreEducationStatistics.Public.Data.Api.Tests/Strategies/AnalyticsWriteDataSetLevelCallsStrategyTests.cs, src/GovUk.Education.ExploreEducationStatistics.Public.Data.Api.Tests/Strategies/__snapshots__/AnalyticsWriteDataSetCallsStrategyTests.ReportTests.CallWrittenSuccessfully_WithCoreDataSetDetails.snap, src/GovUk.Education.ExploreEducationStatistics.Public.Data.Api.Tests/Strategies/__snapshots__/AnalyticsWriteDataSetCallsStrategyTests.ReportTests.CallWrittenSuccessfully_WithPreviewToken.snap, src/GovUk.Education.ExploreEducationStatistics.Public.Data.Api/Extensions/AnalyticsServiceCollectionExtensions.cs, src/GovUk.Education.ExploreEducationStatistics.Public.Data.Api/Requests/AnalyticsCaptureRequests.cs, src/GovUk.Education.ExploreEducationStatistics.Public.Data.Api/Services/AnalyticsPathResolver.cs, src/GovUk.Education.ExploreEducationStatistics.Public.Data.Api/Services/AnalyticsPathResolverBase.cs, src/GovUk.Education.ExploreEducationStatistics.Public.Data.Api/Services/AnalyticsService.cs, src/GovUk.Education.ExploreEducationStatistics.Public.Data.Api/Services/DataSetService.cs, src/GovUk.Education.ExploreEducationStatistics.Public.Data.Api/Services/Interfaces/IAnalyticsPathResolver.cs, src/GovUk.Education.ExploreEducationStatistics.Public.Data.Api/Services/Interfaces/IAnalyticsService.cs, src/GovUk.Education.ExploreEducationStatistics.Public.Data.Api/Services/LocalAnalyticsPathResolver.cs, src/GovUk.Education.ExploreEducationStatistics.Public.Data.Api/Strategies/AnalyticsWriteDataSetCallsStrategy.cs
This PR:
- adds the first of a set of DataSet-level API calls - this time simply "Get summary".
- restructures the Public API's AnalyticsPathResolver to use an AnalyticsPathResolverBase to reduce duplication.
- a few other minor changes to improve readability.
=> EES-6085 - capture Public API "data set summary" call

infrastructure/parameters/prod.parameters.json, infrastructure/templates/template.json
This PR removes the `azureSearchExists` flag from the infrastructure ARM template.
It provided a conditional check on the availability of the Azure AI Search resource and can be removed now it is available in all Azure environments.
Removing it will mean that the environment variables `AZURE_SEARCH_ENDPOINT` and `AZURE_SEARCH_QUERY_KEY` will have values set during the next Production deploy. They are needed by the public site frontend for the new Find Statistics search.
=> EES-6024 Remove `azureSearchExists` flag from infrastructure template

src/GovUk.Education.ExploreEducationStatistics.Events/ReleaseVersionPublishedEvent.cs
The reason when a release was being published that nothing was happening was because the event was missing the ReleaseVersionId!
=> Release Version Published event was missing Release Version Id!

src/explore-education-statistics-admin/src/pages/release/datablocks/components/chart/ChartAxisConfiguration.tsx, src/explore-education-statistics-admin/src/pages/release/datablocks/components/chart/__tests__/ChartAxisConfiguration.test.tsx, src/explore-education-statistics-admin/src/pages/release/datablocks/components/chart/__tests__/ChartConfiguration.test.tsx, src/explore-education-statistics-admin/src/pages/release/datablocks/components/chart/__tests__/ChartReferenceLinesConfiguration.test.tsx, src/explore-education-statistics-admin/src/pages/release/datablocks/components/chart/contexts/__tests__/ChartBuilderFormsContext.test.tsx, src/explore-education-statistics-admin/src/pages/release/datablocks/components/chart/reducers/__tests__/chartBuilderReducer.test.ts, src/explore-education-statistics-common/src/modules/charts/components/HorizontalBarBlock.tsx, src/explore-education-statistics-common/src/modules/charts/components/LineChartBlock.tsx, src/explore-education-statistics-common/src/modules/charts/components/MapBlock.tsx, src/explore-education-statistics-common/src/modules/charts/components/VerticalBarBlock.tsx, src/explore-education-statistics-common/src/modules/charts/types/chart.ts
because rotated text is bad for accessibility.
=> EES-6134 remove option to rotate chart axis labels

src/GovUk.Education.ExploreEducationStatistics.Content.Search.FunctionApp.Tests/Functions/OnReleaseVersionPublished/OnReleaseVersionPublishedFunctionTests.cs, src/GovUk.Education.ExploreEducationStatistics.Content.Search.FunctionApp/Functions/EventHandlers/OnReleaseVersionPublished/OnReleaseVersionPublishedFunction.cs
If the release being published is the first one, then there is no previous searchable document to remove. Therefore do not attempt to remove one.
=> Fix first release bug

src/explore-education-statistics-frontend/src/components/HomepageCard.module.scss, src/explore-education-statistics-frontend/src/components/HomepageCard.tsx, src/explore-education-statistics-frontend/src/pages/index.tsx, tests/robot-tests/tests/general_public/miscellaneous.robot
This PR moves the data catalogue page link on the homepage from under 'Supporting information' to be a CTA box alongside the other two boxes.
As part of this work, I have pulled the homepage box links out into a separate component to reduce repetition. 
It also adds google analytics tracking for when the homepage links are clicked on. N.b I haven't tested the GA tracking locally as don't have the config set up, but am 90% sure it should work as the same function is used elsewhere in the codebase - we should be able to test it easily on the dev environment.
=> EES-6199 homepage data catalogue link

src/explore-education-statistics-admin/src/pages/release/data/__tests__/ReleaseDataFileReplacePage.test.tsx, src/explore-education-statistics-admin/src/pages/release/data/components/DataFilesReplacementTable.tsx, src/explore-education-statistics-admin/src/pages/release/data/components/DataFilesReplacementTableRow.tsx, src/explore-education-statistics-admin/src/pages/release/data/components/ImporterStatus.tsx, src/explore-education-statistics-admin/src/pages/release/data/components/ReleaseDataUploadsSection.tsx, src/explore-education-statistics-admin/src/pages/release/data/components/__tests__/DataFilesReplacementTableRow.test.tsx, src/explore-education-statistics-admin/src/pages/release/data/components/__tests__/DataFilesTableRow.test.tsx, src/explore-education-statistics-admin/src/pages/release/data/components/__tests__/ReleaseDataUploadsSection.test.tsx, src/explore-education-statistics-admin/src/queries/dataFileReplacementQueries.ts, src/explore-education-statistics-admin/src/queries/releaseDataFileQueries.ts, tests/robot-tests/tests/admin/bau/release_status.robot
Adds functionality to confirm or cancel valid data replacements from the data and files page.
Some preparatory work has been added and commented out for adding a bulk confirm button, this will be picked up in a subsequent ticket.
=> EES-5548 confirm replacements from data files page

tests/robot-tests/tests/admin_and_public/bau/data_reordering.robot, tests/robot-tests/tests/admin_and_public_2/bau/publish_release_and_amend.robot
This PR:
- updates expected text on the Data Replacement page in line with the UI changes made in https://github.com/dfe-analytical-services/explore-education-statistics/pull/5977
=> EES-5548 - updated UI tests to be in line with UI changes

src/GovUk.Education.ExploreEducationStatistics.Content.Search.FunctionApp.Tests/Builders/ContentApiClientMockBuilder.cs, src/GovUk.Education.ExploreEducationStatistics.Content.Search.FunctionApp.Tests/Services/CheckSearchableDocuments/ReleaseSummaryRetrieverTests.cs, src/GovUk.Education.ExploreEducationStatistics.Content.Search.FunctionApp/Services/CheckSearchableDocuments/ReleaseSummaryRetriever.cs
If a release summary can not be retrieved, log it and carry on. Make our tool more resilient to the duff data in Dev.
=> Searchable Docs Integrity Tool

src/explore-education-statistics-frontend/src/services/azurePublicationService.ts
This PR increases the maximum number of search facet terms count from 60 to 150 to accommodate for the growing number of themes in the Dev environment. The facet count parameter limits the number of unique facet terms which are returned.
It was set to 60 in the frontend search options, but there are currently 102 unique theme id’s in search results in the Dev environment.
Documentation on `count` from [Faceted navigation examples - Azure AI Search](https://learn.microsoft.com/en-us/azure/search/search-faceted-navigation-examples#facet-parameters-and-syntax):
> Default is 10. There's no upper limit, but higher values degrade performance, especially if the faceted field contains a large number of unique terms. This is due to the way facet queries are distributed across shards. You can set …
=> EES-6222 Increase max search facet terms count from 60 to 150

src/GovUk.Education.ExploreEducationStatistics.Admin.Tests/Services/DataSetFileStorageTests.cs, src/GovUk.Education.ExploreEducationStatistics.Admin.Tests/Services/DataSetValidatorTests.cs, src/GovUk.Education.ExploreEducationStatistics.Admin.Tests/Services/DataSetVersionMappingServiceTests.cs, src/GovUk.Education.ExploreEducationStatistics.Admin.Tests/Services/ReleaseVersionServicePermissionTests.cs, src/GovUk.Education.ExploreEducationStatistics.Admin.Tests/Services/ReleaseVersionServiceTests.cs, src/GovUk.Education.ExploreEducationStatistics.Admin.Tests/Services/ReplacementServiceTests.cs, src/GovUk.Education.ExploreEducationStatistics.Admin/Services/DataSetFileStorage.cs, src/GovUk.Education.ExploreEducationStatistics.Admin/Services/DataSetValidator.cs, src/GovUk.Education.ExploreEducationStatistics.Admin/Services/Public.Data/DataSetVersionMappingService.cs, src/GovUk.Education.ExploreEducationStatistics.Admin/Services/ReleaseVersionService.cs, src/GovUk.Education.ExploreEducationStatistics.Admin/Services/ReplacementService.cs, src/GovUk.Education.ExploreEducationStatistics.Admin/Startup.cs, src/GovUk.Education.ExploreEducationStatistics.Common.Tests/FunctionsIntegrationTest.cs, src/GovUk.Education.ExploreEducationStatistics.Common/Options/FeatureFlagsOptions.cs, src/GovUk.Education.ExploreEducationStatistics.Public.Data.Processor/Functions/CreateNextDataSetVersionMappingsFunction.cs, src/GovUk.Education.ExploreEducationStatistics.Public.Data.Processor/ProcessorHostBuilder.cs, src/GovUk.Education.ExploreEducationStatistics.Public.Data.Processor/Services/DataSetVersionMappingService.cs, src/GovUk.Education.ExploreEducationStatistics.Public.Data.Processor/Services/DataSetVersionService.cs
This PR renames the config options class FeatureFlags to FeatureFlagsOptions.
This PR simplifies the PR https://github.com/dfe-analytical-services/explore-education-statistics/pull/6035/commits/20d0a46370220ccff9adb78caa3ce2c86d36cef2 by not polluting that PR with these changes where FeatureFlags is renamed to FeatureFlagsOptions
=> Rename FeatureFlags.cs to FeatureFlagsOptions.cs across the codebase to abide by convention in place.

src/GovUk.Education.ExploreEducationStatistics.Admin/Services/ThemeService.cs
Instead of attempting to invalidate the cache in parallel (which errors), do it sequentially.
=> EES-6226 - Concurrent cache invalidation bug fix

src/GovUk.Education.ExploreEducationStatistics.Content.Model/Extensions/PublicationExtensions.cs, src/GovUk.Education.ExploreEducationStatistics.Events/ReleaseVersionPublishedEvent.cs, src/GovUk.Education.ExploreEducationStatistics.Publisher.Tests/Builders/Models/PublicationBuilder.cs, src/GovUk.Education.ExploreEducationStatistics.Publisher.Tests/Builders/Services/ContentDbContextMockBuilder.cs, src/GovUk.Education.ExploreEducationStatistics.Publisher.Tests/Services/PublisherEventRaiserTests.cs, src/GovUk.Education.ExploreEducationStatistics.Publisher.Tests/Services/PublishingCompletionServiceTests.cs, src/GovUk.Education.ExploreEducationStatistics.Publisher/Services/PublishedPublicationInfo.cs, src/GovUk.Education.ExploreEducationStatistics.Publisher/Services/PublisherEventRaiser.cs, src/GovUk.Education.ExploreEducationStatistics.Publisher/Services/PublishingCompletionService.cs
When a release is published, add a flag to the event to indicate whether the parent publication is archived.
This is because the search functionality does not want to create searchable documents for archived publications.
=> EES-6235 Release Version Published Event - Add Is Publication Archived flag

infrastructure/templates/search/application/searchDocsFunction.bicep, infrastructure/templates/search/application/searchDocsFunctionEventSubscriptions.bicep, infrastructure/templates/search/types.bicep, src/GovUk.Education.ExploreEducationStatistics.Content.Search.FunctionApp.Tests/Functions/OnPublicationDeleted/OnPublicationDeletedFunctionTests.cs, src/GovUk.Education.ExploreEducationStatistics.Content.Search.FunctionApp/Functions/EventHandlers/OnPublicationDeleted/Dtos/PublicationDeletedEventDto.cs, src/GovUk.Education.ExploreEducationStatistics.Content.Search.FunctionApp/Functions/EventHandlers/OnPublicationDeleted/OnPublicationDeletedFunction.cs, src/GovUk.Education.ExploreEducationStatistics.Content.Search.FunctionApp/local.settings.json, src/GovUk.Education.ExploreEducationStatistics.Events/PublicationDeletedEvent.cs
This PR adds event handling to the Search Function App for deleting publications.
When a theme is deleted (which only happens for UI Test themes in the Dev environment), the Admin will publish an event with type 'publication-deleted' onto the 'publication-changed' topic endpoint for every publication in the theme.
A new 'OnPublicationDeleted' event handler function has been added to the Search Function App and is subscribed to this event type via a new `publication-deleted-queue' Storage queue with a queue trigger binding.
On deletion of a publication, the 'OnPublicationDeleted' in turn triggers the existing 'RemoveSearchableDocument' command handler function to remove the searchable document for the latest published release of the publication. The payload of the event will contain the …
=> EES-6253 Add event handling to Search function app for deleting publications

src/GovUk.Education.ExploreEducationStatistics.Events/EventTopicOptionsKeys.cs, src/GovUk.Education.ExploreEducationStatistics.Events/EventTypes.cs, src/GovUk.Education.ExploreEducationStatistics.Events/PublicationArchivedEvent.cs, src/GovUk.Education.ExploreEducationStatistics.Events/PublicationChangedEvent.cs, src/GovUk.Education.ExploreEducationStatistics.Events/PublicationDeletedEvent.cs, src/GovUk.Education.ExploreEducationStatistics.Events/PublicationLatestPublishedReleaseReorderedEvent.cs, src/GovUk.Education.ExploreEducationStatistics.Events/PublicationRestoredEvent.cs, src/GovUk.Education.ExploreEducationStatistics.Events/ReleaseSlugChangedEvent.cs, src/GovUk.Education.ExploreEducationStatistics.Events/ReleaseVersionPublishedEvent.cs, src/GovUk.Education.ExploreEducationStatistics.Events/ThemeChangedEvent.cs
This PR defines event types and event topic options keys as static constants.
This means all the constants are defined in a single place, and options keys which are reused by different event type classes don’t have a possibility of diverging.
This improvement was suggested in a comment by @leeoades in https://github.com/dfe-analytical-services/explore-education-statistics/pull/6050#discussion_r2154886066.
=> EES-6255 Define event types and event topic options keys as static constants

src/explore-education-statistics-frontend/src/modules/find-statistics/FindStatisticsPageAzure.tsx, src/explore-education-statistics-frontend/src/modules/find-statistics/__tests__/FindStatisticsPageAzure.test.tsx
Currently, if you filter by a facet (theme, release type), the remaining items in the filter dropdown show '(0)' after them (as there are no results returned with the current filter applied!)
This PR changes this, so that if you filter by one dimension, we don't append any counts to the other items in the dropdown for that dimension.
So if you filter by theme, the dropdown for 'theme' will list themes without counts, but the release version dropdown will show counts. Vice versa,
If you filter by both facets, no items will have counts next to them.
=> EES-6246 Only show counts next to filter options if no filter currently applied

src/explore-education-statistics-frontend/src/modules/find-statistics/FindStatisticsPageAzure.tsx, src/explore-education-statistics-frontend/src/services/azurePublicationService.ts
There was an off by one error on the pagination. Now fixed so that we don't think there's an extra page when totalResults is 10, 20, 30 etc
=> EES-6250 find stats pagination fix

src/GovUk.Education.ExploreEducationStatistics.Admin.Tests/MockBuilders/AdminEventRaiserMockBuilder.cs, src/GovUk.Education.ExploreEducationStatistics.Admin.Tests/Services/AdminEventRaiserTests.cs, src/GovUk.Education.ExploreEducationStatistics.Admin.Tests/Services/ThemeServiceTests.cs, src/GovUk.Education.ExploreEducationStatistics.Admin/Services/AdminEventRaiser.cs, src/GovUk.Education.ExploreEducationStatistics.Admin/Services/Interfaces/IAdminEventRaiser.cs, src/GovUk.Education.ExploreEducationStatistics.Admin/Services/ThemeService.cs, src/GovUk.Education.ExploreEducationStatistics.Content.Model.Tests/Fixtures/PublicationGeneratorExtensions.cs, src/GovUk.Education.ExploreEducationStatistics.Content.Search.FunctionApp.Tests/Functions/EventHandlers/OnPublicationDeleted/OnPublicationDeletedFunctionTests.cs, src/GovUk.Education.ExploreEducationStatistics.Content.Search.FunctionApp/Domain/LatestPublishedReleaseInfo.cs, src/GovUk.Education.ExploreEducationStatistics.Content.Search.FunctionApp/Functions/EventHandlers/OnPublicationDeleted/Dtos/PublicationDeletedEventDto.cs, src/GovUk.Education.ExploreEducationStatistics.Content.Search.FunctionApp/Functions/EventHandlers/OnPublicationDeleted/OnPublicationDeletedFunction.cs, src/GovUk.Education.ExploreEducationStatistics.Events/LatestPublishedReleaseInfo.cs, src/GovUk.Education.ExploreEducationStatistics.Events/PublicationDeletedEvent.cs
This PR changes the Admin to publish an event of type `PublicationDeletedEvent` for every publication that is deleted when deleting a theme.
The Search Function App has already been subscribed to this event by changes made in https://github.com/dfe-analytical-services/explore-education-statistics/pull/6050, and will remove any searchable document for the deleted publication’s latest published release.
=> EES-6254 Raise an event when a publication is deleted

src/GovUk.Education.ExploreEducationStatistics.Admin/Services/DataSetValidator.cs, src/GovUk.Education.ExploreEducationStatistics.Admin/Services/ReleaseDataFileService.cs, src/GovUk.Education.ExploreEducationStatistics.Common.Tests/Model/EitherTest.cs, src/GovUk.Education.ExploreEducationStatistics.Common/Model/Either.cs, src/GovUk.Education.ExploreEducationStatistics.Public.Data.Processor/Services/DataSetVersionService.cs
Added support for `OnSuccessAll()` when using bare Eithers, rather than Task<Eithers>.
Removed slightly ambiguous and very rarely-used variant of `OnSuccessVoid(...)` which can be replaced with an `OnSuccessDo(...).OnSuccessVoid()`.
=> EES-5999 - added OnSuccessAll() variant for non-Task based Eithers

infrastructure/templates/search/scripts/SetupSearchService.ps1, src/GovUk.Education.ExploreEducationStatistics.Content.Search.FunctionApp.Tests/Extensions/ReleaseSearchableDocumentExtensionsTests.cs, src/GovUk.Education.ExploreEducationStatistics.Content.Search.FunctionApp/Extensions/ReleaseSearchableDocumentExtensions.cs
This PR follows up https://github.com/dfe-analytical-services/explore-education-statistics/pull/6074 with a related bugfix. During testing we discovered that unicode characters can creep into a release slug if they are added to a release label while editing the release in the Admin. This prevents the searchable document blob from being uploaded after the update event is triggered.
As explained in https://github.com/dfe-analytical-services/explore-education-statistics/pull/6074, metadata key/value pairs are set using HTTP headers when the searchable document blobs are uploaded and must be valid headers containing only ASCII characters.
This PR applies the same change that was made for theme title, publication title, publication summary and publication slug by Base64 encoding the release …
=> EES-6285 Base64 encode `releaseSlug` for safe use in HTTP headers

src/GovUk.Education.ExploreEducationStatistics.Admin/Services/ReleaseDataFileService.cs
This PR fixes a bug where the auth for the GetDataSetAccoutrementsSummary endpoint was always failing as the db query didn't include `ReleaseFile.ReleaseVersion`. That's it!
=> EES-6269 Fix GetAccoutrementsSummary bug

src/explore-education-statistics-common/src/modules/charts/components/HorizontalBarBlock.tsx, src/explore-education-statistics-common/src/modules/charts/components/LineChartBlock.tsx, src/explore-education-statistics-common/src/modules/charts/components/VerticalBarBlock.tsx, src/explore-education-statistics-common/src/modules/charts/util/__tests__/createDataSetCategories.test.ts, src/explore-education-statistics-common/src/modules/charts/util/createDataSetCategories.ts
Fixes a bug where clicking 'sort ascending' in the chart major axis configuration tab could cause the order of the bars within groups and the legend to change. This only happened if the data sets had been reordered as that could effect the order of the data sets withing the groupings.
It's a bit hard to explain what was happening, but I'll try...
Example A - the chart is grouped by filter (school type) and the first data set has the filter primary, so it's the first group in the axis. 
Example B - the chart is also grouped by filter (school type) and the data sets have been reordered so the first one has the filter secondary, so it's first in the axis.  
The ordering of the bars & legend comes from the ordering of the (in this case) indicators in the data sets for the first group in the …
=> EES-6245 fix weird behaviour when reversing chart major axis

infrastructure/templates/common/application/eventMessaging.bicep, infrastructure/templates/common/application/privateDnsZones.bicep, infrastructure/templates/common/components/containerisedFunctionApp.bicep, infrastructure/templates/common/components/event-grid/eventGridCustomTopic.bicep, infrastructure/templates/common/components/event-grid/eventGridMessaging.bicep, infrastructure/templates/common/components/functionApp.bicep, infrastructure/templates/common/components/privateDnsZone.bicep, infrastructure/templates/common/components/privateEndpoint.bicep, infrastructure/templates/common/dnsZones.bicep, infrastructure/templates/common/types.bicep, infrastructure/templates/public-api/components/containerAppPrivateDns.bicep, infrastructure/templates/public-api/components/durableFunctionApp.bicep, infrastructure/templates/public-api/components/postgreSqlFlexibleServer.bicep, infrastructure/templates/public-api/components/storageAccount.bicep, infrastructure/templates/public-api/main.bicep, infrastructure/templates/public-api/types.bicep, infrastructure/templates/search/application/eventMessaging.bicep, infrastructure/templates/search/main.bicep, infrastructure/templates/search/types.bicep, infrastructure/templates/template.json
This PR configures private endpoints for the Azure Event Grid custom topics used for publishing events.
It disables access to topics from public networks. Access is now restricted to private endpoints only. Private endpoints allow ingress of events directly from the virtual network to the custom topics securely over a private link without going through the public internet.
This change involves:
- Creating a subnet within the virtual network to assign private IP addresses to Event Grid custom topics.
- Creating a private DNS zone allowing applications in the virtual network to connect to the Event Grid using the same connection string and role based authorization that was already in place.
- Creating private endpoints for each Event Grid custom topic.
⚠️ The order of deploying is important …
=> EES-6036 Configure private endpoints for Event Grid topics and restrict access to private endpoints only

src/GovUk.Education.ExploreEducationStatistics.Notifier.Tests/Functions/ReleasePublishingFeedbackFunctionTests.cs, src/GovUk.Education.ExploreEducationStatistics.Notifier/Functions/ReleasePublishingFeedbackFunction.cs, src/GovUk.Education.ExploreEducationStatistics.Publisher.Tests/Services/NotificationsServiceTests.cs, src/GovUk.Education.ExploreEducationStatistics.Publisher/Services/NotificationsService.cs
This PR:
- follows up on work done for EES-6240, specifically ignoring the currently-unused Drafter role as well as the already-ignored Approver role.
This means that the global query filters don't need to be ignored anymore.
I've added some extra tests too, which can go when Jack's permissions simplifications work in complete.
=> EES-6240 - additional amendments after talking changes through with Jack. Ignoring Drafter role in addition to Approver role.

infrastructure/parameters/dev.parameters.json, infrastructure/parameters/pre-prod.parameters.json, infrastructure/parameters/test.parameters.json, infrastructure/templates/template.json, src/GovUk.Education.ExploreEducationStatistics.Notifier.Tests/Services/EmailServiceTests.cs, src/GovUk.Education.ExploreEducationStatistics.Notifier/Functions/ReleasePublishingFeedbackFunction.cs, src/GovUk.Education.ExploreEducationStatistics.Notifier/Options/AppOptions.cs, src/GovUk.Education.ExploreEducationStatistics.Notifier/Services/EmailService.cs, src/GovUk.Education.ExploreEducationStatistics.Notifier/appsettings.Local.json.example
This PR:
- adds the ability to suppress exceptions being thrown when emails are sent to recipients that are not within the GovUK Notify team when using Team-only API keys.
This work comes about because alerts were being raised from Notifier on Dev due to it attempting to send to recipients like "ees-test.analyst1@education.gov.uk" when a Release is published.  This came about because of the new email functionality introduced in EES-6240.
Now we support a per-environment flag called `SuppressExceptionsForTeamOnlyApiKeyErrors` which is true for all environments except for Production.
The effect of this flag being true is for team-only API exceptions to be caught and converted to logged messages instead, thus preventing them being seen as real errors:
```
[notifier] …
```
=> EES-6240 - suppressing errors from invalid email recipients when using team-only Notify API keys on non-Prod environments.

src/explore-education-statistics-admin/src/pages/release/data/components/DataFilesReplacementTable.tsx, src/explore-education-statistics-admin/src/pages/release/data/components/DataFilesReplacementTableRow.tsx, src/explore-education-statistics-admin/src/pages/release/data/components/DataFilesTable.module.scss, src/explore-education-statistics-admin/src/pages/release/data/components/DataFilesTable.tsx, src/explore-education-statistics-admin/src/pages/release/data/components/__tests__/DataFilesReplacementTableRow.test.tsx
The cancel and confirm buttons for data replacements shouldn't appear until the file has finished processing.
=> EES-6270 don't show cancel and confirm replacement buttons while processing

src/explore-education-statistics-frontend/src/components/SearchFormAzure.tsx, src/explore-education-statistics-frontend/src/components/__tests__/SearchFormAzure.test.tsx, src/explore-education-statistics-frontend/src/modules/find-statistics/__tests__/__data__/testPublicationSuggestions.ts, src/explore-education-statistics-frontend/src/services/azurePublicationService.ts
This PR adds highlighting for the autocomplete results, showing matching terms in bold.
Annoyingly, azure returns highlighted content for each result, but it is either the `title` or `summary`, and we don't know which it is.
So when rendering the results, we figure out which field has been returned with highlights already and try to apply manual highlights to the other field, by working out which highlighted term has been returned by Azure.
Hopefully this process is clear in the code.
Please see [this slack thread](https://exploreeducationstats.slack.com/archives/C065M8V6HRC/p1751637731621039) for more discussion about this issue.
=> EES-6297 highlights for typeahead

src/explore-education-statistics-frontend/src/components/Page.tsx, src/explore-education-statistics-frontend/src/components/TryNewSearchBanner.tsx, src/explore-education-statistics-frontend/src/modules/find-statistics/FindStatisticsPageAzure.tsx, src/explore-education-statistics-frontend/src/modules/find-statistics/FindStatisticsPageCurrent.tsx, src/explore-education-statistics-frontend/src/pages/index.tsx
This PR adds a banner to the home page, the current find stats page, and the new find stats page
=> EES-6248 Add new search banners to home and search pages

infrastructure/templates/template.json, src/GovUk.Education.ExploreEducationStatistics.Admin.Tests/appsettings.IntegrationTest.json, src/GovUk.Education.ExploreEducationStatistics.Admin/Options/DataScreenerClientOptions.cs, src/GovUk.Education.ExploreEducationStatistics.Admin/Startup.cs, src/GovUk.Education.ExploreEducationStatistics.Admin/appsettings.Development.json
Dev environment is referencing the wrong appsettings section name, this PR amends the mixed naming to "DataScreener".
=> EES-5999: Rename appsettings section for the Screener API.

src/explore-education-statistics-frontend/src/modules/find-statistics/FindStatisticsPageAzure.tsx, src/explore-education-statistics-frontend/src/services/azurePublicationService.ts
When a filter is applied (theme or releaseType), we need to show how many items there are for the _other_ filter item options of the same filter type. So we now make an extra request to azure _per applied filter_. Currently, if a filter is applied, we don't show counts next to the items in the dropdowns, as they are all 0 except for the applied filter.
e.g. If we are filtering by theme: we need to show the counts of items in other themes, so request the same search but without the theme filter applied, too.
Details are in [the JIRA ticket](https://dfedigital.atlassian.net/browse/EES-6247).
**Example 1:** We are filtering by search term and theme. There are 6 results total with the current search. But other themes have different results, reflected in the numbers next to them in the …
=> EES-6247 Show better facet counts in filter dropdowns

infrastructure/templates/template.json
The previous changes associated with this work display a list of data set uploads in the UI, and allow manual deletion. Uploads are stored in the temporary `releases-temp` blob storage container, and the import process transfers them from the temporary container to the permanent `releases` container. As such, if an import is triggered on an auto-deleted blob it will generate an error in the app.
Since users can now see uploads (i.e. incomplete imports) in the data uploads section, there's no need to ensure that they are tidied up periodically, this work removes the auto-deletion lifecycle policy.
[[PR which adds the configuration](https://github.com/dfe-analytical-services/explore-education-statistics/pull/5669/files)]
This PR also corrects the Azure Function App resource name.
=> EES-5999: Remove blob auto-deletion after 24h rule, correct resource name

infrastructure/templates/search/application/searchService.bicep, infrastructure/templates/search/components/searchService.bicep, infrastructure/templates/search/main.bicep, infrastructure/templates/search/parameters/main-dev.bicepparam, infrastructure/templates/search/parameters/main-preprod.bicepparam, infrastructure/templates/search/parameters/main-prod.bicepparam, infrastructure/templates/search/parameters/main-test.bicepparam
This PR adds support for configuring the availability and pricing plan of semantic ranking in Azure AI Search in different environments.
Semantic ranking can be
- Disabled
- Available on the free pricing plan
- Available on the standard pricing plan for higher query volumes
The setting applies to all indexes.
The availability is configured for each Azure environment.
- Format file searchService.bicep.
=> EES-6307 Allow configuring availability and pricing plan of semantic ranking in different environments

infrastructure/templates/screener/application/screenerApplicationInsights.bicep, infrastructure/templates/screener/main.bicep, infrastructure/templates/screener/types.bicep, infrastructure/templates/template.json
This PR:
- fixes the Screener URL as used by Admin, by appending `/api/screen` to the end of the URL.
- whitelists the Screener Function App's subnet with Core Storage to allow calls through.
In addition to the above changes, this PR also links Screener's App Insights up with our shared Log Analytics Workspace.
=> EES-6308 - fix Screener URL as used by Admin, and whitelist Screener's subnet with storage

src/GovUk.Education.ExploreEducationStatistics.Admin.Tests/Controllers/Api/DataReplacementControllerTests.cs, src/GovUk.Education.ExploreEducationStatistics.Admin.Tests/Services/ReplacementBatchServiceTests.cs, src/GovUk.Education.ExploreEducationStatistics.Admin.Tests/Services/ReplacementServiceTests.cs, src/GovUk.Education.ExploreEducationStatistics.Admin/Controllers/Api/DataReplacementController.cs, src/GovUk.Education.ExploreEducationStatistics.Admin/Requests/ReplacementRequest.cs, src/GovUk.Education.ExploreEducationStatistics.Admin/Services/Interfaces/IReplacementBatchService.cs, src/GovUk.Education.ExploreEducationStatistics.Admin/Services/Interfaces/IReplacementService.cs, src/GovUk.Education.ExploreEducationStatistics.Admin/Services/ReplacementBatchService.cs, src/GovUk.Education.ExploreEducationStatistics.Admin/Services/ReplacementService.cs, src/GovUk.Education.ExploreEducationStatistics.Admin/Startup.cs, src/GovUk.Education.ExploreEducationStatistics.Admin/Validators/ValidationErrorMessages.cs, src/GovUk.Education.ExploreEducationStatistics.Admin/Validators/ValidationMessages.cs, src/GovUk.Education.ExploreEducationStatistics.Admin/Validators/ValidationUtils.cs, src/explore-education-statistics-admin/src/pages/release/data/components/DataFileReplacementPlan.tsx, src/explore-education-statistics-admin/src/pages/release/data/components/DataFilesReplacementTableRow.tsx, src/explore-education-statistics-admin/src/pages/release/data/components/ReleaseDataUploadsSection.tsx, src/explore-education-statistics-admin/src/pages/release/data/components/__tests__/DataFileReplacementPlan.test.tsx, src/explore-education-statistics-admin/src/queries/dataFileReplacementQueries.ts, src/explore-education-statistics-admin/src/services/dataReplacementService.ts
This PR changes the backend's replacement completion endpoint to accept multiple fileIds, allowing the frontend to complete multiple replacements in a single request to the backend.
This ability to complete multiple replacements in a single request isn't yet being utilised. But it will be when the "Confirm all valid replacements" button is added to the Data and files page as part of EES-6244.
The endpoint has been coded such that if multiple replacements are provided and one errors, the others will still be completed. Despite some of them being successfully replaced, the backend endpoint still returns an error for any that have failed. We do this because in the frontend we would expect none to fail, and so would want to be made aware of any issues, so therefore considered it wiser to blow …
=> EES-6289 Allow completion of multiple replacements at once

src/GovUk.Education.ExploreEducationStatistics.Admin.Tests/Services/ReleaseAmendmentServiceTests.cs, src/GovUk.Education.ExploreEducationStatistics.Admin/Migrations/ContentMigrations/20250714103833_EES6317_AddReleaseVersionPublishingOrganisations.Designer.cs, src/GovUk.Education.ExploreEducationStatistics.Admin/Migrations/ContentMigrations/20250714103833_EES6317_AddReleaseVersionPublishingOrganisations.cs, src/GovUk.Education.ExploreEducationStatistics.Admin/Migrations/ContentMigrations/20250714103833_EES6317_AddReleaseVersionPublishingOrganisations.sql, src/GovUk.Education.ExploreEducationStatistics.Admin/Services/ReleaseAmendmentService.cs, src/GovUk.Education.ExploreEducationStatistics.Content.Model.Tests/Fixtures/OrganisationGeneratorExtensions.cs, src/GovUk.Education.ExploreEducationStatistics.Content.Model.Tests/Fixtures/ReleaseVersionGeneratorExtensions.cs, src/GovUk.Education.ExploreEducationStatistics.Content.Model/Database/ContentDbContext.cs, src/GovUk.Education.ExploreEducationStatistics.Content.Model/Organisation.cs, src/GovUk.Education.ExploreEducationStatistics.Content.Model/ReleaseVersion.cs
This PR contains the backend changes to add publishing organisations to the release version model.
- Add a new type `Organisation` with properties `Id`, `Title`, `Url`, `Created`, and `Updated`.
- Add a unique index on `Title` to prevent duplication organisations being created.
- Add a new property `List<Organisation> PublishingOrganisations` to `ReleaseVersion`.
- Alter the Content database context, setting up a unidirectional many-to-many relationship, override the join table name, and alter the default foreign key column names.
- Add the database migration including granting permission for the content and publisher database users.
- Insert seed data into the database for the 'Department for Education' and 'Skills England' organisations.
- Copy the value of any `PublishingOrganisations` …
=> EES-6317 Add publishing organisations to release version model

src/explore-education-statistics-admin/src/pages/release/content/components/ReleaseContent.tsx, src/explore-education-statistics-frontend/src/modules/find-statistics/PublicationReleasePage.tsx
Quick fix, as `publishingOrganisations` was being returned as an empty array, so the field was rendering as blank
=> EES-6315 Check array length when rendering published by

infrastructure/templates/screener/application/screenerContainerisedFunctionApp.bicep, infrastructure/templates/screener/ci/jobs/deploy-screener-function-app.yml, infrastructure/templates/screener/ci/tasks/deploy-bicep.yml, infrastructure/templates/screener/main.bicep, infrastructure/templates/template.json, src/GovUk.Education.ExploreEducationStatistics.Admin.Tests/Services/DataSetScreenerClientTests.cs, src/GovUk.Education.ExploreEducationStatistics.Admin.Tests/Services/Public.Data/ProcessorClientTests.cs, src/GovUk.Education.ExploreEducationStatistics.Admin.Tests/Services/Public.Data/PublicDataApiClientTests.cs, src/GovUk.Education.ExploreEducationStatistics.Admin/Options/DataScreenerClientOptions.cs, src/GovUk.Education.ExploreEducationStatistics.Admin/Options/IAzureAuthenticationOptions.cs, src/GovUk.Education.ExploreEducationStatistics.Admin/Options/PublicDataApiOptions.cs, src/GovUk.Education.ExploreEducationStatistics.Admin/Options/PublicDataProcessorOptions.cs, src/GovUk.Education.ExploreEducationStatistics.Admin/Services/Authentication/HttpClientAuthenticationManagers.cs, src/GovUk.Education.ExploreEducationStatistics.Admin/Services/DataSetScreenerClient.cs, src/GovUk.Education.ExploreEducationStatistics.Admin/Services/Public.Data/ProcessorClient.cs, src/GovUk.Education.ExploreEducationStatistics.Admin/Services/Public.Data/PublicDataApiClient.cs, src/GovUk.Education.ExploreEducationStatistics.Admin/Startup.cs
This PR:
- adds EasyAuth security between Admin and Screener.
We have added 4 App Registrations into DfE's Entra ID - these registrations represent the Screener Function App for security and permissions purposes.
Screener is set up to enable EasyAuth and to only accept requests from Admin and from the DevOps SPN (for the purposes of pinging its healthcheck endpoint during deployment).  All other requests will receive 401s.  The requests from Admin and DevOps must provide valid access tokens as Bearer tokens.
Admin is set up (via its DataSetScreenerClient) to request Access Tokens in order to talk to Screener via EasyAuth.  Admin requests a valid access token and adds it as a Bearer token to its requests to Screener.
DevOps is set up to request Access Tokens in order to talk to Screener …
=> EES-6023 - add entra id authentication between Screener and Admin

src/GovUk.Education.ExploreEducationStatistics.Notifier/Services/LoggingEmailService.cs
This came out of a Github Copilot recommendation
=> Stops recording user's emails in the logs

infrastructure/templates/search/ci/jobs/deploy-infrastructure.yml, infrastructure/templates/search/ci/tasks/deploy-search-service-config.yml
This PR fixes the value of the `searchServiceIndexerName` parameter of the `deploy-bicep.yml` step in the `deploy-infrastructure.yml` job template.
This is the name of the indexer in the Azure AI Search Service which ultimately gets set as an environment variable **AzureSearch__IndexerName** in the Search Function App.
The value was previously blank after changes made in #6116.
=> 🐛 EES-6329 Fix missing search indexer name

.github/workflows/validate-snapshots.yml
Quick one to remove Jen from the approvers of snapshots as she's not in the team at the moment.
Not applicable 
No need
=> Update snapshot approvers

src/explore-education-statistics-frontend/src/pages/index.tsx
This PR formats `src/explore-education-statistics-frontend/src/pages/index.tsx`.
It was failing the prettier format check in the build pipeline after #6158.
```
$ pnpm format:check
> explore-education-statistics@ format:check C:\Users\BenOutram\dev\ees
> prettier --list-different "**/*.{js,jsx,ts,tsx,css,scss,html}"
src/explore-education-statistics-frontend/src/pages/index.tsx
```
=> Fix frontend formatting

src/GovUk.Education.ExploreEducationStatistics.Admin.Tests/Controllers/Api/OrganisationsControllerTests.cs, src/GovUk.Education.ExploreEducationStatistics.Admin.Tests/MockBuilders/OrganisationServiceMockBuilder.cs, src/GovUk.Education.ExploreEducationStatistics.Admin.Tests/Services/OrganisationServiceTests.cs, src/GovUk.Education.ExploreEducationStatistics.Admin/Controllers/Api/OrganisationsController.cs, src/GovUk.Education.ExploreEducationStatistics.Admin/Services/Interfaces/IOrganisationService.cs, src/GovUk.Education.ExploreEducationStatistics.Admin/Services/OrganisationService.cs, src/GovUk.Education.ExploreEducationStatistics.Admin/Startup.cs, src/GovUk.Education.ExploreEducationStatistics.Admin/ViewModels/OrganisationViewModel.cs, src/GovUk.Education.ExploreEducationStatistics.Common.Tests/Extensions/ArrayExtensions.cs, src/GovUk.Education.ExploreEducationStatistics.Common.Tests/Extensions/ArrayExtensionsTests.cs, src/GovUk.Education.ExploreEducationStatistics.Content.Model/Organisation.cs, src/GovUk.Education.ExploreEducationStatistics.Content.Services.Tests/PublicationServiceTests.cs
This PR adds a new Admin API endpoint to get all organisations.
Request:
```http
GET https://admin.url/api/organisations
Authorization: Bearer <token>
```
Response:
```http
HTTP/1.1 200 OK
Content-Type: application/json; charset=utf-8
[
{
"id": "5e089801-cf1a-b375-acd3-88e9d8aece66",
"title": "Department for Education",
"url": "https://www.gov.uk/government/organisations/department-for-education"
},
{
"id": "5e089801-ce1a-e274-9915-e83f3e978699",
"title": "Skills England",
"url": "https://www.gov.uk/government/organisations/skills-england"
}
]
```
It will be used when creating or updating release versions in the Admin UI to list the organisations as options, allowing selecting one or more publishing organisations of the release. This is a change being made to the Admin by #6139.
=> EES-6319 Add new Admin API endpoint to get all organisations

infrastructure/parameters/pre-prod.parameters.json
=> EES-6330 - increasing Pre-Prod stats DB capacity following testing with multiple large file uploads

src/GovUk.Education.ExploreEducationStatistics.Common/Extensions/QueryableExtensions.cs, src/GovUk.Education.ExploreEducationStatistics.Content.Model/Repository/Interfaces/IReleaseFileRepository.cs, src/GovUk.Education.ExploreEducationStatistics.Content.Model/Repository/ReleaseFileRepository.cs, src/GovUk.Education.ExploreEducationStatistics.Content.ViewModels/ReleaseSummaryViewModel.cs, src/GovUk.Education.ExploreEducationStatistics.Public.Data.Processor/Services/DataSetVersionService.cs
This PR:
- removes a redundant include of "CreatedBy" users from ReleaseFiles, as the Users who are actually used to create ViewModels in the end come from a separate DataImports query later in the code (ReleaseDataFileService line 649). 
When first attempting to fix this, I originally added support for optional Includes, using the `ConditionalQueryable` that @leeoades added.  I've left the optional Include method there in case it is useful in the future.
=> EES-6345 - removing redundant include of users within ReleaseFiles

tests/robot-tests/tests/admin/bau/upload_files.robot, tests/robot-tests/tests/admin_and_public_2/bau/maps_across_time.robot, tests/robot-tests/tests/libs/admin-common.robot
This PR:
- updates various UI tests to expect Screener steps to be skipped, and auto-import to be enabled.
I've referenced everywhere where these changes need reversed with the ticket ref EES-6341.
=> EES-XXXX - updated various UI tests to bring in line with Screener integration being skipped

src/explore-education-statistics-frontend/src/modules/find-statistics/PublicationReleasePage.tsx, src/explore-education-statistics-frontend/src/modules/find-statistics/__tests__/PublicationReleasePage.test.tsx
Small PR to change the 'Download all data (ZIP)' from a button to a link, on a release page.
For context, this used to be a link but was changed to a button previously to allow analytics tracking. To preserve this tracking, I have added the `fromPage` query param in line with the button functionality.
I've also added an ID attribute to be able to target the link programmatically, which is what analysts are trying to do.
=> EES-6339 Change download all files button back to link

src/explore-education-statistics-frontend/src/modules/find-statistics/PublicationReleasePage.tsx, src/explore-education-statistics-frontend/src/modules/find-statistics/__tests__/PublicationReleasePage.test.tsx, tests/robot-tests/tests/admin_and_public/bau/archive_publication.robot, tests/robot-tests/tests/admin_and_public/bau/publish_content.robot, tests/robot-tests/tests/admin_and_public/bau/publish_data.robot, tests/robot-tests/tests/admin_and_public/bau/release_reordering.robot, tests/robot-tests/tests/admin_and_public_2/bau/publish_methodology_publication_update.robot, tests/robot-tests/tests/general_public/prod_only/old_fast_track.robot
https://dfedigital.atlassian.net/browse/EES-6348
A quick change to make this messaging more correct
Previously:
> This is (not) the latest _data_
Now reads:
> This is (not) the latest _release_
=> EES-6348 Change 'this is (not) the latest release' tag on release pages

tests/robot-tests/tests/general_public/release_page_absence.robot
I recently changed the 'Download all data (zip)' link to a button but forgot to update a relevant UI test. This PR fixes that.
=> EES-6339 Fix failing UI test after changing button to link

src/explore-education-statistics-admin/src/pages/release/data/components/DataFilesReplacementTableRow.tsx, src/explore-education-statistics-admin/src/pages/release/data/components/ReleaseDataUploadsSection.tsx
https://dfedigital.atlassian.net/browse/EES-6358
In a unique instance, the FE was attemping to get permissions on a file that no longer existed, causing a 404 error and erroring the page. I've updated the code so if this happens to simply refetch all dataFiles.
For more information as to why this is happening I've written a comment about it here: https://exploreeducationstats.slack.com/archives/C08US9M1G3V/p1753354297276129?thread_ts=1753353842.037289&cid=C08US9M1G3V
=> EES-6358 - manages file missing error, avoids 404 error by refreshing the datafiles data

src/explore-education-statistics-frontend/src/modules/permalink/PermalinkPage.tsx, src/explore-education-statistics-frontend/src/modules/permalink/__tests__/PermalinkPage.test.tsx, tests/robot-tests/scripts/permalink_snapshots/check_permalinks.py, tests/robot-tests/tests/admin_and_public/bau/archive_publication.robot, tests/robot-tests/tests/admin_and_public_2/bau/publish_release_and_amend_2.robot, tests/robot-tests/tests/general_public/prod_only/old_fast_track.robot
Removed the error styling as it was a little too dramatic, updated warning text and removed "WARNING - " warning message prefixes as icon and hidden text implied as much
=> EES-6347 permalink warning UI tweak

src/explore-education-statistics-frontend/src/components/PageMeta.tsx, src/explore-education-statistics-frontend/src/modules/data-catalogue/DataCataloguePage.tsx, src/explore-education-statistics-frontend/src/modules/data-catalogue/__tests__/DataCataloguePage.test.tsx, src/explore-education-statistics-frontend/src/modules/data-catalogue/components/DataSetFileSummary.module.scss, src/explore-education-statistics-frontend/src/modules/data-catalogue/components/DataSetFileSummary.tsx, src/explore-education-statistics-frontend/src/modules/data-catalogue/components/__tests__/DataSetSummary.test.tsx, tests/robot-tests/tests/admin_and_public/bau/archive_publication.robot, tests/robot-tests/tests/general_public/data_set_page_absence_in_prus.robot, tests/robot-tests/tests/public_api/public_api_major_auto_changes.robot, tests/robot-tests/tests/public_api/public_api_minor_manual_changes.robot, tests/robot-tests/tests/public_api/public_api_preview_token.robot
Moves the publication title to above the data set name in the list on the data catalogue page. To make sure it's accessible the publication name is included in the heading and link, which required a bit of CSS re-jigging to make it look right.
When the list is filtered by publication the publication title doesn't show on the data sets as it's shown as a heading on the page so there's no need.
I think I've caught all the places this would cause UI tests to break, apologies if not (I can't get clean runs because of other failures).
Also, removes an unused import in PageMeta as the build was complaining about it.
=> EES-6261 show publication title in data set heading on data catalogue

src/explore-education-statistics-admin/src/pages/release/data/ReleaseApiDataSetDetailsPage.tsx, src/explore-education-statistics-admin/src/pages/release/data/utils/__tests__/shouldShowDraftActions.test.ts, src/explore-education-statistics-admin/src/pages/release/data/utils/shouldShowDraftActions.ts
This Pull Request introduces a utility function, `shouldShowDraftActions`, to determine if the draft version actions should be displayed on the API details page for a new release. It integrates it into the `ReleaseApiDataSetDetailsPage` component. Additionally, accompanying unit tests are added to ensure the function behaves as expected.
- Added the `shouldShowDraftActions` helper function in `utils/shouldShowDraftActions.ts` to encapsulate logic for draft version action visibility.
- Updated `ReleaseApiDataSetDetailsPage.tsx` to use the new utility function for determining whether to display draft version actions.
- Added a new test file `__tests__/shouldShowDraftActions.test.ts` with comprehensive test cases to verify the behaviour of `shouldShowDraftActions`.
=> EES-5779/EES-6343 The API details page for a draft API data set version should hide the actions section if its empty

infrastructure/templates/analytics/application/analyticsApplicationInsights.bicep, infrastructure/templates/analytics/application/analyticsFunctionApp.bicep, infrastructure/templates/analytics/main.bicep, infrastructure/templates/analytics/types.bicep
This PR uses the new common LogAnalyticsWorkspace with the analytics appInsights instance. I have already manually migrated the app insights instance via the azure portal - this is to check that everything still works after having updated the bicep template.
=> EES-6168 Use common appInsights for analytics

src/GovUk.Education.ExploreEducationStatistics.Admin.Tests/MockBuilders/OrganisationsValidatorMockBuilder.cs, src/GovUk.Education.ExploreEducationStatistics.Admin.Tests/Services/ReleaseServicePermissionTests.cs, src/GovUk.Education.ExploreEducationStatistics.Admin.Tests/Services/ReleaseServiceTests.cs, src/GovUk.Education.ExploreEducationStatistics.Admin.Tests/Services/ReleaseVersionServicePermissionTests.cs, src/GovUk.Education.ExploreEducationStatistics.Admin.Tests/Services/ReleaseVersionServiceTests.cs, src/GovUk.Education.ExploreEducationStatistics.Admin.Tests/Validators/OrganisationsValidatorTests.cs, src/GovUk.Education.ExploreEducationStatistics.Admin/Requests/ReleaseRequests.cs, src/GovUk.Education.ExploreEducationStatistics.Admin/Requests/ReleaseVersionRequests.cs, src/GovUk.Education.ExploreEducationStatistics.Admin/Services/ReleaseService.cs, src/GovUk.Education.ExploreEducationStatistics.Admin/Services/ReleaseVersionService.cs, src/GovUk.Education.ExploreEducationStatistics.Admin/Startup.cs, src/GovUk.Education.ExploreEducationStatistics.Admin/Validators/IOrganisationsValidator.cs, src/GovUk.Education.ExploreEducationStatistics.Admin/Validators/OrganisationsValidator.cs, src/GovUk.Education.ExploreEducationStatistics.Admin/Validators/ValidationMessages.cs
This PR makes changes to the following Admin API methods to allow optionally setting and updating publishing organisations when creating a new release or updating an existing release version.
```http
POST /api/releases
PATCH /api/releaseVersions/{releaseVersionId}
```
The `ReleaseCreateRequest` and `ReleaseVersionUpdateRequest` request types have been changed to accept an optional `publishingOrganisations` array of type Guid, representing organisation id’s.
It silently ignore duplicates, associating the release version with a distinct list of the publishing organisations.
<sub>* Screenshot shows a result using the Admin with the frontend changes from EES-6316 combined with this change.</sub>.
Both methods return a list of validation errors if any of the organisations cannot be found.
``` …
```
=> EES-6320 Allow setting publishing organisations when creating and updating a release version

src/explore-education-statistics-admin/src/pages/release/ReleaseCreatePage.tsx, src/explore-education-statistics-admin/src/pages/release/ReleaseSummaryEditPage.tsx, src/explore-education-statistics-admin/src/pages/release/ReleaseSummaryPage.tsx, src/explore-education-statistics-admin/src/pages/release/components/ReleaseSummaryForm.tsx, src/explore-education-statistics-admin/src/pages/release/components/__tests__/ReleaseSummaryForm.test.tsx, src/explore-education-statistics-admin/src/services/organisationService.ts, src/explore-education-statistics-admin/src/services/releaseService.ts, src/explore-education-statistics-admin/src/services/releaseVersionService.ts
Building on the work done in EES-6135, 6137, 6138, this PR allows a user to optionally associate `publishingOrganisations` to a release version (when creating a release, or editing a release version). This value is also displayed on the Release Summary.
We fetch a list of organisations in the ReleaseSummaryForm and present them as checkboxes options.
N.b we need to wait until the BE tasks associated with this work are done before working, and it may need to be amended once the BE is done and we can test it properly, so **it is not ready to merge yet**.
=> EES-6316 Add ability to set `publishingOrganisations` in admin

tests/robot-tests/tests/admin_and_public_2/bau/publishing_organisations.robot, tests/robot-tests/tests/libs/admin-common.robot
This PR adds UI tests for setting and reading publishing organisations when managing releases.
To run them, you will need to have the code from https://dfedigital.atlassian.net/browse/EES-6320 and https://dfedigital.atlassian.net/browse/EES-6316 to enable the functionality.
=> EES-6356 publishing organisations UI tests

src/explore-education-statistics-admin/src/pages/release/data/ReleaseApiDataSetDetailsPage.tsx, src/explore-education-statistics-admin/src/pages/release/data/__tests__/ReleaseApiDataSetDetailsPage.test.tsx
This PR Improves the content design of the error summary displayed in the API data set details page.
It does this by making the message more specific to the error at hand. 
If the error summary for patch versions that result in incomplete automapping display a message for incomplete mapping, otherwise if it results in a major change, the error summary is more specific for major change.
e.g.,
We are also adding the use of component InsetText with variant="error" when rendering error summary for the API details page
=> EES-5779/EES-6363 - Show more specific error messages in the API details page (for incomplete manual mapping vs for major version change found).

src/explore-education-statistics-frontend/src/modules/permalink/PermalinkPage.tsx
We want to remove the red styling of permalink errors, here's an example of how they render now:
=> EES-6371 permalink error styling update

src/explore-education-statistics-admin/src/pages/release/datablocks/components/chart/ChartDataSetsConfiguration.tsx, src/explore-education-statistics-admin/src/pages/release/datablocks/components/chart/utils/__tests__/getSelectedDataSets.test.ts, src/explore-education-statistics-common/src/modules/charts/components/__tests__/__data__/testMapBlockData.ts, src/explore-education-statistics-common/src/modules/charts/util/__tests__/getDataSetCategoryConfigs.test.ts, src/explore-education-statistics-common/src/modules/charts/util/__tests__/getMapDataSetCategoryConfigs.test.ts, src/explore-education-statistics-common/src/modules/table-tool/components/__tests__/DataTableCaption.test.tsx, src/explore-education-statistics-common/src/modules/table-tool/components/__tests__/DownloadTable.test.tsx, src/explore-education-statistics-common/src/modules/table-tool/types/fullTable.ts, src/explore-education-statistics-common/src/modules/table-tool/utils/__data__/testTableData.ts, src/explore-education-statistics-common/src/modules/table-tool/utils/__data__/testTableDataWithDuplicateLabels.ts, src/explore-education-statistics-common/src/modules/table-tool/utils/__data__/testTableDataWithMergedCells.ts, src/explore-education-statistics-common/src/modules/table-tool/utils/__tests__/generateTableTitle.test.ts, src/explore-education-statistics-common/src/modules/table-tool/utils/mapFullTableMeta.ts, src/explore-education-statistics-frontend/src/modules/table-tool/components/__tests__/__data__/tableData.ts
Ticket https://dfedigital.atlassian.net/browse/EES-6362
in `mapFullTableMeta` the filters were keyed by their legend (which react hook form wasn't happy with), which contains plain text, including punctuation. This change makes the filters arranged and keyed by their original filter key, which is in camel case with no punctuation.
I've given this a test and ran UI tests and this change didn't seem to create any issue, however I suggest this be rigorously tested to prevent any potential bugs around existing datablocks and chart rendering on both admin and public sites
=> EES-6362 - Fix chart rendering with filter names containing apostrophes (punctuation)

src/GovUk.Education.ExploreEducationStatistics.Content.Model/DataImport.cs, src/GovUk.Education.ExploreEducationStatistics.Content.Model/DataSetFileMeta.cs, src/GovUk.Education.ExploreEducationStatistics.Content.ViewModels/DataSetFileMetaViewModel.cs, src/GovUk.Education.ExploreEducationStatistics.Data.Processor.Tests/Services/FileImportServiceTests.cs, src/GovUk.Education.ExploreEducationStatistics.Data.Processor/Services/DataImportService.cs, src/GovUk.Education.ExploreEducationStatistics.Data.Processor/Services/FileImportService.cs, src/GovUk.Education.ExploreEducationStatistics.Data.Processor/Services/Interfaces/IDataImportService.cs, src/explore-education-statistics-frontend/src/modules/data-catalogue/components/DataSetFileDetails.tsx, src/explore-education-statistics-frontend/src/services/dataSetFileService.ts
When DataSetFileMeta.NumDataFileRows was introduced, it was made optional since existing data had null values. However, this is no longer the case and we can finally set this value to be mandatory. Likewise, a DataImport must have TotalRows
Could someone with access to all of the DBs please confirm that this is the case - that there are no longer any rows that are missing this value?
Also, can anyone with more knowledge of this area think of any other issues with setting this to mandatory?
Thanks.
=> EES-6205 Make DataSetFileMeta.NumDataFileRows non-optional

src/GovUk.Education.ExploreEducationStatistics.Analytics.Consumer/Extensions/DuckDbConnectionExtensions.cs, src/GovUk.Education.ExploreEducationStatistics.Analytics.Consumer/GovUk.Education.ExploreEducationStatistics.Analytics.Consumer.csproj
This PR:
- fixes the issue whereby we were getting occasional failures in reading batches of DataSetVersion-level JSON analytics files.
The exception behind the failure was this (the existence of a `requestedDataSetVersion` field in one of the JSON files):
```
[analytics] [2025-08-08T12:59:30.167Z] Exception: DuckDB.NET.Data.DuckDBException (0x00000020): Invalid Input Error: JSON transform error in file "/home/dwatson/development/projects/dfe/explore-education-statistics/data/analytics/public-api/data-set-versions/processing/18bf7573-424b-4399-9d9f-b9944e17ea6e/1/20250721-151752_6faa9501-cf1d-f274-9b2d-a6d117135298_6177a.json", in record/value 1: Object {"dataSetId":"63629501-d3ca-c471-9780-ec4cb6fdf172... has unknown key "requestedDataSetVersion"
[analytics] [2025-08-08T12:59:30.167Z] …
```
=> EES-6366 - fixing analytics failures

package.json, src/explore-education-statistics-api-docs/README.md, src/explore-education-statistics-api-docs/docker/Dockerfile, src/explore-education-statistics-api-docs/docker/build-docs.sh, src/explore-education-statistics-api-docs/docker/run-docs.sh
This PR was created off the back of investigating some build failures for the Public API docs on a feature branch.
During this investigation, I found that the setup process was a bit tricky and polluted my local dev machine quite a bit, so I figured it'd be a good candidate to have a Dockerized process as well as the manual one.
This PR:
- introduces `pnpm api-docs:build` which uses Docker to build the API docs locally.
- introduces `pnpm api-docs:run` which uses Docker to build and run the API docs locally with the Middleman development server.
`pnpm api-docs:build` will validate and build the API docs, generating the built files in the `src/explore-education-statistics-api-docs/.build` folder.
`pnpm api-docs:run` will validate, build and run the API docs using Middleman, hosting  the …
=> EES-XXXX - adding simpler Docker solution for building and running Public API docs locally

src/GovUk.Education.ExploreEducationStatistics.Admin.Tests/Controllers/Api/Migrations/PopulateReleasePublishingFeedbackReportingFieldsMigrationControllerTests.cs, src/GovUk.Education.ExploreEducationStatistics.Admin/Controllers/Api/Migrations/PopulateReleasePublishingFeedbackReportingFieldsMigrationController.cs, src/GovUk.Education.ExploreEducationStatistics.Admin/Migrations/ContentMigrations/20250811120206_EES6370_AddAdditionalReportingFieldsToReleasePublishingFeedback.Designer.cs, src/GovUk.Education.ExploreEducationStatistics.Admin/Migrations/ContentMigrations/20250811120206_EES6370_AddAdditionalReportingFieldsToReleasePublishingFeedback.cs, src/GovUk.Education.ExploreEducationStatistics.Content.Model/ReleasePublishingFeedback.cs, src/GovUk.Education.ExploreEducationStatistics.Publisher.Tests/Services/NotificationsServiceTests.cs, src/GovUk.Education.ExploreEducationStatistics.Publisher/Services/NotificationsService.cs
This PR:
- adds a new PublicationTitle column to the ReleasePublishingFeedback table for easier reporting for Cam.
- adds a new combined ReleaseTitle ("<TimeIdentifier> <Year> <Label>") column to the ReleasePublishingFeedback table for easier reporting for Cam.
- adds a manual migration endpoint for updating existing feedback entries.
The reason that we have a manual migration endpoint is that the database has no notion of the plain-English labels that we use to refer to the different TimeIdentifiers.  E.g. we typically would store "AY" in the db which in code is then surfaced as "Academic year".  A SQL migration would require a monster case statement!
After this code is deployed, we need to call the following manual migration endpoint:
`PUT …
=> EES-6370 - added new fields to ReleasePublishingFeedback for easier reporting

src/explore-education-statistics-common/src/components/ContentSectionIndex.tsx
Long section navigation lists on methodology page can get cut off on small screens, this makes them scrollable if needed.
=> EES-6396 scrollable methodology nav on small screens

tests/robot-tests/tests/files/public-api-data-files/absence_school_patch_manual.csv, tests/robot-tests/tests/files/public-api-data-files/absence_school_patch_manual.meta.csv, tests/robot-tests/tests/public_api/public_api_patch_replacement_fe.robot
Summary
Adds a robot test, the test adds 2 patch versions to a publication and then tests that we display the latest/highest patch version on the public front end. Also that we collate the two changelogs into a single page.
Overview
This PR adds a new robot test for the public front end (non admin) functionality related to patch replacement.
This test creates two amendments on a single release to create data set versions 1.0, 1.0.1, 1.0.2.
It then tests that the public frontend displays the highest patch version when the patch data set page is loaded on the public frontend when a user navigates from the 'data catalogue' link.
It also tests that we collate changelogs that are patch change logs on a single page.
example screenshot for collating change logs:
=> EES-5779/EES-6184 Add E2E robot test which tests the non-admin side of patch replacement feature.

src/GovUk.Education.ExploreEducationStatistics.Admin.Tests/Services/DataSetValidatorTests.cs, src/GovUk.Education.ExploreEducationStatistics.Admin/Services/DataSetValidator.cs, src/GovUk.Education.ExploreEducationStatistics.Admin/Services/Interfaces/Public.Data/IDataSetService.cs, src/GovUk.Education.ExploreEducationStatistics.Admin/Services/Public.Data/DataSetService.cs, src/GovUk.Education.ExploreEducationStatistics.Admin/Validators/ValidationMessages.cs, src/explore-education-statistics-admin/src/pages/release/data/components/DataFileUploadForm.tsx
This Pull Request introduces enhancements to the DataSetValidator for handling scenarios involving draft API data sets. 
It adds a check to prevent creating multiple draft versions of API data sets and includes corresponding updates to validation messages, test cases, and associated files.
Main Changes
- DataSetValidator Logic Update: New validation logic ensures that no multiple draft API data sets can exist simultaneously, improving system consistency.
- Test Updates: Added unit tests in DataSetValidatorTests.cs to verify new draft API data set validation behavior.
- New Validation Message: Introduced a localized error message in ValidationMessages.cs to notify users about the restriction.
- Frontend Update: Added a new error identifier CannotCreateMultipleDraftApiDataSet to the …
=> EES-6455 & EES-6456 Block creation of multiple draft API data set versions

src/explore-education-statistics-admin/src/pages/release/data/components/DataFileUploadForm.tsx
This PR Fixes frontend code so that when on going replacement has not been confirmed, and another replacement is attempted, the error message is more instructive based on the original error message intended.
Current error message:
Intended error message after small tweak:
There are tests in place already for the backend which produces this error message.
=> EES-6456 Informative error message when replacing an ongoing replacement that has not been confirmed

src/GovUk.Education.ExploreEducationStatistics.Admin/Controllers/Api/ReleaseFileController.cs, src/GovUk.Education.ExploreEducationStatistics.Admin/Services/DataSetFileStorage.cs, src/GovUk.Education.ExploreEducationStatistics.Admin/Services/DataSetUploadRepository.cs, src/explore-education-statistics-admin/src/services/releaseFileService.ts, src/explore-education-statistics-common/src/modules/release/hooks/useGetReleaseFile.ts, src/explore-education-statistics-common/src/services/downloadService.ts
This PR:
- cleans up some TODO comments left over in the codebase from the previously merged PR for EES-6359.
The TODOs left in the codebase now reference a new ticket EES-6480, for implementing permission checks.
=> EES-6480 - cleaning up TODOs left over from EES-6359.

src/GovUk.Education.ExploreEducationStatistics.Admin/Services/ManageContent/ReleaseNoteService.cs, src/GovUk.Education.ExploreEducationStatistics.Admin/Startup.cs, src/GovUk.Education.ExploreEducationStatistics.Common.Tests/ViewModels/PaginatedListViewModelTests.cs, src/GovUk.Education.ExploreEducationStatistics.Common/ViewModels/PaginatedListViewModel.cs, src/GovUk.Education.ExploreEducationStatistics.Content.Model/Update.cs, src/GovUk.Education.ExploreEducationStatistics.Content.Services.Tests/Releases/ReleaseUpdatesServiceTests.cs, src/GovUk.Education.ExploreEducationStatistics.Content.Services/Releases/ReleaseUpdatesService.cs
This PR makes an update to the new Content API endpoint to get release updates added by https://github.com/dfe-analytical-services/explore-education-statistics/pull/6274.
It appends an update entry with the summary 'First published' and the date that the first version of the release was published.
Request:
```http
GET https://content-api.url/api/publications/{publicationSlug}/releases/{releaseSlug}/updates?page=1&pageSize=10
```
Updated response, now including the 'First published' entry:
```http
HTTP/1.1 200 OK
Content-Type: application/json; charset=utf-8
{
"results": [
{
"date": "2025-09-09T14:32:33.44189+01:00",
"summary": "Update 3"
},
{
"date": "2025-09-09T14:32:04.5317757+01:00",
"summary": "Update 2"
},
{
"date": "2025-09-09T14:31:42.1236855+01:00",
"summary": "Update 1"
},
{ …
```
=> EES-6485 Add 'First published' entry to Release updates

infrastructure/parameters/prod.parameters.json
This PR reverts the change made in https://github.com/dfe-analytical-services/explore-education-statistics/pull/6260.
It reduces the scale of the statistics primary and replica databases in the Prod environment, from provisioned 12 to 10 vCores.
The update in code reflects the manual adjustment that has already applied to the databases on 10/09/25.
=> EES-6471 Reduce statistics database scale after temporarily scaling up

infrastructure/templates/template.json
Our Azure Storage instances are already not available publicly due to only being made available to specific subnets.
This PR additionally disables anonymous blob access to the same Azure Storage instances, which provides an extra layer of protection should other protections fail.
=> EES-6521 Disable anonymous blob access to Az Storage instances

infrastructure/templates/template.json
This PR removes DDoS protection config from our ARM template. We're doing as a temporary measure until it can be readded. Currently there is a restriction of one DdosProtectionPlan per subscription that is preventing us from deploying this to production.
=> EES-6520 Remove ARM template DDOS protection config

src/explore-education-statistics-common/src/services/publicationService.ts, src/explore-education-statistics-frontend/src/modules/find-statistics/PublicationReleaseListPage.tsx, src/explore-education-statistics-frontend/src/modules/find-statistics/__tests__/PublicationReleaseListPage.test.tsx, src/explore-education-statistics-frontend/src/pages/find-statistics/[publication]/releases.tsx
This PR adds a new page to a publication (at `/find-statistics/publication-slug/releases`) which shows a list of releases belonging to the publication (legacy and standard releases)
The results are paginated like the 'updates' page.
There is an optional display of 'next release' if the publication has one.
=> EES-6442 releases in this series page

tests/robot-tests/tests/general_public/no_javascript.robot
This PR skips the `Validate publications list is on page` test case in the `no_javascript.robot` file.
It is skipped with a message explaining that it requires frontend Azure Search configuration in the local environment and fails in Dev, Test, and PreProd. The failures in those environments is suspected to be due to Basic Authentication.
=> Skip `no_javascript.robot` UI test failing in local environment

src/GovUk.Education.ExploreEducationStatistics.Admin.Tests/Services/SignInServiceTests.cs, src/GovUk.Education.ExploreEducationStatistics.Admin/Services/SignInService.cs, src/GovUk.Education.ExploreEducationStatistics.Content.Model.Tests/Fixtures/UserGeneratorExtensions.cs
This 1-liner was missed on the [previous PR for EES-6502](https://github.com/dfe-analytical-services/explore-education-statistics/pull/6305).
It makes sense to reset the `User.DeletedById` field to `Null` when signing in with a previously soft-deleted user.
=> EES-6502 - Resetting `User.DeletedById` back to `Null` when signing-in with a soft deleted user

src/explore-education-statistics-common/src/components/AccordionSection.tsx, src/explore-education-statistics-common/src/components/__tests__/Accordion.test.tsx, src/explore-education-statistics-common/src/components/__tests__/__snapshots__/AccordionSection.test.tsx.snap
Fixes an accessibility issue raised by DAC where when screen reader users are navigating using the arrow keys, accordion headings are read as two separate elements (the actual heading and 'show'). Comparing our html with the design system I noticed we were missing two things, adding them has fixed the issue:
- an `aria-label` containing the the heading and 'show / hide this section'
- a hidden span containing `, ` between the heading and 'show /hide'
=> EES-6599 improve accordions for screen reader users

src/GovUk.Education.ExploreEducationStatistics.Admin/Services/ReleaseVersionService.cs, tests/robot-tests/tests/libs/common.robot
This PR does two things:
- reenable the NetworkActivityContext UI test check
- and attempt to improve the performance of `ReleaseVersionService#ListScheduledReleases`.
Previous this PR was intending to remove NetworkActivityContext, but after a chat with Dunc, we're now going to keep it.
I had intended to remove this I noticed that the UI test check on the network activity attribute in pages' `Body` was remaining active for a long time, slowing down UI tests by 30-60 seconds unnecessarily. I assumed this would happen anywhere the `user waits until page finishes loading` keyword was called, but Dunc pointed out that it will be specific to the Dashboard, and specifically the `api/releases/scheduled` endpoint that still hasn't returned.
It's also possible that while we saw no flaky test …
=> EES-6602 Reenable NetworkActivityContext UI test check
