armTemplates/service-template.json

Disables the ARR Affinity cookie on content api as it is a stateless application

DFE-285: Disable Affinity cookie on content API

---

src/explore-education-statistics-frontend/src/components/Accordion.tsx
src/explore-education-statistics-frontend/src/components/AccordionSection.tsx
src/explore-education-statistics-frontend/src/components/__tests__/Accordion.test.tsx

This PR adds additional logic to open the nearest `AccordionSection` when an element in the section's content has an ID that matches the URL hash. The element can then be scrolled to in the section.

DFE-320 Open accordion section if URL hash matches a section content element

---

src/explore-education-statistics-admin/test/setupTests.js
src/explore-education-statistics-common/src/components/Accordion.tsx
src/explore-education-statistics-common/src/components/Tabs.tsx
src/explore-education-statistics-common/src/components/TabsSection.tsx
src/explore-education-statistics-common/src/components/__tests__/Tabs.test.tsx
src/explore-education-statistics-common/src/components/__tests__/__snapshots__/Tabs.test.tsx.snap
src/explore-education-statistics-common/src/hooks/useMedia.ts
src/explore-education-statistics-common/src/hooks/useMounted.ts
src/explore-education-statistics-common/test/setupTests.js
src/explore-education-statistics-frontend/test/setupTests.js

This PR primarily fixes the window jumping to the respective tab sections when the tab links are clicked. 
- Tab section headings are now automatically generated from the `title` prop and will use `h3`s by default. This sizing can be changed with the `headingTag` if necessary. This is important as it makes it obvious where the user has jumped to when they click a tab link on the mobile/non-Javascript version.

DFE-441 Fix window jumping on clicking Tab links

---

src/explore-education-statistics-frontend/src/modules/glossary/GlossaryIndexPage.tsx
src/explore-education-statistics-frontend/src/modules/methodology/MethodologyIndexPage.tsx
src/explore-education-statistics-frontend/src/pages/glossary/index.tsx
src/explore-education-statistics-frontend/src/pages/index.tsx
src/explore-education-statistics-frontend/src/pages/methodology/index.tsx

Placeholder pages in functioning app to support further development of methodology and the glossary

FRONTEND: Add methodology and glossary page placeholders

---

src/GovUk.Education.ExploreEducationStatistics.Data.Api/Services/TableBuilder/ResultBuilder.cs
src/GovUk.Education.ExploreEducationStatistics.Data.Api/ViewModels/TableBuilder/TableBuilderObservationViewModel.cs

Filters and indicator id's should be the same data type in the query response as they are in the meta data.
They are strings in the meta data to be consistent with geographic attribute values which come from the data and may not always be numeric.

DFE-631 Id data type should be consistent with meta data

---

src/explore-education-statistics-frontend/src/modules/table-tool/components/FiltersForm.tsx
src/explore-education-statistics-frontend/src/modules/table-tool/components/LocationFiltersForm.tsx
src/explore-education-statistics-frontend/src/modules/table-tool/components/PublicationForm.tsx
src/explore-education-statistics-frontend/src/modules/table-tool/components/PublicationSubjectForm.tsx

This PR fixes the validation rules for selecting filters by forcing the user to select at least one option from every category before they can create a table.

DFE-514 Validate that all filter groups must have one option selected

---

src/explore-education-statistics-common/src/components/ButtonText.module.scss
src/explore-education-statistics-common/src/components/ButtonText.tsx
src/explore-education-statistics-common/src/components/form/FormCheckbox.tsx
src/explore-education-statistics-common/src/components/form/FormCheckboxGroup.module.scss
src/explore-education-statistics-common/src/components/form/FormCheckboxGroup.tsx
src/explore-education-statistics-common/src/components/form/FormCheckboxSearchGroup.module.scss
src/explore-education-statistics-common/src/components/form/FormCheckboxSearchSubGroups.module.scss
src/explore-education-statistics-common/src/components/form/FormCheckboxSearchSubGroups.tsx
src/explore-education-statistics-common/src/components/form/FormCheckboxSubGroups.tsx
src/explore-education-statistics-common/src/components/form/__tests__/FormCheckboxGroup.test.tsx
src/explore-education-statistics-common/src/components/form/__tests__/FormCheckboxSubGroups.test.tsx
src/explore-education-statistics-common/src/components/form/__tests__/FormFieldCheckboxGroup.test.tsx
src/explore-education-statistics-common/src/components/form/__tests__/FormFieldCheckboxSearchGroup.test.tsx
src/explore-education-statistics-common/src/components/form/__tests__/FormFieldCheckboxSearchSubGroups.test.tsx
src/explore-education-statistics-common/src/components/form/__tests__/FormFieldCheckboxSubGroups.test.tsx
src/explore-education-statistics-common/src/components/form/__tests__/__snapshots__/FormCheckboxGroup.test.tsx.snap
src/explore-education-statistics-common/src/components/form/__tests__/__snapshots__/FormCheckboxSubGroups.test.tsx.snap
src/explore-education-statistics-common/src/components/form/util/checkboxGroupFieldHelpers.ts
src/explore-education-statistics-frontend/next.config.js
src/explore-education-statistics-frontend/src/modules/table-tool/components/FiltersForm.tsx
src/explore-education-statistics-frontend/src/modules/table-tool/components/FormFieldCheckboxMenu.tsx
src/explore-education-statistics-frontend/src/modules/table-tool/components/LocationFiltersForm.tsx
src/explore-education-statistics-frontend/src/modules/table-tool/components/TimePeriodDataTable.tsx

This PR makes the 'Select all' option more obvious by changing it to a button instead that states if you want to 'Select all X options' or 'Unselect all X options'.

DFE-402 Make checkbox 'Select all' option more obvious

---

src/explore-education-statistics-frontend/src/modules/table-tool/components/TimePeriodForm.tsx

This PR fixes the premature showing of the time period validation message if the start/end date is before the corresponding start/end date.

DFE-645 Fix error showing before all time period options have been chosen

---

src/explore-education-statistics-common/src/components/form/FormCheckboxGroup.tsx
src/explore-education-statistics-common/src/components/form/FormRadioGroup.tsx
src/explore-education-statistics-common/src/components/form/FormSelect.tsx
src/explore-education-statistics-common/src/components/form/__tests__/FormCheckboxGroup.test.tsx
src/explore-education-statistics-common/src/components/form/__tests__/FormRadioGroup.test.tsx
src/explore-education-statistics-common/src/components/form/__tests__/FormSelect.test.tsx

This PR add new `order` and `orderDirection` props to `FormSelect`, `FormCheckboxGroup` and `FormRadioGroup` to enable custom ordering of options. By default these will sort by label in ascending order. This should be a sensible default for most forms.

DFE-664 Order select, checkbox and radio groups by label by default

---

src/explore-education-statistics-admin/test/setupTests.js
src/explore-education-statistics-common/src/hooks/useMedia.ts
src/explore-education-statistics-common/src/polyfill.js
src/explore-education-statistics-common/test/setupTests.js
src/explore-education-statistics-frontend/test/setupTests.js

This PR:
- Adds the `Array.flat` polyfill that previously was breaking on Edge. We have to alias it to the old `Array.flatten` proposal (that has been superceded by `Array.flat`)  as we are stuck on CoreJS v2 for the time being (due to Next's dependencies).
- Removes the `MediaQueryList.addEventListener/removeEventListener` polyfills as these do not work with Safari. Instead we should just use the older `addListener/removeListener` methods when applicable as these are well supported (despite being deprecated).

DFE-675 + DFE-595 Add polyfill for Array.flat and remove MediaQueryLister.add/removeEventListener polyfill

---

src/explore-education-statistics-common/src/components/Button.tsx
src/explore-education-statistics-common/src/components/form/Form.tsx
src/explore-education-statistics-common/src/components/form/Formik.tsx
src/explore-education-statistics-common/src/components/form/index.ts
src/explore-education-statistics-frontend/src/modules/table-tool/components/FiltersForm.tsx
src/explore-education-statistics-frontend/src/modules/table-tool/components/LocationFiltersForm.tsx
src/explore-education-statistics-frontend/src/modules/table-tool/components/PublicationForm.tsx
src/explore-education-statistics-frontend/src/modules/table-tool/components/PublicationSubjectForm.tsx
src/explore-education-statistics-frontend/src/modules/table-tool/components/TableHeadersForm.tsx
src/explore-education-statistics-frontend/src/modules/table-tool/components/TimePeriodForm.tsx
src/explore-education-statistics-frontend/src/modules/table-tool/components/WizardStepFormActions.tsx
src/explore-education-statistics-frontend/src/modules/table-tool/components/__tests__/WizardStepFormActions.test.tsx

This PR fixes the null pointer that is thrown due to residual form state when the 'Previous step' button for a wizard step is clicked. Each step's form state is now cleared down to avoid this issue.
A Formik extension component has been created to enable us to handle a form's submission in an async. manner. 
Previously, in Formik's v1 API, Formik automatically resolves the `onSubmit` handler without caring if `onSubmit` is async (i.e. returns a promise). Consequently, this has meant that the form submitting state (changes 'Next step' button to a disabled 'Submitting' button) has not been triggering correctly and hasn't stopped users from accidentally double-submitting.
This has now been rectified and should work as expected, although the solution is somewhat undesirable as we have to get …

DFE-665 Fix null pointer when moving to and from previous step

---

src/explore-education-statistics-common/src/services/tableBuilderService.ts
src/explore-education-statistics-common/src/services/types/TimePeriod.ts
src/explore-education-statistics-frontend/src/modules/table-tool/TableToolPage.tsx
src/explore-education-statistics-frontend/src/modules/table-tool/components/PublicationForm.tsx

This PR replaces the hard-coded publication list in the 'Choose publication' step with a call to the new `/meta/themes` endpoint which returns a tree of themes/topics/publications that can be used to display the publication options.

DFE-682 Add dynamic publication list to 'Choose publication' step

---

src/explore-education-statistics-frontend/src/modules/find-statistics/PublicationReleasePage.tsx
src/explore-education-statistics-frontend/src/prototypes/publication/PrototypePublicationPageAbsence.tsx
src/explore-education-statistics-frontend/src/prototypes/publication/PrototypePublicationPageExclusions.tsx
src/explore-education-statistics-frontend/src/prototypes/publication/PrototypePublicationPageGCSE.tsx

replaced text with requested alternate text on 4 of the hardcoded publication pages
From 
```
The United Kingdom Statistics Authority designated these
statistics as National Statistics in <a href="#">Month Year</a> in
accordance with the Statistics and Registration Service Act 2007
and signifying compliance with the Code of Practice for
Statistics.
```
To
```
The United Kingdom Statistics Authority designated these
statistics as National Statistics in 2011 in accordance with the
Statistics and Registration Service Act 2007 and signifying
compliance with the Code of Practice for Statistics.
```

DFE-785-National-Stats

---

src/explore-education-statistics-frontend/src/modules/find-statistics/PublicationReleasePage.tsx

As requested, updated the text to: 
> The United Kingdom Statistics Authority designated these statistics as National Statistics in accordance with the Statistics and Registration Service Act 2007 and signifying compliance with the Code of Practice for Statistics.
https://alpha-dfe-data.atlassian.net/secure/RapidBoard.jspa?rapidView=1&projectKey=DFE&modal=detail&selectedIssue=DFE-785

dfe-785 National Stats update 2

---

src/explore-education-statistics-frontend/src/modules/find-statistics/PublicationReleasePage.tsx

Removes the feedback and questions section as this is no longer required

DFE-691: Remove Feedback and Questions from release page

---

src/explore-education-statistics-common/src/components/PageSearchForm.tsx
src/explore-education-statistics-common/src/components/__tests__/PageSearchForm.test.tsx
src/explore-education-statistics-common/src/components/form/FormComboBox.tsx
src/explore-education-statistics-common/src/components/form/__tests__/FormComboBox.test.tsx
src/explore-education-statistics-common/src/components/form/__tests__/__snapshots__/FormComboBox.test.tsx.snap
src/explore-education-statistics-common/src/hooks/useClickAway.ts
src/explore-education-statistics-common/src/lib/dom/__tests__/findAllByText.test.tsx
src/explore-education-statistics-common/src/lib/dom/findAllByText.ts

This PR adds functionality to allow the user to close `PageSearchForm`s results list when the user clicks away. This behaviour is actually abstracted into `FormComboBox`.
Additionally, the search input now requires 3 characters to be entered (rather than 4), which should be a little more flexible to search on. To alleviate issues with acronyms (e.g. LA) with only 2 characters, search will still be performed if the input seems to be an acronym.

DFE-846 Allow clicking away from search form to close it

---

src/explore-education-statistics-frontend/src/modules/table-tool/TableToolPage.tsx

This PR adds in the link to a publications methodology from table tool

DFE-583: Add methodology link on table tool

---

azure-pipelines.dfe.yml
azure-pipelines.pr.yml
src/explore-education-statistics-admin/src/pages/prototypes/PrototypeAdminDashboard.tsx
src/explore-education-statistics-admin/src/pages/prototypes/publication/components/PrototypeDataSample.tsx
src/explore-education-statistics-common/package-lock.json
src/explore-education-statistics-common/package.json
src/explore-education-statistics-common/src/components/Accordion.tsx
src/explore-education-statistics-common/src/components/AccordionSection.tsx
src/explore-education-statistics-common/src/components/Tabs.tsx
src/explore-education-statistics-common/src/components/TabsSection.tsx
src/explore-education-statistics-common/src/components/__tests__/Accordion.test.tsx
src/explore-education-statistics-common/src/components/__tests__/PageSearchForm.test.tsx
src/explore-education-statistics-common/src/components/__tests__/Tabs.test.tsx
src/explore-education-statistics-common/src/components/__tests__/__snapshots__/Accordion.test.tsx.snap
src/explore-education-statistics-common/src/components/__tests__/__snapshots__/AccordionSection.test.tsx.snap
src/explore-education-statistics-common/src/components/__tests__/__snapshots__/Tabs.test.tsx.snap
src/explore-education-statistics-common/src/hooks/useMounted.ts
src/explore-education-statistics-common/src/lib/type-guards/components/isComponentType.ts
src/explore-education-statistics-common/src/modules/find-statistics/components/DataBlock.tsx
src/explore-education-statistics-common/src/modules/find-statistics/components/__tests__/DataBlock.test.tsx
src/explore-education-statistics-common/src/modules/find-statistics/components/__tests__/__snapshots__/DataBlock.test.tsx.snap
src/explore-education-statistics-frontend/src/prototypes/publication/components/PrototypeDataSample.tsx
src/explore-education-statistics-frontend/src/prototypes/publication/components/PrototypeDataSampleApplications.tsx
src/explore-education-statistics-frontend/src/prototypes/publication/components/PrototypeDataSampleExclusions.tsx
src/explore-education-statistics-frontend/src/prototypes/publication/components/PrototypeDataSampleGCSE.tsx

This PR refactors the Accordion component so that the implementation is completely in React (rather than layering the GOVUK module on top). This should have the benefit of allowing us more flexibility in how we build on top of the Accordion in the future.
Following on from the Accordion, the Tabs component has also been changed so that `id`s for TabsSection components are auto-generated from an `id` provided to the parent Tabs component. This allows for easier use without having to add IDs to every TabsSection. This makes the behaviour more consistent with the Accordion when it comes to generation of IDs for child components.

Refactor Accordion and Tabs components

---

tests/newman/tests/data-api.json

Expectation is that it should be above 1 rather than 2 as most enviroments only have 2 themes. Resolves pass on dev but failure on test and production

Bugfix: Failing data api test due to theme count

---

src/explore-education-statistics-common/src/lib/utils/number/__tests__/formatPretty.test.ts
src/explore-education-statistics-common/src/lib/utils/number/formatPretty.ts
src/explore-education-statistics-frontend/src/modules/table-tool/components/DownloadCsvButton.tsx
src/explore-education-statistics-frontend/src/modules/table-tool/components/TimePeriodDataTable.tsx
src/explore-education-statistics-frontend/src/modules/table-tool/components/__tests__/DownloadCsvButton.test.tsx
src/explore-education-statistics-frontend/src/modules/table-tool/components/__tests__/__snapshots__/DownloadCsvButton.test.tsx.snap

This PR:
- Removes the unnecessary en-GB locale number formatting from the generated CSV.
- Abstracts the formatting from the generated table, into `formatPretty` util function.
- Changes CSV button text from 'Download data (.csv)' to 'Download underlying data (.csv)' to make it clearer that the data does not necessarily align with how the generated table looks.

DFE-759 Remove unnecessary formatting from CSV

---

src/explore-education-statistics-common/src/components/form/FormCheckbox.tsx
src/explore-education-statistics-common/src/components/form/FormCheckboxGroup.tsx
src/explore-education-statistics-common/src/components/form/FormCheckboxSearchSubGroups.tsx
src/explore-education-statistics-common/src/components/form/FormCheckboxSubGroups.tsx
src/explore-education-statistics-common/src/components/form/FormFieldCheckboxGroup.tsx
src/explore-education-statistics-common/src/components/form/FormFieldCheckboxSearchGroup.tsx
src/explore-education-statistics-common/src/components/form/FormFieldCheckboxSearchSubGroups.tsx
src/explore-education-statistics-common/src/components/form/FormFieldCheckboxSubGroups.tsx
src/explore-education-statistics-common/src/components/form/FormRadio.tsx
src/explore-education-statistics-common/src/components/form/FormRadioGroup.tsx
src/explore-education-statistics-common/src/components/form/__tests__/FormFieldCheckboxSearchSubGroups.test.tsx
src/explore-education-statistics-common/src/components/form/__tests__/FormFieldCheckboxSubGroups.test.tsx
src/explore-education-statistics-common/src/components/form/util/checkboxGroupFieldHelpers.ts
src/explore-education-statistics-frontend/src/modules/table-tool/components/FormFieldCheckboxGroupsMenu.tsx
src/explore-education-statistics-frontend/src/modules/table-tool/components/LocationFiltersForm.tsx
src/explore-education-statistics-frontend/src/modules/table-tool/components/__tests__/__snapshots__/FormFieldCheckboxGroupsMenu.test.tsx.snap

This PR fixes the 'Select all' button for checkbox sub-groups in `FormCheckboxSubGroups` not working when another sub-group with more options has already had all of their options selected.
As part of these changes, this has involved:
- Passing a `checked` parameter through to the `FormCheckboxGroup.onAllChange` handler. This fixes the bulk of the issue.
- Refactoring `FormCheckbox.onChange` to avoid having to memoize the parent's `onChange` handler (see `FormCheckboxGroup`). As part of this, we no longer provide the original `CheckboxOption` as a parameter, but this shouldn't be an issue as we weren't really using it anyway.

DFE-875 Fix 'Select all' button not working for all checkbox sub-groups

---

src/explore-education-statistics-common/src/components/ErrorSummary.tsx
src/explore-education-statistics-common/src/components/__tests__/ErrorSummary.test.tsx
src/explore-education-statistics-common/src/components/form/FieldCheckboxArray.tsx
src/explore-education-statistics-common/src/components/form/Form.tsx
src/explore-education-statistics-common/src/components/form/__tests__/Form.test.tsx

This PR fixes the excessive screen jumping that would occur due to the `ErrorSummary` grabbing the user's focus when there is a validation error. 
To fix this, we have introduced a `focusOnError` prop that toggles `ErrorSummary`s focusing behaviour and combined this with our `Form` implementation so that `focusOnError` is not true until the form has been submitted at least once.
- When the form is reset e.g. from moving back steps in table tool's wizard, all errors are now cleared. This includes submission errors that result from things like API calls failing.

DFE-882 Fix excessive screen jumping due to form validation and ErrorSummary

---

src/explore-education-statistics-common/src/polyfill.js

I've removed an arrow function that caused 'this' to be undefined - breaking the page

IE11 Frontend: Visiting anchor tag directly leads to grey screen

---

src/explore-education-statistics-frontend/src/modules/table-tool/TableToolPage.tsx

This PR fixes the `filterPublicationSubjectMeta` query not having the correct structure due to the chosen location options not being spread correctly into the query parameter.

DFE-1054 Fix meta query request not having correct location shape

---

src/GovUk.Education.ExploreEducationStatistics.Admin/Controllers/SigninController.cs
src/explore-education-statistics-admin/src/pages/sign-in/SignInPage.tsx

This PR adds a temp workaround to sign-in and redirect back to the react application.
This can be used until the full authentication process is implemented as a means of returning to the react app as the current sign-in process is built around as server side model.

DFE-1145: add workaround for admin sign-in to react dashboard

---

src/explore-education-statistics-frontend/src/hooks/useCookies.ts

Turns out Chrome will not set cookies that are secure when testing on localhost.
After testing with ngrok on `https` the secure cookies are set as expected

DFE-950: Cookies Banner w/ secure cookies

---

src/GovUk.Education.ExploreEducationStatistics.Data.Api/Services/ResultBuilder.cs

Table was previously not rendering if any of the measures have null values.

DFE-1137 Filter out null measures.

---

src/explore-education-statistics-frontend/src/pages/cookies/details.tsx

There is a separate ticket in the backlog to review the content of these cookies, as I'm unsure whether the purpose and durations I've added are correct: DFE-1302

Frontend: Adding ai_user and ai_session cookies to cookies details page

---

src/GovUk.Education.ExploreEducationStatistics.Data.Api/Models/Query/ObservationPredicateBuilder.cs

String interpolation results in the query being evaluated locally.

DFE-357 Reverting change suggested in PR comment.

---

armTemplates/ees-service/template.json
src/GovUk.Education.ExploreEducationStatistics.Admin/Controllers/Api/ReleaseController.cs

Disables file uploads adding a message to the import queue (while we sort out the import process).
Data api connection string changed to use public statistics database.

Disable adding message to queue once file uploaded in admin

---

src/GovUk.Education.ExploreEducationStatistics.Content.Api/Services/MethodologyService.cs

The set of logic for generating the tree is flawed but given the changes to the structure this should be a quick fix to the issue seen on dev, we only show the list of methodology if there is a valid release in the service.
I'm having a few docker db issues locally so if this could be checked on branch that would be awesome.

DFE-1359: Only show methodologies for publications with a live release

---

src/explore-education-statistics-frontend/src/components/PageMeta.tsx

Fixing: https://alpha-dfe-data.atlassian.net/browse/DFE-983
No longer using `react-helmet` and instead using `next/head`
Tested by requesting the page in postman and the appropriate <head><meta... tags are in there from the server.
This should fix the issue with page meta not appearing when sharing links etc.

Fix for PageMeta

---

src/explore-education-statistics-common/src/components/ContentSectionIndex.tsx
src/explore-education-statistics-common/src/styles/_print.scss

Does: 
- added some SCSS that will override the recharts CSS when we print, making it to have a `max-width: 100%`
- “In this section” section contents menu no longer is shown in print preview
Does *not*:
- Default headers and footers to off
- fix _"Altering the scale will still change to desktop view and then hides the tab information"_

DFE-1094 Additional Print Page functionality

---

src/GovUk.Education.ExploreEducationStatistics.Content.Model/Database/ApplicationDbContext.cs

There are no changes to content. No migrations need to run. This just cleans up the names of two enum values to match the new filter item names.

Correct the names of two filter items when building content

---

src/explore-education-statistics-frontend/src/modules/find-statistics/components/PublicationList.tsx
src/explore-education-statistics-frontend/src/modules/methodologies/MethodologyPage.tsx

Covers lists of publications on find stats page, with h3s added to publication titles. Also methodology search position moved to be consistent with the rest of the site.

EES-114 Updated header hierarchy + moved search box on methodology

---

src/GovUk.Education.ExploreEducationStatistics.Content.Api/Migrations/20190916133902_AlterDataBlockConfiguration.Designer.cs
src/GovUk.Education.ExploreEducationStatistics.Content.Api/Migrations/20190916133902_AlterDataBlockConfiguration.cs
src/GovUk.Education.ExploreEducationStatistics.Content.Model/DataQuery.cs
src/GovUk.Education.ExploreEducationStatistics.Content.Model/Database/ApplicationDbContext.cs

Changes 5 charts.
Updates the line chart configuration blocks to show legend at top of the chart.
Charts minor axis now begin at zero.
Corrects the case of some of the chart labels to be consistent.
Corrects one of the chart lines which was set for the wrong filter so it wasn't displaying.
Removes unused property `ShowLegend` from configuration block.

EES-115 Private beta

---

src/explore-education-statistics-common/src/modules/find-statistics/components/SummaryRenderer.module.scss

This PR sets all the key indicators to the same height, so they don't look uneven on the page

EES-218 Fix for heights of key indicator tiles

---

armTemplates/ees-service/dev.parameters.json
armTemplates/ees-service/prod.parameters.json
armTemplates/ees-service/test.parameters.json

This adds some of the arm template parameters into environment specific files.
Once this is merged then the pipeline can be updated to use these.
I've scaled down the admin app for now, and scaled up the data API in production.
This will be a part 1, and is just single instance scaling (scale up), once this is proven i'll raise another ticket to add more instances as a configuration option (scale out).

EES-317: Added arm template parameters files with scaling of sku's

---

src/GovUk.Education.ExploreEducationStatistics.Admin/Models/Api/ReleaseViewModel.cs

Set release live flag to the release view model this will then correctly display the release as "live" e.g. on the public facing site within the admin application.

EES-385: Set release live flag

---

src/explore-education-statistics-frontend/src/modules/methodologies/MethodologyPage.tsx

This fixes an issue where the dynamic id wasn't getting passed down to the 'In this section' links on the methodology pages.

EES-209 Fix for methodology page

---

src/explore-education-statistics-common/src/components/form/FormFieldset.tsx
src/explore-education-statistics-common/src/components/form/__tests__/__snapshots__/FormCheckboxGroup.test.tsx.snap
src/explore-education-statistics-common/src/components/form/__tests__/__snapshots__/FormCheckboxSearchGroup.test.tsx.snap
src/explore-education-statistics-common/src/components/form/__tests__/__snapshots__/FormCheckboxSearchSubGroups.test.tsx.snap
src/explore-education-statistics-common/src/components/form/__tests__/__snapshots__/FormFieldset.test.tsx.snap
src/explore-education-statistics-common/src/modules/table-tool/components/FiltersForm.tsx
src/explore-education-statistics-common/src/modules/table-tool/components/PublicationSubjectForm.tsx
src/explore-education-statistics-common/src/modules/table-tool/components/WizardStepHeading.tsx
src/explore-education-statistics-common/src/modules/table-tool/components/__tests__/__snapshots__/FormFieldCheckboxGroupsMenu.test.tsx.snap

Altered default sizing of table-tool header components to give a more hierarchical structure for clarity
https://alpha-dfe-data.atlassian.net/browse/EES-162

EES-162 table tool header clarification

---

src/explore-education-statistics-common/src/components/ErrorPrefixPageTitle.tsx
src/explore-education-statistics-common/src/components/ErrorSummary.tsx

Ticket: https://alpha-dfe-data.atlassian.net/browse/EES-403
> Ensure that when an error occurs, the page title is prefixed with the text ‘Error:’ to enableusers to determine that there are errors on the page, immediately.Example of how to achieve this can be found at:https://design-system.service.gov.uk/components/error-summary/
-----
Added a `ErrorPrefixPageTitle` component which when rendered will always prefix the page title with `"ERROR: "`. 
The component attempts to removed the prefix when unMounting, however the prefix remains if there are other ErrorPrefixPageTitle's present

EES-403 Page Title 'ERROR: ' prefixing

---

src/explore-education-statistics-frontend/src/modules/table-tool/TableToolPage.tsx

I debugged clicking the methodology link on the Table Tool page and found it was trying to GET
http://localhost:5010/api/Methodology/**undefined**
I.e. the publication slug segment of the service call in methodologyService.ts was undefined.
Fixed it by correcting the publication slug link parameter on the Table Tool page.

EES-434 Correcting methodology link

---

src/GovUk.Education.ExploreEducationStatistics.Publisher/Services/FileStorageService.cs

We produce a zip containing all the files which are copied from the Admin to the Public site when a release happens. This will be:
- Data (i.e. the original csv files but not the meta files) that have been uploaded via the Admin.
- Ancillary files that have been uploaded via the Admin.
- Media, i.e. images and other charts that have been uploaded via the Admin.
The zip file is created in the ancillary directory in the Public site and has a label property for the UI of “All files”.
The content cache function produces the list of files which appear under the “Download data files” link. The list comprises of the following two directories:
- ancillary (which now includes the “All files” zip entry) 
- data 
The list of files is sorted alphabetically A-Z. We might want further work on …

EES-512 - Display the zip of all files for download

---

src/explore-education-statistics-common/package-lock.json
src/explore-education-statistics-common/package.json
src/explore-education-statistics-common/src/components/AriaLiveAnnouncer.tsx
src/explore-education-statistics-common/src/components/AriaLiveMessage.tsx
src/explore-education-statistics-common/src/components/LoadingSpinner.tsx
src/explore-education-statistics-frontend/src/modules/table-tool/TableToolPage.tsx
src/explore-education-statistics-frontend/src/pages/_app.tsx

Ticket: https://alpha-dfe-data.atlassian.net/browse/EES-409
The frontend app has been now been wrapped with AriaLiveAnnouncer component that provides a context that can be used by the AriaLiveMessage components to send messages into an [aria-live region](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/ARIA_Live_Regions) to notify users that rely on audio feedback as to why they might be waiting on a page (ie: table-tool).
LoadingSpinner component now renders an AriaLiveMessage with a default message of "The page is loading."

EES-409 Notify users that rely on audio feedback when a page is Loading... (spinner)

---

src/GovUk.Education.ExploreEducationStatistics.Admin/Mappings/MappingProfiles.cs

Mapping InternalReleaseNote and ReleaseStatus fields of the Release to the corresponding fields in the ReleaseSummaryViewModel since these fields are not currently versioned.

EES-642 Mapping InternalReleaseNote and ReleaseStatus fields

---

src/explore-education-statistics-common/src/modules/table-tool/components/FixedMultiHeaderDataTable.tsx

Tested with Windows Narrator after the change and the screen reader still successfully reads the table header and its contents after being tabbed into.

EES-414 - Table keyboard scroll accessibility

---

src/GovUk.Education.ExploreEducationStatistics.Data.Api/GovUk.Education.ExploreEducationStatistics.Data.Api.csproj
src/GovUk.Education.ExploreEducationStatistics.Data.Model/GovUk.Education.ExploreEducationStatistics.Data.Model.csproj
src/GovUk.Education.ExploreEducationStatistics.Data.Model/Migrations/20190819131048_InitialCreate.Designer.cs
src/GovUk.Education.ExploreEducationStatistics.Data.Model/Migrations/20190819131048_InitialCreate.cs
src/GovUk.Education.ExploreEducationStatistics.Data.Model/Migrations/20190819131247_IntialCreate_Custom.Designer.cs
src/GovUk.Education.ExploreEducationStatistics.Data.Model/Migrations/20190819131247_IntialCreate_Custom.cs
src/GovUk.Education.ExploreEducationStatistics.Data.Model/Migrations/20190830082721_AddCsvRowFieldToObservation.Designer.cs
src/GovUk.Education.ExploreEducationStatistics.Data.Model/Migrations/20190830082721_AddCsvRowFieldToObservation.cs
src/GovUk.Education.ExploreEducationStatistics.Data.Model/Migrations/20191008162516_UpdateFilteredObservationsStoredProc.Designer.cs
src/GovUk.Education.ExploreEducationStatistics.Data.Model/Migrations/20191008162516_UpdateFilteredObservationsStoredProc.cs
src/GovUk.Education.ExploreEducationStatistics.Data.Model/Migrations/20191101153547_Ees263UpdateFilteredObservationsStoredProc.Designer.cs
src/GovUk.Education.ExploreEducationStatistics.Data.Model/Migrations/20191101153547_Ees263UpdateFilteredObservationsStoredProc.cs
src/GovUk.Education.ExploreEducationStatistics.Data.Model/Migrations/StatisticsDbContextModelSnapshot.cs

The migrations directory wasn't being found after the migrations were moved to the Data.Model library project. Also updating the namespace of the migrations classes.

EES-633 Fix migration SQL files not being found

---

src/GovUk.Education.ExploreEducationStatistics.Data.Importer/Services/CsvUtil.cs

Spotted when two indicator groups were created for the same group name, one with trailing whitespace.
@shakes90 see what you think to the difference in timings.
Alternatively this could be dealt with through validation or trimming individual fields such as the group names.

EES-350 Trim leading and trailing whitespace. 

---

src/explore-education-statistics-admin/src/modules/chart-builder/ChartAxisConfiguration.tsx
src/explore-education-statistics-common/src/modules/find-statistics/components/charts/ChartFunctions.tsx

A conditional override value for tickSpacing to avoid rendering potentially 1000's of ticks
I believe the problem to be that the default value for tickSpacing to be set to `1`.
The problem with that is that in this particular chart, outlined in the ticket, the minimum and maximum values on the Y-axis are 0 and 300,000 respectively. As the user selects _Custom_, the chart attempts to render a tick for every `1` value between the 0 and 300,000; resulting in 299,998 ticks attempting to render - resulting in a browser crash due to insufficient memory.
The solution I've implemented is to provide a reasonable tickSpacing value whenever the tickSpacing input changes to ensure that a maximum of 100 ticks can be attempted to be rendered.

EES-646 chart axis freezing bug

---

src/GovUk.Education.ExploreEducationStatistics.Admin/Startup.cs

Allows use of swagger to testing api calls with a valid token

Adding Bearer token to admin swagger documentation

---

src/explore-education-statistics-admin/src/modules/chart-builder/ChartAxisConfiguration.tsx
src/explore-education-statistics-common/src/modules/find-statistics/components/charts/ChartFunctions.tsx

Should now just work, as the override steps in before rendering, whereas before it was stepping in on input change, which meant it was being missed on initial render (causing the crash)

moved the previous fix (reasonable tick override) to a more appropriate place

---

infrastructure/templates/template.json

Adds om a new storage account specific to the publisher.
Changes the publisher to now use the storage account. Queues to trigger functions will now need to use this storage account.

EES-873: Add in new storage account for publisher

---

src/explore-education-statistics-admin/src/pages/release/edit-release/manage-datablocks/CreateDataBlocks.tsx
src/explore-education-statistics-admin/src/pages/release/edit-release/manage-datablocks/DataBlockDetailsForm.tsx
src/explore-education-statistics-admin/src/pages/release/edit-release/manage-datablocks/ReleaseManageDataBlocksPage.tsx

Ticket: https://alpha-dfe-data.atlassian.net/browse/EES-626
Various fixes to datablock creation/edit state handling.
The main on being that the initial Values in CreateDataBlocks.tsx are now stored in state - as opposed to being generated on each render (which was the main cause of the bug)
Some other bugs I spotted also have been squished.
notably: _Removed the ID of the currentDataBlock in DataBlockDetailsForm.tsx to avoid updating a previously edited(viewed) datablock when going back to create a new datablock_

bugfixes to datablock creation

---

src/explore-education-statistics-admin/src/components/ProtectedRoute.tsx
src/explore-education-statistics-admin/src/components/ProtectedRoutes.tsx
src/explore-education-statistics-admin/src/components/api-authorization/AuthorizeService.js
src/explore-education-statistics-admin/src/components/api-authorization/LoginMenu.js
src/explore-education-statistics-admin/src/services/sign-in/types.ts

AuthenticationService now returns full user details, not just profile and we now store a "validToken" prop on the user state of the LoginContext.
~On a side note:~
> ~The user's refreshToken coming back from the AuthenticationService is undefined - could the be causing the the silentRefresh of the token to fail?~ (see futher comment below)
If the user navigates to a ProtectedRoute with an expired token, it will redirect in the same way as if the user is not logged in.

EES-751 - Another stab at the expired token handling of the client

---

src/explore-education-statistics-common/src/modules/table-tool/components/TimePeriodDataTable.tsx
src/explore-education-statistics-common/src/modules/table-tool/components/utils/tableToolHelpers.ts

Ensure that rows and results are mapped correctly by checking the location level when mapping.

EES-964: Table bug, duplication rows / wrong data on similar locations (same code different location level)

---

src/GovUk.Education.ExploreEducationStatistics.Data.Services/ViewModels/Meta/ObservationalUnitGeoJsonMeta.cs
src/explore-education-statistics-admin/src/pages/release/edit-release/manage-datablocks/CreateDataBlocks.tsx
src/explore-education-statistics-admin/src/pages/release/edit-release/manage-datablocks/DataBlockDetailsForm.tsx

removed redundant line, removed initial table config in datablock create request && Use GeographicLevel value as camel case rather than EnumValue annotation value, as expected by the UI.

EES-1021 - Datablock issues

---

src/GovUk.Education.ExploreEducationStatistics.Admin.Tests/Services/ManageContent/ContentServicePermissionTests.cs
src/GovUk.Education.ExploreEducationStatistics.Admin/Controllers/Api/ManageContent/ContentController.cs
src/GovUk.Education.ExploreEducationStatistics.Admin/Controllers/Api/ManageContent/UpdateDataBlockRequest.cs
src/GovUk.Education.ExploreEducationStatistics.Admin/Migrations/ContentMigrations/20200117121041_AddGuidanceTitleToDataBlock.Designer.cs
src/GovUk.Education.ExploreEducationStatistics.Admin/Migrations/ContentMigrations/20200117121041_AddGuidanceTitleToDataBlock.cs
src/GovUk.Education.ExploreEducationStatistics.Admin/Services/Interfaces/ManageContent/IContentService.cs
src/GovUk.Education.ExploreEducationStatistics.Admin/Services/ManageContent/ContentService.cs
src/GovUk.Education.ExploreEducationStatistics.Content.Model/ContentSection.cs
src/GovUk.Education.ExploreEducationStatistics.Content.Model/Database/ContentDbContext.cs

This PR:
- adds a field for Guidance Title for Key Stats tiles
- adds an API call for updating an attached Data Block with Trend, Guidance Text and Guidance Title

EES-1083 - added ability to update text fields on Data Blocks

---

src/explore-education-statistics-common/src/styles/patterns/_dfe-modifiers.scss

CSS fix for markdown code not wrapping

EES-1111 Mark down not wrapping and breaking out of page structure

---

src/explore-education-statistics-common/src/modules/find-statistics/components/ContentSubBlockRenderer.tsx
src/explore-education-statistics-frontend/src/modules/find-statistics/PublicationReleasePage.tsx

This reverts commit 2e53439df219a1cbe102b3df06be6cbe8d69badf.
Reverting the temporary regex solution.
After the following PR was merged, developers who recreate their Content database should no longer have an issue as a fix to the Markdown content was applied to the IntialCreate.cs migration file.
https://github.com/dfe-analytical-services/explore-education-statistics/pull/1200
The affected Markdown blocks were also manually updated in all environments so this temporary regex solution _should_ no longer be needed.

Revert "EES-1117 - Regex temp solution"

---

src/GovUk.Education.ExploreEducationStatistics.Publisher/Services/ReleaseService.cs

The generate content task considers the latest release to be the one with the most recent published date.
A bug occurs because the release has no published date set until all stages of publishing have been completed, which is after the generate content task has been run.

EES-1177 Order by publish scheduled if the release hasn't been published yet

---

src/explore-education-statistics-common/src/components/TabsSection.module.scss
src/explore-education-statistics-common/src/components/TabsSection.tsx
src/explore-education-statistics-common/src/components/__tests__/__snapshots__/Tabs.test.tsx.snap

The problem seemed to be that when a tab was hidden using the 'govuk-visually-hidden' class it was setting the container width to 1px which was messing up some of the math functionality on the charts.
This also fixes charts in datablocks when printing

BAU/PP-160 - Chart width: A negative value is not valid. ("-89")

---

src/explore-education-statistics-common/src/modules/table-tool/components/FiltersForm.tsx
src/explore-education-statistics-common/src/modules/table-tool/components/LocationFiltersForm.tsx
src/explore-education-statistics-common/src/modules/table-tool/components/PublicationForm.tsx
src/explore-education-statistics-common/src/modules/table-tool/components/PublicationSubjectForm.tsx
src/explore-education-statistics-common/src/modules/table-tool/components/TableHeadersForm.tsx
src/explore-education-statistics-common/src/modules/table-tool/components/TableToolWizard.tsx
src/explore-education-statistics-common/src/modules/table-tool/components/TimePeriodForm.tsx
src/explore-education-statistics-frontend/src/modules/table-tool/TableToolPage.tsx
src/explore-education-statistics-frontend/src/modules/table-tool/components/TableTool.tsx

⚠️ **Depends on `run-script` branch**
This PR disables table tool form validations from occurring for `onChange` and `onBlur` events. Validation will now only occur on form submission.

PP-100/103 Disable onChange/Blur validations for table tool forms

---

src/GovUk.Education.ExploreEducationStatistics.Admin/Services/PreReleaseService.cs

This PR:
- dummies out the Methodology link on the RHS of the Pre Release page (links within content aren't affected)
- dummies out Other Releases links that aren't legacy links

EES-1238 - fix for null PublishScheduled date

---

src/explore-education-statistics-admin/src/modules/find-statistics/PublicationReleaseContent.tsx
src/explore-education-statistics-admin/src/modules/find-statistics/components/RelatedInformationSection.tsx

This PR:
- replaces methodology links and Other Releases links (that aren't legacy releases) with dummy "#" links
Note that this does not affect links embedded within content.

EES-1263 - dummied out links

---

src/GovUk.Education.ExploreEducationStatistics.Publisher.Model/ReleaseStatus.cs
src/GovUk.Education.ExploreEducationStatistics.Publisher/Functions/DataFactoryPipelineStatusFunction.cs
src/GovUk.Education.ExploreEducationStatistics.Publisher/Functions/GenerateReleaseContentFunction.cs
src/GovUk.Education.ExploreEducationStatistics.Publisher/Functions/PublishReleaseContentFunction.cs
src/GovUk.Education.ExploreEducationStatistics.Publisher/Functions/PublishReleaseDataFunction.cs
src/GovUk.Education.ExploreEducationStatistics.Publisher/Functions/PublishReleaseFilesFunction.cs
src/GovUk.Education.ExploreEducationStatistics.Publisher/Services/Interfaces/IReleaseStatusService.cs
src/GovUk.Education.ExploreEducationStatistics.Publisher/Services/ReleaseStatusService.cs

For example, if the data factory pipeline fails it would be handy to have the message in the release status table to avoid having to backtrack to work out the release status id from the release, go to data factory and work out which is the corresponding data factory pipeline run (there could be a few), and then read the error message.
This PR appends messages if any of the stages fail, hopefully giving a quick indication of what the cause is.

EES-1224 Appending messages if a stage fails

---

src/explore-education-statistics-common/src/components/Details.tsx
src/explore-education-statistics-common/src/components/__tests__/__snapshots__/Details.test.tsx.snap
src/explore-education-statistics-common/src/components/form/FormCheckboxSearchGroup.tsx
src/explore-education-statistics-common/src/components/form/FormCheckboxSearchSubGroups.tsx
src/explore-education-statistics-common/src/components/form/__tests__/FormCheckboxSearchGroup.test.tsx
src/explore-education-statistics-common/src/components/form/__tests__/FormCheckboxSearchSubGroups.test.tsx
src/explore-education-statistics-common/src/modules/table-tool/components/PublicationForm.tsx
src/explore-education-statistics-common/src/modules/table-tool/components/__tests__/PublicationForm.test.tsx

This PR simply swaps out the regex based search implementations to simpler `includes` checks on lowercased strings (which will achieve the same thing).

PP-240 Fix search boxes that can break when invalid regex character like '[' is entered

---

src/explore-education-statistics-admin/src/modules/find-statistics/components/ReleaseHeadlines.tsx
src/explore-education-statistics-common/src/modules/find-statistics/components/TimePeriodDataTableRenderer.tsx
src/explore-education-statistics-frontend/src/modules/permalink/PermalinkPage.tsx

This PR fixes a regression due to earlier refactoring which removed `mapTableHeadersConfig` from being applied in `TimePeriodDataTable` itself. We now apply this function in all the relevant call sites (particularly in release content), so that our tables are not just populated with n/a's.

EES-1424 Fix tables showing n/as in release content

---

src/explore-education-statistics-common/src/components/CollapsibleList.module.scss
src/explore-education-statistics-common/src/modules/table-tool/components/FixedMultiHeaderDataTable.module.scss
src/explore-education-statistics-frontend/src/modules/permalink/PermalinkPage.tsx

Set permalink page to be full page with to better facilitate large tables.
Restricted the width of the surrounding text - table titles, and footnotes,  following GDS guidelines for text legibility

BAU-343 Full width permalink page

---

src/explore-education-statistics-common/src/modules/table-tool/components/DownloadExcelButton.tsx
src/explore-education-statistics-common/src/modules/table-tool/components/__tests__/DownloadExcelButton.test.tsx
src/explore-education-statistics-frontend/src/modules/table-tool/components/TableTool.tsx

This PR also refactors the `appendFootnotes` function to use the built-in `sheet_add_json` util function to add the footnotes.

BAU-15 Add title to table spreadsheet

---

src/explore-education-statistics-admin/src/pages/release/edit-release/manage-datablocks/components/ChartBuilder.tsx
src/explore-education-statistics-admin/src/pages/release/edit-release/manage-datablocks/components/ChartDataConfiguration.tsx
src/explore-education-statistics-admin/src/pages/release/edit-release/manage-datablocks/components/ChartDataSelector.module.scss
src/explore-education-statistics-admin/src/pages/release/edit-release/manage-datablocks/components/ChartDataSelector.tsx
src/explore-education-statistics-admin/src/pages/release/edit-release/manage-datablocks/components/DataBlockDetailsForm.tsx
src/explore-education-statistics-admin/src/pages/release/edit-release/manage-datablocks/components/DataBlockSourceWizard.tsx
src/explore-education-statistics-admin/src/pages/release/edit-release/manage-datablocks/components/graph-builder.module.scss
src/explore-education-statistics-common/src/components/form/Form.tsx
src/explore-education-statistics-common/src/components/form/__tests__/Form.test.tsx
src/explore-education-statistics-common/src/modules/charts/types/chart.ts
src/explore-education-statistics-common/src/modules/charts/util/__tests__/chartUtils.test.ts
src/explore-education-statistics-common/src/modules/charts/util/chartUtils.ts
src/explore-education-statistics-common/src/modules/table-tool/components/FiltersForm.tsx
src/explore-education-statistics-common/src/modules/table-tool/components/LocationFiltersForm.tsx
src/explore-education-statistics-common/src/modules/table-tool/components/PublicationForm.tsx
src/explore-education-statistics-common/src/modules/table-tool/components/PublicationSubjectForm.tsx
src/explore-education-statistics-common/src/modules/table-tool/components/TimePeriodForm.tsx

This PR:
- Adds multiple selects for each filter type e.g. Characteristics, School Types, etc when building a chart. This makes it easier for a user to select the filters in a more granular way, whereas before they were represented using a single select with all of the option combinations as comma separated strings.
- Fixing the filters UI also nicely fixes this ticket's issue.
- Adds validation and error messages to the `ChartDataSelector` form so that the user receives feedback properly.
- Tidy up how the `DataBlockDetailsForm` is presented to make it more obvious to the user. Currently it can be a little hidden away if the data table has footnotes.
- Refactors styles for `ChartDataSelector` out of the catch-all `graph-builder.module.scss` stylesheet. This needs further refactoring to …

EES-778 Allow creation of charts without filters

---

src/explore-education-statistics-common/src/components/TabsSection.tsx
src/explore-education-statistics-common/src/components/__tests__/__snapshots__/Tabs.test.tsx.snap
src/explore-education-statistics-common/src/modules/find-statistics/components/SummaryRenderer.module.scss
src/explore-education-statistics-common/src/modules/find-statistics/components/__tests__/__snapshots__/DataBlock.test.tsx.snap

Updated key stats panel styling:
- Help details now appear below the indicator
- Restricted the help text title to one line, to prevent use of overly long titles and wrapping issues.

BAU-289 Key stats help and guidance dialog position

---

src/GovUk.Education.ExploreEducationStatistics.Admin/Migrations/ContentMigrations/20200313092647_AddPlanningAreaToDataBlockRequest.Designer.cs
src/GovUk.Education.ExploreEducationStatistics.Admin/Migrations/ContentMigrations/20200313092647_AddPlanningAreaToDataBlockRequest.cs

This is an additional migration as it appears that if you add a field to statistics Location this needs to be carried over to the Content DataBlockRequest.

BAU-342 Add new location planning_area to DataBlockRequests.

---

src/explore-education-statistics-common/src/components/CollapsibleList.module.scss
src/explore-education-statistics-common/src/modules/table-tool/components/FixedMultiHeaderDataTable.module.scss
src/explore-education-statistics-common/src/styles/_layout.scss
src/explore-education-statistics-common/src/styles/patterns/_dfe-modifiers.scss
src/explore-education-statistics-frontend/src/components/CookieBanner.module.scss
src/explore-education-statistics-frontend/src/components/PrintThisPage.module.scss
src/explore-education-statistics-frontend/src/components/PrintThisPage.tsx
src/explore-education-statistics-frontend/src/modules/permalink/PermalinkPage.module.scss
src/explore-education-statistics-frontend/src/modules/permalink/PermalinkPage.tsx

Added 'Print this page' CTA to permalink page. 
Added some extra props to the print button component to allow for better alignment within the permalink page.
Updated print styles to make better use of space for text, and also hidden unnecessary elements on the printed page.

BAU-294 Permalink print page styling

---

azure-pipelines.dfe.yml
azure-pipelines.pr.yml
src/explore-education-statistics-admin/package.json
src/explore-education-statistics-common/package-lock.json
src/explore-education-statistics-common/package.json
src/explore-education-statistics-frontend/package.json

This PR changes the way that Jest test artifacts for the frontend are being published. Previously we were publishing them as several test runs in Azure DevOps, but now we can merge them into a single test run for the PR and Release pipelines respectively.
This has the main advantage of Jest tests being in a single artifact, rather than multiple.

BAU-282 Publish Jest test artifacts as single test run

---

infrastructure/templates/datafactory/components/template.json

Apparently ordering of these mappings matters, even though they are mappings!

EES-1522 Correct order of Location fields in Data Factory

---

azure-pipelines.dfe.yml

Reverts the earlier scoping of `npm run bootstrap` as this causes dependent tasks (such as `tsc`) to fail.
We should refactor the entire pipeline in subsequent PR so that we only need to run the entire frontend build (public and admin) in one stage and avoid multiple bootstraps.

BAU-417 Remove scoping of bootstrap steps to dependent step failures

---

src/explore-education-statistics-admin/src/components/ErrorBoundary.tsx
src/explore-education-statistics-admin/src/hooks/useFormSubmit.ts
src/explore-education-statistics-common/src/components/form/util/serverValidationHandler.ts

This PR fixes the regression that was caused by a missing `await` in the `withoutErrorHandling` method.
We also improve the `handleServerSideValidation` function by removing its use of currying as it just makes the function slightly awkward to use.

EES-1571 Fix server validation errors not being correctly handled by useFormSubmit

---

src/explore-education-statistics-common/src/components/CollapsibleList.tsx
src/explore-education-statistics-common/src/components/__tests__/CollapsibleList.test.tsx
src/explore-education-statistics-common/src/modules/charts/components/ChartRenderer.tsx
src/explore-education-statistics-common/src/modules/find-statistics/components/DataBlockRenderer.tsx
src/explore-education-statistics-common/src/modules/find-statistics/components/__tests__/__snapshots__/DataBlockRenderer.test.tsx.snap
src/explore-education-statistics-common/src/modules/table-tool/components/DownloadExcelButton.tsx
src/explore-education-statistics-common/src/modules/table-tool/components/FixedMultiHeaderDataTable.tsx
src/explore-education-statistics-common/src/modules/table-tool/components/TimePeriodDataTable.tsx
src/explore-education-statistics-frontend/src/modules/permalink/PermalinkPage.tsx

This PR adds data block `source` information to charts and tables.
- Fixes `PermalinkPage` not having a button for downloading the XLSX version of the table.
- De-pluralises text used for the `CollapsibleList` button if there is only 1 hidden list item.

EES-1212 Add source to datablock charts/tables

---

src/GovUk.Education.ExploreEducationStatistics.Admin/Controllers/Api/BAU/BauUsersController.cs
src/GovUk.Education.ExploreEducationStatistics.Admin/Services/Interfaces/IUserManagementService.cs
src/GovUk.Education.ExploreEducationStatistics.Admin/Services/UserManagementService.cs
src/GovUk.Education.ExploreEducationStatistics.Admin/Startup.cs
src/GovUk.Education.ExploreEducationStatistics.Admin/Validators/ValidationUtils.cs
src/GovUk.Education.ExploreEducationStatistics.Admin/ViewModels/RoleViewModel.cs
src/GovUk.Education.ExploreEducationStatistics.Admin/ViewModels/UserInviteViewModel.cs
src/explore-education-statistics-admin/src/components/PageFooter.tsx
src/explore-education-statistics-admin/src/components/PageHeader.tsx
src/explore-education-statistics-admin/src/pages/bau/BauDashboardPage.tsx
src/explore-education-statistics-admin/src/pages/bau/BauUsersPage.tsx
src/explore-education-statistics-admin/src/pages/users/ManageUserPage.tsx
src/explore-education-statistics-admin/src/pages/users/PendingInvitesPage.tsx
src/explore-education-statistics-admin/src/pages/users/PreReleaseUsersPage.tsx
src/explore-education-statistics-admin/src/pages/users/UserInvitePage.tsx
src/explore-education-statistics-admin/src/routes/dashboard/routes.ts
src/explore-education-statistics-admin/src/services/users/service.ts
src/explore-education-statistics-admin/src/services/users/types.ts

This PR updates the Platform administration functions to better support the BAU team in the management of users.
This specific PR does the following:
- BAU-549 - Improves user invites with ability to assign role
- BAU-550 -Moves "Platform administration" from the footer to the main menu with associated permissions check
- BAU-551 - Adds a"Pre-release" users section in platform administration for display of pre-release users (and thus removing this from the main user management page)
- BAU-552 - Displays a users role on the user management page-
- Updates the Platform administration page to be a bit more user friendly than a text list of links.
- BAU-554 - Add the ability to cancel a user invite
⚠️ Contains some WIP
This PR Also contains a small amount of UI WIP for Part 2 which will add …

BAU-553: Improve user management - Part 1

---

src/explore-education-statistics-common/src/components/Details.tsx
src/explore-education-statistics-common/src/components/PageSearchForm.tsx
src/explore-education-statistics-common/src/components/__tests__/Details.test.tsx
src/explore-education-statistics-common/src/components/__tests__/PageSearchForm.test.tsx
src/explore-education-statistics-common/src/utils/delay.ts
src/explore-education-statistics-frontend/src/modules/find-statistics/FindStatisticsPage.tsx
src/explore-education-statistics-frontend/src/modules/find-statistics/components/PublicationList.tsx

This PR fixes a fairly subtle timing issue that meant that the required `Details` component to open would not register the click to open it correctly when using `PageSearchForm`.
I believe the `Details` could fail to open as React could potentially be in the middle of re-rendering the component, meaning that the click event could potentially be lost.
We've added delays to simply slow down the code enough that React has time to fully update the DOM before we try and do some subsequent steps.
- Changed `Details` to render with a stable auto-generated default `id` prop. Previously re-rendering would cause the default `id` prop to change, changing the ids used in the DOM.
- Cleaned up markup/styling around `PublicationList`.

BAU-468, BAU-195 Fix timing issue causing Details to fail to open when searching

---

src/GovUk.Education.ExploreEducationStatistics.Admin/Services/FootnoteService.cs

This can be reproduced by engineering a footnote to be orphaned, i.e. with no matching criteria which is what appears to have happened in the Test environment where there is bad data. No matching criteria means:
- No subject links
- No filter links
- No filter group links
- No filter item links
- No indicator links
This should never happen but can be setup as follows in any environment:
In the Admin set up two Releases with at least one file uploaded to both.
On one of the Releases create a footnote with some dummy text for the Subject and make it applicable to all filters and indicators (i.e. it has a just a Subject link).
Switch to the Footnotes tab on the other Release and observe that no footnotes are visible.
Now delete the Subject link directly from the database.
Observe that the …

EES-706 Prevent querying orphaned footnotes with no matching criteria

---

src/explore-education-statistics-frontend/server.js

This PR prevents basic auth from triggering on Next's static assets in `/_next/static`. 
IE11 shows multiple auth prompts on initial render due to loading in multiple additional static asset chunks via XHR. Getting any of these prompts wrong will mean that the associated static asset for that prompt will proceed to return 401s. 
Any asset chunks that fail to load in can break their respective parts of the application when trying to navigate to them via page links. By de-authenticating these assets, we should no longer get multiple auth prompts and also stop the app from breaking.

EES-749 Stop basic auth from triggering on Next's static assets

---

src/explore-education-statistics-admin/src/pages/release/edit-release/manage-datablocks/components/ChartAxisConfiguration.tsx
src/explore-education-statistics-common/src/components/form/FormSelect.tsx
src/explore-education-statistics-common/src/modules/charts/util/__tests__/createDataSetCategories.test.ts
src/explore-education-statistics-common/src/modules/charts/util/createDataSetCategories.ts

This PR removes siblingless filters from the chart when grouping by 'Filters'. 
The user will typically find it undesirable to show filters from groups where there is only one option selected. An example of this would be the following chart:
FTE is the only option selected in it's filter group, and will end up aggregating all of the data sets from the other categories (hence why it has 5 bars). This isn't particularly useful to the user as it doesn't provide any better granularity of the data than the other filter groups. Consequently, we should just remove these.

EES-758 Remove siblingless filters from charts

---

src/explore-education-statistics-common/src/modules/find-statistics/components/__tests__/__snapshots__/DataBlockRenderer.test.tsx.snap
src/explore-education-statistics-common/src/modules/table-tool/components/MultiHeaderTable.module.scss
src/explore-education-statistics-common/src/modules/table-tool/components/MultiHeaderTable.tsx
src/explore-education-statistics-common/src/modules/table-tool/components/__tests__/MultiHeaderTable.test.tsx
src/explore-education-statistics-common/src/modules/table-tool/components/__tests__/__snapshots__/FixedMultiHeaderDataTable.test.tsx.snap
src/explore-education-statistics-common/src/modules/table-tool/components/__tests__/__snapshots__/MultiHeaderTable.test.tsx.snap
src/explore-education-statistics-common/src/modules/table-tool/components/__tests__/__snapshots__/TimePeriodDataTable.test.tsx.snap
src/explore-education-statistics-common/src/modules/table-tool/utils/getDefaultTableHeadersConfig.ts
src/explore-education-statistics-common/src/modules/table-tool/utils/mapTableHeadersConfig.ts

This PR fixes 'Total' filters being potentially removed from tables when they shouldn't be. This was due to:
- Aggressive filtering of filters based on them being totals.
- Incorrect merging of identical headers.
- Simplified `MultiHeaderTable` styling. Due to the new header merging rules that have been implemented, the styling for the column headers could easily be made to look bad.
To avoid this, we just simplify the styling by mostly getting rid of conditional classes and default to the following:
When more than one column header row:
- Use `text-align: center` and grey background
When single column header row:
- Use `text-align: right` and white background

EES-765 Fix 'Total' filters being incorrectly removed from tables

---

src/explore-education-statistics-admin/src/pages/release/edit-release/manage-datablocks/components/DataBlockSourceWizard.tsx
src/explore-education-statistics-common/src/modules/table-tool/components/TimePeriodDataTable.tsx

This PR addresses potential issues wherein a user might attempt to reorder the table headers **after** they have changed part of the data block's table query e.g. changed some indicators, filters, etc. The current implementation will cause the previous table query to be persisted alongside the new table header config (which has the new filters/indicators/whatever).
As the table header config and table query no longer match, this will cause `TimePeriodDataTable` to throw an error as it cannot correctly construct the headers for the table.
- Simply don't update the data block when re-ordering table headers. This didn't really make sense anyway in the UI as there is the 'Save data block' button further down the page that should be used instead.
- Wrap `TimePeriodDataTable` with an …

EES-774 Prevent incorrect saving of data block when reordering table headers

---

src/GovUk.Education.ExploreEducationStatistics.Admin/Migrations/ContentMigrations/20200430093743_EES760UpdatePublicationsTopicsAndThemes.Designer.cs
src/GovUk.Education.ExploreEducationStatistics.Admin/Migrations/ContentMigrations/20200430093743_EES760UpdatePublicationsTopicsAndThemes.cs
src/GovUk.Education.ExploreEducationStatistics.Content.Model/Database/ContentDbContext.cs

- Moved Publication `Graduate labour market statistics` to topic `Higher education graduate employment and earnings`.
- Removed the (now) unused topic `Graduate labour market`.
- Changed the Publication slug from `graduate-labour-markets` to `graduate-labour-market-statistics`.
- Change two theme summaries.
By default EF migration tool wanted to delete the Publication and recreate it which would have deleted any draft Releases. This is a custom migration to avoid that.

EES-760 Change publication topic, remove unused topic, correct publication slug, change theme text

---

src/explore-education-statistics-admin/src/pages/release/edit-release/manage-datablocks/components/ReleaseManageDataBlocksPageTabs.tsx
src/explore-education-statistics-common/src/modules/find-statistics/hooks/useTableQuery.ts

This PR adds additional `onSuccess` and `onError` callback options to `useTableQuery`, allowing us to better synchronise the subject meta query (`filterPublicationSubjectMeta`) that is dependent on the table query result.
Currently, these queries can easily become de-synchronized whenever the `selectedDataBlock` prop changes (e.g. when the data block is saved). This consequently causes stale table tool state to be propagated leading to null pointer errors.

EES-735 Fix updating of table query causing desynchronization of table tool state

---

src/GovUk.Education.ExploreEducationStatistics.Admin/Services/DataBlockMigrationService.cs

While transforming each datablock we execute a query to get the metadata and this has a security check which was failing when trying to query the latest release from the linked releases for the subject.
This failure was because the datablocks query was still in progress when we began the query for the latest linked release. Each open connection can only support one query at a time.
The solution here is to resolve the datablocks DbSet into a List before we start transforming them, which is where the inner queries are made by the security check.
This solution wouldn't be ideal if there are a lot of datablocks since they are now loaded into memory up front.

EES-802 Fix 'open datareader' error migrating datablocks

---

src/explore-education-statistics-admin/src/pages/release/prerelease/PreReleasePage.tsx

This PR fixes `permissionService.getPreReleaseWindowStatus` not being called before other API calls are made, causing the user to potentially see Forbidden pages.
We also clean up the page so that the user can always see the page layout. Even if there is no content, this is better than a white screen where they can't go anywhere from.

EES-818 Ensure prerelease window is checked before rendering PreReleasePage

---

src/explore-education-statistics-admin/src/pages/release/edit-release/manage-datablocks/components/ChartAxisConfiguration.tsx
src/explore-education-statistics-admin/src/pages/release/edit-release/manage-datablocks/components/ChartBuilder.tsx
src/explore-education-statistics-admin/src/pages/release/edit-release/manage-datablocks/components/ChartBuilderTabSection.tsx
src/explore-education-statistics-admin/src/pages/release/edit-release/manage-datablocks/components/ChartConfiguration.tsx
src/explore-education-statistics-admin/src/pages/release/edit-release/manage-datablocks/components/ChartDataSelector.tsx
src/explore-education-statistics-admin/src/pages/release/edit-release/manage-datablocks/reducers/__tests__/chartBuilderReducer.test.ts
src/explore-education-statistics-admin/src/pages/release/edit-release/manage-datablocks/reducers/chartBuilderReducer.ts
src/explore-education-statistics-common/src/components/ModalConfirm.tsx

This PR adds the 'Delete chart' button to bottom of each chart builder form. On clicking it, a confirmation modal will appear to make sure the user didn't accidentally click it.

EES-647 Add 'Delete chart' button to chart builder

---

src/GovUk.Education.ExploreEducationStatistics.Admin/Migrations/ContentMigrations/20200430093743_EES760UpdatePublicationsTopicsAndThemes.cs
src/GovUk.Education.ExploreEducationStatistics.Admin/Migrations/ContentMigrations/20200507100229_EES825RevertSlug.Designer.cs
src/GovUk.Education.ExploreEducationStatistics.Admin/Migrations/ContentMigrations/20200507100229_EES825RevertSlug.cs
src/GovUk.Education.ExploreEducationStatistics.Content.Model/Database/ContentDbContext.cs

In https://github.com/dfe-analytical-services/explore-education-statistics/pull/1621 it was spotted that the Publication slug doesn’t match the title and this was corrected in advance of the first Release of this publication going live on the platform.
In https://github.com/dfe-analytical-services/explore-education-statistics/pull/1621 there was a mistake and it was going to be updated to `graduate-outcomes-leo-postgraduate-outcomes`.
Before this change was deployed to production, the first release for it was published.
This means we are now too late to correct `-markets` for `-market-statistics` without a redirect, and the slug should remain for now as `graduate-labour-markets`.
This change was required to prevent the slug being altered to `graduate-outcomes-leo-postgraduate-outcomes` …

EES-825 Slug reverted back to graduate-labour-markets

---

src/explore-education-statistics-admin/src/App.tsx
src/explore-education-statistics-admin/src/components/PageErrorBoundary.tsx
src/explore-education-statistics-admin/src/components/__tests__/PageErrorBoundary.test.tsx
src/explore-education-statistics-admin/src/hooks/useFormSubmit.ts
src/explore-education-statistics-admin/src/pages/users/InvitedUsersPage.tsx
src/explore-education-statistics-admin/src/services/release/edit-release/data/editReleaseDataService.ts
src/explore-education-statistics-common/src/contexts/ErrorControlContext.tsx
src/explore-education-statistics-common/src/modules/find-statistics/hooks/useDataBlockQuery.ts
src/explore-education-statistics-common/src/modules/find-statistics/hooks/useTableQuery.ts
src/explore-education-statistics-common/src/modules/table-tool/components/TableToolWizard.tsx
src/explore-education-statistics-common/src/polyfill.js
src/explore-education-statistics-common/src/services/api/Client.ts

Currently `withoutErrorHandling` is unreliable as it can create race conditions where multiple invocations can reset the default error handling behaviour once the associated task has completed. It's consequently possible for the user to still see the error page(s) when using `withoutErrorHandling` in multiple places.
The previous solution was to use `catch` everywhere, and this can robustly solve the problem, but is quite verbose.
Our new solution is to attach the default error handling to the `unhandledrejection` window event instead of the `Client` error handler. This means that most API requests no longer have a default `catch` that cannot be easily overridden.
A very nice benefit is that we can now idiomatically add custom error handling in our code as we no longer need to wrap the …

EES-801 Replace `withoutErrorHandling` in favour of `unhandledrejection` listener

---

src/explore-education-statistics-admin/src/pages/release/edit-release/manage-datablocks/components/ChartBuilder.tsx
src/explore-education-statistics-admin/src/pages/release/edit-release/manage-datablocks/components/ChartBuilderTabSection.tsx
src/explore-education-statistics-admin/src/pages/release/edit-release/manage-datablocks/components/DataBlockSourceWizard.tsx
src/explore-education-statistics-admin/src/pages/release/edit-release/manage-datablocks/components/ReleaseManageDataBlocksPageTabs.tsx
src/explore-education-statistics-admin/src/pages/release/edit-release/manage-datablocks/components/TableTabSection.tsx
src/explore-education-statistics-common/src/modules/charts/util/__tests__/filterOrphanedDataSets.test.ts
src/explore-education-statistics-common/src/modules/charts/util/filterOrphanedDataSets.ts

This PR re-works the current state implementation the 'Manage data blocks' UI so that  `ReleaseManageDataBlocksPageTabs` is the source of truth for all of its child components.
Previously, state could still be localised in some of the child components leading to continued stale state issues. The complexity of synchronizing this UI had been unfortunately underestimated.
We've now lifted most of this state up to `ReleaseManageDataBlockPageTabs` so that it is much harder to desynchronize. We maintain this state in a `tableState` variable that is updated when any of the tabs save/update.
- On initial render, a table query will be executed in `ReleaseManageDataBlockPageTabs` if updating an existing data block. This result is stored in `tableState`. This table query will not be executed again. …

EES-806 Synchronize table state across all data block tabs

---

src/explore-education-statistics-common/src/modules/table-tool/components/FiltersForm.tsx
src/explore-education-statistics-common/src/modules/table-tool/components/LocationFiltersForm.tsx
src/explore-education-statistics-common/src/modules/table-tool/components/PublicationSubjectForm.tsx
src/explore-education-statistics-common/src/modules/table-tool/components/TimePeriodForm.tsx

This PR fixes validation errors not being removed when table tool's forms have been changed. This was due to `validateOnChange` being set to false. We've removed this in favour of using the default `validateOnChange` (which is true).

EES-793 Fix validation errors not being removed when table tool forms changed

---

src/explore-education-statistics-admin/src/pages/release/edit-release/manage-datablocks/components/DataBlockDetailsForm.tsx
src/explore-education-statistics-admin/src/pages/release/edit-release/manage-datablocks/components/DataBlockSourceWizard.tsx
src/explore-education-statistics-admin/src/pages/release/edit-release/manage-datablocks/components/ReleaseManageDataBlocksPageTabs.tsx
src/explore-education-statistics-common/src/modules/table-tool/components/TableToolWizard.tsx
src/explore-education-statistics-common/src/modules/table-tool/components/Wizard.tsx
src/explore-education-statistics-common/src/modules/table-tool/components/WizardStep.tsx
src/explore-education-statistics-common/src/modules/table-tool/components/__tests__/PublicationForm.test.tsx
src/explore-education-statistics-common/src/modules/table-tool/components/__tests__/Wizard.test.tsx

> :warning: Depends on `ees-806`
This PR fixes the `DataBlockSourceWizard` showing incorrect options when the user attempts to go to a previous step for an existing data block to update it. This was due to the subject meta being potentially incorrect as we start at the final step, instead of moving from step 1 through 5.
We consequently need to add an `onBack` callback to the relevant `TableToolWizard` steps so that we can re-filter the subject meta options for that step. This way we can ensure that the options are actually correct.
To err on the safe side, we also initialise the `DataBlockSourceWizard` will the full subject meta so that options are filtered out. This looks marginally better than flicker as options load in.

EES-808 Fix existing data block source options not being correct on previous steps

---

src/explore-education-statistics-common/src/modules/table-tool/components/DownloadCsvButton.tsx
src/explore-education-statistics-common/src/modules/table-tool/components/DownloadExcelButton.tsx
src/explore-education-statistics-common/src/modules/table-tool/components/TableToolWizard.tsx
src/explore-education-statistics-common/src/modules/table-tool/components/__tests__/DownloadCsvButton.test.tsx
src/explore-education-statistics-frontend/src/modules/permalink/PermalinkPage.tsx
src/explore-education-statistics-frontend/src/modules/table-tool/components/TableTool.tsx

This PR also changes the permalink's CSV/Excel filenames to use the permalink ID. Previously the filenames would have `undefined` in them, which looked quite ugly.

EES-849 Add correct table source to PermalinkPage

---

src/GovUk.Education.ExploreEducationStatistics.Admin/Services/PublicationRepository.cs
src/GovUk.Education.ExploreEducationStatistics.Admin/Services/ThemeRepository.cs

Prevent themes and publications endpoints returning releases that a user **only** has pre-release access for.
Currently topics and publications/releases are returned on the dashboard if a user only has pre-release access, this then results in failing api calls to get the status of that releases as that is forbidden (correctly).
This modified the themes/topics response to include those that a user has access to, and excludes those that they **only** have pre-release access for (as a user may have both access and pre-release at the same time).
To be safe ive also ensured that the publications endpoint does not return publications/releases with the same conditions.

EES-874: Prevent themes and publications endpoints returning pre-release releases

---

src/explore-education-statistics-admin/src/components/Link.tsx
src/explore-education-statistics-admin/src/components/__tests__/Link.test.tsx
src/explore-education-statistics-admin/src/components/editable/EditableLink.tsx
src/explore-education-statistics-admin/src/modules/find-statistics/PublicationReleaseContent.tsx
src/explore-education-statistics-admin/src/modules/find-statistics/components/AdminPublicationReleaseHelpAndSupportSection.tsx
src/explore-education-statistics-admin/src/modules/find-statistics/components/RelatedInformationSection.tsx

This PR adds proper URLs to `PublicationReleaseContent`'s previous release links. Previously they were empty and wouldn't go anywhere.
- `Link` now handles absolute URLs via the `to` prop. This makes it easier to link to external URLs without using the confusing `href` prop. We've changed the type definition here to remove `href` as a prop completely.

EES-330 Link publication's previous releases to public frontend

---

src/GovUk.Education.ExploreEducationStatistics.Admin/Services/PreReleaseContactsService.cs

Should use release.Title as this has the full time period description.
This will need testing.

EES-911: Pre release email should use release title not release name

---

src/explore-education-statistics-admin/src/pages/release/edit-release/manage-datablocks/components/ChartAxisConfiguration.tsx
src/explore-education-statistics-admin/src/pages/release/edit-release/manage-datablocks/components/ChartBuilder.tsx
src/explore-education-statistics-admin/src/pages/release/edit-release/manage-datablocks/components/ChartBuilderSaveButton.tsx
src/explore-education-statistics-admin/src/pages/release/edit-release/manage-datablocks/components/ChartConfiguration.tsx
src/explore-education-statistics-admin/src/pages/release/edit-release/manage-datablocks/components/ChartDataSelector.tsx
src/explore-education-statistics-admin/src/pages/release/edit-release/manage-datablocks/reducers/__tests__/chartBuilderReducer.test.ts
src/explore-education-statistics-admin/src/pages/release/edit-release/manage-datablocks/reducers/chartBuilderReducer.ts
src/explore-education-statistics-common/src/components/ErrorSummary.tsx
src/explore-education-statistics-common/src/components/Tabs.tsx
src/explore-education-statistics-common/src/components/__tests__/ErrorSummary.test.tsx
src/explore-education-statistics-common/src/components/__tests__/__snapshots__/Tabs.test.tsx.snap
src/explore-education-statistics-common/src/types/govuk-frontend.d.ts

:warning: Depends on `ees-763`
This PR adds the following tweaks to chart builder's error messages:
- Fixed requiring a second submission in certain instances to see the submit error message properly (as described by EES-826).
- Add additional error messages for individual chart builder tabs that have failing validation e.g. 'Chart configuration tab is not valid'. These error messages also allow the user to directly open the tab by clicking on them.
- Fixed error summary sometimes stealing focus when it renders. This was due to the GOVUK Error Summary component (that is used internally) calling `focus` when it initialises. We've fixed this by doing the initialisation of this component manually i.e.
```typescript
const { handleClick } = new GovUkErrorSummary(ref.current); …
```

EES-826 Add tweaks to chart builder submit error messages

---

src/GovUk.Education.ExploreEducationStatistics.Admin.Tests/Controllers/Api/ReleaseControllerTests.cs
src/GovUk.Education.ExploreEducationStatistics.Admin.Tests/Services/Methodologies/MethodologyServiceTests.cs
src/GovUk.Education.ExploreEducationStatistics.Admin.Tests/Services/ValidationTestUtil.cs
src/GovUk.Education.ExploreEducationStatistics.Admin/Services/Methodologies/MethodologyService.cs

When updating the methodology the check for a unique slug needs to exclude the existing methodology.
Prior to this any update not changing the title received an error
`{
"errors": {
"": [
"SLUG_NOT_UNIQUE"
]
},
"title": "One or more validation errors occurred.",
"status": 400
}`
This problem wasn't previously raised by the update unit test in `MethdodologyServiceTests` because there was no slug saved to the database prior to the update.

EES-890 Fix methodology unique slug validation failing when updating methodology

---

src/GovUk.Education.ExploreEducationStatistics.Admin.Tests/Security/AuthorizationHandlers/ViewSpecificReleaseAuthorizationHandlersTests.cs
src/GovUk.Education.ExploreEducationStatistics.Admin/Controllers/Api/Security/PermissionsController.cs
src/GovUk.Education.ExploreEducationStatistics.Admin/Models/PreReleaseWindow.cs
src/GovUk.Education.ExploreEducationStatistics.Admin/Models/PreReleaseWindowStatus.cs
src/GovUk.Education.ExploreEducationStatistics.Admin/Security/AuthorizationHandlers/ViewSpecificReleaseAuthorizationHandlers.cs
src/GovUk.Education.ExploreEducationStatistics.Admin/Services/Interfaces/IPreReleaseService.cs
src/GovUk.Education.ExploreEducationStatistics.Admin/Services/PreReleaseContactsService.cs
src/GovUk.Education.ExploreEducationStatistics.Admin/Services/PreReleaseService.cs
src/GovUk.Education.ExploreEducationStatistics.Common/Extensions/DateTimeExtensions.cs
src/explore-education-statistics-admin/src/services/permissions/permissionService.ts

- Retrieves the Prerelease access window to use the start date.
- Converts the Prerelease start date and the Release PublishScheduled date to GMT/BST timezone from UTC. We assume GMT/BST to be the timezone of our users receiving the email.
- Formats date and times for the email.
- Removes the hard coded publish time of 09:30 from the template body in Gov.uk Notify. This will be set by EES-828.
- Makes PreReleaseWindowStatus field names less verbose.
This impacts the front end usage of `release/{releaseId}/prerelease/status`
`PreReleaseAccess` -> `Access`
`PreReleaseWindowStartTime` -> `Start`
`PreReleaseWindowEndTime` -> `End`
- Depends on a template change to Gov.uk Notify to add and remove altered template keys. This has been set in the Explore Education Statistics (Test) account.

EES-910 Date and time string parameters for Prerelease email body

---

src/explore-education-statistics-admin/src/components/PageHeader.module.scss

Making pre-prod a different colour to production (turquoise rather than red, as production is red).

Changing the colour of the pre-prod banner

---

src/explore-education-statistics-frontend/src/pages/_app.tsx

This change reverts the static optimisations implemented by EES-892 as it appears that they cause strange behaviour when it comes to the injection of environment variables. It appears that loading the app from a statically generated page (like the home page), will cause the environment variables not to be loaded in later when client-side rendering takes place.
This could be potentially remedied by re-loading the environment variables upon client-side mounting, but for the time being, it seems to just be safer to force server-side rendering on all pages.

EES-932 Force server-side renders (reverting Next static optimisations)

---

src/GovUk.Education.ExploreEducationStatistics.Publisher.Tests/Services/CronScheduleUtilTests.cs
src/GovUk.Education.ExploreEducationStatistics.Publisher.Tests/Services/MethodologyServiceTests.cs
src/GovUk.Education.ExploreEducationStatistics.Publisher.Tests/Services/ReleaseServiceTests.cs
src/GovUk.Education.ExploreEducationStatistics.Publisher/Functions/GenerateReleaseContentFunction.cs
src/GovUk.Education.ExploreEducationStatistics.Publisher/Functions/PublishReleaseContentImmediateFunction.cs
src/GovUk.Education.ExploreEducationStatistics.Publisher/Models/PublishContext.cs
src/GovUk.Education.ExploreEducationStatistics.Publisher/Services/ContentService.cs
src/GovUk.Education.ExploreEducationStatistics.Publisher/Services/Interfaces/IContentService.cs
src/GovUk.Education.ExploreEducationStatistics.Publisher/Services/Interfaces/IMethodologyService.cs
src/GovUk.Education.ExploreEducationStatistics.Publisher/Services/Interfaces/IReleaseService.cs
src/GovUk.Education.ExploreEducationStatistics.Publisher/Services/MethodologyService.cs
src/GovUk.Education.ExploreEducationStatistics.Publisher/Services/PublishingService.cs
src/GovUk.Education.ExploreEducationStatistics.Publisher/Services/ReleaseService.cs
tests/newman/tests/admin-api-dev.json

There were two bugs applicable to Releases as well as Methodology.
- The Published date shown to the user on public front was the date it was previously published when a Release is republished.
- When using Release on Demand the date was not the current time but the next scheduled time determined by the Publishers cron schedule setting.
In https://github.com/dfe-analytical-services/explore-education-statistics/pull/1696 we made a change to set the published date of the methodology when publishing it so that it shows up in the Admin with a date in the ‘Published on’ field.
The same PR also set the published date prior to this in the view model when generating the json serialised cache based on the date we expect it to eventually be published at, i.e. worked out from the next occurrence of …

EES-786 Corrections to published date of Releases and Methogologies.

---

src/explore-education-statistics-admin/src/components/editable/EditableBlockRenderer.tsx
src/explore-education-statistics-admin/src/modules/find-statistics/PublicationReleaseContent.tsx
src/explore-education-statistics-common/src/modules/find-statistics/components/ContentBlockRenderer.tsx

Other changes:
- Fixes 'undefined' showing in empty read-only content blocks.
- Changes rendered block ids to use the format `block-{id}` instead of `editableBlockRenderer-{id}`

EES-881 Fix 'Add summary' button showing for prerelease content

---

infrastructure/templates/datafactory/components/template.json

In the CopyIndicators DataFactory pipeline step, copy the new column DecimalPlaces. Without this the data is formatted in the admin to the number of decimal places specified in the metadata, but not in the Public.
This won't fix any releases using the new decimal places feature that have already been published.

EES-738 Copy DecimalPlaces

---

src/explore-education-statistics-admin/src/pages/release/edit-release/manage-datablocks/components/ChartAxisConfiguration.tsx
src/explore-education-statistics-common/src/components/TabsSection.module.scss
src/explore-education-statistics-common/src/components/TabsSection.tsx
src/explore-education-statistics-common/src/components/__tests__/Tabs.test.tsx
src/explore-education-statistics-common/src/components/__tests__/__snapshots__/Tabs.test.tsx.snap
src/explore-education-statistics-common/src/modules/charts/components/AxisLabel.tsx
src/explore-education-statistics-common/src/modules/charts/components/ChartContainer.tsx

This PR:
- Fixes Y axis label from pushing the chart too far to the right when a label width has been set. We have used a combination of `max-width` and `width` styles to prevent this. Consequently, the label can no longer be larger than 40% of the container width. Any additional width will not be considered past this.
- Fixes initial chart sizing issue that can occur due to trying to render before the container has the correct rendered width for it to use. We `useMounted` to check that the component has mounted before rendering the chart.
- Fixes initial chart sizing issue due to `TabSections` using `govuk-visually-hidden`. This was removing padding from the `TabSection` causing the wrong width to be calculated by Recharts. We've removed this in favour of the `hidden` attribute and …

EES-620 Stop axis labels from causing chart to break out of its container

---

infrastructure/templates/template.json

The public storage connection string is currently duplicated in both variables and connection strings.
As this should be retrieved from Vault the variable should be used and the connection string removed.]

EES-972: Remove DataAPI Storage conection string duplication

---

azure-pipelines.dfe.yml

This is required to ensure that the `robot-tests` artifact has the correct dependencies to run the tests after deployment to each environment.

ci: copy Pipfiles into tests/robot-tests for robot-tests artifact

---

azure-pipelines.dfe.yml
azure-pipelines.pr.yml
tests/robot-tests/README.md
tests/robot-tests/run_tests.py
tests/robot-tests/scripts/get_auth_tokens.py
tests/robot-tests/scripts/pipeline-run-rf-tests.sh
useful-scripts/auth-tokens/get_auth_tokens.sh
useful-scripts/auth-tokens/requirements.txt

Currently Robot and Newman tests are separated out into separate pipeline artifacts which is causing us issues as they both rely on shared dependencies such as `get_auth_tokens.py`. We've moved this into the `tests/scripts` directory and now package the entires `tests` directory as an artifact.

ci: move all test files into the same test artifact

---

src/explore-education-statistics-admin/src/pages/bau/BauDashboardPage.tsx
src/explore-education-statistics-admin/src/pages/contacts/ContactsPage.tsx
src/explore-education-statistics-admin/src/routes/dashboard/routes.ts

Adds a new administration section for contacts.
Adds a new contacts page that lists all contacts currently in the service.
This is a `quick win` piece of work to allow some visibility to what contact data we have in the service to BAU users using an existing API.
Further work will follow to tidy up and expand the page with edit, add, delete functionality etc.

Add a basic BAU page for listing contacts

---

src/GovUk.Education.ExploreEducationStatistics.Data.Model/Services/SubjectService.cs

Could not delete a subject once imported & footnotes created which link to filter. Had to delete the observation filter items rows first.

EES-986 Delete observation filter items when delete subject.

---

src/GovUk.Education.ExploreEducationStatistics.Admin/Services/ReleaseRepository.cs
src/GovUk.Education.ExploreEducationStatistics.Admin/appsettings.Development.json
src/explore-education-statistics-admin/src/pages/admin-dashboard/AdminDashboardPage.tsx

- Don't include Releases that a user only has PreRelease role for when getting scheduled Releases. Fixes a 403 error getting the Release Status on them. User must use e-mail link to access pre releases.
- Don't attempt to get pre release contacts without Release update permission by hiding the `PreReleaseManagement `component. Fixes 403 error when user only has Viewer role on Releases.
- Remove unused Prerelease code from `AdminDashboardPage.tsx`.
- Add missing `AdminUri `param fixing e-mail link when inviting new users to EES.

EES-887 PreRelease fixes

---

src/explore-education-statistics-admin/src/pages/errors/ForbiddenPage.tsx
src/explore-education-statistics-admin/src/pages/sign-in/SignedOutPage.tsx

Sign in buttons should consistently have the following style

EES-381: Admin sign in link style

---

src/GovUk.Education.ExploreEducationStatistics.Data.Services/AbstractSubjectMetaService.cs
src/GovUk.Education.ExploreEducationStatistics.Data.Services/LabelRelationalComparer.cs
src/GovUk.Education.ExploreEducationStatistics.Data.Services/SubjectMetaService.cs

This change adds sorting to filter group and filter items by their labels in Subject metadata requests.
It compares them as strings but caters for integer and DateTime values represented as strings.
* If both values can be converted to integer then they are compared as integer values.
* If both values can be converted to DateTime then they are compared as DateTime values.
* If conversion is not possible then they are compared as strings. 
This should add sorting but also mean that integer sequences are not sorted as 1,10,11,12,.. and date sequences are properly ordered too.

EES-1019 Add sorting to filter groups and filter items in Subject metadata requests

---

src/GovUk.Education.ExploreEducationStatistics.Data.Model/Services/SubjectService.cs

The fix for EES-986 https://github.com/dfe-analytical-services/explore-education-statistics/pull/1750 is retrieving all Observation Filter items in order to delete them which is a long running query. There is an example in Prod failing in method RemoveReleaseSubjectLinkAsync taking 29.8 minutes before failing.
This PR reverts the change in https://github.com/dfe-analytical-services/explore-education-statistics/pull/1750

Revert "EES-986 Delete observation filter items when delete subject."

---

src/explore-education-statistics-common/src/components/form/FormCheckboxSearchSubGroups.tsx
src/explore-education-statistics-common/src/components/form/FormFieldCheckboxSearchSubGroups.tsx
src/explore-education-statistics-common/src/components/form/__tests__/FormCheckboxSearchSubGroups.test.tsx
src/explore-education-statistics-common/src/components/form/__tests__/__snapshots__/FormCheckboxSearchSubGroups.test.tsx.snap
src/explore-education-statistics-common/src/modules/table-tool/components/FormFieldCheckboxGroupsMenu.tsx
src/explore-education-statistics-common/src/modules/table-tool/components/__tests__/FormFieldCheckboxGroupsMenu.test.tsx
src/explore-education-statistics-common/src/modules/table-tool/components/__tests__/__snapshots__/FormFieldCheckboxGroupsMenu.test.tsx.snap

This PR fixes the 'Select all options' button not showing in instances where there is only a single checkbox subgroup.
We also take this opportunity to do some additional cleanup of the subgroup rendering behaviour to stuff more of it into  `FormCheckboxSearchSubGroups`. Currently this logic is fragmented across multiple consumer components rather than just being handled internally. We've now stripped this all back and removed a lot of the duplication.

EES-1020 Show 'Select all options' button consistently when single subgroup 

---

src/GovUk.Education.ExploreEducationStatistics.Admin.Tests/Controllers/Api/Statistics/FootnoteControllerTests.cs
src/GovUk.Education.ExploreEducationStatistics.Admin/Controllers/Api/Statistics/FootnoteController.cs
src/GovUk.Education.ExploreEducationStatistics.Data.Services/AbstractSubjectMetaService.cs
src/GovUk.Education.ExploreEducationStatistics.Data.Services/Mappings/DataServiceMappingProfiles.cs
src/GovUk.Education.ExploreEducationStatistics.Data.Services/ResultSubjectMetaService.cs
src/GovUk.Education.ExploreEducationStatistics.Data.Services/SubjectMetaService.cs
src/GovUk.Education.ExploreEducationStatistics.Data.Services/ViewModels/Meta/IndicatorMetaViewModel.cs
src/GovUk.Education.ExploreEducationStatistics.Data.Services/ViewModels/Meta/ObservationalUnitMetaViewModel.cs
src/explore-education-statistics-common/src/modules/table-tool/components/FiltersForm.tsx
src/explore-education-statistics-common/src/modules/table-tool/components/LocationFiltersForm.tsx

Follow on from https://github.com/dfe-analytical-services/explore-education-statistics/pull/1761 which added sorting to filter groups and filter items.
This PR adds sorting to Indicators and Observational Units at the API level.

EES-1035 Add sorting of indicators and observational units by label.

---

src/GovUk.Education.ExploreEducationStatistics.Data.Processor/Services/ReleaseProcessorService.cs

This PR makes sure when files are imported and the Subject Id is added to the ReleaseFileReference that the correct ReleaseFileReference is found by case sensitive filename check.
Previously the check was case insensitive due to being executed Linq-to-SQL where the SQLServer database is operating case insensitive, and could lead to the wrong ReleaseFileReference being found.
An additional file being imported with the same name (except for case) as an existing file would overwrite the Subjectd of the first ReleaseFileReference matching that name case insensitive.

EES-990 Find the correct ReleaseFileReference when importing files

---

src/GovUk.Education.ExploreEducationStatistics.Admin/Services/ContactService.cs

Contacts are currently relying on the ui to order them, this does the ordering at the API layer

Order contacts alphabetically

---

src/explore-education-statistics-admin/src/pages/methodology/edit-methodology/status/MethodologyStatusPage.tsx
src/explore-education-statistics-admin/src/pages/release/edit-release/manage-datablocks/ReleaseManageDataBlocksPage.tsx
src/explore-education-statistics-admin/src/pages/release/edit-release/manage-datablocks/components/ReleaseManageDataBlocksPageTabs.tsx
src/explore-education-statistics-common/src/components/Gate.tsx
src/explore-education-statistics-common/src/hooks/__tests__/useAsyncCallback.test.ts
src/explore-education-statistics-common/src/hooks/__tests__/useAsyncHandledRetry.test.tsx
src/explore-education-statistics-common/src/hooks/__tests__/useAsyncRetry.test.ts
src/explore-education-statistics-common/src/hooks/__tests__/usePrevious.test.ts
src/explore-education-statistics-common/src/hooks/useAsyncCallback.ts
src/explore-education-statistics-common/src/hooks/useAsyncHandledRetry.ts
src/explore-education-statistics-common/src/hooks/useAsyncRetry.ts
src/explore-education-statistics-common/src/hooks/usePrevious.ts
src/explore-education-statistics-common/src/modules/find-statistics/components/DataBlockRenderer.tsx
src/explore-education-statistics-common/src/modules/find-statistics/components/__tests__/DataBlockRenderer.test.tsx
src/explore-education-statistics-common/src/modules/table-tool/components/TableToolWizard.tsx

This PR fixes data blocks throwing errors and causing release pages to break when navigating to other releases.
This issue stems from stale `useAsyncRetry` state even though its dependencies may have changed. As the async task's effect is ran on the next render, the current render may still be referencing the incorrect state in combination with its new dependencies.  In the case of `DataBlockRenderer`, we will try to call `mapTableHeadersConfig` with the stale table data leading to errors being thrown.
To avoid this, we now do a equality check on the prev/current `useAsyncRetry` dependencies. If the dependencies are different, we reset to the initial state.
For good measure, we also wrap `DataBlockRenderer` with an `ErrorBoundary` that just shows 'Could not load content' if any error is …

EES-1012 Fix data blocks throwing errors when page props change

---

src/GovUk.Education.ExploreEducationStatistics.Admin/Controllers/Api/ConfigurationController.cs
src/explore-education-statistics-admin/src/App.tsx
src/explore-education-statistics-admin/src/index.tsx
src/explore-education-statistics-common/src/contexts/ApplicationInsightsContext.tsx
src/explore-education-statistics-common/src/services/applicationInsightsService.ts
src/explore-education-statistics-common/src/services/logger.ts
src/explore-education-statistics-frontend/next.config.js
src/explore-education-statistics-frontend/server.js
src/explore-education-statistics-frontend/src/modules/ErrorPage.tsx
src/explore-education-statistics-frontend/src/pages/_app.tsx

This PR adds Application Insights tracking/logging to the public frontend and admin. 
We now try to log errors in as many places as possible such as:
- Error boundary components
- Next's `_error` page
- `logger.error`
- Public frontend server startup errors
Additionally, we have also enabled page view tracking by hooking into each app's respective router and detecting changes to the URL.
As part of this, we have also introduced a new `ApplicationInsightsContext` for better integration with React. This can be accessed in components using the `useApplicationInsights` hook.

EES-875 Add Application Insights logging across frontend code

---

src/explore-education-statistics-admin/package-lock.json
src/explore-education-statistics-admin/package.json
src/explore-education-statistics-admin/src/components/BrowserWarning.tsx
src/explore-education-statistics-admin/src/components/PageTitle.tsx
src/explore-education-statistics-admin/src/components/editable/EditableContentBlock.tsx
src/explore-education-statistics-admin/src/components/editable/EditableSectionBlocks.tsx
src/explore-education-statistics-admin/src/components/form/FormEditor.tsx
src/explore-education-statistics-admin/src/modules/find-statistics/PublicationReleaseContent.tsx
src/explore-education-statistics-admin/src/pages/methodology/edit-methodology/MethodologyPage.tsx
src/explore-education-statistics-admin/src/pages/methodology/edit-methodology/content/MethodologyContentPage.tsx
src/explore-education-statistics-admin/src/pages/release/ManageReleasePageContainer.tsx
src/explore-education-statistics-admin/src/pages/release/edit-release/content/ReleaseContentPage.tsx
src/explore-education-statistics-common/package-lock.json
src/explore-education-statistics-common/package.json
src/explore-education-statistics-common/src/components/form/FormTextArea.tsx
src/explore-education-statistics-common/src/styles/_form.scss
src/explore-education-statistics-common/src/utils/isBrowser.ts
src/explore-education-statistics-frontend/package-lock.json
src/explore-education-statistics-frontend/package.json

This PR adds the following warning message to the top of the release and methodology content pages:
We also prevent the user from editing any `FormEditor` components if it is detected they are using IE. This prevents them from having the false perception that they can actually edit the content and gives them a hard nudge to change browser.
- Adds proper page titles to release/methodology pages. This was mainly motivated by the incorrect heading tag hierarchy used for the release content page. This relates to the wider issue EES-68 for adding proper page titles across the admin.
- Upgraded Immer to v7. This was previously causing out of stack space crashes on IE11.

EES-901 Add IE browser warnings to admin content pages

---

src/GovUk.Education.ExploreEducationStatistics.Admin.Tests/Services/ReleaseServiceAmendmentTests.cs
src/GovUk.Education.ExploreEducationStatistics.Admin.Tests/Services/ReleaseServicePermissionTests.cs
src/GovUk.Education.ExploreEducationStatistics.Admin.Tests/Services/ReleaseServiceTests.cs
src/GovUk.Education.ExploreEducationStatistics.Admin/Services/DataBlockService.cs
src/GovUk.Education.ExploreEducationStatistics.Admin/Services/FileStorageService.cs
src/GovUk.Education.ExploreEducationStatistics.Admin/Services/ImportService.cs
src/GovUk.Education.ExploreEducationStatistics.Admin/Services/PublicationService.cs
src/GovUk.Education.ExploreEducationStatistics.Admin/Services/ReleaseService.cs
src/GovUk.Education.ExploreEducationStatistics.Admin/Services/TopicService.cs
src/GovUk.Education.ExploreEducationStatistics.Admin/Startup.cs
src/GovUk.Education.ExploreEducationStatistics.Common/Services/Interfaces/IGuidGenerator.cs
src/GovUk.Education.ExploreEducationStatistics.Common/Services/SequentialGuidGenerator.cs
src/GovUk.Education.ExploreEducationStatistics.Data.Importer/Services/ImporterLocationService.cs
src/GovUk.Education.ExploreEducationStatistics.Data.Importer/Services/ImporterMetaService.cs
src/GovUk.Education.ExploreEducationStatistics.Data.Importer/Services/ImporterService.cs
src/GovUk.Education.ExploreEducationStatistics.Data.Processor/Startup.cs

By convention, primary keys of type Guid are set up to have values generated for inserted entities using `Microsoft.EntityFrameworkCore.ValueGeneration.SequentialGuidValueGenerator` which generates sequential values using the same algorithm as `NEWSEQUENTIALID()` in Microsoft SQL Server.
There are some cases in our application where `Id = Guid.NewGuid` has been set prior to adding the entity e.g. in `CreatePublicationAsync`. 
These are generating non-sequential Guid's which are impacting the clustered PK indexes, causing fragmentation. Each row of data is inserted into the middle of the clustered index (out of sequential order) causing SQL Server to make room for the data by rearranging the cluster.
Where the Id does not need to be known prior to adding, they have been removed to force …

EES-1077 Use sequentially generated Guid's

---

infrastructure/templates/template.json
src/GovUk.Education.ExploreEducationStatistics.Admin/GovUk.Education.ExploreEducationStatistics.Admin.csproj
src/GovUk.Education.ExploreEducationStatistics.Admin/Program.cs
src/GovUk.Education.ExploreEducationStatistics.Admin/Startup.cs
src/GovUk.Education.ExploreEducationStatistics.Content.Api/GovUk.Education.ExploreEducationStatistics.Content.Api.csproj
src/GovUk.Education.ExploreEducationStatistics.Content.Api/Program.cs
src/GovUk.Education.ExploreEducationStatistics.Content.Api/Startup.cs
src/GovUk.Education.ExploreEducationStatistics.Data.Api/Program.cs
src/GovUk.Education.ExploreEducationStatistics.Data.Api/Startup.cs

Follows the documentation here to make sure we've got the App Insights SDK installed correctly and attempts to capture logs from early in the application startup pipeline from Startup.cs and Program.cs themselves.
**Installation:**
https://docs.microsoft.com/en-us/azure/azure-monitor/app/asp-net-core
**A note on logging Startup.cs and Program.cs:**
https://docs.microsoft.com/en-us/azure/azure-monitor/app/ilogger#aspnet-core-applications
**Provision for App Service logs should we need it:**
https://docs.microsoft.com/en-us/aspnet/core/fundamentals/logging/?view=aspnetcore-3.1#azure-app-service

EES-994 EES-1022 Configuring App Insights SDK

---

src/GovUk.Education.ExploreEducationStatistics.Admin/appsettings.json
src/GovUk.Education.ExploreEducationStatistics.Content.Api/appsettings.json
src/GovUk.Education.ExploreEducationStatistics.Data.Api/appsettings.json
src/GovUk.Education.ExploreEducationStatistics.Data.Processor/Startup.cs

Tweaks found as part of work testing that App Insights logging is correctly installed (https://dfedigital.atlassian.net/browse/EES-994)
* We shouldn't be calling AddApplicationInsightsTelemetry() in Function projects as documented here
https://docs.microsoft.com/en-us/azure/azure-functions/functions-dotnet-dependency-injection
* Removing ApplicationInsights sections from log level configuration. While we are not differing the level for ApplicationInsights these sections are just duplicating the default config unnecessarily.
* Setting "Microsoft" category from Information to Warning to reduce logging. In the Admin application in the last 24 hours we had 244K Information level traces. At least of 230K of these traces are "Microsoft" and don't add much value.

EES-994 App Insights configuration

---

src/GovUk.Education.ExploreEducationStatistics.Admin/Startup.cs

Override the default allowed username characters in the `Microsoft.AspNetCore.Identity.UserValidator` to include an apostrophe.
In `ExternalLogin.cshtml` after checking the invite exists we call await `_userManager.CreateAsync(user)` where the `user.UserName` is the email which can contain an apostrophe.
Without this override the UserManager username validation fails when creating a new user and the invited user cannot login.
https://docs.microsoft.com/en-us/aspnet/core/security/authentication/identity-configuration?view=aspnetcore-3.1

EES-1100 Set allowed username characters

---

src/GovUk.Education.ExploreEducationStatistics.Content.Model/ExternalMethodology.cs
src/explore-education-statistics-admin/src/pages/theme/topic/CreatePublicationPage.tsx
src/explore-education-statistics-admin/src/pages/theme/topic/publication/AssignMethodologyForm.tsx

This PR prevents analysts from using entering external methodology URLs for the actual admin service.

EES-415 Add validation to prevent external methodology URL containing current host

---

src/GovUk.Education.ExploreEducationStatistics.Admin.Tests/Security/AuthorizationHandlers/ApproveSpecificReleaseAuthorizationHandlersTests.cs
src/GovUk.Education.ExploreEducationStatistics.Admin.Tests/Security/AuthorizationHandlers/MarkSpecificReleaseAsDraftAuthorizationHandlersTests.cs
src/GovUk.Education.ExploreEducationStatistics.Admin.Tests/Security/AuthorizationHandlers/SubmitSpecificReleaseToHigherReviewAuthorizationHandlersTests.cs
src/GovUk.Education.ExploreEducationStatistics.Admin.Tests/Security/AuthorizationHandlers/UpdateSpecificReleaseAuthorizationHandlersTests.cs
src/GovUk.Education.ExploreEducationStatistics.Admin/Controllers/Api/Security/PermissionsController.cs
src/GovUk.Education.ExploreEducationStatistics.Admin/Security/AuthorizationHandlers/ApproveSpecificReleaseAuthorizationHandlers.cs
src/GovUk.Education.ExploreEducationStatistics.Admin/Security/AuthorizationHandlers/MarkSpecificReleaseAsDraftAuthorizationHandlers.cs
src/GovUk.Education.ExploreEducationStatistics.Admin/Security/AuthorizationHandlers/SubmitSpecificReleaseToHigherApprovalAuthorizationHandlers.cs
src/GovUk.Education.ExploreEducationStatistics.Admin/Security/AuthorizationHandlers/UpdateSpecificReleaseAuthorizationHandlers.cs
src/explore-education-statistics-admin/src/pages/release/ReleaseStatusPage.tsx
src/explore-education-statistics-admin/src/services/permissionService.ts

This PR allows BAU users to move releases back to Draft as long as they haven't been published yet.
As part of this, we've aggregated the current `/api/permissions/release/{releaseId}/status` permissions into a single endpoint, rather than needing to make 3 requests for each status type.

EES-957 Allow BAU users to move unpublished releases back to Draft

---

src/GovUk.Education.ExploreEducationStatistics.Admin/Migrations/ContentMigrations/20200707170022_EES415UpdateExternalMethodologyWithRequiredTitleAndUrl.Designer.cs
src/GovUk.Education.ExploreEducationStatistics.Admin/Migrations/ContentMigrations/20200707170022_EES415UpdateExternalMethodologyWithRequiredTitleAndUrl.cs

This PR adds a missing migration that EF is detecting we need due to the new  `Required` annotations on `ExternalMethodology` `Url` and `Title` fields.

EES-415 Add migration for external methodology's required url/title

---

src/explore-education-statistics-admin/src/App.tsx
src/explore-education-statistics-admin/src/components/Breadcrumbs.tsx
src/explore-education-statistics-admin/src/components/Page.tsx
src/explore-education-statistics-admin/src/components/PageFooter.tsx
src/explore-education-statistics-admin/src/components/__tests__/Breadcrumbs.test.tsx
src/explore-education-statistics-admin/src/pages/release/PreReleasePage.tsx
src/explore-education-statistics-admin/src/prototypes/PrototypeExamplePage.tsx
src/explore-education-statistics-admin/src/prototypes/PrototypeIndexPage.tsx
src/explore-education-statistics-admin/src/prototypes/components/PrototypePage.tsx
src/explore-education-statistics-admin/src/prototypes/components/PrototypePageBanner.tsx
src/explore-education-statistics-admin/src/prototypes/prototypeRoutes.ts

This PR adds prototype pages that are accessible via `/prototypes` or the footer link.

Admin prototype pages

---

src/GovUk.Education.ExploreEducationStatistics.Admin.Tests/Security/AuthorizationHandlers/ApproveSpecificReleaseAuthorizationHandlersTests.cs
src/GovUk.Education.ExploreEducationStatistics.Admin.Tests/Security/AuthorizationHandlers/MarkSpecificReleaseAsDraftAuthorizationHandlersTests.cs
src/GovUk.Education.ExploreEducationStatistics.Admin.Tests/Security/AuthorizationHandlers/SubmitSpecificReleaseToHigherReviewAuthorizationHandlersTests.cs
src/GovUk.Education.ExploreEducationStatistics.Admin.Tests/Security/AuthorizationHandlers/UpdateSpecificReleaseAuthorizationHandlersTests.cs
src/GovUk.Education.ExploreEducationStatistics.Admin/Security/AuthorizationHandlers/ApproveSpecificReleaseAuthorizationHandlers.cs
src/GovUk.Education.ExploreEducationStatistics.Admin/Security/AuthorizationHandlers/MarkSpecificReleaseAsDraftAuthorizationHandlers.cs
src/GovUk.Education.ExploreEducationStatistics.Admin/Security/AuthorizationHandlers/SubmitSpecificReleaseToHigherApprovalAuthorizationHandlers.cs
src/GovUk.Education.ExploreEducationStatistics.Admin/Security/AuthorizationHandlers/UpdateSpecificCommentAuthorizationHandler.cs
src/GovUk.Education.ExploreEducationStatistics.Admin/Security/AuthorizationHandlers/UpdateSpecificReleaseAuthorizationHandlers.cs
src/GovUk.Education.ExploreEducationStatistics.Admin/Services/Interfaces/IReleaseStatusRepository.cs
src/GovUk.Education.ExploreEducationStatistics.Admin/Services/ReleaseStatusRepository.cs
src/GovUk.Education.ExploreEducationStatistics.Admin/Services/ReleaseStatusService.cs
src/GovUk.Education.ExploreEducationStatistics.Admin/Startup.cs

This PR adds additional checks to release status permissions to prevent users from changing the status if publishing has already started or has completed.

EES-957 Prevent changing of release status if publishing has started/completed

---

src/explore-education-statistics-admin/src/components/editable/EditableAccordionSection.tsx
src/explore-education-statistics-admin/src/components/editable/EditableBlockWrapper.tsx
src/explore-education-statistics-admin/src/components/editable/EditableKeyStatTile.tsx
src/explore-education-statistics-admin/src/components/editable/__tests__/__snapshots__/EditableBlockRenderer.test.tsx.snap
src/explore-education-statistics-admin/src/pages/release/ReleaseStatusPage.tsx
src/explore-education-statistics-admin/src/pages/release/content/components/AddSecondaryStats.tsx
src/explore-education-statistics-admin/src/pages/release/content/components/DataBlockSelectForm.tsx
src/explore-education-statistics-admin/src/pages/release/content/components/KeyStatSelectForm.tsx
src/explore-education-statistics-admin/src/pages/release/content/components/ReleaseContentAccordionSection.tsx
src/explore-education-statistics-admin/src/pages/release/datablocks/components/ChartAxisConfiguration.tsx
src/explore-education-statistics-admin/src/pages/release/datablocks/components/ChartConfiguration.tsx
src/explore-education-statistics-admin/src/pages/release/datablocks/components/ChartDataSelector.tsx
src/explore-education-statistics-common/src/components/Button.module.scss
src/explore-education-statistics-common/src/components/Button.tsx
src/explore-education-statistics-common/src/components/ButtonGroup.module.scss
src/explore-education-statistics-common/src/components/WarningMessage.module.scss
src/explore-education-statistics-common/src/components/WarningMessage.tsx
src/explore-education-statistics-common/src/components/__tests__/__snapshots__/Button.test.tsx.snap
src/explore-education-statistics-common/src/modules/table-tool/components/WizardStepFormActions.tsx
tests/robot-tests/tests/admin/bau/release_status.robot
tests/robot-tests/tests/admin_and_public/bau/publish_release.robot
tests/robot-tests/tests/libs/admin-common.robot

This PR adds the following warning message to make users aware of the consequences of using the 'As soon as possible' option:
- Fix `WarningMessage` icon looking squashed despite using out of the box `govuk-frontend` styling. We also now vertically centre all the child elements.
- Refactor instances of groups of buttons to use `ButtonGroup` component. This ensures that the group's elements are spaced consistently and centrally consistently.
- Add UI tests to cover release status more comprehensively.

EES-1142 Add warning message to 'As soon as possible' option for release publishing

---

src/explore-education-statistics-common/src/contexts/ApplicationInsightsContext.tsx
src/explore-education-statistics-frontend/src/modules/ErrorPage.tsx
src/explore-education-statistics-frontend/src/pages/_app.tsx

This was due to the conditional child rendering that was taking place in`ApplicationInsightsContextProvider`. We have been doing this primarily to prevent `useApplicationInsights` from returning an optional `ApplicationInsights`.
We've now allowed `ApplicationInsights` to be optional and consequently `ApplicationInsightsContextProvider` will always render its children. This has meant some tweaks to our code where we `useApplicationInsights` to avoid potential null pointer errors.

EES-1148 Fix public frontend not rendering when JS is disabled

---

src/GovUk.Education.ExploreEducationStatistics.Common.Tests/Extensions/StringExtensionTests.cs
src/GovUk.Education.ExploreEducationStatistics.Common/Extensions/StringExtensions.cs

This fixes filter group keys not being PascalCased correctly so that non-alphanumeric characters are filtered out. This is leading to characters such as dots appearing in the keys.
These keys are used for the Formik field names and unfortunately cause validation to fail due to the dots being considered as 
object path notation by Formik.
We have now corrected the `PascalCase` function (and ergo the `CamelCase` function) so that only alphanumeric characters are allowed.

EES-1079 Fix incorrect PascalCasing of filter group keys

---

src/explore-education-statistics-admin/src/pages/methodology/edit-methodology/summary/MethodologySummaryEditPage.tsx
src/explore-education-statistics-admin/src/pages/methodology/edit-methodology/summary/MethodologySummaryPage.tsx
src/explore-education-statistics-admin/src/pages/release/ReleaseStatusPage.tsx
src/explore-education-statistics-admin/src/pages/release/ReleaseSummaryPage.tsx
src/explore-education-statistics-admin/src/pages/release/content/components/BasicReleaseSummary.tsx
src/explore-education-statistics-admin/src/pages/release/datablocks/components/ChartBuilderTabSection.tsx
src/explore-education-statistics-common/src/utils/date/__tests__/partialDate.test.ts
src/explore-education-statistics-common/src/utils/date/partialDate.ts

This PR fixes issues with `publishScheduled` and `nextReleaseDate` fields being parsed and formatted incorrectly when displayed on pages such as the 'Manage content' or 'Release status' pages.
As this was a fairly weird problem, let's look a bit more into why this happens and see what we can learn.
Javascript's `Date` can accept ISO8601 date strings passed into its constructor e.g.
```javascript
new Date('2020-01-01');
new Date('2020-01-01T12:00:00');
new Date('2020-01-01T12:00:00Z');
```
When we are just parsing an ISO8601 date without the time component in cases such as the `publishScheduled` or `nextReleaseDate` field, the date will be parsed to UTC i.e.
```javascript
new Date('2020-01-01').toISOString() === '2020-01-01T00:00:00.000Z'
```
This is great if we're only working with UTC …

EES-1091 Fix incorrect publish and next release dates in IE11

---

src/GovUk.Education.ExploreEducationStatistics.Data.Api.Tests/Controllers/MetaControllerTests.cs
src/GovUk.Education.ExploreEducationStatistics.Data.Api/Controllers/MetaController.cs
src/GovUk.Education.ExploreEducationStatistics.Data.Model/ReleaseFastTrack.cs
src/GovUk.Education.ExploreEducationStatistics.Data.Services.Tests/PublicationMetaServiceTests.cs
src/GovUk.Education.ExploreEducationStatistics.Data.Services/Interfaces/IPublicationMetaService.cs
src/GovUk.Education.ExploreEducationStatistics.Data.Services/PublicationMetaService.cs
src/GovUk.Education.ExploreEducationStatistics.Data.Services/ViewModels/Meta/PublicationSubjectsMetaViewModel.cs
src/GovUk.Education.ExploreEducationStatistics.Publisher/Services/FastTrackService.cs

Add the highlights field to the PublicationSubjectsMetaViewModel to be used for displaying top tables.
`{
"publicationId": "ce4d9287-3e4a-4f1f-b6a5-08d824c9830f",
"highlights": [
{
"id": "fad75800-6871-4a5a-0e76-08d824c9ca91",
"label": "Top table name"
}
],
"subjects": [
{
"id": "f56cb03b-0f50-4037-897f-08d824c9775f",
"label": "EES-342 Test Subject"
}
]
}`

EES-342 Add Top Table Highlights to PublicationSubjectsMetaViewModel

---

src/GovUk.Education.ExploreEducationStatistics.Common/Services/FileStoragePathUtils.cs
src/GovUk.Education.ExploreEducationStatistics.Publisher/Functions/PublishReleaseContentFunction.cs
src/GovUk.Education.ExploreEducationStatistics.Publisher/Models/CopyReleaseFilesCommand.cs
src/GovUk.Education.ExploreEducationStatistics.Publisher/Services/FastTrackService.cs
src/GovUk.Education.ExploreEducationStatistics.Publisher/Services/FileStorageService.cs
src/GovUk.Education.ExploreEducationStatistics.Publisher/Services/Interfaces/IFileStorageService.cs
src/GovUk.Education.ExploreEducationStatistics.Publisher/Services/PublishingService.cs
src/GovUk.Education.ExploreEducationStatistics.Publisher/Services/ReleaseService.cs

If any data blocks have been deleted when republishing then both ReleaseFastTracks and the FastTrack file for the datablock need to be deleted.
Similarly if a datablock HighlightName has been updated when republishing then the ReleaseFastTrack HighlightName needs updating.
We cover both by deleting all ReleaseFastTracks and FastTrack files prior to regenerating them all.
This PR also tries to tidy up some of the logic around deleting statistics Files for Previous versions in FileStorageService, making it a more generic `AdditionalDeleteDirectoryPaths` and moving the logic around whether the additional delete is required or not to `PublishingService `. I suspect there is a bug here anyway though, if the files are deleted during the same stage that they are copied (midnight), files will be …

EES-1166 Delete ReleaseFastTracks and FastTrack files prior to generating them

---

src/explore-education-statistics-admin/src/pages/release/datablocks/components/DataBlockSourceWizard.tsx
src/explore-education-statistics-admin/src/pages/release/datablocks/components/ReleaseDataBlocksPageTabs.tsx
src/explore-education-statistics-common/src/modules/table-tool/components/TableToolWizard.tsx
src/explore-education-statistics-common/src/modules/table-tool/components/WizardStepHeading.tsx
src/explore-education-statistics-common/src/modules/table-tool/components/__tests__/TableToolWizard.test.tsx
src/explore-education-statistics-common/src/services/tableBuilderService.ts
src/explore-education-statistics-frontend/src/modules/table-tool/TableToolPage.tsx
tests/robot-tests/tests/admin/bau/create_data_block_with_chart.robot
tests/robot-tests/tests/admin_and_public/bau/files/upload-file-test.csv
tests/robot-tests/tests/admin_and_public/bau/files/upload-file-test.meta.csv
tests/robot-tests/tests/admin_and_public/bau/publish_data.robot
tests/robot-tests/tests/admin_and_public/bau/publish_release.robot

This PR:
- Adds table highlights column to 'Choose a subject' step on table tool page for public frontend.
- Fixes 'Manage data blocks' page showing 'Choose a publication' step when creating a new data block.
- Adds UI tests to cover publishing of data and table highlights.

EES-342 Ad table highlights column to table tool

---

src/GovUk.Education.ExploreEducationStatistics.Publisher/Functions/PublishReleaseContentFunction.cs
src/GovUk.Education.ExploreEducationStatistics.Publisher/Functions/PublishReleaseContentImmediateFunction.cs
src/GovUk.Education.ExploreEducationStatistics.Publisher/Services/ContentService.cs
src/GovUk.Education.ExploreEducationStatistics.Publisher/Services/FastTrackService.cs
src/GovUk.Education.ExploreEducationStatistics.Publisher/Services/Interfaces/IContentService.cs
src/GovUk.Education.ExploreEducationStatistics.Publisher/Services/Interfaces/IFastTrackService.cs
src/GovUk.Education.ExploreEducationStatistics.Publisher/Services/Interfaces/IReleaseService.cs
src/GovUk.Education.ExploreEducationStatistics.Publisher/Services/ReleaseService.cs

For Releases that have just been published which are Amendments we need to:
* Delete FastTrack json files and ReleaseFastTrackRows for each Releases previous version.
* Delete Release content which hasn't been overwritten i.e. delete the previous version if the Release Slug was amended.
We were already doing the latter in `ReleaseService`. I have moved the method to `ContentService` which seems more appropriate and combined both operations.
I also added a new method to ReleaseService to help get Amendments for a list of `releaseIds`.

EES-1161 Delete FastTracks for previous version if Amendment

---

src/explore-education-statistics-admin/src/services/permissionService.ts

The start/end dates for `PreReleaseWindowStatus` were missing `parseISO` to convert them UTC dates to local times, leading to them being incorrectly displayed.

EES-1091 Add `parseISO` to prerelease window status dates

---

src/GovUk.Education.ExploreEducationStatistics.Publisher.Model/ReleaseStatus.cs
src/GovUk.Education.ExploreEducationStatistics.Publisher.Model/ReleaseStatusState.cs
src/GovUk.Education.ExploreEducationStatistics.Publisher/Functions/PublishReleaseContentFunction.cs
src/GovUk.Education.ExploreEducationStatistics.Publisher/Functions/PublishReleaseContentImmediateFunction.cs
src/GovUk.Education.ExploreEducationStatistics.Publisher/Functions/PublishReleasesFunction.cs
src/GovUk.Education.ExploreEducationStatistics.Publisher/Services/Interfaces/IReleaseStatusService.cs
src/GovUk.Education.ExploreEducationStatistics.Publisher/Services/ReleaseStatusService.cs
src/GovUk.Education.ExploreEducationStatistics.Publisher/Services/ReleaseStatusTableQueryUtil.cs

Cancel publishing of any other releases sharing a dependency with the content of a failing release.
**Reason:** Publishing any Release copies the whole staging directory.
Cancelling the publishing stage of other Releases is necessary to avoid publishing staged content of the Release which is now failing, and other parts of content which were calculated expecting that Release to exist.
Future work in EES-1070 will mean the failing stage can be retried and successful retry attempts will reschedule publishing of all affected Releases.

EES-648 Cancel publishing of releases sharing a dependency with the content of a failing release

---

src/GovUk.Education.ExploreEducationStatistics.Data.Model/Migrations/20200715112018_Routine_DropAndCreateRelease.sql

Split of the string was incorrect in the stored procedure when more than one subject or footnote.

EES-1176 Correct split of string

---

src/GovUk.Education.ExploreEducationStatistics.Admin.Tests/Security/AuthorizationHandlers/MakeAmendmentOfReleaseAuthorizationHandlersTests.cs
src/GovUk.Education.ExploreEducationStatistics.Admin.Tests/Services/ReleaseServiceAmendmentTests.cs
src/GovUk.Education.ExploreEducationStatistics.Admin/Security/AuthorizationHandlers/MakeAmendmentOfSpecificReleaseAuthorizationHandlers.cs

It was previously possible to create an Amendment of an older version, at least at an API level, and also by clicking the confirmation multiple times in quick succession.

EES-1189 Prevent creating Amendments of older versions

---

src/GovUk.Education.ExploreEducationStatistics.Notifier/GovUk.Education.ExploreEducationStatistics.Notifier.csproj
src/GovUk.Education.ExploreEducationStatistics.Notifier/PublicationNotifier.cs

* Temporarily downgrade Notifier dependency Microsoft.NET.Sdk.Functions to 3.0.3
Prevents error when subscribing to Publications
`'Could not load file or assembly 'Microsoft.IdentityModel.Tokens, Version=6.5.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'. The system cannot find the file specified'`
See https://github.com/Azure/azure-functions-host/issues/5894
* Add logging for caught exceptions.
* Update Azure IdentityModel Tokens extension library to 6.5.0.

EES-1205 Temporarily downgrading Notifier dependency Microsoft.NET.Sdk.Functions to 3.0.3

---

src/explore-education-statistics-common/src/components/form/FormFieldFileInput.tsx

The validation error was being thrown on screen as the user clicked to choose a file on the file input.
This was caused by the `field.onBlur` being ran as soon as the file selector was opened which lead to the file input being blurred.
To combat this, I've added a `useToggle` (`fileHasBeenSelected`) to track if the user has previously added a file to the input.
If a file was never added, the validation will not run, even if the file selection is cancelled.
If a file was previously added, and then it was removed, an error will be thrown.
The changes will not affect the onSubmit form validation, so if the user doesn't add a file and they try to submit, an error will still be displayed onscreen as expected.

EES-1200 - fileInput premature validation

---

src/explore-education-statistics-admin/src/services/releaseAncillaryFileService.ts

This fixes the immediate problem of not being able to add ancillary files but there's no need to return arrays from the back end as the frontend re-requests all row files anyway on successful addition. This is probably a historical hangover.
I have raised https://dfedigital.atlassian.net/browse/EES-1210 to address the further changes needed.

EES-1208 Add ancillary has incorrect return value.

---

src/explore-education-statistics-common/src/components/form/FormFieldFileInput.tsx

Added additional checking for the forms field value, against the input value - if they differ, then the formField value was changed outside of the input controls - for instance, when the form is reset programatically. If this happens, we now reset the (previously added) field touched state

EES-1200 - fileInput premature validation (part 2)

---

src/GovUk.Education.ExploreEducationStatistics.Admin.Tests/Controllers/Api/Statistics/FootnoteControllerTests.cs
src/GovUk.Education.ExploreEducationStatistics.Common/Model/Unit.cs
src/GovUk.Education.ExploreEducationStatistics.Publisher/Functions/NotifyChangeFunction.cs
src/GovUk.Education.ExploreEducationStatistics.Publisher/Services/Interfaces/IValidationService.cs
src/GovUk.Education.ExploreEducationStatistics.Publisher/Services/ValidationService.cs

**Depends on https://github.com/dfe-analytical-services/explore-education-statistics/pull/1881**
Previously we were validating the Release regardless of any state in a ReleaseStatus row for the Release and as part of the validation we checked that state. A new ReleaseStatus row was always added for every invocation regardless of passing or failing validation.
This PR separates out the validation of any existing state to the rest of the validation.
If an existing state is found which is Started or Scheduled execution stops and no ReleaseStatus row is written.
(Scheduled should never occur anyway since any existing scheduled Releases are superseded at the beginning).
This fixes a problem where multiple `Immediate=true` approvals  in quick succession resulted in invalid ReleaseStatus rows …

EES-1185 Don't validate Release if Publishing State is already Started

---

src/explore-education-statistics-admin/src/components/editable/EditableKeyStat.tsx
src/explore-education-statistics-admin/src/pages/release/content/components/KeyStatSelectForm.tsx
src/explore-education-statistics-admin/src/pages/release/content/components/KeyStatistics.tsx
src/explore-education-statistics-admin/src/pages/release/content/contexts/useReleaseContentActions.ts
src/explore-education-statistics-admin/src/services/releaseContentService.ts
src/explore-education-statistics-common/src/modules/charts/components/MapBlockInternal.tsx
src/explore-education-statistics-common/src/modules/charts/components/__tests__/MapBlock.test.tsx
src/explore-education-statistics-common/src/modules/find-statistics/components/KeyStat.module.scss
src/explore-education-statistics-common/src/modules/find-statistics/components/KeyStat.tsx
src/explore-education-statistics-common/src/modules/find-statistics/components/KeyStatTile.module.scss
src/explore-education-statistics-common/src/modules/find-statistics/components/KeyStatTile.tsx
src/explore-education-statistics-frontend/src/modules/find-statistics/components/PublicationReleaseHeadlinesSection.tsx
tests/robot-tests/tests/admin/analyst/analyst_absence_permissions.robot
tests/robot-tests/tests/libs/common.robot
tests/robot-tests/tests/libs/public-utilities.py

Unfortunately we've had to abuse `!important` to style the contents correctly. This is mostly to make it easier to style the rendered `children` correctly.
It's also quite awkward to emulate GOVUK heading/body styles without using `@extends`. I'm not particularly a big fan of some of their choices here in regards to extensibility.
We've also moved logic out `KeyStatTile` and placed it in `KeyStat` instead. This allows us to more easily re-use `KeyStatTile` itself in other places such as `MapBlockInternal`.

EES-1214 Fix KeyStatTiles having black text (instead of white)

---

src/GovUk.Education.ExploreEducationStatistics.Admin/Services/ImportService.cs
src/GovUk.Education.ExploreEducationStatistics.Admin/Services/Interfaces/IImportService.cs
src/GovUk.Education.ExploreEducationStatistics.Common.Tests/Model/EitherTest.cs
src/GovUk.Education.ExploreEducationStatistics.Common/Model/Either.cs

This PR attempts to fix EES-1227 which appears to be being caused by threading issues arising from `Either.OnSuccessDo`. 
We think this is due to the current implementation having overloads that don't `await` the result of their success task, meaning that execution continues without waiting for all async methods to complete (i.e. database transactions) in the success task before moving onto the next chained `Either`.

EES-1227 Add awaits to all `Either.OnSuccessDo` overloads

---

src/GovUk.Education.ExploreEducationStatistics.Common/BlobContainerNames.cs
src/GovUk.Education.ExploreEducationStatistics.Common/Services/FileStorageUtils.cs
src/GovUk.Education.ExploreEducationStatistics.Data.Api/Services/FileStorageService.cs
src/GovUk.Education.ExploreEducationStatistics.Publisher/Functions/NotifyChangeFunction.cs
src/GovUk.Education.ExploreEducationStatistics.Publisher/Functions/PublishReleaseDataFunction.cs
src/GovUk.Education.ExploreEducationStatistics.Publisher/Services/FileStorageService.cs
src/GovUk.Education.ExploreEducationStatistics.Publisher/Services/Interfaces/IFileStorageService.cs
src/GovUk.Education.ExploreEducationStatistics.Publisher/Services/Interfaces/IReleaseStatusService.cs
src/GovUk.Education.ExploreEducationStatistics.Publisher/Services/ReleaseStatusService.cs

https://github.com/dfe-analytical-services/explore-education-statistics/pull/1885 made an improvement to stop further validation and stop Invalid ReleaseStatus rows from being written if publishing has already Started.
This PR makes sure that if approval messages are being processed concurrently that they can't enter the `ValidatePublishingState ` or  `CreateReleaseStatusAsync ` methods without being aware of each other if they are for the same Release Id by acquiring a lease on the Release id for a short amount of time.
Previously it was possible for multiple messages for the same Release processed concurrently to all pass the validation due to seeing no existing rows, and then all enter the create method and write multiple `ReleaseStatus ` rows. This resulted in stages running …

EES-1185 Acquire lease on Release Id when validating Release approval notification

---

src/GovUk.Education.ExploreEducationStatistics.Publisher/Functions/DataFactoryPipelineStatusFunction.cs
src/GovUk.Education.ExploreEducationStatistics.Publisher/Services/ReleaseStatusService.cs

This PR reinstates publishing for this Release and other failed Releases after a successful retry of the Data Stage.
Calculates the states for reinstating stages before they were cancelled due to a failure.
Checks that the states are still Cancelled/Failed as expected, and if not, leaves them untouched.
Updates the succeeding row at the same time that the Data stage state is changed to Complete and then goes on to reinstate publishing of any other releases sharing a dependency with the content of that Release which were also cancelled.

EES-1070 Reinstate publishing for this and other failed Releases after a successful retry of the Data Stage

---

src/GovUk.Education.ExploreEducationStatistics.Admin.Tests/Services/LegacyReleaseServiceTests.cs
src/GovUk.Education.ExploreEducationStatistics.Admin/Services/LegacyReleaseService.cs
tests/robot-tests/tests/admin/bau/legacy_releases.robot

This PR ensures that legacy releases are reordered correctly when updating a single one.
We expect to see that:
- The updated legacy release can correctly take the position of an existing sibling.
- Sibling legacy releases are shifted around to make room for the legacy release.
- There are no gaps in the `order` field for the legacy releases i.e. they always increment sequentially.
- Various improvements to `LegacyReleaseServiceTests` to better assert that create/update method results are correct.

EES-1247 Fix re-ordering of legacy releases upon edit

---

src/GovUk.Education.ExploreEducationStatistics.Admin.Tests/Services/PublicationServicePermissionTests.cs
src/GovUk.Education.ExploreEducationStatistics.Admin.Tests/Services/PublicationServiceTests.cs
src/GovUk.Education.ExploreEducationStatistics.Admin.Tests/Services/PublishingServicePermissionTests.cs
src/GovUk.Education.ExploreEducationStatistics.Admin.Tests/Services/PublishingServiceTests.cs
src/GovUk.Education.ExploreEducationStatistics.Admin/Controllers/Api/BAU/BauReleaseController.cs
src/GovUk.Education.ExploreEducationStatistics.Admin/Migrations/ContentMigrations/20200806145340_EES1121AddPublicationPublishedDateTime.Designer.cs
src/GovUk.Education.ExploreEducationStatistics.Admin/Migrations/ContentMigrations/20200806145340_EES1121AddPublicationPublishedDateTime.cs
src/GovUk.Education.ExploreEducationStatistics.Admin/Services/Interfaces/IPublishingService.cs
src/GovUk.Education.ExploreEducationStatistics.Admin/Services/PublicationService.cs
src/GovUk.Education.ExploreEducationStatistics.Admin/Services/PublishingService.cs
src/GovUk.Education.ExploreEducationStatistics.Admin/Services/ReleaseService.cs
src/GovUk.Education.ExploreEducationStatistics.Common.Tests/Extensions/StringExtensionTests.cs
src/GovUk.Education.ExploreEducationStatistics.Common/Extensions/StringExtensions.cs
src/GovUk.Education.ExploreEducationStatistics.Common/Services/FileStoragePathUtils.cs
src/GovUk.Education.ExploreEducationStatistics.Content.Model/Publication.cs
src/GovUk.Education.ExploreEducationStatistics.Publisher.Model/PublishPublicationMessage.cs
src/GovUk.Education.ExploreEducationStatistics.Publisher.Model/PublisherQueues.cs
src/GovUk.Education.ExploreEducationStatistics.Publisher.Model/ViewModels/CachedReleaseViewModel.cs
src/GovUk.Education.ExploreEducationStatistics.Publisher/Functions/PublishPublicationFunction.cs
src/GovUk.Education.ExploreEducationStatistics.Publisher/Services/ContentService.cs
src/GovUk.Education.ExploreEducationStatistics.Publisher/Services/FileStorageService.cs
src/GovUk.Education.ExploreEducationStatistics.Publisher/Services/Interfaces/IContentService.cs
src/GovUk.Education.ExploreEducationStatistics.Publisher/Services/Interfaces/IFileStorageService.cs
src/GovUk.Education.ExploreEducationStatistics.Publisher/Services/Interfaces/IPublicationService.cs
src/GovUk.Education.ExploreEducationStatistics.Publisher/Services/PublicationService.cs
src/GovUk.Education.ExploreEducationStatistics.Publisher/Services/PublishingService.cs
src/GovUk.Education.ExploreEducationStatistics.Publisher/Services/ReleaseService.cs
src/GovUk.Education.ExploreEducationStatistics.Publisher/host.json

This PR publishes a Publication when it is edited by sending a message to the Publisher.
The Publisher will regenerate the Publication cache, and move files and content for the Publication if the slug has changed.
A Publication still relies on first being published along with a Release when the first Release is published.
When a publication is edited, if it's not yet published, no message is sent.

EES-1221 Allow publishing of a Publication independently to a Release

---

src/explore-education-statistics-admin/src/pages/release/data/components/ReleaseDataUploadsSection.tsx
src/explore-education-statistics-admin/src/pages/release/data/components/ReleaseFileUploadsSection.tsx
src/explore-education-statistics-admin/src/pages/release/data/components/footnotes/form/FootnoteForm.tsx
src/explore-education-statistics-common/src/components/SummaryListItem.tsx

This PR fixes `SummaryListItem` not rendering its `actions` prop correctly if it has no `children`.
- Fixed incorrectly styled cancel buttons across 'Manage data' section forms

EES-1262 Fix SummmaryListItem actions not rendering correctly when no children

---

src/GovUk.Education.ExploreEducationStatistics.Admin.Tests/Services/Methodologies/MethodologyServiceTests.cs
src/GovUk.Education.ExploreEducationStatistics.Admin/Controllers/Api/Methodologies/CreateMethodologyRequest.cs
src/GovUk.Education.ExploreEducationStatistics.Admin/Controllers/Api/Methodologies/UpdateMethodologyRequest.cs
src/GovUk.Education.ExploreEducationStatistics.Admin/Mappings/MappingProfiles.cs
src/GovUk.Education.ExploreEducationStatistics.Admin/Migrations/ContentMigrations/20200810131121_EES1237RemoveMethodologyPublishScheduled.Designer.cs
src/GovUk.Education.ExploreEducationStatistics.Admin/Migrations/ContentMigrations/20200810131121_EES1237RemoveMethodologyPublishScheduled.cs
src/GovUk.Education.ExploreEducationStatistics.Admin/Models/Api/MethodologySummaryViewModel.cs
src/GovUk.Education.ExploreEducationStatistics.Admin/Services/Methodologies/MethodologyService.cs
src/GovUk.Education.ExploreEducationStatistics.Content.Model/Database/ContentDbContext.cs
src/GovUk.Education.ExploreEducationStatistics.Content.Model/Methodology.cs
src/explore-education-statistics-admin/src/pages/methodology/MethodologyCreatePage.tsx
src/explore-education-statistics-admin/src/pages/methodology/components/MethodologySummaryForm.tsx
src/explore-education-statistics-admin/src/pages/methodology/edit-methodology/content/context/__tests__/MethodologyContext.test.tsx
src/explore-education-statistics-admin/src/pages/methodology/edit-methodology/summary/MethodologySummaryEditPage.tsx
src/explore-education-statistics-admin/src/pages/methodology/edit-methodology/summary/MethodologySummaryPage.tsx
src/explore-education-statistics-admin/src/pages/publication/components/__tests__/PublicationForm.test.tsx
src/explore-education-statistics-admin/src/services/methodologyContentService.ts
src/explore-education-statistics-admin/src/services/methodologyService.ts

Scheduling when creating methodology was not required since a new methodology is only published when a Publication using it has a Release published.
Also agreed with @lauraselby that updates to Methodology will be made as soon as they are approved, so no scheduling required on update either.
There will be a future enhancement to make amendments to methodology - EES-1263.

EES-1237 Remove scheduling support for Methodology

---

src/GovUk.Education.ExploreEducationStatistics.Admin.Tests/Security/AuthorizationHandlers/MarkSpecificMethodologyAsDraftAuthorizationHandlerTests.cs
src/GovUk.Education.ExploreEducationStatistics.Admin.Tests/Security/AuthorizationHandlers/UpdateSpecificMethodologyAuthorizationHandlerTests.cs
src/GovUk.Education.ExploreEducationStatistics.Admin.Tests/Services/Methodologies/MethodologyServiceTests.cs
src/GovUk.Education.ExploreEducationStatistics.Admin.Tests/Services/PublicationServiceTests.cs
src/GovUk.Education.ExploreEducationStatistics.Admin.Tests/Services/PublishingServiceTests.cs
src/GovUk.Education.ExploreEducationStatistics.Admin/Areas/Identity/Data/UsersAndRolesDbContext.cs
src/GovUk.Education.ExploreEducationStatistics.Admin/Controllers/Api/Security/PermissionsController.cs
src/GovUk.Education.ExploreEducationStatistics.Admin/Migrations/20200813105224_EES913AssignClaimToRole.Designer.cs
src/GovUk.Education.ExploreEducationStatistics.Admin/Migrations/20200813105224_EES913AssignClaimToRole.cs
src/GovUk.Education.ExploreEducationStatistics.Admin/Migrations/ContentMigrations/20200812154820_EES913AddUpdatedFields.Designer.cs
src/GovUk.Education.ExploreEducationStatistics.Admin/Migrations/ContentMigrations/20200812154820_EES913AddUpdatedFields.cs
src/GovUk.Education.ExploreEducationStatistics.Admin/Security/AuthorizationHandlers/MarkSpecificMethodologyAsDraftAuthorizationHandlers.cs
src/GovUk.Education.ExploreEducationStatistics.Admin/Security/AuthorizationHandlers/UpdateSpecificMethodologyAuthorizationHandlers.cs
src/GovUk.Education.ExploreEducationStatistics.Admin/Security/SecurityClaimTypes.cs
src/GovUk.Education.ExploreEducationStatistics.Admin/Services/Interfaces/IPublishingService.cs
src/GovUk.Education.ExploreEducationStatistics.Admin/Services/Methodologies/MethodologyService.cs
src/GovUk.Education.ExploreEducationStatistics.Admin/Services/PublicationService.cs
src/GovUk.Education.ExploreEducationStatistics.Admin/Services/PublishingService.cs
src/GovUk.Education.ExploreEducationStatistics.Content.Model/Database/ContentDbContext.cs
src/GovUk.Education.ExploreEducationStatistics.Content.Model/Methodology.cs
src/GovUk.Education.ExploreEducationStatistics.Content.Model/Publication.cs
src/GovUk.Education.ExploreEducationStatistics.Publisher.Model/PublishPublicationMessage.cs
src/GovUk.Education.ExploreEducationStatistics.Publisher.Model/ViewModels/MethodologyViewModel.cs
src/GovUk.Education.ExploreEducationStatistics.Publisher.Tests/Services/MethodologyServiceTests.cs
src/GovUk.Education.ExploreEducationStatistics.Publisher.Tests/Services/PublicationServiceTests.cs
src/GovUk.Education.ExploreEducationStatistics.Publisher/Functions/PublishPublicationFunction.cs
src/GovUk.Education.ExploreEducationStatistics.Publisher/Services/ContentService.cs
src/GovUk.Education.ExploreEducationStatistics.Publisher/Services/Interfaces/IContentService.cs
src/explore-education-statistics-admin/src/pages/methodology/edit-methodology/status/MethodologyStatusPage.tsx

- Allow BAU users to mark a Methodology as Draft to make further changes after it has already been approved.
- Don't Alter Publication or Methodology slugs if the they are already published.  We shouldn't be updating the slugs as we have no other way to handle redirecting links.

EES-913 Allow BAU users to mark Methodology as Draft. Don't Alter Publication or Methodology slugs

---

src/explore-education-statistics-admin/src/App.tsx
src/explore-education-statistics-common/src/components/DetailsMenu.module.scss
src/explore-education-statistics-common/src/modules/charts/util/__tests__/createDataSetCategories.test.ts
src/explore-education-statistics-common/src/modules/charts/util/createDataSetCategories.ts
src/explore-education-statistics-frontend/src/pages/_app.tsx
tests/robot-tests/run_tests.py
tests/robot-tests/tests/admin/bau/create_data_block_with_chart.robot
tests/robot-tests/tests/admin/bau/create_publication_and_release.robot
tests/robot-tests/tests/admin/bau/delete_subject.robot
tests/robot-tests/tests/admin/bau/release_status.robot
tests/robot-tests/tests/admin_and_public/bau/publish_data.robot
tests/robot-tests/tests/general_public/table_tool_absence_by_characteristic.robot
tests/robot-tests/tests/general_public/table_tool_absence_in_prus.robot
tests/robot-tests/tests/general_public/table_tool_exclusions_by_geographic_level.robot
tests/robot-tests/tests/libs/admin-common.robot
tests/robot-tests/tests/libs/common.robot
tests/robot-tests/tests/libs/utilities.py

This PR:
- Refactors and cleans up checkbox/radio keywords:
- Adds additional keywords to cover clicking and checking the checked/unchecked checkbox/radio state. Some of this has been moved out of `utilities.py` into `common.robot`.
- Makes use of more lower-level keywords instead of relying on copy-pasta.
- Adds stricter checks on `input` type being checkbox or radio.
- Removes `user selects start/end date` keywords as these are far too specific to the time period form in table tool.
- Fixes data data set categories being incorrectly generated when there is only grouping filter.
- Fixes incorrect style import order causing incorrect styling of things like the `DetailsMenu` component.

EES-1269 Cleanup checkbox/radios and other test keyword cleanup

---

src/explore-education-statistics-admin/src/pages/release/datablocks/reducers/__tests__/chartBuilderReducer.test.ts
src/explore-education-statistics-admin/src/pages/release/datablocks/reducers/chartBuilderReducer.ts
src/explore-education-statistics-common/src/modules/charts/components/MapBlock.tsx
src/explore-education-statistics-common/src/modules/charts/types/chart.ts

Currently chart definitions allow you to specify constant values that will always be set in the current chart/axes options. Whilst this was a nice idea on paper, this causes issues when trying to swap between charts.
We've specifically found that changing from/to a map chart causes the `groupBy` option to be forced to 'locations'. This isn't a major problem but doesn't make a very nice user experience as the user will most likely not want this groupBy.
Instead of defining constants in the chart, we can just set these in the chart component itself. For exmaple, we are already doing this in `MapBlockInternal` to force the `groupBy` to 'locations'.

EES-357 Remove chart definition constants in favour of defaults

---

Pipfile
Pipfile.lock
src/explore-education-statistics-admin/src/pages/admin-dashboard/components/ManagePublicationsAndReleasesTab.tsx
tests/robot-tests/tests/admin/bau/manage_content.robot
tests/robot-tests/tests/admin/bau/prerelease.robot
tests/robot-tests/tests/admin_and_public/bau/footnotes.robot
tests/robot-tests/tests/admin_and_public/bau/publish_data.robot
tests/robot-tests/tests/admin_and_public/bau/publish_release_and_amend.robot
tests/robot-tests/tests/general_public/table_tool_exclusions_by_geographic_level.robot
tests/robot-tests/tests/libs/utilities.py

This PR fixes test assertions on the prerelease start/end times being incorrect when running the tests from a non-UK timezone. This is currently problematic as the build agents run on UTC and these time assertions will usually be off by an hour.
We resolve this by converting the expected UK local time (i.e. midnight of the scheduled publish date) to the test runner's local timezone via a new `format uk to local date time` keyword.

EES-1271 Fix prerelease window start/end time assertions for all timezones

---

src/GovUk.Education.ExploreEducationStatistics.Publisher/Services/ContentService.cs
src/GovUk.Education.ExploreEducationStatistics.Publisher/Services/ReleaseService.cs

This PR fixes a bug visible on Publications with more than one Release published since EES-1221 went live on 27/08/20 where the latest release displays an incorrect link to an older Release labelled as the "latest", and all the older Releases have no "Other Release" link back to the real latest Release.
As part of EES-1221 we made a change to prevent generating the Publication cache json file with every Release unless it's the first Release for the Publication (i.e. never published before).
We then only ever generated the Publication cache json again if there's an update to the Publication (title/contact details etc).
This has caused a bug because on publishing additional Releases for the same Publication (amendment or not, it doesn't matter), the Publication cache isn't getting updated. …

EES-1339 Revert to regenerating the Publication with every Release

---

src/GovUk.Education.ExploreEducationStatistics.Admin.Tests/Services/ReleaseServiceAmendmentTests.cs
src/GovUk.Education.ExploreEducationStatistics.Admin/Migrations/ContentMigrations/20200825153306_EES1145AllowReleasePreviousVersionIdToBeNullable.Designer.cs
src/GovUk.Education.ExploreEducationStatistics.Admin/Migrations/ContentMigrations/20200825153306_EES1145AllowReleasePreviousVersionIdToBeNullable.cs
src/GovUk.Education.ExploreEducationStatistics.Admin/Security/AuthorizationHandlers/MakeAmendmentOfSpecificReleaseAuthorizationHandlers.cs
src/GovUk.Education.ExploreEducationStatistics.Admin/Services/ReleaseService.cs
src/GovUk.Education.ExploreEducationStatistics.Content.Model/Database/ContentDbContext.cs
src/GovUk.Education.ExploreEducationStatistics.Content.Model/Publication.cs
src/GovUk.Education.ExploreEducationStatistics.Content.Model/Release.cs
src/GovUk.Education.ExploreEducationStatistics.Content.Model/Versioned.cs
src/GovUk.Education.ExploreEducationStatistics.Data.Model/Migrations/20200825161515_EES1445AllowReleasePreviousVersionIdToBeNullable.Designer.cs
src/GovUk.Education.ExploreEducationStatistics.Data.Model/Migrations/20200825161515_EES1445AllowReleasePreviousVersionIdToBeNullable.cs
src/GovUk.Education.ExploreEducationStatistics.Data.Model/Release.cs
src/GovUk.Education.ExploreEducationStatistics.Data.Processor.Model/Release.cs
src/GovUk.Education.ExploreEducationStatistics.Data.Processor/Services/ReleaseProcessorService.cs
src/GovUk.Education.ExploreEducationStatistics.Publisher.Tests/Services/PublicationServiceTests.cs
src/GovUk.Education.ExploreEducationStatistics.Publisher.Tests/Services/ReleaseServiceTests.cs
src/GovUk.Education.ExploreEducationStatistics.Publisher.Tests/Utils/PublisherUtilsTests.cs
src/GovUk.Education.ExploreEducationStatistics.Publisher/Functions/PublishReleaseContentFunction.cs
src/GovUk.Education.ExploreEducationStatistics.Publisher/Services/ContentService.cs
src/GovUk.Education.ExploreEducationStatistics.Publisher/Services/FileStorageService.cs
src/GovUk.Education.ExploreEducationStatistics.Publisher/Services/ReleaseService.cs

This PR changes `Release.PreviousVersionId` to nullable so that we can make it easier to bulk delete releases when deleting themes/topics. Currently `PreviousVersionId` cannot be nulled and EF is consequently unable to delete all of a theme/topic's releases in a single operation due to the self-referential nature of the `Release` -> `PreviousVersion` relationship.
Additionally, `PreviousVersionId` can take on non-sensical IDs such as `Guid.Empty` or its own `Id` when it is the first release (doesn't make sense as the previous version shouldn't be itself). These changes should correct the semantics of `PreviousVersion` and `PreviousVersionId` i.e. make them properly optional.

EES-1145 Make `Release.PreviousVersionId` field nullable

---

src/explore-education-statistics-admin/src/components/editable/EditableContentBlock.tsx
src/explore-education-statistics-admin/src/components/editable/EditableKeyStat.tsx
src/explore-education-statistics-admin/src/components/editable/__tests__/EditableKeyStat.test.tsx
src/explore-education-statistics-admin/src/components/form/FormEditor.module.scss
src/explore-education-statistics-admin/src/components/form/FormEditor.tsx
src/explore-education-statistics-admin/src/prototypes/PrototypeBauGlossary.tsx
src/explore-education-statistics-admin/src/prototypes/components/PrototypeMetaForms.tsx
src/explore-education-statistics-admin/src/prototypes/components/PrototypePreReleaseCreate.tsx
src/explore-education-statistics-common/src/modules/find-statistics/components/KeyStat.tsx
src/explore-education-statistics-common/src/modules/find-statistics/components/KeyStatTile.tsx
src/explore-education-statistics-common/src/modules/find-statistics/components/__tests__/KeyStat.test.tsx
src/explore-education-statistics-common/src/modules/find-statistics/hooks/useKeyStatQuery.ts
tests/robot-tests/tests/admin/analyst/analyst_absence_permissions.robot
tests/robot-tests/tests/general_public/release_page_absence.robot
tests/robot-tests/tests/libs/common.robot
tests/robot-tests/tests/libs/public-common.robot

This PR primarily fixes the `EditableKeyStat` components not rendering  in the same way that `KeyStat` does, leading to the missing summaries/definitions. This was due to a recent refactoring neglecting to keep both of these components in parity with one another.
- Fixed heading markup semantics for `EditableKeyStat` when toggling between read-only and writeable variants. Now correctly goes from `h3` to `h4`.
- Added better error handling to `EditableKeyStat` so that admin users can more easily see when there is a problem loading the key stat (e.g. there is a backend error). They can also choose to delete the key stat from the content if required.
- Made `EditableKeyStat` form input ids consistent (based on the form id) so that form validation can be applied correctly.
- Adds unit tests …

EES-1347 Fixes 'Manage content' key stats not showing summaries/definitions

---

src/GovUk.Education.ExploreEducationStatistics.Data.Model/Services/ReleaseSubjectService.cs

This error means we will have orphaned subjects in the DB but I will see how many first and choose a quiet time to clean up the dbs.

EES-1366 Fix set of soft deleted subject.

---

src/GovUk.Education.ExploreEducationStatistics.Admin.Tests/Services/ReplacementServiceTests.cs
src/GovUk.Education.ExploreEducationStatistics.Admin/Controllers/Api/ReleasesController.cs
src/GovUk.Education.ExploreEducationStatistics.Admin/Services/Interfaces/IReplacementService.cs
src/GovUk.Education.ExploreEducationStatistics.Admin/Services/ReplacementService.cs
src/GovUk.Education.ExploreEducationStatistics.Admin/Validators/ValidationUtils.cs
src/GovUk.Education.ExploreEducationStatistics.Admin/ViewModels/ReplacementPlanViewModel.cs
src/GovUk.Education.ExploreEducationStatistics.Common/Extensions/DictionaryExtensions.cs
src/GovUk.Education.ExploreEducationStatistics.Common/Extensions/EnumerableExtensions.cs
src/GovUk.Education.ExploreEducationStatistics.Common/Extensions/TableHeadersExtensions.cs

Allows changing the Subject of DataBlocks or Footnotes on a Release.
For DataBlocks as well as changing the Subject this includes changing the Filter Items and Indicators of the data block query and the table header configuration.
For Footnotes as well as changing any linked Subject this includes changing any linked Filter Items, Filter Groups, Filters and Indicators.
A replacement plan is generated immediately before updating and this must be valid.

EES-1292 API to allow replacing a Subject on DataBlocks and Footnotes

---

src/GovUk.Education.ExploreEducationStatistics.Admin.Tests/Controllers/Api/Statistics/FootnoteControllerTests.cs
src/GovUk.Education.ExploreEducationStatistics.Admin.Tests/Services/ReleaseServiceAmendmentTests.cs
src/GovUk.Education.ExploreEducationStatistics.Admin/Services/FootnoteService.cs
src/GovUk.Education.ExploreEducationStatistics.Admin/Services/Interfaces/IFootnoteService.cs
src/GovUk.Education.ExploreEducationStatistics.Admin/Services/ReleaseService.cs

The previous version of a Release needs to remain unaffected by replacing data in case a user cancels an amendment and then decides to amend it again.
This PR makes it so a copy of existing Footnotes (and all of their criteria links) is always made when amending a Release.
This makes it easier to do things like replacing data where we would otherwise need to work out if the Footnote is exclusive to a Release and clone the footnote if not, to avoid affecting the previous version.
We are now guaranteed that a footnote is exclusive to a Release and can be safely altered, except for any draft Release amendments that exist when this change is deployed.

EES-1377 Always copy Footnotes when amending a Release

---

src/GovUk.Education.ExploreEducationStatistics.Admin.Tests/Services/ReplacementServiceTests.cs
src/GovUk.Education.ExploreEducationStatistics.Admin/Services/ReplacementService.cs
src/GovUk.Education.ExploreEducationStatistics.Admin/ViewModels/DataReplacementPlanViewModel.cs

Remove the `target` field from the DataBlock Filters and FilterGroup replacement response models which isn't needed.
Presence of a target value was previously used to check if the Filter / Filter Group are valid but this should have been checking whether the child Filter Groups / Filter Items are also valid.
New valid field added to both response models which checks that their children are valid.

EES-221 Filters and Filter Groups are valid only if their children are all valid

---

src/GovUk.Education.ExploreEducationStatistics.Admin.Tests/Controllers/Api/ReleasesControllerTests.cs
src/GovUk.Education.ExploreEducationStatistics.Admin.Tests/Services/ReleaseServicePermissionTests.cs
src/GovUk.Education.ExploreEducationStatistics.Admin.Tests/Services/ReleaseServiceTests.cs
src/GovUk.Education.ExploreEducationStatistics.Admin.Tests/Services/ReplacementServiceTests.cs
src/GovUk.Education.ExploreEducationStatistics.Admin/Controllers/Api/ReleasesController.cs
src/GovUk.Education.ExploreEducationStatistics.Admin/Services/Interfaces/IReleaseService.cs
src/GovUk.Education.ExploreEducationStatistics.Admin/Services/ReleaseService.cs
src/GovUk.Education.ExploreEducationStatistics.Admin/Services/ReplacementService.cs

Although a user won't be given the option to remove a Subject when it's already entered the process of being replaced, it's possible that a user might have a view on the remove option for that Subject before the replacement process started.
This PR makes sure that if a Subject is removed and it's associated with an incomplete replacement, that the replacement Subject is also removed.

EES-1417 When removing a Subject also remove any replacement Subject that might exist

---

src/GovUk.Education.ExploreEducationStatistics.Admin/Services/ReplacementService.cs

There was a bug in method `ReplacementService.ValidateFiltersForDataBlock` since a groups filter items aren’t necessarily the same filter items from the data block query.
They will be, the first time the filter group is accessed from a new database context, but they are susceptible to be altered by other database access, for example by getting all the footnotes in a later call, where the FootnotesService.GetBaseFootnoteQuery results in a FilterGroup being populated with FilterItems appearing in footnotes.
This explains why this bug doesn’t happen when there are no footnotes for the original subject.

EES-1434 Filter group should only have filter items of data block

---

src/explore-education-statistics-common/src/components/AccordionSection.module.scss
src/explore-education-statistics-common/src/components/AccordionSection.tsx
src/explore-education-statistics-common/src/components/__tests__/__snapshots__/Accordion.test.tsx.snap
src/explore-education-statistics-common/src/components/__tests__/__snapshots__/AccordionSection.test.tsx.snap

When using the govuk styles alone, content inside the AccordionSection
wouldn't lazy load until the user had interacted with the page - specifically tables and charts. This meant tables and charts would load forever until the user scrolled down the page a little. Using these additional AccordionSection
styles resolves this issue.

EES-1186 Add styles to ensure AccordionSection contents lazy load

---

src/explore-education-statistics-admin/src/pages/release/ReleasePageContainer.tsx
src/explore-education-statistics-admin/src/pages/release/data/ReleaseDataFilePage.tsx
src/explore-education-statistics-admin/src/pages/release/data/ReleaseDataFileReplacementCompletePage.tsx
src/explore-education-statistics-admin/src/pages/release/data/components/DataFileReplacementPlan.tsx
src/explore-education-statistics-admin/src/pages/release/data/components/__tests__/DataFileReplacementPlan.test.tsx
src/explore-education-statistics-admin/src/routes/releaseRoutes.ts

This PR:
- Adds new `ReleaseDataFileReplacementCompletePage` that the user will be redirected to once a data replacement has completed. This shows them the required warning text and lists the data blocks/footnotes that they should check over. Fixes EES-1439.
- Updates wording on the current `DataFileReplacementPlan` to remove mentions of 'valid'. This has been updated to variations of 'replaced by' instead to try prevent setting of false expectations. Fixes EES-1440.

EES-1439, EES-1440 Add replacement completion page and update wording

---

src/explore-education-statistics-admin/src/pages/release/data/ReleaseDataFilePage.tsx
src/explore-education-statistics-admin/src/pages/release/data/__tests__/ReleaseDataFilePage.test.tsx
src/explore-education-statistics-admin/src/pages/release/data/components/ImporterStatus.tsx
src/explore-education-statistics-admin/src/pages/release/data/components/__tests__/ReleaseDataUploadsSection.test.tsx

This PR moves the existing 'Data replacement in progress' tag into the `ImporterStatus` component so that it will be shown anywhere that the data file is in a replacement state i.e.

EES-1427 Move 'Data replacement in progress' tag to ImporterStatus

---

src/explore-education-statistics-admin/src/pages/release/data/components/DataFileDetailsTable.tsx

There was a change in https://github.com/dfe-analytical-services/explore-education-statistics/pull/2013 to remove dedicated endpoints for downloading types of files, replaced by a common endpoint to download any file by its file id.
This PR updates the meta file download links to use the meta file id rather than the corresponding data file id.

EES-1446 Meta file download links need to use the meta file id

---

src/GovUk.Education.ExploreEducationStatistics.Admin.Tests/Services/FileUploadsValidatorServiceTests.cs
src/GovUk.Education.ExploreEducationStatistics.Admin.Tests/Services/ReleaseFilesServiceTests.cs
src/GovUk.Education.ExploreEducationStatistics.Admin/Services/DataArchiveValidationService.cs
src/GovUk.Education.ExploreEducationStatistics.Admin/Services/FileUploadsValidatorService.cs
src/GovUk.Education.ExploreEducationStatistics.Admin/Services/ImportService.cs
src/GovUk.Education.ExploreEducationStatistics.Admin/Services/Interfaces/IDataArchiveValidationService.cs
src/GovUk.Education.ExploreEducationStatistics.Admin/Services/Interfaces/IFileUploadsValidatorService.cs
src/GovUk.Education.ExploreEducationStatistics.Admin/Services/Interfaces/IImportService.cs
src/GovUk.Education.ExploreEducationStatistics.Admin/Services/ReleaseFilesService.cs
src/GovUk.Education.ExploreEducationStatistics.Common/Model/BlobInfo.cs
src/GovUk.Education.ExploreEducationStatistics.Common/Model/DataArchiveFile.cs
src/GovUk.Education.ExploreEducationStatistics.Common/Services/FileStorageUtils.cs
src/GovUk.Education.ExploreEducationStatistics.Content.Model/ReleaseFileReference.cs

This PR fixes the `ReleaseFilesService.UploadDataFilesAsZip` method returning incorrect `DataFileInfo`. We have now adjusted this to return details of the zipped data file instead of the ZIP file itself. This includes the correct subject name and the import status (so 'Not found' will no longer be displayed).
As part of this, we have refactored other service APIs involving `ZipArchiveEntry` parameters to take a `DataArchiveFile` instead. This allows us to more easily mock things for unit tests.

EES-1426 Fix uploaded zip data file returning incorrect details

---

src/GovUk.Education.ExploreEducationStatistics.Admin.Tests/Services/ReleaseFilesServiceTests.cs
src/GovUk.Education.ExploreEducationStatistics.Admin/Services/ReleaseFilesService.cs

This PR:
Corrects the file name that we delete the meta data blob with
Adds unit tests for deleting a Subjects set of files and deleting a Subjects set of files that exist on a previous version.

EES-1449 Delete meta data blob by the correct filename

---

src/GovUk.Education.ExploreEducationStatistics.Admin.Tests/Services/ReleaseFilesServiceTests.cs
src/GovUk.Education.ExploreEducationStatistics.Admin/Services/ReleaseFilesService.cs
src/GovUk.Education.ExploreEducationStatistics.Common/Utils/IPersistenceHelper.cs
src/GovUk.Education.ExploreEducationStatistics.Common/Utils/PersistenceHelper.cs

This PR:
- Fixes `ReleaseFilesService.ListDataFiles` always returning `NOT_FOUND` import statuses for an amendment. This was due to the wrong release id being used when fetching the import status. We have now corrected this to the `ReleaseFileReference.ReleaseId`, which should always allow the file to be found.
- Fixes `ReleaseFilesService.GetDataFile` being able to return a data file for completely different releases. We now check that the file reference id is linked to the release, otherwise, we return a 404.

EES-1455 Fix incorrect import status when listing amendment data files

---

src/GovUk.Education.ExploreEducationStatistics.Admin.Tests/Controllers/Api/DataBlocksControllerTests.cs
src/GovUk.Education.ExploreEducationStatistics.Admin.Tests/Services/ReleaseServiceTests.cs
src/GovUk.Education.ExploreEducationStatistics.Admin/Services/DataBlockService.cs
src/GovUk.Education.ExploreEducationStatistics.Admin/Services/Interfaces/IDataBlockService.cs
src/GovUk.Education.ExploreEducationStatistics.Admin/Services/ReleaseService.cs

This PR:
- Returns the result for removing a replacement data file if it's a failure. This was previously ignored so if the replacement file was still importing the original file continued to be deleted without an error.
- Adds unit tests for removing a data file that is importing
- Adds a unit test for removing a data file with a replacement file that is importing
- Cleans up other unit tests in `ReleaseServiceTests`.

EES-1417 Don't allow deleting a file if a replacement file is still importing

---

src/GovUk.Education.ExploreEducationStatistics.Admin.Tests/Services/ReleaseFilesServiceTests.cs
src/GovUk.Education.ExploreEducationStatistics.Admin/Services/ReleaseFilesService.cs

There was a referential integrity database exception occuring when cancelling a Data Replacement.
Cancelling the replacement in the UI makes an API call to delete the replacement file id.
The exception was occurring because it is still linked to the original file in its `ReplacedBy` field.
When deleting a file, if it has a `Replacing` file then it's a replacement and we find that file and clear the `ReplacedBy` before removing it.

EES-1459 Unlink a replacement release file reference from the original before trying to delete it

---

src/explore-education-statistics-admin/src/pages/release/datablocks/components/ChartBuilderTabSection.tsx
src/explore-education-statistics-admin/src/pages/release/datablocks/components/DataBlockSourceWizard.tsx
src/explore-education-statistics-admin/src/pages/release/datablocks/components/ReleaseDataBlocksPageTabs.tsx
src/explore-education-statistics-admin/src/pages/release/datablocks/components/__tests__/ReleaseDataBlocksPageTabs.test.tsx
src/explore-education-statistics-admin/src/services/dataBlockService.ts
src/explore-education-statistics-common/src/components/Tabs.tsx
src/explore-education-statistics-common/src/components/TabsSection.tsx
src/explore-education-statistics-common/src/components/__tests__/Tabs.test.tsx
src/explore-education-statistics-common/src/modules/table-tool/components/FiltersForm.tsx
src/explore-education-statistics-common/src/modules/table-tool/components/LocationFiltersForm.tsx
src/explore-education-statistics-common/src/modules/table-tool/components/TableToolWizard.tsx
src/explore-education-statistics-common/src/modules/table-tool/components/TimePeriodForm.tsx
src/explore-education-statistics-common/src/modules/table-tool/components/__tests__/FiltersForm.test.tsx
src/explore-education-statistics-common/src/modules/table-tool/components/__tests__/TableToolWizard.test.tsx
src/explore-education-statistics-common/src/modules/table-tool/components/utils/__tests__/getInitialStepSubjectMeta.test.ts
src/explore-education-statistics-common/src/modules/table-tool/components/utils/getInitialStepSubjectMeta.ts
src/explore-education-statistics-common/src/services/logger.ts
src/explore-education-statistics-common/src/services/tableBuilderService.ts
src/explore-education-statistics-frontend/src/modules/find-statistics/PublicationReleaseHelpAndSupportSection.tsx
src/explore-education-statistics-frontend/src/modules/find-statistics/PublicationReleasePage.tsx
src/explore-education-statistics-frontend/src/modules/table-tool/TableToolPage.tsx
src/explore-education-statistics-frontend/src/pages/data-tables/fast-track/[fastTrackId].tsx

This PR adds the ability for the 'Data blocks' page table tool to initialise from an earlier step when we determine that an empty table could be rendered or the table headers may throw an error. Typically, we will send the user back to the locations step (step 2) when there is such a failure.
This isn't the most optimum solution as it doesn't really tell the user what the problem is, and it doesn't take them to the specific step in table tool to rectify the issue. Unfortunately this solution is quite involved and would require a lot more work. We have decided not to go with this for the time being.
- Fixed `Tabs` not being able to conditionally render its tab sections. This previously meant that all of its child sections would need to be rendered as soon as the parent `Tabs` was. We have …

EES-1429 Allow initialisation of data block table tool when table cannot be rendered

---

src/GovUk.Education.ExploreEducationStatistics.Admin.Tests/Services/ReleaseServicePermissionTests.cs
src/GovUk.Education.ExploreEducationStatistics.Admin.Tests/Services/ReleaseServiceTests.cs
src/GovUk.Education.ExploreEducationStatistics.Admin/Controllers/Api/ReleasesController.cs
src/GovUk.Education.ExploreEducationStatistics.Admin/Services/Interfaces/IReleaseService.cs
src/GovUk.Education.ExploreEducationStatistics.Admin/Services/ReleaseService.cs

When an amendment is deleted, delete any files including those belonging to incomplete replacements.
Without doing this, the replacement files would still be tracked as replacing their original files.
If the previous Release was amended again the files would show up as having replacements in progress.
We've also been retaining files unnecessarily when cancelling amendments and a new issue has been opened to clean these up and physically delete Releases rather than soft deleting them.

EES-1457 Delete any replacement file that might exist when deleting an amendment.

---

src/GovUk.Education.ExploreEducationStatistics.Data.Api/Services/PermalinkService.cs
src/GovUk.Education.ExploreEducationStatistics.Data.Api/ViewModels/PermalinkViewModel.cs
src/explore-education-statistics-common/src/components/WarningMessage.module.scss
src/explore-education-statistics-common/src/components/WarningMessage.tsx
src/explore-education-statistics-common/src/modules/table-tool/components/FixedMultiHeaderDataTable.module.scss
src/explore-education-statistics-common/src/modules/table-tool/components/MultiHeaderTable.module.scss
src/explore-education-statistics-common/src/services/permalinkService.ts
src/explore-education-statistics-common/src/styles/_layout.scss
src/explore-education-statistics-common/src/styles/utils/_flex.scss
src/explore-education-statistics-frontend/src/components/PageTitle.tsx
src/explore-education-statistics-frontend/src/modules/permalink/PermalinkPage.tsx
src/explore-education-statistics-frontend/src/modules/permalink/__tests__/PermalinkPage.test.tsx

This PR adds the following warning message to permalinks when they are invalidated by a data replacement or file deletion in an amendment:
- Cleaned up various markup and styling across `PermalinkPage`.
- Fixed wide pages being too wide for printing.

EES-214 Add warning message when permalinks are invalidated

---

src/explore-education-statistics-common/src/modules/table-tool/components/FormFieldSortableList.tsx
src/explore-education-statistics-common/src/modules/table-tool/components/FormFieldSortableListGroup.tsx
src/explore-education-statistics-common/src/modules/table-tool/components/FormSortableList.tsx

This PR fixes inconsistent behaviour when trying to drag table headers. Roughly half the time, the parent table header group (in `FormFieldSortableListGroup`) would be dragged instead of its child table headers (in `FormSortableList`), leading to a sub-optimal user experience.
We simply disable the table header group from being dragged whilst the user's mouse is over any of the table headers.

EES-711 Fix inconsistent dragging behaviour of table headers

---

src/explore-education-statistics-common/package-lock.json

This PR removes the unnecessary `history` dependency from the common module.

EES-1464 Remove `history` from common package-lock.json

---

infrastructure/templates/datafactory/components/template.json
src/GovUk.Education.ExploreEducationStatistics.Admin.Tests/Services/MetaGuidanceServicePermissionTests.cs
src/GovUk.Education.ExploreEducationStatistics.Admin.Tests/Services/MetaGuidanceServiceTests.cs
src/GovUk.Education.ExploreEducationStatistics.Admin/Controllers/Api/MetaGuidanceController.cs
src/GovUk.Education.ExploreEducationStatistics.Admin/Migrations/ContentMigrations/20201008104504_EES1409AddMetaGuidanceFieldToRelease.Designer.cs
src/GovUk.Education.ExploreEducationStatistics.Admin/Migrations/ContentMigrations/20201008104504_EES1409AddMetaGuidanceFieldToRelease.cs
src/GovUk.Education.ExploreEducationStatistics.Admin/Services/Interfaces/IMetaGuidanceService.cs
src/GovUk.Education.ExploreEducationStatistics.Admin/Services/MetaGuidanceService.cs
src/GovUk.Education.ExploreEducationStatistics.Admin/Startup.cs
src/GovUk.Education.ExploreEducationStatistics.Admin/ViewModels/MetaGuidanceViewModel.cs
src/GovUk.Education.ExploreEducationStatistics.Common/Model/LabelValue.cs
src/GovUk.Education.ExploreEducationStatistics.Content.Model/Release.cs
src/GovUk.Education.ExploreEducationStatistics.Data.Model/Migrations/20201008103731_EES1409AddMetaGuidanceFieldToSubject.Designer.cs
src/GovUk.Education.ExploreEducationStatistics.Data.Model/Migrations/20201008103731_EES1409AddMetaGuidanceFieldToSubject.cs
src/GovUk.Education.ExploreEducationStatistics.Data.Model/Migrations/20201009100336_EES1409AddMetaGuidanceFieldToReleaseSubject.Designer.cs
src/GovUk.Education.ExploreEducationStatistics.Data.Model/Migrations/20201009100336_EES1409AddMetaGuidanceFieldToReleaseSubject.cs
src/GovUk.Education.ExploreEducationStatistics.Data.Model/Migrations/StatisticsDbContextModelSnapshot.cs
src/GovUk.Education.ExploreEducationStatistics.Data.Model/ReleaseSubject.cs
src/GovUk.Education.ExploreEducationStatistics.Data.Model/Subject.cs

This PR adds the API endpoints to get and update Meta Guidance for Release and Subjects
`GET {{admin_api_url}}/release/{releaseId}/meta-guidance`
`PUT {{admin_api_url}}/release/{releaseId}/meta-guidance`
`PUT {{admin_api_url}}/release/{releaseId}/meta-guidance/subject/{subjectId}`
Each of these requests returns a common Meta Guidance response containing
- Guidance text for the Release
- List of Subjects (sorted by name) containing:
- Guidance text for the Subject
- Filename
- Name
- Time Periods
- Geographic Levels
- List of Filter and Indicator column names with descriptions
```
{
"id": "ea72ef7a-e357-479d-1fc7-08d86c4b2553",
"content": "Guidance text for the Release",
"subjects": [
{
"id": "9e8b9d66-bec9-49f5-80a4-08d86c4c75f9",
"filename": "data.csv",
"name": "Test Data Subject", …
```

EES-1409 EES-1410 Add API to get and update Meta Guidance for Release and Subjects

---

src/GovUk.Education.ExploreEducationStatistics.Content.Api/Models/ReleaseViewModel.cs
src/GovUk.Education.ExploreEducationStatistics.Publisher.Model/ViewModels/CachedReleaseViewModel.cs
src/GovUk.Education.ExploreEducationStatistics.Publisher.Tests/Services/ReleaseServiceTests.cs

Depends on https://github.com/dfe-analytical-services/explore-education-statistics/pull/2059
This PR adds the new Release.MetaGudiance field to the serialized Release that is stored in the public content storage account.

EES-1480 Add Release.MetaGudiance to serialized Release

---

src/GovUk.Education.ExploreEducationStatistics.Admin.Tests/Services/ReleaseMetaServicePermissionTests.cs
src/GovUk.Education.ExploreEducationStatistics.Admin.Tests/Services/ReleaseMetaServiceTests.cs
src/GovUk.Education.ExploreEducationStatistics.Admin/Services/ReleaseMetaService.cs
src/GovUk.Education.ExploreEducationStatistics.Common/Extensions/EnumerableExtensions.cs
src/explore-education-statistics-admin/src/pages/release/datablocks/components/DataBlockSourceWizard.tsx
src/explore-education-statistics-admin/src/pages/release/datablocks/components/ReleaseDataBlocksPageTabs.tsx
src/explore-education-statistics-common/src/modules/table-tool/components/TableToolWizard.tsx
src/explore-education-statistics-common/src/modules/table-tool/components/__tests__/TableToolWizard.test.tsx
src/explore-education-statistics-common/src/services/fastTrackService.ts
src/explore-education-statistics-frontend/src/modules/table-tool/TableToolPage.tsx
src/explore-education-statistics-frontend/src/pages/data-tables/fast-track/[fastTrackId].tsx
tests/robot-tests/tests/admin_and_public/bau/footnotes.robot
tests/robot-tests/tests/admin_and_public/bau/publish_data.robot
tests/robot-tests/tests/admin_and_public/bau/publish_release_and_amend.robot
tests/robot-tests/tests/general_public/release_page_absence.robot
tests/robot-tests/tests/libs/common.robot
tests/robot-tests/tests/libs/public-common.robot
tests/robot-tests/tests/libs/utilities.py

This PR filters out subjects that are in the middle of importing from displaying on the 'Data blocks' page table tool. This prevents the user from being able to select them and be presented with the second step in an incorrect state.
- Refactored all of `TableToolWizard`'s internal state so that it can be passed in via the `initialState` prop. This allows us to completely control the initial state from the parent component and allows us to only render `TableToolWizard` when its initial state has all been fetched. This change has mostly been done to avoid the initial step momentarily showing empty state whilst the meta is still being fetched.

EES-372 Filter out subjects that are importing from table tool

---

src/GovUk.Education.ExploreEducationStatistics.Admin.Tests/Services/MetaGuidanceServiceTests.cs
src/GovUk.Education.ExploreEducationStatistics.Admin/Services/MetaGuidanceService.cs
src/GovUk.Education.ExploreEducationStatistics.Admin/ViewModels/MetaGuidanceViewModel.cs

- Don't await multiple tasks when building Subject view models since this involves multiple database calls and DbContext is not thread safe and results in an error getting the Subject Guidance for a Release with multiple Subjects.
- Fix a performance issue getting Subject time period of large subjects by limiting the database query to the time period fields.
- Serialize GeographicLevel as String label in the view model response.

EES-1409 Multiple Subject Guidance API bug fixes

---

src/explore-education-statistics-admin/src/pages/admin-dashboard/components/PublicationSummary.tsx

This PR changes `PublicationSummary` so that it no longer renders the external mehodology URL. Long URLs were causing the`SummaryListItem` action column to be pushed out of the page, making it difficult to change the publication details. We've changed this so that it just displays the following:

EES-1398 Fix PublicationSummary rendering long external methodology URLs

---

src/explore-education-statistics-frontend/src/modules/table-tool/TableToolPage.tsx
tests/robot-tests/tests/general_public/table_tool_exclusions_by_geographic_level.robot

This PR fixes `/data-tables` on the public frontend throwing a JSON serialization error on 'undefined' when running the development server. Notably, it's a bit unfortunate that this only happens in development as it means that the UI tests can't actually catch this kind of problem.

EES-372 Fix /data-tables throwing serialization error in development

---

src/GovUk.Education.ExploreEducationStatistics.Data.Services.Tests/MetaGuidanceSubjectServiceTests.cs
src/GovUk.Education.ExploreEducationStatistics.Data.Services/MetaGuidanceSubjectService.cs

When getting the meta guidance Subject view models for a Release we are checking first that the Release exists before executing the body of the code.
This PR makes a change to not execute the body but instead handle a failure when the Release doesn't exist and succeed with an empty list.
This is because the Statistics database Releases are not always in sync with Content database Releases.
For example until the first Subject is imported, no StatisticsDb Release exists.
When used by the Public Content API, the only database available is the Statistics database.
It might be possible to improve this in future if the Public Content API using this service is granted access to both databases.

EES-1481 Allow no Release to exist when databases are not in sync.

---

src/GovUk.Education.ExploreEducationStatistics.Admin.Tests/Services/MetaGuidanceServiceTests.cs
src/GovUk.Education.ExploreEducationStatistics.Admin.Tests/Services/ReleaseServiceAmendmentTests.cs
src/GovUk.Education.ExploreEducationStatistics.Admin.Tests/Services/ReleaseServicePermissionTests.cs
src/GovUk.Education.ExploreEducationStatistics.Admin.Tests/Services/ReleaseServiceTests.cs
src/GovUk.Education.ExploreEducationStatistics.Admin/Services/Interfaces/IMetaGuidanceService.cs
src/GovUk.Education.ExploreEducationStatistics.Admin/Services/MetaGuidanceService.cs
src/GovUk.Education.ExploreEducationStatistics.Admin/Services/ReleaseService.cs
src/GovUk.Education.ExploreEducationStatistics.Admin/Validators/ValidationUtils.cs
src/GovUk.Education.ExploreEducationStatistics.Data.Services.Tests/MetaGuidanceSubjectServiceTests.cs
src/GovUk.Education.ExploreEducationStatistics.Data.Services/Interfaces/IMetaGuidanceSubjectService.cs
src/GovUk.Education.ExploreEducationStatistics.Data.Services/MetaGuidanceSubjectService.cs
src/explore-education-statistics-admin/src/pages/release/ReleaseStatusPage.tsx

This alters the approval validation when changing the status of a Release to check that the public meta guidance document has been populated with content for the Release and content for every Subject.
If there are no data files the validation is skipped completely as the user is not asked to enter the Release level guidance.

EES-1412 Prevent approval if meta guidance isn't populated.

---

src/GovUk.Education.ExploreEducationStatistics.Admin.Tests/Services/ReleaseFilesServiceTests.cs
src/GovUk.Education.ExploreEducationStatistics.Admin.Tests/Services/ReplacementServiceTests.cs
src/GovUk.Education.ExploreEducationStatistics.Admin/Areas/Identity/Pages/Account/Login.cshtml.cs
src/GovUk.Education.ExploreEducationStatistics.Admin/Areas/Identity/Pages/Account/Manage/EnableAuthenticator.cshtml.cs
src/GovUk.Education.ExploreEducationStatistics.Admin/Areas/Identity/Pages/Error.cshtml.cs
src/GovUk.Education.ExploreEducationStatistics.Admin/Models/ErrorViewModel.cs
src/GovUk.Education.ExploreEducationStatistics.Admin/Pages/Error.cshtml.cs
src/GovUk.Education.ExploreEducationStatistics.Admin/Services/ImportService.cs
src/GovUk.Education.ExploreEducationStatistics.Admin/Services/Interfaces/IImportService.cs
src/GovUk.Education.ExploreEducationStatistics.Admin/Services/MetaGuidanceService.cs
src/GovUk.Education.ExploreEducationStatistics.Admin/Services/ReleaseFilesService.cs
src/GovUk.Education.ExploreEducationStatistics.Admin/Services/ReplacementService.cs
src/GovUk.Education.ExploreEducationStatistics.Admin/ViewModels/DataReplacementPlanViewModel.cs
src/GovUk.Education.ExploreEducationStatistics.Admin/ViewModels/ReleaseViewModels.cs
src/GovUk.Education.ExploreEducationStatistics.Common.Tests/Extensions/StringExtensionTests.cs
src/GovUk.Education.ExploreEducationStatistics.Common/Extensions/StringExtensions.cs
src/GovUk.Education.ExploreEducationStatistics.Common/Functions/ConnectionUtils.cs
src/GovUk.Education.ExploreEducationStatistics.Data.Model/LocalAuthority.cs
src/GovUk.Education.ExploreEducationStatistics.Data.Processor/Services/ReleaseProcessorService.cs

When confirming a Subject replacement we now copy the meta guidance of the original Subject to retain it.
I originally implemented this so that it was retained when importing the replacement but this gave a chance for users to alter the guidance on the original Subject before confirming the replacement, which could have led to lost updates.

EES-1541 Retain Subject meta guidance when replacing Subject

---

src/GovUk.Education.ExploreEducationStatistics.Admin.Tests/Services/ReleaseServiceTests.cs
src/GovUk.Education.ExploreEducationStatistics.Admin/Services/ReleaseService.cs
src/GovUk.Education.ExploreEducationStatistics.Admin/Validators/ValidationUtils.cs
src/explore-education-statistics-admin/src/pages/release/ReleaseStatusPage.tsx

This PR adds validation to stop a Release being approved if data replacement(s) are in progress. This was previously not checked allowing the temporary replacement file to be published in addition to the original file.

EES-1546 Don't allow approval if data replacements are in progress

---

src/GovUk.Education.ExploreEducationStatistics.Admin.Tests/Services/MetaGuidanceServiceTests.cs
src/GovUk.Education.ExploreEducationStatistics.Admin/Services/MetaGuidanceService.cs
src/GovUk.Education.ExploreEducationStatistics.Content.Api.Tests/Services/MetaGuidanceServiceTests.cs
src/GovUk.Education.ExploreEducationStatistics.Data.Services.Tests/MetaGuidanceSubjectServiceTests.cs
src/GovUk.Education.ExploreEducationStatistics.Data.Services/Interfaces/IMetaGuidanceSubjectService.cs
src/GovUk.Education.ExploreEducationStatistics.Data.Services/MetaGuidanceSubjectService.cs

This PR excludes subjects that are uploaded while a replacement is in progress from the Meta guidance tab and Admin Meta guidance content preview.
The Public Content API continues to retrieve meta guidance for all subjects belonging to the Release.

EES-1532 Exclude subjects that are uploaded while a replacement is in progress from Meta guidance

---

src/GovUk.Education.ExploreEducationStatistics.Admin.Tests/Services/PublishingServiceTests.cs
src/GovUk.Education.ExploreEducationStatistics.Admin/Services/PublishingService.cs
src/GovUk.Education.ExploreEducationStatistics.Common/Services/Interfaces/IStorageQueueService.cs
src/GovUk.Education.ExploreEducationStatistics.Common/Services/StorageQueueService.cs
src/GovUk.Education.ExploreEducationStatistics.Content.Api/Startup.cs
src/GovUk.Education.ExploreEducationStatistics.Notifier/local.settings.json
src/GovUk.Education.ExploreEducationStatistics.Publisher/Services/NotificationsService.cs
src/GovUk.Education.ExploreEducationStatistics.Publisher/Services/QueueService.cs

This PR add a `AddMessagesAsync(IEnumerable<object> value)` overload to `StorageQueueService.AddMessagesAsync` to avoid the compiler treating an `IEnumerable<object>` of messages as single valued object array with the existing method `AddMessagesAsync(params object[] values)`.
This was resulting in us serializing the IEnumerable as a single message body, rather than queuing individual messages for each value.
For consistency we also add this to the non-async method `StorageQueueService.AddMessages`.

EES-1550 Fix Publisher sending notifications when Releases are published

---

src/GovUk.Education.ExploreEducationStatistics.Admin/Services/ReleaseService.cs
src/GovUk.Education.ExploreEducationStatistics.Content.Api.Tests/Services/MetaGuidanceServiceTests.cs
src/GovUk.Education.ExploreEducationStatistics.Content.Api/Controllers/MetaGuidanceController.cs
src/GovUk.Education.ExploreEducationStatistics.Content.Api/Controllers/PreReleaseAccessListController.cs
src/GovUk.Education.ExploreEducationStatistics.Content.Api/Controllers/ReleaseController.cs
src/GovUk.Education.ExploreEducationStatistics.Content.Api/Services/Interfaces/IMetaGuidanceService.cs
src/GovUk.Education.ExploreEducationStatistics.Content.Api/Services/MetaGuidanceService.cs
src/GovUk.Education.ExploreEducationStatistics.Content.Api/ViewModels/MetaGuidanceViewModel.cs
src/GovUk.Education.ExploreEducationStatistics.Data.Model/ReleaseSubject.cs
src/explore-education-statistics-admin/src/pages/release/ReleaseMetaGuidancePage.tsx
src/explore-education-statistics-admin/src/pages/release/data/components/ReleaseMetaGuidanceSection.tsx
src/explore-education-statistics-admin/src/services/releaseMetaGuidanceService.ts
src/explore-education-statistics-common/src/modules/release/components/ReleaseMetaGuidanceDataFile.tsx
src/explore-education-statistics-common/src/modules/release/components/ReleaseMetaGuidancePageContent.tsx
src/explore-education-statistics-common/src/modules/release/components/__tests__/ReleaseMetaGuidancePageContent.test.tsx
src/explore-education-statistics-common/src/services/releaseMetaGuidanceService.ts
src/explore-education-statistics-frontend/src/modules/find-statistics/PreReleaseAccessListPage.tsx
src/explore-education-statistics-frontend/src/modules/find-statistics/PublicationReleasePage.tsx
src/explore-education-statistics-frontend/src/modules/find-statistics/ReleaseMetaGuidancePage.tsx
src/explore-education-statistics-frontend/src/pages/find-statistics/[publication]/[release]/meta-guidance.tsx
src/explore-education-statistics-frontend/src/pages/find-statistics/[publication]/meta-guidance.tsx
tests/robot-tests/tests/admin_and_public/bau/publish_release_and_amend.robot
tests/robot-tests/tests/libs/public-common.robot

This PR adds the public metadata guidance page, completing the end-to-end journey. Users can access it in the same place as the Pre-release access list in the 'Download associated files' details dropdown on a release.
- Modifies meta guidance endpoints to include the publication slug as we need this to be able to fetch the correct publication details to include in the `MetaGuidanceViewModel`. This just extends `ReleaseSummaryViewModel` so that the frontend can conveniently display all of its requirements using a single request.
- Adds new endpoint for getting the latest release's meta guidance from `/publications/{publicationSlug}/releases/latest/meta-guidance`. This is used by the `ReleaseMetaGuidancePage` when no release slug is specified.
- Fixes `ReleaseSubjects` for amendments having …

EES-1416 Add metadata guidance page to public frontend

---

tests/robot-tests/tests/admin_and_public/bau/publish_release_and_amend.robot
tests/robot-tests/tests/libs/admin-common.robot

This PR simply updates the meta guidance editor keywords to use the `user enters text into element` keyword internally. This is beneficial as it automatically handles clearing of the editor element before typing the text.

EES-1416 Use `user enter text into element` for meta guidance editor tests

---

src/GovUk.Education.ExploreEducationStatistics.Admin.Tests/Services/ThemeServicePermissionTests.cs
src/GovUk.Education.ExploreEducationStatistics.Admin.Tests/Services/ThemeServiceTests.cs
src/GovUk.Education.ExploreEducationStatistics.Admin.Tests/Services/TopicServicePermissionTests.cs
src/GovUk.Education.ExploreEducationStatistics.Admin.Tests/Services/TopicServiceTests.cs
src/GovUk.Education.ExploreEducationStatistics.Admin/Services/Interfaces/IPublishingService.cs
src/GovUk.Education.ExploreEducationStatistics.Admin/Services/PublishingService.cs
src/GovUk.Education.ExploreEducationStatistics.Admin/Services/ThemeService.cs
src/GovUk.Education.ExploreEducationStatistics.Admin/Services/TopicService.cs
src/GovUk.Education.ExploreEducationStatistics.Publisher.Model/PublishTaxonomyMessage.cs
src/GovUk.Education.ExploreEducationStatistics.Publisher.Model/PublisherQueues.cs
src/GovUk.Education.ExploreEducationStatistics.Publisher/Functions/PublishTaxonomyFunction.cs
src/GovUk.Education.ExploreEducationStatistics.Publisher/Services/ContentService.cs
src/GovUk.Education.ExploreEducationStatistics.Publisher/Services/Interfaces/IContentService.cs

This PR adds a new `PublishTaxonomyFunction` that is used to update the respective content trees whenever a theme or topic is created, updated or deleted. This should allow users to update the taxonomy without needing to republish a release or update a publication.
Identified that the content blob store must be the source of UI test flakiness when run in parallel. UI tests that involve publishing content to the public will typically have intermittent failures when verifying that the correct publication(s) are in the theme trees. This is most likely down to interleaving of publishing tasks that trigger tree regeneration.
In these cases, it's possible for a task to generate a tree using stale content database data and then overwrite a more up-to-date tree (generated by another task). This …

EES-1293 Add PublishTaxonomy function to update content themes/topics when changed

---

src/GovUk.Education.ExploreEducationStatistics.Admin.Tests/Services/DbUtils.cs
src/GovUk.Education.ExploreEducationStatistics.Content.Model/Database/ContentDbUtils.cs
src/GovUk.Education.ExploreEducationStatistics.Content.Model/GovUk.Education.ExploreEducationStatistics.Content.Model.csproj
src/GovUk.Education.ExploreEducationStatistics.Data.Model/Theme.cs
src/GovUk.Education.ExploreEducationStatistics.Publisher.Tests/Services/PublicationServiceTests.cs
src/GovUk.Education.ExploreEducationStatistics.Publisher.Tests/Services/TaxonomyServiceTests.cs
src/GovUk.Education.ExploreEducationStatistics.Publisher/Functions/PublishTaxonomyFunction.cs
src/GovUk.Education.ExploreEducationStatistics.Publisher/MappingProfiles.cs
src/GovUk.Education.ExploreEducationStatistics.Publisher/Services/Interfaces/ITaxonomyService.cs
src/GovUk.Education.ExploreEducationStatistics.Publisher/Services/PublicationService.cs
src/GovUk.Education.ExploreEducationStatistics.Publisher/Services/TaxonomyService.cs
src/GovUk.Education.ExploreEducationStatistics.Publisher/Startup.cs

This PR:
- Adds additional syncing functionality to ensure that changes to the content DB taxonomy also updates the statistics DB taxonomy as well. Synchronization means that we add, update and remove themes/topics as required to ensure that they match each other.
- Fixes changes to content DB's publication also not being synced to the statistics DB.
- As part of the synchronization, we remove themes/topics that are no longer in the content DB. This unlikely to happen unless you delete a theme/topic in the admin (via API), however, it could theoretically happen if you manually modify the database tables (definitely not advised).
- If themes/topics were removed during synchronization, to make sure everything was cleaned up properly we would also need to delete relevant subjects/files …

EES-1293 Sync content DB taxonomy with stats DB on change

---

src/explore-education-statistics-common/src/components/SanitizeHtml.tsx
src/explore-education-statistics-common/src/utils/sanitizeHtml.ts
src/explore-education-statistics-frontend/src/modules/glossary/GlossaryPage.tsx

This PR allows links in the Glossary to have `target` and `rel` attributes so that they can open up in a new browser tab (particularly useful for external links).

EES-1557 Allow glossary links to have `target` and `rel` attributes

---

infrastructure/templates/template.json

This should fix the "Only a maximum of 15 tags are supported per resource" failure on the deploy of all three DBs.

EES-1380 Update apiVersion for all DBs

---

src/GovUk.Education.ExploreEducationStatistics.Content.Model.Tests/ReleaseTests.cs
src/GovUk.Education.ExploreEducationStatistics.Content.Model/ContentBlock.cs
src/GovUk.Education.ExploreEducationStatistics.Content.Model/ContentSection.cs
src/GovUk.Education.ExploreEducationStatistics.Content.Model/Link.cs
src/GovUk.Education.ExploreEducationStatistics.Content.Model/Release.cs
src/GovUk.Education.ExploreEducationStatistics.Content.Model/ReleaseContentBlock.cs
src/GovUk.Education.ExploreEducationStatistics.Content.Model/ReleaseContentSection.cs
src/GovUk.Education.ExploreEducationStatistics.Content.Model/Update.cs

This PR updates content sections with new fast track links when an amendment is created. We have implemented this with a simple search and replace, which should be sufficient for the time being.
- Cleaned up `Release.CreateReleaseAmendment` method. This has involved removing any unnecessary parts from the `CloneContext` (now a nested class on `Release`). Ideally we want to be able to remove this completely, but we need to make some adjustments to the content DB schema first to avoid the same data block references being in multiple places.

EES-1420 Update amendment content with new fast track links

---

src/GovUk.Education.ExploreEducationStatistics.Data.Services.Tests/MetaGuidanceSubjectServiceTests.cs
src/GovUk.Education.ExploreEducationStatistics.Data.Services/MetaGuidanceSubjectService.cs
src/explore-education-statistics-common/src/components/SummaryListItem.tsx
src/explore-education-statistics-common/src/modules/release/components/ReleaseMetaGuidanceDataFile.tsx
src/explore-education-statistics-common/src/modules/release/components/ReleaseMetaGuidancePageContent.tsx
src/explore-education-statistics-common/src/modules/release/components/__tests__/ReleaseMetaGuidancePageContent.test.tsx

This PR:
- Fixes empty meta guidance content and file content incorrectly rendering (EES-1574)
- Fixes empty subject time periods and geographic levels incorrectly rendering (EES-1575)
- Orders meta guidance subjects alphabetically by name (EES-1576)

EES-1574, EES-1575, EES-1576 Fixes for meta guidance content

---

src/GovUk.Education.ExploreEducationStatistics.Common.Tests/Services/ImportStatusServiceTests.cs
src/GovUk.Education.ExploreEducationStatistics.Common/Model/ImportStatus.cs
src/GovUk.Education.ExploreEducationStatistics.Common/Services/ImportStatusService.cs
src/GovUk.Education.ExploreEducationStatistics.Data.Processor/host.json

This PR:
Adds logging so we can see progress updates e.g. `Update: spc_pupils_fsm_eth_lang.csv STAGE_4 (88%) -> STAGE_4 (91%)`
Adds logging so we can see status updates e.g. `spc_pupils_fsm_eth_lang.csv STAGE_4 (97%) -> COMPLETE (100%)`
Adds logging so we can see lost updates e.g. `Precondition failure as expected while updating progress. ETag does not match for update: spc_pupils_fsm_eth_lang.csv STAGE_4 (93%) -> STAGE_4 (97%)`
Throw exceptions occurring for reasons other than optimistic locking when updating status or progress of imports.
Alters logging categories so all services are included by default at Information level.

EES-1578 Add logging and alter exception handling when updating import status and progress values

---

src/GovUk.Education.ExploreEducationStatistics.Common.Tests/Services/ImportStatusServiceTests.cs
src/GovUk.Education.ExploreEducationStatistics.Common/Services/ImportStatusService.cs
src/GovUk.Education.ExploreEducationStatistics.Common/Services/Interfaces/IImportStatusService.cs

* Retry up to 5 times when updating status or progress if an import status row has been changed by a concurrent update.
* Ignore status updates to a lesser status than the existing one, for example, `Stage 4 -> Stage 3` and `Complete -> Stage 4` would both be ignored

EES-1578 Retry when updating import statuses if an import was changed by a concurrent update

---

src/explore-education-statistics-frontend/src/modules/glossary/GlossaryPage.tsx
src/explore-education-statistics-frontend/src/pages/glossary.tsx

This PR re-jigs the glossary page so that the entries are sanitized at build time (using the `sanitizeHtml` function), rather than at run time (using the `SanitizeHtml` component). 
This allows for a decent ~25% reduction in JS bundle size:
Before: 226 kB 
After: 170 kB

EES-1557 Optimize glossary page bundle size

---

src/explore-education-statistics-admin/src/routes/methodologyRoutes.ts

There is a UI test failing when approving a newly created methodology because it expects the 'status' tab label to be 'Sign off' rather than 'Release status'. This change updates the label to 'Sign off', matching the terminology used when managing Release content.

EES-1587 Alter title to Sign off to match the same label when managing content for Releases

---

src/GovUk.Education.ExploreEducationStatistics.Common.Tests/Services/ImportStatusServiceTests.cs
src/GovUk.Education.ExploreEducationStatistics.Common/Services/BlobStorageService.cs
src/GovUk.Education.ExploreEducationStatistics.Common/Services/ImportStatusService.cs
src/GovUk.Education.ExploreEducationStatistics.Common/Services/Interfaces/IImportStatusService.cs
src/GovUk.Education.ExploreEducationStatistics.Data.Importer/Services/ImporterService.cs
src/GovUk.Education.ExploreEducationStatistics.Data.Processor/Services/FileImportService.cs
src/GovUk.Education.ExploreEducationStatistics.Data.Processor/Services/SplitFileService.cs
src/GovUk.Education.ExploreEducationStatistics.Data.Processor/Services/ValidatorService.cs

Previously there were two different methods for `UpdateStatus` and `UpdateProgress`, and `UpdateProgress` did not check the existing status matched the intended status of the calling code doing the update.
When updating the Percentage Complete value in a `DatafileImport` row in Azure Table Storage, always set Status and Percentage Complete together so that there is no chance of to inadvertently writing a percentage value for a different phase and corrupting it.

EES-1578 Allow updating Status and Percentage Complete together

---

src/GovUk.Education.ExploreEducationStatistics.Admin.Tests/Services/FileUploadsValidatorServiceTests.cs
src/GovUk.Education.ExploreEducationStatistics.Admin.Tests/Services/ReleaseDataFileServiceTest.cs
src/GovUk.Education.ExploreEducationStatistics.Admin.Tests/Services/ReleaseServiceTests.cs
src/GovUk.Education.ExploreEducationStatistics.Admin.Tests/Services/ReleaseSubjectServiceTests.cs
src/GovUk.Education.ExploreEducationStatistics.Admin/Services/FileUploadsValidatorService.cs
src/GovUk.Education.ExploreEducationStatistics.Admin/Services/ReleaseDataFileService.cs
src/GovUk.Education.ExploreEducationStatistics.Admin/Services/ReleaseService.cs
src/GovUk.Education.ExploreEducationStatistics.Admin/Services/TopicService.cs
src/GovUk.Education.ExploreEducationStatistics.Data.Api/Services/FastTrackService.cs
src/GovUk.Education.ExploreEducationStatistics.Data.Api/Services/PermalinkService.cs
src/GovUk.Education.ExploreEducationStatistics.Data.Model.Tests/SubjectServiceTests.cs
src/GovUk.Education.ExploreEducationStatistics.Data.Model/Services/FootnoteService.cs
src/GovUk.Education.ExploreEducationStatistics.Data.Model/Services/Interfaces/IReleaseSubjectService.cs
src/GovUk.Education.ExploreEducationStatistics.Data.Model/Services/Interfaces/ISubjectService.cs
src/GovUk.Education.ExploreEducationStatistics.Data.Model/Services/ReleaseSubjectService.cs
src/GovUk.Education.ExploreEducationStatistics.Data.Model/Services/SubjectService.cs
src/GovUk.Education.ExploreEducationStatistics.Data.Services/PublicationMetaService.cs
src/GovUk.Education.ExploreEducationStatistics.Data.Services/ResultSubjectMetaService.cs
src/GovUk.Education.ExploreEducationStatistics.Data.Services/TableBuilderService.cs
src/GovUk.Education.ExploreEducationStatistics.Publisher/Services/ReleaseService.cs
tests/robot-tests/tests/admin_and_public/bau/create_amendment_check_permalink.robot

This PR fixes permalinks throwing error when a subject has been replaced. When building the permalink view model, we now do an additional check to ensure that the subject actually exists before calling the `SubjectService.IsSubjectForLatestPublishedRelease` method (was previously throwing as the subject could not be found).
Interestingly, this was only happening on non-local environments. I'm not 100% why this occurs, but it's probably because of the specific interaction between data factory and the public stats DB.
- Cleaned up `ReleaseSubjectService`, simplfying methods and their names, and updating the orphaned subject check to use the most up-to-date `ReleaseSubjects`.

EES-1570 Fix permalink throwing error when subject has been replaced in amendment

---

src/GovUk.Education.ExploreEducationStatistics.Data.Api/Services/PermalinkService.cs
src/GovUk.Education.ExploreEducationStatistics.Data.Api/ViewModels/TableBuilderQueryViewModel.cs
src/GovUk.Education.ExploreEducationStatistics.Data.Model.Tests/SubjectServiceTests.cs
src/GovUk.Education.ExploreEducationStatistics.Data.Model/Services/Interfaces/ISubjectService.cs
src/GovUk.Education.ExploreEducationStatistics.Data.Model/Services/SubjectService.cs

This PR allows the permalink `Query.PublicationId` to be set to null as there will no longer be any link back to the Publication in the ticket's scenario. To enable this, we have added a `SubjectService.FindPublicationForSubject` method that returns the nullable Publication (instead of throwing when there is none).

EES-1570 Allow Permalink query's `PublicationId` to be nullable

---

src/GovUk.Education.ExploreEducationStatistics.Data.Model/Services/ReleaseSubjectService.cs

This changes the deletion of orphaned subjects so that they are untracked by EF beforehand. This stops EF trying to cascade the delete to related entities, such as Filters and Observations, in the wrong order.
Instead, we just execute the deletion of the subject by itself and let the database-level cascades handle the rest.

EES-1604 Fix UI test teardown throwing foreign key constraint error

---

src/explore-education-statistics-common/src/modules/charts/components/MapBlock.module.scss
src/explore-education-statistics-common/src/modules/charts/components/MapBlockInternal.tsx

This change prevents map tooltips with lots of content from becoming toowide for the map container. This bug would typically make it really hardto use the map as most of the tooltip content could be shifted out of the map pane.

EES-92 Fix map tooltips becoming too wide for map container

---

src/GovUk.Education.ExploreEducationStatistics.Admin.Tests/Services/MockUtils.cs
src/GovUk.Education.ExploreEducationStatistics.Common/Model/ImportStatus.cs
src/GovUk.Education.ExploreEducationStatistics.Data.Processor.Tests/Functions/ProcessorTests.cs
src/GovUk.Education.ExploreEducationStatistics.Data.Processor.Tests/GovUk.Education.ExploreEducationStatistics.Data.Processor.Tests.csproj
src/GovUk.Education.ExploreEducationStatistics.Data.Processor/Functions/Processor.cs
src/GovUk.Education.ExploreEducationStatistics.Data.Processor/Services/Interfaces/IProcessorService.cs
src/GovUk.Education.ExploreEducationStatistics.Data.Processor/Services/ProcessorService.cs
src/GovUk.Education.ExploreEducationStatistics.Data.Processor/Services/SplitFileService.cs
src/GovUk.Education.ExploreEducationStatistics.Data.Processor/Services/ValidatorService.cs
src/GovUk.Education.ExploreEducationStatistics.Data.Processor/Startup.cs
src/GovUk.Education.ExploreEducationStatistics.sln

This PR: 
- adds a new "Processor.Tests" project to the EES solution
- refactors Processor.cs to execute stages for an importing file in a more granular way, processing a stage at a time for an importing file (rather than running through multiple consecutive stages in one go), then posting a new Queue message to initiate the next stage.  This makes it easier to test and brings it more in line with the expectations of ImportRecoveryHandler, which expects to be able to simply post a message of an interrupted import to the "imports-pending" queue, and have it pick up on the current stage of import based purely on the ImportStatus record of that file
- adds a ProcessorTests test suite to test the refactored Processor
- fixes a race condition between Processor and BatchService, whereby they …

Ees 1606 create tests project for processor

---

src/GovUk.Education.ExploreEducationStatistics.Data.Model/Database/StatisticsDbContext.cs
src/GovUk.Education.ExploreEducationStatistics.Data.Model/Location.cs
src/GovUk.Education.ExploreEducationStatistics.Data.Model/Migrations/20201120112425_EES1615RemoveCascadeDeleteBetweenLocationAndObservation.Designer.cs
src/GovUk.Education.ExploreEducationStatistics.Data.Model/Migrations/20201120112425_EES1615RemoveCascadeDeleteBetweenLocationAndObservation.cs

This PR removes the cascade delete operation in the one-to-many relationship, `Location-Observation`.
Currently deleting Location (parent) will delete all the associated Observations (children) as the relationship had the default Cascade delete strategy.
This could have had potentially catastrophic consequences if somebody deleted a Location thinking it's either unused by any Observations when it's not, or expected the delete to fail if it's used by any Observations, which it won't.

EES-1615 Prevent cascade delete in one-to-many relationship between Location and Observations.

---

infrastructure/templates/datafactory/components/db-maintenance-template.json

With the ARM template infrastructure deploy, the triggers triggers can only be deployed in a stopped state.
See https://github.com/MicrosoftDocs/feedback/issues/1583
This PR removes our attempt to start them automatically which is not possible and attempts to stop the deployment failure caused by this if the triggers are already started.
Previously we have been stopping them manually prior to a deploy.
We will still need to remember to re-enable them unless we can add a DevOps plugin to automate this.

EES-1544 Deploy triggers in a stopped state

---

src/GovUk.Education.ExploreEducationStatistics.Data.Processor/Startup.cs

This PR switches the new ProcessorService to be transient, as some of its dependencies are transient and its prior Singleton wiring was causing these transient dependencies to take on a Singleton lifecycle.

EES-1618 - swapped out singleton wiring for transient for new ProcessorService

---

src/explore-education-statistics-common/src/modules/charts/components/MapBlockInternal.tsx
src/explore-education-statistics-common/src/modules/charts/components/__tests__/MapBlock.test.tsx
src/explore-education-statistics-common/src/modules/charts/components/__tests__/__data__/testMapBlockData.ts
src/explore-education-statistics-common/src/modules/table-tool/components/__tests__/__snapshots__/TimePeriodDataTable.test.tsx.snap
src/explore-education-statistics-common/src/utils/number/__tests__/formatPretty.test.ts
src/explore-education-statistics-common/src/utils/number/formatPretty.ts

This change reinstates 2 decimal places as the default for `formatPretty` (and consequently all indicator formatting). This will have implications for any indicators where analysts have not specified decimal places e.g. indicators that are actually integers will be 'incorrectly' formatted to 2 decimal places. The advice there is to ensure that decimal places are explicitly specified in the metadata.

EES-1605 Re-add 2 d.p as default for map legend groups and indicators

---

src/explore-education-statistics-common/src/modules/charts/components/MapBlockInternal.tsx
src/explore-education-statistics-common/src/modules/charts/components/__tests__/MapBlock.test.tsx
src/explore-education-statistics-common/src/modules/charts/components/__tests__/__data__/testMapBlockData.ts
src/explore-education-statistics-common/src/modules/table-tool/components/__tests__/__snapshots__/TimePeriodDataTable.test.tsx.snap
src/explore-education-statistics-common/src/utils/number/__tests__/countDecimals.test.ts
src/explore-education-statistics-common/src/utils/number/__tests__/formatPretty.test.ts
src/explore-education-statistics-common/src/utils/number/__tests__/getMinMax.test.ts
src/explore-education-statistics-common/src/utils/number/countDecimals.ts
src/explore-education-statistics-common/src/utils/number/formatPretty.ts
src/explore-education-statistics-common/src/utils/number/getMinMax.ts

This PR:
- Mostly reverts decimal place formatting changes made to `formatPretty`. If no decimal places are specified, it will default to having a maximum of 2 decimal places and a minimum based on the decimals in the input value.
- Adjusts the `MapBlock` legend to calculate the decimal places to use in its group boundaries based on the data values. We try and find the maximum number of decimal places in the values (up to a max of 2), then re-adjust if necessary to prevent the boundaries from overlapping.

EES-1605 Revert decimal place formatting and calculate default map legend decimals from data

---

src/GovUk.Education.ExploreEducationStatistics.Admin.Tests/Services/ReleaseDataFileServiceTest.cs
src/GovUk.Education.ExploreEducationStatistics.Admin.Tests/Services/ReleaseFileServiceTests.cs
src/GovUk.Education.ExploreEducationStatistics.Admin/Services/ReleaseFileService.cs
src/GovUk.Education.ExploreEducationStatistics.Content.Model/ReleaseFileReference.cs
src/GovUk.Education.ExploreEducationStatistics.Publisher/Services/FileStorageService.cs

Historically the blob storage filename has not always been forced to lowercase,  so rely on the `Filename` field which should be accurate for all files, rather than `Filename.ToLower()` in `BlobStorageName` getter.
Also since Filename is forced to lower case now whenever a `ReleaseFileReference` is created or updated, there was no need to lowercase it again here and removing this won't affect lowercasing newly uploaded files.
The filename of blobs is due to change soon when they will be migrated to use the their database file id, in the same way as chart files now.

EES-1632 Historically blob filename has not been forced lowercase.

---

src/explore-education-statistics-admin/src/pages/release/content/components/ReleaseContent.tsx

This bug was causing the causing browser to infer the file type based on the blob returned from the API. It seems like most files seem to have been uploaded with Excel content types, so it would incorrectly infer file types as xls.
By setting the filename correctly, we provide the file with a .csv extension, which is enough to make sure the file downloads correctly.

EES-1636 Fix admin release files not specifying correct file name

---

src/GovUk.Education.ExploreEducationStatistics.Data.Importer/Utils/DbUtils.cs
src/GovUk.Education.ExploreEducationStatistics.Data.Processor/Services/ReleaseProcessorService.cs

This PR:
- adds concurrency control to the process of creating Themes, Topics, Publications and Releases when multiple data files for the same Release are uploaded close to each other.
It does this by preventing two or more importer threads from attempting to create-or-update any of the above entities by acquiring locks at an "entity type" / "entity id" granularity.
If three threads are trying to create-or-update a "Theme" entity with ID "123478324-37239855-asd0faf-234509845":
- the first thread to acquire the lock will block the others.  It will create a lock called "CreateOrUpdateTheme-123478324-37239855-asd0faf-234509845" and then be free to create the Theme unhindered
- it will then release the lock (after its transaction commits)
- the next thread that tried to acquire the lock will …

Ees 1000 stop insert clashes on parallel imports

---

src/explore-education-statistics-admin/src/pages/release/footnotes/components/FootnoteForm.tsx
src/explore-education-statistics-admin/src/services/utils/footnote/footnoteToFlatFootnote.ts

This change fixes saved footnotes causing `FootnoteForm` to initialise with the wrong initial values. This wouldn't be an immediate issue, butwould cause submission of the form to fail as `footnoteToFlatFootnote` would receive incorrect values to process (leading to the error).

EES-1647 Fix footnote form throwing error for saved footnotes

---

src/GovUk.Education.ExploreEducationStatistics.Data.Model/Services/FootnoteService.cs

Avoid NullReferenceException in the check `IsFootnoteLinkedToAnotherSubjectForThisRelease` called when deleting footnotes by always including FootnoteFilter.Filter in the query result.
A NullReferenceException was occuring in `Contains(filter.Filter.SubjectId)` if the footnote is linked to other subjects as well as the one being deleted.

EES-1623 EES-1645 Avoid NullReferenceException

---

src/explore-education-statistics-admin/src/pages/release/datablocks/components/chart/ChartBuilder.tsx
src/explore-education-statistics-admin/src/pages/release/datablocks/components/chart/reducers/__tests__/chartBuilderReducer.test.ts
src/explore-education-statistics-admin/src/pages/release/datablocks/components/chart/reducers/chartBuilderReducer.ts

This PR fixes two issues that have been causing the unexpected behaviour seen in the ticket:
- Incorrect initialisation of initial state (i.e. when user visits chart builder for the first time). For example, this was setting `height` to 300px for every chart regardless of type. We have now modified this so that the state is essentially empty until the user starts using chart builder.
- Chart definition defaults not being set correctly in chart builder state when the definition changes. We now override any height/width with the chart definition's defaults whenever another type has been selected by the user. This should be more in-line with their expectations.

EES-1616 Fix chart definition defaults not being honoured when type is changed

---

src/explore-education-statistics-admin/src/pages/release/ReleaseStatusPage.tsx
src/explore-education-statistics-admin/src/pages/release/__tests__/ReleaseStatusPage.test.tsx
src/explore-education-statistics-admin/src/pages/release/components/ReleaseStatusForm.tsx
src/explore-education-statistics-admin/src/pages/release/components/__tests__/ReleaseStatusForm.test.tsx
src/explore-education-statistics-admin/src/services/releaseService.ts

This change also adds a raft of tests to cover `ReleaseStatusPage` and `ReleaseStatusForm`.

EES-1653 Refactor ReleaseStatusForm out of ReleaseStatusPage

---

src/GovUk.Education.ExploreEducationStatistics.Admin.Tests/Services/FootnoteServicePermissionTests.cs
src/GovUk.Education.ExploreEducationStatistics.Admin.Tests/Services/FootnoteServiceTests.cs
src/GovUk.Education.ExploreEducationStatistics.Admin.Tests/Services/ReleaseSubjectServiceTests.cs
src/GovUk.Education.ExploreEducationStatistics.Admin.Tests/Services/ReplacementServiceTests.cs
src/GovUk.Education.ExploreEducationStatistics.Admin/Services/FootnoteService.cs
src/GovUk.Education.ExploreEducationStatistics.Admin/Services/ReplacementService.cs
src/GovUk.Education.ExploreEducationStatistics.Admin/Startup.cs
src/GovUk.Education.ExploreEducationStatistics.Data.Api/Startup.cs
src/GovUk.Education.ExploreEducationStatistics.Data.Model/Services/FootnoteRepository.cs
src/GovUk.Education.ExploreEducationStatistics.Data.Model/Services/Interfaces/IFootnoteRepository.cs
src/GovUk.Education.ExploreEducationStatistics.Data.Model/Services/ReleaseSubjectService.cs
src/GovUk.Education.ExploreEducationStatistics.Data.Services/ResultSubjectMetaService.cs
src/GovUk.Education.ExploreEducationStatistics.Publisher/Startup.cs

This PR renames the common `FootnoteService` (in `Data.Model`) to `FootnoteRepository`. 
This has the benefit of: 
- Removing namespacing issues 
- Simplifying names from things like `commonFootnoteService` to `footnoteRepository`
- Being more semantically correct, as it is more like a repository than a service (most of the common data 'services' are repositories).

EES-1691 Rename common FootnoteService to FootnoteRepository

---

src/explore-education-statistics-admin/src/pages/admin-dashboard/components/PublicationSummary.tsx
src/explore-education-statistics-common/src/components/ModalConfirm.tsx
src/explore-education-statistics-common/src/components/__tests__/ModalConfirm.test.tsx
src/explore-education-statistics-common/src/hooks/useMountedRef.ts

This change prevents `ModalConfirm` buttons from being clicked and the modal from being exited (e.g. with Esc or an underlay click) whilst the current `onConfirm` or `onCancel` is in progress.
Whilst confirming/cancelling is in progress, the user should be unable to do anything to prevent them from getting the page into an inconsistent state.

EES-1727 Disable ModalConfirm buttons and exits when confirming/cancelling

---

Pipfile
Pipfile.lock
useful-scripts/create-emulator-release-files.py

This PR adds the following fixes to the new `create-emulator-release-files` script:
- Fixes `downloads` container not being created if it doesn't exist.
- Fixes script hard-coding the storage emulator as `127.0.0.1`. The `data-storage` host alias should be used instead as it will not be `127.0.0.1` if running the emulator via a Windows VM.
- Pins version for `azure-storage-blob` Pipfile dependency.

Fixes for emulator files script

---

src/GovUk.Education.ExploreEducationStatistics.Publisher.Tests/Services/ReleaseServiceTests.cs
src/GovUk.Education.ExploreEducationStatistics.Publisher/Services/ReleaseService.cs

We should throw an exception if the 'All files' zip is missing when publishing a Release since it should never be missing.
This was already the case, although the  error (raised outside our project) is rather unhelpful and doesn't include the missing blob path.
Temporarily, in order to  to collect a list of missing files and not halt publishing while regenerating content for all releases, we log an error and continue by returning a `FileInfo` containing a null file path.
This is to assist cleaning up environments believed to contain bad test data.

EES-1755 Temporarily be lenient if 'All files' zip is missing

---

src/GovUk.Education.ExploreEducationStatistics.Content.Model.Tests/ReleaseTests.cs
src/GovUk.Education.ExploreEducationStatistics.Content.Model/Release.cs

Skip null or empty content before updating FastTrack links.
If a user creates a text block but doesn't add any text, there was previously an error occurring when amending that Release if it also had data blocks.

EES-1759 Skip null or empty content before updating FastTrack links.

---

src/GovUk.Education.ExploreEducationStatistics.Publisher.Tests/Extensions/PublisherExtensionTests.cs
src/GovUk.Education.ExploreEducationStatistics.Publisher/Extensions/PublisherExtensions.cs
src/GovUk.Education.ExploreEducationStatistics.Publisher/Utils/PublisherUtils.cs

Change `PublisherExtensions#IsReleasePublished` to work correctly for amendment Releases not yet published but included for publishing.

EES-1785 Change PublisherExtensions#IsReleasePublished for amendment Releases not yet published

---

src/GovUk.Education.ExploreEducationStatistics.Common.Tests/Services/TimePeriodLabelFormatterTests.cs
src/GovUk.Education.ExploreEducationStatistics.Common/Model/TimeIdentifier.cs
src/GovUk.Education.ExploreEducationStatistics.Common/Model/TimeIdentifierCategory.cs
src/GovUk.Education.ExploreEducationStatistics.Data.Services.Tests/Extensions/TimeIdentifierExtensionsTests.cs
src/GovUk.Education.ExploreEducationStatistics.Data.Services.Tests/TimeIdentifierUtilTests.cs
src/GovUk.Education.ExploreEducationStatistics.Data.Services.Tests/TimePeriodUtilTests.cs
src/GovUk.Education.ExploreEducationStatistics.Data.Services/Extensions/TimeIdentifierExtensions.cs
src/GovUk.Education.ExploreEducationStatistics.Data.Services/TimeIdentifierUtil.cs

Adds two new custom time periods to support an upcoming ad-hoc Release that is for data recorded between
- April to September
- October to March
Full label format `2020/21 October to March`
Full label before year format `October to March 2020/21`
Short label format `2020/21 Oct to Mar`
Slug format `2020-21-oct-to-mar`
Expected CSV `time_identifier` value format `October to March`

EES-1791 Add new custom time periods for forthcoming ad-hoc Release

---

src/explore-education-statistics-frontend/next.config.js
src/explore-education-statistics-frontend/package-lock.json
src/explore-education-statistics-frontend/package.json
src/explore-education-statistics-frontend/src/polyfill.js

This PR fixes syntax errors being thrown on IE11 due to un-transpiled code (ES6+) being included in the bundle. This originated from `sanitize-html@2.0` which no longer provides a pre-built version of their module (they expect you to transpile it yourself).

EES-1694 Fix content blocks breaking on IE11 due to syntax errors

---

src/GovUk.Education.ExploreEducationStatistics.Admin.Tests/Services/ReleaseChecklistServiceTests.cs
src/GovUk.Education.ExploreEducationStatistics.Admin/Services/ReleaseChecklistService.cs
src/GovUk.Education.ExploreEducationStatistics.Admin/Validators/ValidationUtils.cs
src/explore-education-statistics-admin/src/pages/release/components/ReleaseStatusChecklist.tsx
src/explore-education-statistics-admin/src/pages/release/components/__tests__/ReleaseStatusChecklist.test.tsx
src/explore-education-statistics-admin/src/services/releaseService.ts
tests/robot-tests/tests/admin/bau/release_status.robot

This PR changes the release checklist rule requiring a PRA public list from an error to a warning. This is necessary due to the weird release on Friday that doesn't fit nicely into our release model.

EES-1807 Relax PRA public list checklist rule to warning

---

src/explore-education-statistics-admin/src/pages/release/datablocks/components/chart/ChartBuilder.tsx
src/explore-education-statistics-admin/src/pages/release/datablocks/components/chart/ChartBuilderTabSection.tsx
src/explore-education-statistics-admin/src/pages/release/datablocks/components/chart/ChartConfiguration.tsx
src/explore-education-statistics-admin/src/pages/release/datablocks/components/chart/reducers/chartBuilderReducer.ts
src/explore-education-statistics-common/src/modules/charts/components/MapBlockInternal.tsx

This change fixes the chart builder's boundary level field (for maps) not being initialized with a value (regardless of if you save the chart with a different boundary level or not).
This was due to `boundaryLevel` not being injected into the `chartBuilderReducer` (from the data block's table data query). Instead,
we have now completely removed the boundary level field from the `ChartConfiguration` form and `chartBuilderReducer`. It is now a standalone `FormSelect` controlled by the `boundaryLevel` prop.

EES-1767 Fix chart builder boundary level field not being initialized

---

src/GovUk.Education.ExploreEducationStatistics.Data.Services/ViewModels/ObservationViewModel.cs
src/explore-education-statistics-admin/src/pages/release/datablocks/components/DataBlockSourceWizard.tsx
src/explore-education-statistics-admin/src/pages/release/datablocks/components/ReleaseDataBlocksPageTabs.tsx
src/explore-education-statistics-common/src/modules/charts/components/MapBlockInternal.tsx
src/explore-education-statistics-common/src/modules/charts/components/__tests__/__data__/testChartData.ts
src/explore-education-statistics-common/src/modules/charts/components/__tests__/__data__/testMapBlockData.ts
src/explore-education-statistics-common/src/modules/charts/util/__tests__/createDataSetCategories.test.ts
src/explore-education-statistics-common/src/modules/charts/util/__tests__/groupResultMeasuresByDataSet.test.ts
src/explore-education-statistics-common/src/modules/charts/util/createDataSetCategories.ts
src/explore-education-statistics-common/src/modules/charts/util/groupResultMeasuresByDataSet.ts
src/explore-education-statistics-common/src/modules/table-tool/components/DownloadCsvButton.tsx
src/explore-education-statistics-common/src/modules/table-tool/components/TimePeriodDataTable.tsx
src/explore-education-statistics-common/src/modules/table-tool/components/WizardStep.tsx
src/explore-education-statistics-common/src/modules/table-tool/components/__tests__/DownloadCsvButton.test.tsx
src/explore-education-statistics-common/src/modules/table-tool/components/__tests__/TimePeriodDataTable.test.tsx
src/explore-education-statistics-common/src/modules/table-tool/components/__tests__/__data__/TimePeriodDataTable.data.tsx
src/explore-education-statistics-common/src/modules/table-tool/components/utils/__tests__/groupResultsMeasuresByCombination.test.ts
src/explore-education-statistics-common/src/modules/table-tool/components/utils/groupResultMeasuresByCombination.ts
src/explore-education-statistics-common/src/modules/table-tool/types/filters.ts
src/explore-education-statistics-frontend/src/modules/table-tool/components/TableToolFinalStep.tsx

This PR adds the following performance optimizations:
- Adds pre-grouping of result measures by their respective set of filters. This drastically speeds up lookup of results during `createDataSetCategories` (up to ~10x faster)
- Adds a similar pre-grouping of result measures optimization to `TimePeriodDataTable` as well (~4-5x faster)
- Aggregates multiple operations required for calculating `MapBlock` geometries into a single operation (~0.25x faster)
- Removes client-side camelCasing of `geographicLevel` for both charts and tables. This only shaves off a fairly neglible amount of time (~1%), but it mainly makes sense to push any camelCasing onto the server for consistency.
- Fixes `ReleaseDataBlockSourceWizardFinalStep` rendering its table twice unnecessarily.
- Changes 'Table' tab in …

EES-1730 Add initial performance optimizations for charts/tables

---

src/GovUk.Education.ExploreEducationStatistics.Data.Model/Services/FootnoteRepository.cs
src/GovUk.Education.ExploreEducationStatistics.Data.Model/Services/Interfaces/IFootnoteRepository.cs
src/GovUk.Education.ExploreEducationStatistics.Data.Processor/Services/SplitFileService.cs
src/GovUk.Education.ExploreEducationStatistics.Data.Services/ObservationService.cs
src/GovUk.Education.ExploreEducationStatistics.Data.Services/TableBuilderService.cs

This PR:
- cuts out unnecessary joins to fetch Filters from Observations when returning for data block queries and meta queries.  The Filters are never used by the calling code.  A more robust approach to this would be to return an `ObservationRowResult` or some other class that contained just what the calling code actually needed from the Observations, namely the FilterItem IDs and nothing more (as per on the EES-1795 branch)
- fixes issue whereby if Observation results were in several batches, the Locations were being selected and reapplied to previous batches of Observations each time a new batch was processed (look how `result` is used as a basis to find Location IDs and then select and assign those found Locations to everything in `result` again and again.

Ees 1806 performance quick wins with data block queries

---

src/GovUk.Education.ExploreEducationStatistics.Common/Services/BlobStorageService.cs
src/GovUk.Education.ExploreEducationStatistics.Common/Services/FileStoragePathUtils.cs
src/GovUk.Education.ExploreEducationStatistics.Common/Services/Interfaces/IBlobStorageService.cs
src/GovUk.Education.ExploreEducationStatistics.Content.Api.Tests/Services/FileStorageServiceTests.cs
src/GovUk.Education.ExploreEducationStatistics.Content.Api/Services/FileStorageService.cs
src/GovUk.Education.ExploreEducationStatistics.Data.Api.Tests/Controllers/TableBuilderControllerTests.cs
src/GovUk.Education.ExploreEducationStatistics.Data.Api.Tests/Services/DataBlockServiceTests.cs
src/GovUk.Education.ExploreEducationStatistics.Data.Api/Controllers/TableBuilderController.cs
src/GovUk.Education.ExploreEducationStatistics.Data.Api/Services/DataBlockService.cs
src/GovUk.Education.ExploreEducationStatistics.Data.Api/Services/Interfaces/IDataBlockService.cs
src/GovUk.Education.ExploreEducationStatistics.Data.Api/Startup.cs
src/GovUk.Education.ExploreEducationStatistics.Publisher/Services/FileStorageService.cs

This PR adds caching of release data block responses in blob storage. This is performed via a cache-aside strategy, so we don't perform all the caching up-front when a release is published. 
Instead, the very first user that fetches a data block table response will still go to the DB for the table response, but the result will be cached in blob storage. Users from that point onwards will receive the cached version instead. Once in cache, this results in much faster response times compared with hitting the DB.
- Lifted `GetDeserializedJson` and `UploadAsJson` methods into `BlobStorageService` as this makes it much more convenient to upload/download JSON objects from blob storage.

EES-1722 Add blob storage caching of data block responses

---

src/GovUk.Education.ExploreEducationStatistics.Admin.Tests/Services/ReplacementServiceTests.cs
src/GovUk.Education.ExploreEducationStatistics.Admin/Services/ReplacementService.cs
src/GovUk.Education.ExploreEducationStatistics.Common/Model/Chart/ChartLegend.cs
src/GovUk.Education.ExploreEducationStatistics.Content.Model/Database/ContentDbContext.cs

This change adds a new `ChartLegendItemDataSet` type which allows all of the constitutent properties to be optional. This is important as the frontend will typically remove the grouping filter type from the data set.
Previously this was causing empty guids to be persisted in the data sets when grouping by indicator. These would then be returned in the response and the data sets could not be matched correctly to the data.

EES-1804 Fix legend item data sets not saving with optional properties

---

src/GovUk.Education.ExploreEducationStatistics.Common/Extensions/ControllerExtensions.cs
src/GovUk.Education.ExploreEducationStatistics.Data.Api.Tests/Controllers/TableBuilderControllerTests.cs
src/GovUk.Education.ExploreEducationStatistics.Data.Api/Controllers/TableBuilderController.cs
src/explore-education-statistics-common/src/services/tableBuilderService.ts

This PR adds an `ETag` header to the data block table query endpoint. We primarily need this to enable us to invalidate the cache if there is a breaking change to the API.
In this instance, we have changed location levels to be camelCased on the server. This is a breaking change, but we cannot inform clients that the cache should be invalidated using just `LastModified`. With `ETag`, we can trigger invalidation by changing some string, such as a API version number.
- Added an additional `CacheWithETag` method that can be used in other controllers if required.
- Fixed casing of `/tablebuilder/release/{releaseId}/data-block/{dataBlockId}` endpoint URL

EES-1819 Add ETag to data block table query endpoint for invalidation

---

infrastructure/templates/template.json

This PR:
- Removes the `AllowAllWindowsAzureIps` firewall rule from the SQL servers. This allows connections from anywhere in Azure, which is potentially a security vulnerability.
- Adds virtual network rules to allow access from our subnets for each respective application/function.
- It seems like data factory already has some form of direct access to our SQL databases (via 'Linked services') so I don't _think_ it needs any additional work to reach the databases. We need to test that this is true on dev.
- Additional work needs to be done to segregate content/stats databases for more granular network access control - [EES-1825](https://dfedigital.atlassian.net/browse/EES-1825)

EES-1824 Restrict access to DBs using virtual network rules

---

tests/robot-tests/tests/admin_and_public/bau/footnotes.robot

Fix `footnotes.robot` UI test by adding in some checks to make sure the clicks that selenium performs isn't intercepted by the "set page view" feature.

Ees 1860 - fix footnotes UI test

---

src/GovUk.Education.ExploreEducationStatistics.Admin.Tests/Controllers/Api/Statistics/FootnoteControllerTests.cs
src/GovUk.Education.ExploreEducationStatistics.Admin.Tests/Services/ReleaseMetaServicePermissionTests.cs
src/GovUk.Education.ExploreEducationStatistics.Admin.Tests/Services/ReleaseMetaServiceTests.cs
src/GovUk.Education.ExploreEducationStatistics.Admin/Controllers/Api/Statistics/FootnoteController.cs
src/GovUk.Education.ExploreEducationStatistics.Admin/Controllers/Api/Statistics/TableBuilderMetaController.cs
src/GovUk.Education.ExploreEducationStatistics.Admin/Services/Interfaces/IReleaseMetaService.cs
src/GovUk.Education.ExploreEducationStatistics.Admin/Services/ReleaseMetaService.cs
src/GovUk.Education.ExploreEducationStatistics.Content.Model/ContentBlock.cs
src/GovUk.Education.ExploreEducationStatistics.Data.Services/ViewModels/Meta/ReleaseSubjectsMetaViewModel.cs
src/explore-education-statistics-admin/src/pages/release/datablocks/components/__tests__/ReleaseDataBlocksPageTabs.test.tsx
src/explore-education-statistics-admin/src/pages/release/pre-release/PreReleasePageContainer.tsx
src/explore-education-statistics-admin/src/pages/release/pre-release/PreReleaseTableToolPage.tsx
src/explore-education-statistics-admin/src/pages/release/pre-release/__tests__/PreReleaseTableToolPage.test.tsx
src/explore-education-statistics-admin/src/routes/preReleaseRoutes.ts
src/explore-education-statistics-common/src/modules/table-tool/components/__tests__/TableToolWizard.test.tsx
src/explore-education-statistics-common/src/services/tableBuilderService.ts
src/explore-education-statistics-frontend/src/modules/table-tool/TableToolPage.tsx

This PR adds this 'Table highlights' section to Step 1 of the pre-release table tool page:
This provides parity withe public frontend's equivalent page.
- Fixed public frontend `TableToolPage` potentially showing an empty list of table highlights if there was exactly one highlight and the user had already navigated to it.

EES-1846 Add table highlights to pre-release table tool page

---

src/GovUk.Education.ExploreEducationStatistics.Admin.Tests/Services/DataBlockServicePermissionTests.cs
src/GovUk.Education.ExploreEducationStatistics.Admin.Tests/Services/DataBlockServiceTests.cs
src/GovUk.Education.ExploreEducationStatistics.Admin/Services/DataBlockService.cs
src/GovUk.Education.ExploreEducationStatistics.Admin/Services/Interfaces/IDataBlockService.cs
src/explore-education-statistics-admin/src/pages/release/ReleasePageContainer.tsx
src/explore-education-statistics-admin/src/pages/release/datablocks/ReleaseDataBlockCreatePage.tsx
src/explore-education-statistics-admin/src/pages/release/datablocks/ReleaseDataBlockEditPage.tsx
src/explore-education-statistics-admin/src/pages/release/datablocks/ReleaseDataBlocksPage.tsx
src/explore-education-statistics-admin/src/pages/release/datablocks/ReleaseTableToolPage.tsx
src/explore-education-statistics-admin/src/pages/release/datablocks/__data__/tableToolServiceData.ts
src/explore-education-statistics-admin/src/pages/release/datablocks/__tests__/ReleaseDataBlockEditPage.test.tsx
src/explore-education-statistics-admin/src/pages/release/datablocks/__tests__/ReleaseDataBlocksCreatePage.test.tsx
src/explore-education-statistics-admin/src/pages/release/datablocks/__tests__/ReleaseDataBlocksPage.test.tsx
src/explore-education-statistics-admin/src/pages/release/datablocks/__tests__/ReleaseTableToolPage.test.tsx
src/explore-education-statistics-admin/src/pages/release/datablocks/components/DataBlockPageReadOnlyTabs.tsx
src/explore-education-statistics-admin/src/pages/release/datablocks/components/DataBlockPageTabs.tsx
src/explore-education-statistics-admin/src/pages/release/datablocks/components/DataBlockSelector.tsx
src/explore-education-statistics-admin/src/pages/release/datablocks/components/TableTabSection.tsx
src/explore-education-statistics-admin/src/pages/release/datablocks/components/__tests__/DataBlockPageTabs.test.tsx
src/explore-education-statistics-admin/src/pages/release/datablocks/components/chart/ChartBuilderTabSection.tsx
src/explore-education-statistics-admin/src/routes/releaseRoutes.ts
tests/robot-tests/tests/admin_and_public/bau/publish_release_and_amend.robot

This PR adds a read-only variant of the 'Edit data block' page that is only visible once the release has been published. It looks like the following:
The user cannot modify the data block any further at this point and can only see the table and chart tabs.
If they want to play around with the table tool itself, they can do so by visting a new 'Go to table tool' button on the main 'Data blocks' page:
This takes them to a read-only version of the table tool:
This table tool is essentially the same as the one in the public frontend, but does not offer any of the additional options (e.g. downloading as CSV/XLSX, permalinks, etc).
- Refactors `DataBlockService` to fetch the required `ReleaseContentBlocks` directly, instead of fetching a `DataBlock` then matching it with a `Release`. This …

EES-1848 Allow data blocks to be inspected after release is published

---

src/explore-education-statistics-frontend/src/modules/cookies/CookiesPage.module.scss
src/explore-education-statistics-frontend/src/modules/cookies/CookiesPage.tsx

This PR:
- Removes the unnecessary `FormFieldset` wrapping the GA cookie options.
- Cleans up styling and markup for the success message.

EES-78 Remove unnecessary fieldset from CookiesPage and general cleanup

---

src/explore-education-statistics-admin/src/pages/release/datablocks/ReleaseDataBlockCreatePage.tsx
src/explore-education-statistics-admin/src/pages/release/datablocks/ReleaseDataBlockEditPage.tsx
src/explore-education-statistics-admin/src/pages/release/datablocks/ReleaseDataBlocksPage.tsx

This fixes incorrect state being shown on data blocks due to not waiting for the `canUpdateRelease` check to finish loading. We've now refactored these pages to use a model-based approach to ensure all the required state has been loaded before rendering.

EES-1879 Fix incorrect state flickering on data blocks pages

---

src/GovUk.Education.ExploreEducationStatistics.Admin.Tests/Services/DataBlockServiceTests.cs
src/GovUk.Education.ExploreEducationStatistics.Admin/Migrations/ContentMigrations/20210208180541_EES1873AddDataBlockHighlightDescription.Designer.cs
src/GovUk.Education.ExploreEducationStatistics.Admin/Migrations/ContentMigrations/20210208180541_EES1873AddDataBlockHighlightDescription.cs
src/GovUk.Education.ExploreEducationStatistics.Admin/ViewModels/DataBlockSummaryViewModel.cs
src/GovUk.Education.ExploreEducationStatistics.Admin/ViewModels/DataBlockViewModels.cs
src/GovUk.Education.ExploreEducationStatistics.Content.Model/ContentBlock.cs
src/GovUk.Education.ExploreEducationStatistics.Content.Model/Database/ContentDbContext.cs
src/explore-education-statistics-admin/src/pages/release/datablocks/ReleaseDataBlockEditPage.tsx
src/explore-education-statistics-admin/src/pages/release/datablocks/__tests__/ReleaseDataBlockEditPage.test.tsx
src/explore-education-statistics-admin/src/pages/release/datablocks/components/DataBlockDetailsForm.tsx
src/explore-education-statistics-admin/src/pages/release/datablocks/components/DataBlockSourceWizard.tsx
src/explore-education-statistics-admin/src/pages/release/datablocks/components/__tests__/DataBlockDetailsForm.test.tsx
src/explore-education-statistics-admin/src/pages/release/datablocks/components/__tests__/DataBlockPageTabs.test.tsx
src/explore-education-statistics-admin/src/services/dataBlockService.ts
src/explore-education-statistics-common/src/services/types/blocks.ts
tests/robot-tests/tests/admin/bau/create_data_block_with_chart.robot
tests/robot-tests/tests/admin_and_public/bau/publish_data.robot

This PR adds a new 'Highlight description' field that can be seen when create/updating data blocks. It looks like the following:
- Updated the 'Table highlight name' field label to simply 'Highlight name'
- Fixes highlight name summary row rendering in the read-only view, even if there is no highlight name to show. We now just hide the row for the name and description unless they are filled out.

EES-1873 Add highlight description field when create/updating data blocks

---

src/GovUk.Education.ExploreEducationStatistics.Admin.Tests/Services/PublicationServiceTests.cs
src/GovUk.Education.ExploreEducationStatistics.Admin.Tests/Services/ReleaseChecklistServicePermissionTests.cs
src/GovUk.Education.ExploreEducationStatistics.Admin.Tests/Services/ReleaseChecklistServiceTests.cs
src/GovUk.Education.ExploreEducationStatistics.Admin/Services/PublicationService.cs
src/GovUk.Education.ExploreEducationStatistics.Admin/Services/ReleaseChecklistService.cs
src/GovUk.Education.ExploreEducationStatistics.Admin/Validators/ValidationUtils.cs
src/explore-education-statistics-admin/src/pages/publication/components/PublicationForm.tsx
src/explore-education-statistics-admin/src/pages/release/components/ReleaseStatusChecklist.tsx
src/explore-education-statistics-admin/src/services/releaseService.ts

EES-1132 adds extra validation to the release approval checklist. If a release has a generic content section that contain no content blocks, or if a generic content section contains only blank HtmlBlocks, the user will receive a release checklist error.
EES-1878 gives users the ability to attach any methodology to a publication. Previously, the frontend filtered the available methodologies so that only Approved methodologies were available, and the backend validated that created/updated publications methodologies were approved.

EES-1132 and EES-1878

---

src/explore-education-statistics-common/src/modules/table-tool/components/TableHighlightsList.tsx
src/explore-education-statistics-common/src/modules/table-tool/components/__tests__/TableHighlightsList.test.tsx

This changes table highlights so that they no longer render empty descriptions. This could be a bit weird for screen readers as they would be directed to an empty paragraph.

EES-1664 Fix highlight links having potentially empty descriptions

---

src/explore-education-statistics-common/src/components/form/Form.tsx
src/explore-education-statistics-common/src/components/form/__tests__/Form.test.tsx
src/explore-education-statistics-common/src/components/form/__tests__/__snapshots__/Form.test.tsx.snap

This PR fixes most forms triggering a console error upon submitting due to state setters being called once the form has unmounted (typically because the user is redirected to another page).
To prevent this from happening, we have just wrapped the state setters with `isMounted.current` checks.
- Refactored `Form` tests to use `screen` and replace deprecated `wait` with `waitFor`.

EES-967 Prevent console errors after submitting forms

---

src/explore-education-statistics-admin/src/pages/release/components/ReleaseStatusForm.tsx
src/explore-education-statistics-common/src/components/form/FormCheckboxGroup.tsx
src/explore-education-statistics-common/src/components/form/FormFieldRadioGroup.tsx
src/explore-education-statistics-common/src/components/form/FormRadioGroup.tsx
src/explore-education-statistics-common/src/modules/charts/util/createDataSetCategories.ts
src/explore-education-statistics-common/src/modules/table-tool/components/FiltersForm.tsx
src/explore-education-statistics-common/src/modules/table-tool/components/LocationFiltersForm.tsx
src/explore-education-statistics-common/src/modules/table-tool/components/TableHighlightsList.tsx
src/explore-education-statistics-common/src/modules/table-tool/components/TableToolWizard.tsx
src/explore-education-statistics-common/src/modules/table-tool/components/__tests__/TableHighlightsList.test.tsx
src/explore-education-statistics-common/src/modules/table-tool/utils/__tests__/getDefaultTableHeadersConfig.test.ts
src/explore-education-statistics-common/src/modules/table-tool/utils/getDefaultTableHeadersConfig.ts
src/explore-education-statistics-common/src/utils/array/__tests__/naturalOrderBy.test.ts
src/explore-education-statistics-common/src/utils/array/naturalOrderBy.ts

This PR adds improved sorting for:
- Table tool checkboxes
- Table tool table headers
- Chart axis labels
We have implemented this via a new `naturalOrderBy` function. It roughly mimics `lodash/orderBy` and should replace it in cases where we display sorted information to the user. 
It's still fine to use `orderBy`, but `naturalOrderBy` does a much better job of sorting items on string properties that contain numeric information e.g. dates, or numbers in general.

EES-1880 Add natural ordering to table tool and chart labels

---

infrastructure/templates/template.json

This makes a change to configure the deployment slots for each of the three app services to use the virtual network.
Currently they do not. When the production app service is swapped with the non-production service, it has the virtual network removed. This can be seen in the changelog of the slots during deployment time.
If there are requests in progress as the production slot is  swapped they may still try acquiring a database  pool connection which would then be blocked by the firewall.
We also think this might be the cause of intermittent start-up failures, if the reverse happens and start-up occurs after deployment before the virtual network has been assigned.

EES-1941 Configure Deployment Slot in Virtual Network

---

src/explore-education-statistics-admin/config/webpack.config.js

This was accidentally removed in 2f15563, so we're just adding this back in to lint CSS on save.

fix: re-add missing Stylelint plugin to admin Webpack config

---

src/explore-education-statistics-common/src/components/PageSearchForm.tsx
src/explore-education-statistics-common/src/components/__tests__/PageSearchForm.test.tsx
src/explore-education-statistics-frontend/src/components/Link.tsx
src/explore-education-statistics-frontend/src/components/PageSearchFormWithAnalytics.tsx
src/explore-education-statistics-frontend/src/components/PrintThisPage.tsx
src/explore-education-statistics-frontend/src/modules/download/DownloadIndexPage.tsx
src/explore-education-statistics-frontend/src/modules/download/components/TopicDownloadList.tsx
src/explore-education-statistics-frontend/src/modules/find-statistics/FindStatisticsPage.tsx
src/explore-education-statistics-frontend/src/modules/find-statistics/PublicationReleaseHelpAndSupportSection.tsx
src/explore-education-statistics-frontend/src/modules/find-statistics/PublicationReleasePage.tsx
src/explore-education-statistics-frontend/src/modules/find-statistics/components/PublicationSectionBlocks.tsx
src/explore-education-statistics-frontend/src/modules/glossary/GlossaryPage.tsx
src/explore-education-statistics-frontend/src/modules/methodologies/MethodologyIndexPage.tsx
src/explore-education-statistics-frontend/src/modules/methodologies/MethodologyPage.tsx
src/explore-education-statistics-frontend/src/modules/permalink/PermalinkPage.tsx
src/explore-education-statistics-frontend/src/modules/table-tool/TableToolPage.tsx
src/explore-education-statistics-frontend/src/modules/table-tool/components/TableToolFinalStep.tsx
src/explore-education-statistics-frontend/src/services/googleAnalyticsService.ts

This PR just refactors all public frontend link/button components to use a combination of `onClick` handlers with `logEvent` calls.
As part of this, we've also refactored the `logEvent` function to accept a single object paramter, instead of multiple parameters. This simplifies the API and prevents potential ordering bugs with the parameters.
- Refactors `PageSearchForm` to a function component.

EES-1904 Replace link `analytics` prop with `logEvent` calls

---

useful-scripts/importer-tests/importer.py
useful-scripts/publisher-tests/publisher.py

This PR: 
Fixes SSL errors that occur from the requests library when running these scripts locally.  Originally both these scripts used: `requests.packages.urllib3.disable_warnings()` to disable warnings however is seems that the library still complains about SSL errors. In order to prevent this from occurring I've added `    requests.packages.urllib3.disable_warnings(urllib3.exceptions.InsecureRequestWarning)` which seems to work when running these scripts against a local environment

EES-1953 - fix importer.py & publisher.py local SSL errors

---

src/explore-education-statistics-admin/src/services/releaseImageService.ts
src/explore-education-statistics-frontend/package.json
src/explore-education-statistics-frontend/server.js
src/explore-education-statistics-frontend/src/modules/find-statistics/components/PublicationSectionBlocks.tsx

Alter HTTP Content-Security-Policy `img-src` directive to allow Content API as an image source.
Images were previously blocked with the error
- Remove additional `/api` in client POST url when uploading images.
- Remove additional `/api` in the `rootUrl` which is already in the image Url's when transforming content editor image nodes.
- Configure Jest to use the dotenv environment.

EES-1954 Alter HTTP Content-Security-Policy img-src directive to allow Content API as an image source.

---

tests/robot-tests/tests/admin_and_public/bau/footnotes.robot
tests/robot-tests/tests/admin_and_public/bau/publish_release_and_amend_2.robot
tests/robot-tests/tests/libs/admin-common.robot

This PR: 
- Fixes various Admin / public UI tests failures (when ran on the pipeline). The majority of failures seem to be around not finding specific elements after x amount of seconds. In order to try to fix this I've added more generous timeouts / wait assertions for the tests that are currently failing.

EES-1958 - Fix admin / public UI tests

---

src/GovUk.Education.ExploreEducationStatistics.Data.Processor/Functions/Processor.cs
src/GovUk.Education.ExploreEducationStatistics.Data.Processor/Services/DataImportService.cs

This PR makes a change to log exceptions before attempting to fail the imports which could in itself fail,
leaving us without any trace of the exception in Application Insights.
It also handles being called with a null errors array or a null error string.

EES-1914 Log exceptions before failing imports and handle null error

---

src/GovUk.Education.ExploreEducationStatistics.Admin.Tests/Services/Methodologies/MethodologyImageServiceTests.cs
src/GovUk.Education.ExploreEducationStatistics.Admin.Tests/Services/ReleaseDataFileServiceTest.cs
src/GovUk.Education.ExploreEducationStatistics.Admin.Tests/Services/ReleaseFileServiceTests.cs
src/GovUk.Education.ExploreEducationStatistics.Admin.Tests/Services/ReleaseImageServiceTests.cs
src/GovUk.Education.ExploreEducationStatistics.Admin/Controllers/Api/MigrateFilesController.cs
src/GovUk.Education.ExploreEducationStatistics.Admin/Migrations/ContentMigrations/20210311102805_EES1983AddCreatedFieldsToFile.Designer.cs
src/GovUk.Education.ExploreEducationStatistics.Admin/Migrations/ContentMigrations/20210311102805_EES1983AddCreatedFieldsToFile.cs
src/GovUk.Education.ExploreEducationStatistics.Admin/Models/DataFileInfo.cs
src/GovUk.Education.ExploreEducationStatistics.Admin/Services/Interfaces/IMigrateFilesService.cs
src/GovUk.Education.ExploreEducationStatistics.Admin/Services/Interfaces/IReleaseDataFileRepository.cs
src/GovUk.Education.ExploreEducationStatistics.Admin/Services/Interfaces/IReleaseFileRepository.cs
src/GovUk.Education.ExploreEducationStatistics.Admin/Services/Interfaces/Methodologies/IMethodologyFileRepository.cs
src/GovUk.Education.ExploreEducationStatistics.Admin/Services/Methodologies/MethodologyFileRepository.cs
src/GovUk.Education.ExploreEducationStatistics.Admin/Services/Methodologies/MethodologyImageService.cs
src/GovUk.Education.ExploreEducationStatistics.Admin/Services/MigrateFileService.cs
src/GovUk.Education.ExploreEducationStatistics.Admin/Services/ReleaseDataFileRepository.cs
src/GovUk.Education.ExploreEducationStatistics.Admin/Services/ReleaseDataFileService.cs
src/GovUk.Education.ExploreEducationStatistics.Admin/Services/ReleaseFileRepository.cs
src/GovUk.Education.ExploreEducationStatistics.Admin/Services/ReleaseFileService.cs
src/GovUk.Education.ExploreEducationStatistics.Admin/Services/ReleaseImageService.cs
src/GovUk.Education.ExploreEducationStatistics.Common.Tests/Utils/MockUtils.cs
src/GovUk.Education.ExploreEducationStatistics.Common/Extensions/BlobInfoExtensions.cs
src/GovUk.Education.ExploreEducationStatistics.Common/Services/FileStorageUtils.cs
src/GovUk.Education.ExploreEducationStatistics.Content.Model/Database/ContentDbContext.cs
src/GovUk.Education.ExploreEducationStatistics.Content.Model/File.cs
src/GovUk.Education.ExploreEducationStatistics.Data.Processor/Services/DataArchiveService.cs
src/GovUk.Education.ExploreEducationStatistics.Data.Processor/Services/SplitFileService.cs
src/GovUk.Education.ExploreEducationStatistics.Publisher.Tests/Services/ReleaseServiceTests.cs

This PR adds new Created and CreatedBy fields to File for auditing/debugging as well as displaying the "Uploaded on" field of data files in the Admin.
It also has a manual endpoint `PATCH http://localhost:5021/api/files/private/data/migrate-created-fields` to retain values of existing data files which it gets from their blobs in the Storage container.
This needs to be run prior to the files migration which changes their paths by moving the files where the Created value on the blob is reset due to the move operation being a copy and delete.

EES-1983 Add Created/CreatedBy fields to File and retain existing values when migrating data files

---

src/GovUk.Education.ExploreEducationStatistics.Publisher/Services/PublishingService.cs

This fixes a problem where after publishing a methodology we saw no files being copied from private to public storage.

EES-1997 Release containers should have been methodologies containers.

---

src/GovUk.Education.ExploreEducationStatistics.Admin/Services/Methodologies/MethodologyImageService.cs
src/GovUk.Education.ExploreEducationStatistics.Common/BlobContainers.cs

Locally methodology file containers should be:
```
devstoreaccount1/private-methodologies
devstoreaccount1/public-methodologies
```
but they were both `devstoreaccount1/methodologies`.
With only one container locally this was hiding a problem with publishing files when being tested.
- Use ForEachAsync and delete blobs prior to deleting database references. This addresses comments raised  on https://github.com/dfe-analytical-services/explore-education-statistics/pull/2416

EES-1995 Fix the naming of methodology file containers locally

---

src/GovUk.Education.ExploreEducationStatistics.Common/BlobContainers.cs
src/GovUk.Education.ExploreEducationStatistics.Content.Api.Tests/Services/FileStorageServiceTests.cs
src/GovUk.Education.ExploreEducationStatistics.Content.Api/Services/FileStorageService.cs
src/GovUk.Education.ExploreEducationStatistics.Data.Api.Tests/Services/DataBlockServiceTests.cs
src/GovUk.Education.ExploreEducationStatistics.Data.Api/Services/DataBlockService.cs
src/GovUk.Education.ExploreEducationStatistics.Data.Api/Services/FastTrackService.cs
src/GovUk.Education.ExploreEducationStatistics.Publisher/Services/ContentService.cs
src/GovUk.Education.ExploreEducationStatistics.Publisher/Services/FastTrackService.cs
src/GovUk.Education.ExploreEducationStatistics.Publisher/Services/PublishingService.cs

This PR is a rename of the Public Content `BlobContainer` field name from `PublicContentContainerName` to `PublicContent` which deliberately wasn't renamed in 01668bd0730f4a435675b67177d2390261e8cfa2 to reduce the visual diff needing to be reviewed in the PR for that work.
It resolves the comment when it was spotted by @ntsim https://github.com/dfe-analytical-services/explore-education-statistics/pull/2358#discussion_r582067426

EES-1936 Rename Public Content BlobContainer field name.

---

src/GovUk.Education.ExploreEducationStatistics.Admin/Migrations/ContentMigrations/20210317120015_EES1936RemoveDataImportMigratedField.Designer.cs
src/GovUk.Education.ExploreEducationStatistics.Admin/Migrations/ContentMigrations/20210317120015_EES1936RemoveDataImportMigratedField.cs
src/GovUk.Education.ExploreEducationStatistics.Admin/Services/DataImportService.cs
src/GovUk.Education.ExploreEducationStatistics.Content.Model/DataImport.cs

This PR removes the `DataImport.Migrated` database field which was used for debugging to differentiate rows being migrated from table storage from newer imports during the migration of https://github.com/dfe-analytical-services/explore-education-statistics/pull/2323 which moved Imports from an Azure Storage Table to the Content database.

EES-1936 Remove DataImport Migrated field

---

useful-scripts/create-emulator-release-files.py

This PR updates the Python script that we use to create Release data/metdata/ancillary files in emulator storage to remove support for creating the legacy file structure, only now creating the new structure.
It also stops adding the `userName` property to the data files after the need for it was removed by https://github.com/dfe-analytical-services/explore-education-statistics/pull/2412

EES-1936 Update emulator Release file Python script

---

src/GovUk.Education.ExploreEducationStatistics.Publisher.Model/ReleaseStatusState.cs
src/GovUk.Education.ExploreEducationStatistics.Publisher.Model/ViewModels/LegacyReleaseViewModel.cs
src/GovUk.Education.ExploreEducationStatistics.Publisher.Model/ViewModels/LinkViewModel.cs
src/GovUk.Education.ExploreEducationStatistics.Publisher.Tests/Services/MethodologyServiceTests.cs
src/GovUk.Education.ExploreEducationStatistics.Publisher/Functions/PublishReleaseFilesFunction.cs
src/GovUk.Education.ExploreEducationStatistics.Publisher/Functions/PublishReleasesFunction.cs
src/GovUk.Education.ExploreEducationStatistics.Publisher/Services/ContentService.cs
src/GovUk.Education.ExploreEducationStatistics.Publisher/Services/Interfaces/IMethodologyService.cs
src/GovUk.Education.ExploreEducationStatistics.Publisher/Services/Interfaces/IQueueService.cs
src/GovUk.Education.ExploreEducationStatistics.Publisher/Services/MethodologyService.cs
src/GovUk.Education.ExploreEducationStatistics.Publisher/Services/PublishingService.cs
src/GovUk.Education.ExploreEducationStatistics.Publisher/Services/ReleaseService.cs
src/GovUk.Education.ExploreEducationStatistics.Publisher/Services/ValidationService.cs

A Methodolgy is deliberately not published when first created and approved until it's used by a Publication/Release that is published.
This PR makes a change so that when a Release is published, as well as publishing the methodology content, it's methodology files will be published too. The files were previously missed.
On further methodology approvals, the files are already being published.

EES-1998 Publish the files of the Methodology if it's not already live

---

tests/robot-tests/tests/admin_and_public/bau/prerelease_visibility.robot
tests/robot-tests/tests/admin_and_public/bau/publish_release_and_amend.robot
tests/robot-tests/tests/general_public/release_page_absence.robot

This PR: 
- Fixes various UI tests that are currently failing on the UI testing pipeline. This is mainly due to tests timing out due to not finding elements after a certain period of time. In order to prevent this I've added more generous timeouts to the tests that are failing

EES-2008 - fix various UI tests

---

src/explore-education-statistics-frontend/src/html/glossary/C.html
src/explore-education-statistics-frontend/src/html/glossary/E.html

Adding the following definitions to the glossary as a hotfix so they appear on Production before the CIN Outcomes publication on the 25th March.
1. **Child in need**
A child in need is defined under the Children Act 1989 as a child who is unlikely to reach or maintain a satisfactory level of health or development, or their health or development will be significantly impaired without the provision of children's social care services, or the child is disabled.
On production, this definition should show at - https://explore-education-statistics.service.gov.uk/glossary#child-in-need.
2. **Child protection plan**
A [child in need](link to above definition) becomes the subject of a child protection plan if they are assessed as being at risk of harm, at an initial child protection conference.
On …

Hotfix/EES-2020 Adding CIN and EDA to the glossary

---

tests/robot-tests/tests/admin_and_public/bau/publish_release_and_amend.robot

This PR: 
- Fixes publish_release_and_amend.robot from failing. For some reason the focus seemed to be in a frozen state (focus was set to the footnotes link) which caused the test to fail after timing out. After forcing this test case to click a Summary link the test seemed to continue with other test cases and pass.

EES-2021 - Fix publish_release_and_amend.robot

---

src/GovUk.Education.ExploreEducationStatistics.Notifier/GovUk.Education.ExploreEducationStatistics.Notifier.csproj

This PR switches the GOV.UK Notify client from Bintray https://bintray.com/gov-uk-notify/nuget/Notify/2.8.0 to Nuget Gallery https://www.nuget.org/packages/GovukNotify 4.0.0 due to the upcoming Bintray sunset on 1st May.
It adds a dependency on [Jwt.Net](https://github.com/jwt-dotnet/jwt) which is required by GOV.UK Notify >= 7.0.0 && < 8.0.0.
See https://docs.notifications.service.gov.uk/net.html#net-client-documentation
and https://github.com/alphagov/notifications-net-client/blob/master/CHANGELOG.md
It also takes the opportunity to upgrade dependency `System.IdentityModel.Tokens.Jwt` to the latest version 6.9.0.

EES-2025 Use package GovukNotify

---

src/GovUk.Education.ExploreEducationStatistics.Notifier/PublicationNotifier.cs

If an error occurs we were leaking the error messages direct from the GOV.UK Notify client into our bad result response.
These errors are already logged to App Insights and are visible there so don't need to be returned in the response for the user to potentially discover.
Also removing some unused success messages which were also visible in the response.

Don't leak GOV.UK Notify errors into the response.

---

src/explore-education-statistics-admin/src/pages/release/data/components/ReleaseDataUploadsSection.tsx

Adds a confirmation line including the subject title to the delete modal.

EES-1814 add confirmation text to data upload delete modal

---

src/explore-education-statistics-admin/src/pages/release/footnotes/components/FilterGroupDetails.tsx
src/explore-education-statistics-admin/src/pages/release/footnotes/components/FootnoteForm.tsx
src/explore-education-statistics-admin/src/pages/release/footnotes/components/FootnoteSubjectSelection.tsx
src/explore-education-statistics-admin/src/pages/release/footnotes/components/IndicatorDetails.tsx
src/explore-education-statistics-admin/src/services/footnoteService.ts

Following on from https://github.com/dfe-analytical-services/explore-education-statistics/pull/2387 this fixes various UI bugs relating to the introduction of the new selection type, including:
- changing the selection type when editing a footnote
- select all behaviour for filters
It could maybe do with some more tidying and clearer naming next time we come back to it.
This could do with some thorough testing as I'm not very familiar with the footnotes so may have missed things.

EES-161 footnotes ui bug fixes

---

src/explore-education-statistics-frontend/src/modules/find-statistics/PublicationReleasePage.tsx

Sends an analytics event when the 'View data and files' button is clicked.
Not sure if the label is really necessary, but a few others had it so thought it might be standard practice if there's no more meaningful label to send.

EES-1947 Add analytics event for View data and files button

---

src/GovUk.Education.ExploreEducationStatistics.Admin.Tests/Controllers/Api/ReleasesControllerTests.cs
src/GovUk.Education.ExploreEducationStatistics.Admin.Tests/Services/ManageContent/ManageContentPageServiceTests.cs
src/GovUk.Education.ExploreEducationStatistics.Admin.Tests/Services/ReleaseDataFileServiceTest.cs
src/GovUk.Education.ExploreEducationStatistics.Admin.Tests/Services/ReleaseFileServiceTests.cs
src/GovUk.Education.ExploreEducationStatistics.Admin/Services/Interfaces/IReleaseFileRepository.cs
src/GovUk.Education.ExploreEducationStatistics.Admin/Services/Interfaces/Methodologies/IMethodologyFileRepository.cs
src/GovUk.Education.ExploreEducationStatistics.Admin/Services/Methodologies/MethodologyFileRepository.cs
src/GovUk.Education.ExploreEducationStatistics.Admin/Services/Methodologies/MethodologyImageService.cs
src/GovUk.Education.ExploreEducationStatistics.Admin/Services/ReleaseDataFileService.cs
src/GovUk.Education.ExploreEducationStatistics.Admin/Services/ReleaseFileRepository.cs
src/GovUk.Education.ExploreEducationStatistics.Admin/Services/ReleaseFileService.cs
src/GovUk.Education.ExploreEducationStatistics.Admin/Services/ReleaseImageService.cs
src/GovUk.Education.ExploreEducationStatistics.Common/Model/FileInfo.cs
src/GovUk.Education.ExploreEducationStatistics.Common/Services/FileStorageUtils.cs
src/GovUk.Education.ExploreEducationStatistics.Content.Model.Tests/Extensions/FileExtensionTests.cs
src/GovUk.Education.ExploreEducationStatistics.Content.Model.Tests/Extensions/MethodologyFileExtensionTests.cs
src/GovUk.Education.ExploreEducationStatistics.Content.Model.Tests/Extensions/ReleaseFileExtensionTests.cs
src/GovUk.Education.ExploreEducationStatistics.Content.Model/Extensions/FileExtensions.cs
src/GovUk.Education.ExploreEducationStatistics.Content.Model/Extensions/MethodologyFileExtensions.cs
src/GovUk.Education.ExploreEducationStatistics.Content.Model/Extensions/ReleaseFileExtensions.cs
src/GovUk.Education.ExploreEducationStatistics.Data.Processor/Services/DataArchiveService.cs
src/GovUk.Education.ExploreEducationStatistics.Data.Processor/Services/SplitFileService.cs
src/GovUk.Education.ExploreEducationStatistics.Publisher.Tests/Services/ReleaseServiceTests.cs
src/GovUk.Education.ExploreEducationStatistics.Publisher.Tests/Services/ZipFileServiceTests.cs
src/GovUk.Education.ExploreEducationStatistics.Publisher/Services/Interfaces/IZipFileService.cs
src/GovUk.Education.ExploreEducationStatistics.Publisher/Services/PublishingService.cs
src/GovUk.Education.ExploreEducationStatistics.Publisher/Services/ReleaseService.cs
src/GovUk.Education.ExploreEducationStatistics.Publisher/Services/ZipFileService.cs

Now that we have releaseFile.Name, we don't need to store subject names
in blob file metadata and can retrieve subject names from releaseFile.Name instead.
This currently is only happening with data files, not ancillary files.

EES-1815 Retrieve file names from releaseFile.Name where possible

---

src/explore-education-statistics-common/src/components/AccordionSection.module.scss

This seems to occur because of the absolutely positioned govuk-visually-hidden elements within accordion content. These cause the accordion content to extend the height of the page, despite being in a collapsed section.
Making the collapsed sections have relative position fixes it as the govuk-visually-hidden elements are now absolutely positioned relative to their containing section (and still remain visually hidden).

EES-2051 fix excessive footer padding on some releases

---

src/explore-education-statistics-admin/src/pages/release/footnotes/components/FootnoteForm.tsx
src/explore-education-statistics-admin/src/services/utils/footnote/__tests__/footnoteToFlatFootnote.test.ts
src/explore-education-statistics-admin/src/services/utils/footnote/footnoteToFlatFootnote.ts

Makes sure that previously selected indicators and filters aren't submitted when a footnote is changed to be for all data.
Also, handles changing a footnote subject to 'Does not apply' in footnoteToFlatFootnote instead of when the form is submitted.

EES-2044 send correct data when edit footnote

---

infrastructure/templates/datafactory/components/template.json

This PR removes the Subject `Name` field from a copy activity mapping in Data Factory config after it was removed by https://github.com/dfe-analytical-services/explore-education-statistics/pull/2480

EES-2074 Remove Name field from Copy activity mapping in Data Factory config

---

src/explore-education-statistics-admin/src/pages/release/datablocks/components/chart/__tests__/ChartLegendConfiguration.test.tsx
src/explore-education-statistics-common/src/modules/charts/components/__tests__/HorizontalBarBlock.test.tsx
src/explore-education-statistics-common/src/modules/charts/components/__tests__/LineChartBlock.test.tsx
src/explore-education-statistics-common/src/modules/charts/components/__tests__/VerticalBarBlock.test.tsx
src/explore-education-statistics-common/src/modules/charts/util/getDataSetCategoryConfigs.ts

- Removes the ordering of datasets by name so the order can be controlled by adding them in the desired order
- Updates some tests that were expecting alphabetical order

EES-907 don't order chart data by name

---

src/explore-education-statistics-common/src/modules/charts/components/MapBlockInternal.tsx

Set to the same level as the default as that's already pretty zoomed out.

EES-393 set min zoom level on maps

---

src/explore-education-statistics-common/src/modules/charts/components/ChartRenderer.tsx

Prevents a new map footnote being added each time the component re-renders.

EES-2072 prevent duplicate map footnotes appearing

---

src/explore-education-statistics-common/src/modules/charts/components/LineChartBlock.tsx
src/explore-education-statistics-common/src/modules/charts/components/VerticalBarBlock.tsx

Adds some space at the top so the top value doesn't get pushed down.

EES-62 fix y axis top value position

---

src/explore-education-statistics-common/src/modules/charts/components/MapBlockInternal.tsx
src/explore-education-statistics-common/src/modules/charts/components/__tests__/MapBlock.test.tsx

Allow users to reset the map by selecting 'Non selected' in the location dropdown. clicking this de-selects the selected area and zooms the map back out.

EES-1323 add none selected option to map location select

---

src/explore-education-statistics-common/src/modules/table-tool/components/TableHighlightsList.tsx
src/explore-education-statistics-common/src/modules/table-tool/components/__tests__/TableHighlightsList.test.tsx
src/explore-education-statistics-common/src/services/tableBuilderService.ts

This PR:
- fixes an issue with the Highlight Table search box, whereby the highlight code expected a defined description whereas there are several hundred entries live with no description available

EES-2081 - made Highlight Description non-mandatory in front end

---

src/GovUk.Education.ExploreEducationStatistics.Admin.Tests/Services/ReleaseFileServiceTests.cs
src/GovUk.Education.ExploreEducationStatistics.Admin/Controllers/Api/ReleaseFileController.cs
src/GovUk.Education.ExploreEducationStatistics.Admin/Services/Interfaces/IReleaseFileRepository.cs
src/GovUk.Education.ExploreEducationStatistics.Admin/Services/Interfaces/IReleaseFileService.cs
src/GovUk.Education.ExploreEducationStatistics.Admin/Services/ReleaseFileRepository.cs
src/GovUk.Education.ExploreEducationStatistics.Admin/Services/ReleaseFileService.cs
src/explore-education-statistics-admin/src/pages/release/ReleasePageContainer.tsx
src/explore-education-statistics-admin/src/pages/release/data/ReleaseAncillaryFilePage.tsx
src/explore-education-statistics-admin/src/pages/release/data/ReleaseDataFilePage.tsx
src/explore-education-statistics-admin/src/pages/release/data/ReleaseDataFileReplacePage.tsx
src/explore-education-statistics-admin/src/pages/release/data/ReleaseDataFileReplacementCompletePage.tsx
src/explore-education-statistics-admin/src/pages/release/data/ReleaseDataPage.tsx
src/explore-education-statistics-admin/src/pages/release/data/__tests__/ReleaseDataFileReplacePage.test.tsx
src/explore-education-statistics-admin/src/pages/release/data/components/ReleaseDataUploadsSection.tsx
src/explore-education-statistics-admin/src/pages/release/data/components/ReleaseFileUploadsSection.tsx
src/explore-education-statistics-admin/src/pages/release/data/components/__tests__/ReleaseDataUploadsSection.test.tsx
src/explore-education-statistics-admin/src/pages/release/data/components/__tests__/ReleaseFileUploadsSection.test.tsx
src/explore-education-statistics-admin/src/routes/releaseRoutes.ts
src/explore-education-statistics-admin/src/services/releaseAncillaryFileService.ts
src/explore-education-statistics-admin/src/services/releaseChartFileService.ts
src/explore-education-statistics-admin/src/services/releaseDataFileService.ts

On the backend, this PR adds two endpoints, one to rename ReleaseFiles.Name for Data or Ancillary files. The other gets a single Ancillary file's FileInfo.
On the frontend, this adds two pages for editing data file and ancillary file details, and links to those pages.

EES-1512 Add ability to rename Data and Ancillary files

---

src/GovUk.Education.ExploreEducationStatistics.Admin.Tests/Services/ReplacementServiceTests.cs
src/GovUk.Education.ExploreEducationStatistics.Admin/Services/ReplacementService.cs
src/GovUk.Education.ExploreEducationStatistics.Admin/ViewModels/DataReplacementPlanViewModel.cs
src/explore-education-statistics-admin/src/pages/release/data/components/DataFileReplacementPlan.tsx
src/explore-education-statistics-admin/src/pages/release/data/components/__tests__/DataFileReplacementPlan.test.tsx
src/explore-education-statistics-admin/src/services/dataReplacementService.ts

This PR:
- flags a data block as invalid if a whole new filter is introduced in a replacement subject
- marks scenarios as fixable / unfixable depending upon whether or not the user can edit and fix a data block with the current screens available, and only presents the "Edit Data Block" in the Replacement screen if it's fixable
- fixes a bug in the Replacement screen whereby deleting the last invalid items would not then show the "Confirm replacement" button

EES-2087 - invalid data blocks

---

src/explore-education-statistics-admin/src/pages/release/datablocks/components/chart/ChartConfiguration.tsx

Removes validation that prevents the chart preview from updating unless the required fields (title and alt) are filled.
I couldn't think of a reason the validation needed to there for the onChange event and have checked it hasn't changed how the validation works when the form is submitted or the required fields changed. Let me know if there's something I'm missing that requires it.

EES-1236 remove validation preventing chart preview update

---

src/GovUk.Education.ExploreEducationStatistics.Publisher.Tests/Services/ReleaseServiceTests.cs
src/GovUk.Education.ExploreEducationStatistics.Publisher/Services/ReleaseService.cs

When we create the cache Release content view model, we do that at midnight (or just before publishing when the publishing mode is immediate) and so the published date in the database isn't set yet, since it's only set once we actually complete publishing.
This means we have to set a published date in the view model otherwise it would be empty if just mapped from the database values.
If it's already been published (i.e. we are republishing for some reason), it will already be set.
Otherwise, it was previously set based on the expected publishing time worked out when the function execution beings.
This PR makes a change so that if it's an amendment, it's set to the value of the previous version so that amended releases continue to show the original published date rather than the date they …

EES-2084 Cached Release view model for amendments should use published date of previous release.

---

src/explore-education-statistics-frontend/src/hooks/useCookies.ts

Increases the banner seen cookie length to 1 year, this is still shorter than the analytics one but 10 years seemed to long and this makes it consistent with the gov.uk equivalent (see https://www.gov.uk/help/cookie-details).
Note for testing: this will also update the info on https://explore-education-statistics.service.gov.uk/cookies/details

EES-2059 increase cookie banner cookie expiry

---

src/explore-education-statistics-admin/src/components/editable/Comments.tsx

EES-1016 - order comments by created date, most recent at top. Previously new comments would be added at the top then shown at the bottom of the list after refresh.
EES-1158 - clear the comment field after adding a new comment. Included in this PR as I noticed and it while doing the above and belatedly realised there was a ticket for it.

EES-1016 order comments, EES-1158 reset comment form

---

infrastructure/templates/template.json
src/GovUk.Education.ExploreEducationStatistics.Admin.Tests/Services/EmailTemplateServiceTests.cs
src/GovUk.Education.ExploreEducationStatistics.Admin/Services/EmailTemplateService.cs
src/GovUk.Education.ExploreEducationStatistics.Admin/appsettings.Development.json

This PR completes the changes for adding a new resource role to a Publication for a User by sending an email to the user using a new Gov.Uk Notify email template that has been set up for it.

EES-2311 Send email when assigning a Publication role to a user

---

src/explore-education-statistics-admin/src/pages/release/datablocks/components/DataBlockPageReadOnlyTabs.tsx
src/explore-education-statistics-admin/src/pages/release/datablocks/components/DataBlockPageTabs.tsx
src/explore-education-statistics-admin/src/pages/release/pre-release/PreReleaseTableToolPage.tsx
src/explore-education-statistics-common/src/modules/find-statistics/components/DataBlockTabs.tsx
src/explore-education-statistics-common/src/modules/find-statistics/components/__tests__/DataBlockTabs.test.tsx
src/explore-education-statistics-common/src/modules/table-tool/components/TableToolWizard.tsx
src/explore-education-statistics-common/src/modules/table-tool/components/__tests__/TimePeriodDataTable.test.tsx
src/explore-education-statistics-common/src/modules/table-tool/utils/__tests__/getDefaultTableHeadersConfig.test.ts
src/explore-education-statistics-common/src/modules/table-tool/utils/__tests__/mapTableHeadersConfig.test.ts
src/explore-education-statistics-common/src/modules/table-tool/utils/getDefaultTableHeadersConfig.ts
src/explore-education-statistics-common/src/modules/table-tool/utils/mapTableHeadersConfig.ts
src/explore-education-statistics-frontend/src/modules/permalink/PermalinkPage.tsx
src/explore-education-statistics-frontend/src/modules/table-tool/TableToolPage.tsx

When terms were used for time periods in the table tool extra terms were shown in the reorder table headers list, this PR filters the unnecessary ones out.

EES-1126 show correct time period table headers in reorder list

---

src/explore-education-statistics-admin/src/pages/release/data/ReleaseDataFileReplacePage.tsx
src/explore-education-statistics-admin/src/pages/release/data/components/DataFileDetailsTable.tsx
src/explore-education-statistics-admin/src/pages/release/data/components/DataFileReplacementPlan.tsx
src/explore-education-statistics-admin/src/pages/release/data/components/DataFileUploadForm.tsx
src/explore-education-statistics-admin/src/pages/release/data/components/ReleaseDataUploadsSection.tsx
src/explore-education-statistics-admin/src/pages/release/data/components/__tests__/ReleaseDataUploadsSection.test.tsx
src/explore-education-statistics-admin/src/services/releaseDataFileService.ts

When a zip file is uploaded leave the file size and number of rows blanks until the file is being processed and that information is available.
Noticed a couple of related places where state was trying to update on an unmounted component so have fixed those by checking if the component us mounted in the relevant places.

EES-1397 show correct file size and rows when upload zips

---

src/explore-education-statistics-common/src/components/SummaryListItem.tsx
src/explore-education-statistics-common/src/modules/table-tool/components/__tests__/__snapshots__/FiltersForm.test.tsx.snap
src/explore-education-statistics-common/src/services/publicationService.ts
src/explore-education-statistics-frontend/src/modules/find-statistics/PublicationReleasePage.tsx
src/explore-education-statistics-frontend/src/modules/find-statistics/__tests__/PublicationReleasePage.test.tsx
src/explore-education-statistics-frontend/src/modules/table-tool/__tests__/__snapshots__/TableToolPage.test.tsx.snap
src/explore-education-statistics-frontend/src/modules/table-tool/components/__tests__/TableToolFinalStep.test.tsx

This PR:
- removes the "Next update" section from the public Publication Release page if this is not the latest Release

EES-941 - removed Next update section from Publication Release page if not the latest Release

---

src/explore-education-statistics-admin/src/components/editable/EditableContentBlock.tsx
src/explore-education-statistics-admin/src/components/editable/EditableContentForm.tsx
src/explore-education-statistics-admin/src/components/form/FormFieldEditor.tsx
src/explore-education-statistics-admin/src/contexts/EditingContext.tsx
src/explore-education-statistics-admin/src/pages/release/content/ReleaseContentPage.tsx
src/explore-education-statistics-admin/src/pages/release/content/components/ReleaseContent.tsx
src/explore-education-statistics-admin/src/pages/release/content/components/ReleaseContentAccordionSection.tsx
src/explore-education-statistics-admin/src/pages/release/content/components/ReleaseEditableBlock.tsx
src/explore-education-statistics-admin/src/pages/release/content/components/ReleaseHeadlines.tsx
src/explore-education-statistics-admin/src/pages/release/content/components/__tests__/ReleaseEditableBlock.test.tsx
src/explore-education-statistics-admin/src/pages/release/content/components/utils/__tests__/unSavedEdits.test.ts
src/explore-education-statistics-admin/src/pages/release/content/components/utils/unSavedEdits.ts

- Shows a warning at the top if there are unsaved text block changes on the content tab
- If the changes are in an accordion section it shows '(Unsaved changes)' in the heading

EES-197 unsaved changes warning

---

src/GovUk.Education.ExploreEducationStatistics.Admin.Tests/Services/PublicationRepositoryTests.cs
src/GovUk.Education.ExploreEducationStatistics.Admin.Tests/Services/PublicationServicePermissionTests.cs
src/GovUk.Education.ExploreEducationStatistics.Admin/Services/Interfaces/IPublicationRepository.cs
src/GovUk.Education.ExploreEducationStatistics.Admin/Services/PublicationRepository.cs
src/GovUk.Education.ExploreEducationStatistics.Admin/Services/PublicationService.cs

This PR fixes a bug where Publications without any Releases that should be included in the 'My Publications' result because they are granted via the Publication Owner role to the user were being excluded.

EES-2353 Include Publications granted by Publication Owner that have no Releases in the 'My Publications' result

---

src/GovUk.Education.ExploreEducationStatistics.Admin.Tests/Security/AuthorizationHandlers/ReleaseStatusAuthorizationHandlersTests.cs
src/GovUk.Education.ExploreEducationStatistics.Admin/Security/AuthorizationHandlers/ReleaseStatusAuthorizationHandlers.cs

This PR allows Publication Owner to move Release sign-off statuses between Draft and Higher Level Review.
Because of a security check on updating the status when updating a Release, even if the status is not changing, the Publication Owner was unable to update a Release. This caused other bugs such as not being able to update the Pre-Release access list.

EES-2355 Allow Publication Owner to change Release statuses between Draft and Higher Level Review

---

src/GovUk.Education.ExploreEducationStatistics.Admin.Tests/Controllers/Api/Methodologies/MethodologyControllerTests.cs
src/GovUk.Education.ExploreEducationStatistics.Admin.Tests/Services/Methodologies/MethodologyServiceTests.cs
src/GovUk.Education.ExploreEducationStatistics.Admin.Tests/Services/PublicationServiceTests.cs
src/GovUk.Education.ExploreEducationStatistics.Admin/Controllers/Api/Methodologies/MethodologyController.cs
src/GovUk.Education.ExploreEducationStatistics.Admin/Mappings/MappingProfiles.cs
src/GovUk.Education.ExploreEducationStatistics.Admin/Migrations/ContentMigrations/20210601153005_EES2195AddPublicationMethodology.Designer.cs
src/GovUk.Education.ExploreEducationStatistics.Admin/Migrations/ContentMigrations/20210601153005_EES2195AddPublicationMethodology.cs
src/GovUk.Education.ExploreEducationStatistics.Admin/Migrations/ContentMigrations/20210601153649_EES2195InitPublicationMethodology.Designer.cs
src/GovUk.Education.ExploreEducationStatistics.Admin/Migrations/ContentMigrations/20210601153649_EES2195InitPublicationMethodology.cs
src/GovUk.Education.ExploreEducationStatistics.Admin/Services/Interfaces/Methodologies/IMethodologyService.cs
src/GovUk.Education.ExploreEducationStatistics.Admin/Services/Methodologies/MethodologyService.cs
src/GovUk.Education.ExploreEducationStatistics.Admin/Services/PublicationService.cs
src/GovUk.Education.ExploreEducationStatistics.Admin/Validators/ValidationUtils.cs
src/GovUk.Education.ExploreEducationStatistics.Admin/ViewModels/Methodology/MethodologyCreateRequest.cs
src/GovUk.Education.ExploreEducationStatistics.Admin/ViewModels/PublicationViewModels.cs
src/GovUk.Education.ExploreEducationStatistics.Content.Model/Database/ContentDbContext.cs
src/GovUk.Education.ExploreEducationStatistics.Content.Model/Methodology.cs
src/GovUk.Education.ExploreEducationStatistics.Content.Model/MethodologyParent.cs
src/GovUk.Education.ExploreEducationStatistics.Content.Model/PublicationMethodology.cs
src/GovUk.Education.ExploreEducationStatistics.Content.Model/Release.cs
src/GovUk.Education.ExploreEducationStatistics.Content.Model/Versioned.cs
src/explore-education-statistics-admin/src/pages/methodology/MethodologiesPage.tsx
src/explore-education-statistics-admin/src/pages/methodology/MethodologyCreatePage.tsx
src/explore-education-statistics-admin/src/routes/routes.ts
src/explore-education-statistics-admin/src/services/methodologyService.ts

This PR adds two database migrations which in order:
`EES2195AddPublicationMethodology`:
- Alter existing fields  Slug, Content and Annexes of Methodology making them not nullable. This is a side effect of adding the `nullable` directive to `Methodology.cs` which was done to make it clearer that certain fields like the new `CreatedBy` and `PreviousVersion` fields are optional. Unless we decide to also make Slug, Content and Annexes optional, they are now `not null` in the database after generating this migration. Fields Summary and InternalReleaseNote remain as nullable by now marking them as optional in the code.
- Add versionable fields CreatedBy, CreatedById, PreviousVersionId, and Version to Methodology. It wasn't possible to use the existing `Versionable` abstract class as the fields …

EES-2195 EES-2196 Schema, model changes and data migration to support methodology versions, and publications that can have multiple Methodologies

---

src/explore-education-statistics-admin/src/components/ReleaseServiceStatus.tsx
src/explore-education-statistics-admin/src/pages/admin-dashboard/components/ReleaseSummary.tsx

Updates the release tags on the admin dashboard:
- if a release is approved and complete show green 'Published' tag
- if a release is approved and scheduled show blue 'Scheduled' tag (this includes on the Scheduled releases tab)
This PR should also fix the issue raised in https://dfedigital.atlassian.net/browse/EES-791 of the loading spinner always showing. The lazy loader seems unnecessary here as it's not used in other places the release status is shown, and wasn't working, so I've removed it.
I couldn't recreate the other issue on EES-791 where not all the scheduled releases showed and there was a chunk error in the console, so it may have been fixed since this ticket was raised.

EES-51 published and scheduled tags

---

src/GovUk.Education.ExploreEducationStatistics.Notifier/PublicationNotifier.cs
src/GovUk.Education.ExploreEducationStatistics.Publisher/Functions/PublishReleaseContentFunction.cs
src/GovUk.Education.ExploreEducationStatistics.Publisher/Functions/PublishReleasesFunction.cs
src/GovUk.Education.ExploreEducationStatistics.Publisher/Functions/PublishStagedReleaseContentFunction.cs
src/GovUk.Education.ExploreEducationStatistics.Publisher/Functions/RetryStageFunction.cs

This PR removes superfluous usages of `Date.Now` (i.e. in logging information) with `Date.UtcNow`. 
Currently there is a problem with how dates are stored in Azure blobs and the differences between local Azure blob environments & production Azure blob environments. Because of this difference the majority of `Date.Now` usages have been left in the codebase.

EES-417 - replace Now with UtcNow

---

src/explore-education-statistics-admin/package.json
src/explore-education-statistics-admin/src/pages/admin-dashboard/components/MethodologySummary.tsx
src/explore-education-statistics-admin/src/pages/admin-dashboard/components/__tests__/MethodologySummary.test.tsx
src/explore-education-statistics-admin/src/services/methodologyService.ts
src/explore-education-statistics-admin/src/services/publicationService.ts
src/explore-education-statistics-admin/test/createMemoryHistoryWithMockedPush.ts
src/explore-education-statistics-admin/tsconfig.json

Adds logic for showing the amend, edit, view and cancel methodology buttons. The logic here is copied from release amendments so may need to be adapted if it's different for methodologies.
Hooks up the amend and cancel buttons to what I expect the service to be, again copied from release amendments so may need altering. There are confirmation modals for both buttons.
I've assumed the permissions will be similar to releases so this may need changing.
None of this is visible currently as methodologies can't be created. I override the methodology with a test one to check it.
I shamelessly copied createMemoryHistoryWithMockedPush.ts from @duncan-at-hiveit's PR https://github.com/dfe-analytical-services/explore-education-statistics/pull/2579

EES-2199 amend methodology and related buttons

---

src/explore-education-statistics-common/src/modules/table-tool/components/TableToolWizard.tsx

Currently in the table tool if you select a table highlight, then go back to step 1, select the same publication then the same highlight you get stuck on step 2 instead of showing the highlight.
Trying to force update the step, see https://github.com/dfe-analytical-services/explore-education-statistics/pull/2584 (or do it a nicer way) ended up causing other problems - changing filters after then re-selecting wouldn't reset the filters to the highlight table ones.
So I've changed approach and am now resetting the url when you go back to step 1, this fixes the original problem and the only side effect is that the original publication isn't still selected, which I think is ok. 
If you've gone through the table tool without the fast track and go back to step 1, it still keeps your previous …

EES-2361 reset table tool route when edit publication

---

src/GovUk.Education.ExploreEducationStatistics.Admin.Tests/Services/Methodologies/MethodologyRepositoryTests.cs
src/GovUk.Education.ExploreEducationStatistics.Admin/Mappings/MyPublicationPermissionSetPropertyResolver.cs
src/GovUk.Education.ExploreEducationStatistics.Admin/Services/Methodologies/MethodologyRepository.cs
src/GovUk.Education.ExploreEducationStatistics.Admin/ViewModels/MyPublicationViewModel.cs
src/explore-education-statistics-admin/src/pages/admin-dashboard/components/MethodologySummary.tsx
src/explore-education-statistics-admin/src/pages/admin-dashboard/components/__tests__/ManagePublicationsAndReleasesTab.test.tsx
src/explore-education-statistics-admin/src/pages/admin-dashboard/components/__tests__/MethodologySummary.test.tsx
src/explore-education-statistics-admin/src/pages/methodology/edit-methodology/MethodologyPage.tsx
src/explore-education-statistics-admin/src/pages/methodology/edit-methodology/summary/MethodologySummaryEditPage.tsx
src/explore-education-statistics-admin/src/pages/methodology/edit-methodology/summary/MethodologySummaryPage.tsx
src/explore-education-statistics-admin/src/pages/release/components/ReleaseStatusChecklist.tsx
src/explore-education-statistics-admin/src/pages/release/components/__tests__/ReleaseStatusChecklist.test.tsx
src/explore-education-statistics-admin/src/routes/methodologyRoutes.ts
src/explore-education-statistics-admin/src/routes/routes.ts
src/explore-education-statistics-admin/src/services/publicationService.ts

This PR:
- controls the visibility of the Create Methodology and Link to External Methodology buttons based on permissions checks
- controls the visibility of the Edit and Remove External Methodology buttons based on permissions checks
- refactors the Methodology routes to not have them always under the context of a particular Publication

Ees 2220 add create methodology permissions to front end

---

src/explore-education-statistics-admin/src/components/editable/Comments.tsx
src/explore-education-statistics-admin/src/components/editable/__tests__/Comments.test.tsx
src/explore-education-statistics-admin/src/pages/release/content/ReleaseContentPage.tsx
src/explore-education-statistics-admin/src/pages/release/content/contexts/ReleaseContentContext.tsx
src/explore-education-statistics-admin/src/pages/release/content/contexts/__tests__/ReleaseContentContext.test.tsx
src/explore-education-statistics-admin/src/pages/release/content/utils/getUnresolvedComments.ts

Comments fixes:
- Only shows the unresolved comments warning if there are some
- Updates the  unresolved comments warning when comments are added and deleted
- Fixes problem where the wrong comment id could be sent when editing or deleting comments causing either the wrong comment to be edited / deleted or a permissions error

EES-2338 fix editing, deleting and num of unresolved comments

---

src/explore-education-statistics-admin/src/pages/release/datablocks/components/chart/ChartDataSetsConfiguration.tsx
src/explore-education-statistics-admin/src/pages/release/datablocks/components/chart/__tests__/ChartDataSetsConfiguration.test.tsx

Adds options to add all filters and indicators when creating charts. Each is added as a separate row as if they'd been added individually. For filters I've call it 'Add options' so we don't have to worry about pluralising the actual filter name.

EES-1326 Add all options for filters and indicators on charts

---

src/explore-education-statistics-admin/src/pages/release/datablocks/components/chart/ChartBuilderPreview.tsx

I'm not sure about this one... the code I've removed here was forcing charts to re-render when any of their configuration props changed, for example editing the title. For infographics this meant that the image was being fetched on each re-render. For other chart types it causes a brief flicker as the chart disappeared and reappeared.
I've tested changing config options for charts, maps and infographics, including resizing them, and they all seem to update correctly.
But clearly it was added for a reason so it may have been decided at the time that the flickering & fetches were the lesser evil.
Thoughts and opinions welcome 😃

EES-1256 prevent unnecessary chart re-renders

---

src/GovUk.Education.ExploreEducationStatistics.Admin.Tests/Services/ManageContent/ManageContentPageServiceTests.cs
src/GovUk.Education.ExploreEducationStatistics.Admin/Mappings/MappingProfiles.cs
src/GovUk.Education.ExploreEducationStatistics.Admin/Services/ManageContent/ManageContentPageService.cs
src/GovUk.Education.ExploreEducationStatistics.Admin/Services/UserManagementService.cs
src/GovUk.Education.ExploreEducationStatistics.Common/Model/Either.cs
src/explore-education-statistics-admin/src/pages/release/content/components/ReleaseContent.tsx
src/explore-education-statistics-admin/src/pages/release/content/components/ReleaseHelpAndSupportSection.tsx

This PR adds the functionality to show links to the latest methodology (or methodologies) of the Publication on the Manage Content page of a Release.
This was removed at the beginning of SOW4 work and is now reintroduced with support for multiple methodologies. Each methodology may have multiple versions. In the Admin a link to the latest version is shown for each Methodology.

EES-2395 Show links to Methodologies from Admin Manage Content page

---

src/explore-education-statistics-admin/src/pages/release/content/components/ReleaseContent.tsx
src/explore-education-statistics-admin/src/pages/release/content/components/ReleaseHelpAndSupportSection.tsx
src/explore-education-statistics-frontend/src/modules/find-statistics/PublicationReleaseHelpAndSupportSection.tsx
src/explore-education-statistics-frontend/src/modules/find-statistics/PublicationReleasePage.tsx

On release pages:
- adds a link to contact us from the useful information section
- adds a caption to the contact us accordion

EES-2430 contact us caption and link on release page

---

src/GovUk.Education.ExploreEducationStatistics.Admin.Tests/Mappings/MyMethodologyPermissionsPropertyResolverTest.cs
src/GovUk.Education.ExploreEducationStatistics.Admin.Tests/Mappings/MyPublicationPermissionsPropertyResolverTest.cs
src/GovUk.Education.ExploreEducationStatistics.Admin.Tests/Mappings/MyReleasePermissionsPropertyResolverTest.cs
src/GovUk.Education.ExploreEducationStatistics.Admin.Tests/Security/AuthorizationHandlers/CreateMethodologyForSpecificPublicationAuthorizationHandlerTests.cs
src/GovUk.Education.ExploreEducationStatistics.Admin.Tests/Security/AuthorizationHandlers/ManageExternalMethodologyForSpecificPublicationAuthorizationHandlerTests.cs
src/GovUk.Education.ExploreEducationStatistics.Admin.Tests/Services/MapperUtils.cs
src/GovUk.Education.ExploreEducationStatistics.Admin.Tests/Services/PublicationRepositoryTests.cs
src/GovUk.Education.ExploreEducationStatistics.Admin.Tests/Services/PublicationServicePermissionTests.cs
src/GovUk.Education.ExploreEducationStatistics.Admin/Mappings/Interfaces/IMyMethodoloyPermissionSetPropertyResolver.cs
src/GovUk.Education.ExploreEducationStatistics.Admin/Mappings/MappingProfiles.cs
src/GovUk.Education.ExploreEducationStatistics.Admin/Mappings/MyMethodologyPermissionSetPropertyResolver.cs
src/GovUk.Education.ExploreEducationStatistics.Admin/Mappings/MyPublicationPermissionSetPropertyResolver.cs
src/GovUk.Education.ExploreEducationStatistics.Admin/Security/AuthorizationHandlers/CreateMethodologyForSpecificPublicationAuthorizationHandlers.cs
src/GovUk.Education.ExploreEducationStatistics.Admin/Security/AuthorizationHandlers/ManageExternalMethodologyForSpecificPublicationAuthorizationHandlers.cs
src/GovUk.Education.ExploreEducationStatistics.Admin/Security/SecurityPolicies.cs
src/GovUk.Education.ExploreEducationStatistics.Admin/Security/StartupSecurityConfiguration.cs
src/GovUk.Education.ExploreEducationStatistics.Admin/Services/Interfaces/Security/UserServiceExtensions.cs
src/GovUk.Education.ExploreEducationStatistics.Admin/Services/PublicationService.cs
src/GovUk.Education.ExploreEducationStatistics.Admin/Startup.cs
src/GovUk.Education.ExploreEducationStatistics.Admin/ViewModels/MyMethodologyViewModel.cs
src/GovUk.Education.ExploreEducationStatistics.Admin/ViewModels/MyPublicationViewModel.cs
src/explore-education-statistics-admin/src/pages/admin-dashboard/components/MethodologySummary.tsx
src/explore-education-statistics-admin/src/pages/admin-dashboard/components/PublicationSummary.tsx
src/explore-education-statistics-admin/src/pages/admin-dashboard/components/__tests__/ManagePublicationsAndReleasesTab.test.tsx
src/explore-education-statistics-admin/src/pages/admin-dashboard/components/__tests__/MethodologySummary.test.tsx
src/explore-education-statistics-admin/src/services/methodologyService.ts
src/explore-education-statistics-admin/src/services/publicationService.ts
src/explore-education-statistics-admin/test/createMemoryHistoryWithMockedPush.ts

This PR:
- returns Methodologies with Publications for the Admin Dashboard
- adds proper permissions around the Methodology actions
Still to do: need to only allow each Publication to own a single Methodology.

EES-2024 Put Methodology links back on the Admin Dashboard

---

tests/robot-tests/scripts/get_auth_tokens.py
tests/robot-tests/scripts/pipeline-run-rf-tests.sh
tests/robot-tests/tests/admin/bau/create_data_block_with_chart.robot
tests/robot-tests/tests/admin/bau/create_publication_and_release.robot
tests/robot-tests/tests/admin/bau/delete_subject.robot
tests/robot-tests/tests/admin/bau/prerelease.robot
tests/robot-tests/tests/admin/bau/release_status.robot
tests/robot-tests/tests/admin_and_public/bau/prerelease_visibility.robot
tests/robot-tests/tests/admin_and_public/bau/publish_data.robot
tests/robot-tests/tests/admin_and_public/bau/publish_release_and_amend.robot
tests/robot-tests/tests/admin_and_public/bau/publish_release_and_amend_2.robot
tests/robot-tests/tests/admin_and_public/bau/release_and_publication_role_permissions.robot
tests/robot-tests/tests/general_public/release_page_absence.robot
tests/robot-tests/tests/general_public/table_tool_absence_by_characteristic.robot
tests/robot-tests/tests/general_public/table_tool_exclusions_by_geographic_level.robot
tests/robot-tests/tests/libs/admin-common.robot
tests/robot-tests/tests/libs/charts.robot
tests/robot-tests/tests/libs/common.robot
tests/robot-tests/tests/libs/utilities.py

This PR fixes a variety of UI tests that are currently failing in CI due to timeout-related issues. In addition to this, an argument has been added to the run tests bash script to allow pabot to make use of more than 2 processes. This offers a nice performance boost when tests are running in CI

Ees 2411 - Various UI test failure fixes

---

src/GovUk.Education.ExploreEducationStatistics.Admin/Services/Methodologies/MethodologyService.cs
src/GovUk.Education.ExploreEducationStatistics.Content.Api.Tests/Controllers/ThemeControllerTests.cs
src/GovUk.Education.ExploreEducationStatistics.Content.Api.Tests/Services/MethodologyServiceTests.cs
src/GovUk.Education.ExploreEducationStatistics.Content.Api/Controllers/ThemeController.cs
src/GovUk.Education.ExploreEducationStatistics.Content.Api/Services/Interfaces/IMethodologyService.cs
src/GovUk.Education.ExploreEducationStatistics.Content.Api/Services/MethodologyService.cs
src/GovUk.Education.ExploreEducationStatistics.Publisher.Model/ViewModels/MethodologyTreeNode.cs
src/GovUk.Education.ExploreEducationStatistics.Publisher.Model/ViewModels/PublicationMethodologiesTreeNode.cs
src/GovUk.Education.ExploreEducationStatistics.Publisher.Tests/Services/MethodologyServiceTests.cs
src/GovUk.Education.ExploreEducationStatistics.Publisher/Services/Interfaces/IMethodologyService.cs
src/GovUk.Education.ExploreEducationStatistics.Publisher/Services/MethodologyService.cs
src/explore-education-statistics-common/src/services/themeService.ts
src/explore-education-statistics-frontend/src/modules/methodologies/components/MethodologyList.tsx

This PR reinstates the back end support for the public View All Methodologies view produced from the Content API.
It also alters the public view to support a Publication having multiple methodologies.

EES-2378 Reinstate support for the public View All Methodologies page and support multiple Methodologies

---

src/GovUk.Education.ExploreEducationStatistics.Admin.Tests/Services/ReleaseServicePermissionTests.cs
src/GovUk.Education.ExploreEducationStatistics.Admin.Tests/Services/ReleaseServiceTests.cs
src/GovUk.Education.ExploreEducationStatistics.Admin/Controllers/Api/ReleasesController.cs
src/GovUk.Education.ExploreEducationStatistics.Admin/Services/Interfaces/IReleaseService.cs
src/GovUk.Education.ExploreEducationStatistics.Admin/Services/ReleaseService.cs
src/GovUk.Education.ExploreEducationStatistics.Admin/ViewModels/ReleaseViewModels.cs
src/explore-education-statistics-admin/src/pages/release/ReleaseStatusEditPage.tsx
src/explore-education-statistics-admin/src/services/releaseService.ts

The same release update endpoint is being used on three different pages: to change a release's ApprovalStatus, to add/edit PreRelease access list content, and to alter a release's summary info. 
By only adding a new ReleaseStatus row when the ApprovalStatus changes, we ensure that we only add a new ReleaseStatus entry when the user is on the Sign off page. This prevents the endpoint erroring if it is used to add/edit an access list or edit a release's summary info.

EES-2448 Only create ReleaseStatus row if ApprovalStatus changes

---

tests/robot-tests/report-modifiers/CheckForAtLeastOnePassingRunPrerebotModifier.py
tests/robot-tests/run_tests.py
tests/robot-tests/tests/admin/bau/create_data_block_with_chart.robot
tests/robot-tests/tests/admin/bau/create_publication_and_release.robot
tests/robot-tests/tests/admin/bau/prerelease.robot
tests/robot-tests/tests/admin/bau/release_status.robot
tests/robot-tests/tests/admin_and_public/bau/prerelease_visibility.robot
tests/robot-tests/tests/admin_and_public/bau/publish_release_and_amend.robot
tests/robot-tests/tests/admin_and_public/bau/publish_release_and_amend_2.robot
tests/robot-tests/tests/admin_and_public/bau/release_and_publication_role_permissions.robot
tests/robot-tests/tests/general_public/table_tool_absence_by_characteristic.robot
tests/robot-tests/tests/general_public/table_tool_exclusions_by_geographic_level.robot
tests/robot-tests/tests/libs/admin-common.robot
tests/robot-tests/tests/libs/common.robot
tests/robot-tests/tests/libs/utilities.py

This PR:
- fixes up the rest of the latest UI test failures on the dev branch (and marks a few as Failing until later work)
- adds additional rerun failed tests support by adding a Prerebot Model Modifier that marks a test as PASSing if it passed on either the original run or the rerun, and merges that result into the rerun's report file

Ees 2222 fix UI tests on dev before tests on 2222 branch

---

src/GovUk.Education.ExploreEducationStatistics.Admin.Tests/Controllers/Api/ReleasesControllerTests.cs
src/GovUk.Education.ExploreEducationStatistics.Admin.Tests/Services/ReleaseServicePermissionTests.cs
src/GovUk.Education.ExploreEducationStatistics.Admin.Tests/Services/ReleaseServiceTests.cs
src/GovUk.Education.ExploreEducationStatistics.Admin/Controllers/Api/ReleasesController.cs
src/GovUk.Education.ExploreEducationStatistics.Admin/Services/Interfaces/IReleaseService.cs
src/GovUk.Education.ExploreEducationStatistics.Admin/Services/ReleaseService.cs
src/GovUk.Education.ExploreEducationStatistics.Admin/ViewModels/ReleaseViewModels.cs
src/explore-education-statistics-admin/src/pages/release/ReleaseStatusEditPage.tsx
src/explore-education-statistics-admin/src/pages/release/ReleaseSummaryEditPage.tsx
src/explore-education-statistics-admin/src/pages/release/pre-release/ReleasePreReleaseAccessPage.tsx
src/explore-education-statistics-admin/src/services/releaseService.ts

After EES-2448, the ReleaseUpdate method still allowed the changing of the ApprovalStatus of a release even though the frontend didn't use this functionality, and if it were to be used to publish a release it would lead to bugs because the backend now only expects releases to be published with the ReleaseStatusUpdate method.
This PR fixes this issue by changing ReleaseUpdate to ReleaseUpdateInfo. This method is now only used on two pages - when editing a release's details (i.e. timeperiodcoverage, year, release type) and when adding or editing a prerelease access list.

EES-2450 Change UpdateRelease into UpdateReleaseInfo

---

tests/robot-tests/tests/admin/bau/create_methodology_for_publication.robot
tests/robot-tests/tests/admin_and_public/bau/publish_release_and_amend_2.robot
tests/robot-tests/tests/libs/admin-common.robot

This PR:
- fixes a bug in the "view methodology of publication" journey.
- adds test for editing and approving a newly created methodology.
- removes some dynamic test case names, as these don't play well with the report merging that happens when re-running failed test suites.

Ees 2222 UI tests for sow4 create methodology flow 2

---

src/GovUk.Education.ExploreEducationStatistics.Admin.Tests/Services/ReleaseServiceTests.cs

This PR removes a reference to InternalReleaseNote on Release on the SOW4 branch.
This attribute was removed on the dev branch by 2b5e7a3c2daaafff53d017218399fcaf4bb5086a but despite there being no changes to pull in, it still exists for some reason so this PR removes it.

EES-2423 Remove reference to InternalReleaseNote on SOW4 branch

---

src/GovUk.Education.ExploreEducationStatistics.Admin.Tests/Services/Methodologies/MethodologyServiceTests.cs
src/GovUk.Education.ExploreEducationStatistics.Admin/Services/Methodologies/MethodologyService.cs
src/GovUk.Education.ExploreEducationStatistics.Publisher.Tests/Services/MethodologyServiceTests.cs
src/GovUk.Education.ExploreEducationStatistics.Publisher.Tests/Services/ReleaseServiceTests.cs
src/GovUk.Education.ExploreEducationStatistics.Publisher/Functions/PublishReleaseContentFunction.cs
src/GovUk.Education.ExploreEducationStatistics.Publisher/Services/Interfaces/IMethodologyService.cs
src/GovUk.Education.ExploreEducationStatistics.Publisher/Services/Interfaces/IReleaseService.cs
src/GovUk.Education.ExploreEducationStatistics.Publisher/Services/MethodologyService.cs
src/GovUk.Education.ExploreEducationStatistics.Publisher/Services/PublishingService.cs
src/GovUk.Education.ExploreEducationStatistics.Publisher/Services/ReleaseService.cs
src/GovUk.Education.ExploreEducationStatistics.Publisher/Startup.cs

This PR sets the published dates of methodologies when they first turn publicly accessible.
A Methodology can 'turn' publicly accessible:
**Now** -  if its been approved for immediate publishing and a Publication using it already has a published Release.
Here the published date is set by the Admin application when the Methodology is approved.
or
**Later** - If it's been approved for immediate publishing - When a publication using it has it's first release published.
**Later** - If its been approved for publishing with a Release - When that Release is published.
In both of these cases the published date is set by the Publisher function application when the Release is published.
These changes rely on a method for calculating if a methodology is publicly accessible which has a known problem …

EES-2466 Set Methodology Published dates when they first turn publicly accessible

---

src/GovUk.Education.ExploreEducationStatistics.Data.Processor.Tests/Services/ImporterLocationServiceTests.cs
src/GovUk.Education.ExploreEducationStatistics.Data.Processor/Services/ImporterLocationService.cs
tests/newman/files/small-files/case_sensitive_locations_1.csv
tests/newman/files/small-files/case_sensitive_locations_1.meta.csv
tests/newman/files/small-files/case_sensitive_locations_2.csv
tests/newman/files/small-files/case_sensitive_locations_2.meta.csv

This ensures all comparisons of Location *_Name's are case-sensitive compared. This also includes RscRegion_Code as the code for RscRegions doubles as the name.
Another thing to note about this PR is that the additional unit test currently passes before this change was made. This is because the in-memory DB in the version of EF we're using doesn't support case-insensitive comparisons: https://github.com/dotnet/efcore/issues/20770

EES-2427 Make comparison of location names case sensitive when importing

---

src/explore-education-statistics-admin/src/pages/methodology/components/MethodologySummaryForm.tsx
src/explore-education-statistics-admin/src/pages/methodology/components/__tests__/MethodologySummaryForm.test.tsx
src/explore-education-statistics-admin/src/pages/methodology/edit-methodology/summary/MethodologySummaryEditPage.tsx

Adds a new version of the methodology summary form with an option to use the publication title or set an alternative one.
This is hidden under a flag so the current form will still work. Switch `canUpdateTitle` to true to see it in action.
It will need updating once the back end is ready but can be merged safely before then.

EES-2215 updated methodology summary form

---

src/GovUk.Education.ExploreEducationStatistics.Admin.Tests/Services/ReleaseFileServiceTests.cs
src/GovUk.Education.ExploreEducationStatistics.Admin/Services/ReleaseFileService.cs
src/GovUk.Education.ExploreEducationStatistics.Common.Tests/Extensions/StringExtensionTests.cs
src/GovUk.Education.ExploreEducationStatistics.Common/Extensions/StringExtensions.cs
src/GovUk.Education.ExploreEducationStatistics.Content.Model/Release.cs
src/GovUk.Education.ExploreEducationStatistics.Publisher.Tests/Services/DataGuidanceFileWriterTests.cs
src/GovUk.Education.ExploreEducationStatistics.Publisher/Services/DataGuidanceFileWriter.cs
src/GovUk.Education.ExploreEducationStatistics.Publisher/Services/PublishingService.cs
tests/robot-tests/tests/admin_and_public/bau/publish_release_and_amend.robot

This PR:
- Adds handling of published releases with no (meta)data guidance. These releases should not generate a data guidance file in the 'All files' zip. Unfortunately this logic was accidentally omitted, hence we were getting a exception due to the release's `MetaGuidance` field being null/empty.
- Fixes UI test teardown throwing foreign key errors due to `DataGuidance` file types still being attached to the release. This type has now been added to the types of files that can be deleted by `ReleaseFileService.DeleteAll`.
- Fixes some remaining test failures related to the 'All files' zip size increasing due to the new data guidance file.
- Cleaned up and reorganized some of the `StringExtensions` tests.

EES-2359 Fix various UI test failures associated with updated 'All files' zip

---

src/GovUk.Education.ExploreEducationStatistics.Common.Tests/Utils/HtmlToTextUtilsTests.cs
src/GovUk.Education.ExploreEducationStatistics.Common/Utils/HtmlToTextUtils.cs
src/GovUk.Education.ExploreEducationStatistics.Publisher.Tests/Services/DataGuidanceFileWriterTests.cs
src/GovUk.Education.ExploreEducationStatistics.Publisher.Tests/Services/__snapshots__/DataGuidanceFileWriterTests.WriteFile_FileWithEmptyProperties.snap
src/GovUk.Education.ExploreEducationStatistics.Publisher.Tests/Services/__snapshots__/DataGuidanceFileWriterTests.WriteFile_FileWithEmptyTimePeriodEnd.snap
src/GovUk.Education.ExploreEducationStatistics.Publisher.Tests/Services/__snapshots__/DataGuidanceFileWriterTests.WriteFile_FileWithEmptyTimePeriodStart.snap
src/GovUk.Education.ExploreEducationStatistics.Publisher.Tests/Services/__snapshots__/DataGuidanceFileWriterTests.WriteFile_FileWithEmptyVariable.snap
src/GovUk.Education.ExploreEducationStatistics.Publisher.Tests/Services/__snapshots__/DataGuidanceFileWriterTests.WriteFile_FileWithSingleProperties.snap
src/GovUk.Education.ExploreEducationStatistics.Publisher/Services/DataGuidanceFileWriter.cs

This change adds missing handling for potential empty values across the data guidance file. Empty values can consist of things like empty strings for geographic levels, time periods and variable names/descriptions.
We want to avoid displaying parts of the guidance file that may contain these empty values.

EES-2359 Add handling for empty data guidance values

---

src/GovUk.Education.ExploreEducationStatistics.Common/Services/BlobStorageService.cs

This PR fixes a bug in `BlobStorageService` which is preventing deleting all blobs in a container.
As well as deleting a subfolder of blobs, this method can be used to delete all container blobs without specifying a `directoryPath`, e.g. as used by the Publisher DeleteAllContentFunction which is used to perform a full content refresh.
In this case we don't want to append a trailing slash to an empty `directoryPath` otherwise
Prefix: `/`
matches no blobs which have names of the format
```
Blob name: FolderA/blob1
Blob name: FolderA/blob2
Blob name: FolderA/blob3
Blob name: FolderA/FolderB/blob1
Blob name: FolderB/blob1
Blob name: FolderB/blob2
```
since no blob names begin `/`.

EES-2504 Fix bug to allow deleting all container blobs

---

src/docker-compose.yml

This PR mounts a volume to the Azurite container, allowing it to persist data in between running `docker-compose up` and `down`.

Add volume to Azurite container to persist data

---

tests/robot-tests/tests/admin_and_public/bau/publish_release_and_amend_2.robot
tests/robot-tests/tests/libs/tables-common.robot
tests/robot-tests/tests/libs/utilities.py

This PR:
- moves the lookup of parents from a single initial lookup in `user_waits_until_parent_contains_element` and `user_waits_until_parent_does_not_contain_element` to a dynamic lookup within the `waiting._wait_until` loop, thus ensuring that the parent being used to find the child is always fresh
- refactors `get_child_element` and `get_child_elements` to reuse much of the code used within `user_waits_until_parent_contains_element` for easier maintenance.
- adds a warning within `get_child_element` if the lookup resulted in more than one element being found.  Previous behaviour was just to return the first element that the query matched without any warning.  This highlights some areas where we're currently "getting away with it".
- corrects a table xpath expression that was only …

EES-2513 - avoid Stale Reference errors

---

src/GovUk.Education.ExploreEducationStatistics.Content.Api.Tests/Controllers/ThemeControllerTests.cs
src/GovUk.Education.ExploreEducationStatistics.Content.Api.Tests/Services/MethodologyServiceTests.cs
src/GovUk.Education.ExploreEducationStatistics.Content.Api.Tests/ViewModels/AllMethodologiesThemeViewModelTests.cs
src/GovUk.Education.ExploreEducationStatistics.Content.Api.Tests/ViewModels/AllMethodologiesTopicViewModelTests.cs
src/GovUk.Education.ExploreEducationStatistics.Content.Api/Controllers/ThemeController.cs
src/GovUk.Education.ExploreEducationStatistics.Content.Api/Services/Interfaces/IMethodologyService.cs
src/GovUk.Education.ExploreEducationStatistics.Content.Api/Services/MethodologyService.cs
src/GovUk.Education.ExploreEducationStatistics.Content.Api/ViewModels/AllMethodologiesViewModels.cs
src/GovUk.Education.ExploreEducationStatistics.Content.Model.Tests/Repository/MethodologyParentRepositoryTests.cs
src/GovUk.Education.ExploreEducationStatistics.Content.Model.Tests/Repository/MethodologyRepositoryTests.cs
src/GovUk.Education.ExploreEducationStatistics.Content.Model/Repository/MethodologyParentRepository.cs
src/GovUk.Education.ExploreEducationStatistics.Content.Model/Repository/MethodologyRepository.cs

This is an experimental PR attempting to optimise fetching and building the view model for the Public All Methodologies page.
The cause of the performance problem appears to be down to fetching the publication in  methods `MethodologyParentRepository#GetByPublication` and `MethodologyRepository#GetLatestPublishedByPublication` to check for its existence before proceeding.
We called these methods a number of times, one for each Publication each time we were attempting to check if the Publication has child Methodology nodes, and once to build the Methodologies for the Publication node view model.
While it's nice to check that the publication exists, in theory it should be impossible to reach this code with a publication id that hasn't first come from some data containing actual …

EES-2509 Optimise building All Methodologies view

---

src/explore-education-statistics-admin/src/pages/admin-dashboard/components/MethodologySummary.tsx
src/explore-education-statistics-admin/src/pages/admin-dashboard/components/__tests__/MethodologySummary.test.tsx

This PR hides the methodology amendments button which won't be made public until further development and testing of amendments is completed.

EES-2523 Disable methodology amendments button

---

src/explore-education-statistics-admin/src/pages/admin-dashboard/components/MethodologySummary.tsx

This PR swaps the order of methodologies created on the service to show them before the external methodology buttons.
Before:
After:

EES-2522 Swap the order of EES methodologies and buttons 

---

src/GovUk.Education.ExploreEducationStatistics.Publisher.Tests/Services/PublicationServiceTests.cs
src/GovUk.Education.ExploreEducationStatistics.Publisher.Tests/Services/PublishingServiceTests.cs
src/GovUk.Education.ExploreEducationStatistics.Publisher/Functions/PublishReleaseFilesFunction.cs
src/GovUk.Education.ExploreEducationStatistics.Publisher/Services/Interfaces/IPublicationService.cs
src/GovUk.Education.ExploreEducationStatistics.Publisher/Services/Interfaces/IPublishingService.cs
src/GovUk.Education.ExploreEducationStatistics.Publisher/Services/PublicationService.cs
src/GovUk.Education.ExploreEducationStatistics.Publisher/Services/PublishingService.cs
src/GovUk.Education.ExploreEducationStatistics.Publisher/Startup.cs

This PR completes a TODO in the code that had been accidently missed that relates to publishing Methodology image files while publishing a Release.
```
// TODO SOW EES-2385 Also need to do this if ScheduledForPublishingImmediately
but not accessible yet because this is the first Release
```
If publishing a Release is about to make a Methodology public then we also need to publish the files for that Methodology.
We were already do this for a Methodology scheduled for publishing with the Release (note: even though  this functionality isn't available to analysts yet).
When a Methodology is approved for publishing immediately the image files are not copied if no publications using that Methodology are public.
Upon publishing the first Release for one of those publications we need to publish …

EES-2526 Publish the images of the latest Methodologies related to this Release

---

src/GovUk.Education.ExploreEducationStatistics.Admin.Tests/Services/Methodologies/MethodologyAmendmentServiceTests.cs
src/GovUk.Education.ExploreEducationStatistics.Admin.Tests/Services/Methodologies/MethodologyImageServicePermissionTests.cs
src/GovUk.Education.ExploreEducationStatistics.Admin.Tests/Services/Methodologies/MethodologyImageServiceTests.cs
src/GovUk.Education.ExploreEducationStatistics.Admin.Tests/Services/Methodologies/MethodologyServiceTests.cs
src/GovUk.Education.ExploreEducationStatistics.Admin/Services/Interfaces/Methodologies/IMethodologyFileRepository.cs
src/GovUk.Education.ExploreEducationStatistics.Admin/Services/Interfaces/Methodologies/IMethodologyImageService.cs
src/GovUk.Education.ExploreEducationStatistics.Admin/Services/Methodologies/MethodologyAmendmentService.cs
src/GovUk.Education.ExploreEducationStatistics.Admin/Services/Methodologies/MethodologyFileRepository.cs
src/GovUk.Education.ExploreEducationStatistics.Admin/Services/Methodologies/MethodologyImageService.cs
src/GovUk.Education.ExploreEducationStatistics.Admin/Services/Methodologies/MethodologyService.cs
src/GovUk.Education.ExploreEducationStatistics.Common.Tests/Extensions/EitherTestExtensions.cs
src/GovUk.Education.ExploreEducationStatistics.Common/Extensions/EnumerableExtensions.cs
src/GovUk.Education.ExploreEducationStatistics.Common/Model/Either.cs
src/GovUk.Education.ExploreEducationStatistics.Common/Services/CollectionUtils.cs
src/explore-education-statistics-admin/src/pages/admin-dashboard/components/MethodologySummary.tsx
src/explore-education-statistics-admin/src/pages/admin-dashboard/components/__tests__/MethodologySummary.test.tsx

This PR:
* Creates links to an original Methodology version's files when creating a new Methodology amendment.
* Unlinks files from a Methodology version when deleting it, and deletes the files from the Files table and Blob Storage if no other Methodology version is using them.
With this PR in place, Methodology Amendments no longer have to be a hidden feature, and so the "Amend Methodology" button has been reinstated in the UI.

Ees 2156 sow4 create methodology amendment part 2

---

src/explore-education-statistics-admin/src/pages/release/content/components/ReleaseContent.tsx
src/explore-education-statistics-admin/src/pages/release/data/ReleaseAncillaryFilePage.tsx
src/explore-education-statistics-admin/src/pages/release/data/ReleaseDataFilePage.tsx
src/explore-education-statistics-admin/src/pages/release/data/__tests__/ReleaseAncilllaryFilePage.test.tsx
src/explore-education-statistics-admin/src/pages/release/data/__tests__/ReleaseDataFilePage.test.tsx
src/explore-education-statistics-admin/src/pages/release/data/components/ReleaseFileUploadsSection.tsx
src/explore-education-statistics-admin/src/pages/release/data/components/__tests__/ReleaseFileUploadsSection.test.tsx
src/explore-education-statistics-admin/src/services/releaseAncillaryFileService.ts
src/explore-education-statistics-admin/src/services/releaseDataFileService.ts
src/explore-education-statistics-common/src/modules/release/components/ReleaseDataAndFilesAccordion.tsx
src/explore-education-statistics-common/src/modules/release/components/__tests__/ReleaseDataAndFilesAccordion.test.tsx
src/explore-education-statistics-common/src/services/types/file.ts
src/explore-education-statistics-common/src/styles/_all.scss
src/explore-education-statistics-common/src/styles/utils/_text.scss
src/explore-education-statistics-frontend/src/modules/find-statistics/PublicationReleasePage.tsx
tests/robot-tests/tests/admin/bau/create_methodology_for_publication.robot
tests/robot-tests/tests/admin/bau/upload_files.robot
tests/robot-tests/tests/admin_and_public/bau/publish_release_and_amend.robot
tests/robot-tests/tests/libs/admin-common.robot
tests/robot-tests/tests/libs/common.robot
tests/robot-tests/tests/libs/utilities.py

This PR adds the new 'Summary' field for ancillary files. This has been added to both the upload and update forms.
- Added missing tests for updating ancillary and data file titles.
- Added a new `label` element selector that replaces the previous 'textfield' specific keywords (e.g. `user enters text into textfield`). This reduces duplication and is more versatile as it locates an element by id matching the label's `for` attribute. Comparatively, the previous textfield keywords would only look for an input directly adjacent to the label.
Upload form:
Edit form:
In the release's downloads accordion:

EES-2364 Update frontend with ancillary file Summary field

---

src/explore-education-statistics-admin/src/components/editable/EditableAccordion.module.scss

Accordions in drag and drop areas sometimes open upwards instead of down. This seems to be because the dnd default styles set overflow-anchor to none on the drop area. I've overridden this specifically for the release content accordion.
According to the dnd docs the style is needed because 'The automatic overflow-anchor behavior leads to incorrect scroll positioning post drop.', see  https://github.com/atlassian/react-beautiful-dnd/blob/master/docs/guides/preset-styles.md, however I haven't found any problems when trying it after overriding the style, though it's definitely worth bearing in mind for testing..

EES-2414 override dnd style to fix accordion opening direction

---

tests/robot-tests/tests/libs/common.robot

This fixes cases where we are using keywords like `user checks page does not contain`. These were primarily failing due to keywords that were waiting for elements that would never appear.
It also turns out that we need to return lists of elements for custom selectors instead of singular elements.

EES-2536 Fix custom selectors failing for negation keywords

---

infrastructure/templates/template.json
src/GovUk.Education.ExploreEducationStatistics.Data.Model/Database/PublicStatisticsDbContext.cs
src/GovUk.Education.ExploreEducationStatistics.Data.Model/Database/StatisticsDbContext.cs
src/GovUk.Education.ExploreEducationStatistics.Data.Model/Database/StatisticsDbUtils.cs
src/GovUk.Education.ExploreEducationStatistics.Publisher.Tests/Services/ReleaseServiceTests.cs
src/GovUk.Education.ExploreEducationStatistics.Publisher/Services/ReleaseService.cs
src/GovUk.Education.ExploreEducationStatistics.Publisher/Startup.cs
src/GovUk.Education.ExploreEducationStatistics.Publisher/local.settings.json

This PR adds a new connection to the private statistics DB from the Publisher. This has been implemented by extending `StatisticsDbContext` with a `PublicStatisticsDbContext`.

EES-2538 Update Publisher to use private statistics DB

---

src/GovUk.Education.ExploreEducationStatistics.Data.Model/Database/StatisticsDbContext.cs

This PR tries to fix admin potentially failing (may not happen depending on your machine) due to some weirdness around the new `StatisticsDbContext` constructor using a default `timeout` parameter.
I can't really understand why this is happening, so I'm just going to chalk it up to some reflection-based madness that's going on under the hood.
Adding in the original constructor implementation back in seems to fix it.

EES-2538 Fix StatisticsDbContext constructor with default timeout parameter not working

---

src/explore-education-statistics-common/src/modules/charts/components/CustomReferenceLineLabel.tsx
src/explore-education-statistics-common/src/modules/charts/components/LineChartBlock.tsx

Renders a custom label for reference lines that changes the text alignment if the label is at the start or end. This is for line charts only currently as I'm not sure it's necessary for bar charts and would look odd with wide bars
Before:
After:

EES-2472 prevent chart ref line labels being cut off

---

src/GovUk.Education.ExploreEducationStatistics.Admin.Tests/Services/Methodologies/MethodologyServicePermissionTests.cs
src/GovUk.Education.ExploreEducationStatistics.Admin.Tests/Services/Methodologies/MethodologyServiceTests.cs
src/GovUk.Education.ExploreEducationStatistics.Admin/Services/Methodologies/MethodologyService.cs
src/GovUk.Education.ExploreEducationStatistics.Admin/Startup.cs
src/GovUk.Education.ExploreEducationStatistics.Common.Tests/Extensions/MockCacheServiceExtensions.cs
src/GovUk.Education.ExploreEducationStatistics.Common.Tests/Utils/MockUtils.cs
src/GovUk.Education.ExploreEducationStatistics.Common/Cache/AllMethodologiesCacheKey.cs
src/GovUk.Education.ExploreEducationStatistics.Common/Cache/Interfaces/ICacheKey.cs
src/GovUk.Education.ExploreEducationStatistics.Common/Model/Interfaces/ICacheKey.cs
src/GovUk.Education.ExploreEducationStatistics.Common/Services/BlobStorageCacheService.cs
src/GovUk.Education.ExploreEducationStatistics.Common/Services/Interfaces/ICacheService.cs
src/GovUk.Education.ExploreEducationStatistics.Content.Api.Tests/Services/BlobStorageCacheServiceTests.cs
src/GovUk.Education.ExploreEducationStatistics.Content.Api.Tests/Services/MethodologyServiceTests.cs
src/GovUk.Education.ExploreEducationStatistics.Content.Api/Services/MethodologyService.cs
src/GovUk.Education.ExploreEducationStatistics.Content.Api/Startup.cs
src/GovUk.Education.ExploreEducationStatistics.Content.Api/ViewModels/AllMethodologiesViewModels.cs
src/GovUk.Education.ExploreEducationStatistics.Data.Api.Tests/Services/DataBlockServiceTests.cs
src/GovUk.Education.ExploreEducationStatistics.Data.Api/Services/DataBlockService.cs
src/GovUk.Education.ExploreEducationStatistics.Data.Api/Startup.cs
src/GovUk.Education.ExploreEducationStatistics.Data.Services/Cache/DataBlockTableResultCacheKey.cs
src/GovUk.Education.ExploreEducationStatistics.Data.Services/ViewModels/TableBuilderResultViewModel.cs
src/GovUk.Education.ExploreEducationStatistics.Publisher/Functions/PublishReleaseContentFunction.cs
src/GovUk.Education.ExploreEducationStatistics.Publisher/Functions/PublishStagedReleaseContentFunction.cs
src/GovUk.Education.ExploreEducationStatistics.Publisher/Services/ContentService.cs
src/GovUk.Education.ExploreEducationStatistics.Publisher/Startup.cs

This PR introduces a new caching interface with implementation `BlobStorageCacheService` which can read and write cached entity results in blob storage serialised as JSON, identified by a unique key.
It is a the same 'Cache Aside' strategy that we were already using to cache data block results where we first try to read from the cache, and if no result is found then read the result from the database, serialising the result as JSON in the storage container before returning it.
The same logic is moved to this new service so that it can also be used by the Public Content API's endpoint to retrieve the themes 'tree' of all Methodologies via the cache, significantly improving the load time of this page from around 1.5s to <100ms.
The interface of the cache service expects a callback function …

EES-2509 Add new Caching service to cache results in Azure blob storage

---

src/GovUk.Education.ExploreEducationStatistics.Data.Model/Services/ReleaseSubjectService.cs
src/GovUk.Education.ExploreEducationStatistics.Publisher/Startup.cs

This was causing SQL errors on pre-prod due to `ReleaseSubjectService` trying to run delete commands against the private stats DB (the publisher only has read access).
To fix this, we explicitly provide the `PublicStatisticsDbContext` as a dependency of `ReleaseSubjectService`.

EES-2549 Fix private stats DB wired into publisher's ReleaseSubjectService

---

src/GovUk.Education.ExploreEducationStatistics.Common/Model/TimeIdentifier.cs

This PR should fix the incorrect ordering of releases leading to the wrong latest release being selected: https://explore-education-statistics.service.gov.uk/find-statistics/serious-incident-notifications

EES-2560 Reduce priority of Financial Year Part time identifiers

---

src/explore-education-statistics-admin/src/components/editable/EditableAccordion.module.scss
src/explore-education-statistics-admin/src/components/editable/EditableAccordion.tsx

Makes the fix for Editable Accordions sometimes opening in the wrong direction apply to all of them, not just the release content one. They're used on:
- release content
- methodology content

EES-2562 apply editable accordion direction fix to all

---

infrastructure/parameters/dev.parameters.json
infrastructure/parameters/pre-prod.parameters.json
infrastructure/parameters/test.parameters.json
infrastructure/templates/template.json
src/GovUk.Education.ExploreEducationStatistics.Admin.Tests/Controllers/Api/Methodologies/MethodologyControllerTests.cs
src/GovUk.Education.ExploreEducationStatistics.Admin.Tests/Services/EmailTemplateServiceTests.cs
src/GovUk.Education.ExploreEducationStatistics.Admin.Tests/Services/Methodologies/MethodologyImageServicePermissionTests.cs
src/GovUk.Education.ExploreEducationStatistics.Admin.Tests/Services/Methodologies/MethodologyImageServiceTests.cs
src/GovUk.Education.ExploreEducationStatistics.Admin.Tests/Services/Methodologies/MethodologyServiceTests.cs
src/GovUk.Education.ExploreEducationStatistics.Admin.Tests/Services/ThemeServicePermissionTests.cs
src/GovUk.Education.ExploreEducationStatistics.Admin.Tests/Services/ThemeServiceTests.cs
src/GovUk.Education.ExploreEducationStatistics.Admin.Tests/Services/TopicServicePermissionTests.cs
src/GovUk.Education.ExploreEducationStatistics.Admin.Tests/Services/TopicServiceTests.cs
src/GovUk.Education.ExploreEducationStatistics.Admin/Services/Interfaces/Methodologies/IMethodologyImageService.cs
src/GovUk.Education.ExploreEducationStatistics.Admin/Services/Interfaces/Methodologies/IMethodologyService.cs
src/GovUk.Education.ExploreEducationStatistics.Admin/Services/Interfaces/Security/UserServiceExtensions.cs
src/GovUk.Education.ExploreEducationStatistics.Admin/Services/Methodologies/MethodologyImageService.cs
src/GovUk.Education.ExploreEducationStatistics.Admin/Services/Methodologies/MethodologyService.cs
src/GovUk.Education.ExploreEducationStatistics.Admin/Services/ThemeService.cs
src/GovUk.Education.ExploreEducationStatistics.Admin/Services/TopicService.cs
src/GovUk.Education.ExploreEducationStatistics.Admin/Startup.cs
src/GovUk.Education.ExploreEducationStatistics.Admin/appsettings.Development.json
src/GovUk.Education.ExploreEducationStatistics.Common.Tests/Extensions/EitherTestExtensions.cs
src/GovUk.Education.ExploreEducationStatistics.Common.Tests/Utils/MockUtils.cs
src/GovUk.Education.ExploreEducationStatistics.Content.Api/Startup.cs
src/GovUk.Education.ExploreEducationStatistics.Data.Api/Startup.cs

This PR:
- Adds an order in which Releases and Methodologies are deleted under a Theme when the Theme and its Topics are deleted.  This is to prevent foreign key issues coming from Previous Version Id columns which reference entities of the same type.  This way, the latest version of Releases and Methodologies are deleted first, then their previous versions, then their previous etc etc, until finally the original versions are deleted.
- Adds the removal of Methodology Files and orphaned MethodologyParents from Blob Storage when deleting a Theme and its Topics, by way of using MethodologyService to delete Methodologies cleanly (with an extra "forceDelete" flag to override the default security checks).
- Adds per-environment configuration to allow or disallow the deleting of whole Themes. …

EES-2519 - order of deletion of Releases and Methodologies

---

src/GovUk.Education.ExploreEducationStatistics.Common.Tests/Utils/HtmlToTextUtilsTests.cs
src/GovUk.Education.ExploreEducationStatistics.Common.Tests/Utils/__snapshots__/HtmlToTextUtilsTests.HtmlToText_OrderedList_OverTenItemsWithMultiline.snap
src/GovUk.Education.ExploreEducationStatistics.Common.Tests/Utils/__snapshots__/HtmlToTextUtilsTests.HtmlToText_UnorderedList_OverTenItemsWithMultiline.snap
src/GovUk.Education.ExploreEducationStatistics.Common/Utils/Html/HtmlToTextConverter.cs
src/GovUk.Education.ExploreEducationStatistics.Content.Api/Startup.cs
src/GovUk.Education.ExploreEducationStatistics.Data.Model/IndicatorGroup.cs
src/GovUk.Education.ExploreEducationStatistics.Data.Services.Tests/MetaGuidanceSubjectServiceTests.cs
src/GovUk.Education.ExploreEducationStatistics.Data.Services/Interfaces/IMetaGuidanceSubjectService.cs
src/GovUk.Education.ExploreEducationStatistics.Data.Services/MetaGuidanceSubjectService.cs
src/GovUk.Education.ExploreEducationStatistics.Data.Services/ViewModels/MetaGuidanceSubjectViewModel.cs
src/GovUk.Education.ExploreEducationStatistics.Publisher.Tests/Services/DataGuidanceFileWriterTests.cs
src/GovUk.Education.ExploreEducationStatistics.Publisher.Tests/Services/__snapshots__/DataGuidanceFileWriterTests.WriteFile_FileWithEmptyFootnote.snap
src/GovUk.Education.ExploreEducationStatistics.Publisher.Tests/Services/__snapshots__/DataGuidanceFileWriterTests.WriteFile_FileWithOverTenFootnotesAndMultiline.snap
src/GovUk.Education.ExploreEducationStatistics.Publisher.Tests/Services/__snapshots__/DataGuidanceFileWriterTests.WriteFile_MultipleDataFiles.snap
src/GovUk.Education.ExploreEducationStatistics.Publisher.Tests/Services/__snapshots__/DataGuidanceFileWriterTests.WriteFile_SingleDataFile.snap
src/GovUk.Education.ExploreEducationStatistics.Publisher/Services/DataGuidanceFileWriter.cs
src/GovUk.Education.ExploreEducationStatistics.Publisher/Startup.cs

This PR adds footnotes to the data endpoint and the associated data guidance file (in the All files zip).
- Fixed indentation issue with `ol` elements in HTML to text conversion. This would previously lead to misalignment of the list item content if there were over 10 items in a list.

EES-2371 Add footnotes to data guidance endpoint and file

---

src/explore-education-statistics-admin/src/pages/release/data/components/DataUploadCancelButton.tsx
src/explore-education-statistics-admin/src/pages/release/data/components/ReleaseDataUploadsSection.tsx
src/explore-education-statistics-admin/src/pages/release/data/components/__tests__/ReleaseDataUploadsSection.test.tsx

I was unable to recreate the problem described in the ticket (spamming the cancel button), it may been fixed since it was raised.
This PR adds error handling for the cancel upload button so if something does go wrong users will be informed.

EES-1757 error handling for data upload cancel button

---

src/GovUk.Education.ExploreEducationStatistics.Content.Model/Repository/MethodologyRepository.cs
src/explore-education-statistics-admin/src/pages/release/content/components/RelatedPagesSection.tsx
src/explore-education-statistics-admin/src/pages/release/content/components/ReleaseContent.tsx
src/explore-education-statistics-frontend/src/modules/find-statistics/PublicationReleasePage.tsx
src/explore-education-statistics-frontend/src/modules/methodologies/MethodologyPage.tsx

This PR:
- rearranges the list of Methodology links on the Admin and Public Release content pages to sit under a "Methodologies" subheading
- adds the "Methodology" caption to the Public Methodology page to make it more obvious to the user as to what kind of page it is
- fixes a bug whereby a set of MethodologyParents weren't fully fetched before the contentDbContext was used for further operations

Ees 2530 put methodologies under subheading

---

src/GovUk.Education.ExploreEducationStatistics.Admin.Tests/GovUk.Education.ExploreEducationStatistics.Admin.Tests.csproj
src/GovUk.Education.ExploreEducationStatistics.Common.Tests/GovUk.Education.ExploreEducationStatistics.Common.Tests.csproj
src/GovUk.Education.ExploreEducationStatistics.Content.Api.Tests/GovUk.Education.ExploreEducationStatistics.Content.Api.Tests.csproj
src/GovUk.Education.ExploreEducationStatistics.Content.Api/GovUk.Education.ExploreEducationStatistics.Content.Api.csproj
src/GovUk.Education.ExploreEducationStatistics.Content.Model.Tests/GovUk.Education.ExploreEducationStatistics.Content.Model.Tests.csproj
src/GovUk.Education.ExploreEducationStatistics.Content.Model/GovUk.Education.ExploreEducationStatistics.Content.Model.csproj
src/GovUk.Education.ExploreEducationStatistics.Content.Security.Tests/GovUk.Education.ExploreEducationStatistics.Content.Security.Tests.csproj
src/GovUk.Education.ExploreEducationStatistics.Content.Security/GovUk.Education.ExploreEducationStatistics.Content.Security.csproj
src/GovUk.Education.ExploreEducationStatistics.Data.Api/GovUk.Education.ExploreEducationStatistics.Data.Api.csproj
src/GovUk.Education.ExploreEducationStatistics.Data.Model.Tests/GovUk.Education.ExploreEducationStatistics.Data.Model.Tests.csproj
src/GovUk.Education.ExploreEducationStatistics.Data.Model/GovUk.Education.ExploreEducationStatistics.Data.Model.csproj
src/GovUk.Education.ExploreEducationStatistics.Data.Processor.Model/GovUk.Education.ExploreEducationStatistics.Data.Processor.Model.csproj
src/GovUk.Education.ExploreEducationStatistics.Data.Processor.Tests/GovUk.Education.ExploreEducationStatistics.Data.Processor.Tests.csproj
src/GovUk.Education.ExploreEducationStatistics.Data.Processor/GovUk.Education.ExploreEducationStatistics.Data.Processor.csproj
src/GovUk.Education.ExploreEducationStatistics.Data.Services.Tests/GovUk.Education.ExploreEducationStatistics.Data.Services.Tests.csproj
src/GovUk.Education.ExploreEducationStatistics.Data.Services/GovUk.Education.ExploreEducationStatistics.Data.Services.csproj
src/GovUk.Education.ExploreEducationStatistics.Notifier.Model/GovUk.Education.ExploreEducationStatistics.Notifier.Model.csproj
src/GovUk.Education.ExploreEducationStatistics.Publisher.Model/GovUk.Education.ExploreEducationStatistics.Publisher.Model.csproj
src/GovUk.Education.ExploreEducationStatistics.Publisher.Tests/GovUk.Education.ExploreEducationStatistics.Publisher.Tests.csproj
src/GovUk.Education.ExploreEducationStatistics.Publisher/GovUk.Education.ExploreEducationStatistics.Publisher.csproj

This was really easy to do as it just involves adding the [IsExternalInit](https://github.com/manuelroemer/IsExternalInit) package to get it working.
With this, we can get C# 9 features whilst avoiding general migration pain for upgrading to .NET 5. I found the main barrier to upgrading to .NET 5  was that Azure Functions didn't really work correctly. It appears that there will be proper support for .NET 6 in November, so it's worth waiting until then for us to do that upgrade.
All UI tests have been ran and there are no failures to speak of.
C# 9 gives us few really nice new features:
- Records - https://docs.microsoft.com/en-us/dotnet/csharp/whats-new/csharp-9#record-types
- Init only setters - https://docs.microsoft.com/en-us/dotnet/csharp/whats-new/csharp-9#init-only-setters
- Can …

EES-2575 Upgrade to C# 9 without .NET 5

---

src/explore-education-statistics-admin/src/pages/methodology/edit-methodology/status/MethodologyStatusPage.tsx
src/explore-education-statistics-admin/src/pages/methodology/edit-methodology/status/components/MethodolodyStatusForm.tsx
src/explore-education-statistics-admin/src/pages/methodology/edit-methodology/status/components/__tests__/MethodologyStatusForm.test.tsx
src/explore-education-statistics-admin/src/services/methodologyService.ts

Adds a 'When to publish' section to the methodology sign off form allow users to select a release to publish the methodology with.
I've copied and adapted the UI for setting a publish date on releases.
I've had to make some guesses & assumptions so will likely need a bit of tweaking when the BE is hooked up. 
This is hidden under the showWithRelease flag in the component, you'll need to flip it to true to see it. When the backend is ready this flag can be removed. With the flag set to false it should work as now so is safe to merge to dev.

EES-2265 methodology dependent release FE

---

tests/robot-tests/tests/admin/analyst/analyst_absence_permissions.robot
tests/robot-tests/tests/general_public/methodologies_page.robot
tests/robot-tests/tests/general_public/methodology_page_absence.robot

This PR cleans up 1 instance of a high timeout that can be replaced with the new variable `%{WAIT_LONG}`. In addition to this, I've added additional assertions for the new page captions on methodology slug pages

EES-2585 - clean-up remaining UI test timeouts

---

src/GovUk.Education.ExploreEducationStatistics.Common/GovUk.Education.ExploreEducationStatistics.Common.csproj
src/GovUk.Education.ExploreEducationStatistics.Data.Api.Tests/GovUk.Education.ExploreEducationStatistics.Data.Api.Tests.csproj
src/GovUk.Education.ExploreEducationStatistics.Notifier/GovUk.Education.ExploreEducationStatistics.Notifier.csproj

Unfortunately, admin needs to remain on C# 8 for the time being due to its Razor view compiler being incompatible with C# 9 without .NET 5.
For now we'll just have to wait until we upgrade everything to .NET 6.

EES-2575 Add missing C# 9 references (excluding admin)

---

src/GovUk.Education.ExploreEducationStatistics.Admin.Tests/Services/Methodologies/MethodologyContentServicePermissionTests.cs
src/GovUk.Education.ExploreEducationStatistics.Admin.Tests/Services/Methodologies/MethodologyServiceTests.cs
src/GovUk.Education.ExploreEducationStatistics.Admin/Services/Interfaces/Methodologies/IMethodologyFileRepository.cs
src/GovUk.Education.ExploreEducationStatistics.Admin/Services/Methodologies/MethodologyContentService.cs
src/GovUk.Education.ExploreEducationStatistics.Admin/Services/Methodologies/MethodologyFileRepository.cs
src/GovUk.Education.ExploreEducationStatistics.Admin/Services/Methodologies/MethodologyImageService.cs
src/explore-education-statistics-admin/src/pages/admin-dashboard/components/MethodologySummary.tsx
src/explore-education-statistics-admin/src/pages/admin-dashboard/components/__tests__/MethodologySummary.test.tsx

This PR:
- removes the `allowAmendment` flag now that amendments are ready
- addresses leftover comments from original 2156 PR
- addresses leftover TODO to add Jest tests around removing a non-Amendment Methodology from a Publication

Ees 2547 tidy up tasks for 2156

---

useful-scripts/misc-test-utils/src/index.ts
useful-scripts/misc-test-utils/src/modules/publication/publishPublication.ts
useful-scripts/misc-test-utils/src/modules/release/createRelease.ts
useful-scripts/misc-test-utils/src/modules/subject/uploadSubject.ts
useful-scripts/misc-test-utils/src/services/commonService.ts
useful-scripts/misc-test-utils/src/services/publicationService.ts
useful-scripts/misc-test-utils/src/services/releaseService.ts
useful-scripts/misc-test-utils/src/services/subjectService.ts
useful-scripts/misc-test-utils/src/utils/adminApi.ts
useful-scripts/misc-test-utils/src/utils/zipDirectory.ts

This PR splits functionality that each module in this CLI uses into service files. This is to avoid code repetition across the cli. It splits up functionality into 3 services: 
- `releaseService` 
- `commonService`
- `subjectService`

Ees 2572 - refactor CLI to use common services

---

src/GovUk.Education.ExploreEducationStatistics.Admin.Tests/Controllers/Api/Methodologies/MethodologyControllerTests.cs
src/GovUk.Education.ExploreEducationStatistics.Admin.Tests/Services/Methodologies/MethodologyServiceTests.cs
src/GovUk.Education.ExploreEducationStatistics.Admin/Controllers/Api/Methodologies/MethodologyController.cs
src/GovUk.Education.ExploreEducationStatistics.Admin/Mappings/MappingProfiles.cs
src/GovUk.Education.ExploreEducationStatistics.Admin/Services/Interfaces/Methodologies/IMethodologyService.cs
src/GovUk.Education.ExploreEducationStatistics.Admin/Services/Methodologies/MethodologyService.cs
src/GovUk.Education.ExploreEducationStatistics.Admin/Validators/ValidationUtils.cs
src/GovUk.Education.ExploreEducationStatistics.Admin/ViewModels/Methodology/MethodologySummaryViewModel.cs
src/GovUk.Education.ExploreEducationStatistics.Admin/ViewModels/Methodology/MethodologyUpdateRequest.cs
src/GovUk.Education.ExploreEducationStatistics.Content.Model.Tests/MethodologyTests.cs
src/GovUk.Education.ExploreEducationStatistics.Content.Model/Methodology.cs
src/GovUk.Education.ExploreEducationStatistics.Publisher/Services/PublishingService.cs
src/explore-education-statistics-admin/src/pages/methodology/edit-methodology/status/MethodologyStatusEditPage.tsx
src/explore-education-statistics-admin/src/pages/methodology/edit-methodology/status/MethodologyStatusPage.tsx
src/explore-education-statistics-admin/src/pages/methodology/edit-methodology/status/components/MethodolodyStatusForm.tsx
src/explore-education-statistics-admin/src/pages/methodology/edit-methodology/status/components/__tests__/MethodologyStatusForm.test.tsx
src/explore-education-statistics-admin/src/pages/methodology/edit-methodology/status/components/__tests__/MethodologyStatusPageTest.test.tsx
src/explore-education-statistics-admin/src/services/methodologyService.ts
tests/robot-tests/tests/admin_and_public/bau/publish_methodology.robot
tests/robot-tests/tests/general_public/methodologies_page.robot
tests/robot-tests/tests/general_public/methodology_page_absence.robot
tests/robot-tests/tests/libs/admin-common.robot
tests/robot-tests/tests/libs/public-common.robot

This PR:
- Adds a new Admin API endpoint `/api/methodology/{methodologyId}/unpublished-releases`  returning an ordered list of unpublished Releases for the owning or adopting publications using the methodology.
- Allows setting the chosen publishing strategy when approving a Release - Immediately or With a specifc release.
- Alters the Admin `UpdateMethodology` method to allow setting the chosen release id when approving with a specific release.
- Validates that the methodology can depend on a chosen release for publishing, i.e. checks that this release exists, that it's not already published, and that it's still linked via its publication to the methodology.
- Hooks up the FE work for this feature covered by @amyb-hiveit  in https://github.com/dfe-analytical-services/explore-education-sta …

EES-2164 Allow approving methodology for publishing in combination with a Release

---

tests/robot-tests/tests/admin_and_public/bau/prerelease_visibility.robot
tests/robot-tests/tests/general_public/download_page.robot
tests/robot-tests/tests/general_public/miscellaneous.robot
useful-scripts/run.js

This PR: 
- Removes instances of `NotAgainstLocal` tags of tests that aren't failing to increase test coverage (as UI tests should be run against a local frontend that is running in a production mode) 
- Adds an argument to the `run.js` script to run the public frontend in production mode

EES-2602 - remove `notAgainstLocal` tags from UI tests

---

src/explore-education-statistics-common/src/modules/table-tool/components/FormFieldSortableListGroup.module.scss
src/explore-education-statistics-common/src/modules/table-tool/components/FormFieldSortableListGroup.tsx
src/explore-education-statistics-common/src/modules/table-tool/components/FormSortableList.module.scss
src/explore-education-statistics-common/src/modules/table-tool/components/FormSortableList.tsx

Adds styling to visually indicate when a header item or group has been dragged outside the drop area.
https://user-images.githubusercontent.com/81572860/128190915-4727b91b-989c-480f-8d20-38769a84c7b6.mp4
https://user-images.githubusercontent.com/81572860/128190932-d748e2d9-def5-40a7-b111-e5759d00e63a.mp4

EES-2578 indicate when drag table headers outside drop area

---

src/GovUk.Education.ExploreEducationStatistics.Admin.Tests/Services/Methodologies/MethodologyServiceTests.cs
src/GovUk.Education.ExploreEducationStatistics.Admin/Services/Methodologies/MethodologyService.cs
src/explore-education-statistics-admin/src/pages/methodology/edit-methodology/status/components/MethodolodyStatusForm.tsx
src/explore-education-statistics-admin/src/pages/methodology/edit-methodology/status/components/__tests__/MethodologyStatusForm.test.tsx

This PR changes the list of unpublished releases shown on the methodology sign off tab.
After this change, unpublished releases are ordered beginning with the most recent first, though still ordered by publication if the methodology is used by multiple publications.

EES-2268 Order unpublished releases by most recent first

---

src/GovUk.Education.ExploreEducationStatistics.Common.Tests/Cache/BlobCacheAttributeTests.cs
src/GovUk.Education.ExploreEducationStatistics.Common.Tests/Cache/CacheAspectTests.cs
src/GovUk.Education.ExploreEducationStatistics.Common.Tests/Fixtures/CacheTestFixture.cs

This uses a combination of xUnit collections (so that the caching tests don't run in parallel), and a class fixture `CacheTestFixture` to enable/disable caching.

EES-2548 Fix intermittent caching test failures

---

tests/robot-tests/run_tests.py

This PR: 
- Allows you to pass in a custom `.env` file via the run_tests.py script.   
To use this new argument: 
`pipenv run python run_tests.py -f tests -i robot -b chrome -e <test_env> --custom-env <custom_env_name>`

EES-2499 - add custom env arg to run_tests.py

---

src/explore-education-statistics-frontend/src/modules/data-catalogue/DataCataloguePage.tsx
src/explore-education-statistics-frontend/src/modules/data-catalogue/__tests__/DataCataloguePage.test.tsx
src/explore-education-statistics-frontend/src/modules/data-catalogue/components/DownloadStep.tsx
src/explore-education-statistics-frontend/src/modules/data-catalogue/components/ReleaseForm.tsx
src/explore-education-statistics-frontend/src/modules/data-catalogue/components/ReleaseStep.tsx
src/explore-education-statistics-frontend/src/pages/data-catalogue/[publicationSlug].tsx
src/explore-education-statistics-frontend/src/pages/data-catalogue/[publicationSlug]/[releaseSlug].tsx

On the data catalogue  page you can directly link to:
- `/data-catalogue/<publication-slug>` -  releases for a publication (step 2)
- `/data-catalogue/<publication-slug>/<release-slug>` - downloads for a release (step 3)
The isMounted check on the release and download steps is because of a weird thing where when components from the frontend repo are active in the wizard on page load formikContext is undefined. Components from the common repo don't require this check. Something to do with how Formik is initialised maybe 🤷

EES-2373 allow direct link to release downloads on data catalogue

---

src/explore-education-statistics-admin/src/pages/release/content/components/ReleaseContent.tsx
src/explore-education-statistics-frontend/src/modules/find-statistics/PublicationReleasePage.tsx
tests/robot-tests/tests/admin/bau/prerelease.robot
tests/robot-tests/tests/admin_and_public/bau/publish_data.robot
tests/robot-tests/tests/admin_and_public/bau/publish_release_and_amend.robot

On the public frontend and the release edit / preview in the admin.

EEs-2234 remove metaguidance link from useful info

---

tests/robot-tests/tests/admin/bau/create_methodology_amendment.robot
tests/robot-tests/tests/libs/admin-common.robot

Updates the UI tests related to methodology status tags.
The ones that expect the tag to update to approved when the methodology is signed off still fail as this isn't currently working,  ticket to fix it: https://dfedigital.atlassian.net/browse/EES-2599

EES-2622 update methodology status tags ui tests

---

src/GovUk.Education.ExploreEducationStatistics.Admin.Tests/GovUk.Education.ExploreEducationStatistics.Admin.Tests.csproj
src/GovUk.Education.ExploreEducationStatistics.Admin/GovUk.Education.ExploreEducationStatistics.Admin.csproj
src/GovUk.Education.ExploreEducationStatistics.Common.Tests/GovUk.Education.ExploreEducationStatistics.Common.Tests.csproj
src/GovUk.Education.ExploreEducationStatistics.Common/GovUk.Education.ExploreEducationStatistics.Common.csproj
src/GovUk.Education.ExploreEducationStatistics.Content.Api.Tests/GovUk.Education.ExploreEducationStatistics.Content.Api.Tests.csproj
src/GovUk.Education.ExploreEducationStatistics.Content.Api/GovUk.Education.ExploreEducationStatistics.Content.Api.csproj
src/GovUk.Education.ExploreEducationStatistics.Content.Model.Tests/GovUk.Education.ExploreEducationStatistics.Content.Model.Tests.csproj
src/GovUk.Education.ExploreEducationStatistics.Content.Model/GovUk.Education.ExploreEducationStatistics.Content.Model.csproj
src/GovUk.Education.ExploreEducationStatistics.Content.Security.Tests/GovUk.Education.ExploreEducationStatistics.Content.Security.Tests.csproj
src/GovUk.Education.ExploreEducationStatistics.Content.Security/GovUk.Education.ExploreEducationStatistics.Content.Security.csproj
src/GovUk.Education.ExploreEducationStatistics.Data.Api.Tests/GovUk.Education.ExploreEducationStatistics.Data.Api.Tests.csproj
src/GovUk.Education.ExploreEducationStatistics.Data.Api/GovUk.Education.ExploreEducationStatistics.Data.Api.csproj
src/GovUk.Education.ExploreEducationStatistics.Data.Model.Tests/GovUk.Education.ExploreEducationStatistics.Data.Model.Tests.csproj
src/GovUk.Education.ExploreEducationStatistics.Data.Model/GovUk.Education.ExploreEducationStatistics.Data.Model.csproj
src/GovUk.Education.ExploreEducationStatistics.Data.Processor.Tests/GovUk.Education.ExploreEducationStatistics.Data.Processor.Tests.csproj
src/GovUk.Education.ExploreEducationStatistics.Data.Processor/GovUk.Education.ExploreEducationStatistics.Data.Processor.csproj
src/GovUk.Education.ExploreEducationStatistics.Data.Services.Tests/GovUk.Education.ExploreEducationStatistics.Data.Services.Tests.csproj
src/GovUk.Education.ExploreEducationStatistics.Data.Services/GovUk.Education.ExploreEducationStatistics.Data.Services.csproj
src/GovUk.Education.ExploreEducationStatistics.Publisher.Tests/GovUk.Education.ExploreEducationStatistics.Publisher.Tests.csproj
src/GovUk.Education.ExploreEducationStatistics.Publisher/GovUk.Education.ExploreEducationStatistics.Publisher.csproj

We are holding back from a .NET 6 upgrade until its final release, scheduled for November 2021.
@ntsim attempted a .NET 5 upgrade but found a problem with Azure Functions mentioned in the description of https://github.com/dfe-analytical-services/explore-education-statistics/pull/2737 which upgraded to C# 9.
This PR upgrades all project dependencies from .NET Core 3.1.5 released June 2020 to 3.1.18 released in the [August 2021 updates](https://devblogs.microsoft.com/dotnet/net-august-2021/).
This upgrade was made as part of trying to solve a bug found during the testing of https://github.com/dfe-analytical-services/explore-education-statistics/pull/2785. The bug was elsewhere.
As there appear to be no breakages (see the test results attached here run with latest code from `dev`), it seems …

EES-2348 Upgrade .NET Core 3.1.5 to 3.1.18

---

src/GovUk.Education.ExploreEducationStatistics.Common.Tests/Extensions/ReflectionExtensionsTests.cs
src/GovUk.Education.ExploreEducationStatistics.Common/Extensions/ReflectionExtensions.cs

This PR fixes AOP cached methods not actually returning cached results when the method return type is a supertype (such as `IList`), but the actual returned value was a subtype (such as `List`). We could see this most prominently with the content trees which exhibited this behaviour.

EES-2625 Fix AOP cache not being hit for supertypes

---

src/explore-education-statistics-common/src/components/form/FormCheckboxGroup.tsx
src/explore-education-statistics-common/src/components/form/FormCheckboxSearchSubGroups.tsx
src/explore-education-statistics-common/src/components/form/FormFieldCheckboxGroup.tsx
src/explore-education-statistics-common/src/components/form/FormFieldCheckboxSearchGroup.tsx
src/explore-education-statistics-common/src/components/form/FormFieldCheckboxSearchSubGroups.tsx

Fixes problems with select all and search on the table tool:
1. 'Select all' not working for filtered locations and Indicators/Filters with multiple sub-categories
2. Search not working for Indicators/Filters with only one sub-category
The existing unit tests pass, slightly worryingly. They should be updated to cover these scenarios. I can do this next week, either as part of this PR or separately if this gets merged.

EES-2631 fix select all and search issues

---

src/explore-education-statistics-admin/src/pages/release/datablocks/components/chart/ChartAxisConfiguration.tsx
src/explore-education-statistics-admin/src/pages/release/datablocks/components/chart/__tests__/ChartAxisConfiguration.test.tsx
src/explore-education-statistics-common/src/modules/charts/types/chart.ts
src/explore-education-statistics-common/src/modules/charts/util/__tests__/createDataSetCategories.test.ts
src/explore-education-statistics-common/src/modules/charts/util/createDataSetCategories.ts

Adds an option to select a specific filter when grouping a chart by filter.
Changes the group by options to a radio group as that works best with conditionally showing the filters dropdown.
The filters dropdown is hidden behind the `showGroupByFilter` flag as backend work to store the value is required (EES-2620)

EES-2467 chart group by filters

---

src/GovUk.Education.ExploreEducationStatistics.Admin.Tests/Security/AuthorizationHandlers/LegacyReleaseAuthorizationHandlersTests.cs
src/GovUk.Education.ExploreEducationStatistics.Admin.Tests/Security/AuthorizationHandlers/Utils/PublicationAuthorizationHandlersTestUtil.cs
src/GovUk.Education.ExploreEducationStatistics.Admin/Security/AuthorizationHandlers/LegacyReleaseAuthorizationHandlers.cs
src/explore-education-statistics-admin/src/pages/publication/PublicationEditPage.tsx
src/explore-education-statistics-admin/src/routes/legacyReleaseRoutes.tsx
src/explore-education-statistics-admin/src/routes/routes.ts

This PR allows publication owners to manage legacy releases.
Now that users manage legacy releases on the Manage publication page, besides adding permissions for publication owners, the permissions have been aligned with the rest of the manage publication page.
Since the HandleRequirementAsync override for the manage legacy releases authorization handlers takes a LegacyRelease object, not a Release or Publication, I've created a new method to test all different publication roles for that.

EES-2553 Publication owners should be able to manage legacy releases

---

src/GovUk.Education.ExploreEducationStatistics.Common.Tests/Model/PartialDateTest.cs
src/GovUk.Education.ExploreEducationStatistics.Common/Extensions/DbContextExtensions.cs
src/GovUk.Education.ExploreEducationStatistics.Common/Model/PartialDate.cs
src/GovUk.Education.ExploreEducationStatistics.Content.Api/Controllers/ReleaseController.cs
src/GovUk.Education.ExploreEducationStatistics.Content.Api/Startup.cs
src/GovUk.Education.ExploreEducationStatistics.Content.Model.Tests/ReleaseTests.cs
src/GovUk.Education.ExploreEducationStatistics.Content.Security.Tests/AuthorizationHandlers/ViewPublicationAuthorizationHandlerTests.cs
src/GovUk.Education.ExploreEducationStatistics.Content.Security.Tests/AuthorizationHandlers/ViewReleaseAuthorizationHandlerTests.cs
src/GovUk.Education.ExploreEducationStatistics.Content.Security/AuthorizationHandlers/ViewPublicationAuthorizationHandler.cs
src/GovUk.Education.ExploreEducationStatistics.Content.Security/AuthorizationHandlers/ViewReleaseAuthorizationHandler.cs
src/GovUk.Education.ExploreEducationStatistics.Content.Security/ContentSecurityPolicies.cs
src/GovUk.Education.ExploreEducationStatistics.Content.Security/Extensions/UserServiceExtensions.cs
src/GovUk.Education.ExploreEducationStatistics.Content.Services.Tests/ReleaseServiceTests.cs
src/GovUk.Education.ExploreEducationStatistics.Content.Services/Interfaces/IReleaseService.cs
src/GovUk.Education.ExploreEducationStatistics.Content.Services/ReleaseService.cs
src/GovUk.Education.ExploreEducationStatistics.Content.Services/ViewModels/MetaGuidanceViewModel.cs
src/GovUk.Education.ExploreEducationStatistics.Content.Services/ViewModels/PreReleaseAccessListViewModel.cs
src/GovUk.Education.ExploreEducationStatistics.Content.Services/ViewModels/ReleaseSummaryViewModel.cs
src/GovUk.Education.ExploreEducationStatistics.Publisher.Model/ViewModels/ReleaseTypeViewModel.cs
src/explore-education-statistics-common/src/services/publicationService.ts
src/explore-education-statistics-common/src/services/releaseMetaGuidanceService.ts
src/explore-education-statistics-frontend/src/modules/data-catalogue/DataCataloguePage.tsx
src/explore-education-statistics-frontend/src/modules/data-catalogue/__tests__/DataCataloguePage.test.tsx
src/explore-education-statistics-frontend/src/modules/data-catalogue/components/DownloadStep.tsx
src/explore-education-statistics-frontend/src/modules/data-catalogue/components/ReleaseForm.tsx
src/explore-education-statistics-frontend/src/modules/data-catalogue/components/ReleaseStep.tsx
src/explore-education-statistics-frontend/src/modules/data-catalogue/components/__tests__/DownloadStep.test.tsx
src/explore-education-statistics-frontend/src/modules/data-catalogue/components/__tests__/ReleaseStep.test.tsx

This PR adds a new Content API endpoint (`/publications/{publicationId}/releases`) that fetches a publication's published releases.
- Added `ViewPublicationAuthorizationHandler` to secure the new endpoint.
- Added new `TryReloadEntity` and `ReloadEntity` extension methods for `DbContext`. These are intended to try to ensure that entities passed to a service method are actually up-to-date and have not been detached from the context or have been deleted from the database. 
This is a common issue whilst passing raw database entities between various service classes and it is recommended that we use when we can't 100% know the state of the entity before it is received by the service e.g. authorization handlers.
- Enabled nullable on `PartialDate` and fixed various issues with it potentially …

EES-2657 Add Content API endpoint to query a publication's releases

---

src/GovUk.Education.ExploreEducationStatistics.Admin.Tests/Mappings/MyPublicationMethodologyPermissionsPropertyResolverTest.cs
src/GovUk.Education.ExploreEducationStatistics.Admin.Tests/Security/AuthorizationHandlers/DropMethodologyLinkAuthorizationHandlerTests.cs
src/GovUk.Education.ExploreEducationStatistics.Admin.Tests/Services/Extensions/MockUserPublicationRoleRepositoryExtensions.cs
src/GovUk.Education.ExploreEducationStatistics.Admin.Tests/Services/MapperUtils.cs
src/GovUk.Education.ExploreEducationStatistics.Admin.Tests/Services/Methodologies/MethodologyServicePermissionTests.cs
src/GovUk.Education.ExploreEducationStatistics.Admin.Tests/Services/Methodologies/MethodologyServiceTests.cs
src/GovUk.Education.ExploreEducationStatistics.Admin.Tests/Services/PublicationRepositoryTests.cs
src/GovUk.Education.ExploreEducationStatistics.Admin.Tests/Services/PublicationServicePermissionTests.cs
src/GovUk.Education.ExploreEducationStatistics.Admin/Mappings/Interfaces/IMyPublicationMethodologyPermissionsPropertyResolver.cs
src/GovUk.Education.ExploreEducationStatistics.Admin/Mappings/MappingProfiles.cs
src/GovUk.Education.ExploreEducationStatistics.Admin/Mappings/MyPublicationMethodologyPermissionsPropertyResolver.cs
src/GovUk.Education.ExploreEducationStatistics.Admin/Security/AuthorizationHandlers/DropMethodologyLinkAuthorizationHandler.cs
src/GovUk.Education.ExploreEducationStatistics.Admin/Security/SecurityPolicies.cs
src/GovUk.Education.ExploreEducationStatistics.Admin/Security/StartupSecurityConfiguration.cs
src/GovUk.Education.ExploreEducationStatistics.Admin/Services/Interfaces/IPublicationRepository.cs
src/GovUk.Education.ExploreEducationStatistics.Admin/Services/Interfaces/Security/UserServiceExtensions.cs
src/GovUk.Education.ExploreEducationStatistics.Admin/Services/Methodologies/MethodologyService.cs
src/GovUk.Education.ExploreEducationStatistics.Admin/Services/PublicationRepository.cs
src/GovUk.Education.ExploreEducationStatistics.Admin/Services/PublicationService.cs
src/GovUk.Education.ExploreEducationStatistics.Admin/Startup.cs
src/GovUk.Education.ExploreEducationStatistics.Admin/Validators/ValidationUtils.cs
src/GovUk.Education.ExploreEducationStatistics.Admin/ViewModels/MyMethodologyViewModel.cs
src/GovUk.Education.ExploreEducationStatistics.Admin/ViewModels/MyPublicationMethodologyViewModel.cs
src/GovUk.Education.ExploreEducationStatistics.Admin/ViewModels/MyPublicationViewModel.cs
src/explore-education-statistics-admin/src/pages/admin-dashboard/components/MethodologySummary.tsx
src/explore-education-statistics-admin/src/pages/admin-dashboard/components/__tests__/MethodologySummary.test.tsx
src/explore-education-statistics-admin/src/services/publicationService.ts

This PR alters the `MyPublicationViewModel` to change the list of methodologies to be a list of `MyPublicationMethodologyViewModel` representing the links between publications and methodologies.
This has the `Owner` property which is true if this publication owns the methodology and will allow the front end to distinguish the methodology for a publication as the primary methodology from other adopted methodologies.
It also has a `Permissions` property with a permission `CanDropMethodology`. This allows a front end decision to be made on whether to allow dropping the link.
Here is a sample back end response (abbreviated) showing what this would appear as for two methodologies, one owned by the publication and the other adopted from a different publication, where the user is a BAU user or a …

EES-2660 Add the owner and drop permission values to MyPublicationViewModel for each Methodology

---

tests/robot-tests/tests/general_public/methodology_page_absence.robot

This PR: 
- disables the `methodlogy_page_absence` UI test from running against pre-prod & prod environments. This is due to the test data not being present in both environments.

EES-2650-2 - disable `methodlogy_page_absence` UI test

---

src/explore-education-statistics-common/src/modules/charts/components/MapBlockInternal.tsx
src/explore-education-statistics-common/src/modules/charts/components/__tests__/MapBlock.test.tsx
src/explore-education-statistics-common/src/modules/charts/components/__tests__/__data__/testMapBlockData.ts

Updates the 'Select a location' dropdown label on maps to show the specific level of location, eg 'Select a Local Authority'. If more than one level is in the dataset then 'Select a location' is shown.

EES-2555 location type in map dropdown label

---

src/GovUk.Education.ExploreEducationStatistics.Admin.Tests/Controllers/Api/Methodologies/MethodologyControllerTests.cs
src/GovUk.Education.ExploreEducationStatistics.Admin.Tests/Services/Methodologies/MethodologyServiceTests.cs
src/GovUk.Education.ExploreEducationStatistics.Admin/Controllers/Api/Methodologies/MethodologyController.cs
src/GovUk.Education.ExploreEducationStatistics.Admin/Services/Interfaces/Methodologies/IMethodologyService.cs
src/GovUk.Education.ExploreEducationStatistics.Admin/Services/Methodologies/MethodologyService.cs
src/GovUk.Education.ExploreEducationStatistics.Admin/ViewModels/Methodology/MethodologySummaryViewModel.cs
src/GovUk.Education.ExploreEducationStatistics.Common/Extensions/DbContextExtensions.cs
src/GovUk.Education.ExploreEducationStatistics.Content.Model.Tests/Repository/MethodologyRepositoryTests.cs
src/GovUk.Education.ExploreEducationStatistics.Content.Model/Repository/Interfaces/IMethodologyRepository.cs
src/GovUk.Education.ExploreEducationStatistics.Content.Model/Repository/MethodologyRepository.cs

This PR changes the response of the URL `GET /api/publication/{publicationId}/adoptable-methodologies` to return a list of `MethodologySummaryViewModel` resources rather than `TitleAndIdViewModel`.
This is so that future work on the UI to implement managing adoption of methodologies can show additional details about them such as their status, publication, published date, amendment flag, etc.
It also refactors the various methods of `MethodologyService` that now return a `MethodologySummaryViewModel` to use a common method to build the view model.
The unit tests are enhanced around checking the fields of a `MethodologySummaryViewModel` result to ensure the various fields of it are being mapped correctly.

EES-2284 Return MethodologySummaryViewModel  as result of getting the adoptable methodologies

---

src/GovUk.Education.ExploreEducationStatistics.Admin.Tests/Services/ReplacementServiceTests.cs
src/GovUk.Education.ExploreEducationStatistics.Admin/Services/ReplacementService.cs
src/GovUk.Education.ExploreEducationStatistics.Data.Model/Country.cs
src/GovUk.Education.ExploreEducationStatistics.Data.Model/EnglishDevolvedArea.cs
src/GovUk.Education.ExploreEducationStatistics.Data.Model/IObservationalUnit.cs
src/GovUk.Education.ExploreEducationStatistics.Data.Model/Institution.cs
src/GovUk.Education.ExploreEducationStatistics.Data.Model/LocalAuthority.cs
src/GovUk.Education.ExploreEducationStatistics.Data.Model/LocalAuthorityDistrict.cs
src/GovUk.Education.ExploreEducationStatistics.Data.Model/LocalEnterprisePartnership.cs
src/GovUk.Education.ExploreEducationStatistics.Data.Model/Mat.cs
src/GovUk.Education.ExploreEducationStatistics.Data.Model/MayoralCombinedAuthority.cs
src/GovUk.Education.ExploreEducationStatistics.Data.Model/ObservationalUnit.cs
src/GovUk.Education.ExploreEducationStatistics.Data.Model/OpportunityArea.cs
src/GovUk.Education.ExploreEducationStatistics.Data.Model/ParliamentaryConstituency.cs
src/GovUk.Education.ExploreEducationStatistics.Data.Model/PlanningArea.cs
src/GovUk.Education.ExploreEducationStatistics.Data.Model/Provider.cs
src/GovUk.Education.ExploreEducationStatistics.Data.Model/Region.cs
src/GovUk.Education.ExploreEducationStatistics.Data.Model/Repository/Interfaces/ILocationRepository.cs
src/GovUk.Education.ExploreEducationStatistics.Data.Model/Repository/LocationRepository.cs
src/GovUk.Education.ExploreEducationStatistics.Data.Model/RscRegion.cs
src/GovUk.Education.ExploreEducationStatistics.Data.Model/School.cs
src/GovUk.Education.ExploreEducationStatistics.Data.Model/Sponsor.cs
src/GovUk.Education.ExploreEducationStatistics.Data.Model/Ward.cs
src/GovUk.Education.ExploreEducationStatistics.Data.Processor/Services/ImporterLocationService.cs
src/GovUk.Education.ExploreEducationStatistics.Data.Services.Tests/TableBuilderSubjectMetaServiceTests.cs
src/GovUk.Education.ExploreEducationStatistics.Data.Services/AbstractSubjectMetaService.cs
src/GovUk.Education.ExploreEducationStatistics.Data.Services/Mappings/DataServiceMappingProfiles.cs
src/GovUk.Education.ExploreEducationStatistics.Data.Services/ResultSubjectMetaService.cs
src/GovUk.Education.ExploreEducationStatistics.Data.Services/SubjectMetaService.cs

This PR:
- fixes a bug whereby Locations with duplicate codes but different names were not being returned via the API to the table tool
The cause of the bug was a very innocent Distinct() call on a list of IObservationalUnits. The real bug was that the Observational Units in questions implemented Equals() and hashcode methods that only operated on Code, and not the combination of Code and Name.
I've restructured the various Observational Units to extend a common base class that holds Code and Name and the equality members. The various subclasses are now all much smaller.
I have also removed some JSON annotations on RscRegion, which after speaking with Ben, we believe to be redundant nowadays. Still, some good testing with all sorts of Location types will be required.

Ees 2662 locations with duplicate codes removed from table tool as hotfix

---

src/GovUk.Education.ExploreEducationStatistics.Admin.Tests/Services/DataBlockServiceTests.cs
src/GovUk.Education.ExploreEducationStatistics.Common/Model/Chart/Charts.cs
src/GovUk.Education.ExploreEducationStatistics.Content.Model/ContentBlock.cs
src/explore-education-statistics-admin/src/pages/release/__data__/testEditableRelease.ts
src/explore-education-statistics-admin/src/pages/release/content/contexts/__tests__/ReleaseContentContext.test.tsx
src/explore-education-statistics-admin/src/pages/release/datablocks/components/DataBlockPageTabs.tsx
src/explore-education-statistics-admin/src/pages/release/datablocks/components/chart/ChartBuilder.tsx
src/explore-education-statistics-admin/src/pages/release/datablocks/components/chart/ChartBuilderTabSection.tsx
src/explore-education-statistics-admin/src/pages/release/datablocks/components/chart/ChartConfiguration.tsx
src/explore-education-statistics-admin/src/pages/release/datablocks/components/chart/reducers/__tests__/chartBuilderReducer.test.ts
src/explore-education-statistics-admin/src/pages/release/datablocks/components/chart/reducers/chartBuilderReducer.ts
src/explore-education-statistics-admin/src/pages/release/pre-release/__tests__/PreReleaseTableToolPage.test.tsx
src/explore-education-statistics-common/src/modules/charts/types/chart.ts
src/explore-education-statistics-common/src/modules/table-tool/components/DataTableCaption.tsx
src/explore-education-statistics-common/src/modules/table-tool/components/__tests__/DataTableCaption.test.tsx
src/explore-education-statistics-common/src/modules/table-tool/components/__tests__/DownloadTable.test.tsx
src/explore-education-statistics-common/src/modules/table-tool/components/__tests__/TimePeriodDataTable.test.tsx
src/explore-education-statistics-frontend/src/modules/permalink/__tests__/PermalinkPage.test.tsx
src/explore-education-statistics-frontend/src/modules/table-tool/components/__tests__/TableToolFinalStep.test.tsx
tests/robot-tests/tests/admin/bau/create_data_block_with_chart.robot
tests/robot-tests/tests/admin/bau/delete_subject.robot
tests/robot-tests/tests/admin/bau/prerelease.robot
tests/robot-tests/tests/admin_and_public/bau/publish_data.robot

This PR allows users to set the chart title to default to using the table heading. Alternatively, users can enter a custom title for a data block's chart.
The backend now expects no chart title to be in a request when the chart title should default to the table heading. This can be seen in `ContentBlock.cs`.
But the backend does return the table heading as the chart title in response to a request for a data block. Because of this, the frontend works out whether the data block response is defaulting to the table heading by comparing the table heading with the chart title. If they're equal, it assumes the chart title is inheriting the table title.
An additional wrinkle was that when changing a data block's heading, because the old data block heading was returned as the chart title when …

EES-2417 Add ability to use the table heading as the chart title

---

src/GovUk.Education.ExploreEducationStatistics.Admin.Tests/Models/VersionedEntityDeletionOrderComparerTests.cs
src/GovUk.Education.ExploreEducationStatistics.Admin.Tests/Services/Methodologies/MethodologyImageServicePermissionTests.cs
src/GovUk.Education.ExploreEducationStatistics.Admin.Tests/Services/Methodologies/MethodologyImageServiceTests.cs
src/GovUk.Education.ExploreEducationStatistics.Admin.Tests/Services/Methodologies/MethodologyServicePermissionTests.cs
src/GovUk.Education.ExploreEducationStatistics.Admin.Tests/Services/Methodologies/MethodologyServiceTests.cs
src/GovUk.Education.ExploreEducationStatistics.Admin.Tests/Services/TopicServiceTests.cs
src/GovUk.Education.ExploreEducationStatistics.Admin.Tests/ViewModels/PublicationSaveViewModelTests.cs
src/GovUk.Education.ExploreEducationStatistics.Admin/Models/IdAndPreviousVersionIdPair.cs
src/GovUk.Education.ExploreEducationStatistics.Admin/Services/Interfaces/Methodologies/IMethodologyImageService.cs
src/GovUk.Education.ExploreEducationStatistics.Admin/Services/Interfaces/Methodologies/IMethodologyService.cs
src/GovUk.Education.ExploreEducationStatistics.Admin/Services/Interfaces/Security/UserServiceExtensions.cs
src/GovUk.Education.ExploreEducationStatistics.Admin/Services/Methodologies/MethodologyImageService.cs
src/GovUk.Education.ExploreEducationStatistics.Admin/Services/Methodologies/MethodologyService.cs
src/GovUk.Education.ExploreEducationStatistics.Admin/Services/TopicService.cs
src/GovUk.Education.ExploreEducationStatistics.Common.Tests/Extensions/MockBlobStorageServiceExtensions.cs

When the UI tests complete they delete the Topic resource using `DELETE /api/topics/{topicId}`.
The service method being called depends on several other service calls to forcefully delete Methodologies and Releases.
The results of some of these calls were being ignored making it appear as though the Topic has been deleted successfully (returning 204 No Content), when in some cases an error should have occurred.
_Example Failure_
If a Topic contains any approved Methodologies with images, there should have been a 403 Forbidden as the user does not have permission to update an approved Methodology.
This PR also prevents this failure by adding in a `DeleteAll` method to forcefully delete Methodology images.
- Delete Releases that are soft deleted. Failures caused by attempting to delete a …

EES-2674 Return failure results when deleting topics and forcefully delete methodology images

---

src/GovUk.Education.ExploreEducationStatistics.Admin.Tests/Controllers/Api/ReleasesControllerTests.cs
src/GovUk.Education.ExploreEducationStatistics.Admin.Tests/Services/ReleaseServicePermissionTests.cs
src/GovUk.Education.ExploreEducationStatistics.Admin.Tests/Services/ReleaseServiceTests.cs
src/GovUk.Education.ExploreEducationStatistics.Admin/Controllers/Api/ReleasesController.cs
src/GovUk.Education.ExploreEducationStatistics.Admin/Services/Interfaces/IReleaseService.cs
src/GovUk.Education.ExploreEducationStatistics.Admin/Services/ReleaseService.cs
src/GovUk.Education.ExploreEducationStatistics.Common.Tests/Extensions/ActionResultTestExtensions.cs
src/explore-education-statistics-admin/src/pages/admin-dashboard/components/CancelAmendmentModal.tsx
src/explore-education-statistics-admin/src/pages/admin-dashboard/components/DraftReleasesTab.tsx
src/explore-education-statistics-admin/src/pages/admin-dashboard/components/NonScheduledReleaseSummary.tsx
src/explore-education-statistics-admin/src/pages/admin-dashboard/components/PublicationSummary.tsx
src/explore-education-statistics-admin/src/pages/admin-dashboard/components/ReleaseSummary.tsx
src/explore-education-statistics-admin/src/pages/admin-dashboard/components/__tests__/CancelAmendmentModal.test.tsx
src/explore-education-statistics-admin/src/pages/admin-dashboard/components/__tests__/MethodologySummary.test.tsx
src/explore-education-statistics-admin/src/pages/admin-dashboard/components/__tests__/NonScheduledReleaseSummary.test.tsx
src/explore-education-statistics-admin/src/pages/admin-dashboard/components/__tests__/PublicationSummary.test.tsx
src/explore-education-statistics-admin/src/services/releaseService.ts
src/explore-education-statistics-admin/test/createMemoryHistoryWithMockedPush.ts
tests/robot-tests/tests/admin_and_public/bau/publish_methodology.robot
tests/robot-tests/tests/libs/admin-common.robot

This PR:
- adds a list of Methodologies to the warning modal when deleting a Release Amendment if they are scheduled to be published alongside the Release Amendment.
- unsets any Methodology scheduling details after the Amendment is deleted.
- resets the Methodologies to Draft, otherwise they would be left as "Approved" / "Immediately".
Also in this PR, I noticed we didn't have any coverage of `PublicationSummary.tsx`, so I've added various test cases around this component, including the deleting of Amendments, which is the last test case.
Also, I've moved the Cancel modal functionality into `NonScheduledReleaseSummary.tsx` and out of its parent components, to reduce the duplication of code.  I've added Jest tests for `NonScheduledReleaseSummary.tsx` as well as we didn't have any before.

Ees 2151 warning when cancelling release amendment with scheduled methodologies

---

src/GovUk.Education.ExploreEducationStatistics.Admin.Tests/Services/Methodologies/MethodologyAmendmentServiceTests.cs
src/GovUk.Education.ExploreEducationStatistics.Admin.Tests/Services/Methodologies/MethodologyNoteServicePermissionTests.cs
src/GovUk.Education.ExploreEducationStatistics.Admin.Tests/Services/Methodologies/MethodologyNoteServiceTests.cs
src/GovUk.Education.ExploreEducationStatistics.Admin/Controllers/Api/Methodologies/MethodologyNoteController.cs
src/GovUk.Education.ExploreEducationStatistics.Admin/Mappings/MappingProfiles.cs
src/GovUk.Education.ExploreEducationStatistics.Admin/Migrations/ContentMigrations/20210913161056_EES-2171_AddMethodologyNotes.Designer.cs
src/GovUk.Education.ExploreEducationStatistics.Admin/Migrations/ContentMigrations/20210913161056_EES-2171_AddMethodologyNotes.cs
src/GovUk.Education.ExploreEducationStatistics.Admin/Migrations/ContentMigrations/20210914150247_EES-2171_AddMethodologyNotes.Designer.cs
src/GovUk.Education.ExploreEducationStatistics.Admin/Migrations/ContentMigrations/20210914150247_EES-2171_AddMethodologyNotes.cs
src/GovUk.Education.ExploreEducationStatistics.Admin/Migrations/ContentMigrations/ContentDbContextModelSnapshot.cs
src/GovUk.Education.ExploreEducationStatistics.Admin/Services/Interfaces/Methodologies/IMethodologyNoteService.cs
src/GovUk.Education.ExploreEducationStatistics.Admin/Services/Methodologies/MethodologyAmendmentService.cs
src/GovUk.Education.ExploreEducationStatistics.Admin/Services/MethodologyNoteService.cs
src/GovUk.Education.ExploreEducationStatistics.Admin/Startup.cs
src/GovUk.Education.ExploreEducationStatistics.Admin/ViewModels/Methodology/MethodologyNoteAddRequest.cs
src/GovUk.Education.ExploreEducationStatistics.Admin/ViewModels/Methodology/MethodologyNoteUpdateRequest.cs
src/GovUk.Education.ExploreEducationStatistics.Admin/ViewModels/Methodology/MethodologyNoteViewModel.cs
src/GovUk.Education.ExploreEducationStatistics.Content.Model.Tests/MethodologyVersionTests.cs
src/GovUk.Education.ExploreEducationStatistics.Content.Model.Tests/Repository/MethodologyNoteRepositoryTests.cs
src/GovUk.Education.ExploreEducationStatistics.Content.Model/Database/ContentDbContext.cs
src/GovUk.Education.ExploreEducationStatistics.Content.Model/MethodologyNote.cs
src/GovUk.Education.ExploreEducationStatistics.Content.Model/MethodologyVersion.cs
src/GovUk.Education.ExploreEducationStatistics.Content.Model/Repository/Interfaces/IMethodologyNoteRepository.cs
src/GovUk.Education.ExploreEducationStatistics.Content.Model/Repository/MethodologyNoteRepository.cs
src/GovUk.Education.ExploreEducationStatistics.Content.Model/Update.cs

This PR introduces support for methodology version notes along with a new API to create, update and delete them.
* `POST /api/methodologies/{versionId}/notes`
* Returns the created note view model resource.
* `PUT /api/methodologies/{versionId}/notes/{id}`
* Returns the updated note view model resource.
* `DELETE /api/methodologies/{versionId}/notes/{id}`
* Deletes the note and returns no content.
- Clone notes when creating a new methodology version.
- Notes are cloned for the new version and are assigned a new Id but retain all other values, i.e. the original content, display date, created and last updated dates, created by and last updated by users id's.

EES-2304 EES-2306  Introduce support for methodology version notes

---

infrastructure/templates/template.json

This is an attempt to fix a FileLoadException error that sometimes
prevents the Admin app starting on an environment after a deploy - and
we have to manually restart it.

EES-949 Update apiVersion for appInsight instances in ARM template

---

src/GovUk.Education.ExploreEducationStatistics.Admin.Tests/Services/ReleaseServiceTests.cs
src/GovUk.Education.ExploreEducationStatistics.Admin/Migrations/ContentMigrations/20210906084644_EES968AddNotifySubscribersColumnToReleaseStatus.Designer.cs
src/GovUk.Education.ExploreEducationStatistics.Admin/Migrations/ContentMigrations/20210906084644_EES968AddNotifySubscribersColumnToReleaseStatus.cs
src/GovUk.Education.ExploreEducationStatistics.Admin/Migrations/ContentMigrations/20210913090611_EES968AddNotifiedOnColumnToReleaseStatus.Designer.cs
src/GovUk.Education.ExploreEducationStatistics.Admin/Migrations/ContentMigrations/20210913090611_EES968AddNotifiedOnColumnToReleaseStatus.cs
src/GovUk.Education.ExploreEducationStatistics.Admin/Services/ReleaseService.cs
src/GovUk.Education.ExploreEducationStatistics.Admin/ViewModels/ReleaseViewModels.cs
src/GovUk.Education.ExploreEducationStatistics.Content.Model/Database/ContentDbContext.cs
src/GovUk.Education.ExploreEducationStatistics.Content.Model/Release.cs
src/GovUk.Education.ExploreEducationStatistics.Content.Model/ReleaseStatus.cs
src/GovUk.Education.ExploreEducationStatistics.Notifier.Model/PublicationNotificationMessage.cs
src/GovUk.Education.ExploreEducationStatistics.Publisher.Tests/Services/NotificationsServiceTests.cs
src/GovUk.Education.ExploreEducationStatistics.Publisher/Functions/PublishReleaseContentFunction.cs
src/GovUk.Education.ExploreEducationStatistics.Publisher/Functions/PublishStagedReleaseContentFunction.cs
src/GovUk.Education.ExploreEducationStatistics.Publisher/Services/Interfaces/INotificationsService.cs
src/GovUk.Education.ExploreEducationStatistics.Publisher/Services/NotificationsService.cs
src/explore-education-statistics-admin/src/pages/release/components/ReleaseStatusForm.tsx
src/explore-education-statistics-admin/src/pages/release/components/__tests__/ReleaseStatusForm.test.tsx
src/explore-education-statistics-admin/src/services/releaseService.ts
tests/robot-tests/tests/admin/analyst/role_ui_permissions/release_and_publication_role_end_to_end_permissions.robot
tests/robot-tests/tests/admin/bau/comments.robot
tests/robot-tests/tests/admin/bau/create_methodology_amendment.robot
tests/robot-tests/tests/admin_and_public/bau/publish_data.robot
tests/robot-tests/tests/admin_and_public/bau/publish_methodology.robot
tests/robot-tests/tests/admin_and_public/bau/publish_release_and_amend.robot
tests/robot-tests/tests/admin_and_public/bau/publish_release_and_amend_2.robot
tests/robot-tests/tests/libs/admin-common.robot
tests/robot-tests/tests/libs/bootstrap_data/bootstrap_common.robot

This PR adds a `Notify subscribers by email` checkbox when approving an amended release on the Admin Sign off page.
Previously, subscribers would be notified every time a release would be published. Now, analysts can choose whether subscribers are notified when publishing an amendment. Subscribers are still always notified when an original release is published.
Edit: 
We've additionally added a `NotifyOn` column to the Content DB ReleaseStatus table. This is to reduce the chance that we send a notification email twice.
It is possible for a ReleaseStatus to have `NotifySubscribers` set to true and the `NotifyOn` column to never get set. This happens if a user schedules a release for publication and then moves it back to draft. The ReleaseStatus associated with the scheduling of the release …

EES-968 Notifying subscribers for amendment release publication now optional

---

src/GovUk.Education.ExploreEducationStatistics.Admin.Tests/Services/Methodologies/MethodologyNoteServiceTests.cs
src/GovUk.Education.ExploreEducationStatistics.Admin/Services/MethodologyNoteService.cs
src/GovUk.Education.ExploreEducationStatistics.Admin/ViewModels/Methodology/MethodologyNoteAddRequest.cs
src/GovUk.Education.ExploreEducationStatistics.Admin/ViewModels/Methodology/MethodologyNoteUpdateRequest.cs

This PR is a bugfix to prevent requests that accidently omit the `DisplayDate` field from setting the `DateTime` default value `0000-00-00T00:00:00` when adding or updating methodology notes.
Type `DateTime` has a default value of `0000-00-00T00:00:00`. Even when applying the `[Required]` attribute this default value would be assigned if the request field was missing rather than resulting in an invalid model state and a validation error.
This PR changes the fields to be of type `DateTime?` rather than `DateTime` and applies the `[Required]` attribute so that requests omitting the field now receive a validation error:
```
{
"errors": {
"DisplayDate": [
"The DisplayDate field is required."
]
},
...
}
```
At the service level we now default to using `DateTime.Today` if the field has no value …

EES-2306 Add Required attribute to DisplayDate field when adding/updating Methodology Notes

---

Pipfile
Pipfile.lock

This PR: 
- updates RF to 4.1.1 
- updates peer dependencies of RF
- updates azure-core from 1.16.0 to 1.8.0

EES-2695 - update RF to 4.1.1

---

src/explore-education-statistics-common/src/modules/table-tool/components/WizardStep.module.scss
src/explore-education-statistics-common/src/modules/table-tool/components/WizardStepHeading.tsx
src/explore-education-statistics-frontend/src/modules/data-catalogue/components/DownloadStep.tsx

This PR adds the following 'Select/Unselect all' button to the data catalogue's downloads step (step 3):
- Adds minor adjustments to the margin between wizard steps to make things look nicer in error states (where an `ErrorSummary` component is rendered)

EES-2693 Add 'Select all' button to data catalogue's downloads step

---

src/GovUk.Education.ExploreEducationStatistics.Admin.Tests/Services/Methodologies/MethodologyServiceTests.cs
src/GovUk.Education.ExploreEducationStatistics.Admin/ViewModels/Methodology/MethodologySummaryViewModel.cs
src/explore-education-statistics-admin/src/pages/methodology/edit-methodology/__tests__/MethodologyPage.test.tsx
src/explore-education-statistics-admin/src/pages/methodology/edit-methodology/status/MethodologyStatusPage.tsx
src/explore-education-statistics-admin/src/pages/methodology/edit-methodology/status/__tests__/MethodologyStatusPage.test.tsx
tests/robot-tests/tests/admin_and_public/bau/publish_methodology.robot

This PR adds the expected publicly accessible methodology URL to the admin Sign off tab.
This is done in the same way that we show the release URL from the admin release Sign Off tab.

EES-2711 Add publicly accessible methodology URL to the Sign off tab

---

tests/robot-tests/tests/admin_and_public/bau/publish_data.robot
tests/robot-tests/tests/general_public/prod_table_tool.robot
tests/robot-tests/tests/libs/common.robot

This PR: 
- prevents the prod UI tests from throwing errors due to not finding an element in x amount of seconds. This is caused by the UI tests being run in a slow CI environment. Once the UI tests are able to run in a VMSS this issue should go away

EES-2697 - prevent prod UI tests from throwing false failures

---

src/GovUk.Education.ExploreEducationStatistics.Admin.Tests/Controllers/Api/Statistics/FootnoteControllerTests.cs
src/GovUk.Education.ExploreEducationStatistics.Admin.Tests/Services/MetaGuidanceServiceTests.cs
src/GovUk.Education.ExploreEducationStatistics.Content.Services.Tests/DataGuidanceFileWriterTests.cs
src/GovUk.Education.ExploreEducationStatistics.Content.Services.Tests/MetaGuidanceServiceTests.cs
src/GovUk.Education.ExploreEducationStatistics.Content.Services/DataGuidanceFileWriter.cs
src/GovUk.Education.ExploreEducationStatistics.Data.Services.Tests/MetaGuidanceSubjectServiceTests.cs
src/GovUk.Education.ExploreEducationStatistics.Data.Services.Tests/PublicationServiceTests.cs
src/GovUk.Education.ExploreEducationStatistics.Data.Services.Tests/ReleaseServiceTests.cs
src/GovUk.Education.ExploreEducationStatistics.Data.Services.Tests/TimePeriodServiceTests.cs
src/GovUk.Education.ExploreEducationStatistics.Data.Services/Interfaces/ITimePeriodService.cs
src/GovUk.Education.ExploreEducationStatistics.Data.Services/MetaGuidanceSubjectService.cs
src/GovUk.Education.ExploreEducationStatistics.Data.Services/ReleaseService.cs
src/GovUk.Education.ExploreEducationStatistics.Data.Services/TimePeriodService.cs
src/GovUk.Education.ExploreEducationStatistics.Data.Services/ViewModels/MetaGuidanceSubjectViewModel.cs
src/GovUk.Education.ExploreEducationStatistics.Data.Services/ViewModels/SubjectViewModel.cs
src/GovUk.Education.ExploreEducationStatistics.Data.Services/ViewModels/TimePeriodLabels.cs

After changing TimePeriods to TimePeriodRange, this broke the app as the frontend was expecting `timePeriods` not `timePeriodRange`. So I've changed everything back to what it was originally named rather than changing the frontend, just in case this is cached somewhere.

EES-2715 Rename TimePeriodRangeLabels back to TimePeriodLabels

---

src/GovUk.Education.ExploreEducationStatistics.Admin.Tests/Security/AuthorizationHandlers/CreateMethodologyForSpecificPublicationAuthorizationHandlerTests.cs
src/GovUk.Education.ExploreEducationStatistics.Admin.Tests/Security/AuthorizationHandlers/DeleteSpecificMethodologyAuthorizationHandlerTests.cs
src/GovUk.Education.ExploreEducationStatistics.Admin.Tests/Security/AuthorizationHandlers/ManageExternalMethodologyForSpecificPublicationAuthorizationHandlerTests.cs
src/GovUk.Education.ExploreEducationStatistics.Admin/Security/AuthorizationHandlers/DeleteSpecificMethodologyAuthorizationHandlers.cs
src/GovUk.Education.ExploreEducationStatistics.Content.Model.Tests/MethodologyVersionTests.cs
src/GovUk.Education.ExploreEducationStatistics.Content.Model/MethodologyVersion.cs
tests/robot-tests/tests/admin/analyst/role_ui_permissions/release_and_publication_role_end_to_end_permissions.robot
tests/robot-tests/tests/libs/admin/analyst/role_ui_permissions.robot

The 'Cancel amendment' button deletes a methodology version. To do so the user needs permission to delete the version.
However this also deletes image files in turn which are protected by a separate permission, checking that the user has permission to update the version. This secondary check fails when a version is approved and the user sees a 403 Forbidden error.
This PR makes a change to not show the 'Cancel amendment' button for an approved version, forcing the user to get the version changed to a draft before it can be deleted.
Prior to this change we allowed deleting the first version of a methodology so long as it was a draft, and we allowed deleting amendment versions.
Both of these operations are still allowed as we always allow deleting drafts. However this change prevents …

EES-2698 Prevent deleting approved methodology amendments

---

src/explore-education-statistics-admin/src/pages/methodology/edit-methodology/status/MethodologyStatusPage.tsx
tests/robot-tests/tests/admin_and_public/bau/publish_methodology.robot

This PR makes a change to the methodology Sign off view to refresh the permissions after the form is submitted.
Depending on the new status and the status of releases that are using this methodology, the permissions can change which affect whether the 'Edit status' button should still be shown or not.
Example:
* If a user approves a methodology for publishing immediately and it's already used by a published release, then its publicly accessible immediately. The ‘Edit status’ button should not be visible since it’s publicly accessible and can't be modified except by creating an amendment.
* If a user approves a methodology for publishing immediately and it's _not_ used by any published release, then it's not yet made publicly accessible. We continue to show the 'Edit status' button so that …

EES-2680 Refresh permissions after methodology status update

---

src/explore-education-statistics-admin/src/pages/users/components/PublicationAccessForm.tsx
src/explore-education-statistics-admin/src/pages/users/components/ReleaseAccessForm.tsx
tests/robot-tests/tests/admin/analyst/role_ui_permissions/release_and_publication_role_end_to_end_permissions.robot
tests/robot-tests/tests/admin/bau/themes_and_topics.robot
tests/robot-tests/tests/libs/admin-common.robot

This PR fixes failing UI tests caused by removing incorrect analyst Release roles.
`user removes release access from analyst` was ignoring the Release name, and even then would not be able to accurately identify the correct Release without also having a Publication name parameter.
The test now clicks the correct 'Remove' link to remove the desired permission for the correct Publication/Release/Role combination.
This will also fix an intermittent failing in the test `Navigate to Release where analyst has Release Approver role` which was being caused by the previous suite sometimes removing the incorrect Release role from the analyst.

EES-2698 Fix failing UI tests caused by removing incorrect analyst Release roles

---

src/explore-education-statistics-admin/src/pages/methodology/edit-methodology/__tests__/MethodologyPage.test.tsx
src/explore-education-statistics-admin/src/pages/methodology/edit-methodology/content/MethodologyContentPage.tsx
src/explore-education-statistics-admin/src/pages/methodology/edit-methodology/content/components/MethodologyNotesSection.tsx
src/explore-education-statistics-admin/src/pages/methodology/edit-methodology/content/components/__tests__/MethodologyNotesSection.test.tsx
src/explore-education-statistics-admin/src/pages/methodology/edit-methodology/content/context/__tests__/MethodologyContentContext.test.tsx
src/explore-education-statistics-admin/src/services/methodologyContentService.ts
src/explore-education-statistics-admin/src/services/methodologyNoteService.ts
tests/robot-tests/tests/admin_and_public/bau/publish_methodology.robot
tests/robot-tests/tests/libs/admin-common.robot
tests/robot-tests/tests/libs/admin-utilities.py
tests/robot-tests/tests/libs/admin_api.py

Add, edit and remove methodology notes from the methodology content tab.
Also updates the UI tests and removes the temporary api calls for notes added in https://github.com/dfe-analytical-services/explore-education-statistics/pull/2876/files

EES-2302 add, edit and remove methodology notes

---

src/explore-education-statistics-common/src/components/form/FormFieldRadioGroup.tsx
src/explore-education-statistics-common/src/components/form/FormFieldRadioSearchGroup.module.scss
src/explore-education-statistics-common/src/components/form/FormRadioGroup.tsx
src/explore-education-statistics-common/src/components/form/FormRadioSearchGroup.tsx
src/explore-education-statistics-common/src/components/form/__tests__/__snapshots__/FormRadioSearchGroup.test.tsx.snap
src/explore-education-statistics-frontend/src/modules/data-catalogue/components/ReleaseForm.tsx
src/explore-education-statistics-frontend/src/modules/data-catalogue/components/ReleaseStep.tsx
src/explore-education-statistics-frontend/src/modules/data-catalogue/components/__tests__/ReleaseStep.test.tsx

This removes unnecessarily nested `fieldset` elements across the data catalogue's release step. This kind of nesting is poor for
accessibility and breaks with the step patterns used in the table tool wizard.
We have mostly fixed this by refactoring `FormRadioGroup` (and its associated field/search groups) to be nearly identical to its checkbox group counterparts.

EES-2721 Cleanup radio group markup across data catalogue

---

src/GovUk.Education.ExploreEducationStatistics.Content.Services.Tests/MethodologyServiceTests.cs
src/GovUk.Education.ExploreEducationStatistics.Content.Services/Mappings/MappingProfiles.cs
src/GovUk.Education.ExploreEducationStatistics.Content.Services/MethodologyService.cs
src/GovUk.Education.ExploreEducationStatistics.Content.Services/ViewModels/MethodologyViewModel.cs
src/GovUk.Education.ExploreEducationStatistics.Content.Services/ViewModels/PublicationSummaryViewModel.cs
src/explore-education-statistics-common/src/services/methodologyService.ts
src/explore-education-statistics-frontend/src/modules/methodologies/MethodologyPage.tsx
src/explore-education-statistics-frontend/src/modules/methodologies/__tests__/MethodologyPage.test.tsx
src/explore-education-statistics-frontend/src/modules/methodologies/__tests__/__data__/testMethodologyData.ts
tests/robot-tests/tests/admin_and_public/bau/publish_methodology.robot
tests/robot-tests/tests/general_public/methodology_page_absence.robot

This PR adds publications links to the general public methodology page for publications that are using the methodology.
This will always include the owning publication of a methodology but can also include other publications which have adopted it.
Since this is a change to the general public site, only visible publications _with published releases_ can be shown.
A recent change has already added in a 'Related information' section to the page which can be seen here on the live site:
This change now adds links to the publications within this section.
Here is the same example but running locally where another publication with a published release has adopted the methodology:

EES-2709 Add publication links to public methodology page

---

src/GovUk.Education.ExploreEducationStatistics.Publisher/Functions/PublishStagedReleaseContentFunction.cs
src/GovUk.Education.ExploreEducationStatistics.Publisher/Functions/PublishTaxonomyFunction.cs
src/GovUk.Education.ExploreEducationStatistics.Publisher/Services/ContentService.cs
src/GovUk.Education.ExploreEducationStatistics.Publisher/Services/Interfaces/IContentService.cs

We also refactor the deleting of all cache tree json files in this PR to prevent the problem arising again.
It looks like due to this refactoring, the PublishTaxonomy function could now potentially be removed entirely. If that's right, I'll create a separate ticket for this work rather than address it here.

EES-2745 Delete Data catalogue page cache tree when publishing a release

---

src/explore-education-statistics-admin/src/pages/methodology/edit-methodology/content/components/MethodologyNotesSection.tsx
src/explore-education-statistics-admin/src/pages/methodology/edit-methodology/content/components/__tests__/MethodologyNotesSection.test.tsx
tests/robot-tests/tests/admin/bau/link_publication_to_external_methodology.robot

Fixes the bug where editing the dates on methodology notes could result in the wrong 'Last updated' date being shown.
Also, fixes the external methodology robot test as noticed it was failing.

EES-2741 fix methodology last updated

---

src/GovUk.Education.ExploreEducationStatistics.Content.Api/Startup.cs
src/GovUk.Education.ExploreEducationStatistics.Data.Api/Startup.cs
src/explore-education-statistics-frontend/.env
src/explore-education-statistics-frontend/src/modules/data-catalogue/DataCataloguePage.tsx
src/explore-education-statistics-frontend/src/modules/find-statistics/PublicationReleasePage.tsx

This PR:
- adds a new file download GA event to the Data Catalogue page
- amends existing file download GA events to send Publication title and Release name separately, to bring in line with the format of the new event in the Data Catalogue page

EES-2687 - added GA download files event to new Data Catalogue page

---

tests/robot-tests/run_tests.py
tests/robot-tests/scripts/create_snapshots.py
tests/robot-tests/tests/libs/admin_api.py
tests/robot-tests/tests/libs/file_operations.py
tests/robot-tests/tests/libs/no_javascript.py
tests/robot-tests/tests/libs/setup_auth_variables.py

Refactors our current implementation of the requests library to use connection pooling. This offers several performance improvements to using the standard `requests.<verb>` method  (lower CPU + memory usage, reduced latency in multiple requests, etc.)
We do this via creating a new session in requests: 
```python 
requests.sessions.HTTPAdapter(
pool_connections=50,
pool_maxsize=50,
max_retries=3
)
session = requests.Session()
def my_request:
myData = session.get("https://www.google.com", flush=True)
```
Sessions allow us to reuse an already opened connection. Each connection is stored in a pool of connections. Reusing the connection to send out multiple requests offers multiple performance improvements
In addition to connection pooling, I've added `flush=True` to all requests. The flush …

EES-2858 - Refactor requests to use connection pooling

---

infrastructure/parameters/dev.parameters.json
infrastructure/templates/template.json
src/GovUk.Education.ExploreEducationStatistics.Admin.Tests/Services/ReplacementServiceTests.cs
src/GovUk.Education.ExploreEducationStatistics.Admin/Controllers/Api/DataBlockQuerySizeController.cs
src/GovUk.Education.ExploreEducationStatistics.Admin/Services/ManageContent/CommentService.cs
src/GovUk.Education.ExploreEducationStatistics.Admin/Startup.cs
src/GovUk.Education.ExploreEducationStatistics.Admin/Validators/ValidationErrorMessages.cs
src/GovUk.Education.ExploreEducationStatistics.Admin/Validators/ValidationUtils.cs
src/GovUk.Education.ExploreEducationStatistics.Admin/appsettings.Development.json
src/GovUk.Education.ExploreEducationStatistics.Common.Tests/Model/Data/Query/LocationQueryTest.cs
src/GovUk.Education.ExploreEducationStatistics.Common/Model/Data/Query/LocationQuery.cs
src/GovUk.Education.ExploreEducationStatistics.Common/Validators/ValidationUtils.cs
src/GovUk.Education.ExploreEducationStatistics.Data.Api/Startup.cs
src/GovUk.Education.ExploreEducationStatistics.Data.Api/appsettings.Development.json
src/GovUk.Education.ExploreEducationStatistics.Data.Model.Tests/FilterItemRepositoryTests.cs
src/GovUk.Education.ExploreEducationStatistics.Data.Model/Repository/FilterItemRepository.cs
src/GovUk.Education.ExploreEducationStatistics.Data.Model/Repository/Interfaces/IFilterItemRepository.cs
src/GovUk.Education.ExploreEducationStatistics.Data.Services.Tests/TableBuilderServicePermissionTests.cs
src/GovUk.Education.ExploreEducationStatistics.Data.Services.Tests/TableBuilderServiceTests.cs
src/GovUk.Education.ExploreEducationStatistics.Data.Services.Tests/Utils/TableBuilderUtilsTests.cs
src/GovUk.Education.ExploreEducationStatistics.Data.Services/Interfaces/ITableBuilderService.cs
src/GovUk.Education.ExploreEducationStatistics.Data.Services/ObservationPredicateBuilder.cs
src/GovUk.Education.ExploreEducationStatistics.Data.Services/TableBuilderService.cs
src/GovUk.Education.ExploreEducationStatistics.Data.Services/Utils/TableBuilderUtils.cs
src/GovUk.Education.ExploreEducationStatistics.Data.Services/ValidationErrorMessages.cs
src/explore-education-statistics-common/src/modules/table-tool/components/FiltersForm.tsx
tests/robot-tests/tests/general_public/table_tool_exclusions_by_geographic_level.robot

This PR returns a validation error if a table builder query exceeds the maximum number of allowed table cells.
This applies to both the admin site for analysts building data blocks and the public site for users using the table builder.
It calculates the maximum number of table cells that could be rendered for the result of a table query, based on
the indicator, location, time period, and any other filter parameters of the query.
Calculating based on attributes of the query criteria is preferential to counting the actual result
to avoid wasted overhead of executing a query that won't be rendered due to exceeding the cell count limit.
This works by making an assumption that data is provided for _all_ combinations of location, time
period and any other filter values to calculate the maximum …

EES-152 Return validation error if table builder query can exceed maximum allowable table size

---

infrastructure/parameters/dev.parameters.json
infrastructure/parameters/prod.parameters.json
tests/robot-tests/tests/general_public/table_tool_exclusions_by_geographic_level.robot

This PR overrides `tableBuilderMaxTableCellsAllowed` configuration parameter with an over generous value in the Prod environment so that no existing data blocks fail to load because their table queries exceed the maximum allowed table size when the changes for EES-152 are first deployed.
Default in all environments unless overridden: 25,000.
Override in Prod: 1,000,000.
After the deploy is complete we can run the report `GET /api/data-blocks/query-size-report` which contains the size of the existing data blocks and use this to establish a more suitable value for the Prod environment.
Other changes
- Remove the same override for the Dev environment which was setting the same value as the default.
- Remove some warninge in UI Test 'Table Tool Exclusions By Geographic Level' caused by …

EES-152 Override tableBuilderMaxTableCellsAllowed with an over generous value in Prod environment

---

src/explore-education-statistics-admin/src/pages/release/datablocks/components/DataBlockSourceWizard.tsx
src/explore-education-statistics-common/src/components/ErrorSummary.tsx
src/explore-education-statistics-common/src/modules/table-tool/components/FiltersForm.tsx
src/explore-education-statistics-common/src/modules/table-tool/components/TableSizeError.tsx
src/explore-education-statistics-common/src/modules/table-tool/components/TableToolWizard.tsx
src/explore-education-statistics-common/src/modules/table-tool/components/__tests__/FiltersForm.test.tsx
src/explore-education-statistics-common/src/validation/serverValidations.ts
src/explore-education-statistics-frontend/src/modules/table-tool/TableToolPage.tsx
tests/robot-tests/tests/general_public/table_tool_exclusions_by_geographic_level.robot

Adds custom error handling for the table size error to:
- show a button to download the subject file in the error message (in the admin this button is disabled / not shown as appropriate)
- log a GA event
**Public:**
**Admin - table tool preview and pre-release:**
**Admin - data blocks**

EES-2853 & EES-2854 table size custom error and ga event

---

src/explore-education-statistics-admin/src/pages/publication/PublicationManageTeamAccessPage.tsx
src/explore-education-statistics-admin/src/pages/publication/components/PublicationManageTeamAccessTab.tsx
src/explore-education-statistics-admin/src/pages/publication/components/ReleaseContributorPermissions.module.scss
src/explore-education-statistics-admin/src/pages/publication/components/ReleaseContributorPermissions.tsx
src/explore-education-statistics-admin/src/pages/publication/components/__tests__/ReleaseContributorPermissions.test.tsx
src/explore-education-statistics-admin/src/services/releasePermissionService.ts
src/explore-education-statistics-common/src/components/WarningMessage.tsx

Tidies up the front end for the manage team access tab.
Adds buttons for granting access to all users and removing users, the click event for these will need to be updated.

EES-2866 manage team access FE tidying

---

src/explore-education-statistics-admin/config/webpackDevServer.config.js
src/explore-education-statistics-frontend/next.config.js
src/explore-education-statistics-frontend/package.json

This PR:
- Fixes the public frontend server from crashing at startup in our non-local environments. This is due to `next-transpile-modules` searching for modules that are stripped out by our build and are not in the deployed artifacts.
- Fixes admin's Webpack dev server from still displaying the default error overlay.
- Enables logging of compile warnings (lints, etc) to the browser console for the admin development server.

EES-2128 Stop next-transpile-modules throwing on starting server in prod mode

---

src/GovUk.Education.ExploreEducationStatistics.Common.Tests/Model/Data/Query/LocationQueryTest.cs
src/GovUk.Education.ExploreEducationStatistics.Common/Model/Data/Query/LocationQuery.cs
src/GovUk.Education.ExploreEducationStatistics.Data.Services/ObservationPredicateBuilder.cs
src/explore-education-statistics-admin/src/pages/release/content/components/KeyStatSelectForm.tsx

This PR allows all of the LocationQuery attribute arrays to be optional again, reverting a change made by https://github.com/dfe-analytical-services/explore-education-statistics/pull/2960.
The previous change initialised them as new collections which was intended to make summing the count of all attributes easier by avoiding the possibility of `null` values. However this problem was easily solved by using `.Sum(collection => collection?.Count ?? 0)` which expects to encounter null values.
This PR fixes a problem where a DataBlock with a LocationQuery cannot be added as a Key Statistic since they now always fail a FE check which makes sure that candidate Key Statistic data blocks only have a single location attribute.
```
const locationLevels = Object.values(locations);
const …
```

EES-2894 🐛 Allow LocationQuery fields to be optional

---

src/GovUk.Education.ExploreEducationStatistics.Data.Processor/GovUk.Education.ExploreEducationStatistics.Data.Processor.csproj
src/GovUk.Education.ExploreEducationStatistics.Notifier/GovUk.Education.ExploreEducationStatistics.Notifier.csproj
src/GovUk.Education.ExploreEducationStatistics.Publisher/GovUk.Education.ExploreEducationStatistics.Publisher.csproj

This PR fixes a problem starting any of the Azure Function applications if you have upgraded Azure Core Tools from v3 to v4.
As soon as the Azure Functions Host is v4 it enforces a minimum version of supported extensions including `Microsoft.Azure.WebJobs.Extensions.Storage` at version 4.0.4 or later.
See https://aka.ms/func-min-extension-versions for more information.
Without this, starting any of the function projects will fail startup with the error
```
ExtensionStartupType AzureStorageWebJobsStartup from assembly 'Microsoft.Azure.WebJobs.Extensions.Storage, Version=4.0.2.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' does not meet the required minimum versi
on of 4.0.4.0. Update your NuGet package reference for Microsoft.Azure.WebJobs.Extensions.Storage to 4.0.4 or later.
```

Upgrade Function Storage Extensions from 4.0.2 to 4.0.5. 

---

src/explore-education-statistics-frontend/next.config.js
tests/robot-tests/.env.example
tests/robot-tests/tests/libs/common.robot
tests/robot-tests/tests/libs/utilities.py

This changes how the UI tests perform basic authentication against the public frontend. Previously, we were putting these into the `PUBLIC_URL` variable, but unfortunately this seems to now be incompatible with Next.js now that we've upgrade to v11.
To get around this, we now add the basic auth credentials into the request headers using the Chrome DevTools prototocol. This necessitates the use of two new environment variables: `PUBLIC_AUTH_USER` and `PUBLIC_AUTH_PASSWORD`.

EES-2893 Fix UI tests failing due to basic auth credentials in URL

---

tests/robot-tests/tests/admin/bau/create_data_block_with_chart.robot
tests/robot-tests/tests/admin/bau/manage_users_page.robot
tests/robot-tests/tests/admin/bau/prerelease.robot
tests/robot-tests/tests/admin_and_public/bau/data_catalogue.robot
tests/robot-tests/tests/admin_and_public/bau/prerelease_visibility.robot
tests/robot-tests/tests/admin_and_public/bau/publish_methodology.robot
tests/robot-tests/tests/admin_and_public/bau/publish_release_and_amend.robot
tests/robot-tests/tests/admin_and_public/bau/publish_release_and_amend_2.robot
tests/robot-tests/tests/general_public/fast_track.robot
tests/robot-tests/tests/general_public/glossary_page.robot
tests/robot-tests/tests/general_public/miscellaneous.robot
tests/robot-tests/tests/general_public/notifications_absence.robot
tests/robot-tests/tests/general_public/permalink_prod_1.robot
tests/robot-tests/tests/general_public/permalink_prod_2.robot
tests/robot-tests/tests/general_public/permalink_prod_3.robot
tests/robot-tests/tests/general_public/release_page_absence.robot
tests/robot-tests/tests/general_public/statistics_page.robot
tests/robot-tests/tests/libs/admin-common.robot
tests/robot-tests/tests/libs/common.robot
tests/robot-tests/tests/libs/no_javascript.py
tests/robot-tests/tests/libs/public-common.robot
tests/robot-tests/tests/libs/utilities.py

Apart from a couple of small fixes, this PR makes a larger change to make sure basic auth headers aree enabled / disabled for public / admin respectively, as if they're set when you try to visit the admin frontend, you get a blank screen.
To solve this issue, we've created keywords `user navigates to public frontend` and `user navigates to admin frontend` and tried to coerce switches from public to admin or vice versa through those keywords. We've also made `user goes to url` throw an error so it's clear that the new keywords should be used in future.

EES-2900 Fix UI tests

---

src/explore-education-statistics-common/src/modules/table-tool/components/MultiHeaderTable.tsx
src/explore-education-statistics-common/src/modules/table-tool/components/__tests__/MultiHeaderTable.test.tsx
src/explore-education-statistics-common/src/modules/table-tool/components/__tests__/__snapshots__/MultiHeaderTable.test.tsx.snap
src/explore-education-statistics-common/src/modules/table-tool/components/utils/Header.ts
src/explore-education-statistics-common/src/modules/table-tool/components/utils/__tests__/Header.test.ts

This PR fixes table cell misalignment that was being caused by row/col headers not taking up the correct cross span. This was caused by a bug meaning that headers only had a max cross span of 2. We have now fixed this so that headers take up the correct cross spans and fill the table cells correctly.
Ironically, due to recent changes limiting the table tool's maximum number of filters, it's not really possible to generate the table that demonstrates the issue in the ticket anymore.
- Refactored most of `MultiHeaderTable` to construct it's expanded headers in a more imperative way. This is hopefully a little simpler to understand as there's less going on. It also allows us to take advantage of breadth/depth first search algorithms to try improve performance.

EES-2844 Fix table headers alignments for row/col headers with large cross spans

---

src/explore-education-statistics-admin/src/pages/release/content/components/AddSecondaryStats.tsx
src/explore-education-statistics-admin/src/pages/release/content/components/KeyStatSelectForm.tsx
src/explore-education-statistics-admin/src/pages/release/content/components/KeyStatistics.tsx
tests/robot-tests/run_tests.py
tests/robot-tests/tests/admin/analyst/role_ui_permissions/release_and_publication_role_end_to_end_permissions.robot
tests/robot-tests/tests/admin/bau/create_data_block_with_chart.robot
tests/robot-tests/tests/admin/bau/delete_subject.robot
tests/robot-tests/tests/admin/bau/prerelease.robot
tests/robot-tests/tests/admin/bau/release_content.robot
tests/robot-tests/tests/admin_and_public/bau/data_catalogue.robot
tests/robot-tests/tests/admin_and_public/bau/prerelease_visibility.robot
tests/robot-tests/tests/admin_and_public/bau/publish_data.robot
tests/robot-tests/tests/admin_and_public/bau/publish_release_and_amend.robot
tests/robot-tests/tests/admin_and_public/bau/publish_release_and_amend_2.robot
tests/robot-tests/tests/libs/admin-common.robot
tests/robot-tests/tests/libs/admin/manage-content-common.robot
tests/robot-tests/tests/libs/bootstrap_data/bootstrap_common.robot
tests/robot-tests/tests/libs/common.robot

This PR:
- adds UI tests around the management of Key Stats tiles and the Secondary stats section when editing Release Content.
UPDATE:
- Added medium waits into various points of the new test code

Ees 2898 key and secondary stats UI tests

---

src/GovUk.Education.ExploreEducationStatistics.Admin/appsettings.Development.json
src/GovUk.Education.ExploreEducationStatistics.Admin/appsettings.json
src/GovUk.Education.ExploreEducationStatistics.Data.Api/appsettings.Development.json
src/GovUk.Education.ExploreEducationStatistics.Data.Api/appsettings.json

This sets a sensible default timeout of 5 minutes for all environments (not just for local development).

EES-2831 Move data API's table tool timeout into appsettings.json

---

.gitignore
README.md
tests/robot-tests/run_tests.py
tests/robot-tests/scripts/pipeline-run-rf-tests.sh
tests/robot-tests/tests/libs/admin-utilities.py
tests/robot-tests/tests/libs/admin_api.py
tests/robot-tests/tests/libs/file_operations.py
tests/robot-tests/tests/libs/no_javascript.py
tests/robot-tests/tests/libs/public-utilities.py
tests/robot-tests/tests/libs/slack.py
tests/robot-tests/tests/libs/utilities.py

This PR: 
- enables test reports to be sent via slack to the #build channel 
- formats various python files to PEP8 standards

EES-2896 - setup slack notifications for UI tests

---

Pipfile
Pipfile.lock

This PR adds back in the azure-storage-blob dependency necessary for `create-emulator-release-files.py` which looks like it was removed by accident in  4b4bd54340d9aac49756a7d9ae03c3886892a3c8.
Without the dependency this error can be seen after `pipenv --rm` and `pipenv install`

Add azure-storage-blob dependency back in for the create-emulator-release-files script

---

src/GovUk.Education.ExploreEducationStatistics.Data.Processor/Functions/Processor.cs
src/explore-education-statistics-admin/src/pages/release/data/components/ImporterStatus.tsx

This work improves the import messaging if a subject import fails.
Firstly, we no longer add exception messages as errors, as they aren't
useful to users - for debugging these can still be found in AppInsights.
Secondly, we displays a generic message for all failed imports
suggesting analysts try running their data files through the data
screener.

EES-2841 Improve importer failure messaging

---

src/explore-education-statistics-admin/src/components/editable/EditableAccordionSection.tsx
src/explore-education-statistics-admin/src/pages/release/content/components/ReleaseBlock.tsx
src/explore-education-statistics-admin/src/pages/release/content/components/ReleaseContentAccordionSection.tsx
src/explore-education-statistics-admin/src/pages/release/content/components/ReleaseEditableBlock.tsx
src/explore-education-statistics-common/src/components/Gate.tsx
src/explore-education-statistics-common/src/components/__tests__/Gate.test.tsx
src/explore-education-statistics-common/src/modules/find-statistics/components/DataBlockTabs.tsx
src/explore-education-statistics-frontend/src/modules/find-statistics/PublicationReleasePage.tsx
src/explore-education-statistics-frontend/src/modules/find-statistics/components/PublicationSectionBlocks.tsx
tests/robot-tests/tests/admin/bau/create_data_block_with_chart.robot

This PR adds further lazy-loading of the data blocks so that they will not load until their relevant section in the release content has been opened. 
Previously, most (if not all) of the data block requests would be triggered as soon as the user scrolled over the release's main content accordion. This could lead to large spikes in traffic if none of the data blocks were cached for that release.
To allow us to do this enhanced lazy loading, we now use wrapping `Gate` components that prevent their child data block from loading until the accordion section has been opened at least once.
- Refactors `Gate` to use a `useEffect` instead of `useAsyncCallback`. We needed more fine-grained control of how the states toggle, particularly as we have introduced a new `passOnce` prop that controls if …

EES-2922 Lazy load data blocks upon opening of their content section

---

infrastructure/parameters/dev.parameters.json
infrastructure/templates/template.json
src/GovUk.Education.ExploreEducationStatistics.Data.Api/appsettings.json

This PR:
-lowers the default Table Tool query timeout to 210 seconds across the board, which is 20 seconds below the Azure App Service default timeout.
- allows us to deliver a useful error response to the user rather than the silent Azure timeout response (which is silent due to CORS errors preventing its response data to be used in the browser).
I've removed the parameter from `dev.parameters.json` to allow it to pick up the default.
See this post for similar details: https://techcommunity.microsoft.com/t5/apps-on-azure/app-service-timeout-in-230-sec/m-p/1526934

EES-2831 - decreased default Table Tool query timeout to below Azure app service timeout threshold (of 230 seconds)

---

src/GovUk.Education.ExploreEducationStatistics.Admin/appsettings.json
src/GovUk.Education.ExploreEducationStatistics.Data.Api/Services/PermalinkService.cs
src/GovUk.Education.ExploreEducationStatistics.Data.Api/appsettings.json

This PR corrects a few things which were merged with https://github.com/dfe-analytical-services/explore-education-statistics/pull/3025.
* Corrects the `TableResultLocationHierarchiesEnabled` property in the `appsettings.json` files to match the expected property name in `LocationOptions`. The property was disabled by default and remains disabled by default so this wasn't a serious problem but the property name was wrong so enabling the feature was broken.
* Corrects the type of `ResultSubjectMetaViewModel` in the `PermalinkContractResolver` when determining if the `Location` and `LocationsHierarchical` should be serialized. The type was previously `Permalink` so this wasn't working as their declaring type was wrong meaning both fields were being serialized. While this doesn't cause an …

🐛 Bugfix/EES-2917 Fixes around table result subject metadata after PR #3025

---

infrastructure/parameters/test.parameters.json

This PR: 
- increases tableBuilderMaxTableCells allowed as discussed in standup for the test environment

EES-2958 - increase tableBuilderMaxTableCellsAllowed for test env

---

tests/robot-tests/run_tests.py
tests/robot-tests/tests/libs/create_emulator_release_files.py

This PR: 
- handles `ResourceExist ` exceptions related to blob files already existing in local storage emulator environments 
- Moves `create_emulator_release_files` into the tests directory (in order to call various methods in `run_tests.py`)
- Runs `create_emulator_release_files` as part of `run_tests.py`

EES-2941 - handle blob exists exceptions

---

src/explore-education-statistics-admin/src/pages/release/data/components/ImporterStatus.tsx
src/explore-education-statistics-admin/src/pages/release/data/components/__tests__/ReleaseDataUploadsSection.test.tsx
src/explore-education-statistics-admin/src/pages/release/data/components/__tests__/ReleaseFileUploadsSection.test.tsx
src/explore-education-statistics-admin/src/pages/release/datablocks/__tests__/ReleaseDataBlockEditPage.test.tsx
src/explore-education-statistics-admin/src/pages/release/datablocks/__tests__/ReleaseDataBlocksCreatePage.test.tsx

This PR refactors tests for various admin page tests to avoid `waitFor` calls failing intermittently.
As previously mentioned on Slack, we should avoid using `getByRole` within a `waitFor` as it can cause test processes to choke and fail (due to `getByRole` being slow) e.g:
```ts
await waitFor(() => {
// Bad ❌
expect(screen.getByRole('button', { name: 'Something' })).toBeInTheDocument();
});
```
Instead, we should use faster `getByText` or `getByTestId` selectors:
```ts
await waitFor(() => {
// Good ✅
expect(screen.getByText('Something')).toBeInTheDocument();
});
// Fine to use `getByRole` outside of the `waitFor`
expect(screen.getByRole('button', { name: 'Something' })).toBeInTheDocument();
```

Refactor admin page tests to avoid blocking `waitFor` failures

---

src/GovUk.Education.ExploreEducationStatistics.Common/Model/TimeIdentifier.cs

This PR orders Months after Weeks to force December to be treated as greater (more recent) than any other Week when ordering the Releases in the laptops-and-tablets-data release.
There is currently a problem where categories of time identifiers have been mixed - Weeks and Months, and Week 28 is treated as more recent than December.
In general this PR will not fix ordering of Time Identifiers when different categories are mixed such as ordering weeks and months together correctly.
In fact, this PR only happens to order December correctly, assuming that we can always treat it greater than any week.
A solution is needed to overhaul how Release and Observation time periods are defined to allow more flexible ordering.
It will not work if any other monthly releases are created for 2021 into …

EES-2972 order Months after Weeks

---

src/explore-education-statistics-admin/src/pages/release/content/components/ReleaseContent.tsx
src/explore-education-statistics-common/src/components/SectionBreak.tsx
src/explore-education-statistics-common/src/modules/release/components/ReleaseDataAndFilesAccordion.module.scss
src/explore-education-statistics-common/src/modules/release/components/ReleaseDataAndFilesAccordion.tsx
src/explore-education-statistics-common/src/modules/release/components/__tests__/ReleaseDataAndFilesAccordion.test.tsx
src/explore-education-statistics-frontend/src/components/ButtonLink.tsx
src/explore-education-statistics-frontend/src/modules/find-statistics/PublicationReleasePage.tsx
tests/robot-tests/tests/admin/bau/prerelease.robot
tests/robot-tests/tests/admin/bau/upload_files.robot
tests/robot-tests/tests/admin_and_public/bau/publish_data.robot
tests/robot-tests/tests/admin_and_public/bau/publish_release_and_amend.robot

Updates to the release page on the public site and in the admin.
- Renames and adds 'Supporting information' section to the sidebar 
- Tidies up the 'Explore data and files' accordion
- In the admin tries to keep the look of it consistent with the public site by using disabled buttons when they aren't available until the release is published.
- Removes an unnecessary extra link to the pre-release access list from the admin version
- Does not add the file type and size to the download all data button, I think this will need to be a separate ticket.
Sidebar:
'Explore data and files' accordion - public site:
'Explore data and files' accordion - admin site:

EES-2964 tidying release page

---

infrastructure/templates/template.json

Currently, an infrastructure deploy will fail due to this data factory alert. We're commenting out again so it won't prevent a deploy to preprod/prod.

EES-2976 Remove broken DF alert in ARM template

---

tests/robot-tests/run_tests.py

This PR: 
- Fixes UI test startup issues related to `run_tests.py` referencing a CLI flag that no longer exists 
- Adds additional asserts to make sure the correct `.env` variables are set

EES-3006 - fix UI test startup issues

---

tests/robot-tests/run_tests.py

This PR: 
- Fixes a startup issue occurring in Azure CI. This happened because we were trying to assert that certain environment variables were present when the CI script was passing these arguments via CLI flags

EES-3006-3 - fix UI test start-up issue in CI

---

src/GovUk.Education.ExploreEducationStatistics.Admin.Tests/Controllers/Api/Bau/BauCacheControllerTests.cs
src/GovUk.Education.ExploreEducationStatistics.Admin.Tests/Controllers/Api/Methodologies/MethodologyControllerTests.cs
src/GovUk.Education.ExploreEducationStatistics.Admin/Controllers/Api/Bau/BauCacheController.cs
src/GovUk.Education.ExploreEducationStatistics.Admin/Controllers/Api/Bau/BauReleaseController.cs
src/GovUk.Education.ExploreEducationStatistics.Admin/Controllers/Api/DataBlockQuerySizeController.cs
src/GovUk.Education.ExploreEducationStatistics.Admin/GovUk.Education.ExploreEducationStatistics.Admin.csproj
src/GovUk.Education.ExploreEducationStatistics.Admin/Models/Role.cs
src/GovUk.Education.ExploreEducationStatistics.Admin/Security/StartupSecurityConfiguration.cs
src/GovUk.Education.ExploreEducationStatistics.Admin/Startup.cs
src/GovUk.Education.ExploreEducationStatistics.Common.Tests/Extensions/ActionResultTestExtensions.cs
src/GovUk.Education.ExploreEducationStatistics.Common.Tests/Services/BlobStorageServiceTests.cs
src/GovUk.Education.ExploreEducationStatistics.Common.Tests/Validators/ContainsOnlyAttributeTests.cs
src/GovUk.Education.ExploreEducationStatistics.Common/Cache/AllMethodologiesCacheKey.cs
src/GovUk.Education.ExploreEducationStatistics.Common/Services/BlobStorageService.cs
src/GovUk.Education.ExploreEducationStatistics.Common/Services/CollectionUtils.cs
src/GovUk.Education.ExploreEducationStatistics.Common/Services/FileStoragePathUtils.cs
src/GovUk.Education.ExploreEducationStatistics.Common/Services/Interfaces/IBlobStorageService.cs
src/GovUk.Education.ExploreEducationStatistics.Common/Validators/ContainsOnlyAttribute.cs
src/GovUk.Education.ExploreEducationStatistics.Content.Services/Cache/PublicationTreeCacheKey.cs
src/GovUk.Education.ExploreEducationStatistics.Publisher/Services/ContentService.cs

This PR adds the following new endpoints:
- `DELETE /api/bau/private-cache` - clears the entire private cache used by admin
- `DELETE /api/bau/public-cache/trees` - clears specific tree JSON files from the public cache
- `DELETE /api/bau/public-cache/releases` - clears specific paths (e.g. `data-blocks`, `subject-meta`, etc) related to releases from the public cache
It should be noted that all of these endpoints only clear blobs where it is safe to do so i.e. where the cached object can be regenerated easily by a user visiting the relevant part of the app. This means that we don't delete blobs like the release content JSON as these are only generated by the publisher and cannot be regenerated without regenerating all of the content (this is an expensive operation).
Ideally, we would …

EES-3012 Add BAU endpoints to clear blob caches

---

src/GovUk.Education.ExploreEducationStatistics.Data.Model/ILocationAttribute.cs
src/GovUk.Education.ExploreEducationStatistics.Data.Model/LocalAuthority.cs
src/GovUk.Education.ExploreEducationStatistics.Data.Model/Observation.cs
src/GovUk.Education.ExploreEducationStatistics.Data.Model/Repository/Interfaces/ILocationRepository.cs
src/GovUk.Education.ExploreEducationStatistics.Data.Model/Repository/LocationRepository.cs
src/GovUk.Education.ExploreEducationStatistics.Data.Services.Tests/ResultSubjectMetaServiceTests.cs
src/GovUk.Education.ExploreEducationStatistics.Data.Services/ObservationPredicateBuilder.cs
src/GovUk.Education.ExploreEducationStatistics.Data.Services/ObservationService.cs
src/GovUk.Education.ExploreEducationStatistics.Data.Services/ResultSubjectMetaService.cs
src/GovUk.Education.ExploreEducationStatistics.Data.Services/SubjectMetaService.cs

This PR resolves the outstanding PR comments of EES-2778 in https://github.com/dfe-analytical-services/explore-education-statistics/pull/3074.
In addition to adding comments it alters the way we retrieve Locations in `LocationRepository`.
Rather than selecting all location id's and then looking up locations by id which translates to two queries like
```
SELECT DISTINCT LocationId
FROM Observation
WHERE SubjectId = '<Subject Id>'
```
and
```
SELECT Id,
Country_Code,
Country_Name,
EnglishDevolvedArea_Code,
EnglishDevolvedArea_Name,
GeographicLevel,
Institution_Code,
Institution_Name,
LocalAuthorityDistrict_Code,
LocalAuthorityDistrict_Name,
LocalAuthority_Code,
LocalAuthority_Name,
LocalAuthority_OldCode,
LocalEnterprisePartnership_Code,
LocalEnterprisePartnership_Name, …
```

EES-3011 Resolve PR comments of EES-2778

---

src/GovUk.Education.ExploreEducationStatistics.Admin/Startup.cs

This PR fixes the incorrect `BlobStorageService` dependencies being wired into `BauCacheController`. By default, .NET does not allow you to wire up controllers manually, and we have to explicitly allow this by using the `AddControllersAsServices` option.

EES-3012 Fix incorrect wiring up of `BauCacheController`

---

src/GovUk.Education.ExploreEducationStatistics.Admin.Tests/Controllers/Api/Statistics/TableBuilderControllerTests.cs
src/GovUk.Education.ExploreEducationStatistics.Admin/appsettings.json
src/GovUk.Education.ExploreEducationStatistics.Data.Api.Tests/Controllers/FastTrackControllerTests.cs
src/GovUk.Education.ExploreEducationStatistics.Data.Api.Tests/Converters/ResultSubjectMetaViewModelJsonConverterTests.cs
src/GovUk.Education.ExploreEducationStatistics.Data.Api.Tests/Services/PermalinkServiceTests.cs
src/GovUk.Education.ExploreEducationStatistics.Data.Api/Services/PermalinkService.cs
src/GovUk.Education.ExploreEducationStatistics.Data.Api/appsettings.json
src/GovUk.Education.ExploreEducationStatistics.Data.Services.Tests/ResultSubjectMetaServiceTests.cs
src/GovUk.Education.ExploreEducationStatistics.Data.Services/Converters/ResultSubjectMetaViewModelJsonConverter.cs
src/GovUk.Education.ExploreEducationStatistics.Data.Services/LocationsOptions.cs
src/GovUk.Education.ExploreEducationStatistics.Data.Services/ResultSubjectMetaService.cs
src/GovUk.Education.ExploreEducationStatistics.Data.Services/ViewModels/Meta/ResultSubjectMetaViewModel.cs
src/explore-education-statistics-admin/src/pages/release/data/components/__tests__/DataFileReplacementPlan.test.tsx

This PR removes the table result location hierarchies feature toggle and makes it a permanent feature.
This toggle was originally added so that the BE work of the location hierarchies feature could be completed before the UI work began, keeping non hierarchical locations as the default response format in table results.
After EES-2777 included by https://github.com/dfe-analytical-services/explore-education-statistics/pull/3082 this work is now completed.
We also remove the legacy `Locations` field from `ResultSubjectMetaViewModel`.
`ResultSubjectMetaViewModelJsonConverter` is responsible for converting any older Permalinks which have a flat `Locations` field in their JSON serialization into `LocationsHierarchical`. 
Until old Permalinks are migrated, the translation provided by this …

EES-2902 Make location hierarchies a permanent feature of table results

---

infrastructure/parameters/dev.parameters.json
infrastructure/templates/datafactory/components/template.json
infrastructure/templates/datafactory/template.json
infrastructure/templates/template.json

This PR sets Data Factory config to make pipelines run concurrently. The default is "1" (i.e. no concurrency), but I've set Dev to "10". This value might want tweaking.
This has been changed due to a problem we had with the UI test runs against Dev. So many releases were trying to get published at once that test suites would fail. Hopefully, by having pipeline runs run concurrently, this will solve the issue of "queued" pipeline runs.

EES-2996 Dev ADF pipelines now run concurrency

---

src/GovUk.Education.ExploreEducationStatistics.Admin/Startup.cs
src/GovUk.Education.ExploreEducationStatistics.Common.Tests/Config/SensitiveDataTelemetryProcessorTests.cs
src/GovUk.Education.ExploreEducationStatistics.Common/Config/SensitiveDataTelemetryProcessor.cs
src/GovUk.Education.ExploreEducationStatistics.Common/GovUk.Education.ExploreEducationStatistics.Common.csproj
src/GovUk.Education.ExploreEducationStatistics.Content.Api/Startup.cs
src/GovUk.Education.ExploreEducationStatistics.Data.Api/Startup.cs
src/explore-education-statistics-common/src/services/__tests__/applicationInsightsService.test.ts
src/explore-education-statistics-common/src/services/applicationInsightsService.ts

This PR adds filtering to strip out sensitive information from telemetry being sent to Application Insights in both the backend and frontend.
The main intention for this is to be coupled with [EES-2823](https://dfedigital.atlassian.net/browse/EES-2823) where the websocket handshake relies on passing the user's access token via an `access_token` query parameter. Unfortunately, this is problematic as these query strings would get logged out to Application Insights, making it a security vulnerability.
We have implemented this as a fairly simplistic algorithm that detects if a query string parameter contains one of several redactable words (e.g. the word `email`, `code` or `token`). We try to account for potential false positives (e.g. `code` is in the word `encode`) by splitting up the key …

EES-3117 Add sensitive data filtering for Application Insights

---

tests/robot-tests/tests/admin/analyst/invite_contributor_as_publication_owner.robot

This PR : 
fixes a flaky assertion in invite contributor as publication owner. This seemed to occur quite often in CI and when running UI tests against dev.
Original failure:
``` 
Page should have contained text 'ees-analyst-20220126-120528@education.gov.uk' but did not.
```

EES-3132 - fix flaky UI test assertion

---

src/explore-education-statistics-common/src/modules/find-statistics/components/DataBlockTabs.tsx
src/explore-education-statistics-common/src/modules/table-tool/components/FixedMultiHeaderDataTable.tsx
src/explore-education-statistics-common/src/modules/table-tool/components/TimePeriodDataTable.tsx
src/explore-education-statistics-common/src/modules/table-tool/components/__tests__/FixedMultiHeaderDataTable.test.tsx
src/explore-education-statistics-common/src/modules/table-tool/components/__tests__/TimePeriodDataTable.test.tsx
src/explore-education-statistics-common/src/modules/table-tool/components/__tests__/__snapshots__/FixedMultiHeaderDataTable.test.tsx.snap

This PR: 
- Changes `figcaption` elements that are in tables to have dynamic IDs instead of `dataTableCaption`. This was raised as part of the DAC accessibility assessment

EES-3014 - change figcaptions on tables to have dynamic IDs

---

tests/robot-tests/tests/admin/bau/create_publication_and_release.robot
tests/robot-tests/tests/admin/bau/delete_subject.robot
tests/robot-tests/tests/admin/bau/prerelease.robot
tests/robot-tests/tests/admin/bau/release_status.robot
tests/robot-tests/tests/admin/bau/upload_files.robot
tests/robot-tests/tests/admin_and_public/bau/prerelease_visibility.robot
tests/robot-tests/tests/admin_and_public/bau/publish_content.robot
tests/robot-tests/tests/admin_and_public/bau/publish_data.robot
tests/robot-tests/tests/general_public/table_tool_absence_in_prus.robot
tests/robot-tests/tests/general_public/table_tool_exclusions_by_geographic_level.robot
tests/robot-tests/tests/libs/admin-common.robot

This PR: 
- fixes a few assertions related to modals looking for `h1` elements instead of `h2` elements. This was caused by the recent changes in https://github.com/dfe-analytical-services/explore-education-statistics/pull/3129

EES-3140 - fix UI tests

---

src/explore-education-statistics-common/src/modules/table-tool/components/DownloadTable.tsx
src/explore-education-statistics-frontend/src/modules/permalink/PermalinkPage.tsx

Removes the 'Download table' form on permalinks pages if the table isn't valid. It's using a pretty basic check for what's valid, suggestions for how to make that more robust are welcome.

EES-3141 remove download table options if table not renderable

---

src/explore-education-statistics-admin/src/pages/release/datablocks/__data__/tableToolServiceData.ts
src/explore-education-statistics-common/src/modules/charts/components/MapBlockInternal.tsx
src/explore-education-statistics-common/src/modules/table-tool/components/LocationFiltersForm.tsx
src/explore-education-statistics-common/src/modules/table-tool/components/__tests__/LocationFiltersForm.test.tsx
src/explore-education-statistics-common/src/modules/table-tool/components/__tests__/TableToolWizard.test.tsx
src/explore-education-statistics-common/src/utils/locationLevelsMap.ts

Sets the heading of the location step in the table tool:
- if just one type of location available: `Choose <location type>`
- if more than one type it defaults to `Choose locations`

EES-2784 set location step heading based on options available

---

src/explore-education-statistics-common/src/modules/table-tool/components/DownloadTable.tsx
src/explore-education-statistics-frontend/src/modules/permalink/PermalinkPage.tsx

Changed it so the download table form is hidden based on getting an error from the table rendering. 
Also, couldn't find out what exactly you get in GA for exceptions, or see the 'crashes and exceptions' section where it's meant to be in GA so to be on the safe side have changed it to be an event.

EES-3141 hide download table when get error

---

src/GovUk.Education.ExploreEducationStatistics.Admin/Areas/Identity/Data/UsersAndRolesDbContext.cs
src/GovUk.Education.ExploreEducationStatistics.Common.Tests/GovUk.Education.ExploreEducationStatistics.Common.Tests.csproj
src/GovUk.Education.ExploreEducationStatistics.Common.Tests/Utils/DbContextUtilsTests.cs
src/GovUk.Education.ExploreEducationStatistics.Common/Model/Timestamps.cs
src/GovUk.Education.ExploreEducationStatistics.Common/Utils/DbContextUtils.cs
src/GovUk.Education.ExploreEducationStatistics.Content.Model/Database/ContentDbContext.cs
src/GovUk.Education.ExploreEducationStatistics.Data.Model/Database/StatisticsDbContext.cs

This PR adds timestamp interfaces that allow us to automatically update timestamp fields on entities automatically via events attached to Entity Framework's `ChangeTracker`.
We intend to use this as part the content locking work in [EES-2823](https://dfedigital.atlassian.net/browse/EES-2823), but this has been split out as it has cross-over with [EES-3138](https://dfedigital.atlassian.net/browse/EES-3138) to add consistent timestamp columns to entities.

EES-3139 Add timestamp interfaces for entities

---

src/explore-education-statistics-admin/src/pages/release/datablocks/components/chart/ChartDataSetsConfiguration.module.scss
src/explore-education-statistics-admin/src/pages/release/datablocks/components/chart/ChartDataSetsConfiguration.tsx
src/explore-education-statistics-admin/src/pages/release/datablocks/components/chart/__tests__/ChartDataSetsConfiguration.test.tsx
src/explore-education-statistics-common/src/modules/charts/util/__tests__/createDataSetCategories.test.ts
src/explore-education-statistics-common/src/modules/charts/util/createDataSetCategories.ts

Adds reordering to chart data sets to allow users to control the ordering in the chart. This was originally going to be on the legend tab, which is a bit more user friendly, but doesn't work for reordering data set categories.
**Reorder button:**
**Reordering:**

EES-2556 reorder datasets

---

src/GovUk.Education.ExploreEducationStatistics.Data.Services/LocationPredicateBuilder.cs
src/GovUk.Education.ExploreEducationStatistics.Data.Services/ObservationService.cs
src/GovUk.Education.ExploreEducationStatistics.Data.Services/SubjectMetaService.cs

This PR:
- fixes an existing bug in LocationPredicateBuilder (formerly ObservationPredicateBuilder) whereby School and Provider were not recognised as being able to provide Location Attributes and so did not add any clauses to the overall Location predicate.
- This caused the work in 2999 to fetch too many Locations when Provider or School codes were provided, thus returning table results that were not valid for the ranges of Providers and Schools chosen in queries.
I've also added in throws for any "misuse" of the LocationPredicateBuilder i.e. any scenarios that would not actually add any genuine clauses to the location predicate.

EES-2999 - added fix for provider and school level Location queries

---

useful-scripts/get_data_block_responses/get_data_block_responses.py

This PR makes a few minor improvements to the get_data_block_responses script.
- All console output of the script is now also saved in a "console_output" file.
- Removed "fails" directory - all data block files are saved in the same directory now.

EES-2999 Improve get_data_block_responses script

---

tests/robot-tests/scripts/create_snapshots.py

This PR temporarily reverts the changes made to the `create_snapshots.py` Python script which expect the public Find Statistics page to have already changed to group publications by their type.
This won't be the case until https://github.com/dfe-analytical-services/explore-education-statistics/pull/3148 is pushed to the Prod environment, at which time this commit will need to be reverted. A separate PR is already prepared to do this revert in https://github.com/dfe-analytical-services/explore-education-statistics/pull/3153.

EES-3124 Temporarily revert changes to create_snapshots.py

---

src/explore-education-statistics-admin/src/components/form/FormEditor.module.scss
src/explore-education-statistics-admin/src/hooks/useCKEditorConfig.ts

Adds SVG to the allowed image upload types in CKEditor, plus some css to make sure they always show in the editor.
The list of types is the default plus svg, we might want to review it (I can't imagine anyone uploading a tiff file).

EES-2944 allow svgs in ckeditor

---

tests/robot-tests/scripts/create_snapshots.py

This PR re-applies the create_snapshot.py changes made by EES-3124 that were reverted in https://github.com/dfe-analytical-services/explore-education-statistics/pull/3152
It should not be merged until the changes made by EES-3124 in https://github.com/dfe-analytical-services/explore-education-statistics/pull/3148 are pushed to the Prod environment.

EES-3124 Reapply changes to create_snapshots.py

---

src/explore-education-statistics-frontend/src/modules/table-tool/components/TableToolFinalStep.tsx

On the frontend table tool hide the create permalink and download table options if the table errors and can't be rendered. 
The error is logged to Google Analytics.

EES-3146 hide permalink and download on table tool final step if table cannot render

---

src/explore-education-statistics-common/src/modules/charts/components/MapBlockInternal.tsx
src/explore-education-statistics-common/src/modules/charts/components/__tests__/MapBlock.test.tsx
src/explore-education-statistics-common/src/modules/charts/components/__tests__/MapBlockInternal.test.tsx
src/explore-education-statistics-common/src/modules/charts/components/__tests__/__data__/testMapBlockData.ts

- Groups Local Authorities by region in the Map block location dropdown
- If other location levels are also in the locations then they are grouped by level
- If there are no LAs in the locations then the list is not grouped and remains as it is currently.
- Also changed the 'None selected' option to be added as a placeholder on the FormSelect instead of being added to the options array.

EES-2779 group LAs in map dropdown

---

src/GovUk.Education.ExploreEducationStatistics.Admin.Tests/Areas/Identity/Pages/Account/ExternalLoginTests.cs
src/GovUk.Education.ExploreEducationStatistics.Admin.Tests/GovUk.Education.ExploreEducationStatistics.Admin.Tests.csproj
src/GovUk.Education.ExploreEducationStatistics.Admin.Tests/Security/AuthorizationHandlers/AdoptMethodologyForSpecificPublicationAuthorizationHandlerTests.cs
src/GovUk.Education.ExploreEducationStatistics.Admin.Tests/Security/AuthorizationHandlers/ApproveSpecificMethodologyAuthorizationHandlerTests.cs
src/GovUk.Education.ExploreEducationStatistics.Admin.Tests/Security/AuthorizationHandlers/CreateMethodologyForSpecificPublicationAuthorizationHandlerTests.cs
src/GovUk.Education.ExploreEducationStatistics.Admin.Tests/Security/AuthorizationHandlers/DeleteSpecificMethodologyAuthorizationHandlerTests.cs
src/GovUk.Education.ExploreEducationStatistics.Admin.Tests/Security/AuthorizationHandlers/DropMethodologyLinkAuthorizationHandlerTests.cs
src/GovUk.Education.ExploreEducationStatistics.Admin.Tests/Security/AuthorizationHandlers/MakeAmendmentOfSpecificMethodologyAuthorizationHandlerTests.cs
src/GovUk.Education.ExploreEducationStatistics.Admin.Tests/Security/AuthorizationHandlers/ManageExternalMethodologyForSpecificPublicationAuthorizationHandlerTests.cs
src/GovUk.Education.ExploreEducationStatistics.Admin.Tests/Security/AuthorizationHandlers/MarkSpecificMethodologyAsDraftAuthorizationHandlerTests.cs
src/GovUk.Education.ExploreEducationStatistics.Admin.Tests/Security/AuthorizationHandlers/UpdateSpecificCommentAuthorizationHandlerTests.cs
src/GovUk.Education.ExploreEducationStatistics.Admin.Tests/Security/AuthorizationHandlers/UpdateSpecificMethodologyAuthorizationHandlerTests.cs
src/GovUk.Education.ExploreEducationStatistics.Admin.Tests/Security/AuthorizationHandlers/Utils/AuthorizationHandlersTestUtil.cs
src/GovUk.Education.ExploreEducationStatistics.Admin.Tests/Security/AuthorizationHandlers/Utils/PublicationAuthorizationHandlersTestUtil.cs
src/GovUk.Education.ExploreEducationStatistics.Admin.Tests/Security/AuthorizationHandlers/Utils/ReleaseAuthorizationHandlersTestUtil.cs
src/GovUk.Education.ExploreEducationStatistics.Admin.Tests/Security/AuthorizationHandlers/ViewSpecificMethodologyAuthorizationHandlerTests.cs
src/GovUk.Education.ExploreEducationStatistics.Admin.Tests/Security/AuthorizationHandlers/ViewSpecificPublicationAuthorizationHandlersTests.cs
src/GovUk.Education.ExploreEducationStatistics.Admin.Tests/Security/AuthorizationHandlers/ViewSpecificReleaseAuthorizationHandlersTests.cs
src/GovUk.Education.ExploreEducationStatistics.Admin.Tests/Security/Utils/ClaimsPrincipalUtils.cs
src/GovUk.Education.ExploreEducationStatistics.Admin/Areas/Identity/Pages/Account/ExternalLogin.cshtml.cs
src/GovUk.Education.ExploreEducationStatistics.Admin/Startup.cs
src/GovUk.Education.ExploreEducationStatistics.Common/Model/Either.cs

This PR:
* adds support for us to migrate from one App Registration to another on environments.
* adds Unit Testing around the login process.
The effects of moving App Registration (even when pointing against the same AD instance) means that the ProviderKey for a single user (unique identifier for a user provided form the login process) differ between the old and the new App Registration.
This means we must handle the ability for a single user (identified by email address) to have more than one set of ProviderKey information.  This supports not only having multiple App Registrations, but also multiple external OpenID Connect Identity Providers as well where we trust the Identity Provider and its ability to securely identify a user by their email address.  Thus we could support login from …

Ees 2990 allow change in app registrations for existing users

---

src/GovUk.Education.ExploreEducationStatistics.Admin/Controllers/Api/ReleaseFileController.cs
src/GovUk.Education.ExploreEducationStatistics.Content.Api/Controllers/ReleaseFileController.cs

This PR:
- removes the filename hash suffix from the downloadable zip file after a user makes a choice of individual files to download.
This is done in both admin and public sites.

EES-2713 - removed hash from generated filename

---

src/explore-education-statistics-common/src/modules/table-tool/components/TableToolWizard.tsx
src/explore-education-statistics-common/src/modules/table-tool/components/TimePeriodForm.tsx
src/explore-education-statistics-common/src/modules/table-tool/components/__tests__/TableToolWizard.test.tsx

Fixes two table tool bugs:
1. After changing location, can move past time period step without selecting a valid time period - fixed by checking that the selected time period is still available and and resetting the selection if not.
2. Can create table despite not selecting an indicator - fixed by resetting selections when the subject is changed.
n/a
n/a

EES-1477 prevent bugs when change table tool subject and location

---

tests/robot-tests/scripts/pipeline-run-rf-tests-snapshots.sh
tests/robot-tests/tests/libs/slack.py

This PR:
* Duplicates pipeline script so that we do not send slack notifications when running the snapshot test pipeline
* Minor cleanup of `slack.py`
Continuation of https://github.com/dfe-analytical-services/explore-education-statistics/pull/3164 due to a bad rebase

EES-3163 - duplicate CI test script for snapshot tests

---

src/GovUk.Education.ExploreEducationStatistics.Data.Processor/host.json
src/GovUk.Education.ExploreEducationStatistics.Notifier/host.json
src/GovUk.Education.ExploreEducationStatistics.Publisher/host.json

This PR prevents log spam we were getting when running Azure Functions locally via azure-functions-core-tools. The log spam looked like this:
```
[2022-02-14T16:37:47.611Z] Request [b12a9236-e309-4c20-bb7c-54f06c9c824c] PUT http://data-storage:10000/devstoreaccount1/azure-webjobs-hosts/locks/baptistin-479599971/host?comp=lease
[2022-02-14T16:37:47.613Z] x-ms-lease-action:release
[2022-02-14T16:37:47.615Z] x-ms-lease-id:00000000-0000-0000-0000-0000a7df7835
[2022-02-14T16:37:47.617Z] x-ms-version:2020-08-04
[2022-02-14T16:37:47.618Z] Accept:application/xml
[2022-02-14T16:37:47.620Z] x-ms-client-request-id:b12a9236-e309-4c20-bb7c-54f06c9c824c
[2022-02-14T16:37:47.622Z] x-ms-return-client-request-id:true
[2022-02-14T16:37:47.624Z] User-Agent:azsdk-net-Storage.Blobs/12.9.0,(.NET …
```

EES-3170 Stop log spam when running Azure Functions locally

---

src/explore-education-statistics-admin/src/components/editable/BlockDraggable.module.scss
src/explore-education-statistics-admin/src/components/editable/BlockDraggable.tsx

This PR fixes a display issue with the unicode character for BlockDraggable not displaying correctly:
Our guess is that this started happening when we switched from using `node-sass` to `sass`.

EES-3176 Fix frontend drag handle display issue

---

src/explore-education-statistics-admin/public/index.html
src/explore-education-statistics-admin/src/components/editable/BlockDraggable.module.scss
src/explore-education-statistics-admin/src/components/editable/BlockDraggable.tsx

This PR fixes HTML `charset` not being set on the admin's `index.html`. This was causing the corrupted character encoding issues that we were typically seeing on drag handles using pseudo elements.
This also reverts the previous attempt to fix this issue as it's no longer necessary. We would have had to make this change in multiple places and it's generally just cleaner to the drag handle unicode in CSS instead.

EES-3176 Fix corrupted unicode characters displaying for CSS pseudo elements

---

src/GovUk.Education.ExploreEducationStatistics.Admin.Tests/Controllers/Api/Statistics/TableBuilderControllerTests.cs
src/GovUk.Education.ExploreEducationStatistics.Data.Api.Tests/Controllers/FastTrackControllerTests.cs
src/GovUk.Education.ExploreEducationStatistics.Data.Services.Tests/TableBuilderServiceTests.cs
src/GovUk.Education.ExploreEducationStatistics.Data.Services/ResultBuilder.cs
src/GovUk.Education.ExploreEducationStatistics.Data.Services/ViewModels/ObservationViewModel.cs

This PR adds new `Id` and `LocationId` fields to `ObservationViewModel` so that they are present in all table responses.
Sample of how a Observation result in the table `results` field will now appear:
```
{
"id": "71ff5069-a6ac-4b9c-f530-08d9f78ec0af",
"filters": [],
"geographicLevel": "country",
"locationId": "62424e77-ff57-4a7c-f52a-08d9f78ec0af",
"location": {
"country": {
"code": "E92000001",
"name": "England"
}
},
"measures": {
"b5b12479-90cf-44dd-f525-08d9f78ec0af": "607928"
},
"timePeriod": "2022_CY"
}
```
`LocationId` is being added anyway by https://github.com/dfe-analytical-services/explore-education-statistics/pull/3179 (EES-2955) but having it in the response early along with `Id` means that we can more reliably test table responses for equality.
The 'full' `Location` field …

EES-3203 Add Id and Location Id to ObservationViewModel

---

src/explore-education-statistics-admin/src/pages/release/datablocks/components/chart/ChartLegendConfiguration.tsx
src/explore-education-statistics-admin/src/pages/release/datablocks/components/chart/__tests__/ChartLegendConfiguration.test.tsx

Changes the default symbol option on line charts to none.

EES-2842 default line chart symbol to none

---

src/explore-education-statistics-admin/src/pages/release/data/ReleaseDataPage.tsx
src/explore-education-statistics-admin/src/pages/release/data/components/ReleaseDataReorderSection.module.scss
src/explore-education-statistics-admin/src/pages/release/data/components/ReleaseDataReorderSection.tsx
src/explore-education-statistics-admin/src/pages/release/data/components/ReorderFiltersList.tsx
src/explore-education-statistics-admin/src/pages/release/data/components/ReorderIndicatorsList.tsx
src/explore-education-statistics-admin/src/pages/release/data/components/ReorderList.module.scss
src/explore-education-statistics-admin/src/pages/release/data/components/ReorderList.tsx
src/explore-education-statistics-admin/src/pages/release/data/components/__tests__/ReorderFiltersList.test.tsx
src/explore-education-statistics-admin/src/pages/release/data/components/__tests__/ReorderIndicatorsList.test.tsx
src/explore-education-statistics-common/src/services/tableBuilderService.ts

Adds a tab in the 'Data and Files' section of a release for reordering filters and indicators.
- The tab is commented out, uncomment it in  [ReleaseDataPage.tsx](https://github.com/dfe-analytical-services/explore-education-statistics/compare/EES-2786?expand=1#diff-9b79898fb4082e2a782056d92cd17b0c5dfddede02ad88ec96f019a08cbd225a) to see it in action
- Uses test data for now as the code assumes an id and order will be added to filters and indicators on subjectMeta. Some types will need to be updated for this.
- Transforms the filters and indictors into arrays instead of keyed objects and strips out unnecessary fields before submitting the request to update them. The shape of this data is based on discussions with @benoutram, see the tests for what it will look like.
- The save request will …

EES-2786 EES-2808 reorder filters and indicators frontend

---

useful-scripts/get_data_block_responses/get_data_block_responses.py

When running the `get_data_block_responses` script I noticed that there are quite a lot of 404 responses being saved.
This is because we post the data block query with the 'ReleaseId' and if this param is present there's a security check which makes sure the subject belongs to the latest published release.
This PR amends the query we use to populate the data blocks CSV which drives the script to only include data blocks from the latest published release.
This eliminates all of the 404 'noise' being generated by the script.

EES-3167 Restrict get_data_block_responses CSV query to only include Data Blocks from the latest published Release

---

src/GovUk.Education.ExploreEducationStatistics.Common.Tests/Model/Data/Query/ObservationQueryContextTests.cs
src/GovUk.Education.ExploreEducationStatistics.Common.Tests/Model/Data/TableBuilderConfigurationTests.cs

This PR addresses a couple of feedback comments of https://github.com/dfe-analytical-services/explore-education-statistics/pull/3180 (EES-3167) which has already been accepted and merged.
In unit testing that the `Clone` methods of `ObservationQueryContext` and `TableBuilderConfiguration` are performing a deep copy, we now assert that all of the fields in the clones are the same as the originals, prior to the updates that we make to the clones.

EES-3205 Address PR feedback of EES-3167

---

src/GovUk.Education.ExploreEducationStatistics.Publisher.Tests/Services/DataBlockMigrationServiceTests.cs
src/GovUk.Education.ExploreEducationStatistics.Publisher/Services/DataBlockMigrationService.cs

This PR adds in a `distinct` when retrieving data block query codes for a particular geographic level so that we only resolve a single id for each code.
In Pre-prod we see one or two datablocks containing duplicate codes e.g.
```
"Locations": {
"LocalAuthority": [
"E09000002",
"E09000002",
"E08000016",
"E06000022",
"E06000055"]
}
```
These were previously being resolved multiple times so the resulting array of location id's also contained duplicate Guid's.

🐛 EES-3167 Add distinct when retrieving data block query codes

---

tests/robot-tests/tests/admin/bau/create_data_block_with_chart.robot

This PR: 
- Adds an assertion to `create_datablock_with_chart` to assert that when a user updates a footnote, the updated footnote shows up on the data block in the content section. This assertion came about as part of a bug raised whereby cached data blocks don't get invalidated if a user updates a footnote (EES-3136)

EES-3178 - add UI test update footnote assertion

---

src/explore-education-statistics-common/src/modules/charts/components/MapBlock.module.scss
src/explore-education-statistics-common/src/modules/charts/components/MapBlockInternal.tsx
src/explore-education-statistics-common/src/modules/charts/components/__tests__/MapBlockInternal.test.tsx
tests/robot-tests/tests/admin/bau/create_data_block_with_chart.robot
tests/robot-tests/tests/general_public/release_page_absence.robot
tests/robot-tests/tests/libs/charts.robot

The ticket was to move the indicator tiles to above maps so they are more noticeable.  However, doing this resulted in the map being pushed down the page, potentially off screen, when there were several tiles.
Chatted to Cam about it, he realised that all datasets were shown in the indicator tiles, not just the one that's selected. The same was true of the tooltip when you hover over the map.
So this PR:
- only shows the selected data set as an indicator tile and in the tooltip
- moves the indicator tile to under the map legend to make it more noticeable
- adds aria-live="polite" so that screen readers are informed when it changes
- removes aria-live="assertive" from the map legend to prevent useless information being shouted at screen reader users …

EES-3086 EES-3060 move map indicator tile

---

tests/robot-tests/tests/admin/bau/create_data_block_with_chart.robot

This PR is a quick fix for the UI tests in `create_data_block_with_chart.robot` which are now failing since the chart line symbol now defaults to 'None' after  EES-2842.
This fix configures a line symbol as expected by the verifications in `charts.robot - user mouses over line chart point` 
```
user waits until parent contains element    ${locator}
...    css:.recharts-line-dots:nth-of-type(${line}) .recharts-symbols:nth-of-type(${number})
```
The seeded Absence Release is still configured with line symbols. Happy to enhance this PR to cater for no symbols but any additional change will need to take the tests on that seeded Release into account.

EES-3250 Fix UI tests in create_data_block_with_chart.robot

---

useful-scripts/get_data_block_responses/get_data_block_responses.py

This PR:
- separates out requests and responses for datablocks into separate files for easier comparison in cases where we expect the requests to change
- adds additional helpful metrics to script output
- captures the response bodies of non-200 responses to aid in determining the reason behind failures

EE-3237 - updated get_data_block_responses.py script for easier testing

---

src/GovUk.Education.ExploreEducationStatistics.Admin.Tests/Services/ReplacementServiceTests.cs
src/GovUk.Education.ExploreEducationStatistics.Admin/Services/ReplacementService.cs
src/GovUk.Education.ExploreEducationStatistics.Data.Model/Repository/Interfaces/ILocationRepository.cs
src/GovUk.Education.ExploreEducationStatistics.Data.Model/Repository/LocationRepository.cs

This PR:
- adds an additional constraint to the lookup of Locations for use in Data Block replacements by restricting to the Locations that were in the original Subject

EES-3228 - only use replacement Locations from original Subject

---

src/GovUk.Education.ExploreEducationStatistics.Admin/Migrations/ContentMigrations/20220309154956_EES3237_AddDataBlockColumnForLocationsMigration.Designer.cs
src/GovUk.Education.ExploreEducationStatistics.Admin/Migrations/ContentMigrations/20220309154956_EES3237_AddDataBlockColumnForLocationsMigration.cs
src/GovUk.Education.ExploreEducationStatistics.Content.Model/ContentBlock.cs
src/GovUk.Education.ExploreEducationStatistics.Content.Model/Database/ContentDbContext.cs
src/GovUk.Education.ExploreEducationStatistics.Publisher.Tests/Services/DataBlockMigrationServiceTests.cs
src/GovUk.Education.ExploreEducationStatistics.Publisher/Services/DataBlockMigrationService.cs

This PR makes a change to the data blocks migration added by https://github.com/dfe-analytical-services/explore-education-statistics/pull/3180.
It adds a new `ContentBlock` column `DataBlock_TableHeaderCountChanged`, used to flag whether the table header count has changed as a result of additional headers being inserted. 
This allows us to easily spot tables that have had additional headers inserted which need checking carefully.
It also allows us to know in advance of testing which tables we should expect visual differences to occur for.
The migration status of all data blocks is reset which will force us to re-run the migration so that this value is calculated. Migrating them again will be safe since the chart/query/table pre-migration remain the same post-migration. The new values are …

EES-3237 Flag whether the table header count has changed during data blocks migration

---

infrastructure/parameters/dev.parameters.json
infrastructure/parameters/pre-prod.parameters.json
infrastructure/parameters/prod.parameters.json
infrastructure/parameters/test.parameters.json
infrastructure/templates/template.json

This PR makes ARM template changes with the overall aim intending to increase the capacity of the Content database in the Prod environment from 1Gb to 2Gb.
The actual changes are:
- Rename variable `maxDbSizeBytes` to `maxStatsDbSizeBytes`.
- Add variable `maxStatsDbSizeBytes` with default value to all environment files where it's missing (Test and Pre-Prod).
- Add variable `maxContentDbSizeBytes` with default 1Gb to replace current value which was 1Gb (1073741824 bytes).
- Override variable `maxContentDbSizeBytes` in the Prod environment file to 2Gb (2147483648 bytes).

EES-3259 Increase size of Prod content db and parameterise size as variable

---

infrastructure/parameters/dev.parameters.json

This PR corrects the `maxContentDbSizeBytes` in the environment file `dev.parameters.json` for the Dev environment.
This was a mistake made in https://github.com/dfe-analytical-services/explore-education-statistics/pull/3207.

EES-3259 Correct maxContentDbSizeBytes in dev.parameters.json

---

src/explore-education-statistics-common/src/modules/charts/util/__tests__/expandDataSet.test.ts
src/explore-education-statistics-common/src/modules/table-tool/components/utils/__tests__/getCsvData.test.ts
src/explore-education-statistics-common/src/modules/table-tool/components/utils/getCsvData.ts
src/explore-education-statistics-common/src/modules/table-tool/types/filters.ts
src/explore-education-statistics-common/src/modules/table-tool/types/workerFullTable.ts
src/explore-education-statistics-common/src/modules/table-tool/utils/__tests__/mapTableHeadersConfig.test.ts
src/explore-education-statistics-frontend/src/modules/table-tool/components/__tests__/__data__/tableData.ts

This PR fixes a bug where we see unique location id's being included in the `location_code` column of the public downloadable CSV files.
Whilst working for historical Permalinks which only contain location codes, the CSV files are wrong when downloaded from newly built tables, table highlights or fast tracks.
This PR adds a new class member `code` to WorkerLocationFilter which should only ever contain the code which is then used for the value of the `location_code` column in the CSV data.

🐛 EES-3273 Ensure location codes are returned in downloadable CSV file

---

src/GovUk.Education.ExploreEducationStatistics.Admin/Startup.cs
src/GovUk.Education.ExploreEducationStatistics.Admin/web.config
src/GovUk.Education.ExploreEducationStatistics.Content.Api/Startup.cs
src/GovUk.Education.ExploreEducationStatistics.Content.Api/web.config
src/GovUk.Education.ExploreEducationStatistics.Data.Api/Startup.cs
src/GovUk.Education.ExploreEducationStatistics.Data.Api/web.config

This PR adds health checks to the admin, data & content API. This has been added in order to provide an endpoint that Azure can use during deployments (in an attempt to fix EES-949)

    EES-3268 - add health checks to admin, content & data APIs

---

src/explore-education-statistics-common/src/modules/table-tool/components/FixedMultiHeaderDataTable.tsx
src/explore-education-statistics-common/src/modules/table-tool/components/MultiHeaderTable.module.scss
src/explore-education-statistics-common/src/modules/table-tool/components/MultiHeaderTable.tsx
src/explore-education-statistics-common/src/modules/table-tool/components/TimePeriodDataTable.tsx
src/explore-education-statistics-common/src/modules/table-tool/components/__tests__/TimePeriodDataTable.test.tsx
src/explore-education-statistics-common/src/modules/table-tool/components/__tests__/__snapshots__/TimePeriodDataTable.test.tsx.snap

Fixes table layout when LADs don't have regions, which causes rows to be mis-aligned.
The fix:
- adds an empty header in the case of a location filter with an empty string for group (when a group isn't expected group is undefined)
- when the table is rendered converts this header into an empty <td> as empty <th> cause accessibility problems
- adds some styling to make it look ok.
For testing
- the original files are attached to the ticket
- please test with reordering the rows and columns, including moving the locations into columns
- please check there are no problems with other location groupings / combinations

EES-3258 fix table layout when missing region

---

src/GovUk.Education.ExploreEducationStatistics.Admin.Tests/Security/AuthorizationHandlers/ViewSpecificMethodologyAuthorizationHandlerTests.cs
src/GovUk.Education.ExploreEducationStatistics.Admin.Tests/Services/UserReleaseRoleRepositoryTests.cs
src/GovUk.Education.ExploreEducationStatistics.Admin/Security/AuthorizationHandlers/ViewSpecificMethodologyAuthorizationHandlers.cs
src/GovUk.Education.ExploreEducationStatistics.Admin/Services/Interfaces/IUserReleaseRoleRepository.cs
src/GovUk.Education.ExploreEducationStatistics.Admin/Services/UserReleaseRoleRepository.cs
src/GovUk.Education.ExploreEducationStatistics.Content.Model/Repository/Interfaces/IMethodologyRepository.cs
src/GovUk.Education.ExploreEducationStatistics.Content.Model/Repository/MethodologyRepository.cs
src/explore-education-statistics-admin/src/pages/methodology/edit-methodology/content/MethodologyContentPage.tsx
src/explore-education-statistics-admin/src/pages/methodology/edit-methodology/content/components/MethodologyNotesSection.tsx
src/explore-education-statistics-admin/src/pages/methodology/edit-methodology/content/context/MethodologyContentContext.tsx
src/explore-education-statistics-admin/src/pages/release/pre-release/PreReleaseMethodologiesPage.tsx
src/explore-education-statistics-admin/src/pages/release/pre-release/PreReleaseMethodologyPage.tsx
src/explore-education-statistics-admin/src/pages/release/pre-release/PreReleasePageContainer.tsx
src/explore-education-statistics-admin/src/pages/release/pre-release/__tests__/PreReleaseMethodologiesPage.test.tsx
src/explore-education-statistics-admin/src/pages/release/pre-release/__tests__/PreReleaseMethodologyPage.test.tsx
src/explore-education-statistics-admin/src/routes/preReleaseRoutes.ts
tests/robot-tests/tests/admin/bau/prerelease.robot

Adds methodologies to the pre-releases:
- adds a methodologies tab to the pre-release screen which lists methodologies associated with the publication
- these link to a read only view of the methodology or directly to the url in the case of external methodologies
Methodologies are shown when they are:
- published
- published amendments
- approved & scheduled
- approved  & scheduled amendments
If a methodology has a unapproved draft amendment the previous published version is shown.
This PR also includes the required permission changes (by @markhiveit )

EES-3270 pre-release methodology view frontend / EES-3271 pre-release methodology view backend permissions

---

Pipfile.lock

This PR is an update of the `Pipfile.lock` file with differences seen after the upgrade from Python 3.8 to Python 3.10 on creation of the virtaulenv.

EES-3285 Updating Pipfile.lock after Python 3.8 to 3.10 upgrade

---

tests/robot-tests/tests/admin/bau/create_data_block_with_chart.robot

This PR: 
- fixes a flaky test when tests are run using `pabot`. I've run the entire suite of tests a few times locally with high concurrency so I'm pretty certain that these changes are solid & the flakiness has been fixed

EES-3296 - fix create_data_block_with_chart UI test

---

src/explore-education-statistics-admin/src/pages/release/data/components/ReorderFiltersList.tsx
src/explore-education-statistics-admin/src/pages/release/data/components/ReorderIndicatorsList.tsx
src/explore-education-statistics-admin/src/pages/release/data/components/ReorderList.tsx
src/explore-education-statistics-admin/src/pages/release/data/components/__tests__/ReorderFiltersList.test.tsx
src/explore-education-statistics-admin/src/pages/release/data/components/__tests__/ReorderIndicatorsList.test.tsx
src/explore-education-statistics-common/src/modules/table-tool/types/filters.ts
src/explore-education-statistics-common/src/services/tableBuilderService.ts

Fixes reordering filters when there's only one filter group.
Also, uses the value for filter/indicator items instead of expecting an id.

EES-3298 fix filter reordering

---

src/explore-education-statistics-admin/src/pages/release/data/ReleaseDataPage.tsx
src/explore-education-statistics-admin/src/pages/release/data/components/ReorderList.tsx

Fixes:
- refreshing the subjects list on the reordering filters & indicators tab when data files change.
- reordering ungrouped indicators

EES-3302 fix refreshing reordering tab and ungrouped indicators

---

package.json

This PR changes the pre-commit hooks for Python and Robot Framework files to use `pipenv run` instead of `python3 -m pipenv`. 
This change is required to stop errors when committing via the IntelliJ GUI (due to not being able to locate `pipenv` in the virtualenv packages).

Change Python/RF commit hooks to just use `pipenv run`

---

tests/robot-tests/tests/admin/bau/create_data_block_with_chart.robot
tests/robot-tests/tests/admin/bau/legacy_releases.robot

This PR:
- fixes a small issue in the legacy release suite whereby the following error consistently happened when the tests are run in a CI environment: 
```bash
Parent 'css:body' did not contain 'xpath:.//button[text()="Create legacy release"]' in 45 seconds.
```
Other changes:
- runs RF lint command to fix `create_data_block_with_chart.robot` lint issues that were missed during the python upgrade

EES-3316 - fix legacy release UI test

---

tests/robot-tests/tests/admin/bau/login.robot

This PR:
Adds authentication tests that are intended to run against test, pre-prod & production environments. This piece of work mainly came about as a result of a temporary infra problem that occurred on production (after a deploy) which resulted in roughly 1h 30mins of authentication downtime which prevented analyst & bau users from logging into the admin app. As a result of now having access to dfe test accounts, we can now run admin tests against test, pre-prod & production

EES-3303 - add authentication tests

---

tests/robot-tests/run_tests.py
tests/robot-tests/scripts/get_auth_tokens.py
tests/robot-tests/scripts/get_webdriver.py
tests/robot-tests/tests/admin/bau/create_data_block_with_chart.robot
tests/robot-tests/tests/admin/bau/legacy_releases.robot

This PR: 
- fixes an issue where UI tests downloaded chromedriver into two separate directories (because pyderman is being called in both `run_tests.py` & in `get_auth_tokens.py`
Other changes: 
- changes return type of `get_identity_info` to `Union[str, str]`
- fixes  arguments made to pyderman when downloading chromedriver

EES 3317 - deduplicate webdriver directories

---

src/explore-education-statistics-frontend/src/pages/index.tsx

This pull request updates the text on the homepage to include a link back to DfE's statistics homepage on gov.uk, something other DfE services are also adding.
I've made these changes directly in GitHub's text editor, therefore I'm not sure if this change will affect any of the UI tests, if it does then I will need help in updating those.

EES-3340 add stats at dfe to homepage

---

tests/robot-tests/tests/admin/bau/release_status.robot

This PR: 
- adds waits to certain keywords in release_status.robot in order to prevent flakiness/transient failures when this test is running in a CI environment

EES-3351 - add additional waits to release_status.robot UI test

---

src/explore-education-statistics-admin/src/pages/release/pre-release/ReleasePreReleaseAccessPage.tsx
src/explore-education-statistics-admin/src/pages/release/pre-release/__tests__/ReleasePreReleaseAccessPage.test.tsx

Hides the pre-release users tab for amendments as invites are only sent for original releases.

EES-2825 hide pre-release users tab for amendments

---

src/GovUk.Education.ExploreEducationStatistics.Admin.Tests/Services/FootnoteServicePermissionTests.cs
src/GovUk.Education.ExploreEducationStatistics.Admin.Tests/Services/FootnoteServiceTests.cs
src/GovUk.Education.ExploreEducationStatistics.Admin/Services/DataBlockService.cs
src/GovUk.Education.ExploreEducationStatistics.Admin/Services/FootnoteService.cs
src/GovUk.Education.ExploreEducationStatistics.Admin/Services/Interfaces/IDataBlockService.cs
src/GovUk.Education.ExploreEducationStatistics.Data.Model/FilterItem.cs
tests/robot-tests/tests/admin/bau/create_data_block_with_chart.robot

This PR fixes a bug where Admin data block cache files wouldn't get invalidated after updating footnotes. This meant that if a data block has been cached and then someone updated footnotes associated with that data block, in Admin Content the data block would display the wrong footnotes.
We now delete all data block cache files associated with a release whenever a footnote is added, updated, or removed. This was for speed and simplicity of implementing it. Also, ascertaining what specific data blocks are affected by a footnote change will probably be an expensive operation, so it isn't clear that doing that is actually preferable.
This PR also adds unit tests for `FootnoteService#DeleteFootnote` and `FootnoteService#UpdateFootnote`, and enables a `Failing` UI test that checks that this PR …

EES-3136 Invalidate Admin data blocks cache files after footnotes get updated

---

src/explore-education-statistics-admin/src/pages/release/datablocks/components/chart/__tests__/ChartLegendConfiguration.test.tsx
src/explore-education-statistics-common/src/modules/charts/util/chartUtils.ts

This PR simply updates the colour choices in chart builder to match ONS recommendations.
Note that the ticket suggests that the colours should be grouped by their use-case, however, this isn't really possible using the native colour selector. Discussed with @cjrace and for now we're not going add groupings for now.

EES-3320 Update chart colour options to match ONS recommendations

---

src/explore-education-statistics-admin/src/components/editable/EditableBlockWrapper.tsx
src/explore-education-statistics-admin/src/components/editable/__tests__/EditableBlockWrapper.test.tsx
src/explore-education-statistics-admin/src/pages/release/content/components/ReleaseContent.tsx
src/explore-education-statistics-admin/src/pages/release/content/components/ReleaseContentAccordionSection.tsx
src/explore-education-statistics-admin/src/pages/release/content/components/ReleaseEditableBlock.tsx
src/explore-education-statistics-admin/src/pages/release/content/components/ReleaseHeadlines.tsx
src/explore-education-statistics-admin/src/pages/release/content/components/__tests__/ReleaseEditableBlock.test.tsx

Adds an 'Edit data block' link to data blocks on the edit release content tab.

EES-3230 add edit data block links on release content tab

---

src/explore-education-statistics-common/src/modules/find-statistics/components/DataBlockTabs.tsx

Removes the hidden link to switch to the Table tab on data blocks. 
This was recommended by the DAC report as the link was confusing to keyboard users and the tab controls already provide an accessible way to switch between charts and tables.

EES-3016 remove hidden link on data block tabs

---

src/GovUk.Education.ExploreEducationStatistics.Admin.Tests/Controllers/Api/Statistics/FootnoteControllerTests.cs
src/GovUk.Education.ExploreEducationStatistics.Admin/Controllers/Api/Statistics/FootnoteController.cs
src/GovUk.Education.ExploreEducationStatistics.Admin/Services/ReplacementService.cs
src/GovUk.Education.ExploreEducationStatistics.Common.Tests/Extensions/ActionResultTestExtensions.cs
src/GovUk.Education.ExploreEducationStatistics.Common.Tests/Extensions/EitherTestExtensions.cs
src/GovUk.Education.ExploreEducationStatistics.Common/Model/Either.cs
src/GovUk.Education.ExploreEducationStatistics.Common/Utils/IPersistenceHelper.cs
src/GovUk.Education.ExploreEducationStatistics.Common/Utils/PersistenceHelper.cs
src/GovUk.Education.ExploreEducationStatistics.Data.Model/Repository/AbstractRepository.cs
src/GovUk.Education.ExploreEducationStatistics.Data.Model/Repository/BoundaryLevelRepository.cs
src/GovUk.Education.ExploreEducationStatistics.Data.Model/Repository/FilterRepository.cs
src/GovUk.Education.ExploreEducationStatistics.Data.Model/Repository/IndicatorGroupRepository.cs
src/GovUk.Education.ExploreEducationStatistics.Data.Model/Repository/Interfaces/IBoundaryLevelRepository.cs
src/GovUk.Education.ExploreEducationStatistics.Data.Model/Repository/Interfaces/IFilterRepository.cs
src/GovUk.Education.ExploreEducationStatistics.Data.Model/Repository/Interfaces/IIndicatorGroupRepository.cs
src/GovUk.Education.ExploreEducationStatistics.Data.Model/Repository/Interfaces/IRepository.cs
src/GovUk.Education.ExploreEducationStatistics.Data.Services.Tests/DataGuidanceSubjectServiceTests.cs
src/GovUk.Education.ExploreEducationStatistics.Data.Services.Tests/ResultSubjectMetaServiceTests.cs
src/GovUk.Education.ExploreEducationStatistics.Data.Services.Tests/SubjectMetaServiceTests.cs
src/GovUk.Education.ExploreEducationStatistics.Data.Services/DataGuidanceSubjectService.cs
src/GovUk.Education.ExploreEducationStatistics.Data.Services/ResultSubjectMetaService.cs
src/GovUk.Education.ExploreEducationStatistics.Data.Services/SubjectMetaService.cs
src/GovUk.Education.ExploreEducationStatistics.Data.Services/ValidationErrorMessages.cs

This PR builds upon https://github.com/dfe-analytical-services/explore-education-statistics/pull/3270 adding validation to ensure that when filters, filter groups, filter items, indicator groups and indicators are updated that the request contains all elements for the subject and that there are no unexpected elements.
When the update request is processed the sequence of filters and indicators groups is set based on the order in the request along with the sequences of their respective filter groups, filter items, and indicators. It's important to make sure that no elements are missing and that no elements unknown to the subject are included.
* Add async support to `FilterRepository` and `IndicatorGroupRepository`.

EES-3345 Validate all filters and indicators for subject are present on update

---

tests/robot-tests/tests/admin/bau/release_content_authoring.robot

Fixes a click interception in the release content authoring UI test

EES-3381 - fix click interception in release content authoring test

---

src/GovUk.Education.ExploreEducationStatistics.Admin.Tests/Services/ReplacementServiceHelperTests.cs
src/GovUk.Education.ExploreEducationStatistics.Admin.Tests/Services/ReplacementServiceTests.cs
src/GovUk.Education.ExploreEducationStatistics.Admin/Services/ReplacementService.cs
src/GovUk.Education.ExploreEducationStatistics.Admin/Services/ReplacementServiceHelper.cs
src/GovUk.Education.ExploreEducationStatistics.Data.Services.Tests/FiltersViewModelBuilderTests.cs
src/GovUk.Education.ExploreEducationStatistics.Data.Services.Tests/IndicatorsViewModelBuilderTests.cs
src/GovUk.Education.ExploreEducationStatistics.Data.Services/FilterAndIndicatorViewModelBuilders.cs
src/explore-education-statistics-admin/src/pages/release/data/ReleaseDataPage.tsx

This PR makes a change to the Admin data replacement service to make it aware that a `ReleaseSubject` being replaced can now contain the ordering of filters and indicators (as chosen by analysts) and that it needs to be retained on the replacement `ReleaseSubject` if the replacement is requested.
Replacement subjects are temporarily staged while a replacement plan is reviewed. Analysts can choose to request the replacement if the plan is valid or cancel it in which case the replacement subject is removed.
No `FilterSequence` or`IndicatorSequence` will be set on the replacement `ReleaseSubject` until the replacement is requested.
If they are not set on the original `ReleaseSubject` they will remain unset on the replacement.
If a `FilterSequence` or `IndicatorSequence` is set on the …

EES-2793 Retain ordering of Filters and Indicators when data is replaced

---

src/explore-education-statistics-admin/src/pages/users/components/__tests__/RoleForm.test.tsx

Fixed the test, it wasn't taking the placeholder option into account.

EES-3402 fix RoleForm test

---

src/explore-education-statistics-common/src/components/GoToTopLink.tsx
src/explore-education-statistics-common/src/components/__tests__/__snapshots__/AccordionSection.test.tsx.snap

Changes the go to top link in accordions to move the focus to the main content anchor when clicked, previously the focus remained on the link when clicked.

EES-3018 focus main content when click go to top in accordion

---

src/explore-education-statistics-admin/src/hooks/useBlockLock.ts
src/explore-education-statistics-admin/src/pages/methodology/edit-methodology/content/components/__tests__/MethodologyNotesSection.test.tsx
src/explore-education-statistics-admin/src/pages/publication/components/PublicationForm.tsx
src/explore-education-statistics-admin/src/pages/release/components/ReleaseStatusForm.tsx
src/explore-education-statistics-admin/src/pages/release/components/__tests__/ReleaseSummaryForm.test.tsx
src/explore-education-statistics-admin/src/pages/release/content/components/AddSecondaryStats.tsx
src/explore-education-statistics-admin/src/pages/release/pre-release/components/PreReleaseUserAccessForm.tsx
src/explore-education-statistics-admin/src/serviceWorker.ts

This is a speculative attempt to fix an intermittently failing frontend unit test. This probably isn't the solution, but these `awaits` need adding anyway, so we're still going to commit these changes.

EES-3354 Add missing awaits

---

src/explore-education-statistics-admin/src/hooks/__tests__/useHubState.test.ts
src/explore-education-statistics-admin/src/hooks/useHubState.ts
src/explore-education-statistics-admin/src/services/hubs/utils/Hub.ts

This PR fixes issues where:
- `hub.stop` is prematurely called e.g. whilst connecting. This normally throws an error.
- `hub.stop` is _not_ called if the component unmounts but the hub was still connecting. This could lead to orphaned connections that were still open with the server and lead to over-saturation.

EES-3405 Fix `useHubState` not managing connections correctly

---

infrastructure/parameters/prod.parameters.json
infrastructure/templates/template.json

This PR:
- ups Prod's private Stats DB's capacity from 350GB to 450GB.
- reduces user space warning thresholds from 90% to 85% to allow for 70GB wiggle room in Stats DB for doing reindexing jobs (based on max historical space needed for doing these jobs)
- introduces a second set of used space alerts with "URGENT" in the title for triggering alerts when used space reaches 95%.

EES-3394 - updated prods db size from 350GB to 450GB

---

src/GovUk.Education.ExploreEducationStatistics.Admin/Migrations/MigrationConstants.cs
src/GovUk.Education.ExploreEducationStatistics.Admin/Migrations/UsersAndRolesMigrations/20220527101017_EES3388_RenameTestUserEmails.Designer.cs
src/GovUk.Education.ExploreEducationStatistics.Admin/Migrations/UsersAndRolesMigrations/20220527101017_EES3388_RenameTestUserEmails.cs
src/GovUk.Education.ExploreEducationStatistics.Admin/Migrations/UsersAndRolesMigrations/20220527101017_EES3388_RenameTestUserEmails_down.sql
src/GovUk.Education.ExploreEducationStatistics.Admin/Migrations/UsersAndRolesMigrations/20220527101017_EES3388_RenameTestUserEmails_upsert.sql
tests/robot-tests/scripts/create_snapshots.py
tests/robot-tests/tests/admin/analyst/invite_contributor_as_publication_owner.robot
tests/robot-tests/tests/admin/analyst/role_ui_permissions/release_and_publication_role_end_to_end_permissions.robot
tests/robot-tests/tests/admin/bau/manage_users_page.robot
tests/robot-tests/tests/admin/bau/prerelease.robot
tests/robot-tests/tests/admin/bau/release_content_authoring.robot
tests/robot-tests/tests/admin_and_public/bau/publish_release_and_amend_2.robot
tests/robot-tests/tests/libs/admin-common.robot
tests/robot-tests/tests/libs/tables-common.robot
tests/robot-tests/tests/visual_testing/permalinks.robot
tests/robot-tests/tests/visual_testing/visually_check_permalinks.dev.robot
tests/robot-tests/tests/visual_testing/visually_check_permalinks.template.robot
tests/robot-tests/tests/visual_testing/visually_check_tables_and_charts.seed_data.robot
tests/robot-tests/tests/visual_testing/visually_check_tables_and_charts.template.robot

This PR: 
- migrates test accounts to EES based accounts 
- updates UI tests to use these new accounts 
Other notes/changes
- Updates to email & password fields in `.env.*` files will have to be made in order to use these new accounts (locally & on development) 
- lints python & robot test files

EES-3388, EES-3392, EES-1868 - migrate test users

---

src/GovUk.Education.ExploreEducationStatistics.Admin.Tests/Services/UserManagementServicePermissionTests.cs
src/GovUk.Education.ExploreEducationStatistics.Admin.Tests/Services/UserManagementServiceTests.cs
src/GovUk.Education.ExploreEducationStatistics.Admin/Controllers/Api/UserManagement/UserInvitesController.cs
src/GovUk.Education.ExploreEducationStatistics.Admin/Controllers/Api/UserManagement/UserManagementController.cs
src/GovUk.Education.ExploreEducationStatistics.Admin/Services/Interfaces/IUserManagementService.cs
src/GovUk.Education.ExploreEducationStatistics.Admin/Services/UserManagementService.cs
src/GovUk.Education.ExploreEducationStatistics.Admin/ViewModels/AddUserReleaseRoleViewModel.cs
src/GovUk.Education.ExploreEducationStatistics.Admin/ViewModels/UserInviteViewModel.cs
src/GovUk.Education.ExploreEducationStatistics.Admin/ViewModels/UserReleaseRoleAddViewModel.cs
src/explore-education-statistics-admin/src/pages/users/UserInvitePage.tsx
src/explore-education-statistics-admin/src/pages/users/components/InviteUserReleaseRoleForm.tsx
src/explore-education-statistics-admin/src/services/userService.ts

This work allows a BAU user to assign user release roles when inviting a new user. These user release roles are then created when the user logs in the for the first time.
This work also ensures that if a pending invite is cancelled, any associated user release role invites are also cancelled.
Additional work to change the invite email text to include the user release roles they've been invited to (EES-3403) and listing the user release roles of pending invites on the Pending user invites page (EES-3404) will be done in separate PRs.

EES-3386 Add ability to assign user release roles when inviting a new user

---

src/explore-education-statistics-admin/src/pages/release/content/components/ReleaseHeadlines.tsx
src/explore-education-statistics-admin/src/pages/release/datablocks/components/__tests__/DataBlockPageTabs.test.tsx
src/explore-education-statistics-admin/src/pages/release/pre-release/__tests__/ReleasePreReleaseAccessPage.test.tsx
src/explore-education-statistics-common/src/components/Tabs.module.scss
src/explore-education-statistics-common/src/components/Tabs.tsx
src/explore-education-statistics-common/src/components/TabsSection.tsx
src/explore-education-statistics-common/src/components/__tests__/Tabs.test.tsx
src/explore-education-statistics-common/src/components/__tests__/__snapshots__/Tabs.test.tsx.snap
src/explore-education-statistics-common/src/modules/find-statistics/components/DataBlockTabs.tsx
tests/robot-tests/tests/admin_and_public/bau/publish_release_and_amend.robot
tests/robot-tests/tests/libs/admin-common.robot
tests/robot-tests/tests/libs/common.robot

Accessibility improvements for tabs:
- when there's only one tab, for instance when datablocks with just a table are embedded in release content, the tab list is `aria-hidden` to prevent screen readers from seeing it.
- added screen reader only text to the tabs so they make sense when read out of context. This is via a new tabLabel field as the title is used in GA events so had to remain just a string
- changed it so the up and down keys move between tabs and prevented being able to loop over the tabs with the keyboard, this makes it more consistent with expected tabs behaviour and the GDS design system
- changed `user clicks link` to use xpath so that data block tab links can be clicked now that there is adjacent visually hidden text
- I noticed that the Headlines Key Stats block on …

EES-3022 improve tabs accessibility

---

src/GovUk.Education.ExploreEducationStatistics.Admin.Tests/Controllers/Api/Bau/BauCacheControllerTests.cs
src/GovUk.Education.ExploreEducationStatistics.Admin.Tests/Services/ReleaseServiceTests.cs
src/GovUk.Education.ExploreEducationStatistics.Admin.Tests/Services/TopicServiceTests.cs
src/GovUk.Education.ExploreEducationStatistics.Admin/Cache/DataBlockTableResultCacheKey.cs
src/GovUk.Education.ExploreEducationStatistics.Admin/Controllers/Api/Bau/BauCacheController.cs
src/GovUk.Education.ExploreEducationStatistics.Admin/Controllers/Api/Statistics/TableBuilderMetaController.cs
src/GovUk.Education.ExploreEducationStatistics.Admin/Services/ReleaseService.cs
src/GovUk.Education.ExploreEducationStatistics.Admin/Services/TopicService.cs
src/GovUk.Education.ExploreEducationStatistics.Admin/Startup.cs
src/GovUk.Education.ExploreEducationStatistics.Common.Tests/Converters/EnumToEnumValueConverterTests.cs
src/GovUk.Education.ExploreEducationStatistics.Common/Cache/PrivateReleaseContentFolderCacheKey.cs
src/GovUk.Education.ExploreEducationStatistics.Common/Converters/EnumToEnumValueConverter.cs
src/GovUk.Education.ExploreEducationStatistics.Common/Services/FileStoragePathUtils.cs
src/GovUk.Education.ExploreEducationStatistics.Content.Api/Startup.cs
src/GovUk.Education.ExploreEducationStatistics.Data.Api/Startup.cs
src/GovUk.Education.ExploreEducationStatistics.Data.Model/Database/StatisticsDbContext.cs
src/GovUk.Education.ExploreEducationStatistics.Data.Services.Tests/SubjectMetaServicePermissionTests.cs
src/GovUk.Education.ExploreEducationStatistics.Data.Services.Tests/SubjectMetaServiceTests.cs
src/GovUk.Education.ExploreEducationStatistics.Data.Services/Cache/PrivateSubjectMetaCacheKey.cs
src/GovUk.Education.ExploreEducationStatistics.Data.Services/SubjectMetaService.cs
src/GovUk.Education.ExploreEducationStatistics.Data.Services/ViewModels/LocationViewModelBuilder.cs
src/GovUk.Education.ExploreEducationStatistics.Publisher/Services/ContentService.cs
src/GovUk.Education.ExploreEducationStatistics.Publisher/Startup.cs

The motivation behind this PR is that underlying datasets containing school level data are soon to be released in EES and 
the existing location wizard step in the table builder is going to be slow to use since it currently presents the full list of location options available. There could be 20k+ options.
We could implement a dedicated back-end location search and remove the dependency on all the locations being supplied upfront in the subject metadata response, but some rework would be required to restore data blocks and fast tracks in the table builder. See the notes of EES-3433 which has investigated this for more details.
Before we do this, we'd like to know if the existing client side location search would be sufficient if we can make the current subject meta data response more …

EES-3437 Performance improvements to fetching subject metadata

---

src/GovUk.Education.ExploreEducationStatistics.Admin/appsettings.json
src/GovUk.Education.ExploreEducationStatistics.Data.Api/appsettings.json

⚠️ This change requires clearing the public and private subject meta data caches using the `DELETE https://<admin-url>/api/bau/public-cache/releases` and the `DELETE https://<admin-url>/api/bau/private-cache` endpoints.
This PR adds the configuration to enable a location hierarchy for schools to group them by local authority in the table builder and in tables.
[Watch video of filtered results grouped into a hierarchy of LA's](https://www.loom.com/share/c78bddb8afaa445fac5a6729fba77d84)
and here's an underlying data set with a small set of schools where 2 schools are grouped into the 'Sunderland' LA:
**Table builder wizard step showing hierarchy of schools grouped by LA's**
**Table showing schools grouped by LA's**

EES-3450 Enable a location hierarchy of school by Local Authority.

---

infrastructure/templates/template.json
src/GovUk.Education.ExploreEducationStatistics.Admin.Tests/Services/EmailTemplateServiceTests.cs
src/GovUk.Education.ExploreEducationStatistics.Admin.Tests/Services/UserManagementServiceTests.cs
src/GovUk.Education.ExploreEducationStatistics.Admin/Controllers/Api/UserManagement/UserInvitesController.cs
src/GovUk.Education.ExploreEducationStatistics.Admin/Services/EmailTemplateService.cs
src/GovUk.Education.ExploreEducationStatistics.Admin/Services/Interfaces/IEmailTemplateService.cs
src/GovUk.Education.ExploreEducationStatistics.Admin/Services/Interfaces/IUserManagementService.cs
src/GovUk.Education.ExploreEducationStatistics.Admin/Services/ReleaseInviteService.cs
src/GovUk.Education.ExploreEducationStatistics.Admin/Services/UserManagementService.cs
src/GovUk.Education.ExploreEducationStatistics.Admin/ViewModels/PendingInviteViewModel.cs
src/GovUk.Education.ExploreEducationStatistics.Admin/appsettings.Development.json
src/explore-education-statistics-admin/src/pages/users/InvitedUsersPage.tsx
src/explore-education-statistics-admin/src/pages/users/PreReleaseUsersPage.tsx
src/explore-education-statistics-admin/src/pages/users/components/InviteUserPublicationRoleForm.tsx
src/explore-education-statistics-admin/src/pages/users/components/InviteUserReleaseRoleForm.tsx
src/explore-education-statistics-admin/src/services/userService.ts
tests/robot-tests/tests/admin/bau/create_publication_and_release.robot
tests/robot-tests/tests/admin/bau/invite_new_users.robot
tests/robot-tests/tests/admin/bau/prerelease.robot
tests/robot-tests/tests/admin_and_public/bau/archive_publication.robot
tests/robot-tests/tests/admin_and_public/bau/legacy_releases.robot
tests/robot-tests/tests/admin_and_public/bau/publish_methodology.robot
tests/robot-tests/tests/libs/admin-common.robot
tests/robot-tests/tests/libs/common.robot
tests/robot-tests/tests/libs/tables-common.robot

:rotating_light: The new `Invite with roles` email template id needs adding to preprod and prod before this is deployed to those environments :rotating_light: 
This PR now displays release and publication roles attached to invite on the Pending Invites page, and lists any attached release and publication roles to a new user's invite email.

EES-3403 EES-3404 Update Pending invite page with roles and include roles in Invite email

---

src/GovUk.Education.ExploreEducationStatistics.Common/Model/Chart/ChartAxisConfiguration.cs
src/explore-education-statistics-admin/src/pages/release/datablocks/components/chart/ChartAxisConfiguration.tsx
src/explore-education-statistics-admin/src/pages/release/datablocks/components/chart/ChartReferenceLinesConfiguration.tsx
src/explore-education-statistics-admin/src/pages/release/datablocks/components/chart/__tests__/ChartAxisConfiguration.test.tsx
src/explore-education-statistics-admin/src/pages/release/datablocks/components/chart/__tests__/ChartReferenceLinesConfiguration.test.tsx
src/explore-education-statistics-common/src/modules/charts/components/HorizontalBarBlock.tsx
src/explore-education-statistics-common/src/modules/charts/components/LineChartBlock.tsx
src/explore-education-statistics-common/src/modules/charts/components/VerticalBarBlock.tsx
src/explore-education-statistics-common/src/modules/charts/components/utils/createReferenceLine.tsx
src/explore-education-statistics-common/src/modules/charts/types/chart.ts
src/explore-education-statistics-common/src/styles/utils/_position.scss

This PR adds the ability to configure chart reference line styling from one of three options:
- Dashed (the default for most charts)
- Solid (new option)
- None (new option and the default for bar charts)
- Fixed there potentially being excessive options for reference line positions due to the options previously being generated from the table meta. This would often lead to options that were not present in the rendered chart. 
To reduce the options down, we now use the data set configurations (from `ChartAxisConfiguration`) to generate these options. Using data set configurations is advantageous as these should only generate position options for facets that actually exist on the chart.
Chart reference line configuration:
Rendered chart with different reference line styles:

EES-3479 Allow chart reference lines to be unstyled

---

tests/robot-tests/scripts/create_snapshots.py
tests/robot-tests/tests/snapshots/data_catalogue_snapshot.json
tests/robot-tests/tests/snapshots/table_tool_snapshot.json

https://github.com/dfe-analytical-services/explore-education-statistics/pull/3330 has changed the ‘Choose a Publication’ step on the Table Tool and the Data Catalogue pages to not use the Details component.
Instead of being able to gather the themes/topics/publications for these pages by scraping the HTML, the pages now include a form containing a list of themes as radio button inputs with labels. On selecting a theme the list of publications for the theme is shown as radio button inputs with labels.
Topics are no longer shown.
This PR updates the `create_snapshots.py` script to interact with the form using Selenium to build the collection of themes and publications as JSON.
It also contains a commit updating the snapshots to match the latest data from the Prod environment.

EES-3481 Update create_snaphots.py to interact with publications form after EES-3017

---

infrastructure/templates/template.json

We created a new template for invites, using the variable `NotifyInviteWithRolesTemplateId`. Now that has been deployed we can remove `NotifyInviteTemplateId`

EES-3428 Remove NotifyInviteTempateId variable

---

tests/robot-tests/scripts/create_snapshots.py
tests/robot-tests/tests/libs/snapshots.py

This PR alters `snapshots.py` to pass webdriver as an argument.
The process of creating the snapshots was failing in the DevOps pipeline where it runs via the robot test `tests/general_public/check_snapshots.robot` due to the missing webdriver.

EES-3481 Alter snapshots.py to pass webdriver as argument

---

src/explore-education-statistics-common/src/components/form/FormCheckbox.tsx
src/explore-education-statistics-common/src/components/form/FormCheckboxGroup.module.scss
src/explore-education-statistics-common/src/components/form/FormCheckboxGroup.tsx
src/explore-education-statistics-common/src/components/form/FormCheckboxSearchGroup.tsx
src/explore-education-statistics-common/src/components/form/__tests__/FormCheckboxGroup.test.tsx
src/explore-education-statistics-common/src/components/form/__tests__/FormCheckboxSearchGroup.test.tsx
src/explore-education-statistics-common/src/components/form/__tests__/__snapshots__/FormCheckboxSearchGroup.test.tsx.snap
src/explore-education-statistics-common/src/modules/table-tool/components/LocationFiltersForm.tsx
src/explore-education-statistics-common/src/modules/table-tool/components/__tests__/LocationFiltersForm.test.tsx
src/explore-education-statistics-common/src/utils/number/numberWithCommas.ts

Handles schools in the table tool locations step:
- as the data set is very large it doesn't show any schools initially, you have to search to get any results.
- there's a maximum limit on the number of results shown to prevent people searching for generic terms like 'school' and getting thousands of results. This is currently set to 500 which seems to render without problems.
- you can search by school name or URN. This uses the same basic text search as before.
- you have to type 3 characters or more to start a search.
This only applies to schools, all other location types function as before.
**Location hierarchy**
The backend provides the schools data with the location hierarchy (grouped by local authority). In the front end, instead of displaying the schools grouped by LA, as with …

EES-3452 school search

---

src/explore-education-statistics-common/src/modules/release/components/ReleaseDataAccordion.module.scss

This fixes a styling issue in EES-3453 where a HR dividing line wasn't being displayed between the "Explore data and files" and "Related dashboard(s)" accordion sections

EES-3453 Fix ReleaseDataAccordion styling issue

---

Pipfile
Pipfile.lock

This PR: 
- upgrades python to 3.10.5 
See https://www.python.org/downloads/release/python-3105/ for release notes & install instructions

EES-3480 - upgrade python to 3.10.5

---

src/GovUk.Education.ExploreEducationStatistics.Admin.Tests/Areas/Identity/Pages/Account/ExternalLoginTests.cs
src/GovUk.Education.ExploreEducationStatistics.Admin.Tests/Services/PreReleaseUserServiceTests.cs
src/GovUk.Education.ExploreEducationStatistics.Admin.Tests/Services/UserInviteRepositoryTests.cs
src/GovUk.Education.ExploreEducationStatistics.Admin/Areas/Identity/Pages/Account/ExternalLogin.cshtml.cs
src/GovUk.Education.ExploreEducationStatistics.Admin/Services/Interfaces/IUserInviteRepository.cs
src/GovUk.Education.ExploreEducationStatistics.Admin/Services/PreReleaseUserService.cs
src/GovUk.Education.ExploreEducationStatistics.Admin/Services/ReleaseInviteService.cs
src/GovUk.Education.ExploreEducationStatistics.Admin/Services/UserInviteRepository.cs
src/GovUk.Education.ExploreEducationStatistics.Admin/Services/UserManagementService.cs

This PR makes a couple of minor changes to invites:
1. When inviting an existing user to Pre-release, only create a `UserReleaseInvite` if the release is not approved, i.e. when the e-mail is not being sent immediately.
An invite has to exist in order for the e-mail to be sent at a later date which is why we create it, but it's not necessary to create one if the release is already approved and the e-mail is being sent at the same time.
2. When a new user is logging in for the first time, don't delete their `UserReleaseInvite`'s and `UserPublicationInvite`'s.
The reason for removing the deletion of `UserReleaseInvites`'s is that there can be invites where e-mails haven't been sent yet, i.e. in the case of Pre-release invites where e-mails are not sent until a release is approved.
If _all_ …

EES-3489 EES-3491 Changes to invites

---

src/explore-education-statistics-admin/src/pages/release/content/components/ReleaseContent.tsx

This PR makes a similar change to the Admin Release content page as  the change made to the public page in https://github.com/dfe-analytical-services/explore-education-statistics/pull/3373 to fix the 'Explore data and files' link which was broken.

EES-3534 Correct target of Explore data and files in the Admin release content page.

---

src/GovUk.Education.ExploreEducationStatistics.Admin/Properties/launchSettings.json
src/GovUk.Education.ExploreEducationStatistics.Admin/Startup.cs
src/GovUk.Education.ExploreEducationStatistics.Admin/appsettings.json

This PR:
- adds some fallback support for cases where no OpenIdConnect additional configuration is available for a given environment
- switches to explicitly listing the ValidIssuers of access tokens for a given environment.  By default this will always be the environment-specific URL of the Admin service.  Locally, we can add more aliases like `ees.local` to the list.

Ees 3482 try fixing refresh tokens on dev

---

tests/robot-tests/tests/admin/bau/manage_users_page.robot
tests/robot-tests/tests/libs/slack.py

This PR: 
- Fixes UI tests (disables an assertion from running to prevent false positives - see https://dfedigital.atlassian.net/browse/EES-3546 for context) 
- Fixes BS4 warning when sending test reports & test results via slack - see https://dfedigital.atlassian.net/browse/EES-3544

EES-3545, EES-3544 - Fix BS4 warning & fix UI tests

---

tests/performance-tests/src/tests/public/findStatisticsPage.test.ts

This PR:
- adds a Find Statistics page test to run alongside the existing Get Release test, whilst testing the scenario outlined in EES-3542.
- points Get Release at a release that is consistently available in all environments
To run the scenario in question, the details are on the ticket, but after deleting the cache entries in question, run:
```
cd tests/performance-tests
npm run store-environment-details --environment=dev
npm run test dist/getReleasePage.test.js --environment=dev && npm run test dist/findStatisticsPage.test.js --environment=dev
```

EES-3542 - added new Find Statistics Page test to performance tests

---

src/GovUk.Education.ExploreEducationStatistics.Common/Services/BlobStorageService.cs

This PR makes a quick change to remove a zero length check on a blob in `BlobStorageService#DownloadBlobText` before streaming it. This is used by `BlobCacheService#GetItem` every time a cached call looks up the cache key in the storage container to return the deserialised JSON if the blob exists.
This code was a shortcut to avoid opening a content stream if the content is empty.
This change is being made as it seems unlikely that an empty blob will exist and this check was adding additional overhead to every call since checking the content length required retrieving the blob properties.
Retrieving blob properties is an additional HTTP call to the storage container meaning a lot of unnecessary outgoing HTTP traffic get blob properties were occurring for cached method calls.
After this …

EES-3553 Remove zero length check getting cache items from blob storage which gets blob properties

---

src/GovUk.Education.ExploreEducationStatistics.Admin/Migrations/ContentMigrations/20220721114241_EES-3557_ReleaseRelatedInformationNotNull.Designer.cs
src/GovUk.Education.ExploreEducationStatistics.Admin/Migrations/ContentMigrations/20220721114241_EES-3557_ReleaseRelatedInformationNotNull.cs
src/GovUk.Education.ExploreEducationStatistics.Content.Model/Database/ContentDbContext.cs

This PR makes an update to `Release.RelatedInformation`, updating all Releases with a null value in the database to have an empty array. This then matches expectations in code accessing the `RelatedInformation` property which expect a non-null `List<Link>` value.
After this change we also make the `Release.RelatedInformation` column not nullable now that every Release should have a value.
This fixes a bug seen where users were unable to create Release amendments where the current version has a null RelatedInformation value, failing in `ReleaseAmendmentExtensions.CreateAmendment:58` projecting the list which is expected to be non-null.

EES-3557 Ensure all Releases have non-null RelatedInformation

---

src/GovUk.Education.ExploreEducationStatistics.Admin.Tests/Services/ImportStatusBauServiceTests.cs
src/GovUk.Education.ExploreEducationStatistics.Admin/Migrations/ContentMigrations/20220725145526_EES3569_RenamingTotalRows.Designer.cs
src/GovUk.Education.ExploreEducationStatistics.Admin/Migrations/ContentMigrations/20220725145526_EES3569_RenamingTotalRows.cs
src/GovUk.Education.ExploreEducationStatistics.Admin/Services/DataImportService.cs
src/GovUk.Education.ExploreEducationStatistics.Admin/Services/ImportStatusBauService.cs
src/GovUk.Education.ExploreEducationStatistics.Admin/ViewModels/DataImportViewModel.cs
src/GovUk.Education.ExploreEducationStatistics.Admin/ViewModels/ImportStatusBauViewModel.cs
src/GovUk.Education.ExploreEducationStatistics.Content.Model/DataImport.cs
src/GovUk.Education.ExploreEducationStatistics.Data.Processor.Tests/Services/DataImportServiceTests.cs
src/GovUk.Education.ExploreEducationStatistics.Data.Processor.Tests/Services/FileImportServiceTests.cs
src/GovUk.Education.ExploreEducationStatistics.Data.Processor/Services/DataImportService.cs
src/GovUk.Education.ExploreEducationStatistics.Data.Processor/Services/FileImportService.cs
src/GovUk.Education.ExploreEducationStatistics.Data.Processor/Services/Interfaces/IDataImportService.cs
src/GovUk.Education.ExploreEducationStatistics.Data.Processor/Services/ProcessorService.cs
src/explore-education-statistics-admin/src/pages/bau/BauImportsPage.tsx
src/explore-education-statistics-admin/src/pages/release/data/__tests__/ReleaseDataFileReplacePage.test.tsx
src/explore-education-statistics-admin/src/pages/release/data/components/__tests__/ImporterStatus.test.tsx
src/explore-education-statistics-admin/src/pages/release/data/components/__tests__/ReleaseDataUploadsSection.test.tsx
src/explore-education-statistics-admin/src/services/importStatusService.ts
src/explore-education-statistics-admin/src/services/releaseDataFileService.ts

`DataImport` stores information about a data import. It holds transient data while an import is in progress but is also retained to display information such as the number of rows a file has.
In future it might be better if we split data files out from the `File` model to have their own table type and keep all information about a data file that needs retained together in one entity.
If the importer needs to use the database for transient data then it could continue to use `DataImport` but this would remove the need for the import data to be retained long term.
For now, this PR addresses a problem with the naming of the `DataImport` rows columns `Rows` and `TotalRows`.
It seems `Rows` is the total number of rows and `TotalRows` is the number of rows that are importable (i.e. matching …

EES-3569 Rename DataImport TotalRows to ImportedRows and Rows to TotalRows

---

src/GovUk.Education.ExploreEducationStatistics.Admin.Tests/Services/FileMigrationServiceTests.cs
src/GovUk.Education.ExploreEducationStatistics.Admin/Services/FileMigrationService.cs
src/GovUk.Education.ExploreEducationStatistics.Publisher.Tests/Services/FileMigrationServiceTests.cs
src/GovUk.Education.ExploreEducationStatistics.Publisher/Services/FileMigrationService.cs
src/GovUk.Education.ExploreEducationStatistics.Publisher/Startup.cs

⚠️ Has deploy task EES-3549
This PR makes an update to the files migration introduced by EES-3547 in https://github.com/dfe-analytical-services/explore-education-statistics/pull/3389 which will be run by EES-3549.
It's already been run but is re-runnable so it can be used at any time to 'catch-up' with new files that don't yet have `ContentLength` or `ContentType` values.
This PR updates it so that it will also queue messages for data file id's if the `DataImport` doesn't have a positive value for `TotalRows`. When processing each data file it will now retrieve the `DataImport` and set `TotalRows` if necessary.
This update seems to be necessary for all data files that were originally uploaded as zip files. The value was not being set when creating the `DataImport` and wasn't updated even …

EES-3571 Update all DataImports without TotalRows set

---

src/GovUk.Education.ExploreEducationStatistics.Admin.Tests/Security/AuthorizationHandlers/Utils/AuthorizationHandlersTestUtil.cs
src/GovUk.Education.ExploreEducationStatistics.Common/Security/AuthorizationHandlerContextFactory.cs
src/GovUk.Education.ExploreEducationStatistics.Content.Api/Controllers/MethodologyImageController.cs
src/GovUk.Education.ExploreEducationStatistics.Content.Api/Startup.cs
src/GovUk.Education.ExploreEducationStatistics.Content.Api/StartupSecurityConfiguration.cs
src/GovUk.Education.ExploreEducationStatistics.Content.Security.Tests/AuthorizationHandlers/ViewMethodologyVersionAuthorizationHandlerTests.cs
src/GovUk.Education.ExploreEducationStatistics.Content.Security.Tests/AuthorizationHandlers/ViewPublicationAuthorizationHandlerTests.cs
src/GovUk.Education.ExploreEducationStatistics.Content.Security.Tests/AuthorizationHandlers/ViewReleaseAuthorizationHandlerTests.cs
src/GovUk.Education.ExploreEducationStatistics.Content.Security/AuthorizationHandlers/ViewMethodologyVersionAuthorizationHandler.cs
src/GovUk.Education.ExploreEducationStatistics.Content.Security/ContentSecurityPolicies.cs
src/GovUk.Education.ExploreEducationStatistics.Content.Security/Extensions/UserServiceExtensions.cs
src/GovUk.Education.ExploreEducationStatistics.Content.Services.Tests/MethodologyImageServicePermissionTests.cs
src/GovUk.Education.ExploreEducationStatistics.Content.Services.Tests/MethodologyImageServiceTests.cs
src/GovUk.Education.ExploreEducationStatistics.Content.Services/Interfaces/IMethodologyImageService.cs
src/GovUk.Education.ExploreEducationStatistics.Content.Services/MethodologyImageService.cs

Methodology images are currently secured by comparing a special `releasedatetime` property on the image blob containing the date/time that the file was published with the current date/time of the request.
This relies on the blob property being set during publishing when blobs are copied from private to public storage. Only images which have been published are publicly accessible, and only when their published date/time has passed.
To find the `releasedatetime` value we use `BlobStorageService#GetBlob` to get the blob properties and custom metadata. Internally this relies on `BaseBlobClient.GetPropertiesAsync` which makes an additional HTTP call to the storage account.
Making additional calls to get check a blob exists and then get the blob properties before streaming a blob (which already …

EES-3548 Secure methodology images with methodology version permission check

---

src/docker-compose.yml

This PR rolls back the SQL Server version specified in `docker-compose.yml` from 2022 to 2019. Currently, 2022 is only in public preview and is consequently not safe to use.
We should only bump this up when it goes generally available and check that there wouldn't be any problems with compatibility with Azure SQL Database.

EES-3580 Roll SQL Server back to 2019 in docker-compose.yml

---

tests/robot-tests/tests/libs/create_emulator_release_files.py

This PR makes an update to the `create_emulator_release_files.py` python script which we use to create blobs in the storage emulator for the local environment.
In future after EES-3529 the blobs only need to exist so that they can be zipped, or a successful download can be initiated for them.
All other properties about file uploads such as content type (used to open a stream to download them), content length, and  number of rows (applicable to data files) are now stored in either the `File` or `DataImport` in the database.
This PR:
* Removes setting metadata on blobs, meaning name, published date and number of rows is no longer relevant in the code too.
* Sets a content type on blobs.
* Stops uploading the 'All files' zip which is now generated on demand.

EES-3567 Updating create_emulator_release_files.py after EES-3529

---

src/GovUk.Education.ExploreEducationStatistics.Admin.Tests/Services/ThemeServiceTests.cs
src/GovUk.Education.ExploreEducationStatistics.Admin/Services/ThemeService.cs
src/explore-education-statistics-admin/src/components/form/FormThemeTopicSelect.tsx
src/explore-education-statistics-admin/src/pages/admin-dashboard/components/MethodologySummary.tsx
src/explore-education-statistics-admin/src/pages/admin-dashboard/components/__tests__/MethodologySummary.test.tsx
src/explore-education-statistics-admin/src/pages/admin-dashboard/components/__tests__/PublicationSummary.test.tsx
src/explore-education-statistics-admin/src/pages/methodology/external-methodology/ExternalMethodologyPage.tsx
src/explore-education-statistics-admin/src/pages/publication/PublicationDetailsPage.tsx
src/explore-education-statistics-admin/src/pages/publication/PublicationEditPage.tsx
src/explore-education-statistics-admin/src/pages/publication/PublicationPageContainer.tsx
src/explore-education-statistics-admin/src/pages/publication/__tests__/PublicationDetailsPage.test.tsx
src/explore-education-statistics-admin/src/pages/publication/__tests__/PublicationPageContainer.test.tsx
src/explore-education-statistics-admin/src/pages/publication/components/PublicationDetailsForm.tsx
src/explore-education-statistics-admin/src/pages/publication/components/__tests__/LegacyReleasesTable.test.tsx
src/explore-education-statistics-admin/src/pages/publication/components/__tests__/PublicationInviteNewUsersTab.test.tsx
src/explore-education-statistics-admin/src/pages/release/datablocks/__tests__/ReleaseTableToolPage.test.tsx
src/explore-education-statistics-admin/src/pages/release/pre-release/__tests__/PreReleaseMethodologiesPage.test.tsx
src/explore-education-statistics-admin/src/pages/release/pre-release/__tests__/PreReleaseTableToolPage.test.tsx
src/explore-education-statistics-admin/src/routes/publicationRoutes.ts
src/explore-education-statistics-admin/src/services/publicationService.ts

Adds the Details page to the new Manage Publication section.
This work will be hidden to users until it's all ready, so for this you can only access the new page directly, at /publication/details, there are no links to it yet.
This PR, https://github.com/dfe-analytical-services/explore-education-statistics/pull/3391 and https://github.com/dfe-analytical-services/explore-education-statistics/pull/3404 all make changes to PublicationPageContainer and publicationRoutes, when one is merged I'll rebase the others so all changes are kept.
Other things to note:
- archive publication is included in this section (it's not in the designs but I checked with Marv that it should go here)
- added the message when a publication is archived to the header of the Manage Publication section so it'll appear …

EES-3224 publication details page

---

src/explore-education-statistics-admin/src/pages/publication/PublicationContactPage.tsx
src/explore-education-statistics-admin/src/pages/publication/PublicationPageContainer.tsx
src/explore-education-statistics-admin/src/pages/publication/__tests__/PublicationContactPage.test.tsx
src/explore-education-statistics-admin/src/pages/publication/__tests__/PublicationPageContainer.test.tsx
src/explore-education-statistics-admin/src/pages/publication/components/PublicationContactForm.tsx
src/explore-education-statistics-admin/src/routes/publicationRoutes.ts

Adds the Contact page to the new Manage Publication section.
This work will be hidden to users until it's all ready, so for this you can only access the new page directly, at /publication//contact, there are no links to it yet.
This PR and https://github.com/dfe-analytical-services/explore-education-statistics/pull/3391 both make changes to PublicationPageContainer and publicationRoutes, when one is merged I'll rebase the other so all changes are kept.

EES-3223 publication contact details

---

src/GovUk.Education.ExploreEducationStatistics.Admin.Tests/Services/PreReleaseUserServiceTests.cs
src/GovUk.Education.ExploreEducationStatistics.Admin/Services/PreReleaseUserService.cs
src/GovUk.Education.ExploreEducationStatistics.Admin/ViewModels/PreReleaseUserViewModels.cs

This PR fixes a bug in the PRA invite list where duplicates can appear in the UI and console errors occur due to list elements not using unique keys. Users are likely to attempt removing the duplicate rows which then removes the invited email address completely leaving them not invited.
Prior to https://github.com/dfe-analytical-services/explore-education-statistics/commit/348e85ffdba1d9426e368d296e76df29358181d4#diff-cd8f55ba5c572b8c2ff29a81a0e9dbbd60cfa9d1592d7b7d73d2bfe07564e064 producing the email addresses for this list combined active users who already had the Prerelease role with the list of UserReleaseInvites for Prerelease not yet accepted. 
Despite there being a `.Distinct()` on the list of `PreReleaseUserViewModel` prior to returning it there was no definition of equality on …

EES-3535 Prevent duplicates in PRA invite list

---

src/explore-education-statistics-admin/src/pages/release/content/components/ReleaseContent.tsx
src/explore-education-statistics-common/src/modules/release/components/__tests__/ReleaseDataAccordion.test.tsx
src/explore-education-statistics-frontend/src/modules/find-statistics/PublicationReleasePage.tsx
tests/robot-tests/tests/admin/bau/upload_files.robot
tests/robot-tests/tests/admin_and_public/bau/publish_release_and_amend.robot
tests/robot-tests/tests/general_public/release_page_absence.robot

This PR: 
* adds `(zip)` to the end of the download all data button.
Other notes:
* Not sure what `downloads.title` is but there seems to be a reference to it in one of the GA logEvents. I've removed the stray curly bracket but potentially it can be removed all together
```typescript 
onClick={() => {
logEvent({
category: 'Downloads',
action: `Release page all files downloads.title, Release: ${release.title}, File: All files`,
});
}}
```

EES-3075 - add 'zip' to download all data button

---

src/explore-education-statistics-admin/src/pages/release/ReleaseStatusPage.tsx
tests/robot-tests/scripts/get_auth_tokens.py
tests/robot-tests/tests/admin/bau/prerelease.robot
tests/robot-tests/tests/admin/bau/release_content.robot
tests/robot-tests/tests/admin_and_public/bau/data_reordering.robot
tests/robot-tests/tests/admin_and_public/bau/prerelease_visibility.robot
tests/robot-tests/tests/admin_and_public/bau/publish_data.robot
tests/robot-tests/tests/admin_and_public/bau/publish_release_and_amend.robot
tests/robot-tests/tests/admin_and_public/bau/publish_release_and_amend_2.robot
tests/robot-tests/tests/general_public/methodology_page_absence.robot
tests/robot-tests/tests/general_public/release_page_absence.robot
tests/robot-tests/tests/libs/common.robot

This PR: 
- fixes a few TODOs and removes either unnecessary or failing tags from the tests. 
Relevant changes:
* Starts to scaffold out possibilities of how to validate data-guidance directory structure/files 
* Adds assertion to check new release status history entries get created on amendments
* Introduces a data-guidance related TODO in `release_page_absence.robot`
* Increases the timeout for `user clears element text` & `user presses keys` due to periodic failures I noticed when running the tests locally
* Adds `desired_capabilities=DesiredCapabilities.CHROME` parameter when creating a new instance of chrome driver. This seems to silence the various logging some people get on other consoles 
* Adds assertions to check for regressions of …

EES-3550, EES-3589 - review UI tests for TODOs, failing tags & other tags

---

tests/robot-tests/tests/libs/slack.py

This PR: 
Fixes a bs4 warning when parsing XML documents. This is something that was missed when upgrading BeautifulSoup to the latest version.
Warning: 
```python 
XMLParsedAsHTMLWarning: It looks like you're parsing an XML document using an HTML parser. If this really is an HTML document (maybe it's XHTML?), you can ignore or filter this warning. If it's XML, you should know that using an XML parser will be more reliable. To parse this document as XML, make sure you have the lxml package installed, and pass the keyword argument `features="xml"` into the BeautifulSoup constructor.
```

EES-3544 - fix bs4 warning when parsing xml documents

---

src/explore-education-statistics-admin/src/pages/admin-dashboard/AdminDashboardPage.tsx
src/explore-education-statistics-admin/src/pages/admin-dashboard/components/DraftReleaseRow.tsx
src/explore-education-statistics-admin/src/pages/admin-dashboard/components/DraftReleaseRowIssues.tsx
src/explore-education-statistics-admin/src/pages/admin-dashboard/components/DraftReleasesTab.tsx
src/explore-education-statistics-admin/src/pages/admin-dashboard/components/DraftReleasesTable.module.scss
src/explore-education-statistics-admin/src/pages/admin-dashboard/components/DraftReleasesTable.tsx
src/explore-education-statistics-admin/src/pages/admin-dashboard/components/PublicationsTab.tsx
src/explore-education-statistics-admin/src/pages/admin-dashboard/components/ReleasesByStatusTab.tsx
src/explore-education-statistics-admin/src/pages/admin-dashboard/components/ScheduledReleasesTab.tsx
src/explore-education-statistics-admin/src/pages/admin-dashboard/components/ScheduledReleasesTable.tsx
src/explore-education-statistics-admin/src/pages/admin-dashboard/components/TopicPublications.module.scss
src/explore-education-statistics-admin/src/pages/admin-dashboard/components/TopicPublications.tsx
src/explore-education-statistics-admin/src/pages/admin-dashboard/components/__tests__/DraftReleasesTable.test.tsx
src/explore-education-statistics-admin/src/pages/admin-dashboard/components/__tests__/PublicationsTab.test.tsx
src/explore-education-statistics-admin/src/pages/admin-dashboard/components/__tests__/ScheduledReleasesTable.test.tsx
src/explore-education-statistics-admin/src/pages/admin-dashboard/components/__tests__/TopicPublications.test.tsx
src/explore-education-statistics-admin/src/pages/release/components/ReleasePublishingStages.tsx
src/explore-education-statistics-admin/src/routes/routes.ts

Adds the new admin dashboard under a feature flag, add &showNewDashboard=true to the url to see it:
EES-3218 - Publications tab
- only the publication name is shown, which links to the new Manage Publication section
- BAU users still get the theme and topic dropdowns
- non-BAU users see all their publications at once (this is quite inefficient currently but will be updated when the API work is done) 
- loading draft and scheduled releases no longer blocks loading the publications
EES-3219 - Draft releases tab
- new style table of releases
- BAU users don't see the Issues as there are potential performance problems loading the checklist for lots of releases
- the draft releases are refreshed when you go to the tab
EES-3220 - Scheduled releases tab
- new style table of releases
- this tab …

EES-3218 EES-3219 EES-3220 admin dashboard

---

src/explore-education-statistics-admin/src/pages/release/pre-release/components/PreReleaseUserAccessForm.tsx
src/explore-education-statistics-admin/src/pages/release/pre-release/components/__tests__/PreReleaseUserAccessForm.test.tsx
tests/robot-tests/tests/admin/bau/prerelease.robot

This PR removes the email validation on the Admin Pre-release user access page emails field which restricted email addresses to the education.gov.uk domain. Addresses no longer have any domain restriction.
It also changes the validation so that the error identifies the email address which is invalid. This is useful if a long list of addresses is entered containing an invalid value somewhere within it.
Update (suggested by @ntsim): A single error is returned only for the first invalid email to avoid creating a long error message in the case of multiple invalid email addresses. This might have also been quite annoying for screen reader users.

EES-3582 Remove Pre-release email validation requiring education.gov.uk email addresses

---

src/explore-education-statistics-common/src/components/FigureFootnotes.tsx
tests/robot-tests/tests/admin_and_public/bau/publish_data.robot
tests/robot-tests/tests/admin_and_public/bau/publish_release_and_amend.robot
tests/robot-tests/tests/general_public/release_page_absence.robot
tests/robot-tests/tests/libs/common.robot

This PR reduces the number of footnotes shown in the collapsible list below data blocks before collapsing them from 5 to 2.

EES-3581 Reduce number of footnotes in collapsible list before collapsing from 5 to 2

---

tests/robot-tests/scripts/run_tests_pipeline.py

This PR:
fixes the snapshot CI failures due to 'None' being passed to the CLI. This throws the following error which results in the pipeline fatally failing
```python
pipenv run python run_tests.py: error: unrecognized arguments: None
```

EES-3637 - fix snapshot CI failures

---

src/GovUk.Education.ExploreEducationStatistics.Admin.Tests/Services/FileUploadsValidatorServiceTests.cs
src/GovUk.Education.ExploreEducationStatistics.Admin.Tests/Services/ReleaseDataFileServiceTest.cs
src/GovUk.Education.ExploreEducationStatistics.Admin/Services/DataArchiveValidationService.cs
src/GovUk.Education.ExploreEducationStatistics.Admin/Services/FileUploadsValidatorService.cs
src/GovUk.Education.ExploreEducationStatistics.Admin/Services/Interfaces/IFileUploadsValidatorService.cs
src/GovUk.Education.ExploreEducationStatistics.Admin/Services/ReleaseDataFileService.cs
src/GovUk.Education.ExploreEducationStatistics.Admin/Validators/ValidationErrorMessages.cs
src/GovUk.Education.ExploreEducationStatistics.Common.Tests/Utils/MockFormTestUtils.cs
src/explore-education-statistics-admin/src/pages/release/data/components/DataFileUploadForm.tsx

Normally a data filename is invalid if it already exists on the Release so that there's no ambiguity in the presentation of multiple files with the same name. If a data file is uploaded with the same name then a validation error is returned.
The only exception to this is in the case of data replacements where the same filename as the file being replaced is allowed.
`ValidateDataFileNames` method is parameterised with `replacingFile` so that the filename can be compared with the file being replaced, if any.
In the case of zip file upload validation, the value of `replacingFile` was missing, causing a bug where a validation error occurred uploading a replacement zip file containing a data file entry with the same name as the file being replaced.
This PR alters the …

EES-3153 Zip files replacement uploads are valid if the data file entry has the same name as the file it's replacing

---

tests/robot-tests/.env.example
tests/robot-tests/run_tests.py

This PR: 
- adds an assertion to `run_tests.py` to check that the required environment variable `WAIT_MEMORY_CACHE_EXPIRY` exists
Other changes:
* changes assertion error messages to be a bit more helpful if environment variables are missing
* Updates `.env.example`

EES-3655 - check 'WAIT_MEMORY_CACHE_EXPIRY' exists in UI tests

---

src/GovUk.Education.ExploreEducationStatistics.Admin.Tests/Services/Methodologies/MethodologyContentServiceTests.cs
src/GovUk.Education.ExploreEducationStatistics.Admin/Services/Methodologies/MethodologyContentService.cs
src/GovUk.Education.ExploreEducationStatistics.Common.Tests/Extensions/EnumerableExtensionsTests.cs
src/GovUk.Education.ExploreEducationStatistics.Common/Extensions/EnumerableExtensions.cs
src/GovUk.Education.ExploreEducationStatistics.Data.Services/SubjectMetaService.cs
src/explore-education-statistics-admin/src/components/editable/EditableAccordion.tsx
tests/robot-tests/tests/admin_and_public/bau/publish_methodology.robot

This PR fixes a bug in the Admin where content sections and annexe content sections could not be reordered on the methodology content page.
This was due to the `MethodologyVersionContent` related to the `MethodologyVersion` not being loaded when processing the request to reorder the sections.
It might be preferable that in future we change the `MethodologyContent` property to not be initialised by default.
Currently in `MethodologyVersion.cs`:
`public MethodologyVersionContent MethodologyContent { get; set; } = new();`
This could change to using the null-forgiving operator:
`public MethodologyVersionContent MethodologyContent { get; set; } = null!;`
This way we should observe a null `MethodologyVersionContent` if it hasn't been set due a bug where loading the related entity was missed, …

EES-3600 Fix methodology content and annexe content section reordering

---

src/explore-education-statistics-common/src/components/Details.tsx
src/explore-education-statistics-common/src/components/__tests__/Details.test.tsx
src/explore-education-statistics-common/src/modules/find-statistics/components/KeyStat.tsx
src/explore-education-statistics-common/src/modules/release/components/ReleaseDataAccordion.tsx

This PR:
- addresses an accessibility issue whereby the 'More details; and 'help' buttons don't give enough context about the 'More details' and 'help' buttons

EES-3050, EES-3051 - add more context to 'More details' + 'help' buttons for accessibility

---

tests/robot-tests/tests/libs/admin_api.py

This PR fixes the 'user resets user roles' keyword
I tested this by: 
* changing prelease user2 to a user to pre-release viewer
* changing prerelease user1 to an analyst user 
* running `manage_users_page.robot` and checked these users were reset to 'no role' & the test passed
full run:

EES-3671 - fix user resets user roles keyword

---

src/explore-education-statistics-admin/src/pages/publication/PublicationDetailsPage.tsx
src/explore-education-statistics-admin/src/pages/publication/components/PublicationDetailsForm.tsx
src/explore-education-statistics-admin/src/pages/publication/components/PublicationForm.tsx

This PR: 
- changes publication summary field from an input to text area
- fixes `PublicationDetailsPage.tsx` table formatting if no publication summary is set

EES-3669 - change publication summary to be textarea

---

src/explore-education-statistics-common/src/components/Details.tsx
src/explore-education-statistics-common/src/components/__tests__/Details.test.tsx
src/explore-education-statistics-common/src/components/form/FormCheckboxGroup.tsx
src/explore-education-statistics-common/src/components/form/FormCheckboxSearchSubGroups.tsx
src/explore-education-statistics-common/src/modules/find-statistics/components/KeyStat.tsx
src/explore-education-statistics-common/src/modules/release/components/ReleaseDataAccordion.tsx
src/explore-education-statistics-frontend/src/modules/find-statistics/components/ExploreDataButton.tsx
src/explore-education-statistics-frontend/src/modules/find-statistics/components/PublicationSectionBlocks.tsx

This PR: 
- fixes an accessibility issue whereby the 'explore data' button is repeated without additional context. For now, I've added visually hidden text inside the `ExploreDataButton` component and used `block.name` to provide additional context. Not too sure about whether the block is the right thing to use here as it just contains: ` Generic data block - National`. This potentially needs revisiting to decide whether something such as the datablock name would be a more appropriate text

EES-3062 - explore data button accesibility fixes

---

src/explore-education-statistics-admin/package-lock.json
src/explore-education-statistics-admin/package.json
src/explore-education-statistics-admin/src/App.tsx
src/explore-education-statistics-admin/src/pages/admin-dashboard/components/ScheduledReleasesTable.tsx
src/explore-education-statistics-admin/src/pages/publication/PublicationReleasesPage.tsx
src/explore-education-statistics-admin/src/pages/publication/__tests__/PublicationPageContainer.test.tsx
src/explore-education-statistics-admin/src/pages/publication/__tests__/PublicationReleasesPage.test.tsx
src/explore-education-statistics-admin/src/pages/publication/components/DraftReleaseRow.tsx
src/explore-education-statistics-admin/src/pages/publication/components/PublicationDraftReleases.tsx
src/explore-education-statistics-admin/src/pages/publication/components/PublicationPublishedReleases.tsx
src/explore-education-statistics-admin/src/pages/publication/components/PublicationPublishedReleasesTable.tsx
src/explore-education-statistics-admin/src/pages/publication/components/PublicationScheduledReleases.tsx
src/explore-education-statistics-admin/src/pages/publication/components/PublicationUnpublishedReleases.tsx
src/explore-education-statistics-admin/src/pages/publication/components/ScheduledReleaseRow.tsx
src/explore-education-statistics-admin/src/pages/publication/components/__tests__/PublicationDraftReleases.test.tsx
src/explore-education-statistics-admin/src/pages/publication/components/__tests__/PublicationPublishedReleases.test.tsx
src/explore-education-statistics-admin/src/pages/publication/components/__tests__/PublicationScheduledReleases.test.tsx
src/explore-education-statistics-admin/src/pages/publication/components/__tests__/PublicationUnpublishedReleases.test.tsx
src/explore-education-statistics-admin/test/render.tsx

This PR integrates the recently updated publication releases endpoint (`/api/{publicationId}/releases`) with the 'Manage publication > Releases' page.
We have had to reorganise some of the existing component structure to correctly integrate this endpoint i.e.
- `PublicationUnpublishedReleases` - handles draft and scheduled release tables
- `PublicationPublishedReleases` handles the live/published release table
Each of the above components makes its own request to fetch the relevant releases from the publication releases endpoint.
As part of this, we have introduced [React Query](https://tanstack.com/query) as a dependency to manage async requests. This is essentially a more feature complete version of the `useAsync*` collection of hooks that we use throughout the service. It provides …

EES-3554 Part 2 - Integrate publication releases endpoint with Manage publication > Releases page

---

src/explore-education-statistics-common/src/components/Accordion.tsx
src/explore-education-statistics-common/src/components/__tests__/Accordion.test.tsx
src/explore-education-statistics-frontend/src/modules/find-statistics/PublicationReleaseHelpAndSupportSection.tsx

This PR:
- adds visually hidden text to 'Open all' & 'Close all' accordion section buttons to address accesibility issues around 'Open all' & 'Close all' buttons not having enough context/repeating throughout a release page

EES-3058 - accordion accessibility fixes

---

tests/robot-tests/tests/general_public/fast_track.robot

This PR:
fixes the fast track UI test. This was failing due to visually hidden text being inside the 'explore data' link which caused the keyword `user clicks link` to fail. We've changed this to `user clicks link by visible text` which will ignore any screen reader only text

EES-3681 - fix fast track UI test

---

src/explore-education-statistics-admin/src/hooks/useCKEditorConfig.ts

This PR:
- changes the open in new tab CK editor functionality to always default to not open in a new tab. Currently, any links inserted into content blocks open in a new tab by default. As per conversations with Marv + information gathered from the DAC report, we should instead default this to false so that any links inserted into content blocks open in the current tab by default

EES-3683 - change OpenInNewTab defaultValue to be false

---

src/explore-education-statistics-admin/src/pages/admin-dashboard/components/__tests__/MethodologySummary.test.tsx
src/explore-education-statistics-admin/src/pages/release/content/components/ReleasePreviewTableToolFinalStep.tsx
src/explore-education-statistics-admin/src/pages/release/datablocks/components/DataBlockSourceWizard.tsx
src/explore-education-statistics-admin/src/pages/release/datablocks/components/TableTabSection.tsx
src/explore-education-statistics-admin/src/pages/release/pre-release/components/PreReleaseTableToolFinalStep.tsx
src/explore-education-statistics-common/src/components/form/FormCheckboxSearchSubGroups.tsx
src/explore-education-statistics-common/src/hooks/useDebouncedCallback.ts
src/explore-education-statistics-common/src/hooks/useThrottledCallback.ts
src/explore-education-statistics-common/src/modules/table-tool/components/TableHeadersGroupControls.tsx
src/explore-education-statistics-common/src/services/util/combineMeasuresWithDuplicateLocationCodes.ts
src/explore-education-statistics-frontend/src/modules/table-tool/components/__tests__/TableToolFinalStep.test.tsx

This PR: 
* cleans up some eslint warnings (namely around unused variables)

EES-3696 - cleanup lint warnings

---

src/GovUk.Education.ExploreEducationStatistics.Content.Api.Tests/Controllers/ThemeControllerTests.cs
src/GovUk.Education.ExploreEducationStatistics.Content.Services.Tests/Cache/MethodologyCacheServiceTests.cs
src/GovUk.Education.ExploreEducationStatistics.Content.Services.Tests/Cache/PublicationCacheServiceTests.cs
src/GovUk.Education.ExploreEducationStatistics.Content.Services.Tests/Cache/ThemeCacheServiceTests.cs
src/GovUk.Education.ExploreEducationStatistics.Content.Services/ViewModels/ContactViewModel.cs
src/GovUk.Education.ExploreEducationStatistics.Content.Services/ViewModels/ExternalMethodologyViewModel.cs

This PR adds default constructors to `ContactViewModel` and `ExternalMethodologyViewModel` to fix an error seen when deserializing `PublicationViewModel` from the public blob cache after https://github.com/dfe-analytical-services/explore-education-statistics/pull/3472 and adds a unit test for serialisation/deserialisation.
This error is visible in the app service logs when running the UI tests but did not cause any test failures.
- Move similar serialisation tests from `ThemeControllerTests` to `ThemeCacheServiceTests` and `MethodologyCacheServiceTests` since `ThemeController` isn't responsible for caching where the deserialisation happens.

Bugfix/EES-3648 Fix deserialisation error occurring when retrieving publications from blob cache

---

src/GovUk.Education.ExploreEducationStatistics.Admin.Tests/Controllers/Api/Bau/BauCacheControllerTests.cs
src/GovUk.Education.ExploreEducationStatistics.Admin/Controllers/Api/Bau/BauCacheController.cs
src/GovUk.Education.ExploreEducationStatistics.Admin/Startup.cs
src/GovUk.Education.ExploreEducationStatistics.Content.Api.Tests/Controllers/GlossaryControllerTests.cs
src/GovUk.Education.ExploreEducationStatistics.Content.Api/Controllers/GlossaryController.cs
src/GovUk.Education.ExploreEducationStatistics.Content.Api/Startup.cs
src/GovUk.Education.ExploreEducationStatistics.Content.Services.Tests/Cache/GlossaryCacheServiceTests.cs
src/GovUk.Education.ExploreEducationStatistics.Content.Services.Tests/Cache/MethodologyCacheServiceTests.cs
src/GovUk.Education.ExploreEducationStatistics.Content.Services.Tests/Cache/PublicationCacheServiceTests.cs
src/GovUk.Education.ExploreEducationStatistics.Content.Services/Cache/AllMethodologiesCacheKey.cs
src/GovUk.Education.ExploreEducationStatistics.Content.Services/Cache/GlossaryCacheKey.cs
src/GovUk.Education.ExploreEducationStatistics.Content.Services/Cache/GlossaryCacheService.cs
src/GovUk.Education.ExploreEducationStatistics.Content.Services/Cache/PublicationCacheKey.cs
src/GovUk.Education.ExploreEducationStatistics.Content.Services/Interfaces/Cache/IGlossaryCacheService.cs
src/GovUk.Education.ExploreEducationStatistics.Publisher.Tests/Services/PublishingServiceTests.cs
src/GovUk.Education.ExploreEducationStatistics.Publisher/Services/PublishingService.cs

This PR adds a new BAU endpoint to update the publicly cached glossary with the latest glossary from the database.
`PUT /api/bau/public-cache/glossary`
* Rename `BauCacheController` method `ClearPublicCacheTrees` to `UpdatePublicCacheTrees` and change request verb from `DELETE` to `PUT` to reflect that it now updates the cache rather than deleting from it.
* Move `PublicationCacheKey` and `AllMethodologiesCacheKey` from namespace `Common.Cache` to `Content.Services.Cache` to match `GlossaryCacheKey` and `PublicationTreeCacheKey`.
* Update the Confluence page to add this new operation and reflect other recent changes.

EES-3649 Add BAU endpoint to update public glossary cache

---

src/explore-education-statistics-common/src/components/PageSearchForm.module.scss
src/explore-education-statistics-common/src/components/PageSearchForm.tsx
src/explore-education-statistics-common/src/components/__tests__/__snapshots__/PageSearchForm.test.tsx.snap
src/explore-education-statistics-common/src/components/form/FormComboBox.tsx
src/explore-education-statistics-common/src/components/form/__tests__/FormComboBox.test.tsx
src/explore-education-statistics-common/src/components/form/__tests__/__snapshots__/FormComboBox.test.tsx.snap

This PR addresses the following accessibility issues related to `PageSearchForm` & `FormComboBox` which are used on Find stats / Methodology pages.
* [EES-3028](https://dfedigital.atlassian.net/browse/EES-3028) - Ensure that all interactive components can be found both in and out of context for screen reader users
* [EES-3029](https://dfedigital.atlassian.net/browse/EES-3029) - remove search button from `PageSearchForm` 
* [EES-3030](https://dfedigital.atlassian.net/browse/EES-3030) - Fix the ability for screen reader users to find the search element 
* [EES-3032](https://dfedigital.atlassian.net/browse/EES-3032) - Ensure that all interactive components can be found both in & out of context for screen reader users
Relevant changes:
* Added `aria-live="polite"` & `aria-atomic` to results …

EES-3028, EES-3029, EES-3030, EES-3032 - address combobox + page search accessibility issues

---

src/explore-education-statistics-admin/src/components/editable/ReorderableAccordion.tsx
src/explore-education-statistics-admin/src/components/editable/__tests__/ReorderableAccordion.test.tsx
src/explore-education-statistics-admin/src/pages/release/data/components/ReleaseDataUploadsSection.tsx
tests/robot-tests/tests/admin_and_public/bau/subject_reordering.robot

This PR:
disables re-order controls if a user can't update a release (such as when it's being published/approved). Previously, the re-order data-files still showed up even when a release was in the process of publishing or had the status of approved

EES-3677-2 disable reorder controls when release is published

---

src/explore-education-statistics-common/src/modules/table-tool/components/PublicationForm.tsx

Adds missing hash to link on step 1 of table tool page

EES-3701 - fix skip to search results link

---

src/explore-education-statistics-common/src/components/VisuallyHidden.tsx
src/explore-education-statistics-common/src/components/__tests__/VisuallyHidden.test.tsx
src/explore-education-statistics-frontend/src/modules/find-statistics/PublicationReleasePage.tsx

This PR: 
- adds a visually hidden h2 element to the release intro block on publication pages. This is to ensure the structure of headings is correct in order to improve accessibility and general best practice. In the future, we may want to give users the option to add H2s to release intro blocks so I've left a comment explaining why this has been implemented the current way instead of making amends to CK editor.

EES-3541 - add visually hidden h2 to release intro block

---

src/explore-education-statistics-common/src/components/FigureFootnotes.tsx
src/explore-education-statistics-common/src/modules/charts/components/ChartRenderer.tsx
src/explore-education-statistics-common/src/modules/table-tool/components/FixedMultiHeaderDataTable.tsx
src/explore-education-statistics-common/src/modules/table-tool/components/TimePeriodDataTable.tsx
src/explore-education-statistics-frontend/src/modules/find-statistics/components/PublicationSectionBlocks.tsx

This PR: 
* Alters 'footnotes' & 'explore and edit this data online' sections on Accordion sections to have hidden text in order to provide more context for screen readers

EES-3057 - address AccordionSection accesibility issues

---

src/explore-education-statistics-common/src/components/ContentHtml.module.scss
src/explore-education-statistics-common/src/components/ContentHtml.tsx
src/explore-education-statistics-common/src/components/GlossaryEntryButton.tsx
src/explore-education-statistics-common/src/components/__tests__/ContentHtml.test.tsx
src/explore-education-statistics-common/src/styles/_content.scss
src/explore-education-statistics-common/src/styles/_tables.scss

This PR fixes current accessibility issues with table markup from CKEditor that outputs something like:
```html
<figure class="table">
<table>...</table>
<figcaption>The caption</figcaption>
</figure>
```
Unfortunately, this isn't accessible as the caption gets read out after the table, meaning it doesn't provide further context.
To fix this, we intercept the markup in `ContentHtml` before it's rendered in the frontend and transform it into the following format:
```html
<table>
<caption>The caption</caption>
<tbody>...</tbody>
</table>
```
- Extracted `GlossaryEntryButton` component out of `ContentHtml` to tidy things up.

EES-3706 Fix inaccessible table captions outputted by CKEditor

---

src/explore-education-statistics-frontend/src/modules/find-statistics/PublicationReleasePage.tsx
src/explore-education-statistics-frontend/src/modules/find-statistics/__tests__/PublicationReleasePage.test.tsx

This PR: 
* fixes an accessibility issue whereby the 'last updated' & 'see other releases' headings weren't providing enough context to screen-readers
TODO: 
* update UI tests

EES-3052 - add more context to release headers

---

src/GovUk.Education.ExploreEducationStatistics.Admin.Tests/Services/PublicationServicePermissionTests.cs
src/GovUk.Education.ExploreEducationStatistics.Admin.Tests/Services/PublicationServiceTests.cs
src/GovUk.Education.ExploreEducationStatistics.Admin/Controllers/Api/PublicationController.cs
src/GovUk.Education.ExploreEducationStatistics.Admin/Mappings/MappingProfiles.cs
src/GovUk.Education.ExploreEducationStatistics.Admin/Requests/ExternalMethodologySaveRequest.cs
src/GovUk.Education.ExploreEducationStatistics.Admin/Requests/PublicationSaveRequest.cs
src/GovUk.Education.ExploreEducationStatistics.Admin/Services/Interfaces/IPublicationService.cs
src/GovUk.Education.ExploreEducationStatistics.Admin/Services/Methodologies/MethodologyService.cs
src/GovUk.Education.ExploreEducationStatistics.Admin/Services/PublicationService.cs
src/GovUk.Education.ExploreEducationStatistics.Admin/ViewModels/ExternalMethodologyViewModel.cs
src/GovUk.Education.ExploreEducationStatistics.Admin/ViewModels/PublicationSummaryViewModel.cs
src/GovUk.Education.ExploreEducationStatistics.Admin/ViewModels/PublicationViewModel.cs
src/explore-education-statistics-admin/src/pages/admin-dashboard/components/MethodologySummary.tsx
src/explore-education-statistics-admin/src/pages/admin-dashboard/components/PublicationSummary.tsx
src/explore-education-statistics-admin/src/pages/admin-dashboard/components/__tests__/MethodologySummary.test.tsx
src/explore-education-statistics-admin/src/pages/methodology/external-methodology/ExternalMethodologyPage.tsx
src/explore-education-statistics-admin/src/pages/publication/PublicationExternalMethodologyPage.tsx
src/explore-education-statistics-admin/src/pages/publication/PublicationMethodologiesPage.tsx
src/explore-education-statistics-admin/src/pages/publication/__tests__/PublicationExternalMethodologyPage.test.tsx
src/explore-education-statistics-admin/src/pages/publication/__tests__/PublicationMethodologiesPage.test.tsx
src/explore-education-statistics-admin/src/pages/release/content/components/ReleasePreviewTableToolFinalStep.tsx
src/explore-education-statistics-admin/src/pages/release/pre-release/PreReleaseMethodologiesPage.tsx
src/explore-education-statistics-admin/src/pages/release/pre-release/__tests__/PreReleaseMethodologiesPage.test.tsx
src/explore-education-statistics-admin/src/services/publicationService.ts

This PR adds new endpoints for use on Admin pages that get / update / remove an external methodology from a publication.
This code also changes the Admin frontend code to use these new endpoints when appropriate instead of using the `publicationService.createPublication` and `publicationService.updatePublication` endpoints. It is no longer possible to update a publication's external methodology with the `publicationService.updatePublication` endpoint.
I haven't added any UI tests. UI tests for new publication management pages will be done at the same time that they're unhidden, and it doesn't seem worth adding UI tests for the current ways of changing an external methodology as they will soon be removed.

EES-3666 New Admin API endpoints for getting/updating/removing ExternalMethodology

---

src/explore-education-statistics-common/src/modules/table-tool/components/SubjectForm.tsx
src/explore-education-statistics-common/src/modules/table-tool/components/SubjectStep.tsx
src/explore-education-statistics-common/src/modules/table-tool/components/TableToolInfo.tsx

Fixes heading levels in the table tool:
- in the 'More details' on the subject step when there are not featured tables
- in the Contact us section

EES-3082 fix heading levels in table tool

---

src/explore-education-statistics-admin/src/pages/release/datablocks/components/DataBlockSourceWizard.tsx
src/explore-education-statistics-admin/src/pages/release/datablocks/components/__tests__/DataBlockPageTabs.test.tsx
src/explore-education-statistics-admin/src/pages/release/pre-release/__tests__/ReleasePreReleaseAccessPage.test.tsx
src/explore-education-statistics-common/src/components/Tabs.module.scss
src/explore-education-statistics-common/src/components/Tabs.tsx
src/explore-education-statistics-common/src/components/TabsSection.tsx
src/explore-education-statistics-common/src/components/__tests__/Tabs.test.tsx
src/explore-education-statistics-common/src/components/__tests__/__snapshots__/Tabs.test.tsx.snap

Removes tabs when there is only one pane of content as this can be confusing to screen reader users. 
This affects:
- Key stats when there are no secondary stats
- Data blocks when there's just a table
- Pre-release access page on amendments
- Data blocks page in the admin when creating them or viewing a published release - I've added a 'Data source' heading to the content here as its not clear otherwise what you're doing.
Tabbed content with more than one tab should be unaffected.

EES-3083 remove tabs when only one

---

src/explore-education-statistics-common/src/components/ScreenReaderMessage.tsx
src/explore-education-statistics-common/src/components/__tests__/ScreenReaderMessage.test.tsx
src/explore-education-statistics-common/src/modules/table-tool/components/TableHeadersForm.tsx
src/explore-education-statistics-frontend/src/modules/table-tool/components/TableToolShare.tsx

- Announces to screen reader users when a shareable link is generated (EES-3054) and when it is copied to the clipboard (EES-3055).
- When the link is generated I've included the instructions for it in the screen reader announcement so that it's clear what to do and aria-hidden the displayed version of the same message.
- I've added a reusable component for screen reader messages and updated table tool reordering to use this as well.

EES-3054 & 3055 screen reader messages for shareable links

---

src/GovUk.Education.ExploreEducationStatistics.Content.Services/ViewModels/ReleaseCacheViewModel.cs

This PR is an update to https://github.com/dfe-analytical-services/explore-education-statistics/pull/3513.
It annotates `ReleaseCacheViewModel.Type` with json converter `StringEnumConverter`.
While there are no current issues without it, we see here that `Type` is being serialised as the ordinal position of the enum value.
This will become problematic in future and introduce a bug if the order of ReleaseType changes or if values are inserted or removed.
With this change the enum is converted to and from its name string value so there can be no ambiguity:

EES-3127 Annotate ReleaseCacheViewModel.Type with json converter StringEnumConverter

---

src/GovUk.Education.ExploreEducationStatistics.Admin.Tests/Services/PermalinkMigrationServicePermissionTests.cs
src/GovUk.Education.ExploreEducationStatistics.Admin.Tests/Services/PermalinkMigrationServiceTests.cs
src/GovUk.Education.ExploreEducationStatistics.Admin/Controllers/Api/Bau/PermalinkMigrationController.cs
src/GovUk.Education.ExploreEducationStatistics.Admin/Migrations/ContentMigrations/20221003123755_EES3751_AddPermalink.Designer.cs
src/GovUk.Education.ExploreEducationStatistics.Admin/Migrations/ContentMigrations/20221003123755_EES3751_AddPermalink.cs
src/GovUk.Education.ExploreEducationStatistics.Admin/Services/Interfaces/PermalinkMigrationService.cs
src/GovUk.Education.ExploreEducationStatistics.Admin/Services/PermalinkMigrationService.cs
src/GovUk.Education.ExploreEducationStatistics.Admin/Startup.cs
src/GovUk.Education.ExploreEducationStatistics.Admin/Validators/ValidationErrorMessages.cs
src/GovUk.Education.ExploreEducationStatistics.Content.Model/Database/ContentDbContext.cs
src/GovUk.Education.ExploreEducationStatistics.Content.Model/Permalink.cs
src/GovUk.Education.ExploreEducationStatistics.Data.Api.Tests/Services/PermalinkServiceTests.cs
src/GovUk.Education.ExploreEducationStatistics.Data.Api/Controllers/PermalinkController.cs
src/GovUk.Education.ExploreEducationStatistics.Data.Api/Mappings/MappingProfiles.cs
src/GovUk.Education.ExploreEducationStatistics.Data.Api/Models/LegacyPermalink.cs
src/GovUk.Education.ExploreEducationStatistics.Data.Api/Services/Interfaces/IPermalinkService.cs
src/GovUk.Education.ExploreEducationStatistics.Data.Api/Services/PermalinkService.cs
src/GovUk.Education.ExploreEducationStatistics.Data.Api/ViewModels/LegacyPermalinkViewModel.cs
src/GovUk.Education.ExploreEducationStatistics.Publisher.Model/MigratePermalinksMessages.cs
src/GovUk.Education.ExploreEducationStatistics.Publisher.Model/PublisherQueues.cs
src/GovUk.Education.ExploreEducationStatistics.Publisher.Tests/Services/PermalinkMigrationServiceTests.cs
src/GovUk.Education.ExploreEducationStatistics.Publisher/Functions/PermalinkMigrationFunction.cs
src/GovUk.Education.ExploreEducationStatistics.Publisher/Functions/PermalinksMigrationFunction.cs
src/GovUk.Education.ExploreEducationStatistics.Publisher/Services/Interfaces/IPermalinkMigrationService.cs
src/GovUk.Education.ExploreEducationStatistics.Publisher/Services/PermalinkMigrationService.cs
src/GovUk.Education.ExploreEducationStatistics.Publisher/Startup.cs

This PR introduces a new content database `Permalink` entity and adds a migration endpoint to add high-level info about Permalinks to the database. It's being done as part of the work to create permalink table snapshots, investigated by [EES-3665](https://dfedigital.atlassian.net/browse/EES-3665).
The content database is chosen over the statistics database to keep statistics purely related to data about statistics only.
Storing high level information about permalinks in the database gives us:
* An easier way to view the set of permalinks in existence and know its size, without browsing Azure storage.
* A way to query all Permalink id’s that we need to create snapshots for.
* A place to track the snapshot migration status as snapshots are created, until the migration is verified as …

EES-3751 Add high-level info about Permalinks to database

---

src/explore-education-statistics-admin/src/pages/release/datablocks/components/chart/ChartDataSetsConfiguration.tsx
src/explore-education-statistics-admin/src/pages/release/datablocks/components/chart/__tests__/ChartBuilder.test.tsx
src/explore-education-statistics-admin/src/pages/release/datablocks/components/chart/__tests__/ChartDataSetsConfiguration.test.tsx
tests/robot-tests/tests/admin/bau/create_data_block_with_chart.robot

- Adds a 'Remove all' button for data sets in the chart builder.
- Users are asked to confirm after clicking it.
- The data sets table and save actions are now always shown
- Trying to save without any data sets shows an error

EES-3583 remove all data sets option

---

src/explore-education-statistics-admin/src/components/editable/EditableKeyStat.tsx
src/explore-education-statistics-admin/src/components/editable/__tests__/EditableKeyStat.test.tsx
src/explore-education-statistics-common/src/modules/find-statistics/components/KeyStat.tsx
src/explore-education-statistics-common/src/modules/find-statistics/components/__tests__/KeyStat.test.tsx

This PR: 
* fixes a bug whereby the `hiddenText` variable for keyStat tiles is always undefined due to `summary?.dataDefinitionTitle[0]` being set to `Help` by default. 
* Previously we were checking if `summary?.dataDefinitionTitle[0]` was nullable and then setting `hiddenText` if so. The guidance text for a keyStat tile is never nullable and by default is set to the string: `Help`. This caused the previous ternary op's condition to always evaluate to `undefined` & thus visually hidden text was never set on keyStat tiles with the default text of `Help`

EES-3735 - fix keyStat hiddenText always evaluating to undefined

---

src/explore-education-statistics-common/test/setupGlobals.js
src/explore-education-statistics-frontend/src/modules/table-tool/components/TableToolShare.tsx
src/explore-education-statistics-frontend/src/modules/table-tool/components/__tests__/TableToolShare.test.tsx

The previous method of copying a permalink to the clipboard wasn't great for screen reader users as it read the permalink url as well as the 'Link copied to the clipboard' message (see https://github.com/dfe-analytical-services/explore-education-statistics/pull/3518).
This changes the copy method to use `navigator.clipboard`, instead of having to focus on the url input field, so that only the 'Link copied...' message is announced.

EES-3055 change permalink copy method

---

src/GovUk.Education.ExploreEducationStatistics.Admin/Startup.cs

This PR is a bugfix for https://github.com/dfe-analytical-services/explore-education-statistics/pull/3529 which added a new BAU endpoint in Admin to initiate the migration of high-level information about permalinks from the public storage account to the database.
It does this using Publisher functions and the migration is initiated by queuing a message from Admin to Publisher.
There was a bug where the Admin service which initiates it was depending on the default `StorageQueueService` which uses the private storage account.
This fix changes it to explicitly use the publisher's storage account.

EES-3751 🐛 Configure PermalinkMigrationService to use publisher's storage account

---

infrastructure/templates/template.json

Rogue comma went missing whilst removing unnecessary elements to ARM template!  Added back in.

EES-3369 - added missing comma to ARM template

---

src/explore-education-statistics-common/src/components/ContentSectionIndex.tsx
src/explore-education-statistics-frontend/src/modules/methodologies/components/MethodologyContentSection.tsx

Makes the content full width in methodology sections when there is no headings index.

EES-3049 fix methodology section content layout

---

infrastructure/parameters/prod.parameters.json

This PR makes an ARM template parameter change to `prod.parameters.json` to increase the capacity of the `statistics` database in the Prod environment from 450Gb to 550Gb.
It follows other changes made recently to the size in https://github.com/dfe-analytical-services/explore-education-statistics/pull/3046 and https://github.com/dfe-analytical-services/explore-education-statistics/pull/3316.

EES-3747 Increase statistics database size in Prod from 450Gb to 550Gb

---

src/explore-education-statistics-frontend/src/components/PageFooter.tsx

Adds a link to the glossary to the footer on the public site.

EES-3738 add glossary to footer links

---

src/explore-education-statistics-admin/src/pages/admin-dashboard/components/DraftReleaseRow.tsx
src/explore-education-statistics-admin/src/pages/admin-dashboard/components/MethodologySummary.tsx
src/explore-education-statistics-admin/src/pages/admin-dashboard/components/NonScheduledReleaseSummary.tsx
src/explore-education-statistics-admin/src/pages/admin-dashboard/components/__tests__/DraftReleasesTable.test.tsx
src/explore-education-statistics-admin/src/pages/admin-dashboard/components/__tests__/NonScheduledReleaseSummary.test.tsx
src/explore-education-statistics-admin/src/pages/publication/PublicationMethodologiesPage.tsx
src/explore-education-statistics-admin/src/pages/publication/__tests__/PublicationMethodologiesPage.test.tsx
src/explore-education-statistics-admin/src/pages/publication/components/DraftReleaseRow.tsx
src/explore-education-statistics-admin/src/pages/publication/components/__tests__/PublicationDraftReleases.test.tsx
tests/robot-tests/tests/admin/bau/create_methodology_amendment.robot

Change the 'View original' buttons to 'View existing version' for releases and methodologies on
- admin dashboard main tab (current version only, it's not on the new one)
- admin dashboard draft releases tab (current and new versions)
- new Publication - Releases page, https://localhost:5021/publication/id/releases 
- new Publication - Methodologies page, https://localhost:5021/publication/id/methodologies

EES-965 change view original buttons

---

src/GovUk.Education.ExploreEducationStatistics.Admin/appsettings.Development.json

This PR corrects the Admin's local ReleaseApproval environment settings to match the local Publisher's environment  settings.
This fixes a problem in the local environment where it's currently not possible to approve a release scheduled for publishing today, even though the publisher is scheduled every 2 minutes throughout the day.
Previous config: (matches the settings of Pre-prod/Prod where it's not possible to approve on the same day):
```
"ReleaseApproval": {
"PublishReleasesCronSchedule": "0 0 0 * * *",
"PublishReleaseContentCronSchedule": "0 30 9 * * *"
}
```
New config (matching the settings of the local environment where publishing occurs once every two minutes):
```
"ReleaseApproval": {
"PublishReleasesCronSchedule": "0 0-58/2 * * * *",
"PublishReleaseContentCronSchedule": "0 …
```

EES-3774 Correct Admin's local ReleaseApproval env settings to match local Publisher settings

---

src/GovUk.Education.ExploreEducationStatistics.Common/Model/Chart/ChartCustomDataGroup.cs
src/GovUk.Education.ExploreEducationStatistics.Common/Model/Chart/ChartDataClassification.cs
src/GovUk.Education.ExploreEducationStatistics.Common/Model/Chart/Charts.cs
src/explore-education-statistics-admin/src/pages/methodology/edit-methodology/content/components/MethodologyNotesSection.tsx
src/explore-education-statistics-admin/src/pages/release/datablocks/components/chart/ChartBuilder.tsx
src/explore-education-statistics-admin/src/pages/release/datablocks/components/chart/ChartDataSetsConfiguration.tsx
src/explore-education-statistics-admin/src/pages/release/datablocks/components/chart/ChartMapConfiguration.tsx
src/explore-education-statistics-admin/src/pages/release/datablocks/components/chart/ChartMapCustomGroupsConfiguration.tsx
src/explore-education-statistics-admin/src/pages/release/datablocks/components/chart/__tests__/ChartMapConfiguration.test.tsx
src/explore-education-statistics-admin/src/pages/release/datablocks/components/chart/__tests__/ChartMapCustomGroupsConfiguration.test.tsx
src/explore-education-statistics-common/src/modules/charts/components/MapBlock.tsx
src/explore-education-statistics-common/src/modules/charts/components/MapBlockInternal.tsx
src/explore-education-statistics-common/src/modules/charts/components/utils/__tests__/generateLegendDataGroups.test.ts
src/explore-education-statistics-common/src/modules/charts/components/utils/generateLegendDataGroups.ts
src/explore-education-statistics-common/src/modules/charts/types/chart.ts

Allows to create custom data groups for maps.
- I've done the BE part... it seems to work
- groups cannot overlap
- groups don't have to cover the full range of data
- the unit shows if it's set and the datasets don't have different units

EES-3652 custom data groups for maps

---

tests/performance-tests/package.json
tests/performance-tests/src/tests/maintenance/cleanUp.test.ts
tests/performance-tests/src/tests/public/getReleaseApi.test.ts

This PR makes a couple of changes to the clean-up performance test `cleanUp.test.ts` to fix some errors seen when running it locally:
- `The "open()" function is only available in the init stage (i.e. the global scope)` 
- `x509: certificate is valid for localhost, not ees.local`
- Changes the publication slug and release slug used in `getReleaseApi.test.ts` to "Pupil absence in schools in England - 2016/17" which all environments should have.
- Fix `npm stop` command in package.json - `docker-compose down` has no service name or container option.
- Fix `npm stop-and-clear-data` command in package.json - volumes option `-v` needs to be after `docker-compose down`.

EES-3732 Fix clean-up performance test

---

src/docker-compose.yml

This PR: 
* upgrades Azurite version of docker image used in local environments to 3.19.0

EES-3814 - upgrade Azurite docker image to 3.19.0

---

tests/robot-tests/tests/libs/admin-common.robot

This PR: 
- fixes a small failure some people experienced when running the `prerelease.robot` locally in parallel

EES-3501 - fix prerelease.robot test

---

src/GovUk.Education.ExploreEducationStatistics.Content.Model/Database/ContentDbContext.cs

This PR adds config to ContentDbContext to be aligned with the state of our DBs. I created a migration after this change and it was blank.
Ideally, the config wouldn't be `WithMany`, but `WithOne`, as we want Publications and Contacts to have a one-to-one relationship. But currently all environments have contacts that are shared across multiple publications. The time to fix this isn't worth the benefit, so for now I've left it `WithMany`.
Checked for contacts that appear on more than one publication with this query (courtesy of Ben):
```
SELECT ContactId, Count(ContactId) FROM Publications
GROUP BY ContactId
HAVING Count(ContactId) > 1
```

EES-3825 Fix ContentDbContext config for Publications table

---

src/explore-education-statistics-admin/src/pages/release/content/components/ReleasePreviewTableToolFinalStep.tsx
src/explore-education-statistics-admin/src/pages/release/datablocks/components/DataBlockSourceWizard.tsx
src/explore-education-statistics-admin/src/pages/release/datablocks/components/TableTabSection.tsx
src/explore-education-statistics-admin/src/pages/release/pre-release/components/PreReleaseTableToolFinalStep.tsx
src/explore-education-statistics-common/src/components/CollapsibleList.module.scss
src/explore-education-statistics-common/src/modules/find-statistics/components/DataBlockTabs.tsx
src/explore-education-statistics-common/src/modules/table-tool/components/FixedMultiHeaderDataTable.tsx
src/explore-education-statistics-common/src/modules/table-tool/components/TimePeriodDataTable.tsx
src/explore-education-statistics-frontend/src/modules/permalink/PermalinkPage.tsx
src/explore-education-statistics-frontend/src/modules/table-tool/components/TableToolFinalStep.tsx

Fixes a bug where the footnotes for datablocks are only using 2/3’s of the available space in the admin (they're fine on the public site). 
This was due to a style added to restrict the width of footnotes under tables in the table tool / on permalinks that was also affecting all footnotes in the admin.
I've checked that the print style for permalinks is unaffected by this change.

EES-3189 fix footnotes width in admin

---

infrastructure/parameters/prod.parameters.json

This PR makes an ARM template parameter change to `prod.parameters.json` to increase the capacity of the statistics database in the Prod environment from 550Gb to 650Gb.
It follows other changes made recently to the size in https://github.com/dfe-analytical-services/explore-education-statistics/pull/3544, https://github.com/dfe-analytical-services/explore-education-statistics/pull/3046 and https://github.com/dfe-analytical-services/explore-education-statistics/pull/3316.

EES-3845 Increase statistics database size in Prod from 550Gb to 650Gb

---

src/GovUk.Education.ExploreEducationStatistics.Common/Model/Chart/ChartCustomDataGroup.cs
src/explore-education-statistics-admin/src/pages/release/datablocks/components/chart/ChartMapCustomGroupsConfiguration.tsx
src/explore-education-statistics-admin/src/pages/release/datablocks/components/chart/__tests__/ChartMapCustomGroupsConfiguration.test.tsx
src/explore-education-statistics-common/src/modules/charts/components/MapBlockInternal.tsx

Fixes the following issues found by @N-moh during testing:
- group values with decimals were being rounded when the form is saved
- the logic to prevent overlapping groups didn't work for negative values 
- areas that aren't covered by custom groups could be hard to distinguish from those that were as they defaulted to grey which can be indistinguishable from the low end of the legend colour scale, I've changed them to white.

EES-3652 fixes for decimals, negatives and default colour

---

infrastructure/parameters/dev.parameters.json
infrastructure/parameters/pre-prod.parameters.json
infrastructure/parameters/prod.parameters.json
infrastructure/parameters/test.parameters.json
infrastructure/templates/template.json

This PR proposes changes to the app service plans to take advantage of Premium v2 plans which offer better performance for similar prices.
This change is being made now after investigating slow Fast Track pages in [EES-3412](https://dfedigital.atlassian.net/browse/EES-3412) which found that slow requests in the Public app service are not because of slow dependent API requests like getting the fast track table result but because the app service appears to be constrained by available CPU resource.
Looking at the metric of CPU percentage it appears the public app service is regularly hitting 100%, so much so that on a chart of the last 30 days, it looks like a continuous line barely dipping below 100%.
Standard plans are based on A-series compute equivalent VM's which Azure recommend for …

EES-3412 Change app service plans from Standard to Premium V2

---

infrastructure/templates/template.json

After deploying https://github.com/dfe-analytical-services/explore-education-statistics/pull/3590 I noticed that the Notifier service plan has not changed in the Dev environment. The plan was expected to change from S1 to B1.
I notified that it has a different `apiVersion` to the other two function projects.
This PR changes the `apiVersion` of the function apps to all be `2022-03-01`.

🐛 EES-3412 Attempt to get Notifier to use sku config by changing apiVersion

---

infrastructure/parameters/pre-prod.parameters.json
infrastructure/parameters/test.parameters.json

This PR makes some cost saving measures by scaling down the Test environment App Service plans to use B1 in the basic pricing tier intended for Dev/Test workloads.
It also removes autoscaling config from Pre-prod which means the Content, Data, and Public app services have previously been running with a minimum of 2 servers.
We can reverse all these changes if necessary and scale them back up when required.

EES-3412 EES-3850 Scale down Test app services and remove autoscaling config from Pre-pod

---

tests/robot-tests/scripts/run_tests_pipeline.py

This PR: 
* removes all `lib` import references in `run_tests_pipeline.py` in order to avoid `ModuleNotFound` errors. I've purposely not replaced the logging statements with print statements. This is because `run_tests_pipeline.py` is pretty much a fancy wrapper around `run_tests.py` purely for the purpose of running tests in CI and all logging should probably come from within `run_tests.py`. This resolves errors currently occuring in the UI test & snapshot CI jobs

EES-3846 - fix import errors

---

src/GovUk.Education.ExploreEducationStatistics.Content.Model.Tests/Extensions/ReleaseExtensionTests.cs
src/GovUk.Education.ExploreEducationStatistics.Content.Model.Tests/PublicationTests.cs
src/GovUk.Education.ExploreEducationStatistics.Content.Model/Extensions/ReleaseExtensions.cs
src/GovUk.Education.ExploreEducationStatistics.Content.Model/Publication.cs
src/GovUk.Education.ExploreEducationStatistics.Content.Model/Repository/Interfaces/IReleaseRepository.cs
src/GovUk.Education.ExploreEducationStatistics.Content.Model/Repository/ReleaseRepository.cs
src/GovUk.Education.ExploreEducationStatistics.Data.Api.Tests/Controllers/TableBuilderControllerTests.cs
src/GovUk.Education.ExploreEducationStatistics.Data.Api/Controllers/TableBuilderController.cs

This PR fixes a bug where requesting a Fast Track (data block id) that's not for the latest published version of the release returns a 500 error.
This was because the user didn't have permission to view that release when getting the data block table result.
We now check early if the data block is for the latest published version of the release and if not, return not found.

EES-3782 Return not found if Fast Track isn't for latest published version of a release

---

infrastructure/parameters/test.parameters.json

This PR changes the Content, Data and Admin app services to use standard S1 service plan rather than B1 which doesn't support staging slots.
This was discovered after deploying https://github.com/dfe-analytical-services/explore-education-statistics/pull/3594 to Test which resulted in the error `The site(s) ... exceed maximum number of slots allowed for the hosting plan. Remove all deployment slots before scaling to a different mode.`

EES-3412 Change Test env content, data & admin app services to use standard pricing plans

---

src/explore-education-statistics-admin/src/pages/release/datablocks/components/DataBlockPageTabs.tsx

Fixes a bug where changing data block options caused an error because existing datasets used filters that were no longer selected. Invalid datasets were removed from the chart correctly but the table state was updating before the data block which caused the error (if you refreshed the page there was no error).

EES-2073 fix data block update bug

---

src/GovUk.Education.ExploreEducationStatistics.Common/Model/Chart/Charts.cs

A fix to return the data label position from the back end in camelcase. Previously it was capitalised causing the frontend to not match it when populating the position select.
Original PR for reference: https://github.com/dfe-analytical-services/explore-education-statistics/pull/3570

EES-257 lowercase data label position

---

src/explore-education-statistics-common/src/components/Details.tsx
src/explore-education-statistics-common/src/components/__tests__/Details.test.tsx
src/explore-education-statistics-common/src/modules/table-tool/components/FormFieldCheckboxGroupsMenu.tsx
src/explore-education-statistics-common/src/modules/table-tool/components/__tests__/FormFieldCheckboxGroupsMenu.test.tsx

This changes the Details component to work correctly as a React component. Due to a known issue in React this requires preventing the default browser behaviour  so the open state can be controlled. See https://github.com/facebook/react/issues/15486
This fixes a specific bug on the filters step of the table tool where you couldn't open a filter group had an error. 
Also updated the tests to check for the visibility of the content as well as the aria attributes as they were passing incorrectly before.
The expected behaviour when you submit the filters form without selecting filters is:
If the filter group has a total option:
- total is selected
- no error is shown
If the filter group doesn't have a total option:
- an error is shown
- the group is expanded (including if it was closed before …

EES-2867 handle details open state

---

src/explore-education-statistics-admin/src/pages/release/datablocks/components/chart/ChartMapConfiguration.tsx
src/explore-education-statistics-admin/src/pages/release/datablocks/components/chart/__tests__/ChartMapConfiguration.test.tsx

Hide the maps custom data groups option until it can be reimplemented in https://dfedigital.atlassian.net/browse/EES-3858

EES-3869 hide map custom groups option

---

infrastructure/parameters/prod.parameters.json

This PR: 
* Increase the prod statistics DB size by 300GB. I've used the following sum to calculate this: 
```
1073741824 x 300
``` 
References: 
https://learn.microsoft.com/en-us/azure/azure-sql/database/single-database-scale?view=azuresql#vcore-based-purchasing-model

EES-3867 - increase prod stats DB size by 300GB

---

infrastructure/templates/template.json

This removes the previous usage of parameters (`publisherClientId` and `publisherClientSecret`) from DevOps as these are prone to faulty interpolation, and they are less secure than a Key Vault reference.

EES-3871 Inject publisher client id/secret via Key Vault reference

---

src/explore-education-statistics-admin/src/pages/release/datablocks/components/chart/__tests__/ChartLegendConfiguration.test.tsx
src/explore-education-statistics-common/package-lock.json
src/explore-education-statistics-common/package.json
src/explore-education-statistics-common/src/components/form/FormColourInput.module.scss
src/explore-education-statistics-common/src/components/form/FormColourInput.tsx

Replaces the browser colour picker with https://github.com/hello-pangea/color-picker (this is a fork of react-color which is no longer maintained)

EES-3886 new colour picker

---

infrastructure/templates/datafactory/components/db-maintenance-template.json

This PR:
- Changes the timeout of the `pl_rebuild_statistics_indexes` and `pl_rebuild_public_statistics_indexes` pipelines from 4 hours to 12 hours. We've seen the `pl_rebuild_statistics_indexes` pipeline timeout in Dev, Test and Pre-prod after 4 hours and seen the it take 11 hours to run Prod. 
- Schedules the `rebuild_indexes_trigger` to run at 7pm on Saturday instead of 2am on Sunday, to allow it more time to run between 7pm on Saturday and 7am on Sunday when the service should be quieter.
- Schedules the `purge_soft_deleted_subjects_trigger` to run at 7pm on weekdays Monday to Friday instead of 7pm daily so that it's not running at the same time as rebuilding indexes.
- Removes unused parameter `subjectsToMigrate`.

EES-3878 Changes to Azure Data Factory maintenance triggers

---

tests/robot-tests/tests/bootstrap_data/release_and_publication_role_permissions_data.robot

This PR:
* leaves a note in `release_and_publication_role_permissions_data.robot` on how to debug issues with seed data on various environments

EES-3884 - improve documentation on how to seed data in UI tests

---

src/GovUk.Education.ExploreEducationStatistics.Admin/Services/PreReleaseSummaryService.cs
src/GovUk.Education.ExploreEducationStatistics.Admin/ViewModels/PreReleaseSummaryViewModel.cs
src/explore-education-statistics-admin/src/pages/release/pre-release/PreReleasePageContainer.tsx
src/explore-education-statistics-admin/src/pages/release/pre-release/__tests__/PreReleasePageContainer.test.tsx
src/explore-education-statistics-admin/src/services/preReleaseService.ts
src/explore-education-statistics-common/src/components/NotificationBanner.tsx
tests/robot-tests/tests/admin/bau/prerelease.robot

Adds a banner with the team contact name and email to the top of pre-release preview pages.
- I've added the team name to PreReleaseSummary in the backend as it already had the team email so seemed like that would be ok, let me know if not.
- Added a generic notification banner component based on https://design-system.service.gov.uk/components/notification-banner/

EES-3856 contact banner on prerelease

---

tests/robot-tests/tests/admin_and_public/bau/legacy_releases.robot

This PR:
* fixes `legacy_releases` UI test on dev. Legacy releases are memory cached & as such, we should add a `sleep    %{WAIT_MEMORY_CACHE_EXPIRY}` statement in order to wait for a legacy release to be updated on the public frontend

EES-3891 - fix legacy_releases.robot failing on dev

---

src/explore-education-statistics-admin/src/pages/admin-dashboard/AdminDashboardPage.tsx
tests/robot-tests/tests/bootstrap_data/release_and_publication_role_permissions_data.robot
tests/robot-tests/tests/libs/admin-common.robot
tests/robot-tests/tests/libs/admin-utilities.py
tests/robot-tests/tests/libs/bootstrap_data/bootstrap_common.robot

This PR:
* Fixes a UI test that's responsible for seeding test data. This was missed when UI tests were updated across the board as part of the new admin dashboard design
Local:
Dev:

EES-3868 - fix Release And Publication Role Permissions Data seed data UI test

---

src/explore-education-statistics-common/src/modules/charts/components/CustomReferenceLineLabel.tsx

Moves the label on y axis reference lines up a little bit so they don't overlap with the line.
Before:
After:

EES-2946 move y axis ref lines up a tad

---

src/explore-education-statistics-common/src/modules/table-tool/components/WizardStep.module.scss
src/explore-education-statistics-common/src/modules/table-tool/components/WizardStepHeading.module.scss
src/explore-education-statistics-common/src/modules/table-tool/components/WizardStepSummary.module.scss

Adjusts the CSS to not cause the overflow when subject details are expanded in the table tool. The margin that caused the problem was used for spacing on the inactive step headings so I've changed them a bit.
Before: 
After:

EES-3893 fix table tool summary list margin

---

.gitignore
tests/robot-tests/scripts/permalink_snapshots/check_permalinks.py

This PR:
* creates a python script to check whether a permalink can be rendered or not on production. This aids in migrating to [permalink snapshots](https://dfedigital.atlassian.net/browse/EES-3754) 
**Structure**
* Currently the script gets data from a `prod-permalinks.csv` which it assumes already exists and is filled with permalinks via running the query included in `check_permalinks.py` 
* The script then outputs new permalink IDs into `checked-permalinks.csv` to ensure work is not repeated and it only checks permalinks that haven't already been tested 
* Any invalid permalinks that couldn't load or have error text (i.e. `There was a problem rendering the table.`) present are placed in `invalid-permalinks.csv` which stores the following details about the permalink that couldn't …

EES-3784 - create permalink checker script

---

tests/robot-tests/scripts/permalink_snapshots/check_permalinks.py

This PR: 
* fixes an index exception from being thrown when a 404 or 500 page gets found when checking permalinks with the permalink checker script. I encountered this error and it seems the script exited as soon as this uncaught exception was thrown.

EES-3784-2 account for 404 or 500 error pages in permalink checker

---

src/GovUk.Education.ExploreEducationStatistics.Admin/Migrations/ContentMigrations/20221108181115_EES3882_AddLatestPublishedReleaseIdToPublication.Designer.cs
src/GovUk.Education.ExploreEducationStatistics.Admin/Migrations/ContentMigrations/20221108181115_EES3882_AddLatestPublishedReleaseIdToPublication.cs
src/GovUk.Education.ExploreEducationStatistics.Content.Model/Database/ContentDbContext.cs
src/GovUk.Education.ExploreEducationStatistics.Content.Model/Publication.cs

This PR:
- Adds `Publication.LatestPublishedReleaseId` and `Publication.LatestPublishedReleaseNew`.
- Adds  and an optional one-to-one relationship between `Publication.LatestPublishedReleaseNew` and `Release`.
There will be a separate PR raised to add a migration that will set `Publication.LatestPublishedReleaseId` for all publications,
and make a change to Publisher to set `Publication.LatestPublishedReleaseId` when a release is published if applicable.
`LatestPublishedReleaseNew` will be renamed later to `LatestPublishedRelease`.

EES-3882 Introduce Publication.LatestPublishedReleaseId

---

src/explore-education-statistics-admin/src/pages/release/datablocks/components/chart/ChartLegendConfiguration.module.scss
src/explore-education-statistics-admin/src/pages/release/datablocks/components/chart/ChartLegendConfiguration.tsx
src/explore-education-statistics-common/src/styles/_all.scss
src/explore-education-statistics-common/src/styles/utils/_overflow.scss

Fixes a bug where the legend label was unusable on small screens. Also, adds `overflow-x: auto` to the container so you can scroll across the list more easily on small screens.
**Before:**
**After:**

EES-3785 fix legend label on small screens

---

src/GovUk.Education.ExploreEducationStatistics.Admin.Tests/Services/DataBlockServicePermissionTests.cs
src/GovUk.Education.ExploreEducationStatistics.Admin.Tests/Services/PreReleaseUserServicePermissionTests.cs
src/GovUk.Education.ExploreEducationStatistics.Admin.Tests/Services/PublicationServicePermissionTests.cs
src/GovUk.Education.ExploreEducationStatistics.Common/Model/SortOrder.cs
src/GovUk.Education.ExploreEducationStatistics.Content.Api.Tests/Controllers/PublicationControllerTests.cs
src/GovUk.Education.ExploreEducationStatistics.Content.Api/Controllers/PublicationController.cs
src/GovUk.Education.ExploreEducationStatistics.Content.Api/Requests/PublicationsListRequest.cs
src/GovUk.Education.ExploreEducationStatistics.Content.Model/Database/ContentDbContext.cs
src/GovUk.Education.ExploreEducationStatistics.Content.Services.Tests/GovUk.Education.ExploreEducationStatistics.Content.Services.Tests.csproj
src/GovUk.Education.ExploreEducationStatistics.Content.Services.Tests/PublicationServiceTests.cs
src/GovUk.Education.ExploreEducationStatistics.Content.Services/Interfaces/IPublicationService.cs
src/GovUk.Education.ExploreEducationStatistics.Content.Services/PublicationService.cs
src/GovUk.Education.ExploreEducationStatistics.Content.Services/ViewModels/PublicationSearchResultViewModel.cs
src/GovUk.Education.ExploreEducationStatistics.Data.Api.Tests/Services/PermalinkServiceTests.cs
src/GovUk.Education.ExploreEducationStatistics.Publisher.Tests/Services/PermalinkMigrationServiceTests.cs
src/GovUk.Education.ExploreEducationStatistics.Publisher.Tests/Services/ReleaseServiceTests.cs

⚠️ This PR depends on [EES-3882](https://dfedigital.atlassian.net/browse/EES-3882) added by https://github.com/dfe-analytical-services/explore-education-statistics/pull/3631. Technically it doesn't need the associated migration described by [EES-3894](https://dfedigital.atlassian.net/browse/EES-3894) to be run before it's merged, but it won't consider any existing publications as published and return them without it. With this being a brand new API endpoint awaiting front-end development, this probably isn't an issue.
This PR adds a new Content API endpoint that can be used to get published publications for the new Find Statistics page described by [EES-3517](https://dfedigital.atlassian.net/browse/EES-3517).
It uses query parameters to allow controlling filtering, a free-text search, …

EES-3605 Add API endpoint to get publications for the new Find Statistics page

---

src/GovUk.Education.ExploreEducationStatistics.Admin.Tests/Services/PublicationMigrationServicePermissionTests.cs
src/GovUk.Education.ExploreEducationStatistics.Admin.Tests/Services/PublicationMigrationServiceTests.cs
src/GovUk.Education.ExploreEducationStatistics.Admin/Controllers/Api/Bau/PublicationMigrationController.cs
src/GovUk.Education.ExploreEducationStatistics.Admin/Services/Interfaces/IPublicationMigrationService.cs
src/GovUk.Education.ExploreEducationStatistics.Admin/Services/PublicationMigrationService.cs
src/GovUk.Education.ExploreEducationStatistics.Admin/Startup.cs
src/GovUk.Education.ExploreEducationStatistics.Publisher.Tests/Services/PublicationServiceTests.cs
src/GovUk.Education.ExploreEducationStatistics.Publisher/Functions/PublishReleaseContentFunction.cs
src/GovUk.Education.ExploreEducationStatistics.Publisher/Functions/PublishStagedReleaseContentFunction.cs
src/GovUk.Education.ExploreEducationStatistics.Publisher/Services/Interfaces/IPublicationService.cs
src/GovUk.Education.ExploreEducationStatistics.Publisher/Services/PublicationService.cs

⚠️ This has faffy deploy ticket [EES-3894](https://dfedigital.atlassian.net/browse/EES-3894) associated with running the migration.
This PR:
- Adds a migration endpoint that will set `Publication.LatestPublishedReleaseId` for all publications.
- Makes a change to Publisher to update `Publication.LatestPublishedReleaseId` for all publications affected when publishing one or more releases.
Once the migration is run and the new field is set, we can get rid of the computed method `Publication.LatestPublishedRelease()`. This change has already been prepared by https://github.com/dfe-analytical-services/explore-education-statistics/pull/3633.
LatestPublishedRelease() which looks like this, had two problems:
```
public Release? LatestPublishedRelease()
{
return Releases …
```

EES-3882 migration to set Publication.LatestPublishedReleaseId and change Publisher to set it for all publications affected when publishing

---

src/GovUk.Education.ExploreEducationStatistics.Content.Services.Tests/PublicationServiceTests.cs
src/GovUk.Education.ExploreEducationStatistics.Content.Services/PublicationService.cs
src/GovUk.Education.ExploreEducationStatistics.Content.Services/ViewModels/PublicationSearchResultViewModel.cs

This PR updates the Content API  `PublicationController.ListPublications` to return publication `Slug` in the response.
It's required so that we can link to publications from results in the Find Statistics page.

EES-3921 Update PublicationController.ListPublications to return publication Slug in response

---

tests/robot-tests/tests/admin/bau/release_content_authoring.robot
tests/robot-tests/tests/libs/admin-common.robot
tests/robot-tests/tests/libs/admin/manage-content-common.robot

This PR:
* Alters release_content_authoring to prevent flakiness when testing in a CI environment against dev

EES-3910 - reduce flakiness in release_content_authoring test

---

src/explore-education-statistics-admin/src/pages/methodology/edit-methodology/content/components/MethodologyAccordionSection.tsx
src/explore-education-statistics-common/src/components/Accordion.tsx
src/explore-education-statistics-common/src/components/AccordionSection.tsx
src/explore-education-statistics-common/src/components/CopyLinkButton.tsx
src/explore-education-statistics-common/src/components/__tests__/AccordionSection.test.tsx
src/explore-education-statistics-common/src/components/__tests__/__snapshots__/AccordionSection.test.tsx.snap
src/explore-education-statistics-frontend/src/modules/methodologies/MethodologyPage.tsx
tests/robot-tests/tests/admin_and_public/bau/publish_methodology.robot

This PR:
- replaces any methodology/accordion section IDs that start with a number at the start with `section-` which causes this error. This resolves an error whereby methodology URLs with a hash (linking to accordion content) wouldn't open
```
DOMException: Failed to execute 'querySelector' on 'Element': '#6.test-title' is not a valid selector.
```

EES-3877 - fix bad methodology ids being generated in Accordion sections

---

infrastructure/templates/template.json
src/GovUk.Education.ExploreEducationStatistics.Admin.Tests/Services/EmailTemplateServiceTests.cs
src/GovUk.Education.ExploreEducationStatistics.Admin.Tests/Services/ReleaseApprovalServiceTests.cs
src/GovUk.Education.ExploreEducationStatistics.Admin/Migrations/ContentMigrations/20221125141506_EES3908RemoveNotifyReleaseApproversFromReleaseStatus.Designer.cs
src/GovUk.Education.ExploreEducationStatistics.Admin/Migrations/ContentMigrations/20221125141506_EES3908RemoveNotifyReleaseApproversFromReleaseStatus.cs
src/GovUk.Education.ExploreEducationStatistics.Admin/Services/EmailTemplateService.cs
src/GovUk.Education.ExploreEducationStatistics.Admin/Services/Interfaces/IEmailTemplateService.cs
src/GovUk.Education.ExploreEducationStatistics.Admin/Services/ReleaseApprovalService.cs
src/GovUk.Education.ExploreEducationStatistics.Admin/Services/UserPublicationRoleRepository.cs
src/GovUk.Education.ExploreEducationStatistics.Admin/appsettings.Development.json
src/GovUk.Education.ExploreEducationStatistics.Content.Model/ReleaseStatus.cs
src/explore-education-statistics-admin/src/pages/release/components/ReleaseStatusForm.tsx
src/explore-education-statistics-admin/src/pages/release/components/__tests__/ReleaseStatusForm.test.tsx
tests/robot-tests/tests/admin/analyst/role_ui_permissions/release_and_publication_role_end_to_end_permissions.robot
tests/robot-tests/tests/admin/bau/release_status.robot
tests/robot-tests/tests/libs/admin-common.robot

This PR:
* Notifies publication owners & publication release approvers when a release is moved into higher review. Previously, only release approvers were notified however it turned out that the intention behind this work was to notify both publication owners/releaseApprovers and release approvers

EES-3908 - notify approvers

---

src/explore-education-statistics-admin/src/pages/methodology/edit-methodology/content/components/MethodologyAccordion.tsx
src/explore-education-statistics-admin/src/pages/methodology/edit-methodology/content/components/MethodologyAccordionSection.tsx

This PR:
* fixes incorrect methodology IDs from being generated on the admin side when copying methodology accordion content sections. This resulted in copied links not working on the public frontend due to the dynamically generated IDs not matching what is applied to methodology accordions on the public frontend

    EES-3877-2 - fix methodology content linking

---

src/explore-education-statistics-common/src/services/publicationService.ts
src/explore-education-statistics-frontend/src/modules/find-statistics/FindStatisticsPage.tsx
src/explore-education-statistics-frontend/src/modules/find-statistics/FindStatisticsPageNew.tsx
src/explore-education-statistics-frontend/src/modules/find-statistics/__tests__/FindStatisticsPageNew.test.tsx
src/explore-education-statistics-frontend/src/modules/find-statistics/__tests__/__data__/testPublications.ts
src/explore-education-statistics-frontend/src/modules/find-statistics/components/PublicationSummary.tsx
src/explore-education-statistics-frontend/src/modules/find-statistics/components/SortControls.tsx
src/explore-education-statistics-frontend/src/modules/find-statistics/components/__tests__/PublicationSummary.test.tsx
src/explore-education-statistics-frontend/src/modules/find-statistics/components/__tests__/SortControls.test.tsx

Hooks up the paginated list and sort controls in the new Find Statistics UI to the new endpoint. See https://github.com/dfe-analytical-services/explore-education-statistics/pull/3459 for the original UI work and https://github.com/dfe-analytical-services/explore-education-statistics/pull/3635 for details of the endpoint.
Legacy release will no longer be shown on this page (they should all have been removed by the time it goes live).
The existing page should not be affected, to see the new one use the newDesign=true query parameter, e.g. http://localhost:3000/find-statistics?newDesign=true
You'll need to have the the latest database (ees-mssql-data-53.zip) locally for the list to be populated.

EES-3668 hook up new find stats paginated list and sorting

---

src/explore-education-statistics-admin/src/pages/methodology/edit-methodology/content/components/MethodologyAccordion.tsx
src/explore-education-statistics-admin/src/pages/methodology/edit-methodology/content/components/MethodologyAccordionSection.tsx
src/explore-education-statistics-common/src/components/AccordionSection.tsx
src/explore-education-statistics-frontend/src/modules/methodologies/MethodologyPage.tsx

Changing the id to not be the section id (with the guid in) was breaking the reordering, so I've reverted that and added and anchorId instead.

EES-3937 fix reordering methodology sections

---

src/explore-education-statistics-common/src/modules/charts/components/HorizontalBarBlock.tsx
src/explore-education-statistics-common/src/modules/charts/components/LineChartBlock.tsx
src/explore-education-statistics-common/src/modules/charts/components/VerticalBarBlock.tsx
src/explore-education-statistics-common/src/modules/charts/components/__tests__/LineChartBlock.test.tsx
src/explore-education-statistics-common/src/modules/charts/util/__tests__/domainTicks.test.ts
src/explore-education-statistics-common/src/modules/charts/util/domainTicks.ts

Fixes the following problems for charts with negative values:
- EES-3899 Charts with negative values should have a line at 0 on the minor axis (note that while the line now shows at 0, there won't always be a zero tick point as this depends on how the tick spacing is generated)
- EES-3906 data labels on bar charts positioned 'inside' were on the wrong place 
- negative minimum values in the minor axis domain weren't rounded to 'nice' values like max values are, resulting in non rounded tick points
Before:
Now:

EES-3899 EES-3906 fixes for charts with negative values

---

src/explore-education-statistics-common/src/components/CollapsibleList.tsx
src/explore-education-statistics-common/src/components/FigureFootnotes.tsx
src/explore-education-statistics-common/src/modules/charts/components/__tests__/ChartRenderer.test.tsx
src/explore-education-statistics-common/src/modules/table-tool/components/__tests__/__snapshots__/FiltersForm.test.tsx.snap

Only add a test id on collapsible list if it is specified - fixes UI tests related to footnotes.

EES-3993 fix ui tests

---

src/GovUk.Education.ExploreEducationStatistics.Content.Api.Tests/Controllers/ThemeControllerTests.cs
src/GovUk.Education.ExploreEducationStatistics.Content.Api/Controllers/ThemeController.cs
src/GovUk.Education.ExploreEducationStatistics.Content.Api/Startup.cs
src/GovUk.Education.ExploreEducationStatistics.Content.Services.Tests/Cache/PublicationCacheServiceTests.cs
src/GovUk.Education.ExploreEducationStatistics.Content.Services.Tests/PublicationServiceTests.cs
src/GovUk.Education.ExploreEducationStatistics.Content.Services.Tests/ThemeServiceTests.cs
src/GovUk.Education.ExploreEducationStatistics.Content.Services/Interfaces/IThemeService.cs
src/GovUk.Education.ExploreEducationStatistics.Content.Services/PublicationService.cs
src/GovUk.Education.ExploreEducationStatistics.Content.Services/ThemeService.cs
src/GovUk.Education.ExploreEducationStatistics.Content.Services/ViewModels/ThemeViewModel.cs

⚠️ Depends on https://github.com/dfe-analytical-services/explore-education-statistics/pull/3679 ⚠️ 
This PR adds a new Content API endpoint to get the list of all public themes.
It's required for the upcoming work in [EES-3610](https://dfedigital.atlassian.net/browse/EES-3610) which will add filtering by theme to the new Find Statistics page.
Themes are considered public if they have any publications which have published releases and are not superseded. Themes are ordered alphabetically by title.
`GET https://{contentApiUrl}/api/themes`
Example response:
```
[
{
"id": "ee1855ca-d1e1-4f04-a795-cbd61d326a1f",
"slug": "pupils-and-schools",
"title": "Pupils and schools",
"summary": "Including absence, application and offers, capacity exclusion and special educational needs (SEN) statistics" …
```

EES-3883 Add new endpoint to get all public themes for Find Statistics

---

src/GovUk.Education.ExploreEducationStatistics.Publisher/Functions/PublishStagedReleaseContentFunction.cs
src/GovUk.Education.ExploreEducationStatistics.Publisher/Services/ReleaseService.cs

This fixes a bug on publishing multiple scheduled releases at the same time.
Also fixed a separate piece of code in `ReleaseService` which could potentially cause the same issue.

EES-3942 Call ToList before ToAsyncEnumerable

---

src/explore-education-statistics-common/src/components/SearchIcon.tsx
src/explore-education-statistics-common/src/components/form/FormBaseInput.tsx
src/explore-education-statistics-common/src/components/form/FormLabel.tsx
src/explore-education-statistics-common/src/components/form/__tests__/FormBaseInput.test.tsx
src/explore-education-statistics-common/src/components/form/__tests__/__snapshots__/FormBaseInput.test.tsx.snap
src/explore-education-statistics-common/src/components/form/__tests__/__snapshots__/FormCheckboxSearchGroup.test.tsx.snap
src/explore-education-statistics-common/src/components/form/__tests__/__snapshots__/FormCheckboxSearchSubGroups.test.tsx.snap
src/explore-education-statistics-common/src/components/form/__tests__/__snapshots__/FormFieldDateInput.test.tsx.snap
src/explore-education-statistics-common/src/components/form/__tests__/__snapshots__/FormNumberInput.test.tsx.snap
src/explore-education-statistics-common/src/components/form/__tests__/__snapshots__/FormRadioSearchGroup.test.tsx.snap
src/explore-education-statistics-common/src/components/form/__tests__/__snapshots__/FormTextSearchInput.test.tsx.snap
src/explore-education-statistics-common/src/modules/table-tool/components/__tests__/__snapshots__/FormFieldCheckboxGroupsMenu.test.tsx.snap
src/explore-education-statistics-common/src/services/publicationService.ts
src/explore-education-statistics-frontend/src/modules/find-statistics/FindStatisticsPage.tsx
src/explore-education-statistics-frontend/src/modules/find-statistics/FindStatisticsPageNew.tsx
src/explore-education-statistics-frontend/src/modules/find-statistics/__tests__/FindStatisticsPageNew.test.tsx
src/explore-education-statistics-frontend/src/modules/find-statistics/components/FilterClearButton.module.scss
src/explore-education-statistics-frontend/src/modules/find-statistics/components/FilterClearButton.tsx
src/explore-education-statistics-frontend/src/modules/find-statistics/components/SearchForm.module.scss
src/explore-education-statistics-frontend/src/modules/find-statistics/components/SearchForm.tsx
src/explore-education-statistics-frontend/src/modules/find-statistics/components/SortControls.tsx
src/explore-education-statistics-frontend/src/modules/find-statistics/components/__tests__/SearchForm.test.tsx
src/explore-education-statistics-frontend/src/modules/find-statistics/components/__tests__/SortControls.test.tsx

Adds search to the new Find Statistics page:
- minimum 3 characters for the search term
- the URL query params are updated to include the search term
- the search can be removed by clicking the tag style button above the search results
- a clear all filters button has been added
- shows a message if there are no search results (I've copied this from the gov.uk search message)
- when searching an extra sort option 'Relevance' is added and selected

EES-3609 find stats search

---

src/explore-education-statistics-admin/src/pages/release/datablocks/components/chart/ChartAxisConfiguration.tsx
src/explore-education-statistics-admin/src/pages/release/datablocks/components/chart/ChartReferenceLinesConfiguration.tsx
src/explore-education-statistics-admin/src/pages/release/datablocks/components/chart/__tests__/ChartReferenceLinesConfiguration.test.tsx
src/explore-education-statistics-common/src/modules/charts/components/CustomReferenceLineLabel.tsx

Fixes a bug where reference lines on charts didn't show if you grouped the major axis by location. This was caused by the chart data using the location filter id and the reference lines using the filter value, meaning that they didn't match up. I've updated it to use the id for the lines.
Also, I fixed a typo in CustomReferenceLineLabel which caused the other axis position on major axis lines not to work (they would always be in the middle not matter what value you put for the other axis position).

EES-3904 fix ref lines on charts grouped by location

---

src/explore-education-statistics-common/src/modules/charts/components/HorizontalBarBlock.tsx
src/explore-education-statistics-common/src/modules/charts/components/VerticalBarBlock.tsx

Fixes the position of data labels on bar charts. I think maybe the recharts upgrade changed something here as the custom functions for position and offset are no longer needed.
Horizontal bar chart - data labels `inside`
Horizontal bar chart - data labels `outside`
Vertical bar chart - data labels `inside`
Horizontal bar chart - data labels `outside`

EES-3906 fix bar chart data label position

---

tests/robot-tests/run_tests.py
tests/robot-tests/scripts/run_tests_pipeline.py

This PR allows the ExpiredInvite user password to be passed to UI test run scripts such that it can be accessed during CI pipeline runs.
I've also updated the various password options in `run_tests_pipeline.py` so that they're consistent with `run_tests.py` - so `--admin-password` is now `--admin-pass`

EES-3947 Add expiredinvite user to UI test run scripts

---

src/GovUk.Education.ExploreEducationStatistics.Common/GovUk.Education.ExploreEducationStatistics.Common.csproj
src/GovUk.Education.ExploreEducationStatistics.Data.Model/GovUk.Education.ExploreEducationStatistics.Data.Model.csproj
src/GovUk.Education.ExploreEducationStatistics.Data.Processor/GovUk.Education.ExploreEducationStatistics.Data.Processor.csproj
src/GovUk.Education.ExploreEducationStatistics.Data.Services/GovUk.Education.ExploreEducationStatistics.Data.Services.csproj
src/GovUk.Education.ExploreEducationStatistics.Publisher/GovUk.Education.ExploreEducationStatistics.Publisher.csproj

This PR bumps Newtonsoft.Json from 12.0.3 to 13.0.2, replacing dependabot PR's https://github.com/dfe-analytical-services/explore-education-statistics/pull/3698, https://github.com/dfe-analytical-services/explore-education-statistics/pull/3700, https://github.com/dfe-analytical-services/explore-education-statistics/pull/3701, https://github.com/dfe-analytical-services/explore-education-statistics/pull/3702 and https://github.com/dfe-analytical-services/explore-education-statistics/pull/3703 which failed to build.

Bump Newtonsoft.Json from 12.0.3 to 13.0.2

---

infrastructure/templates/datafactory/components/template.json
src/GovUk.Education.ExploreEducationStatistics.Admin.Tests/Services/FootnoteServicePermissionTests.cs
src/GovUk.Education.ExploreEducationStatistics.Admin.Tests/Services/FootnoteServiceTests.cs
src/GovUk.Education.ExploreEducationStatistics.Admin/Controllers/Api/Statistics/FootnoteController.cs
src/GovUk.Education.ExploreEducationStatistics.Admin/Requests/FootnotesUpdateRequest.cs
src/GovUk.Education.ExploreEducationStatistics.Admin/Services/FootnoteService.cs
src/GovUk.Education.ExploreEducationStatistics.Admin/Services/Interfaces/IFootnoteService.cs
src/GovUk.Education.ExploreEducationStatistics.Admin/Validators/ValidationErrorMessages.cs
src/GovUk.Education.ExploreEducationStatistics.Data.Model.Tests/Repository/FootnoteRepositoryTests.cs
src/GovUk.Education.ExploreEducationStatistics.Data.Model/Footnote.cs
src/GovUk.Education.ExploreEducationStatistics.Data.Model/Migrations/20221214113713_EES167_AddFootnotesCreatedUpdatedAndOrder.Designer.cs
src/GovUk.Education.ExploreEducationStatistics.Data.Model/Migrations/20221214113713_EES167_AddFootnotesCreatedUpdatedAndOrder.cs
src/GovUk.Education.ExploreEducationStatistics.Data.Model/Repository/FootnoteRepository.cs
src/GovUk.Education.ExploreEducationStatistics.Data.Model/Repository/Interfaces/IFootnoteRepository.cs
src/GovUk.Education.ExploreEducationStatistics.Data.Services.Tests/DataGuidanceSubjectServiceTests.cs

⚠️ Depends on the existing footnotes tidy-up issue [EES-3951](https://dfedigital.atlassian.net/browse/EES-3951) in PR https://github.com/dfe-analytical-services/explore-education-statistics/pull/3705
This PR makes a back-end change adding the ability to order footnotes so that analysts can order them by their importance.
- All existing footnotes will all be assigned a default order value of 0.
- The first new footnote created for a release will be assigned order value of 0.
- Creating a further footnote will be assigned the next order value in sequence of all footnotes on the release.
- Deleting a footnote from a release will decrement the order by 1 of all footnotes with a greater order than the one being deleted.
- Updating a footnote retains existing order.
- Copying footnotes when …

EES-167 Add ability to order footnotes (back-end)

---

src/explore-education-statistics-admin/src/pages/release/content/components/ReleaseContentAccordionSection.tsx
src/explore-education-statistics-admin/src/pages/release/content/components/__tests__/ReleaseContentAccordionSection.test.tsx
src/explore-education-statistics-common/src/modules/find-statistics/components/EmbedBlock.tsx
tests/robot-tests/tests/admin_and_public_2/bau/publish_release_and_amend.robot

Reinstates Embed blocks and removes the flaky custom error handling. 
Now if a dashboard errors:
- if it 404's it'll show a small white space (about 150px high)
- show the Shiny apps error message for other errors, Cam's going to look into making these nicer.

EES-3682 reinstate embed blocks and remove custom error handling

---

src/explore-education-statistics-common/src/modules/charts/components/MapBlockInternal.tsx
src/explore-education-statistics-common/src/modules/charts/components/__tests__/MapBlockInternal.test.tsx
src/explore-education-statistics-common/src/modules/charts/components/utils/__tests__/generateLegendDataGroups.test.ts
src/explore-education-statistics-common/src/modules/charts/components/utils/generateLegendDataGroups.ts

Fixes a bug with maps where some areas weren't been given a colour. This due to the raw values being compared to the rounded values in the data groups, so not matching up correctly.
**Before:**
**After:**

EES-3900 fix map bug where areas not getting correct colour

---

src/explore-education-statistics-common/src/components/Pagination.tsx

This PR:
* adds test IDs to various pagination components to support the refresh of the find statistics snapshot tests

EES-3965 - add test id to publication summary

---

src/explore-education-statistics-common/src/components/Pagination.tsx

This PR: 
* Fixes test IDs not being applied to frontend pagination components (in order to aid in the find-stats snapshot script refresh)

EES-3965 - fix test-ids being applied to pagination components

---

src/explore-education-statistics-frontend/src/modules/find-statistics/FindStatisticsPageNew.tsx

This PR:
* Adds a test ID to the total results heading on the new find statistics page. This is to support the refresh of the find statistics snapshot script

EES-3965 - add testid to total results

---

tests/robot-tests/tests/snapshots/data_catalogue_snapshot.json
tests/robot-tests/tests/snapshots/find_stats_snapshot.json
tests/robot-tests/tests/snapshots/table_tool_snapshot.json

It seems like the snapshots diverged from the Prod service on 15th December when a number of releases went live but the differences have not been caught (we haven't been alerted to them).
**Early Years / Early Years Survery / Childcare and early years provider survey**
According to the snapshot it's in legacy Publication type "Not yet on this service", but looking at the Prod service we see it's not (its first release was published 15 December 2022):
**Higher education / Higher education graduate employment and earnings**
According to the snapshot it should have publications Graduate outcomes (LEO) and Graduate outcomes (LEO): postgraduate outcomes which are not appearing on the Prod service.
**COVID-19 / Children's …

Public snapshot changes

---

src/GovUk.Education.ExploreEducationStatistics.Admin.Tests/Services/FootnoteServiceTests.cs
src/GovUk.Education.ExploreEducationStatistics.Admin/Services/FootnoteService.cs
src/GovUk.Education.ExploreEducationStatistics.Data.Model.Tests/Repository/ReleaseSubjectRepositoryTests.cs
src/GovUk.Education.ExploreEducationStatistics.Data.Model/Repository/FootnoteRepository.cs
src/GovUk.Education.ExploreEducationStatistics.Data.Model/Repository/Interfaces/IFootnoteRepository.cs
src/GovUk.Education.ExploreEducationStatistics.Data.Model/Repository/ReleaseSubjectRepository.cs

This PR fixes a bug where removing a data file fails to remove links between footnotes of the release and the subject or its filter items/filter groups/filters.
It manifests itself as a publishing failure in the data factory stage of publishing.
See [EES-3966](https://dfedigital.atlassian.net/browse/EES-3966) for the exact steps to reproduce that which involves replacing a file before deleting it.
Even in the local environment or an environment without data factory, the footnote links are still present after deleting a subject, and it doesn't require a data file replacement to observe that at the database level.
This PR also attempts to tidy up the `FootnoteRepository.DeleteFootnote` method which previously had a bit of a nasty signature and in certain cases did not delete the footnote. …

EES-3966 Fix deleting footnotes when removing a subject belonging to previous release versions

---

tests/robot-tests/scripts/run_tests_pipeline.py

This PR:
* Amends `run_tests_pipeline.py` to use `subprocess.check_call` instead of `subprocess.run`. `subprocess.check_call` will raise a `CalledProcessError` exception if the exit code is not `0` which means that when things such as environment variables are missing that `run_tests.py` requires, the CI job will fail & alert us that something needs to be fixed for the snapshot pipeline to run

EES-3968 - fix silent snapshot failures

---

tests/robot-tests/run_tests.py
tests/robot-tests/scripts/create_snapshots_2.py

This PR: 
* updates the snapshot tests to be compatible with the new find stats page 
For now, I've created a new file instead of updating `create_snapshots.py` as the new find stats page isn't deployed to production yet 
Relevant changes:
* Changes the structure of the test into a class-based file 
* Adds support for basic auth

EES-3965 - fix snapshot tests for new find stats page

---

src/GovUk.Education.ExploreEducationStatistics.Admin/Migrations/ContentMigrations/20221221090846_EES3964_DropPublicationLegacyPublicationUrl.Designer.cs
src/GovUk.Education.ExploreEducationStatistics.Admin/Migrations/ContentMigrations/20221221090846_EES3964_DropPublicationLegacyPublicationUrl.cs
src/GovUk.Education.ExploreEducationStatistics.Content.Api.Tests/Controllers/PublicationControllerTests.cs
src/GovUk.Education.ExploreEducationStatistics.Content.Model/Database/ContentDbContext.cs
src/GovUk.Education.ExploreEducationStatistics.Content.Model/Publication.cs
src/GovUk.Education.ExploreEducationStatistics.Content.Services.Tests/Cache/PublicationCacheServiceTests.cs
src/GovUk.Education.ExploreEducationStatistics.Content.Services.Tests/PublicationServiceTests.cs
src/GovUk.Education.ExploreEducationStatistics.Content.Services/Cache/PublicationCacheService.cs
src/GovUk.Education.ExploreEducationStatistics.Content.Services/PublicationService.cs
src/GovUk.Education.ExploreEducationStatistics.Content.Services/Requests/PublicationTreeFilter.cs
src/GovUk.Education.ExploreEducationStatistics.Content.Services/ViewModels/PublicationTreePublicationViewModel.cs
src/explore-education-statistics-common/src/services/publicationService.ts

⚠️Depends on https://github.com/dfe-analytical-services/explore-education-statistics/pull/3723 ⚠️
⚠️ This has faffy deploy ticket https://dfedigital.atlassian.net/browse/EES-3967 ⚠️ 
This PR removes the `FindStatistics` option from `PublicationTreeFilter` which is the type of the `publicationFilter` query parameter in the Content API GET request `/api/publication-tree?publicationFilter=FindStatistics`.
It also removes `Publication.LegacyPublicationUrl` and drops the corresponding database column from the Publications table.
Both of these are no longer relevant after switching to the new Find Statistics page which neither uses the publication 'tree' or displays legacy publications without releases.

EES-3964 BE Tidy up after switching to new Find Statistics page

---

src/explore-education-statistics-admin/package.json
src/explore-education-statistics-admin/src/components/DraggableItem.module.scss
src/explore-education-statistics-admin/src/components/DraggableItem.tsx
src/explore-education-statistics-admin/src/components/DroppableArea.module.scss
src/explore-education-statistics-admin/src/components/DroppableArea.tsx
src/explore-education-statistics-admin/src/components/editable/ReorderableAccordion.module.scss
src/explore-education-statistics-admin/src/components/editable/ReorderableAccordion.tsx
src/explore-education-statistics-admin/src/components/editable/ReorderableAccordionSection.module.scss
src/explore-education-statistics-admin/src/components/editable/ReorderableAccordionSection.tsx
src/explore-education-statistics-admin/src/pages/publication/components/LegacyReleasesTable.module.scss
src/explore-education-statistics-admin/src/pages/publication/components/LegacyReleasesTable.tsx
src/explore-education-statistics-admin/src/pages/release/data/components/ReorderList.module.scss
src/explore-education-statistics-admin/src/pages/release/data/components/ReorderList.tsx
src/explore-education-statistics-admin/src/pages/release/datablocks/components/chart/ChartDataSetsConfiguration.module.scss
src/explore-education-statistics-admin/src/pages/release/datablocks/components/chart/ChartDataSetsConfiguration.tsx
src/explore-education-statistics-admin/src/pages/release/footnotes/ReleaseFootnotesPage.tsx
src/explore-education-statistics-admin/src/pages/release/footnotes/__tests__/ReleaseFootnotesPage.test.tsx
src/explore-education-statistics-admin/src/pages/release/footnotes/components/FootnotesList.tsx
src/explore-education-statistics-admin/src/services/footnoteService.ts
tests/robot-tests/tests/admin_and_public/bau/publish_data.robot

Adds the front end for reordering footnotes.
As part of this I've created some generic components for DroppableArea and DraggableItem so we don't have to duplicate the styles every time we add a new reordering UI. I've used these for footnotes and for the other reordering UI's where it was relatively simple to swap them out:
- filters and indicators
- data files
- data sets for charts
- legacy releases

EES-3914 reorder footnotes

---

src/GovUk.Education.ExploreEducationStatistics.Admin.Tests/Services/DataBlockMigrationServicePermissionTests.cs
src/GovUk.Education.ExploreEducationStatistics.Admin.Tests/Services/PermalinkMigrationServicePermissionTests.cs
src/GovUk.Education.ExploreEducationStatistics.Admin.Tests/Services/PublicationServicePermissionTests.cs
src/GovUk.Education.ExploreEducationStatistics.Admin/Controllers/Api/Security/PermissionsController.cs
src/GovUk.Education.ExploreEducationStatistics.Admin/Security/SecurityPolicies.cs
src/GovUk.Education.ExploreEducationStatistics.Admin/Security/StartupSecurityConfiguration.cs
src/GovUk.Education.ExploreEducationStatistics.Admin/Services/DataBlockMigrationService.cs
src/GovUk.Education.ExploreEducationStatistics.Admin/Services/Interfaces/Security/UserServiceExtensions.cs
src/GovUk.Education.ExploreEducationStatistics.Admin/Services/PermalinkMigrationService.cs
src/GovUk.Education.ExploreEducationStatistics.Admin/Services/PublicationService.cs
src/GovUk.Education.ExploreEducationStatistics.Admin/ViewModels/GlobalPermissionsViewModel.cs
src/explore-education-statistics-admin/src/App.tsx
src/explore-education-statistics-admin/src/components/PageFooter.tsx
src/explore-education-statistics-admin/src/components/PageHeader.tsx
src/explore-education-statistics-admin/src/contexts/AuthContext.tsx
src/explore-education-statistics-admin/src/pages/admin-dashboard/AdminDashboardPage.tsx
src/explore-education-statistics-admin/src/pages/bau/BauDashboardPage.tsx
src/explore-education-statistics-admin/src/pages/release/content/components/ReleaseContentAccordionSection.tsx
src/explore-education-statistics-admin/src/pages/release/content/components/__tests__/ReleaseContentAccordionSection.test.tsx
src/explore-education-statistics-admin/src/routes/administrationRoutes.ts
src/explore-education-statistics-admin/src/services/permissionService.ts

This PR makes the 'Add embed block' button within the admin's content section editor only visible to BAU users. It will be made accessible to all contributors again at a later date.
To restrict visibility of the button it introduces a new front-end and back-end global permission `IsBauUser` which is determined from a new policy of the same name.
* Slight tidy up of  back-end `PermissionsController` - Introduces new record type view model `GlobalPermissionsViewModel`. Constrains all Guid parameter types in api routes. Stops using the controller route `[controller]` and prefixes all routes with `permissions/` instead which isn't susceptible to breaking if the controller class is renamed.
* Removes back-end user extension method `CheckCanRunMigrations` and security policy …

EES-3974 Make 'Add embed block' button only visible to BAU users.

---

src/GovUk.Education.ExploreEducationStatistics.Publisher.Model/ReleasePublishingStatusState.cs
src/GovUk.Education.ExploreEducationStatistics.Publisher/Functions/PublishScheduledReleasesFunction.cs
src/GovUk.Education.ExploreEducationStatistics.Publisher/Functions/StageReleaseContentFunction.cs
src/GovUk.Education.ExploreEducationStatistics.Publisher/Services/Interfaces/IPublishingCompletionService.cs
src/explore-education-statistics-admin/src/services/releaseService.ts

This PR:
- stops the PublishReleaseFilesFunction inadvertently triggering the early completion of Release publishing before the PublishScheduledReleasesFunction has had a chance to successfully unstage the staged content
Prior to this change, at "midnight", the StageScheduledReleasesFunction triggers both the StageReleaseContentFunction and PublishReleaseFilesFunction concurrently for all Releases that are scheduled but not yet published.
The StageReleaseContentFunction marks the "Content" Stage as Complete after content is staged.
The PublishReleaseFilesFunction marks the "Files" Stage as Complete after files are copied.
If the PublishReleaseFilesFunction completes *after* the StageReleaseContentFunction has finished, it calls `_publishingCompletionService.CompletePublishingIfAllPriorStag …

EES-3980 - fixing scheduled Releases not copying staged content consistently

---

tests/robot-tests/tests/admin/bau/themes_and_topics.robot

This PR changes the UI test 'Verify existing theme and topics' in `admin/bau/themes_and_topic.robot` to only depend on the 'Pupils and schools' seed data rather than 'Children, early years and social care'.
'Children, early years and social care' was a legacy publication which is being removed in the non-prod environments as part of EES-3967 after the switchover to the new Find Stats page.
In Prod all existing legacy publications have either already been removed over time or now have EES releases except for a couple waiting to be cleaned up by EES-3967.

EES-3967 Switch UI test 'Verify existing theme and topics' to only depend on 'Pupils and schools'

---

tests/robot-tests/tests/general_public/statistics_page.robot

This PR removes a check in UI test `statistics_page.robot - Filter by theme` on the number of results within the Pupils and schools theme because it's different between environments.

EES-3985 Fix general public Find Statistics UI test

---

src/explore-education-statistics-common/src/components/Pagination.tsx
src/explore-education-statistics-common/src/components/__tests__/Pagination.test.tsx
src/explore-education-statistics-frontend/src/components/Pagination.tsx
src/explore-education-statistics-frontend/src/modules/find-statistics/__tests__/FindStatisticsPage.test.tsx

This PR fixes the failing `FindStatisticsPage` tests in the pipeline. These are being caused by relevant test cases not waiting for the correct text to render in the page.
- Changed the `Pagination` component to provide a `data-testid` (instead of `testId`) in its `renderLink` props. This is to prevent potential future bugs from incorrectly spreading it into `<a>` elements.

EES-3990 Fix failing `FindStatisticsPage` tests

---

src/explore-education-statistics-frontend/src/modules/find-statistics/FindStatisticsPage.tsx
src/explore-education-statistics-frontend/src/modules/find-statistics/__tests__/FindStatisticsPage.test.tsx
tests/robot-tests/tests/general_public/statistics_page.robot

This PR updates the links in the Related Information section of the new Find statistics page to be the same as they were on the old Find statistics page with the exception of adding one new link to the Data catalogue page.
It also adds a UI test for the links.
Before (new page):
Before (old page):
After (new page):

EES-3999 Update 'Related information' links on Find statistics page

---

src/explore-education-statistics-frontend/src/components/Page.tsx
src/explore-education-statistics-frontend/src/modules/find-statistics/FindStatisticsPage.tsx

This PR: 
* adds a notice to the new find statistics page which denotes that the design has changed & prompts the user to provide feedback via the beta survey link

EES-3975 - add notice to new find stats page denoting the page has changed

---

src/explore-education-statistics-frontend/src/modules/find-statistics/components/FilterModals.tsx

This PR updates the release type guidance in the relate type filters modal 'What are release types?' on the Find Statistics page
It changes the order of the release types to reflect their priority
- National statistics
- Official statistics
- Experimental statistics
- Ad hoc statistics
- Management information
Before:
After:

EES-4000 Reorder release types guidance

---

tests/robot-tests/scripts/create_snapshots.py

Small bug fix to correct the total number of pages that the script iterates over on the find statistics page.
It was previously using the `//` to perform floor division, rounding down. This is changed to use `match.ceil` to round up to the nearest whole number.

Fix bug getting the total number of pages on the find statistics page

---

tests/robot-tests/tests/general_public/no_javascript.robot
tests/robot-tests/tests/general_public/notifications_absence.robot
tests/robot-tests/tests/libs/no_javascript.py

This PR:
- Changes `notifications_absence.robot` to navigate direct to the latest Pupil Absence release page before beginning the notificiations tests.
- Changes `no_javascript.robot` to search the Find Statistics page by keywords rather than sorting by "oldest" since the Pupil Absence publication is not guaranteed to be on the first page when sorted by "oldest".
- Changes python function `user_checks_list_contains_publication` to inspect multiple publications rather than expecting the publication to be the first element in the list.

EES-4008 Prod UI test fixes after new Find Statistics page

---

tests/robot-tests/scripts/create_snapshots.py

This PR makes two improvements to the snapshot script:
* Adds option to run in `headed` mode (for debugging locally)
* Adds additional logging to methodology, table tool & data catalogue methods to make it clear what snapshot is currently being taken by the script

EES-4010 - make improvements to create snapshots script

---

src/explore-education-statistics-common/src/styles/_content.scss

Tables added in CKEditor could overflow the page on small screens, I've added overflow:auto to their container so that it will scroll instead.
**Before:**
**After:**

EES-3939 add overflow to tables in content

---

tests/robot-tests/tests/snapshots/data_catalogue_snapshot.json
tests/robot-tests/tests/snapshots/methodologies_snapshot.json
tests/robot-tests/tests/snapshots/table_tool_snapshot.json

The pipeline which runs the snapshots and produces Slack notifications has been failing recently but has just been fixed by https://github.com/dfe-analytical-services/explore-education-statistics/pull/3781 so we should be receiving notifications again soon!

Latest snapshots

---

src/GovUk.Education.ExploreEducationStatistics.Common.Tests/Extensions/HttpResponseMessageTestExtensions.cs
src/GovUk.Education.ExploreEducationStatistics.Common.Tests/Extensions/WebApplicationFactoryExtensions.cs
src/GovUk.Education.ExploreEducationStatistics.Common.Tests/Extensions/WebHostBuilderExtensions.cs
src/GovUk.Education.ExploreEducationStatistics.Common/Extensions/HttpClientExtensions.cs
src/GovUk.Education.ExploreEducationStatistics.Common/Extensions/HttpContentExtensions.cs
src/GovUk.Education.ExploreEducationStatistics.Common/Extensions/HttpRequestMessageExtensions.cs
src/GovUk.Education.ExploreEducationStatistics.Common/Model/Data/Query/TimePeriodQuery.cs
src/GovUk.Education.ExploreEducationStatistics.Common/Utils/JsonNetContent.cs
src/GovUk.Education.ExploreEducationStatistics.Content.Api.Tests/Controllers/ReleaseFileControllerTests.cs
src/GovUk.Education.ExploreEducationStatistics.Content.Api.Tests/GovUk.Education.ExploreEducationStatistics.Content.Api.Tests.csproj
src/GovUk.Education.ExploreEducationStatistics.Content.Api.Tests/TestStartup.cs
src/GovUk.Education.ExploreEducationStatistics.Content.Model.Tests/Utils/ContentDbUtils.cs
src/GovUk.Education.ExploreEducationStatistics.Data.Api.Tests/Controllers/TableBuilderControllerTests.cs
src/GovUk.Education.ExploreEducationStatistics.Data.Api.Tests/TestStartup.cs
src/GovUk.Education.ExploreEducationStatistics.Data.Api/ViewModels/TableBuilderQueryViewModel.cs
src/GovUk.Education.ExploreEducationStatistics.Data.Model.Tests/Utils/StatisticsDbUtils.cs
src/GovUk.Education.ExploreEducationStatistics.Data.Model/Database/StatisticsDbContext.cs

This PR updates existing integration testing code to have better ergonomics and be more inline with other unit test code.
The main change is that we can now avoid setup in the integration test class constructor and setup our integration test like we would any other unit test.
> Previously, the pattern was to perform setup in the constructor, including for test data. This isn't great as it's not particularly convenient and doesn't follow typical unit test conventions.
The pattern so far is something like this:
```cs
public TestApplicationFactory<TestStartup> SetupApp(IYourService? yourService = null)
{
return _testApp
.ResetDbContexts()
.ConfigureServices(services => {
services.AddTransient(_ => yourService ?? Mock.Of<IYourService>);
});
}
```
This can then be used in a test like:
```cs …
```

EES-3777 Updates to controller integration tests

---

tests/robot-tests/tests/admin/analyst/edit_and_approve_release_as_publication_release_approver.robot
tests/robot-tests/tests/admin_and_public_2/bau/publish_release_and_amend.robot
tests/robot-tests/tests/libs/admin-common.robot
tests/robot-tests/tests/libs/bootstrap_data/bootstrap_common.robot

This PR fixes failing robot tests in `admin_and_public_2/bau/publish_release_and_amend.robot`.
`publish_release_and_amend` is changed to set new variables `EXPECTED_SCHEDULED_DATE` after scheduling if we need to check the value of the scheduled date after approving, and `EXPECTED_PUBLISHED_DATE` after publishing if we need to check the value of the published date after publishing.
The two dates can be different, i.e. when scheduling publishing a number of days in advance, but then triggering the publishing of that scheduled release immediately.
Expecting them to be the same date was the cause of the test failure.
It also changes the keyword `user approves release for scheduled publication` in `admin-common.robot` to take the publish day/month/year as arguments to make it a little clearer …

EES-3984 Fix failing UI tests

---

tests/robot-tests/tests/admin_and_public/bau/archive_publication.robot

This PR fixes a failing UI test which was failing on 
```
user checks page does not contain    ${PUBLICATION_NAME_ARCHIVE}
```
because it did exist in the page data even though it wasn't visible.
This is fixed by checking the visible publication in the Step 1 summary list is correct
```
user checks summary list contains    Publication    ${PUBLICATION_NAME_SUPERSEDE}
```
I've also removed
```
user checks page for details dropdown    ${PUBLICATION_NAME_ARCHIVE}
```
because I can't see the details section which it's intending to check.

EES-3960 Fix UI test related to checking archived publication warning

---

src/GovUk.Education.ExploreEducationStatistics.Admin.Tests/Services/ReleaseServiceTests.cs
src/GovUk.Education.ExploreEducationStatistics.Admin/Services/ReleaseService.cs
src/GovUk.Education.ExploreEducationStatistics.Common.Tests/Extensions/EitherTaskExtensionsTests.cs
src/GovUk.Education.ExploreEducationStatistics.Common/Extensions/EitherTaskExtensions.cs
src/GovUk.Education.ExploreEducationStatistics.Content.Model/Repository/ReleaseRepository.cs
src/GovUk.Education.ExploreEducationStatistics.Data.Api.Tests/Services/PermalinkServiceTests.cs
src/GovUk.Education.ExploreEducationStatistics.Data.Api/Services/PermalinkService.cs
src/GovUk.Education.ExploreEducationStatistics.Data.Model.Tests/Repository/SubjectRepositoryTests.cs
src/GovUk.Education.ExploreEducationStatistics.Data.Model/Repository/Interfaces/ISubjectRepository.cs
src/GovUk.Education.ExploreEducationStatistics.Data.Model/Repository/SubjectRepository.cs
src/GovUk.Education.ExploreEducationStatistics.Data.Services.Tests/ResultSubjectMetaServiceTests.cs
src/GovUk.Education.ExploreEducationStatistics.Data.Services.Tests/TableBuilderServicePermissionTests.cs
src/GovUk.Education.ExploreEducationStatistics.Data.Services.Tests/TableBuilderServiceTests.cs
src/GovUk.Education.ExploreEducationStatistics.Data.Services/ResultSubjectMetaService.cs
src/GovUk.Education.ExploreEducationStatistics.Data.Services/TableBuilderService.cs

This PR performs various cleanup around the data API to prevent errors being thrown if the latest release or subject can't be found (resulting in a 500). Instead, we now correctly return a 404 response instead.
One notable change here is the addition of a new `OrNotFound` extension method for `EitherTasks`. This allows us to conveniently return a `NotFoundResult` (i.e. 404) for tasks that have a nullable result (e.g. `Task<T?>`).
Usage is simply:
```cs
return await someService.SomeNullableResult()
.OrNotFound() // Return a 404 if null
.OnSuccess(...); // Do something else if not null
```
The main benefit to this extension is that we can use this to wrap many repository methods that return `Task<T?>`. We no longer need to adapt these methods to use eithers (e.g. `Task<Either<ActionResult, …

EES-4015 Cleanup fetching latest release/subjects in data API

---

src/explore-education-statistics-admin/src/pages/users/components/PublicationAccessForm.tsx
src/explore-education-statistics-admin/src/pages/users/components/ReleaseAccessForm.tsx
tests/robot-tests/tests/admin/analyst/invite_contributor_as_publication_owner.robot
tests/robot-tests/tests/admin/analyst/role_ui_permissions/release_and_publication_role_end_to_end_permissions.robot
tests/robot-tests/tests/admin/bau/release_content_authoring.robot
tests/robot-tests/tests/admin_and_public/bau/archive_publication.robot
tests/robot-tests/tests/admin_and_public_2/bau/publish_release_and_amend.robot
tests/robot-tests/tests/bootstrap_data/release_and_publication_role_permissions_data.robot
tests/robot-tests/tests/libs/admin-common.robot
tests/robot-tests/tests/libs/common.robot

This PR experiments with a few changes to see if any fix intermittent UI tests seen when running against the Dev environment
1.  `bau/create_publication_and_release.robot` failing in `Verify new publication has no releases` - `Page should have contained text 'You have no scheduled releases.' but did not`.
2. `admin_and_public_2/bau/publish_release_and_amend.robot` failing in `Change the release type` - `Page should have contained radio button 'xpath://label[text()="Experimental statistics"]/../input[@type="radio"]' but did not.`
3. `/admin/bau/release_content_authoring.robot` failing in `Switch to bau1 to add review comments for first text block` - `Parent ... did not contain 'testid:comment-textarea'`.
4. Multiple occurrences of `StaleElementReferenceException` in …

EES-3977 EES-4034 UI test fixes for running against Dev

---

.gitignore
.npmrc

This PR fixes a problem whereby applicationinsights was being hoisted out of the frontend's relative `node_modules` directory causing the frontend to not start properly in a production setting:
```
Application has thrown an uncaught exception and is terminated:Error: Cannot find module 'diagnostic-channel-publishers'Require stack:- D:\home\site\wwwroot\node_modules\applicationinsights\out\AutoCollection\diagnostic-channel\initialization.js- D:\home\site\wwwroot\node_modules\applicationinsights\out\AutoCollection\CorrelationContextManager.js- D:\home\site\wwwroot\node_modules\applicationinsights\out\applicationinsights.js- D:\home\site\wwwroot\server.js- D:\Program Files\iisnode\interceptor.jsat Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)at …
```

fix(frontend): fix app insights being hoisted

---

src/explore-education-statistics-frontend/src/modules/find-statistics/__tests__/FindStatisticsPage.test.tsx

This also swaps existing `waitFor` calls to use `screen.findByText` instead as this is a little more ergonomic.

test: fix intermittent failures for no matching results on `FindStatisticsPage` suite

---

Pipfile
Pipfile.lock

This PR changes the target Python version in the Pipfile’s `[requires]` section from 3.10.0 to 3.10.
Locally I'm running the latest Python 3.10.9.

Altering Python target version from 3.10.0 to 3.10.

---

src/explore-education-statistics-frontend/src/modules/find-statistics/PublicationReleasePage.tsx
src/explore-education-statistics-frontend/src/modules/find-statistics/__tests__/PublicationReleasePage.test.tsx

Adds the 'This is not the latest data' tag to release pages.

EES-4047 show not latest data tag on release page

---

pnpm-lock.yaml
src/explore-education-statistics-frontend/package.json
src/explore-education-statistics-frontend/server.js

This PR: 
Temporarily removes app insights from the public frontend in order to try to diagnose deployment errors after #3782

EES-3976 - rm app insights in attempt to reproduce deploy errors

---

tests/robot-tests/scripts/create_snapshots.py

This PR fixes the expressions getting the details of each publication for creating/validating the Find Statistics snapshot.
It was incorrectly getting the details from the first publication list item on the page meaning that large parts of the snapshot data are incorrect.
It results in false negative reports that there are no snapshot differences during validation, when there are changes, as seen on 26/01/2023.
Here's an example where release type, published date and theme in the snapshot data are wrong.
Publication data in the snapshot:
Current view of the same publication on the Prod Find Statistics page:

EES-4054 Fix XPath expressions getting publication details when creating the Find Statistics snapshot

---

tests/robot-tests/tests/snapshots/find_statistics_snapshot.json

There are a lot more changes than we would expect if only 5 new releases were published on 26/01/2023.
This is explained by [EES-4054](https://dfedigital.atlassian.net/browse/EES-4054) fixed by https://github.com/dfe-analytical-services/explore-education-statistics/pull/3818 which meant the snapshot data had previously been incorrect.

Latest snapshot changes

---

tests/robot-tests/tests/libs/admin-common.robot

This PR:
- fixes a scenario whereby the saving of an Update note wasn't correctly being waited for
The current problem is that the post-save check is accidentally not relying on any save action, because it's waiting until text which is *already on the page* becomes available.
The fix is to wait for the previously hidden "Add note" button to reappear post-save.

EES-4050 - fixing a condition whereby adding a Methodology Note isn't awaited successfully

---

src/GovUk.Education.ExploreEducationStatistics.Admin.Tests/Controllers/Api/Bau/BauCacheControllerTests.cs
src/GovUk.Education.ExploreEducationStatistics.Admin/Controllers/Api/Bau/BauCacheController.cs
src/GovUk.Education.ExploreEducationStatistics.Common/Services/FileStoragePathUtils.cs

This PR:
- adds a new endpoint to clear down all `publication.json` files in the `public` cache for when the PublicationCacheViewModel becomes incompatible with the cached JSON 
- adds a new endpoint to clear down all `latest-release.json` and `releases/<year-timeidentifier>.json` files together for when the ReleaseCacheViewModel becomes incompatible with the cached JSON
These are requested via:
`DELETE /api/bau/public-cache/publications/publication-json`
and
`DELETE /api/bau/public-cache/publications/release-json`
respectively against the Admin API (with the appropriate Bearer tokens)

Ees 3960 adding cache invalidation for publication and latest release json 2

---

src/GovUk.Education.ExploreEducationStatistics.Admin/Migrations/ContentMigrations/20230202124813_EES4058DropUnusedFieldsAfterEES4056.Designer.cs
src/GovUk.Education.ExploreEducationStatistics.Admin/Migrations/ContentMigrations/20230202124813_EES4058DropUnusedFieldsAfterEES4056.cs
src/GovUk.Education.ExploreEducationStatistics.Content.Model/Publication.cs
src/GovUk.Education.ExploreEducationStatistics.Content.Model/Release.cs
src/GovUk.Education.ExploreEducationStatistics.Content.Model/ReleaseStatus.cs

It's the tidy-up of the tidy-up. 🙂 
[EES-4056](https://dfedigital.atlassian.net/browse/EES-4056) in https://github.com/dfe-analytical-services/explore-education-statistics/pull/3821 removed all usages of four fields:
- `Publication.Published`
- `Release.DataLastPublished`
- `ReleaseStatus.NotifySubscribers`
- `ReleaseStatus.NotifiedOn`
This PR drops them from the content database.
⚠️ Not to be merged until EES-4056 has progressed through all environments.

EES-4058 Drop unused database fields after EES-4056

---

src/GovUk.Education.ExploreEducationStatistics.Admin/Startup.cs
src/GovUk.Education.ExploreEducationStatistics.Common.Tests/Extensions/MockBlobStorageServiceExtensions.cs
src/GovUk.Education.ExploreEducationStatistics.Common.Tests/Services/BlobCacheServiceTests.cs
src/GovUk.Education.ExploreEducationStatistics.Common.Tests/Services/BlobStorageServiceTests.cs
src/GovUk.Education.ExploreEducationStatistics.Common/Services/BlobStorageService.cs
src/GovUk.Education.ExploreEducationStatistics.Common/Services/Interfaces/IBlobStorageService.cs
src/GovUk.Education.ExploreEducationStatistics.Content.Api/Startup.cs
src/GovUk.Education.ExploreEducationStatistics.Content.Model/Services/Interfaces/IReleaseFileBlobService.cs
src/GovUk.Education.ExploreEducationStatistics.Content.Model/Services/PrivateReleaseFileBlobService.cs
src/GovUk.Education.ExploreEducationStatistics.Content.Model/Services/PublicReleaseFileBlobService.cs
src/GovUk.Education.ExploreEducationStatistics.Data.Api/Startup.cs

This PR adds an `IReleaseFileBlobService` that wraps `IBlobStorageService` to provide methods for working with blobs using a `ReleaseFile` entity.
This removes potential errors from incorrectly calling `IBlobStorageService` methods e.g. with the wrong blob container name or calling `Path` instead of `PublicPath`, etc.
Importantly, this is also necessary for EES-3777 to allow us to create a re-usable `SubjectCsvMetaService` that can work in both the data API and the admin.
- Added cancellation token parameters to `DownloadBlobText` and `GetDeserializedJson` methods.

EES-4080 Add `IReleaseFileBlobService` and private/public implementations

---

src/GovUk.Education.ExploreEducationStatistics.Admin.Tests/Services/ReplacementServiceTests.cs
src/GovUk.Education.ExploreEducationStatistics.Admin/Services/ReplacementService.cs
src/GovUk.Education.ExploreEducationStatistics.Data.Services.Tests/ReleaseServiceTests.cs
src/GovUk.Education.ExploreEducationStatistics.Data.Services.Tests/SubjectMetaServiceTests.cs
src/GovUk.Education.ExploreEducationStatistics.Data.Services.Tests/TimePeriodServiceTests.cs
src/GovUk.Education.ExploreEducationStatistics.Data.Services/DataGuidanceSubjectService.cs
src/GovUk.Education.ExploreEducationStatistics.Data.Services/Interfaces/ITimePeriodService.cs
src/GovUk.Education.ExploreEducationStatistics.Data.Services/ReleaseService.cs
src/GovUk.Education.ExploreEducationStatistics.Data.Services/SubjectMetaService.cs
src/GovUk.Education.ExploreEducationStatistics.Data.Services/TimePeriodService.cs

This PR changes `ITimePeriodService` to use async where possible.
It was a change made while investigating [EES-3945](https://dfedigital.atlassian.net/browse/EES-3945), looking at why Step 1 of the table builder can be slow, which I thought is worth raising as it's own PR.
There's some changes to make the code a little more concise:
`GetTimePeriodLabels(Guid subjectId)` is able to reuse `GetTimePeriods(subjectId)`.
`GetTimePeriods(Guid subjectId)` is able to reuse `GetDistinctObservationTimePeriods(IQueryable<Observation> observationsQuery)`.
All the methods which previously had ordering are refactored to use a common `OrderTimePeriods` method.
It also adds a little warning about the reason we order time periods in memory rather than in a database query.
I performance tested this change …

EES-4091 Change `ITimePeriodService` to use async

---

infrastructure/templates/template.json

This PR:
* Adds the PNPM prototype frontend domain to various cors `allowedOrigins` blocks in order for manual, UI & performance testing to take place on the prototype frontend

EES-4081 - add prototype FE cors origin to allowedOrigins

---

infrastructure/parameters/dev.parameters.json

This PR:
* Increases the max table cells allowed on dev in order to support the performance testing of large permalinks for the potential migration to app service containers (see https://dfedigital.atlassian.net/browse/EES-4081)

EES-4119 - increase max table cells on dev

---

src/GovUk.Education.ExploreEducationStatistics.Admin.Tests/Services/KeyStatisticServicePermissionTests.cs
src/GovUk.Education.ExploreEducationStatistics.Admin.Tests/Services/KeyStatisticServiceTests.cs
src/GovUk.Education.ExploreEducationStatistics.Admin/Controllers/Api/KeyStatisticController.cs
src/GovUk.Education.ExploreEducationStatistics.Admin/Mappings/MappingProfiles.cs
src/GovUk.Education.ExploreEducationStatistics.Admin/Requests/KeyStatisticRequests.cs
src/GovUk.Education.ExploreEducationStatistics.Admin/Services/Interfaces/ManageContent/IKeyStatisticService.cs
src/GovUk.Education.ExploreEducationStatistics.Admin/Services/ManageContent/KeyStatisticService.cs

This PR adds to backend endpoint that the frontend will use to create and update free text key stats.
Deleting and reordering key stats is covered by a generic method for all key stat types.

EES-2469 Add backend endpoints to support free text key stats

---

src/GovUk.Education.ExploreEducationStatistics.Admin/Startup.cs
src/GovUk.Education.ExploreEducationStatistics.Data.Api.Tests/Controllers/TableBuilderMetaControllerTests.cs
src/GovUk.Education.ExploreEducationStatistics.Data.Api/Controllers/TableBuilderMetaController.cs
src/GovUk.Education.ExploreEducationStatistics.Data.Api/Startup.cs
src/GovUk.Education.ExploreEducationStatistics.Data.Services.Tests/ReleaseSubjectServiceTests.cs
src/GovUk.Education.ExploreEducationStatistics.Data.Services.Tests/SubjectMetaServicePermissionTests.cs
src/GovUk.Education.ExploreEducationStatistics.Data.Services.Tests/SubjectMetaServiceTests.cs
src/GovUk.Education.ExploreEducationStatistics.Data.Services/Interfaces/IReleaseSubjectService.cs
src/GovUk.Education.ExploreEducationStatistics.Data.Services/Interfaces/ISubjectMetaService.cs
src/GovUk.Education.ExploreEducationStatistics.Data.Services/ReleaseSubjectService.cs
src/GovUk.Education.ExploreEducationStatistics.Data.Services/SubjectMetaService.cs

This PR moves methods relating to `ReleaseSubject` out of `SubjectMetaService` into a separate `ReleaseSubjectService`.
It didn't really make sense for `SubjectMetaService` to contain these methods, which obscures the fact they exist (making them less likely to be reused in other services).
This is a dependency of EES-3777.
- Renamed `CheckReleaseSubjectExists` method to less verbose `Find`
- Renamed `GetReleaseSubjectForLatestPublishedVersion` method to less verbose `FindForLatestPublishedVersion`

EES-4114 Move methods relating to `ReleaseSubject` into `ReleaseSubjectService`

---

src/GovUk.Education.ExploreEducationStatistics.Data.Services/SubjectMetaService.cs

This PR adds a missing import to `SubjectMetaService` for `ComparerUtils`.

EES-3828 Add missing import

---

tests/performance-tests/src/tests/public/fastTrackPage.test.ts
tests/performance-tests/src/tests/public/permalinkPage.test.ts

This PR:
Adds additional public performance tests to support the testing of the migration to PNPM (see https://github.com/dfe-analytical-services/explore-education-statistics/pull/3892).

 EES-4115 - create permalink & fast track performance tests

---

infrastructure/parameters/dev.parameters.json
infrastructure/parameters/pre-prod.parameters.json
infrastructure/parameters/prod.parameters.json
infrastructure/parameters/test.parameters.json
infrastructure/templates/template.json

Changes in this PR:
- Change Dev/Pre-Prod content databases to use DTU purchasing model, capacity 50 DTU's.
- Change Test content database to use DTU purchasing model, capacity 10 DTU's.
- Change Test statistics databases to use DTU purchasing model, capacity 50 DTU's.
- Change Min-max vCores of Dev/Pre-prod statistics databases from 0.75-1 to 0.5-4.
- Reduce Dev statistics database size from 300Gb to 250Gb.
There's a significant annual cost saving to be made just by making these changes to Dev/Test/Pre-prod.
The investigation behind this change considered auto-pause, and swapping away from serverless to use provisioned databases including with reservations. See the writeup [EES-4092](https://dfedigital.atlassian.net/browse/EES-4092).

EES-4092 Scale down Dev/Test/Pre-prod databases

---

tests/robot-tests/scripts/get_auth_tokens.py

This PR removes a leftover comment from the work to enhance the data-catalogue UI tests

EES-4146 - Remove erroneous comment from UI tests

---

infrastructure/templates/template.json

This PR should fix the arm template validation/deployment failure seen in DevOps currently which is caused by https://github.com/dfe-analytical-services/explore-education-statistics/pull/3909 attempting to create optional parameters which default to `null` which is not allowed.
We've run into this issue previously, see attempts in [here](https://github.com/dfe-analytical-services/explore-education-statistics/pull/3446/files) and [here](https://github.com/dfe-analytical-services/explore-education-statistics/pull/3447/files#diff-df68079c12e13e39423a2e795f489815684f257e5c884a2c15f38cde357671e8) and it looks like there's no other way around it as the parameter values are non-nullable. It appears to be impossible to have an optional parameter with a null value.

EES-4092 Fix deployment error caused by null default values

---

tests/robot-tests/tests/admin_and_public/bau/data_catalogue.robot
tests/robot-tests/tests/libs/admin/manage-content-common.robot

Temporarily tag UI tests relying on file downloads as failing.

EES-4147 Tag UI tests as failing

---

infrastructure/templates/template.json

This PR disables auto-pause for databases using vCore serverless settings.
#3915 made a change which mistakenly enabled it, after assuming `autoPauseDelay` has a default value of `-1` which is not the case, see [Microsoft.Sql servers/databases](https://learn.microsoft.com/en-us/azure/templates/microsoft.sql/servers/databases?pivots=deployment-language-arm-template).
Without this alteration auto-pause would be enabled for all databases using vCore serverless config, i.e. the statistics and statistics geo-replica in all environments and the content database in Prod which we don't want right now, especially since auto pausing is not compatible with geo replication.

🐛 EES-4092 Disable auto-pause

---

src/GovUk.Education.ExploreEducationStatistics.Admin/Migrations/ContentMigrations/20230228123640_EES3913RemoveCascadeDeleteOnKeyStatDataBlockTable.Designer.cs
src/GovUk.Education.ExploreEducationStatistics.Admin/Migrations/ContentMigrations/20230228123640_EES3913RemoveCascadeDeleteOnKeyStatDataBlockTable.cs
src/GovUk.Education.ExploreEducationStatistics.Admin/Requests/KeyStatisticRequests.cs
src/GovUk.Education.ExploreEducationStatistics.Admin/Services/DataBlockService.cs
src/GovUk.Education.ExploreEducationStatistics.Content.Model/Database/ContentDbContext.cs
src/GovUk.Education.ExploreEducationStatistics.Content.Model/KeyStatistic.cs
src/explore-education-statistics-admin/src/pages/release/content/components/EditableKeyStatDataBlockForm.tsx
src/explore-education-statistics-admin/src/pages/release/content/components/EditableKeyStatTextForm.tsx
src/explore-education-statistics-admin/src/pages/release/content/components/__tests__/EditableKeyStatText.test.tsx
tests/robot-tests/tests/admin_and_public_2/bau/publish_release_and_amend.robot

This PR makes two changes:
Specifically for the title, statistic, trend, and guidance title field. Lengths have been chosen based on a combination of what is currently the max length in use on production and what fits the UI. These values have been run past Cam.
On the backend, the lengths are stored as consts in the `KeyStatistic` class. This was done because originally we intended add these contraints to the database, which means they were reused more times. This is also why I haven't made a similar change on the frontend - it doesn't seem worth creating a central location for them given they only get used two places at most. But obviously happy to change that if others want that.
Nusrath found a bug where entries from `KeyStatisticsDataBlock` table were being removed without the …

EES-3913 Add input length validation and fix KeyStatisticDataBlock cascade delete bug

---

src/explore-education-statistics-admin/src/pages/release/content/components/ReleaseHelpAndSupportSection.tsx
src/explore-education-statistics-frontend/src/modules/find-statistics/PublicationReleaseHelpAndSupportSection.tsx
src/explore-education-statistics-frontend/src/modules/find-statistics/PublicationReleasePage.tsx
tests/robot-tests/tests/admin/analyst/analyst_absence_permissions.robot
tests/robot-tests/tests/admin_and_public/bau/publish_publication_update.robot
tests/robot-tests/tests/admin_and_public_2/bau/publish_release_and_amend.robot
tests/robot-tests/tests/general_public/release_page_absence.robot

Changes the Help and Support quick link on release pages to link to the Help and Support heading instead of the accordion.

EES-4059 link to help and support heading not accordion

---

infrastructure/parameters/prod.parameters.json

This PR alters the configuration of the Prod serverless content database.
It changes the capacity from 6 vCores to 4 vCores and the minimum capacity from 2 vCores to 0.5 vCores.
We are making this change because we've seen that the database has very low utilisation at the current config.

EES-4156 Alter Prod serverless content db configuration

---

infrastructure/templates/datafactory/components/db-maintenance-template.json

This PR removes pipelines `pl_purge_subjects_public_statistics` and `pl_rebuild_public_statistics_indexes` from Azure Data Factory config in the db-maintenance ARM template.
It also removes linked service `ls_sql_public_statistics` from the same template since it's now unused.

EES-3763 Remove Azure Data Factory config for public statistics database

---

infrastructure/parameters/prod.parameters.json
useful-scripts/get_data_block_responses/get_data_block_responses.py

This PR alters the configuration of the Prod statistics databases to use provisioned rather than serverless compute tier.
The previous configuration was min capacity 4 vCores, scaling up to an overall capacity of 10 vCores.
That meant a minimum of 4 vCores continuously available independent of usage, but a downside of this was cost with the serverless tier being more expensive especially without us taking advantage of auto-pause.
Here we provision 6 vCores to be continuously available, which despite having more resources made continuously available, makes a significant annual cost saving over the previous config using serverless.
The `GP_Gen5_6` provisioned compute option also has 31.1Gb memory continuously available, compared to the `GP_S_Gen5_10` serverless compute option where minimum …

EES-4094 Alter Prod statistics databases to use provisioned rather than serverless compute tier

---

src/GovUk.Education.ExploreEducationStatistics.Admin.Tests/Services/ReleaseApprovalServiceTests.cs
src/GovUk.Education.ExploreEducationStatistics.Admin/Services/PreReleaseService.cs
src/GovUk.Education.ExploreEducationStatistics.Admin/Services/ReleaseApprovalService.cs
src/explore-education-statistics-admin/src/pages/release/content/components/BasicReleaseSummary.tsx

This hotfix PR:
- stops pre-release invite emails from being sent out when a Release is published Immediately
- shows the real Published date on the Release Content (preview) page in Admin if it has already gone live - this is to prevent confusion around Releases that might have had their Published dates manually amended, or for scheduled Releases that have been forced out immediately using the "Immediate" Publisher HTTP function triggers
- adds a guard to prevent access to Pre-release Window if the Release is already live (and its Published date differs from its Publish Scheduled date, as for Releases that might have had their Published dates manually amended, or for scheduled Releases that have been forced out immediately using the "Immediate" Publisher HTTP function triggers)
- Changes …

Ees 4160 stop prerelease emails on immediate publishing

---

infrastructure/parameters/dev.parameters.json

This PR makes an ARM template parameter change to `dev.parameters.json` to increase the capacity of the statistics database in the Dev environment from 250Gb to 350Gb.
It was recently 300Gb but https://github.com/dfe-analytical-services/explore-education-statistics/pull/3909 decided to reduce it down to 250Gb after seeing the allocated space was under 250Gb.
After recent performance testing the space used has now increased and after rebuilding indexes the allocated space is close to 300Gb.

EES-3993 Increase statistics database size in Dev from 250Gb to 350Gb

---

infrastructure/templates/template.json

Add `GP_Gen5` to allowed list of values to allow specifying General Purpose Provisioned Compute tier databases.

🐛 EES-4094 Allow General purpose - provisioned compute

---

infrastructure/parameters/dev.parameters.json
infrastructure/parameters/pre-prod.parameters.json

This PR changes the statistics database and its geo-replica from using the vCore Serverless compute tier to the vCore Provisioned compute tier in Dev and Pre-Prod.
This revisits #3909 and is made after analysing the cost savings originally estimated.
Originally the serverless config was minimum capacity 0.75 vCore, overall capacity 1 vCore.
The change recently made by  #3909 altered it to minimum capacity 0.5 vCore, overall capacity 4 vCore but this hasn't provided the expected cost saving.
The new setting will move away from Serverless to the Provisioned compute tier with a compute size of 2 vCores.
Over the original serverless config that we had, this new config provides higher resource limits in every aspect compared, for a lower cost.
<html>
<body>
  | Serverless 0.75-1 vCores | …

EES-4092 Change statistics database and geo-replica from Serverless to Provisioned in Dev and Pre-Prod.

---

src/explore-education-statistics-frontend/src/modules/find-statistics/FindStatisticsPage.tsx

Removes the temporary banner on the Find Statistics page.

EES-4044 remove find stats page banner

---

infrastructure/templates/template.json

The Data I/O percentage metric alert `physical_data_read_percent` thresholds were set at 50% over a window size of 5 minutes.
We've seen the alert trigger above this when data is being imported. At levels like 50% utilised that doesn't seem to be a problem.
The values of 50% seem too low so this PR changes them to 85%.

EES-4179 Increase the data I/O percentage metric alert `physical_data_read_percent` thresholds

---

tests/performance-tests/docker-compose.yml

This PR adds the Grafana remote image rendering service to the Docker setup in the performance test project to allow rendering panels and dashboards as PNG's which can be downloaded.
The Grafana image plugin is not compatible with the current Grafana Docker image, so we run the plugin in a remote rendering HTTP service within Docker instead.
See [Grafana Image Renderer](https://grafana.com/grafana/plugins/grafana-image-renderer/).
> Grafana renders an image by making an HTTP request to the remote rendering service, which in turn renders the image and returns it back in the HTTP response to Grafana.
Pin Grafana version to `9.3.2` rather than `latest` because the InfluxDB data source configuration in `grafana-datasource.yml` seems to be incompatible with the latest version. If we query the …

EES-4177 Add Grafana remote image rendering service to performance test project

---

src/explore-education-statistics-admin/src/pages/release/content/components/ReleaseContent.tsx
src/explore-education-statistics-frontend/src/modules/find-statistics/PublicationReleasePage.tsx
src/explore-education-statistics-frontend/src/modules/find-statistics/__tests__/PublicationReleasePage.test.tsx
tests/robot-tests/tests/admin_and_public/bau/legacy_releases.robot
tests/robot-tests/tests/admin_and_public/bau/publish_data.robot
tests/robot-tests/tests/admin_and_public_2/bau/publish_release_and_amend.robot
tests/robot-tests/tests/general_public/release_page_absence.robot

Updates the text for the other releases section on release pages.

EES-4168 change past releases text

---

src/explore-education-statistics-common/src/components/form/rhf/RHFFormFieldCheckboxGroupsMenu.tsx
src/explore-education-statistics-common/src/modules/table-tool/components/FiltersForm.tsx
src/explore-education-statistics-common/src/modules/table-tool/components/__tests__/FiltersForm.test.tsx
tests/robot-tests/tests/admin/bau/delete_subject.robot

Collapse all table tool filters by default and add a collapse / expand all button to toggle them.

EES-4087 collapse all filters by default

---

src/explore-education-statistics-admin/src/components/PageHeader.tsx
src/explore-education-statistics-admin/src/pages/release/content/components/EditableKeyStatDataBlockForm.tsx
src/explore-education-statistics-frontend/src/components/Page.tsx
src/explore-education-statistics-frontend/src/components/PageHeader.tsx
src/explore-education-statistics-frontend/src/components/UserTestingBanner.module.scss
src/explore-education-statistics-frontend/src/components/UserTestingBanner.tsx
src/explore-education-statistics-frontend/src/hooks/useCookies.ts
src/explore-education-statistics-frontend/src/modules/find-statistics/FindStatisticsPage.tsx
src/explore-education-statistics-frontend/src/pages/cookies/details.tsx

This PR adds a user-testing invite banner to the home page.
* Adds a cookie to support the display of the banner: `ees_user_testing_banner_seen` 
* Updates cookie page to reflect new cookies that have been added
* Cleans up lint warnings

EES-2431 - add user testing invite banner

---

.github/workflows/validate-snapshots.yml

This PR:
* Automates the creation of snapshot pull requests. Previously, we'd get an alert at 9:30 AM in the `#alerts` channel notifying us that `create_snapshots.py` has detected differences. We'd then have to manually create a branch, push, create a PR, assign the team as reviewers and then notify the `#alerts` channel about it. Now, pull requests will automatically be raised by the `dfe-sdt` bot user. The Action `peter-evans/create-pull-request@v4` will look for changed files inside the `tests/robot-tests/tests/snapshots` directory and if there are changed files, it will raise a pull request targeting dev.
* Added a fine-grained personal access token `GH_TOKEN` as an action secret to allow the workflow to raise pull requests on behalf of the `dfe-sdt` user
* Added `SLACK_WEBBHOOK_URL` …

EES-4193 - automate snapshot pull requests

---

src/explore-education-statistics-common/src/modules/table-tool/components/TableToolWizard.tsx
tests/robot-tests/tests/admin_and_public/bau/data_reordering.robot
tests/robot-tests/tests/admin_and_public/bau/publish_content.robot
tests/robot-tests/tests/admin_and_public_2/bau/publish_amend_and_cancel.robot
tests/robot-tests/tests/admin_and_public_2/bau/publish_release_and_amend.robot
tests/robot-tests/tests/general_public/table_tool_absence_in_prus.robot
tests/robot-tests/tests/general_public/table_tool_exclusions_by_geographic_level.robot

Changes the table tool to only show the warning modal when you go back to the publication and subject steps.
Also, fixes an unrelated failing test in `publish_content.robot`.

EES-4088 remove go back warning on table tool for later steps

---

src/GovUk.Education.ExploreEducationStatistics.Admin/GovUk.Education.ExploreEducationStatistics.Admin.csproj
src/GovUk.Education.ExploreEducationStatistics.Admin/web.config

This PR increases the Admin application request timeout from `00:02:00` to `00:05:00`.
```
<aspNetCore requestTimeout="00:05:00" />
```
According to the IIS documentation the ANCM module will wait for a default of 2 minutes for a response from the process listening to the .Net Core application where it's deployed using out-of-process hosting.
After this duration the request is terminated and IIS responds with status 502.3 Bad Gateway.
The temporary endpoint added by https://github.com/dfe-analytical-services/explore-education-statistics/pull/3989 can be used to test this change. Here we can see an existing request that's been configured to take longer than 2 minutes getting terminated:
The .Net `publish` build target will transform the `web.config` file so the output will end up like …

EES-4218 Increase Admin's request timeout from `00:02:00` to `00:05:00` and tidy up `web.config`
