- armTemplates/service-template.json
Disables ARR Affinity cookie on Data API as it is a stateless application
> DFE-284: Disable Affinity Cookie on Data API

- armTemplates/service-template.json
Enforces Redirect to HTTPS on the App Service for the Admin Application
> DFE-291: Enforce HTTPS on Admin Applcation

- src/explore-education-statistics-frontend/package-lock.json
- src/explore-education-statistics-frontend/package.json
- src/explore-education-statistics-frontend/server.js
Adds in most of the required security headers
> DFE-272: Public application security headers

- src/GovUk.Education.ExploreEducationStatistics.Content.Api/Services/ContentService.cs
Orders API response alphabetically
> DFE-338: Content API tree ordering

- azure-pipelines.yml
- src/nuget.config
Adds new nuget source for gov uk notify packages
> INFRA: add additional nuget package source

- armTemplates/service-template.json
prevent removal of functions due to missing WEBSITE_RUN_FROM_PACKAGE setting
> INFRA: Azure function arm template update

- tests/robot-tests/tests/general_public/table_tool_prototype.robot
- tests/robot-tests/tests/libs/utilities.py
These tests are more to prove that I can use Selenium with the table tool than anything else. I'll be focused on better selectors and more robust testing once things are more solidified.
> Test: Adding tests for table tool prototype

- armTemplates/ees-service/template.json
incorrect name for notification app insights
> DFE-484: Arm template incorrect resource name

- azure-pipelines.dfe.yml
- src/explore-education-statistics-frontend/.env.development
- src/explore-education-statistics-frontend/package.json
> INFRA: DfE Build Pipeline

- src/explore-education-statistics-frontend/src/pages/prototypes/methodology-home.tsx
- src/explore-education-statistics-frontend/src/prototypes/PrototypeHomePageV2.tsx
Updates to the homepage for Laura's demo with the minister
> PROT - update for homepage to include methodology and guidance links

- README.md
- package.json
- src/docker-compose.yml
- The old Docker setup does not work currently so I've just commented it out for the time being. To make it work we'd need to figure out how to make it work with the new monorepo structure.
> Update README with new frontend installation steps and notes

- src/explore-education-statistics-admin/package-lock.json
- src/explore-education-statistics-admin/package.json
- src/explore-education-statistics-admin/src/index.tsx
- src/explore-education-statistics-admin/test/setupTests.js
- src/explore-education-statistics-common/package-lock.json
- src/explore-education-statistics-common/package.json
- src/explore-education-statistics-common/src/polyfill.js
- src/explore-education-statistics-common/test/setupTests.js
- src/explore-education-statistics-frontend/next.config.js
- src/explore-education-statistics-frontend/package-lock.json
- src/explore-education-statistics-frontend/package.json
- src/explore-education-statistics-frontend/src/pages/_app.tsx
- src/explore-education-statistics-frontend/src/polyfill.js
- src/explore-education-statistics-frontend/test/setupTests.js
This PR changes the way that polyfills are loaded to avoid weird race conditions where the application may crash due to polyfills not being loaded before the first render.
As part of this, the custom `polyfill.js` script (in common sub-project) has been refactored to make it synchronous as well to avoid any additional complexity surrounding asynchronous loading of the module. Any custom polyfills should be placed in here.
This should hopefully be the final word on polyfills.
> DFE-441 Second attempt to fix polyfills not loading before application render

- tests/robot-tests/README.md
- tests/robot-tests/run_tests.py
- tests/robot-tests/tests/general_public/notifications_absence.robot
- tests/robot-tests/tests/libs/email_guerrillamail.py
- tests/robot-tests/tests/libs/library.robot
Updated the README.
The new tests don't even run, and due to various factors cannot be finished right now. But I want to commit this so that the work I've done can be used when these tests are completed later.
> Test: Added non-running skeleton test suite to test notifications.

- src/explore-education-statistics-frontend/src/modules/find-statistics/components/PublicationList.tsx
Making the service and prototype consistent
> DFE-337 Content for publication with no releases on EES

- src/explore-education-statistics-frontend/src/pages/index.tsx
Adds the Schools financial benchmarking releated service to the homepage
> DFE-567: Add Schools financial benchmarking service

- README.md
- src/explore-education-statistics-admin/.env
- src/explore-education-statistics-admin/.env.example
- src/explore-education-statistics-admin/config/webpack.config.js
- src/explore-education-statistics-frontend/.env
- src/explore-education-statistics-frontend/.env.example
- src/explore-education-statistics-frontend/.gitignore
- src/explore-education-statistics-frontend/next.config.js
This PR adds the environment variable option to disable ESLint on save as per our linting meeting last week.
Notably, you can disable it by adding the following to your `.env.local` (in your sub-projects):
```
ESLINT_DISABLE=true
```
> DFE-608 Add option to disable ESLint on save

- src/GovUk.Education.ExploreEducationStatistics.Data.Api/GovUk.Education.ExploreEducationStatistics.Data.Api.csproj
- src/GovUk.Education.ExploreEducationStatistics.Data.Api/Migrations/20190507122936_AddObservationQuery.cs
Includes sql files in the output directory
> DFE-630 Include sql files in the output directory.

- src/explore-education-statistics-frontend/src/modules/find-statistics/PublicationReleasePage.tsx
- src/explore-education-statistics-frontend/src/prototypes/methodology/absence/PrototypeSection7.tsx
- src/explore-education-statistics-frontend/src/prototypes/publication/PrototypePublicationPageAbsence.tsx
- src/explore-education-statistics-frontend/src/prototypes/publication/PrototypePublicationPageExclusions.tsx
- src/explore-education-statistics-frontend/src/prototypes/publication/PrototypePublicationPageGCSE.tsx
Updated placeholder text on functioning app for contact details. 
Also updated the prototype pages for reference
> DFE-232 Contact details updates

- tests/robot-tests/tests/general_public/publication_page_absence.robot
- tests/robot-tests/tests/general_public/table_tool.robot
> Test: Fix table tool ui test suite. Mark Key stats block loading test as

- src/explore-education-statistics-common/src/components/PrintThisPage.tsx
- src/explore-education-statistics-frontend/src/modules/find-statistics/PublicationReleasePage.tsx
component to be used on release and methodology pages
> DFE-405 Print this page component

- src/explore-education-statistics-common/src/lib/utils/string/__tests__/commaList.test.ts
- src/explore-education-statistics-common/src/lib/utils/string/commaList.ts
- src/explore-education-statistics-frontend/src/modules/table-tool/TableToolPage.tsx
- src/explore-education-statistics-frontend/src/modules/table-tool/components/LocationFiltersForm.tsx
- src/explore-education-statistics-frontend/src/modules/table-tool/components/TimePeriodDataTable.tsx
This PR auto-generates Table Tool's caption title with the publication, subject, locations and time period. For example:
> Table showing 'Absence by characteristic' from 'Pupil absence' in England, East Midlands, East of England and Inner London between 2013/14 and 2014/15
> DFE-222 + DFE-512 Add auto-generated titles to Table Tool

- azure-pipelines.dfe.yml
disabling old pr, but also a test of new pr build
> disable pr build

- src/explore-education-statistics-common/src/styles/patterns/_dfe-modifiers.scss
- src/explore-education-statistics-frontend/src/pages/prototypes/browse-releases-v3.tsx
- src/explore-education-statistics-frontend/src/pages/prototypes/browse-releases-v4.tsx
- src/explore-education-statistics-frontend/src/prototypes/PrototypeBrowseReleases.tsx
- src/explore-education-statistics-frontend/src/prototypes/PrototypeBrowseReleasesV2.tsx
- src/explore-education-statistics-frontend/src/prototypes/PrototypeBrowseReleasesV3.tsx
- src/explore-education-statistics-frontend/src/prototypes/PrototypeBrowseReleasesV4.tsx
- src/explore-education-statistics-frontend/src/prototypes/components/PrototypeDownloadDropdown.tsx
A couple of alternative views (in prototype) for A/B testing of find stats page
> Dfe 655 find stats

- src/explore-education-statistics-common/src/components/form/FormCheckboxSearchGroup.tsx
- src/explore-education-statistics-common/src/components/form/FormCheckboxSearchSubGroups.tsx
- src/explore-education-statistics-common/src/components/form/FormTextInput.tsx
- src/explore-education-statistics-common/src/components/form/FormTextSearchInput.tsx
- src/explore-education-statistics-common/src/components/form/__tests__/__snapshots__/FormCheckboxSearchGroup.test.tsx.snap
- src/explore-education-statistics-common/src/components/form/__tests__/__snapshots__/FormCheckboxSearchSubGroups.test.tsx.snap
- src/explore-education-statistics-common/src/components/form/__tests__/__snapshots__/FormTextInput.test.tsx.snap
- src/explore-education-statistics-common/src/components/form/__tests__/__snapshots__/FormTextSearchInput.test.tsx.snap
- src/explore-education-statistics-frontend/src/modules/table-tool/components/FormCheckboxSelectedCount.module.scss
- src/explore-education-statistics-frontend/src/modules/table-tool/components/FormCheckboxSelectedCount.tsx
- src/explore-education-statistics-frontend/src/modules/table-tool/components/PublicationForm.tsx
- Makes some modifications to the wording and placement of the 'X selected' tag appears to make it more consistent across Table Tool.
> DFE-647 Fix filter search inputs causing form submissions upon pressing Enter

- src/GovUk.Education.ExploreEducationStatistics.Content.Api.Tests/Services/MethodologyServiceTests.cs
- src/GovUk.Education.ExploreEducationStatistics.Content.Api/Services/MethodologyService.cs
ammend methodology tree response to include methodogies rather than publications
> dfe-654:  ammend methodology tree response to include methodogies

- src/GovUk.Education.ExploreStatistics.Data.Api.Tests/Controller/MetaControllerTests.cs
Not fully featured but a few additional tests to cover the basics
> Added some basic tests to cover the data api meta controller

- src/GovUk.Education.ExploreEducationStatistics.Content.Api/Controllers/DownloadController.cs
- src/GovUk.Education.ExploreEducationStatistics.Content.Api/GovUk.Education.ExploreEducationStatistics.Content.Api.csproj
- src/GovUk.Education.ExploreEducationStatistics.Content.Api/Services/DownloadService.cs
- src/GovUk.Education.ExploreEducationStatistics.Content.Api/Services/Interfaces/IDownloadService.cs
- src/GovUk.Education.ExploreEducationStatistics.Content.Api/Startup.cs
Intial content api endpoint for the download tree, requires additional work following on from ticket to associate downloads to a release
> dFE-684: download content api

- src/explore-education-statistics-frontend/src/modules/find-statistics/PublicationReleasePage.tsx
List of example files to download within a release
> DFE-689 Added indicative css download links

- src/explore-education-statistics-frontend/src/components/PageFooter.tsx
- src/explore-education-statistics-frontend/src/pages/help-support.tsx
- src/explore-education-statistics-frontend/src/pages/sitemap.tsx
Removed prototype link and added placeholders for help/support and sitemap
> DFE-699 Updated footer links

- src/explore-education-statistics-frontend/src/modules/find-statistics/PublicationReleasePage.tsx
Tweaked release header to allow for repositioning of the 'notify me' link
> DFE-732 Notify me link positioning

- src/explore-education-statistics-frontend/server.js
This adds a content security policy to the public application, and allows unsafe evaluation within a development environment
> DFE-271: Configure Public app content security policy

- src/explore-education-statistics-frontend/server.js
This allows the react application to make calls to sources once the page has loaded.
As the api urls vary across our enviroments and locally this should load these from environment variables
> DFE-271: adds in connect src to allow api calls

- src/explore-education-statistics-frontend/src/modules/methodology/MethodologyIndexPage.tsx
- src/explore-education-statistics-frontend/src/modules/methodology/components/MethodologyList.tsx
- src/explore-education-statistics-frontend/src/modules/methodology/components/TopicList.tsx
Layout for methodology home, now ready for further development
> DFE-552 Methodology layout

- src/GovUk.Education.ExploreEducationStatistics.Content.Api.Tests/Services/MethodologyServiceTests.cs
- src/GovUk.Education.ExploreEducationStatistics.Content.Api/Services/MethodologyService.cs
As discussed, we only want to display items that exist within the service, therefore we only return a partial tree based upon what we hold data for
> DFE-773: Methodology tree only return items with methodology content

- src/explore-education-statistics-frontend/src/modules/find-statistics/PublicationReleasePage.tsx
- src/explore-education-statistics-frontend/src/modules/subscriptions/SubscriptionPage.tsx
altered the contact message and added an alert message explaining notify page isnt available for use
> dfe-755 notify page (unavailable message) w/ contact message alteration

- src/explore-education-statistics-frontend/src/modules/find-statistics/PublicationReleasePage.tsx
removed(commented out) link to table tool in PublicationReleasePage
> dfe-786 publication data download table tool link removal

- src/explore-education-statistics-frontend/src/pages/index.tsx
As suggested by Marv and Laura
> On homepage, moving Contact Us into its own section

- src/explore-education-statistics-common/src/components/Accordion.tsx
- src/explore-education-statistics-common/src/components/AccordionSection.tsx
fixed accordion section open state and removed magic string from AccordionSection
> I took a typescript detour on this one 😆  - the resulting solution was actually much neater than what I came up with along the way
> dfe-251 Accordion section open state caching fix

- src/explore-education-statistics-common/src/modules/find-statistics/components/ChartRenderer.tsx
- src/explore-education-statistics-common/src/modules/find-statistics/components/DataBlock.tsx
- src/explore-education-statistics-common/src/modules/find-statistics/components/charts/MapBlock.tsx
- src/explore-education-statistics-frontend/src/modules/find-statistics/PublicationReleasePage.tsx
- src/explore-education-statistics-frontend/src/modules/find-statistics/components/ContentBlock.tsx
- src/explore-education-statistics-frontend/src/modules/find-statistics/components/ContentSubBlockRenderer.tsx
The original method of using a "ref" won't work with Function Components.
So now passing a "registration function" as a property, that is called with a function to call, when you want to refresh a the DataBlock. Only the Map ultimately uses it at present. All this code is to get the registration function down to the MapBlock where it can detect it and return the function that can be called to refresh the Map.
The PublicationReleasePage will register a callback for each Block and then call the refresh function when the Accordion is toggled open.
> Dfe 807 maps displaying gray box

- src/explore-education-statistics-frontend/server.js
Adds additional font and image sources to resolve hotjar errors
> DFE-876: update frontend csp for hotjar sources

- src/GovUk.Education.ExploreEducationStatistics.Content.Api/Migrations/20190624161407_AddAdditionalMethodologies.cs
- src/GovUk.Education.ExploreEducationStatistics.Content.Api/Migrations/20190626125108_AddMethodologyLastUpdatedDate.Designer.cs
- src/GovUk.Education.ExploreEducationStatistics.Content.Api/Migrations/20190626125108_AddMethodologyLastUpdatedDate.cs
- src/GovUk.Education.ExploreEducationStatistics.Content.Model/Database/ApplicationDbContext.cs
- src/GovUk.Education.ExploreEducationStatistics.Content.Model/Methodology.cs
- src/explore-education-statistics-common/src/services/methodologyService.ts
- src/explore-education-statistics-frontend/src/modules/methodologies/MethodologyPage.tsx
This adds the necessary model and api changes to allow frontend implementation of last updated methodology on the methodology page.
> DFE-767: Add last updated to methodology page 

- src/explore-education-statistics-frontend/.env.dev01
- src/explore-education-statistics-frontend/.env.dev02
This PR disables hotjar on environments that do not currently use it.
> DFE-904: disable hotjar on dev and stage environments

- src/explore-education-statistics-frontend/src/modules/table-tool/components/TimePeriodForm.tsx
Probably wanna read the comments here
https://alpha-dfe-data.atlassian.net/browse/DFE-625
> DFE 625 Error message updates

- src/GovUk.Education.ExploreEducationStatistics.Data.Api/Services/TableBuilderSubjectMetaService.cs
- src/GovUk.Education.ExploreEducationStatistics.Data.Api/ViewModels/Meta/FilterItemMetaViewModel.cs
- src/GovUk.Education.ExploreEducationStatistics.Data.Api/ViewModels/Meta/TableBuilderSubjectMetaViewModel.cs
Including the id value of any 'Total' FilterItem as the 'TotalValue' property if one exists.
> Feature/dfe 891 Total filter value

- azure-pipelines.dfe.yml
- tests/robot-tests/tests/general_public/miscellaneous.robot
Made the test a bit more generic and robust due to ongoing content changes checking a exact sentence is going to be too fragile
> TESTS: Update contact page test

- src/explore-education-statistics-frontend/src/components/PageBanner.tsx
Merge DFE-826 before this one, please.
> DFE-909 - Beta banner feedback form to open in new window

- src/explore-education-statistics-frontend/src/modules/find-statistics/PublicationReleasePage.tsx
Found a bug where if no data files are present it blows up so I've added in a check
> DFE-772 - Publication latest release label

- src/explore-education-statistics-common/src/components/Tabs.tsx
- src/explore-education-statistics-common/src/modules/find-statistics/components/DataBlock.tsx
- src/explore-education-statistics-frontend/src/components/DataBlockWithAnalytics.tsx
- src/explore-education-statistics-frontend/src/modules/find-statistics/PublicationReleasePage.tsx
> DFE-825 - Custom analytics events added to tabs

- azure-pipelines.dfe.yml
This PR removed the fronend build for dev02 as it is no longer used or needed.
> Removing dev02 build

- armTemplates/ees-service/template.json
First step, creates the new database
> DFE-925:Create new public statistics database

- tests/newman/tests/admin-api.json
-Added tests for testing the admin dashboard
> Postman tests for creating new release and admin dashboard

- src/explore-education-statistics-frontend/src/pages/_app.tsx
handling universal cookies on route change
> Bugfix: DFE-950 Cookies Banner

- src/explore-education-statistics-admin/src/pages/admin-dashboard/AdminDashboardPage.tsx
- src/explore-education-statistics-admin/src/pages/admin-dashboard/components/AdminDashboardPublicationsTab.tsx
Updating some of the admin dashboard design to match prototypes
> Update admin dashboard to match prototpyes

- src/explore-education-statistics-common/src/modules/find-statistics/components/SummaryRenderer.tsx
- src/explore-education-statistics-common/src/modules/find-statistics/components/TableRenderer.tsx
formatPretty-ing the table and summary number values with comma separation if number.
> DFE-789 (& 841) Comma separated numbers 

- src/explore-education-statistics-frontend/src/components/CookieBanner.tsx
- src/explore-education-statistics-frontend/src/components/Page.tsx
- src/explore-education-statistics-frontend/src/pages/_app.tsx
... now matching the current page
Moved the cookie banner into the Page component
> DFE-950 Cookie Banner style width alignment 

- tests/robot-tests/tests/admin/admin.robot
- tests/robot-tests/tests/general_public/download_page.robot
I've added ADMIN_EMAIL and ADMIN_PASSWORD environment variables to devops for all the UI test tasks
> Test: UI tests now login to admin service

- src/GovUk.Education.ExploreEducationStatistics.Data.Importer/Services/ImporterService.cs
- src/GovUk.Education.ExploreEducationStatistics.Data.Processor/Models/Batch.cs
- src/GovUk.Education.ExploreEducationStatistics.Data.Processor/Processor.cs
- src/GovUk.Education.ExploreEducationStatistics.Data.Processor/Services/BatchService.cs
- src/GovUk.Education.ExploreEducationStatistics.Data.Processor/Services/FileImportService.cs
- src/GovUk.Education.ExploreEducationStatistics.Data.Processor/Services/FileStorageService.cs
- src/GovUk.Education.ExploreEducationStatistics.Data.Processor/Services/Interfaces/IBatchService.cs
- src/GovUk.Education.ExploreEducationStatistics.Data.Processor/Startup.cs
- src/GovUk.Education.ExploreEducationStatistics.Data.Processor/host.json
- src/GovUk.Education.ExploreEducationStatistics.Data.Processor/local.settings.json
- src/GovUk.Education.ExploreEducationStatistics.Data.Seed/SamplePublications.cs
Note this PR to be merged into DFE-1071.
> Add batch completion support for uploads.

- armTemplates/ees-service/template.json
This PR points the importer function back at the admin statistics database.
> INFRA: Importer will use admin statistics database

- src/explore-education-statistics-admin/src/pages/prototypes/PrototypeDocumentationCreateNewPublication.tsx
- src/explore-education-statistics-admin/src/pages/prototypes/PrototypeDocumentationCreateNewRelease.tsx
- src/explore-education-statistics-admin/src/pages/prototypes/PrototypeDocumentationUsingDashboard.tsx
- src/explore-education-statistics-admin/src/pages/prototypes/PrototypePublicationPageNewAbsenceData.tsx
- src/explore-education-statistics-admin/src/pages/prototypes/components/PrototypeAddFootnotes.tsx
- src/explore-education-statistics-admin/src/pages/prototypes/components/PrototypeFootnotes.tsx
- src/explore-education-statistics-admin/src/pages/prototypes/components/PrototypeStepByStep.tsx
- src/explore-education-statistics-admin/src/pages/prototypes/components/PrototypeStepByStepItem.tsx
- src/explore-education-statistics-admin/src/pages/release/edit-release/ReleaseManageDataBlocksPage.tsx
- src/explore-education-statistics-frontend/src/modules/table-tool/TableToolPage.tsx
This is just a big cleanup because the Prototype merge made a large less of the linting results and it was getting hard to see the wood... trees... etc.
> Cleaning up the linting after prototypes made a mess

- src/explore-education-statistics-frontend/src/modules/table-tool/TableToolPage.tsx
- src/explore-education-statistics-frontend/src/modules/table-tool/components/PublicationForm.tsx
Table tool Step 2 missing Step 1 publication title when coming from 'Create table' on a publication
> DFE-898 - Table tool Step 2 missing Step 1 publication title

- tests/newman/tests/data-api.json
- tests/robot-tests/run_tests.py
All failures on the Data API tests, except for Absence by term, I believe are actual bugs -- I've verified the results against the CSV data.
> Test: Updated Data API tests for new data

- useful-scripts/sql/FootnoteData.sql
Makes safer inserts by looking up subject, filter, filter item and indicator names rather than using hard coded id's.
Corrects footnote data inline with footnotes_example_v2.xlsx
> Footnote data

- tests/newman/tests/admin-api.json
Update number of theses test to look count to be above rather than exact number
> Update admin api tests to account for varying data

- src/GovUk.Education.ExploreEducationStatistics.Data.Seed/GovUk.Education.ExploreEducationStatistics.Data.Seed.csproj
- src/GovUk.Education.ExploreEducationStatistics.Data.Services/GovUk.Education.ExploreEducationStatistics.Data.Services.csproj
100% passing API tests running locally in the following areas after this upgrade:
Data API tests
Admin API/data tests
> EES-298 Upgrading AutoMapper

- src/explore-education-statistics-frontend/src/modules/find-statistics/components/PublicationList.tsx
Added extra context to links for screenreaders
> EES-174 Adding context to links for screen readers

- src/explore-education-statistics-frontend/src/modules/download/components/PublicationDownloadList.tsx
Updates extension on download page to be uppercase in accordance with GDS guidelines
> EES-173 update extension and units to uppercase

- src/explore-education-statistics-admin/src/components/NavLink.module.scss
- src/explore-education-statistics-admin/src/components/NavLink.tsx
> EES-386 active link styling on admin nav

- tests/robot-tests/tests/general_public/table_tool_absence_by_characteristic.robot
> Test: Increase UI tests timeout in Table Tool Absence by Characteristic

- src/explore-education-statistics-admin/src/components/ImporterStatus.tsx
- src/explore-education-statistics-admin/src/pages/release/edit-release/data/ReleaseDataUploadsSection.module.scss
- src/explore-education-statistics-admin/src/pages/release/edit-release/data/ReleaseDataUploadsSection.tsx
- src/explore-education-statistics-admin/src/services/release/imports/service.ts
Now shows an expandable "Show errors" list with listed errors beneath
> EES-318 Failed upload errors

- src/explore-education-statistics-common/src/modules/table-tool/components/DownloadCsvButton.tsx
- src/explore-education-statistics-common/src/modules/table-tool/components/__tests__/DownloadCsvButton.test.tsx
Updated download link text as outlined in the ticket
https://alpha-dfe-data.atlassian.net/browse/EES-486
> EES-486 data download link text iteration

- src/explore-education-statistics-frontend/src/components/PrintThisPage.module.scss
- src/explore-education-statistics-frontend/src/components/PrintThisPage.tsx
What it says on the tin...
Print This Page link now hidden on touch and mobile viewport widths
> EES-280 Print this Page on mobile

- src/explore-education-statistics-frontend/src/components/PrintThisPage.tsx
- src/explore-education-statistics-frontend/src/modules/find-statistics/PublicationReleasePage.tsx
- src/explore-education-statistics-frontend/src/modules/methodologies/MethodologyPage.tsx
Added PrintThisPage component to top of publication and methodology pages - also styled as a secondary button too
> EED-480 Print this page - top of pub and method pages - styled to button

- src/explore-education-statistics-common/src/components/SummaryListItem.tsx
- src/explore-education-statistics-common/src/modules/table-tool/components/LocationFiltersForm.tsx
Can now select all LA's with one button and big list of LA's will now show as collapsed
> EES-485 select all LA's

- src/explore-education-statistics-frontend/src/components/PageMeta.tsx
DAC_Page-title-issue02 added logic to show: 
> `pageTitle` - `serviceName` - GOV.UK
https://alpha-dfe-data.atlassian.net/browse/EES-404
> EES-404 Page title

- src/explore-education-statistics-frontend/src/pages/index.tsx
removed homepage pageMeta override, will fall back to `title` property instead
> EES-404 round 2

- src/explore-education-statistics-frontend/src/modules/glossary/GlossaryIndexPage.tsx
Fixed duplicate ids in /glossary
> EES-416 duplicate header IDs

- src/explore-education-statistics-common/src/components/PageSearchForm.tsx
Added screenreader only button text
> EES-417 button had no text (accessibility issue)

- src/explore-education-statistics-common/src/components/PageSearchForm.tsx
- src/explore-education-statistics-common/src/components/__tests__/PageSearchForm.test.tsx
- src/explore-education-statistics-frontend/src/modules/download/DownloadIndexPage.tsx
- src/explore-education-statistics-frontend/src/modules/find-statistics/FindStatisticsPage.tsx
- src/explore-education-statistics-frontend/src/modules/find-statistics/PublicationReleasePage.tsx
- src/explore-education-statistics-frontend/src/modules/glossary/GlossaryIndexPage.tsx
- src/explore-education-statistics-frontend/src/modules/methodologies/MethodologyIndexPage.tsx
- src/explore-education-statistics-frontend/src/modules/methodologies/MethodologyPage.tsx
https://alpha-dfe-data.atlassian.net/browse/EES-418 Accessibility improvement.
added required inputLabel prop to PageSearch component and added labels on pages it is used
> EES-418 Page Search inputLabels

- tests/newman/files/small-files/LEP.csv
- tests/newman/files/small-files/MCA.csv
- tests/newman/files/small-files/all_geographies.csv
- tests/newman/files/small-files/all_geographies_messy.csv
Amending the test files to address EES-289, in conjunction with changes made in #817
> EES 289 fixes

- src/GovUk.Education.ExploreEducationStatistics.Admin/Services/FileStorageService.cs
- src/GovUk.Education.ExploreEducationStatistics.Common/GovUk.Education.ExploreEducationStatistics.Common.csproj
- src/GovUk.Education.ExploreEducationStatistics.Common/Services/FileStorageUtils.cs
- src/GovUk.Education.ExploreEducationStatistics.Content.Api/Startup.cs
- src/GovUk.Education.ExploreEducationStatistics.Content.Model/Services/FileStorageService.cs
- src/GovUk.Education.ExploreEducationStatistics.Content.Model/Services/Interfaces/IFileStorageService.cs
- src/GovUk.Education.ExploreEducationStatistics.Data.Api/Services/FileStorageService.cs
- src/GovUk.Education.ExploreEducationStatistics.Data.Processor/Extensions/FileExtensions.cs
- src/GovUk.Education.ExploreEducationStatistics.Data.Processor/Models/SubjectData.cs
- src/GovUk.Education.ExploreEducationStatistics.Data.Processor/Services/BatchService.cs
- src/GovUk.Education.ExploreEducationStatistics.Data.Processor/Services/FileStorageService.cs
- src/GovUk.Education.ExploreEducationStatistics.Data.Processor/Services/Interfaces/IFileStorageService.cs
- src/GovUk.Education.ExploreEducationStatistics.Data.Processor/Utils/BlobUtils.cs
- src/GovUk.Education.ExploreEducationStatistics.Data.Seed/Services/FileStorageService.cs
- src/GovUk.Education.ExploreEducationStatistics.Publisher/GovUk.Education.ExploreEducationStatistics.Publisher.csproj
- src/GovUk.Education.ExploreEducationStatistics.Publisher/Services/ContentCacheGenerationService.cs
- src/GovUk.Education.ExploreEducationStatistics.Publisher/Services/FileStorageService.cs
- src/GovUk.Education.ExploreEducationStatistics.Publisher/host.json
Also abstracts out the methods GetCloudBlobContainer appearing in the FileStorageService classes into a new FileStorageUtils.
> EES-511 Zip all files when they are copied to the public release directory

- src/explore-education-statistics-frontend/src/components/Page.tsx
- src/explore-education-statistics-frontend/src/components/PageMeta.tsx
- src/explore-education-statistics-frontend/src/modules/find-statistics/PublicationReleasePage.tsx
- src/explore-education-statistics-frontend/src/modules/methodologies/MethodologyPage.tsx
Fixed the default description not being added, renamed 'seoDescription' to 'description'
> EES-59 meta data

- src/explore-education-statistics-common/src/modules/table-tool/components/TimePeriodForm.tsx
The TimePeriodForm was not being correctly initialised and was overwriting the saved value internally when it was saved.
> EES-563 - initialising the TimePeriodForm initial values correctly

- src/GovUk.Education.ExploreEducationStatistics.Admin.Tests/Controllers/Api/TopicControllerTests.cs
- src/GovUk.Education.ExploreEducationStatistics.Admin/Controllers/Api/TopicController.cs
- src/GovUk.Education.ExploreEducationStatistics.Admin/Services/Interfaces/ITopicService.cs
- src/GovUk.Education.ExploreEducationStatistics.Admin/Services/TopicService.cs
- src/GovUk.Education.ExploreEducationStatistics.Admin/Startup.cs
- src/explore-education-statistics-admin/src/pages/admin-dashboard/components/MyPublicationsTab.tsx
- src/explore-education-statistics-admin/src/pages/create-publication/CreatePublicationPage.tsx
- src/explore-education-statistics-admin/src/pages/release/create-release/CreateReleasePage.tsx
- src/explore-education-statistics-admin/src/services/edit-publication/service.ts
- src/explore-education-statistics-admin/src/services/edit-publication/types.ts
- src/explore-education-statistics-admin/src/services/release/create-release/service.ts
As a side fix the subheadings on the 'create release page' and 'create publication page' has been added in this pr
> EES-396 - Add help and guidance link to create a new release

- src/explore-education-statistics-frontend/src/modules/find-statistics/PublicationReleasePage.tsx
Fixes a header that was out of sequence on the release page
> EES-405 Header hierarchy

- src/explore-education-statistics-admin/src/modules/chart-builder/ChartAxisConfiguration.tsx
- src/explore-education-statistics-admin/src/modules/chart-builder/ChartBuilder.tsx
https://alpha-dfe-data.atlassian.net/browse/EES-246
> ees-246 Default chart creator to have y-axis minimum value set to zero

- src/explore-education-statistics-common/src/components/Accordion.module.scss
- src/explore-education-statistics-common/src/modules/table-tool/components/MultiHeaderTable.module.scss
- src/explore-education-statistics-common/src/modules/table-tool/components/MultiHeaderTable.tsx
- src/explore-education-statistics-common/src/modules/table-tool/components/__tests__/__snapshots__/FixedMultiHeaderDataTable.test.tsx.snap
- src/explore-education-statistics-common/src/modules/table-tool/components/__tests__/__snapshots__/MultiHeaderTable.test.tsx.snap
- Accordion text spacing fix
- Table row header centre aligned
> EES-410 - Updating GDS version

- src/explore-education-statistics-common/src/modules/table-tool/components/MultiHeaderTable.module.scss
- src/explore-education-statistics-common/src/modules/table-tool/components/MultiHeaderTable.tsx
- src/explore-education-statistics-common/src/modules/table-tool/components/__tests__/__snapshots__/FixedMultiHeaderDataTable.test.tsx.snap
- src/explore-education-statistics-common/src/modules/table-tool/components/__tests__/__snapshots__/MultiHeaderTable.test.tsx.snap
Styling to make colspanning headers make more sense visually
> EES-608 header styling

- src/GovUk.Education.ExploreEducationStatistics.Admin/Controllers/Api/CreateUpdateLinkRequest.cs
- src/GovUk.Education.ExploreEducationStatistics.Admin/Controllers/Api/ManageContent/RelatedInformationController.cs
- src/GovUk.Education.ExploreEducationStatistics.Admin/Controllers/Utils/ControllerExtensions.cs
- src/GovUk.Education.ExploreEducationStatistics.Admin/Controllers/Utils/ReleaseUtils.cs
- src/GovUk.Education.ExploreEducationStatistics.Admin/Services/Interfaces/ManageContent/IRelatedInformationService.cs
- src/GovUk.Education.ExploreEducationStatistics.Admin/Services/ManageContent/RelatedInformationService.cs
- src/GovUk.Education.ExploreEducationStatistics.Admin/Startup.cs
- src/GovUk.Education.ExploreEducationStatistics.Admin/Validators/ValidationUtils.cs
- src/GovUk.Education.ExploreEducationStatistics.Common/Model/Either.cs
- src/GovUk.Education.ExploreEducationStatistics.Content.Api/Migrations/20191113102937_AddRelatedInformationToReleases.Designer.cs
- src/GovUk.Education.ExploreEducationStatistics.Content.Api/Migrations/20191113102937_AddRelatedInformationToReleases.cs
- src/GovUk.Education.ExploreEducationStatistics.Content.Model/BasicLink.cs
- src/GovUk.Education.ExploreEducationStatistics.Content.Model/Database/ApplicationDbContext.cs
- src/GovUk.Education.ExploreEducationStatistics.Content.Model/Release.cs
- tests/newman/tests/admin-api.json
This PR adds new APIs for the Related Information section of the Admin Manage Content page.
It adds the routes:
- GET release/{releaseId}/content/related-information
- POST release/{releaseId}/content/related-information
- PUT release/{releaseId}/content/related-information/{relatedInformationId}
- DELETE release/{releaseId}/content/related-information/{relatedInformationId}
> EES-144 - creating PR from master rather than from 235

- src/explore-education-statistics-admin/src/pages/release/edit-release/data/ReleaseFootnotesSection/FootnoteForm.tsx
- src/explore-education-statistics-admin/src/pages/release/edit-release/data/ReleaseFootnotesSection/FootnotesList.tsx
- src/explore-education-statistics-admin/src/pages/release/edit-release/data/ReleaseFootnotesSection/index.tsx
branch: `feature/ees-679-footnote-loading`
ticket(s): https://alpha-dfe-data.atlassian.net/browse/EES-651
Fixes: 
- delete footnote confirmation modal added
- message when no data-files have been uploaded
- loading when waiting for response of footnote creation/update
> ees-651 footnote creation enhancements

- src/GovUk.Education.ExploreEducationStatistics.Admin/Services/ManageContent/RelatedInformationService.cs
This PR:
- fixes the issue whereby the Related Information items weren't truly being updated
- improves the general persisting code
> EES-144 - fixed the updating of Related Information

- src/GovUk.Education.ExploreEducationStatistics.Admin/Controllers/Api/Statistics/FootnoteController.cs
- src/GovUk.Education.ExploreEducationStatistics.Admin/Mappings/MappingProfiles.cs
- src/GovUk.Education.ExploreEducationStatistics.Admin/Models/Api/Statistics/FootnoteFilterGroupViewModel.cs
- src/GovUk.Education.ExploreEducationStatistics.Admin/Models/Api/Statistics/FootnoteFilterViewModel.cs
- src/GovUk.Education.ExploreEducationStatistics.Admin/Models/Api/Statistics/FootnoteIndicatorGroupViewModel.cs
- src/GovUk.Education.ExploreEducationStatistics.Admin/Models/Api/Statistics/FootnoteSubjectViewModel.cs
- src/GovUk.Education.ExploreEducationStatistics.Admin/Models/Api/Statistics/FootnoteViewModel.cs
- src/GovUk.Education.ExploreEducationStatistics.Data.Model/Services/FootnoteService.cs
- tests/newman/tests/admin-api.json
- useful-scripts/sql/FootnoteData.sql
Part of the rework in EES-678, but not all of it.
> New FootnoteViewModel for Admin

- src/explore-education-statistics-common/src/components/Tabs.tsx
new branch of #960 
without additional changes from #956
> EES-689: linking directly to tabs

- src/explore-education-statistics-common/src/components/AriaLiveAnnouncer.tsx
- src/explore-education-statistics-common/src/components/AriaLiveMessage.tsx
- src/explore-education-statistics-common/src/components/LoadingSpinner.tsx
- src/explore-education-statistics-common/src/modules/table-tool/components/WizardStepFormActions.tsx
fixed message not being read - tested with MacOS VoiceOver
> AriaLive spinner messages not being read - fixed

- src/explore-education-statistics-admin/src/modules/find-statistics/PublicationReleaseContent.tsx
- src/explore-education-statistics-admin/src/pages/prototypes/components/PrototypePublicationService.ts
- src/explore-education-statistics-common/src/services/publicationService.ts
Cleaning up unused `dataFiles` field in the `AbstractRelease`.
> EES-146 Download data files

- src/explore-education-statistics-admin/src/components/api-authorization/AuthorizeService.js
isAuthorized returns false if users token is expired
> EES-751 user login admin, blankscreen

- src/explore-education-statistics-admin/src/modules/find-statistics/PublicationReleaseContent.tsx
- src/explore-education-statistics-admin/src/modules/find-statistics/components/AdminPublicationReleaseHelpAndSupportSection.tsx
- src/explore-education-statistics-common/src/modules/find-statistics/components/NationalStatisticsSection.tsx
- src/explore-education-statistics-frontend/src/modules/find-statistics/PublicationReleaseHelpAndSupportSection.tsx
Branching from 149 until it's merged...
Refactored the National stats into a single component for both the front and admin servers to use.
Created a new Adming Help and Support component and moved it out of the Content page to tidy  that up.
> EES-151 - refactor national stats and help and support section

- src/explore-education-statistics-common/src/modules/table-tool/components/WizardStepFormActions.tsx
> swapped buttons around (previous on left, next on right)

- infrastructure/infrastructure-pipeline.yml
- infrastructure/templates/template.json
> EES-793: following guidelines for arm template configuration

- src/explore-education-statistics-common/src/components/ModalConfirm.tsx
The original problem with the next and previous buttons is already fixed. However, the previous step modal buttons were not correct.
> EES-776 - Table tool next & previous buttons in wrong order

- src/explore-education-statistics-frontend/src/modules/find-statistics/PublicationReleasePage.tsx
Changes following comments on [https://alpha-dfe-data.atlassian.net/browse/EES-766?atlOrigin=eyJpIjoiMWU3MWNhY2E1YjkwNDU2ZDgwZjcyM2JiMzI0NmI2MTkiLCJwIjoiaiJ9](url)
> EES-766 - Related information links

- src/GovUk.Education.ExploreEducationStatistics.Admin.Tests/Controllers/Api/Statistics/FootnoteControllerTests.cs
- src/GovUk.Education.ExploreEducationStatistics.Admin/Controllers/Api/Statistics/FootnoteController.cs
- src/GovUk.Education.ExploreEducationStatistics.Data.Model/Services/AbstractRepository.cs
- src/GovUk.Education.ExploreEducationStatistics.Data.Model/Services/FootnoteService.cs
- src/GovUk.Education.ExploreEducationStatistics.Data.Model/Services/Interfaces/IFootnoteService.cs
- src/GovUk.Education.ExploreEducationStatistics.Data.Model/Services/Interfaces/IRepository.cs
…tor groups when fetching footnotes so that the hierarchy can be built
> EES-763 Fixing footnotes

- src/explore-education-statistics-admin/src/modules/find-statistics/PublicationReleaseContent.tsx
- src/explore-education-statistics-admin/src/modules/find-statistics/components/EditableContentBlock.tsx
- src/explore-education-statistics-admin/src/pages/prototypes/PrototypePublicationPageEditAbsenceUnresolvedComments.tsx
- src/explore-education-statistics-admin/src/pages/prototypes/components/EditablePublicationPage.tsx
- src/explore-education-statistics-common/src/modules/find-statistics/components/ContentBlock.tsx
- src/explore-education-statistics-common/src/services/publicationService.ts
- src/explore-education-statistics-frontend/src/modules/find-statistics/PublicationReleasePage.tsx
Refactored to allow empty content section in Release and adding checks for undefined content
> EES-796 - fixing crash after previewing newly added section

- src/explore-education-statistics-common/src/components/PageSearchForm.tsx
- src/explore-education-statistics-common/src/components/form/FormComboBox.tsx
- src/explore-education-statistics-common/src/components/form/__tests__/__snapshots__/FormComboBox.test.tsx.snap
Ticket for reference
[https://alpha-dfe-data.atlassian.net/browse/EES-411?atlOrigin=eyJpIjoiZjEwN2NjNWVlNzI0NDM1YThiOWI5YmYxYTc2MjczYTQiLCJwIjoiaiJ9](url)
> EES-411 - DAC_Form_Controls-issue01

- src/GovUk.Education.ExploreEducationStatistics.Publisher.Model/ReleaseStatus.cs
- src/GovUk.Education.ExploreEducationStatistics.Publisher/Functions/GenerateReleaseContentFunction.cs
- src/GovUk.Education.ExploreEducationStatistics.Publisher/Functions/PublishReleaseDataFunction.cs
- src/GovUk.Education.ExploreEducationStatistics.Publisher/Functions/PublishReleaseFilesFunction.cs
- src/GovUk.Education.ExploreEducationStatistics.Publisher/Functions/PublishReleasesFunction.cs
- src/GovUk.Education.ExploreEducationStatistics.Publisher/Functions/ValidateReleaseFunction.cs
- src/GovUk.Education.ExploreEducationStatistics.Publisher/Services/FileStorageService.cs
- src/GovUk.Education.ExploreEducationStatistics.Publisher/Services/Interfaces/IReleaseStatusService.cs
- src/GovUk.Education.ExploreEducationStatistics.Publisher/Services/ReleaseStatusService.cs
Most of the work was done for this on the scaffolding PR. This PR is mainly just fixing recording the stages of the different tasks being executed. It also deletes any existing files in the public blob container before they are copied.
> EES-863 Function for triggering other functions

- src/explore-education-statistics-admin/src/routes/dashboard/routes.ts
Fixed publication release page
> Update routes.ts (Making pub-release page accesible again)

- infrastructure/templates/template.json
Add openIdConnectTenant to arm template for configuration of AAD
> EES-905: Add openIdConnectTenant to arm template

- src/explore-education-statistics-admin/src/pages/errors/PageNotFoundPage.tsx
> EES-779 - Admin 404 page

- src/explore-education-statistics-admin/src/components/Page.tsx
- src/explore-education-statistics-admin/src/components/PageFooter.tsx
- src/explore-education-statistics-admin/src/pages/ContactUsPage.tsx
- src/explore-education-statistics-admin/src/pages/admin-dashboard/AdminDashboardPage.tsx
- src/explore-education-statistics-admin/src/pages/errors/PageNotFoundPage.tsx
- src/explore-education-statistics-admin/src/pages/errors/ResourceNotFoundPage.tsx
- src/explore-education-statistics-admin/src/pages/errors/ServiceProblemsPage.tsx
Further admin/contact page stuff
> EES-950 admin contact us page footer links etal

- infrastructure/templates/template.json
- src/GovUk.Education.ExploreEducationStatistics.Admin/Areas/Identity/Data/Models/UserInvite.cs
- src/GovUk.Education.ExploreEducationStatistics.Admin/Areas/Identity/Data/UsersAndRolesDbContext.cs
- src/GovUk.Education.ExploreEducationStatistics.Admin/Controllers/Api/BAU/BauUsersController.cs
- src/GovUk.Education.ExploreEducationStatistics.Admin/GovUk.Education.ExploreEducationStatistics.Admin.csproj
- src/GovUk.Education.ExploreEducationStatistics.Admin/Migrations/20200103131845_AddUserInviteTable.Designer.cs
- src/GovUk.Education.ExploreEducationStatistics.Admin/Migrations/20200103131845_AddUserInviteTable.cs
- src/GovUk.Education.ExploreEducationStatistics.Admin/Services/EmailService.cs
- src/GovUk.Education.ExploreEducationStatistics.Admin/Services/IEmailService.cs
- src/GovUk.Education.ExploreEducationStatistics.Admin/Services/Interfaces/IUserManagementService.cs
- src/GovUk.Education.ExploreEducationStatistics.Admin/Services/UserManagementService.cs
- src/GovUk.Education.ExploreEducationStatistics.Admin/Startup.cs
- src/GovUk.Education.ExploreEducationStatistics.Admin/Validators/ValidationUtils.cs
- src/GovUk.Education.ExploreEducationStatistics.Admin/ViewModels/UserInvite.cs
- src/GovUk.Education.ExploreEducationStatistics.Admin/ViewModels/UserInviteViewModel.cs
- src/GovUk.Education.ExploreEducationStatistics.Admin/appsettings.Development.json
- src/explore-education-statistics-admin/src/pages/bau/BauUsersPage.tsx
- src/explore-education-statistics-admin/src/pages/users/PendingInvitesPage.tsx
- src/explore-education-statistics-admin/src/pages/users/UserInvitePage.tsx
- src/explore-education-statistics-admin/src/routes/dashboard/routes.ts
- src/explore-education-statistics-admin/src/services/users/service.ts
- src/explore-education-statistics-admin/src/services/users/types.ts
This add the user invite table and ui for inviting a user to the service
> EES-986 User invite UI and table

- src/explore-education-statistics-admin/src/pages/admin-dashboard/components/ManagePublicationsAndReleasesTab.tsx
Navigating to `/` or `/dashboard` will now fully load the page with themes, topics and publications
> EES-892 -  dashboard refreshing further fixes

- src/GovUk.Education.ExploreEducationStatistics.Admin/Startup.cs
This PR adds FootnoteService from the Data project back into the Admin project's Startup.cs
> EES-1064 - added Data projects FootnoteService back into DI

- src/explore-education-statistics-admin/src/components/WysiwygEditor.tsx
- src/explore-education-statistics-admin/src/components/wysiwyg.module.scss
- src/explore-education-statistics-admin/src/modules/find-statistics/components/DatablockSelectForm.tsx
- src/explore-education-statistics-admin/src/modules/find-statistics/components/KeyStatisticsSecondary.tsx
- src/explore-education-statistics-common/src/modules/find-statistics/components/DataBlock.tsx
see ticket: comments
https://alpha-dfe-data.atlassian.net/browse/EES-806
> EES-806 - ammendments

- src/GovUk.Education.ExploreEducationStatistics.Publisher/Functions/GenerateAllContentFunction.cs
- src/GovUk.Education.ExploreEducationStatistics.Publisher/Services/PublicationService.cs
Only included Topics/Themes/Publications if they have live releases or a legacy Publication URL
> EES-1040 Content generation fix

- infrastructure/templates/template.json
> EES-1086: add content subnet

- src/GovUk.Education.ExploreEducationStatistics.Admin/Pages/Shared/_Layout.cshtml
Updated feedback link was missing on admin login page
> EES-1026: add admin feedback to signin page

- infrastructure/templates/template.json
- src/GovUk.Education.ExploreEducationStatistics.Admin/web.config
Add admin redirect for production
Setup and assign subnets for public storage account
> Production ammendments

- src/explore-education-statistics-common/src/modules/find-statistics/components/ContentSubBlockRenderer.tsx
- src/explore-education-statistics-frontend/src/modules/find-statistics/PublicationReleasePage.tsx
This is a temporary solution for Monday
> EES-1117 - Release page render markdown

- src/explore-education-statistics-admin/src/pages/release/summary/ReleaseSummaryForm.tsx
View ticket comments
https://alpha-dfe-data.atlassian.net/browse/PP-216?atlOrigin=eyJpIjoiMjMyZGVlNzZlOGY4NGI0N2ExYWQyMjI5YWNmMTY3YTgiLCJwIjoiaiJ9
> PP-216 - Creating a release time period validation corrected

- src/GovUk.Education.ExploreEducationStatistics.Publisher.Tests/Services/MethodologyServiceTests.cs
- src/GovUk.Education.ExploreEducationStatistics.Publisher/MappingProfiles.cs
- src/GovUk.Education.ExploreEducationStatistics.Publisher/Services/ContentService.cs
- src/GovUk.Education.ExploreEducationStatistics.Publisher/Services/Interfaces/IMethodologyService.cs
- src/GovUk.Education.ExploreEducationStatistics.Publisher/Services/MethodologyService.cs
- src/GovUk.Education.ExploreEducationStatistics.Publisher/Services/ReleaseService.cs
- src/GovUk.Education.ExploreEducationStatistics.Publisher/ViewModels/MethodologySummaryViewModel.cs
- src/GovUk.Education.ExploreEducationStatistics.Publisher/ViewModels/MethodologyViewModel.cs
- src/GovUk.Education.ExploreEducationStatistics.Publisher/ViewModels/OtherReleaseViewModel.cs
- src/GovUk.Education.ExploreEducationStatistics.Publisher/ViewModels/PublicationViewModel.cs
Also a bit of EES-1200 which is renaming PreviousReleaseViewModel to OtherReleaseViewModel.
> Fix methodologies by introducing view model

- src/explore-education-statistics-common/src/services/publicationService.ts
- src/explore-education-statistics-frontend/src/modules/find-statistics/PublicationReleaseHelpAndSupportSection.tsx
- src/explore-education-statistics-frontend/src/modules/find-statistics/PublicationReleasePage.tsx
I also added in the methodology summary to the methodology accordion in help and support as it seemed a waste to not use the content there
> EES-1190 - Publication release page correct methodology slugs added

- src/explore-education-statistics-common/src/lib/utils/number/__tests__/formatPretty.test.ts
- src/explore-education-statistics-common/src/lib/utils/number/formatPretty.ts
- src/explore-education-statistics-common/src/modules/find-statistics/components/__tests__/__snapshots__/DataBlock.test.tsx.snap
- src/explore-education-statistics-common/src/modules/find-statistics/components/charts/ChartFunctions.tsx
- src/explore-education-statistics-common/src/modules/find-statistics/components/charts/MapBlock.tsx
- src/explore-education-statistics-common/src/modules/find-statistics/components/charts/__tests__/__snapshots__/MapBlock.test.tsx.snap
⚠️ **Depends on `run-script`**
> PP-230 Add 2 d.p formatting to tables/charts/maps

- src/explore-education-statistics-common/src/components/form/FormCheckboxGroup.tsx
- src/explore-education-statistics-common/src/components/form/FormRadioGroup.tsx
- src/explore-education-statistics-common/src/components/form/FormSelect.tsx
- src/explore-education-statistics-common/src/modules/table-tool/components/FiltersForm.tsx
- src/explore-education-statistics-common/src/modules/table-tool/components/LocationFiltersForm.tsx
- src/explore-education-statistics-common/src/modules/table-tool/components/PublicationForm.tsx
- src/explore-education-statistics-common/src/modules/table-tool/components/PublicationSubjectForm.tsx
- src/explore-education-statistics-common/src/modules/table-tool/components/TimePeriodForm.tsx
⚠️ **Depends on `run-script`**
> PP-111 Disable inputs when submitting table tool forms

- src/explore-education-statistics-admin/src/modules/find-statistics/components/AdminPublicationReleaseHelpAndSupportSection.tsx
This PR corrects the accordion title display in the admin application to match that that is displayed on the public applicaiton.
> EES-1222: methodolgy accordion title admin

- src/GovUk.Education.ExploreEducationStatistics.Admin.Tests/Services/MethodologyServiceTests.cs
- src/GovUk.Education.ExploreEducationStatistics.Admin/Models/Api/MethodologyViewModel.cs
This PR includes the status of the methodology in the methodoloy list api endpoint.
The status will still only ever by `Draft` or `Live` until full work on methodology status is complete
> EES-1237: Methodology List include status

- src/explore-education-statistics-common/src/modules/table-tool/components/TimePeriodForm.tsx
Reverts changes made for PP-190 as they introduce new problems in EES-1260. 
PP-190 will require a backend change to resolve.
> Revert "PP-190 - Time periods year given min length"

- useful-scripts/run.js
- Sets `ASPNETCORE_ENVIRONMENT` to `Development` by default
- Staggers execution of tasks to avoid race conditions when accessing files
> Improvements to run script

- src/explore-education-statistics-admin/src/modules/find-statistics/components/KeyIndicatorSelectForm.tsx
fixed logic around filtering key stat datablock list
> EES-1303 - key stat datablocks sometimes not listed

- src/GovUk.Education.ExploreEducationStatistics.Admin.Tests/Services/PublicationRepositoryTests.cs
- src/GovUk.Education.ExploreEducationStatistics.Admin.Tests/Services/ReleaseServiceTests.cs
- src/GovUk.Education.ExploreEducationStatistics.Admin/Migrations/ContentMigrations/20200214160903_UpdateDataBlockFields.Designer.cs
- src/GovUk.Education.ExploreEducationStatistics.Admin/Migrations/ContentMigrations/20200214160903_UpdateDataBlockFields.cs
- src/GovUk.Education.ExploreEducationStatistics.Admin/Migrations/ContentMigrations/20200214161615_RemoveOrderFromRelease.Designer.cs
- src/GovUk.Education.ExploreEducationStatistics.Admin/Migrations/ContentMigrations/20200214161615_RemoveOrderFromRelease.cs
- src/GovUk.Education.ExploreEducationStatistics.Admin/Services/ReleaseService.cs
- src/GovUk.Education.ExploreEducationStatistics.Content.Model/Publication.cs
- src/GovUk.Education.ExploreEducationStatistics.Content.Model/Release.cs
Removing order field from Release. Use LatestRelease field of Publication instead which has been updated to order releases by year and time period.
> Bugfix/ees-1316 Order of Releases (Admin)

- src/explore-education-statistics-admin/src/pages/methodology/edit-methodology/content/MethodologyContentPage.tsx
wrapped the editing context and control around the methodology content being edited
> EES-1355 - editing context & control added

- src/explore-education-statistics-admin/src/pages/methodology/edit-methodology/MethodologyPage.tsx
- src/explore-education-statistics-admin/src/pages/methodology/edit-methodology/content/MethodologyContentPage.tsx
- src/explore-education-statistics-admin/src/pages/release/edit-release/content/ReleaseContentPage.tsx
- src/explore-education-statistics-admin/src/services/methodology/service.ts
- src/explore-education-statistics-admin/src/services/methodology/types.ts
- src/explore-education-statistics-admin/src/styles/patterns/_dfe-modifiers.scss
- src/explore-education-statistics-admin/src/styles/patterns/editor.scss
CRU for content sections in methodology content
Delete isnt implemnted yet
> EES-1356 Add, Rename and Reorder methodology content accordion sections

- src/explore-education-statistics-admin/src/components/EditableAccordionSection.tsx
- src/explore-education-statistics-admin/src/modules/find-statistics/components/ReleaseContentAccordion.tsx
- src/explore-education-statistics-admin/src/modules/find-statistics/components/ReleaseContentAccordionSection.tsx
- src/explore-education-statistics-admin/src/pages/methodology/edit-methodology/MethodologyPage.tsx
- src/explore-education-statistics-admin/src/pages/methodology/edit-methodology/content/MethodologyContentPage.tsx
- src/explore-education-statistics-admin/src/pages/release/edit-release/content/ReleaseContentPage.tsx
- src/explore-education-statistics-admin/src/services/methodology/service.ts
- src/explore-education-statistics-admin/src/services/methodology/types.ts
- src/explore-education-statistics-admin/src/services/release/edit-release/content/service.ts
- src/explore-education-statistics-admin/src/styles/patterns/_dfe-modifiers.scss
- src/explore-education-statistics-admin/src/styles/patterns/editor.scss
Also added the ability to remove content sections in release content too
> EES-1359 - Methodology content - remove accordion sections

- src/explore-education-statistics-admin/src/components/footnotes/form/FootnoteForm.tsx
Updated labelling to make 'select all' option a little more intuitive
> PP-309 Updates to footnotes structure

- src/GovUk.Education.ExploreEducationStatistics.Admin/web.config
Redirect azure and hive domain on dev to new gov.uk domain
> EES-1498 redirect hive to gov.uk domain on dev

- src/explore-education-statistics-frontend/src/modules/glossary/GlossaryIndexPage.tsx
- Removed TBCs, replaced with text saying there is no entries for that
letter
- Added some text at the top of the page to explain that the glossary
will be populated over time
> EES-1491 Update Glossary

- src/explore-education-statistics-admin/src/components/EditableAccordionSection.tsx
- src/explore-education-statistics-admin/src/modules/find-statistics/components/ReleaseContentAccordionSection.tsx
Updated text on CTAs for accordions, also increased the width of the accordion title input
> BAU-411 Label update

- src/GovUk.Education.ExploreEducationStatistics.Data.Model/Filter.cs
- src/GovUk.Education.ExploreEducationStatistics.Data.Model/FilterGroup.cs
- src/GovUk.Education.ExploreEducationStatistics.Data.Model/Services/FilterItemService.cs
- src/GovUk.Education.ExploreEducationStatistics.Data.Services/AbstractTableBuilderSubjectMetaService.cs
Fixes the FilterGroup grouping using an equality comparer.
> EES-706 Total filter not being selected

- infrastructure/parameters/prod.parameters.json
This enables the public facing application.
> Disable basic auth in production

- src/GovUk.Education.ExploreEducationStatistics.Data.Model/Migrations/20200325150211_FootnoteData.sql
This fixes the problem with the Admin failing to start up in some environments due to more than one Subject with the same name.
> EES-1563 Join by Subject Id rather than Name which is unsafe

- src/explore-education-statistics-admin/src/modules/find-statistics/PublicationReleaseContent.tsx
- src/explore-education-statistics-frontend/src/modules/find-statistics/PublicationReleasePage.tsx
Altered label as suggested by @cjrace
> BAU-452 Genericising downloads label

- src/explore-education-statistics-frontend/src/modules/glossary/GlossaryIndexPage.tsx
Link was previously going to the prototype.
> BAU-461 Fix Pupil Absence methodology link

- src/explore-education-statistics-admin/src/pages/theme/topic/CreatePublicationPage.tsx
- src/explore-education-statistics-admin/src/services/edit-publication/service.ts
Made the methodology select list identical to the methodology assign form in the publication create form
> EES-1330 - showing methodology status in methodology select

- src/explore-education-statistics-admin/src/components/ReleaseServiceStatus.tsx
- src/explore-education-statistics-admin/src/pages/admin-dashboard/components/ReleaseSummary.tsx
added logic, release status only requested when release is approved
> EES-1134 - release process status no longer displayed before release is approved

- src/explore-education-statistics-admin/src/pages/theme/topic/CreatePublicationPage.tsx
- src/explore-education-statistics-admin/src/pages/theme/topic/publication/AssignMethodologyForm.tsx
filtered out draft methodologies from the methodology assignment options list
> EES-1131 - Draft methodologies in methodology assingment list

- src/explore-education-statistics-admin/src/pages/release/prerelease/PreReleasePage.tsx
fixed up the prerelease text to display publication and release titles in the message
> EES-573 - Pre Release Before/After message text update

- infrastructure/parameters/pre-prod.parameters.json
This PR updates the arm template parameters for the pre-prod environments domains
> BAU-603: Update Pre-prod domains

- src/explore-education-statistics-admin/src/modules/find-statistics/PublicationReleaseContent.tsx
- src/explore-education-statistics-admin/src/modules/find-statistics/components/ReleaseHeadlines.tsx
The content for these sections was being stored locally in the component parent. So I have added a useEffect to watch for content changes and will update the local state if it changes.
> EES-646 - summary/headline block add bugfix (block is added as expected)

- src/explore-education-statistics-common/src/polyfill.js
imported immers `enableES5()` function for the polyfill in common
> EES-714 - Immer Polyfill (fix IE frontend errors)

- src/explore-education-statistics-common/src/modules/charts/components/MapBlockInternal.tsx
This PR also fixes colouring of features that have missing data as well. Locations that don't have matching data will appear white.
> EES-736 Fix map block error when categories are missing selected data set

- src/GovUk.Education.ExploreEducationStatistics.Admin/Services/DataBlockMigrationService.cs
> EES-812 Only query subject meta by subject Id and cache it

- infrastructure/templates/template.json
- src/GovUk.Education.ExploreEducationStatistics.Publisher/local.settings.json
Sets the timezone of the publisher function to GMT
> EES-816: Set publisher timezone

- src/GovUk.Education.ExploreEducationStatistics.Admin.Tests/Controllers/Api/ConfigurationControllerTests.cs
- src/GovUk.Education.ExploreEducationStatistics.Admin.Tests/Controllers/Api/PreReleaseControllerTests.cs
- src/GovUk.Education.ExploreEducationStatistics.Admin.Tests/Services/PreReleaseServiceTests.cs
- src/GovUk.Education.ExploreEducationStatistics.Admin/Controllers/Api/ConfigurationController.cs
- src/GovUk.Education.ExploreEducationStatistics.Admin/Services/PreReleaseService.cs
- src/GovUk.Education.ExploreEducationStatistics.Admin/ViewModels/PreReleaseSummaryViewModel.cs
- src/explore-education-statistics-admin/src/services/pre-release/preReleaseService.ts
- Add Publication Slug to PreReleaseSummaryViewModel
- Add new Config endpoint to expose some of the Admin application config.
> EES-638 PreRelease improvements

- src/GovUk.Education.ExploreEducationStatistics.Content.Model/Database/ContentDbContext.cs
- src/GovUk.Education.ExploreEducationStatistics.Publisher/Services/ReleaseStatusService.cs
I have taken one of the comments mentioned in this EF Core issue https://github.com/dotnet/efcore/issues/4711
to address the problems that I mention in the comments of 
https://github.com/dfe-analytical-services/explore-education-statistics/pull/1665
> EES-857 Specify database conversion with DateTimeKind UTC on Release.PublishScheduled

- src/GovUk.Education.ExploreEducationStatistics.Data.Api/GovUk.Education.ExploreEducationStatistics.Data.Api.csproj
- src/GovUk.Education.ExploreEducationStatistics.Data.Api/Program.cs
Configure logging as mentioned on this [page](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/logging/?view=aspnetcore-2.2#azure-app-service-provider)
> EES-778 Configuring Azure App Service Provider logging

- src/GovUk.Education.ExploreEducationStatistics.Admin/Controllers/Api/Methodologies/UpdateMethodologyRequest.cs
- src/GovUk.Education.ExploreEducationStatistics.Admin/Services/Interfaces/Security/UserServiceExtensionMethods.cs
- src/GovUk.Education.ExploreEducationStatistics.Admin/Services/Methodologies/MethodologyService.cs
Inlining the check for updating Methodology status in to MethodologyService since UserServiceExtensionMethods isn't responsible for that.
> EES-919 Security around updating methodology

- src/explore-education-statistics-frontend/src/modules/find-statistics/PublicationReleasePage.tsx
Using the Release page file path as per https://github.com/dfe-analytical-services/explore-education-statistics/pull/1686
> EES-946 Using the Release page file path

- src/GovUk.Education.ExploreEducationStatistics.Publisher/Models/CopyReleaseFilesCommand.cs
- src/GovUk.Education.ExploreEducationStatistics.Publisher/Services/ContentService.cs
- src/GovUk.Education.ExploreEducationStatistics.Publisher/Services/FileStorageService.cs
- src/GovUk.Education.ExploreEducationStatistics.Publisher/Services/Interfaces/IFileStorageService.cs
- src/GovUk.Education.ExploreEducationStatistics.Publisher/Services/PublishingService.cs
- src/GovUk.Education.ExploreEducationStatistics.Publisher/Services/ZipFileUtil.cs
Excludes the charts directory from the source files transferred to the public which are zipped during publishing.
> EES-945 Don't zip infographics files in the charts directory

- tests/newman/tests/admin-api-dev.json
> EES-975 Fix various failing Admin API (Dev) Tests

- src/GovUk.Education.ExploreEducationStatistics.Admin/GovUk.Education.ExploreEducationStatistics.Admin.csproj
- src/GovUk.Education.ExploreEducationStatistics.Admin/Services/LoggingNotificationClient.cs
- src/GovUk.Education.ExploreEducationStatistics.Notifier/GovUk.Education.ExploreEducationStatistics.Notifier.csproj
This PR update the GOV.UK notify package to the latest version
> EES-868: Update GOV.UK notify to latest version 2.8.0

- src/GovUk.Education.ExploreEducationStatistics.Common.Tests/Services/TimePeriodLabelFormatterTests.cs
- src/GovUk.Education.ExploreEducationStatistics.Common/Model/TimeIdentifier.cs
- src/GovUk.Education.ExploreEducationStatistics.Common/Model/TimeIdentifierCategory.cs
- src/GovUk.Education.ExploreEducationStatistics.Data.Services.Tests/Extensions/TimeIdentifierExtensionsTests.cs
- src/GovUk.Education.ExploreEducationStatistics.Data.Services.Tests/TimeIdentifierUtilTests.cs
- src/GovUk.Education.ExploreEducationStatistics.Data.Services.Tests/TimePeriodUtilTests.cs
- src/GovUk.Education.ExploreEducationStatistics.Data.Services/Extensions/TimeIdentifierExtensions.cs
- src/GovUk.Education.ExploreEducationStatistics.Data.Services/TimeIdentifierUtil.cs
- src/explore-education-statistics-admin/src/pages/release/summary/ReleaseSummaryForm.tsx
Adds support for weekly data and releases
> EES-1015 Adding support for weekly data and releases

- src/GovUk.Education.ExploreEducationStatistics.Admin/Controllers/Api/PublicationController.cs
- src/GovUk.Education.ExploreEducationStatistics.Admin/Controllers/Api/ReleaseController.cs
- src/explore-education-statistics-admin/src/services/releaseDataFileService.ts
Use query param for the subject title when requesting the delete plan or deleting the file since the title can contain an unencoded '/'.
> EES-1031 Use query param for the subject title

- src/GovUk.Education.ExploreEducationStatistics.Notifier/PublicationNotifier.cs
- src/GovUk.Education.ExploreEducationStatistics.Notifier/Services/EmailService.cs
- src/GovUk.Education.ExploreEducationStatistics.Notifier/Services/TokenService.cs
Tidying up the Notifier logging.
> EES-1107 Tidy up Notifier logging

- src/explore-education-statistics-common/src/modules/table-tool/components/DownloadCsvButton.tsx
- src/explore-education-statistics-common/src/modules/table-tool/components/__tests__/DownloadCsvButton.test.tsx
- src/explore-education-statistics-common/src/modules/table-tool/components/__tests__/__snapshots__/DownloadCsvButton.test.tsx.snap
This was due to incorrect filtering criteria on location levels.
> EES-1111 Fix table tool CSV returning incorrectly matched results

- src/GovUk.Education.ExploreEducationStatistics.Admin/Controllers/Api/AmendmentMigrationController.cs
- src/GovUk.Education.ExploreEducationStatistics.Admin/Services/AmendmentMigrationService.cs
- src/GovUk.Education.ExploreEducationStatistics.Admin/Services/Interfaces/IAmendmentMigrationService.cs
- src/GovUk.Education.ExploreEducationStatistics.Admin/Startup.cs
This PR is to add a temporary endpoint to allow us to fix the existing ReleaseFileReference rows which have a null subjectid.
> EES-1115 Add temporary endpoint to allow update of missing subject ids.

- src/GovUk.Education.ExploreEducationStatistics.Admin/GovUk.Education.ExploreEducationStatistics.Admin.csproj
- src/GovUk.Education.ExploreEducationStatistics.Content.Api/GovUk.Education.ExploreEducationStatistics.Content.Api.csproj
- src/GovUk.Education.ExploreEducationStatistics.Data.Api/GovUk.Education.ExploreEducationStatistics.Data.Api.csproj
Attempting to get rid of startup error exception by installing Microsoft.AspNetCore.AzureAppServices.HostingStartup
This is a solution mentioned in https://github.com/dotnet/aspnetcore/issues/14547 to resolve the error
> EES-1061 Attempting to get rid of startup error exception by installing Microsoft.AspNetCore.AzureAppServices.HostingStartup

- src/GovUk.Education.ExploreEducationStatistics.Publisher.Model/ViewModels/DataBlockViewModel.cs
Not maintaining compatibility as we have agreed we will republish the content of all Releases during deployment.
> EES-1136 FastTrack changes tidy up

- tests/newman/tests/admin-api-dev.json
- tests/newman/tests/admin-api.json
- tests/newman/tests/data-api.json
> API Test fixes

- tests/robot-tests/run_tests.py
With the new Admin API endpoint to create a theme, the UI tests have been updated so that if "Test theme" doesn't already exists, it will be automatically created. 
This change fetches the existing "Test theme"'s GUID, so it is no longer hardcoded into the UI tests run script.
> EES-1106 UI tests should use or create Test theme

- src/GovUk.Education.ExploreEducationStatistics.Admin.Tests/Controllers/Api/BAU/UserManagement/UsersControllerTests.cs
- src/GovUk.Education.ExploreEducationStatistics.Admin/Controllers/Api/UserManagement/UsersController.cs
- src/GovUk.Education.ExploreEducationStatistics.Admin/Services/Interfaces/IUserManagementService.cs
- src/GovUk.Education.ExploreEducationStatistics.Admin/Services/UserManagementService.cs
- src/explore-education-statistics-admin/src/services/userService.ts
Not related to amendments - don't think the delete ever worked.
> EES-1067 Fix delete of UserReleaseRole.

- src/GovUk.Education.ExploreEducationStatistics.Common/Services/TableStorageService.cs
- src/GovUk.Education.ExploreEducationStatistics.Publisher/Services/ContentService.cs
* Create table if it doesn't already exist. Fixes an error publishing a release with a new local environment.
* Correct public Release path in blob storage
> EES-1167 Correct public Release path in blob storage

- tests/robot-tests/run_tests.py
- tests/robot-tests/tests/admin/bau/create_publication_and_release.robot
- tests/robot-tests/tests/admin/bau/release_status.robot
- tests/robot-tests/tests/admin_and_public/bau/publish_data.robot
- tests/robot-tests/tests/libs/admin-common.robot
- tests/robot-tests/tests/libs/common.robot
- tests/robot-tests/tests/libs/utilities.py
This doesn't fix all the UI tests and I haven't run them against the pipeline, but since I'm on holiday for the rest of the week I thought I'd create the PR anyway rather than just have them be left and potentially forgotten about.
> Fixes for UI tests

- src/explore-education-statistics-admin/src/routes/releaseRoutes.ts
- src/explore-education-statistics-common/src/components/ButtonGroup.module.scss
This PR also fixes `ButtonGroup`  buttons not aligning correctly due to its child selector not being specific enough.
> EES-1211 Fix 'Edit release summary' route missing correct component

- src/GovUk.Education.ExploreEducationStatistics.Admin/Migrations/ContentMigrations/ContentDbContextModelSnapshot.cs
- src/GovUk.Education.ExploreEducationStatistics.Content.Model/Database/ContentDbContext.cs
Remove ValueGenerateOnAdd from Methodology.Status. 
Causes a bug generating a change only in the Down method. See https://github.com/dotnet/efcore/issues/21661
> EES-1252 Remove ValueGenerateOnAdd from Methodology.Status. 

- src/explore-education-statistics-common/src/modules/charts/util/chartUtils.ts
Updated ordering of colours, removed those that were too close with contrast
> Ees 1325 add more colors to default chart styling

- src/explore-education-statistics-admin/src/pages/documentation/DocumentationManageData.tsx
- src/explore-education-statistics-admin/src/pages/release/data/components/ReleaseDataUploadsSection.tsx
- src/explore-education-statistics-admin/src/prototypes/components/PrototypeDataReplace.tsx
- src/explore-education-statistics-frontend/src/modules/download/components/PublicationDownloadList.tsx
Update links to R Project to new web app. And trigger analytics event when user downloads a file from the Download latest data page..
> EES-1379 and EES-1376

- src/GovUk.Education.ExploreEducationStatistics.Publisher/Services/FileStorageService.cs
This PR fixes the publisher's `NotifyChange` function throwing 409 errors saying 'The specified blob already exists'. This was due to attempting to upload the lease file again even if it already exists. We now check that it doesn't exists before uploading it.
> EES-1400 Fix AcquireLease method throwing error when lease file exists

- src/GovUk.Education.ExploreEducationStatistics.Publisher/Services/FileStorageService.cs
Copy of f5f61e10c5c99babb48995541840569d401c16c6
> Hotfix/EES-1469 Fix original ancillary files not being published for amendment.

- src/explore-education-statistics-frontend/server.js
This PR fixes CSP errors being thrown in production for Google Analytics.
> EES-1471 Add connect-src directive for Google Analytics

- infrastructure/parameters/dev.parameters.json
- infrastructure/parameters/pre-prod.parameters.json
- infrastructure/parameters/prod.parameters.json
- infrastructure/parameters/test.parameters.json
- infrastructure/templates/template.json
This is experimental as unsure yet whether serverless model is fully supported by the arm templates - will try in dev & test.
> EES-1249 Change template to use serverless db model.

- src/explore-education-statistics-common/src/modules/table-tool/components/DataTableCaption.tsx
- src/explore-education-statistics-common/src/modules/table-tool/components/__tests__/DataTableCaption.test.tsx
- src/explore-education-statistics-frontend/src/modules/permalink/__tests__/PermalinkPage.test.tsx
- tests/robot-tests/tests/admin/bau/create_data_block_with_chart.robot
- tests/robot-tests/tests/admin/bau/delete_subject.robot
- tests/robot-tests/tests/admin_and_public/bau/publish_data.robot
- tests/robot-tests/tests/admin_and_public/bau/publish_release_and_amend.robot
- tests/robot-tests/tests/general_public/permalink_prod_1.robot
- tests/robot-tests/tests/general_public/permalink_prod_2.robot
- tests/robot-tests/tests/general_public/permalink_prod_3.robot
- tests/robot-tests/tests/general_public/release_page_absence.robot
- tests/robot-tests/tests/general_public/table_tool_absence_in_prus.robot
- tests/robot-tests/tests/general_public/table_tool_exclusions_by_geographic_level.robot
Filters added to table caption title
> EES-1441 - Adding more information to table tool / permalink generated titles

- tests/robot-tests/run_tests.py
- tests/robot-tests/tests/general_public/methodology_page_absence.robot
- tests/robot-tests/tests/libs/common.robot
Also fixed broken UI tests on the pipeline due to not clearing text fields.
> EES-1534 Chromedriver filename should be OS dependent

- tests/newman/tests/data-api.json
Some tests I've commented out rather than removed in anticipation of the Public API being implemented.
> EES-1496 Update Data API tests for new optimised SQL query

- tests/robot-tests/tests/admin/bau/admin_dashboard_page.robot
- tests/robot-tests/tests/admin_and_public/bau/footnotes.robot
- tests/robot-tests/tests/admin_and_public/bau/publish_data.robot
- tests/robot-tests/tests/admin_and_public/bau/publish_release_and_amend.robot
- tests/robot-tests/tests/general_public/glossary_page.robot
- tests/robot-tests/tests/general_public/methodology_page_absence.robot
- tests/robot-tests/tests/general_public/miscellaneous.robot
- tests/robot-tests/tests/general_public/notifications_absence.robot
- tests/robot-tests/tests/general_public/release_page_absence.robot
- tests/robot-tests/tests/general_public/table_tool_absence_by_characteristic.robot
- tests/robot-tests/tests/general_public/table_tool_absence_in_prus.robot
- tests/robot-tests/tests/general_public/table_tool_exclusions_by_geographic_level.robot
- Remove hardcoded `Test theme` where possible
- Use `id:` instead of `css:#` where possible
> EES-1536 Various UI Test cleanups

- src/explore-education-statistics-admin/src/pages/release/components/ReleaseSummaryForm.tsx
- src/explore-education-statistics-admin/src/pages/release/components/__tests__/ReleaseSummaryForm.test.tsx
[Ticket 1447](https://dfedigital.atlassian.net/browse/EES-1447)
Fixes:
- Added additional validation to year field, checking year has 4 characters
> EES-1447 - Create release time identifier error

- src/explore-education-statistics-admin/src/pages/admin-dashboard/components/PublicationSummary.tsx
- src/explore-education-statistics-admin/src/pages/release/ReleasePreReleaseAccessPage.tsx
- src/explore-education-statistics-admin/src/pages/release/components/PublicPreReleaseAccessForm.tsx
- src/explore-education-statistics-admin/src/pages/release/components/__tests__/PublicPreReleaseAccessForm.test.tsx
- src/explore-education-statistics-admin/src/pages/release/data/__tests__/ReleaseDataFilePage.test.tsx
- src/explore-education-statistics-admin/src/pages/release/data/components/ImporterStatus.tsx
- src/explore-education-statistics-admin/src/pages/release/data/components/__tests__/ImporterStatus.test.tsx
- src/explore-education-statistics-admin/src/pages/release/data/components/__tests__/ReleaseDataUploadsSection.test.tsx
- src/explore-education-statistics-admin/src/services/releaseDataFileService.ts
- src/explore-education-statistics-common/src/components/ProgressBar.module.scss
- src/explore-education-statistics-common/src/components/ProgressBar.tsx
- src/explore-education-statistics-common/src/components/__tests__/ProgressBar.test.tsx
This PR adds the following progress bar to data files whilst they are importing:
> EES-1571 Add progress bar to data file imports

- src/explore-education-statistics-common/src/modules/find-statistics/components/ContactUsSection.tsx
Altering Press Office telephone number
> EES-1622 Altering Press Office telephone number

- src/explore-education-statistics-frontend/src/html/glossary/C.html
- src/explore-education-statistics-frontend/src/html/glossary/D.html
- src/explore-education-statistics-frontend/src/html/glossary/E.html
- src/explore-education-statistics-frontend/src/html/glossary/I.html
- src/explore-education-statistics-frontend/src/html/glossary/L.html
- src/explore-education-statistics-frontend/src/html/glossary/N.html
- src/explore-education-statistics-frontend/src/html/glossary/R.html
- src/explore-education-statistics-frontend/src/html/glossary/S.html
- src/explore-education-statistics-frontend/src/html/glossary/U.html
Updates to the .html files that are used to supply the content for the glossary based on the current word document sent across by the HoP office.
> initial updates to glossary

- src/GovUk.Education.ExploreEducationStatistics.Admin.Tests/Services/ReplacementServiceTests.cs
- src/GovUk.Education.ExploreEducationStatistics.Admin/Services/ReplacementService.cs
This PR fixes charts being broken after a data replacement due to none of the chart's data sets being replaced. This meant that chart data sets were referencing the original (non-existing) filters and indicators. This functionality was overlooked in the initial replacement work so I've simply added it in.
> EES-1633 Fix data replacement not occurring for data block charts

- src/GovUk.Education.ExploreEducationStatistics.Admin/Services/ReplacementService.cs
- src/GovUk.Education.ExploreEducationStatistics.Data.Model/Services/FootnoteService.cs
Merge the hotfix for EES-1654 back into dev
> EES-1654 Merge Master into Dev

- infrastructure/templates/template.json
- src/GovUk.Education.ExploreEducationStatistics.Content.Api/GovUk.Education.ExploreEducationStatistics.Content.Api.csproj
- src/GovUk.Education.ExploreEducationStatistics.Content.Api/Startup.cs
- src/GovUk.Education.ExploreEducationStatistics.Content.Api/appsettings.Development.json
- src/GovUk.Education.ExploreEducationStatistics.Data.Api/GovUk.Education.ExploreEducationStatistics.Data.Api.csproj
- src/GovUk.Education.ExploreEducationStatistics.Data.Api/Startup.cs
- src/GovUk.Education.ExploreEducationStatistics.Data.Api/appsettings.Development.json
- src/GovUk.Education.ExploreEducationStatistics.Data.Services/GovUk.Education.ExploreEducationStatistics.Data.Services.csproj
This PR adds connection strings for the content database for the content and data APIs.
> EES-1731, EES-1732 Add connections to content DB from public APIs

- src/explore-education-statistics-frontend/src/html/glossary/D.html
Adding definitions for 'Device' and 'Delivered or dispatched' to the glossary. Intended definitions below:
- Device - a laptop or tablet along with a protective sleeve and software/operating licences. 
- Delivered or dispatched - the device has been dispatched from the storage facility or is in transit awaiting delivery on a date specified by the recipient. Shipments are running on a next business day delivery basis and two redelivery attempts are made before the delivery is returned.
> adding device and delivered definitions

- infrastructure/parameters/prod.parameters.json
- infrastructure/templates/template.json
This reverts commit 95bb6ebb912db4eac771b0c7ca9b46b97807b535.
> EES-1380 Readd Serverless vcore I/O changes

- infrastructure/templates/datafactory/components/db-maintenance-template.json
This PR fixes the incorrectly named variable being passed to the new stored procedure.
> EES-1830 - fixed incorrectly named pipeline variable

- src/GovUk.Education.ExploreEducationStatistics.Admin/Areas/Identity/Data/UsersAndRolesDbContext.cs
- src/GovUk.Education.ExploreEducationStatistics.Admin/Migrations/20210205154350_ESS1854UpdateDefaultUsersEmails.Designer.cs
- src/GovUk.Education.ExploreEducationStatistics.Admin/Migrations/20210205154350_ESS1854UpdateDefaultUsersEmails.cs
- src/GovUk.Education.ExploreEducationStatistics.Admin/Migrations/ContentMigrations/20210205154613_EES1854RenameDefaultUsersEmails.Designer.cs
- src/GovUk.Education.ExploreEducationStatistics.Admin/Migrations/ContentMigrations/20210205154613_EES1854RenameDefaultUsersEmails.cs
- src/GovUk.Education.ExploreEducationStatistics.Content.Model/Database/ContentDbContext.cs
- src/explore-education-statistics-admin/src/pages/release/pre-release/components/PreReleaseUserAccessForm.tsx
- tests/robot-tests/tests/admin/bau/prerelease.robot
We're updating the default users' email addresses so that the prerelease UI tests can work, due to the service now only allowing emails ending in @education.gov.uk
> EES-1854 Change default users emails

- tests/robot-tests/tests/admin_and_public/bau/prerelease_visibility.robot
This PR: 
- Fixes typo in filename of this test (prelease_visiblity > prerelease_visibility) 
- Fixes failing UI test (on pipeline) by adding a more generous timeout on line 46
> EES-1916 fix pre-release visibility UI test

- src/explore-education-statistics-admin/src/pages/release/ReleaseSummaryPage.tsx
- src/explore-education-statistics-admin/src/services/releaseService.ts
Fixes incorrect output in release summary
Details explained here in comments:
https://dfedigital.atlassian.net/browse/EES-1508?atlOrigin=eyJpIjoiYTkyYTQxYmJlZjNiNDk3YTg4ZWE3MGZhZjcyNTVhZDEiLCJwIjoiaiJ9
> EES-1508 - Release summary make it more obvious whats editable

- src/explore-education-statistics-common/src/validation/__tests__/serverValidations.test.ts
- src/explore-education-statistics-common/src/validation/serverValidations.ts
This change allows us to map server field validation error messages to a different field without needing it to match one of the `messages`.
For example, we can directly use the error message for a `name` field, and map it to the `firstName` form field.
> EES-1918 Allow mapping of server field errors without `messages`

- tests/robot-tests/tests/admin/bau/legacy_releases.robot
> EES-1506 - Add manage publication page

- src/explore-education-statistics-admin/config/webpack.config.js
This reverts commit f33fe22074019f58a2c163847110ce76a392854d.
> Revert "fix: re-add missing Stylelint plugin to admin Webpack config"

- src/explore-education-statistics-admin/src/components/form/FormEditor.tsx
- src/explore-education-statistics-admin/src/types/ckeditor.ts
> EES-1930 Add table balloon options for rows/columns and merging

- src/GovUk.Education.ExploreEducationStatistics.Admin/Startup.cs
Prior to this change both the IBlobStorageService candidate configured with the private connection string was being injected into both `privateBlobStorageService` and `publicBlobStorageService` when setting up the `MigrateFilesService`. 
This change sets up a separate private and public service each with the correct connection string.
> EES-1705 Configure MigrateFilesService with the correct public storage account.

- src/GovUk.Education.ExploreEducationStatistics.Data.Model/Migrations/20210302000000_AddMandatoryObservationRowConstraints.sql
Corrected foreign key existence checks
> EES-1836 - corrected foreign key existence checks in migration file

- infrastructure/templates/template.json
> EES-1946 - setup arm template for alerts

- src/explore-education-statistics-admin/src/pages/release/data/components/ReleaseDataUploadsSection.tsx
Increases the width of the Subject title to two-thirds.
> EES-1813 Increase data upload subject title input width

- src/explore-education-statistics-frontend/src/modules/find-statistics/PublicationReleasePage.tsx
Order the release notes by date, most recent first.
> EES-2034 order release notes by date

- src/explore-education-statistics-common/src/modules/table-tool/components/SubjectStep.tsx
- src/explore-education-statistics-common/src/modules/table-tool/components/TableToolWizard.tsx
- src/explore-education-statistics-frontend/src/modules/table-tool/TableToolPage.tsx
Show a loader during the short delay when a featured table is clicked.
> EES-1858 Show loader when click featured table

- src/explore-education-statistics-common/src/modules/charts/components/HorizontalBarBlock.tsx
Removes the left padding which puts a gap before 0 on the x axis.
> EES-1322 start horizontal chart x-axis at 0

- src/explore-education-statistics-frontend/src/html/glossary/O.html
Adding definition to the glossary as per the ticket - https://dfedigital.atlassian.net/browse/EES-2109
Should be linkable using this url - https://explore-education-statistics.service.gov.uk/glossary#otherwise-vulnerable
> EES-2109 Add otherwise vulnerable definition to glossary

- src/explore-education-statistics-admin/src/pages/release/datablocks/components/DataBlockSourceWizard.tsx
> EES-2070 show warning when editing block with chart

- package-lock.json
- package.json
- src/explore-education-statistics-admin/package-lock.json
- src/explore-education-statistics-admin/package.json
- src/explore-education-statistics-common/package-lock.json
- src/explore-education-statistics-common/package.json
- src/explore-education-statistics-frontend/package-lock.json
- src/explore-education-statistics-frontend/package.json
Updates:
- immer
- stylelint
- marked
- react-dev-utils
I couldn't see any problems building and running the frontend and admin apps after updating these.
> EES-2126 update dependencies

- src/explore-education-statistics-admin/src/components/PageHeader.tsx
Makes the menu button that shows on small screens open the navigation.
> EES-1817 fix admin menu button

- src/explore-education-statistics-frontend/src/modules/find-statistics/components/PublicationList.tsx
- tests/robot-tests/tests/admin/analyst/analyst_absence_permissions.robot
- tests/robot-tests/tests/admin_and_public/bau/publish_release_and_amend.robot
- tests/robot-tests/tests/general_public/notifications_absence.robot
- tests/robot-tests/tests/general_public/release_page_absence.robot
> EES-2223 - Fix UI test failures

- infrastructure/templates/template.json
The work to prevent these false-positive alerts and enable them again is covered in EES-2260.
> EES-2118 Comment out false-positive alerts

- src/explore-education-statistics-admin/src/pages/users/ManageUserPage.tsx
- src/explore-education-statistics-admin/src/pages/users/UserInvitePage.tsx
- src/explore-education-statistics-admin/src/pages/users/components/PublicationAccessForm.tsx
- src/explore-education-statistics-admin/src/pages/users/components/ReleaseAccessForm.tsx
- src/explore-education-statistics-admin/src/pages/users/components/RoleForm.tsx
- src/explore-education-statistics-admin/src/pages/users/components/__tests__/PublicationAccessForm.test.tsx
- src/explore-education-statistics-admin/src/pages/users/components/__tests__/ReleaseAccessForm.test.tsx
- src/explore-education-statistics-admin/src/pages/users/components/__tests__/RoleForm.test.tsx
- src/explore-education-statistics-admin/src/services/userService.ts
Will need checking once the BE work is completed, but hopefully will work!
> EES-2135 publication access form

- src/explore-education-statistics-common/src/modules/charts/components/HorizontalBarBlock.tsx
- src/explore-education-statistics-common/src/modules/charts/components/LineChartBlock.tsx
- src/explore-education-statistics-common/src/modules/charts/components/VerticalBarBlock.tsx
- src/explore-education-statistics-common/src/modules/charts/util/getUnitOrDefault.ts
- src/explore-education-statistics-common/src/utils/number/__tests__/formatPretty.test.ts
- src/explore-education-statistics-common/src/utils/number/formatPretty.ts
Turns out there was code to do this already! I've adapted it slightly to handle negative £ values and added some extra tests.
> EES-2278 format £ units on charts

- src/GovUk.Education.ExploreEducationStatistics.Admin/Services/BootstrapUsersService.cs
- src/GovUk.Education.ExploreEducationStatistics.Admin/Startup.cs
This PR:
- refactors BootstrapUserUtil static utility class to be proper DI service
> EES-2107 - refactored BootstrapUserUtil static utility class to be proper DI service

- src/explore-education-statistics-frontend/src/modules/table-tool/__tests__/__snapshots__/TableToolPage.test.tsx.snap
- src/explore-education-statistics-frontend/src/modules/table-tool/components/TableToolFinalStep.tsx
- src/explore-education-statistics-frontend/src/modules/table-tool/components/__tests__/TableToolFinalStep.test.tsx
- src/explore-education-statistics-frontend/src/modules/table-tool/components/__tests__/__snapshots__/TableToolFinalStep.test.tsx.snap
Adds contact info for the publication to the table tool final step.
> EES-412 add contact details to table tool

- src/explore-education-statistics-admin/src/pages/admin-dashboard/components/ManagePublicationsAndReleasesTab.tsx
- src/explore-education-statistics-admin/src/pages/admin-dashboard/components/MethodologyExternalLinkForm.tsx
- src/explore-education-statistics-admin/src/pages/admin-dashboard/components/MethodologySummary.tsx
- src/explore-education-statistics-admin/src/pages/admin-dashboard/components/PublicationSummary.tsx
- src/explore-education-statistics-admin/src/pages/admin-dashboard/components/__tests__/MethodologyExternalLinkForm.test.tsx
- src/explore-education-statistics-admin/src/pages/methodology/MethodologiesPage.tsx
- src/explore-education-statistics-admin/src/pages/methodology/MethodologyCreatePage.tsx
- src/explore-education-statistics-admin/src/pages/methodology/edit-methodology/MethodologyPage.tsx
- src/explore-education-statistics-admin/src/pages/publication/PublicationEditPage.tsx
- src/explore-education-statistics-admin/src/pages/publication/components/PublicationForm.tsx
- src/explore-education-statistics-admin/src/pages/publication/components/__tests__/PublicationForm.test.tsx
- src/explore-education-statistics-admin/src/pages/release/components/ReleaseStatusChecklist.tsx
- src/explore-education-statistics-admin/src/pages/release/components/__tests__/ReleaseStatusChecklist.test.tsx
- src/explore-education-statistics-admin/src/routes/methodologyRoutes.ts
- src/explore-education-statistics-admin/src/routes/routes.ts
- Removes the methodology section from the create / manage publication form
- Updates the methodology paths to include the publication 
- Adds Create methodology and Link external methodology buttons to publications on the admin dashboard
- Adds an inline form for adding / editing an external methodology
- Adds edit and remove external methodology buttons
> EES-2350 initial FE work for new create methodology (WIP)

- src/GovUk.Education.ExploreEducationStatistics.Admin.Tests/Services/PublicationRepositoryTests.cs
- src/GovUk.Education.ExploreEducationStatistics.Admin/Services/PublicationRepository.cs
This PR fixes a bug where a Publication appeared twice in the Dashboard if was granted via the Publication Owner role and also a Release role on one of its Releases.
> EES-2368 Stop Publication appearing twice in the Dashboard if granted via the Publication Owner role as well as a Release role

- useful-scripts/importer-publisher-tests/.env.example
- useful-scripts/importer-publisher-tests/README.md
- useful-scripts/importer-publisher-tests/env.d.ts
- useful-scripts/importer-publisher-tests/index.ts
- useful-scripts/importer-publisher-tests/package-lock.json
- useful-scripts/importer-publisher-tests/package.json
This PR: 
- Updates dependencies for the importer / publisher test suite 
- replaces standard dotenv with dotenv-safe
- Fixes typos in README
> EES-2394 - update dependencies & update README

- src/explore-education-statistics-admin/src/pages/admin-dashboard/components/MethodologySummary.tsx
- src/explore-education-statistics-admin/src/pages/admin-dashboard/components/PublicationSummary.tsx
- src/explore-education-statistics-admin/src/pages/admin-dashboard/components/__tests__/MethodologySummary.test.tsx
- src/explore-education-statistics-admin/src/services/methodologyService.ts
- src/explore-education-statistics-admin/src/services/publicationService.ts
Show methodology info, tags and view & amend buttons on the admin dashboard.
I've put in a fake permissions check for that'll need to be updated later and have made some assumptions about param names so they may also need ot be changed.
> EES-2201 methodology info and tags

- src/explore-education-statistics-admin/src/pages/users/components/PublicationAccessForm.tsx
- src/explore-education-statistics-admin/src/pages/users/components/ReleaseAccessForm.tsx
- src/explore-education-statistics-common/src/components/ButtonText.tsx
- tests/robot-tests/tests/admin_and_public/bau/release_and_publication_role_permissions.robot
- tests/robot-tests/tests/libs/admin-common.robot
This PR provides tests for the following:
- Publication owner 
- Release viewer
- Release contributor 
- Release approver
> EES-2137-2 - publication owner UI tests

- src/explore-education-statistics-admin/src/pages/release/components/ReleaseStatusForm.tsx
- src/explore-education-statistics-admin/src/pages/release/components/__tests__/ReleaseStatusForm.test.tsx
Shows a confirm modal on submit if a specific publication date is set.
> EES-2362 add modal to confirm publish date

- src/explore-education-statistics-admin/src/pages/release/data/components/ReleaseDataUploadsSection.tsx
- src/explore-education-statistics-common/src/components/Accordion.tsx
Opens the subject section in the Uploaded data files accordion when the the subject files are uploaded.
> EES-104 expand section accordion on upload

- src/explore-education-statistics-admin/src/pages/publication/PublicationEditPage.tsx
- src/explore-education-statistics-admin/src/pages/publication/components/PublicationForm.tsx
- src/explore-education-statistics-admin/src/pages/publication/components/__tests__/PublicationForm.test.tsx
> EES-1277 show confirm modal when edit publication

- src/explore-education-statistics-frontend/src/html/glossary/A.html
- src/explore-education-statistics-frontend/src/html/glossary/C.html
- src/explore-education-statistics-frontend/src/html/glossary/D.html
- src/explore-education-statistics-frontend/src/html/glossary/E.html
- src/explore-education-statistics-frontend/src/html/glossary/F.html
- src/explore-education-statistics-frontend/src/html/glossary/H.html
- src/explore-education-statistics-frontend/src/html/glossary/I.html
- src/explore-education-statistics-frontend/src/html/glossary/L.html
- src/explore-education-statistics-frontend/src/html/glossary/M.html
- src/explore-education-statistics-frontend/src/html/glossary/O.html
- src/explore-education-statistics-frontend/src/html/glossary/P.html
- src/explore-education-statistics-frontend/src/html/glossary/R.html
- src/explore-education-statistics-frontend/src/html/glossary/S.html
- src/explore-education-statistics-frontend/src/html/glossary/T.html
- src/explore-education-statistics-frontend/src/html/glossary/U.html
- src/explore-education-statistics-frontend/src/html/glossary/V.html
Adding definitions to the glossary for:
- Open data
- UKPRN
- URN
- LAEstab
and also for the student loans definitions as included on the Jira ticket - https://dfedigital.atlassian.net/browse/EES-2433.
> EES 2433 - Adding more definitions to glossary

- src/GovUk.Education.ExploreEducationStatistics.Admin.Tests/Services/Methodologies/MethodologyServiceTests.cs
- src/GovUk.Education.ExploreEducationStatistics.Admin/Services/Methodologies/MethodologyService.cs
- src/GovUk.Education.ExploreEducationStatistics.Admin/ViewModels/Methodology/MethodologyUpdateRequest.cs
- src/GovUk.Education.ExploreEducationStatistics.Admin/ViewModels/MyMethodologyViewModel.cs
Couple of bug fixes on the SOW4 branch:
- Save the Internal Release Note when approving a Methodology
- Show the Methodology status on the Dashboard
> SOW4 Bug fixes

- src/explore-education-statistics-admin/src/contexts/AuthContext.tsx
- src/explore-education-statistics-admin/src/services/permissionService.ts
This PR adds a couple of changes that were accidently missed from https://github.com/dfe-analytical-services/explore-education-statistics/pull/2624
> EES-2458 Remove unused BAU methodologies page

- src/explore-education-statistics-admin/src/components/editable/EditablePageModeToggle.module.scss
- src/explore-education-statistics-admin/src/components/editable/EditablePageModeToggle.tsx
> EES-2413 toggle set page view box

- src/GovUk.Education.ExploreEducationStatistics.Publisher/Startup.cs
This PR adds missing repository dependencies of `MethodologyService` to the Publisher project that was preventing publishing Releases.
> EES-2473 Add missing dependencies to Publisher

- src/GovUk.Education.ExploreEducationStatistics.Admin.Tests/Services/ReleaseServiceAmendmentTests.cs
- src/GovUk.Education.ExploreEducationStatistics.Admin/Migrations/ContentMigrations/20210623090325_EES2423RemoveInternalReleaseNoteFromReleasesTable.Designer.cs
- src/GovUk.Education.ExploreEducationStatistics.Admin/Migrations/ContentMigrations/20210623090325_EES2423RemoveInternalReleaseNoteFromReleasesTable.cs
- src/GovUk.Education.ExploreEducationStatistics.Admin/Services/ReleaseService.cs
- src/GovUk.Education.ExploreEducationStatistics.Content.Model/Release.cs
Holding back merging of this until EES-1526 is successfully deployed to production.
> EES-2423 Remove unused InternalReleaseNote column from Releases table

- src/GovUk.Education.ExploreEducationStatistics.Content.Model.Tests/MethodologyTests.cs
- src/GovUk.Education.ExploreEducationStatistics.Content.Model/Methodology.cs
This PR:
- swaps logic around the ScheduledForPublishingWithPublishedRelease check in Methodology to first check the publishing strategy, to avoid an early exception being thrown
> EES-2222 - fixed logic around the check for ScheduledForPublishingWithPublishedRelease

- src/explore-education-statistics-admin/src/pages/release/components/ReleaseSummaryForm.tsx
Help text for time period when creating or editing a release.
> EES-2460 release time period help text

- src/GovUk.Education.ExploreEducationStatistics.Admin/ViewModels/MyMethodologyViewModel.cs
- src/GovUk.Education.ExploreEducationStatistics.Content.Api/Services/MethodologyService.cs
- tests/robot-tests/tests/admin/bau/create_methodology_for_publication.robot
Addresses bugs found while testing the EES-1263-SOW4 branch:
* EES-2378 Don't use WhereAsync otherwise it results in concurrent threads using the same instance of DbContext in method `MethodologyService.IsPublicationIncluded`
* Add missing InternalReleaseNote and Published to `MyMethodologyViewModel`
* Update robot test `create_methodology_for_publication` to fix expected Title and Published fields
> EES-1263 SOW4 bug fixes

- tests/robot-tests/tests/admin/analyst/analyst_absence_permissions.robot
- tests/robot-tests/tests/admin/bau/prerelease.robot
- tests/robot-tests/tests/admin_and_public/bau/footnotes.robot
- tests/robot-tests/tests/admin_and_public/bau/publish_release_and_amend.robot
- tests/robot-tests/tests/general_public/download_page.robot
- tests/robot-tests/tests/general_public/table_tool_absence_by_characteristic.robot
- tests/robot-tests/tests/general_public/table_tool_exclusions_by_geographic_level.robot
- tests/robot-tests/tests/libs/charts.robot
- tests/robot-tests/tests/libs/common.robot
> EES-2493 - fix UI test failures

- tests/robot-tests/tests/admin/analyst/analyst_absence_permissions.robot
- tests/robot-tests/tests/libs/common.robot
> EES-1263 SOW4 Fix UI tests

- src/explore-education-statistics-admin/src/pages/methodology/edit-methodology/summary/MethodologySummaryPage.tsx
- src/explore-education-statistics-admin/src/services/methodologyService.ts
This is hidden under a flag so won't affect the current version,  switch showPublications to true to see it in action.
> EES-2270 EES-2271 add owner and adopter publications to methodology summary

- tests/robot-tests/tests/libs/bootstrap_data/bootstrap_common.robot
Correcting relative paths after last minute Robot library restructure.
This'll be better when we switch to absolute paths and variables for the /libs/ folder.
> EES-XXXX - corrected library paths for bootstrapping lib file

- package.json
- tests/robot-tests/robotidy.toml
- tests/robot-tests/tests/admin/analyst/role_ui_permissions/publication_owner_permissions.robot
- tests/robot-tests/tests/admin/analyst/role_ui_permissions/release_approver_ui_permissions.robot
- tests/robot-tests/tests/admin/analyst/role_ui_permissions/release_contributor_ui_permissions.robot
- tests/robot-tests/tests/admin/analyst/role_ui_permissions/release_viewer_ui_permissions.robot
- tests/robot-tests/tests/admin/bau/admin_dashboard_page.robot
- tests/robot-tests/tests/admin/bau/create_methodology_for_publication.robot
- tests/robot-tests/tests/admin/bau/delete_subject.robot
- tests/robot-tests/tests/admin/bau/legacy_releases.robot
- tests/robot-tests/tests/admin/bau/manage_users_page.robot
- tests/robot-tests/tests/admin/bau/upload_files.robot
- tests/robot-tests/tests/admin_and_public/bau/prerelease_visibility.robot
- tests/robot-tests/tests/admin_and_public/bau/publish_release_and_amend.robot
- tests/robot-tests/tests/admin_and_public/bau/publish_release_and_amend_2.robot
- tests/robot-tests/tests/general_public/fast_track.robot
- tests/robot-tests/tests/general_public/methodologies_page.robot
- tests/robot-tests/tests/general_public/no_javascript.robot
- tests/robot-tests/tests/general_public/notifications_absence.robot
- tests/robot-tests/tests/libs/admin/analyst/role_ui_permissions.robot
- tests/robot-tests/tests/libs/bootstrap_data/bootstrap_common.robot
- tests/robot-tests/tests/libs/bootstrap_data/bootstrap_data_constants.robot
- tests/robot-tests/tests/libs/common.robot
This PR re-runs the Robot test formatter with settings that appeared to be missing pretty much all of the transforms needed for it to actually make any difference. I primarily noticed this because the formatter wasn't really doing anything as part of the commit hooks.
Additionally, I've added in some NPM scripts so we can conveniently run it from the project root.
> EES-2512 Run Robot test formatter with correct settings

- src/GovUk.Education.ExploreEducationStatistics.Data.Model/Services/ReleaseSubjectService.cs
- src/GovUk.Education.ExploreEducationStatistics.Publisher/Startup.cs
This is the same as PR #2709, but hotfixed to master
> EES-2549 Fix private stats DB wired into publisher's ReleaseSubjectService

- src/explore-education-statistics-admin/src/pages/release/content/components/ReleaseHelpAndSupportSection.tsx
- src/explore-education-statistics-common/src/modules/find-statistics/components/NationalStatisticsSection.tsx
- src/explore-education-statistics-common/src/modules/find-statistics/components/OfficialStatisticsSection.tsx
- src/explore-education-statistics-frontend/src/modules/find-statistics/PublicationReleaseHelpAndSupportSection.tsx
Shows Official Statistics info on releases.
> EES-2533 Add official stats info

- src/GovUk.Education.ExploreEducationStatistics.Common/Model/TimeIdentifier.cs
- src/GovUk.Education.ExploreEducationStatistics.Publisher/Startup.cs
Merge Master into Dev after PR's #2717 and #2718
> Merge Master into Dev after 2717 and 2718

- useful-scripts/sql/execute-filtered-observations.sql
The stored procedure GetFilteredObservations has been renamed and has new parameters. Update this sample script which is useful for executing queries directly against the db for debugging.
> EES-2561 Update sample FilteredObservations script with recent parameter additions

- tests/robot-tests/tests/admin_and_public/bau/publish_release_and_amend_2.robot
- tests/robot-tests/tests/general_public/methodologies_page.robot
> EES-2156 - UI test corrections

- infrastructure/templates/template.json
- src/explore-education-statistics-common/src/components/form/FormCheckbox.tsx
- src/explore-education-statistics-common/src/components/form/FormRadio.module.scss
- src/explore-education-statistics-common/src/components/form/FormRadio.tsx
- src/explore-education-statistics-common/src/modules/table-tool/components/PublicationForm.tsx
- src/explore-education-statistics-common/src/services/themeService.ts
- src/explore-education-statistics-frontend/next.config.js
- src/explore-education-statistics-frontend/src/modules/data-catalogue/DataCataloguePage.tsx
- src/explore-education-statistics-frontend/src/modules/data-catalogue/__tests__/DataCataloguePage.test.tsx
- src/explore-education-statistics-frontend/src/modules/data-catalogue/components/DownloadStep.tsx
- src/explore-education-statistics-frontend/src/modules/data-catalogue/components/ReleaseForm.tsx
- src/explore-education-statistics-frontend/src/modules/data-catalogue/components/ReleaseStep.tsx
- src/explore-education-statistics-frontend/src/modules/data-catalogue/components/__tests__/DownloadStep.test.tsx
- src/explore-education-statistics-frontend/src/modules/data-catalogue/components/__tests__/ReleaseStep.test.tsx
- src/explore-education-statistics-frontend/src/pages/data-catalogue/index.tsx
- src/explore-education-statistics-frontend/src/types/env.d.ts
Adds a new data catalogue page using the Wizard, populated with fake data for now.
> EES-2367 data catalogue wizard with dummy data

- src/GovUk.Education.ExploreEducationStatistics.Common/Cache/PublicationDownloadTreeCacheKey.cs
- src/GovUk.Education.ExploreEducationStatistics.Common/Cache/PublicationTreeCacheKey.cs
- src/GovUk.Education.ExploreEducationStatistics.Content.Api/Services/PublicationService.cs
- src/GovUk.Education.ExploreEducationStatistics.Publisher/Functions/PublishReleaseContentFunction.cs
- src/GovUk.Education.ExploreEducationStatistics.Publisher/Functions/PublishStagedReleaseContentFunction.cs
- src/GovUk.Education.ExploreEducationStatistics.Publisher/Services/ContentService.cs
This PR adds blob caching to the `PublicationService` `GetPublicationTree` and `GetPublicationDownloadsTree` methods.
> EES-2586 Cache publication tree and publication download tree

- tests/robot-tests/tests/admin/analyst/create_methodology_as_publication_owner.robot
- tests/robot-tests/tests/admin_and_public/bau/publish_release_and_amend_2.robot
- tests/robot-tests/tests/general_public/miscellaneous.robot
- tests/robot-tests/tests/libs/admin/manage-content-common.robot
This PR: 
* Adds UI test for setting an alternative methodology title as a publication owner 
* Runs RF formatter across test suites as some files weren't formatted properly
> EES-2217 - alternative title publication owner UI tests

- src/explore-education-statistics-admin/src/pages/methodology/edit-methodology/status/MethodologyStatusPage.tsx
- src/explore-education-statistics-admin/src/pages/methodology/edit-methodology/status/__tests__/MethodologyStatusPage.test.tsx
> EES-2273 add owning and other publications on methodology status page

- src/explore-education-statistics-admin/src/components/editable/Comments.tsx
- src/explore-education-statistics-common/src/components/form/FormTextArea.tsx
- src/explore-education-statistics-common/src/components/form/__tests__/__snapshots__/FormTextArea.test.tsx.snap
- tests/robot-tests/tests/admin/bau/comments.robot
- tests/robot-tests/tests/libs/admin-common.robot
- tests/robot-tests/tests/libs/common.robot
> EES-2597 - comments UI tests 

- src/GovUk.Education.ExploreEducationStatistics.Admin/Services/TopicService.cs
This PR reorders deleting Methodologies before Releases when deleting a Topic since Methodology can now depend on a Release for its publishing strategy.
Prior to this a bug could be demonstrated in the UI tests by running `tests\admin\analyst\role_ui_permissions\release_and_publication_role_end_to_end_permissions.robot`
during the teardown execution of
```
def delete_test_topic():
if os.getenv('TEST_TOPIC_ID') is not None:
admin_request('DELETE', f'/api/topics/{os.getenv("TEST_TOPIC_ID")}')
```
resulting in a Admin error occurring 
`The DELETE statement conflicted with the REFERENCE constraint "FK_Methodologies_Releases_ScheduledWithReleaseId". The conflict occurred in database "content", table "dbo.Methodologies", column 'ScheduledWithReleaseId`
> EES-2634 Reorder deleting Methodologies before Releases when deleting Topic

- src/GovUk.Education.ExploreEducationStatistics.Admin.Tests/Services/ReleaseChecklistServiceTests.cs
- src/GovUk.Education.ExploreEducationStatistics.Admin/Services/ReleaseChecklistService.cs
- src/GovUk.Education.ExploreEducationStatistics.Admin/Validators/ValidationUtils.cs
- src/GovUk.Education.ExploreEducationStatistics.Admin/ViewModels/ReleaseChecklistViewModels.cs
- src/explore-education-statistics-admin/src/pages/release/components/ReleaseStatusChecklist.tsx
- src/explore-education-statistics-admin/src/pages/release/components/__tests__/ReleaseStatusChecklist.test.tsx
- src/explore-education-statistics-admin/src/services/releaseService.ts
- tests/robot-tests/tests/admin/bau/release_status.robot
Switching an error to be a warning, and added Robot tests for the new warning case.
> EES-2150 - switched unapproved Methodology from being a checklist error to a checklist warning

- src/GovUk.Education.ExploreEducationStatistics.Common/Model/Chart/ChartAxisConfiguration.cs
- src/explore-education-statistics-admin/src/pages/release/datablocks/components/chart/ChartAxisConfiguration.tsx
- src/explore-education-statistics-admin/src/pages/release/datablocks/components/chart/__tests__/ChartAxisConfiguration.test.tsx
- src/explore-education-statistics-common/src/modules/charts/util/createDataSetCategories.ts
Backend changes to save the groupby filter. Plus a couple of frontend fixes.
> EES-2620 groupby filter

- tests/robot-tests/tests/admin/bau/release_status.robot
- tests/robot-tests/tests/bootstrap_data/release_and_publication_role_permissions_data.robot
This PR:
- adds tests that ensure that a warning is issued if a Publication has adopted a Draft Methodology and is about to approve a Release
> EES-2292 - adopting Draft Methodology and Approving Release

- src/explore-education-statistics-frontend/src/modules/methodologies/__tests__/MethodologyPage.test.tsx
- src/explore-education-statistics-frontend/src/modules/methodologies/__tests__/__data__/testMethodologyData.ts
Adds some more tests for the frontend methodology page.
> EES-2717 more methodology page unit tests

- src/explore-education-statistics-admin/src/pages/admin-dashboard/components/MethodologySummary.tsx
- src/explore-education-statistics-admin/src/pages/admin-dashboard/components/__tests__/MethodologySummary.test.tsx
- tests/robot-tests/tests/admin/bau/link_publication_to_external_methodology.robot
- tests/robot-tests/tests/libs/admin-common.robot
Shows a a confirmation modal when click the remove external methodology button on the dashboard.
> EES-2531 modal for remove external methodology

- useful-scripts/misc-test-utils/src/services/releaseService.ts
- useful-scripts/misc-test-utils/src/services/subjectService.ts
- useful-scripts/misc-test-utils/tsconfig.json
This PR: 
- updates meta guidance endpoints to data guidance 
- Makes `tsconfig` more strict
> EES-2855 fix misc test utils

- tests/robot-tests/tests/admin_and_public/bau/publish_content.robot
- tests/robot-tests/tests/general_public/miscellaneous.robot
- tests/robot-tests/tests/general_public/notifications_absence.robot
- tests/robot-tests/tests/general_public/release_page_absence.robot
- tests/robot-tests/tests/general_public/table_tool_absence_by_characteristic.robot
- tests/robot-tests/tests/general_public/table_tool_exclusions_by_geographic_level.robot
This PR fixes: 
```
tests/admin_and_public/bau/publish_content.robot
tests/general_public/miscellaneous.robot
tests/general_public/notifications_absence.robot
tests/general_public/release_page_absence.robot
tests/general_public/table_tool_absence_by_characteristic.robot
```
> EES-2891 - fix dev UI tests

- tests/robot-tests/.env.example
- tests/robot-tests/tests/admin/analyst/analyst_absence_permissions.robot
- tests/robot-tests/tests/admin/analyst/role_ui_permissions/publication_owner_permissions.robot
- tests/robot-tests/tests/admin/analyst/role_ui_permissions/release_and_publication_role_end_to_end_permissions.robot
- tests/robot-tests/tests/admin/analyst/role_ui_permissions/release_approver_ui_permissions.robot
- tests/robot-tests/tests/admin/analyst/role_ui_permissions/release_contributor_ui_permissions.robot
- tests/robot-tests/tests/admin/analyst/role_ui_permissions/release_viewer_ui_permissions.robot
- tests/robot-tests/tests/admin/bau/create_data_block_with_chart.robot
- tests/robot-tests/tests/admin/bau/create_methodology_amendment.robot
- tests/robot-tests/tests/admin/bau/create_publication_and_release.robot
- tests/robot-tests/tests/admin/bau/delete_subject.robot
- tests/robot-tests/tests/admin/bau/prerelease.robot
- tests/robot-tests/tests/admin/bau/release_status.robot
- tests/robot-tests/tests/admin_and_public/bau/prerelease_visibility.robot
- tests/robot-tests/tests/admin_and_public/bau/publish_content.robot
- tests/robot-tests/tests/admin_and_public/bau/publish_data.robot
- tests/robot-tests/tests/admin_and_public/bau/publish_publication_update.robot
- tests/robot-tests/tests/admin_and_public/bau/publish_release_and_amend.robot
- tests/robot-tests/tests/admin_and_public/bau/publish_release_and_amend_2.robot
- tests/robot-tests/tests/general_public/notifications_absence.robot
- tests/robot-tests/tests/general_public/release_page_absence.robot
- tests/robot-tests/tests/general_public/table_tool_absence_by_characteristic.robot
- tests/robot-tests/tests/general_public/table_tool_absence_in_prus.robot
- tests/robot-tests/tests/libs/admin-common.robot
- tests/robot-tests/tests/libs/admin/analyst/role_ui_permissions.robot
- tests/robot-tests/tests/libs/admin/manage-content-common.robot
- tests/robot-tests/tests/libs/bootstrap_data/bootstrap_common.robot
- tests/robot-tests/tests/libs/charts.robot
- tests/robot-tests/tests/libs/tables-common.robot
This PR:
- remove long hard-coded waits from UI tests 
- fixes a few flaky tests
> EES-2723 - remove hard-coded waits from UI tests

- tests/robot-tests/tests/admin/bau/release_content.robot
> EES-2937 - fix release_content.robot

- src/GovUk.Education.ExploreEducationStatistics.Common.Tests/Extensions/MoqExtensions.cs
- src/GovUk.Education.ExploreEducationStatistics.Common/Services/BlobCacheService.cs
- src/GovUk.Education.ExploreEducationStatistics.Data.Model/Repository/FilterItemRepository.cs
- src/GovUk.Education.ExploreEducationStatistics.Data.Model/Repository/Interfaces/IFilterItemRepository.cs
- src/GovUk.Education.ExploreEducationStatistics.Data.Services.Tests/ResultSubjectMetaServiceTests.cs
- src/GovUk.Education.ExploreEducationStatistics.Data.Services.Tests/TableBuilderServiceTests.cs
- src/GovUk.Education.ExploreEducationStatistics.Data.Services/AbstractSubjectMetaService.cs
- src/GovUk.Education.ExploreEducationStatistics.Data.Services/Interfaces/IObservationService.cs
- src/GovUk.Education.ExploreEducationStatistics.Data.Services/Interfaces/IResultSubjectMetaService.cs
- src/GovUk.Education.ExploreEducationStatistics.Data.Services/ObservationService.cs
- src/GovUk.Education.ExploreEducationStatistics.Data.Services/ResultSubjectMetaService.cs
- src/GovUk.Education.ExploreEducationStatistics.Data.Services/SubjectMetaService.cs
- src/GovUk.Education.ExploreEducationStatistics.Data.Services/TableBuilderService.cs
This PR:
- merges master into dev, to bring in EES-2924 which was originally planned as a hotfix back onto dev as part of a normal rollout instead
> EES-2924 - merging master into dev

- infrastructure/templates/template.json
This PR: 
- is an initial attempt to try to get data factory alerts working for production environments
> EES-2960 - investigate alerts for data factory failed jobs

- tests/robot-tests/tests/admin/bau/create_data_block_with_chart.robot
- tests/robot-tests/tests/admin/bau/prerelease.robot
- tests/robot-tests/tests/admin_and_public/bau/publish_release_and_amend.robot
- tests/robot-tests/tests/libs/admin-utilities.py
- tests/robot-tests/tests/libs/admin/analyst/role_ui_permissions.robot
- tests/robot-tests/tests/libs/common.robot
> EES-2967 - cleanup UI tests

- tests/robot-tests/tests/admin/analyst/invite_contributor_as_publication_owner.robot
- tests/robot-tests/tests/libs/admin-common.robot
NOTE: Requires EES-2940 to be merged first.
> EES-2885 Manage team access UI tests

- src/explore-education-statistics-frontend/src/pages/accessibility-statement.tsx
Updated accessibility statement based on DAC report.
> EES 3071 review update accessibility statement

- src/GovUk.Education.ExploreEducationStatistics.Common.Tests/Extensions/EitherTestExtensions.cs
- src/GovUk.Education.ExploreEducationStatistics.Common.Tests/Model/EitherTest.cs
- src/GovUk.Education.ExploreEducationStatistics.Common/Model/Either.cs
This PR:
- adds in additional Unit Tests for Either and EitherTaskExtension methods that are used in production.
- brings code coverage in Either to 100%
> EES-3094 - Either and EitherTaskExtension additional tests

- .github/ISSUE_TEMPLATE/-bug_report.yml
- .github/ISSUE_TEMPLATE/config.yml
- .github/pull_request_template.md
- CODE_OF_CONDUCT.md
- CONTRIBUTING.md
This PR: 
- Adds basic community standard checklist that Github recommends. This includes things such as bug report templates, PR templates etc.
> EES-2703 - GH community standards

- src/explore-education-statistics-common/src/modules/table-tool/components/TimePeriodDataTable.tsx
- src/explore-education-statistics-frontend/src/modules/permalink/PermalinkPage.tsx
Added defensive code to prevent the permalink page breaking when the configuration for tableHeaders rows returned from getPermalink is an empty array. 
A jira ticket will be raised separately to investigate why the array is empty, once that's resolved we should be able to remove this check.
> EES-3141 fix broken permalink 

- src/explore-education-statistics-frontend/src/modules/permalink/PermalinkPage.tsx
Show download table when there isn't an error and hide it when there is.
I should pay more attention to what I'm doing!
> EES-3141 true is not false

- src/explore-education-statistics-common/src/modules/table-tool/components/TimePeriodDataTable.tsx
- src/explore-education-statistics-frontend/src/modules/permalink/PermalinkPage.tsx
Branch to fix a conflict merging master back into dev
> Fix conflict on master into dev merge

- useful-scripts/get_data_block_responses/get_data_block_responses.py
This PR fixes a bug in `get_data_block_responses.py` where if a request timed out, it would return the response of the previously processed datablock.
The script has also been refactored.
> EES-3172 Fix and refactor get_data_block_responses.py

- tests/robot-tests/tests/snapshots/all_methodologies_snapshot.json
- tests/robot-tests/tests/snapshots/data_catalogue_snapshot.json
- tests/robot-tests/tests/snapshots/find_stats_snapshot.json
- tests/robot-tests/tests/snapshots/table_tool_snapshot.json
> Public snapshot changes 20220218

- tests/robot-tests/tests/admin/bau/comments.robot
- tests/robot-tests/tests/admin/bau/create_data_block_with_chart.robot
- tests/robot-tests/tests/admin/bau/release_content.robot
- tests/robot-tests/tests/libs/admin/manage-content-common.robot
>     EES-3255 - fix UI tests

- src/GovUk.Education.ExploreEducationStatistics.Publisher.Tests/Services/DataBlockMigrationServiceTests.cs
- src/GovUk.Education.ExploreEducationStatistics.Publisher/Services/DataBlockMigrationService.cs
This hotfix PR makes a change to the data blocks migration added by https://github.com/dfe-analytical-services/explore-education-statistics/pull/3180.
This adds an allowed list of data block id's which don't contain Institution, Planning Area, Provider, or School level data but which we are still going to allow single table headers to transform into multiple headers.
We already transform a single data block header into multiple headers where location codes map to more than one distinct location but up until now we only allow this for codes at 'Provider' and 'School' levels where we know duplicate locations can exist.
The list of data blocks contain locations outside of these levels which are not distinct by code but have been checked by @cjrace to make sure that the duplicate locations …
> EES-3167 EES-3214 Add allow list for data blocks

- src/GovUk.Education.ExploreEducationStatistics.Publisher.Tests/Services/DataBlockMigrationServiceTests.cs
- src/GovUk.Education.ExploreEducationStatistics.Publisher/Services/DataBlockMigrationService.cs
This PR merges master into the dev branch after the hotfix https://github.com/dfe-analytical-services/explore-education-statistics/pull/3217 was merged.
***This is done from a branch where merge conflicts had to be resolved due to changes in dev already made `DataBlockMigrationServiceTests.cs`.***
> Merging master into dev after PR #3217

- tests/robot-tests/tests/admin/bau/comments.robot
- tests/robot-tests/tests/admin/bau/create_data_block_with_chart.robot
- tests/robot-tests/tests/admin_and_public/bau/publish_data.robot
- tests/robot-tests/tests/libs/admin-common.robot
> EES-3284 - fix UI tests

- tests/robot-tests/README.md
- tests/robot-tests/scripts/create_snapshots.py
This PR: 
- updates UI test README to mention snapshot testing & how to run them
> EES-3292 - update UI test readme

- src/explore-education-statistics-admin/src/pages/publication/components/LegacyReleasesTable.tsx
- src/explore-education-statistics-admin/src/pages/publication/components/__tests__/LegacyReleasesTable.test.tsx
- src/explore-education-statistics-admin/src/routes/legacyReleaseRoutes.tsx
- tests/robot-tests/tests/admin/bau/legacy_releases.robot
- tests/robot-tests/tests/libs/admin-common.robot
- tests/robot-tests/tests/libs/common.robot
Shows a modal before you create, edit, delete or reorder legacy releases warning that the changes will be shown immediately on the public site.
> EES-3252 warning modal for legacy release editing

- tests/robot-tests/tests/admin_and_public/bau/legacy_releases.robot
This PR: 
- updates the legacy release UI test suite in order to assert that changes made to legacy releases are instantly shown on the public frontend (if the publication already has live releases)
> EES-3256 - update legacy release UI tests

- src/GovUk.Education.ExploreEducationStatistics.Admin/GovUk.Education.ExploreEducationStatistics.Admin.csproj
- src/GovUk.Education.ExploreEducationStatistics.Notifier/GovUk.Education.ExploreEducationStatistics.Notifier.csproj
This PR upgrades from version 4.0.1 to version 6.0.0 of GovUkNotify client library.
See https://github.com/alphagov/notifications-net-client/blob/master/CHANGELOG.md for more information.
> EES-3423 Upgrade to latest version of GovUkNotify library

- src/explore-education-statistics-common/src/modules/table-tool/components/TimePeriodDataTable.tsx
Note this PR doesn't actually solve the ticket issue. This is simply for debugging any issues with rendering tabls.
> EES-3408 Log out errors from rendering `TimePeriodDataTable`

- tests/robot-tests/tests/snapshots/find_stats_snapshot.json
> Public snapshot changes

- tests/robot-tests/scripts/pipeline-run-rf-tests-snapshots.sh
- tests/robot-tests/scripts/pipeline-run-rf-tests.sh
This PR is to try and ensure that user passwords gets passed correctly to `run_tests.py`. See Jira ticket for more details.
> EES-3514 Changes for CI pipeline

- .gitignore
- tests/robot-tests/scripts/get_auth_tokens.py
Remove debug auth issues util function as pipeline authentication issues are now fixed
> EES-3570-2 - remove debug auth issue utilities

- tests/performance-tests/package.json
- tests/performance-tests/src/auth/storeEnvironmentDetails.ts
- tests/performance-tests/src/tests/admin/import/import.test.ts
- tests/performance-tests/src/tests/admin/table-tool/tableBuilderQuery.test.ts
- tests/performance-tests/src/tests/healthchecks/refreshTokens.test.ts
- tests/performance-tests/src/tests/public/findStatisticsPage.test.ts
- tests/performance-tests/src/tests/public/getReleaseApi.test.ts
- tests/performance-tests/src/tests/public/getReleasePage.test.ts
- tests/performance-tests/src/tests/testData.ts
- tests/performance-tests/src/utils/dataService.ts
- tests/performance-tests/src/utils/environmentAndUsers.ts
- tests/performance-tests/src/utils/getOrRefreshAccessTokens.ts
This PR:
* cleans up some lint & typescript warnings in the performance tests project
> EES-3657 - fix performance tests lint & typescript errors

- package.json
- src/explore-education-statistics-admin/src/components/Breadcrumbs.tsx
- src/explore-education-statistics-admin/src/components/__tests__/__snapshots__/Breadcrumbs.test.tsx.snap
- src/explore-education-statistics-frontend/src/components/Breadcrumbs.tsx
- src/explore-education-statistics-frontend/src/components/__tests__/__snapshots__/Breadcrumbs.test.tsx.snap
This PR: 
- fixes accessibility issues whereby breadcrumbs can be confused for normal links when using a screen reader
> EES-3064 - fix breadcrumb accessibility issues

- Pipfile.lock
Fixes warning message: 
```
Pipfile.lock (6fcf4f) out of date, updating to (791f70)...
Locking [packages] dependencies...
Building requirements...
Resolving dependencies...
```
> EES-3736 - update pipfile lock

- src/explore-education-statistics-admin/src/pages/release/components/__tests__/ReleaseStatusForm.test.tsx
Fixes the test failing because of a hardcoded publish date.
> EES-3790 fix ReleaseStatusForm test

- Pipfile
- Pipfile.lock
This PR: 
* Upgrades robot-framework dependency to v6
> EES-3811 - upgrade to robotframework v6

- tests/robot-tests/listeners/KeywordListener.py
- tests/robot-tests/run_tests.py
- tests/robot-tests/scripts/run_tests_pipeline.py
- tests/robot-tests/scripts/visual-testing/compare_images.py
- tests/robot-tests/tests/libs/create_emulator_release_files.py
- tests/robot-tests/tests/libs/logger.py
- tests/robot-tests/tests/libs/setup_auth_variables.py
- tests/robot-tests/tests/libs/slack.py
This PR: 
* replaces print() statements with a logger 
* Creates new logger utility function which returns a memoized logger via the `lru_cache` strategy (last recently used). Typically the `lru_cache` decorator is good for when a function is complex or invoked frequently (can save computation time, memory, etc.).
> EES-3813 - replace print() statements with logger

- src/docker-compose.yml
> EES-3831 - upgrade Azurite docker image to latest

- src/explore-education-statistics-admin/src/pages/publication/components/PublicationDraftReleases.tsx
- src/explore-education-statistics-admin/src/pages/publication/components/PublicationPublishedReleasesTable.tsx
- src/explore-education-statistics-admin/src/pages/publication/components/PublicationScheduledReleases.tsx
Changes 'State' to 'Status' on the publication releases page.
> EES-3801 change state to status

- src/explore-education-statistics-admin/src/pages/admin-dashboard/components/__tests__/PublicationsTab.test.tsx
- src/explore-education-statistics-admin/src/pages/publication/PublicationDetailsPage.tsx
- src/explore-education-statistics-admin/src/pages/publication/components/__tests__/PublicationInviteNewUsersForm.test..tsx
- src/explore-education-statistics-admin/src/pages/release/datablocks/__tests__/ReleaseTableToolPage.test.tsx
- src/explore-education-statistics-admin/src/pages/release/datablocks/components/chart/ChartConfiguration.tsx
- src/explore-education-statistics-admin/src/pages/release/datablocks/components/chart/ChartLegendConfiguration.tsx
- src/explore-education-statistics-admin/src/pages/release/datablocks/components/chart/ChartMapConfiguration.tsx
- src/explore-education-statistics-admin/src/pages/release/pre-release/__tests__/PreReleaseTableToolPage.test.tsx
- src/explore-education-statistics-admin/src/prototypes/PrototypeAdminMethodology.tsx
- src/explore-education-statistics-admin/src/prototypes/PrototypeAdminPublication.tsx
- src/explore-education-statistics-admin/src/prototypes/PrototypeFindStats.tsx
- src/explore-education-statistics-admin/src/prototypes/PrototypeFindStats2.tsx
- src/explore-education-statistics-admin/src/prototypes/PrototypeFindStats3.tsx
- src/explore-education-statistics-admin/src/prototypes/PrototypeFindStats4.tsx
- src/explore-education-statistics-admin/src/prototypes/PrototypeFindStats5.tsx
- src/explore-education-statistics-admin/src/prototypes/PrototypeFindStats6.tsx
- src/explore-education-statistics-admin/src/prototypes/PrototypeManageUsers.tsx
- src/explore-education-statistics-admin/src/prototypes/PrototypeReleaseSummary.tsx
- src/explore-education-statistics-admin/src/prototypes/components/PrototypeChangeUserRole.tsx
- src/explore-education-statistics-admin/src/prototypes/components/PrototypeFilters.tsx
- src/explore-education-statistics-admin/src/prototypes/components/PrototypeFilters3.tsx
- src/explore-education-statistics-admin/src/prototypes/components/PrototypePublicationReleaseList.tsx
- src/explore-education-statistics-admin/src/prototypes/components/PrototypeSearchResult.tsx
Tidying up so we don't have all those linter warnings any more.
> Tidying up to remove linter warnings

- src/GovUk.Education.ExploreEducationStatistics.Admin/Areas/Identity/Pages/Account/ExternalLogin.cshtml.cs
This PR fixes a bug where after logging in, a user wouldn't get redirected to page they were previously trying to access.
This was fixed by ensuring the argument name for the return URL was correct on `OnGetCallbackAsync`. It must be `returnUrl`, otherwise IdentityServer4 will always return null for that argument.
> EES-3835 Fix login redirect

- tests/robot-tests/tests/admin/analyst/role_ui_permissions/release_and_publication_role_end_to_end_permissions.robot
- tests/robot-tests/tests/libs/admin-common.robot
This PR:
* Attempts to address some flakiness around the admin suite when run in a CI environment against dev
> EES-3902 - address admin suite failures on dev

- .flake8
- .gitignore
- tests/robot-tests/scripts/visual-testing/README.md
- tests/robot-tests/scripts/visual-testing/compare_image_folder_trees.py
- tests/robot-tests/scripts/visual-testing/compare_images.py
- tests/robot-tests/scripts/visual-testing/generate_permalink_test_cases.py
- tests/robot-tests/scripts/visual-testing/generate_tables_and_charts_test_cases.py
- tests/robot-tests/tests/libs/visual.py
- tests/robot-tests/tests/visual_testing/tables_and_charts.robot
This PR fixes chart visual tests (namely around the chart tests not being able to find a selector that's been removed. 
Other changes
* fixes import + path issues 
* fixes styling issues
* Updates visual testing README
* Updates linting rules
> EES-3941 - fix chart tests

- src/docker-compose.yml
This PR updates the azurite docker image to the latest. 
Release notes: https://github.com/Azure/Azurite/releases/tag/v3.21.0
> EES-3996 - update azurite docker image

- src/explore-education-statistics-frontend/src/modules/find-statistics/PublicationReleaseHelpAndSupportSection.tsx
Changes the methodologies list on release pages to be a list and remove the unnecessary spacing.
> EES-3775 remove unnecessary spacing on release page methodologies list

- src/explore-education-statistics-admin/src/components/editable/EditableBlockWrapper.tsx
- src/explore-education-statistics-admin/src/components/editable/EditableEmbedBlock.tsx
- src/explore-education-statistics-admin/src/components/editable/EditableEmbedForm.tsx
- src/explore-education-statistics-admin/src/components/editable/__tests__/EditableBlockWrapper.test.tsx
- src/explore-education-statistics-admin/src/components/editable/__tests__/EditableEmbedBlock.test.tsx
- src/explore-education-statistics-admin/src/pages/release/content/components/ReleaseContentAccordionSection.tsx
- src/explore-education-statistics-admin/src/pages/release/content/components/__tests__/ReleaseContentAccordionSection.test.tsx
- tests/robot-tests/tests/libs/admin/manage-content-common.robot
Changes the button and modal text for embed blocks.
> EES-4043 change embed block text

- tests/robot-tests/tests/snapshots/find_statistics_snapshot.json
> Latest snapshots

- src/explore-education-statistics-admin/src/pages/release/content/components/RelatedPagesSection.tsx
- src/explore-education-statistics-admin/src/pages/release/content/components/ReleaseContent.tsx
- src/explore-education-statistics-frontend/src/modules/find-statistics/PublicationReleasePage.tsx
- src/explore-education-statistics-frontend/src/modules/find-statistics/__tests__/PublicationReleasePage.test.tsx
- tests/robot-tests/tests/admin_and_public/bau/legacy_releases.robot
- tests/robot-tests/tests/admin_and_public/bau/publish_content.robot
- tests/robot-tests/tests/admin_and_public/bau/publish_data.robot
- tests/robot-tests/tests/admin_and_public/bau/subject_reordering.robot
- tests/robot-tests/tests/admin_and_public_2/bau/publish_release_and_amend.robot
- tests/robot-tests/tests/general_public/release_page_absence.robot
Updates the links in the release page sidebar in the public frontend and admin.
> EES-4059 update release page sidebar links

- tests/performance-tests/src/tests/admin/table-tool/adminTableBuilderQuery.test.ts
- tests/performance-tests/src/tests/healthchecks/refreshTokens.test.ts
- tests/performance-tests/src/tests/maintenance/cleanUp.test.ts
- tests/performance-tests/src/tests/public/fastTrackPage.test.ts
- tests/performance-tests/src/tests/public/findStatisticsPage.test.ts
- tests/performance-tests/src/tests/public/getReleaseApi.test.ts
- tests/performance-tests/src/tests/public/getReleasePage.test.ts
- tests/performance-tests/src/tests/public/permalinkPage.test.ts
- tests/performance-tests/src/tests/public/table-tool/publicTableBuilderQuery.test.ts
- tests/performance-tests/src/utils/adminService.ts
- tests/performance-tests/src/utils/utils.ts
This PR: 
* performs a general cleanup in the performance tests. Changes include things such as unnecessary casting, fixing lint issues etc.
> EES-4139 - cleanup performance tests

- tests/robot-tests/tests/admin/bau/prerelease_and_amend.robot
> UI tests to check pre-release access during amendment-fixed

- infrastructure/parameters/dev.parameters.json
- infrastructure/parameters/pre-prod.parameters.json
- infrastructure/templates/template.json
This PR merges the changes in https://github.com/dfe-analytical-services/explore-education-statistics/pull/3941 to the dev branch.
> Merge master into dev after PR #3941

- src/explore-education-statistics-admin/src/pages/release/pre-release/ReleasePreReleaseAccessPage.tsx
Updates the help text on the Manage pre-release user access page.
> EES-4121 update pre-release help text

- src/explore-education-statistics-common/src/modules/table-tool/components/FiltersForm.tsx
Adds `aria-expanded` and `aria-controls` to the Filters Form expand / collapse all button.
> EES-4087 add aria-expanded to filters form toggle

- src/explore-education-statistics-admin/src/pages/release/components/ReleaseStatusForm.tsx
Adds an additional warning to the scheduling confirmation modal.
> EES-4158 update scheduling confirmation modal text

- .github/workflows/validate-snapshots.yml
Removes date from commit message (for now) which isn't being interpolated properly
> chore(tests): fix snapshot commit message

- azure-pipelines-ui-tests.dfe.yml
created a new `azure-pipelines-ui-tests.dfe.yml` file to export UI tests pipeline to YAML.
> EES-3301  Migrating test pipeline to YAML

- azure-pipelines-ui-tests.dfe.yml
Added new Env Variables for Slack
> Editing YAML file

- .github/workflows/validate-snapshots.yml
- tests/robot-tests/scripts/create_snapshots.py
- tests/robot-tests/tests/libs/create_emulator_release_files.py
- tests/robot-tests/tests/visual_testing/tables_and_charts.py
This PR makes several improvements to how automation around snapshots tests is managed & performed. 
Relevant changes:
* Changes commit author in `validate-snapshots.yml` so that I don't get included as a commit author
* Adds labels to the pull request created by the bot
* Refactors `_send_slack_notification` to allow a user to pass an optional slack block in order to enable the creation of more richly formatted messages (see screenshot for an example)
Other changes:
* Runs python linter/formatter on all python related files
> EES-4193, EES-4221 - make improvements to snapshot automation

- tests/robot-tests/scripts/create_snapshots.py
Fixes this error: https://github.com/dfe-analytical-services/explore-education-statistics/actions/runs/4819300794/jobs/8582323237
> EES-4272 Fix snapshot pipeline error

- azure-pipelines-ui-tests.dfe.yml
- tests/robot-tests/tests/admin/bau/release_content_authoring.robot
- tests/robot-tests/tests/admin_and_public/bau/archive_publication.robot
- tests/robot-tests/tests/admin_and_public_2/bau/publish_amend_and_cancel.robot
- tests/robot-tests/tests/admin_and_public_2/bau/publish_release_and_amend.robot
- tests/robot-tests/tests/general_public/release_page_absence.robot
- tests/robot-tests/tests/general_public/table_tool_absence_by_characteristic.robot
- tests/robot-tests/tests/general_public/table_tool_absence_in_prus.robot
- tests/robot-tests/tests/general_public/table_tool_exclusions_by_geographic_level.robot
- tests/robot-tests/tests/libs/admin_api.py
This PR: 
fixes the majority of the UI test failures seen over the past 4 weeks
> EES-4280 - fix UI tests

- azure-pipelines-ui-tests.dfe.yml
- tests/robot-tests/tests/admin/bau/release_content_authoring.robot
- tests/robot-tests/tests/admin_and_public/bau/archive_publication.robot
- tests/robot-tests/tests/admin_and_public_2/bau/publish_amend_and_cancel.robot
- tests/robot-tests/tests/admin_and_public_2/bau/publish_release_and_amend.robot
- tests/robot-tests/tests/general_public/release_page_absence.robot
- tests/robot-tests/tests/general_public/table_tool_absence_by_characteristic.robot
- tests/robot-tests/tests/general_public/table_tool_absence_in_prus.robot
- tests/robot-tests/tests/general_public/table_tool_exclusions_by_geographic_level.robot
Reverts dfe-analytical-services/explore-education-statistics#4025 due to local environment issues related to the old LA casing showing
> Revert "EES-4280 - fix UI tests"

- tests/robot-tests/tests/admin_and_public_2/bau/publish_amend_and_cancel.robot
Added a wait to resolve failing UI tests in Data replacement steps in `admin_and_public_2`
> EES-4294 fixing UI tests

- src/explore-education-statistics-common/src/modules/charts/components/HorizontalBarBlock.tsx
- src/explore-education-statistics-common/src/modules/charts/components/LineChartBlock.tsx
- src/explore-education-statistics-common/src/modules/charts/components/VerticalBarBlock.tsx
- src/explore-education-statistics-common/src/modules/charts/util/chartUtils.ts
Changes the colour of the text in chart axes to the standard body text colour.
I'm open to suggestions for somewhere better than `chartUtils` to put `axisTickStyle`.
> EES-3063 change chart axis text colour

- src/explore-education-statistics-frontend/src/pages/index.tsx
Adds a new link to the supporting information section on the homepage.
> EES-1771 add statistics release calendar link to the homepage

- src/explore-education-statistics-common/src/components/form/FormCheckboxGroup.tsx
- src/explore-education-statistics-common/src/components/form/FormCheckboxSearchGroup.tsx
- src/explore-education-statistics-common/src/components/form/FormCheckboxSearchSubGroups.tsx
- src/explore-education-statistics-common/src/components/form/rhf/__tests__/__snapshots__/RHFFormFieldCheckboxGroupsMenu.test.tsx.snap
- src/explore-education-statistics-common/src/modules/table-tool/components/FiltersForm.tsx
- src/explore-education-statistics-common/src/modules/table-tool/components/LocationFiltersForm.tsx
- src/explore-education-statistics-common/src/modules/table-tool/components/__tests__/LocationFiltersForm.test.tsx
- src/explore-education-statistics-common/src/modules/table-tool/components/__tests__/__snapshots__/FormFieldCheckboxGroupsMenu.test.tsx.snap
Adds visually hidden text for screen reader users to the table tool location and filters steps:
- select all buttons
- search labels
> EES-4341 screen reader text in table tool forms

- src/explore-education-statistics-admin/src/pages/methodology/edit-methodology/content/components/MethodologyAccordion.tsx
- src/explore-education-statistics-admin/src/pages/methodology/edit-methodology/content/components/MethodologyAccordionSection.tsx
Remove unnecessary context to fix the page
> EES-4379 fix prerelease methodology page

- .github/workflows/codeql.yml
- .github/workflows/dependency-review.yml
This PR:
* Implements the automated scanning & analysis of security issues/vulnerabilities
This is achieved via two workflows files:
`codeql.yml`: CodeQL is GitHub's security analyzer which will alert us if there are coding mistakes (i.e. a vulnerable regex statement) or if there are security issues with the project's dependencies. This runs every 8AM on Monday and on every pull request
`dependency_review.yml`: This is responsible for scanning PRs and ensuring that they don't introduce security issues
> EES-4164 - implement code scanning & security analysis tooling

- package.json
This PR fixes various problems we've had with PNPM.
These include:
* Having a typo in the reporter option
* Making `check-node-version` command more succinct 
* Upgrading to the latest version of PNPM
> EES-4424 - fix various problems with PNPM

- tests/robot-tests/tests/admin_and_public/bau/prerelease_visibility.robot
Fix for failing tests due to lack of supporting seed data for existing Methodologies under the Test Theme.
> Prerelease Visibility UI test fix

- tests/robot-tests/tests/general_public/table_tool_exclusions_by_geographic_level.robot
Fixing UI test failure in general_public suite.
Changed 37 MB to 37 Mb
> Updating csv file size

- src/explore-education-statistics-frontend/src/pages/_app.tsx
This PR:
* attempts to fix the loading of environment variables on the public frontend. If this PR doesn't work, we may have to revert the wider changes related to the refactoring of environment variables
> EES-4470 - fix env var loading

- README.md
This PR:
* Mentions node 18 in the README. We've recently changed node version from `16` to `18`
> EES-4459 - mention node 18 in the README

- tests/test-data/files/small-files/replace-data/remove_filter_after.csv
- tests/test-data/files/small-files/replace-data/remove_filter_after.meta.csv
- tests/test-data/files/small-files/replace-data/remove_filter_before.csv
- tests/test-data/files/small-files/replace-data/remove_filter_before.meta.csv
- tests/test-data/files/small-files/replace-data/remove_filter_item_after_visual_impair.csv
- tests/test-data/files/small-files/replace-data/remove_filter_item_after_visual_impair.meta.csv
- tests/test-data/files/small-files/replace-data/remove_filter_item_before.csv
- tests/test-data/files/small-files/replace-data/remove_filter_item_before.meta.csv
Adding a couple of test data sets I created around replacing data:
- One replacement removes a filter found in the first data set
- The other replacement removes a filter item found in the first data set
> EES-4460 New test data sets around removing filter/filter item

- tests/robot-tests/tests/admin/bau/adopt_methodology.robot
Quick PR to fix a UI test failure introduced by https://github.com/dfe-analytical-services/explore-education-statistics/pull/4308
> EES-4531 Fix adopt_methodology.robot failure

- src/explore-education-statistics-common/src/modules/table-tool/components/LocationFiltersForm.tsx
Show the error summary on blur on the table tool locations form.
> EES-4435 fix error summary on location filters form

- tests/robot-tests/tests/libs/admin_api.py
Small fix to ContactTelNo to make it valid, now that there is extra validation.
> EES-4585 Fix UI tests

- tests/robot-tests/tests/admin/analyst/manage_publication_as_publication_owner.robot
- tests/robot-tests/tests/admin_and_public/bau/publish_publication_update.robot
Just fixes a couple of broken UI tests after the contact telephone validation changes
> EES-4585 More UI fixes

- src/explore-education-statistics-common/src/contexts/__tests__/NetworkActivityContext.test.tsx
This PR attempts to fix the flakiness of the `updates 'requestCount' correctly when multiple concurrent requests` test case in the `NetworkActivityContext` suite.
I believe there's a bit of flakiness to this because there isn't sufficient delays in the mocked responses meaning that there will be race conditions depending on how quickly tasks are being processed in the event loop.
To deal with this, I've just staggered the requests with a decent amount of delay to hopefully avoid this.
> test: attempt to reduce flakiness of network activity concurrent request

- src/explore-education-statistics-admin/src/pages/publication/components/PublicationGuidance.tsx
Update the draft release status modal to have the correct tag for 'In Review Amendment'.
> EES-4587 correct In Review Amendment heading in status modal

- src/explore-education-statistics-admin/src/pages/publication/__tests__/PublicationContactPage.test.tsx
- src/explore-education-statistics-admin/src/pages/publication/components/PublicationContactForm.tsx
- src/explore-education-statistics-admin/src/pages/publication/components/PublicationForm.tsx
- src/explore-education-statistics-admin/src/pages/publication/components/__tests__/PublicationForm.test.tsx
Makes the publication contact tel no optional again.
> EES-4645 make publication contact no optional

- src/explore-education-statistics-common/src/components/form/FormBaseTextArea.tsx
- src/explore-education-statistics-common/src/components/form/FormCharacterCount.tsx
- src/explore-education-statistics-common/src/components/form/FormFieldTextArea.tsx
- src/explore-education-statistics-common/src/components/form/rhf/RHFFormField.tsx
- src/explore-education-statistics-common/src/components/form/rhf/RHFFormFieldTextArea.tsx
- src/explore-education-statistics-common/src/components/form/rhf/RHFFormTextArea.tsx
- src/explore-education-statistics-common/src/components/form/rhf/__tests__/RHFFormTextArea.test.tsx
- src/explore-education-statistics-common/src/components/form/rhf/__tests__/__snapshots__/RHFFormTextArea.test.tsx.snap
The update to react hook forms for the publication details forms broke the character count so it no longer updated. This fixes it.
> EES-4634 fix text area character count

- src/explore-education-statistics-common/src/modules/release/components/NationalStatisticsSection.tsx
- src/explore-education-statistics-common/src/modules/release/components/__tests__/NationalStatisticsSection.test.tsx
Updates the National Statistics description and adds tests for the component.
> EES-4620 update national statistics description

- src/explore-education-statistics-admin/src/pages/publication/components/PublicationContactForm.tsx
- src/explore-education-statistics-admin/src/pages/publication/components/PublicationForm.tsx
- src/explore-education-statistics-admin/src/pages/release/content/components/EditableKeyStatDataBlockForm.tsx
- src/explore-education-statistics-admin/src/pages/release/content/components/EditableKeyStatTextForm.tsx
- src/explore-education-statistics-admin/src/pages/release/data/components/AncillaryFileForm.tsx
- src/explore-education-statistics-admin/src/pages/release/data/components/ReleaseDataUploadsSection.tsx
- src/explore-education-statistics-admin/src/pages/release/data/components/ReleaseFileUploadsSection.tsx
- src/explore-education-statistics-admin/src/pages/release/datablocks/components/DataBlockDetailsForm.tsx
- src/explore-education-statistics-admin/src/pages/release/datablocks/components/chart/ChartConfiguration.tsx
- src/explore-education-statistics-admin/src/pages/release/pre-release/components/__tests__/PreReleaseUserAccessForm.test.tsx
- src/explore-education-statistics-common/src/components/form/FormBaseInput.tsx
- src/explore-education-statistics-common/src/components/form/FormBaseTextArea.tsx
- src/explore-education-statistics-common/src/components/form/FormSearchBar.tsx
- src/explore-education-statistics-common/src/components/form/__tests__/FormBaseInput.test.tsx
- src/explore-education-statistics-common/src/components/form/__tests__/FormTextArea.test.tsx
Automatically trim values in text inputs and text areas.
Feedback on an earlier version of this PR, https://github.com/dfe-analytical-services/explore-education-statistics/pull/4400,  suggested this approach so I'll close that PR in favour of this one.
> EES-4584 trim whitespace in forms

- tests/robot-tests/tests/admin_and_public/bau/data_catalogue.robot
This PR fixes the Stale element reference issue which was happening in data catalogue for 'Choose Publication' Test Case.
> EES-4697 Stale element reference fix

- README.md
Update the setup guide:
- corrected anchors to section headings/files/URLs
- add clarity to IdP, storage emulator, and seed data steps
> README: Fix section anchors, update/clarify setup stages.

- src/explore-education-statistics-admin/src/pages/themes/components/ThemeForm.tsx
- src/explore-education-statistics-admin/src/pages/themes/topics/components/TopicForm.tsx
Converts the following forms to React Hook Form:
- create / edit theme
- create / edit topic
> EES-4752 RHF theme and topic forms

- src/explore-education-statistics-admin/src/pages/legacy-releases/components/LegacyReleaseForm.tsx
- src/explore-education-statistics-admin/src/pages/legacy-releases/components/__tests__/LegacyReleaseForm.test.tsx
- src/explore-education-statistics-admin/src/pages/publication/components/PublicationInviteNewUsersForm.tsx
- src/explore-education-statistics-admin/src/pages/publication/components/PublicationReleaseContributorsForm.tsx
- src/explore-education-statistics-admin/src/pages/publication/components/__tests__/PublicationInviteNewUsersForm.test.tsx
- tests/robot-tests/tests/admin/analyst/invite_contributor_as_publication_owner.robot
Explain the **motivation** for making this change. What existing problem does the pull request solve?
You might also want to think about the following:
- How did you solve complex parts of the problem? Other contributors may benefit from knowing more about your solution.
- Are there any potential tradeoffs that need mentioning, or edge cases that have not been covered?
- Have you added a reusable piece of functionality? Consider including some code snippets to better illustrate its usage.
Are there any changes that were closely related to this change but not directly part of the main work e.g. refactoring, fixes, etc?
Are there any screenshots that help illustrate the change made?
> EES-4762 RHF publication forms

- tests/robot-tests/scripts/create_snapshots.py
**Motivation**
When the create_snapshots.py python file was being run, it occasionally failed to complete, however there was no process in place to pick up these failures and notify relevant parties.
**Changes**
Wrap script functionality in an exception handling block in order to catch any errors raised during execution, and send notifications to the appropriate Slack channel.
The exception notification is sent using the webhook parameter, which is an _optional_ parameter in the local development environment, however this parameter is always present during execution of the pipeline.
**Note for reviewers**
None of the code within the try block should have changed (it has just been indented)
> EES-4553: Add exception handling and Slack notifications to snapshot creation script

- README.md
- src/GovUk.Education.ExploreEducationStatistics.Public.Data.Processor/Functions/HelloWorldFunction.cs
- src/GovUk.Education.ExploreEducationStatistics.Public.Data.Processor/GovUk.Education.ExploreEducationStatistics.Public.Data.Processor.csproj
- src/GovUk.Education.ExploreEducationStatistics.Public.Data.Processor/Program.cs
- src/GovUk.Education.ExploreEducationStatistics.Public.Data.Processor/host.json
- src/GovUk.Education.ExploreEducationStatistics.Public.Data.Processor/local.settings.json
- src/GovUk.Education.ExploreEducationStatistics.sln
- useful-scripts/start.ts
This PR creates a new `Public.Data.Processor` function project (with a basic `HelloWorldFunction`). 
We need this to enable @Dancemammal to integrate this project into the build and deployment pipeline as part of EES-4807.
> EES-4807 Add `Public.Data.Processor` project with HelloWorldFunction

- src/GovUk.Education.ExploreEducationStatistics.Data.Services.Tests/ObservationServiceTests.cs
- src/GovUk.Education.ExploreEducationStatistics.Data.Services/ObservationService.cs
- useful-scripts/get_data_block_responses/get_data_block_responses.py
This PR implements a performance optimisation found by Paul. See Jira ticket for more details.
> EES-4522 Use RIGHT JOIN in Observation SQL query

- src/GovUk.Education.ExploreEducationStatistics.Data.Services.Tests/ObservationServiceTests.cs
- src/GovUk.Education.ExploreEducationStatistics.Data.Services/ObservationService.cs
This reverts commit f61bbcd53bc7afa84f5e821da41f0a1d6bc69d2c.
> EES-4522 Restore using JOINs again in table/filter/time_period DB query

- src/GovUk.Education.ExploreEducationStatistics.Data.Services.Tests/ObservationServiceTests.cs
- src/GovUk.Education.ExploreEducationStatistics.Data.Services/ObservationService.cs
This reverts commit c15a324d1b661d6d33ff0361c39d044a229a8ce9.
> EES-4522 Switch back to not using JOIN again for testing

- src/explore-education-statistics-frontend/src/components/Page.tsx
- src/explore-education-statistics-frontend/src/components/UserTestingBanner.tsx
- src/explore-education-statistics-frontend/src/components/__tests__/UserTestingBanner.test.tsx
- src/explore-education-statistics-frontend/src/hooks/useCookies.ts
- Updates the user testing banner text and link
- Sets the cookie value to have a version number so we can change that to force the banner to be shown to all users again
> EES-4819 update user testing banner

- src/GovUk.Education.ExploreEducationStatistics.Data.Services.Tests/ObservationServiceTests.cs
- src/GovUk.Education.ExploreEducationStatistics.Data.Services/ObservationService.cs
This PR readds using the JOIN to a DB query - I'm readding this so I can test the performance via get_datablock_responses on Dev, now that we've added the index as part of EES-4521
> EES-4522 Use JOIN again for testing

- src/GovUk.Education.ExploreEducationStatistics.Data.Services.Tests/ObservationServiceTests.cs
- src/GovUk.Education.ExploreEducationStatistics.Data.Services/ObservationService.cs
This reverts commit 7240af908d56c6d1f0cf39159dae8fac95447e22.
Explain the **motivation** for making this change. What existing problem does the pull request solve?
You might also want to think about the following:
- How did you solve complex parts of the problem? Other contributors may benefit from knowing more about your solution.
- Are there any potential tradeoffs that need mentioning, or edge cases that have not been covered?
- Have you added a reusable piece of functionality? Consider including some code snippets to better illustrate its usage.
Are there any changes that were closely related to this change but not directly part of the main work e.g. refactoring, fixes, etc?
Are there any screenshots that help illustrate the change made?
> Revert "EES-4522 Use JOINs again for testing""

- infrastructure/templates/template.json
This PR adds in missing template params to the ARM template following EES-4814.
> EES-4814 - adding missing template variables to ARM template

- azure-pipelines-ui-tests.dfe.yml
- tests/robot-tests/args_and_variables.py
- tests/robot-tests/scripts/run_tests_pipeline.py
This PR:
- adds additional parameters for the Robot tests running in the pipeline to be accessed and used securely.
> EES-4814 - adding new user password parameters to support Robot tests in CI pipeline

- src/GovUk.Education.ExploreEducationStatistics.Common/Model/TimeIdentifier.cs
- src/GovUk.Education.ExploreEducationStatistics.Data.Services.Tests/TimeIdentifierUtilTests.cs
- src/GovUk.Education.ExploreEducationStatistics.Data.Services.Tests/TimePeriodUtilTests.cs
- src/explore-education-statistics-common/src/components/Tabs.tsx
> Merge master back into dev

- src/GovUk.Education.ExploreEducationStatistics.Notifier/README.md
Add local development details for the Notifier Azure function.
> Add Notifier README file

- styleguides/styleguide-frontend.md
Updates the testing section of the frontend styleguide following changes to Testing Library that were part of the React 18 upgrade.
> docs: Frontend styleguide updates following react 18 upgrade

- tests/robot-tests/tests/admin_and_public_2/bau/publish_methodology_publication_update.robot
- tests/robot-tests/tests/libs/common.robot
This PR verifies the following UI tests using robot tests
-  Publication and methodology redirect
-  Confirmation modal validation while updating publication.
Attached the latest robot test suite results and all the test cases are passing now
> EES-4917 UI tests for publication and methodology re-directs

- src/explore-education-statistics-common/src/components/form/FormCheckboxSearchSubGroups.tsx
- src/explore-education-statistics-common/src/components/form/__tests__/__snapshots__/FormCheckboxSearchSubGroups.test.tsx.snap
Fixes a bug with indicator and filter checkboxes in the table tool where in certain circumstances they weren't responsive.
> EES-5023 fix unresponsive indicator checkboxes

- src/explore-education-statistics-admin/src/pages/release/datablocks/components/chart/contexts/__tests__/ChartBuilderFormsContext.test.tsx
- src/explore-education-statistics-admin/src/prototypes/PrototypeDataCatalog.tsx
- src/explore-education-statistics-admin/src/prototypes/PrototypeDataSelected5.tsx
- src/explore-education-statistics-admin/src/prototypes/PrototypeReleaseNavigation.tsx
- src/explore-education-statistics-admin/src/prototypes/PrototypeReleaseNavigation2.tsx
- src/explore-education-statistics-admin/src/prototypes/PrototypeReleaseNavigation3.tsx
- src/explore-education-statistics-admin/src/prototypes/PrototypeReleaseNavigation4.tsx
- src/explore-education-statistics-admin/src/prototypes/PrototypeReleaseNavigation5.tsx
- src/explore-education-statistics-admin/src/prototypes/PrototypeReleaseNavigation6.tsx
- src/explore-education-statistics-admin/src/prototypes/PrototypeReleaseNavigation7.tsx
- src/explore-education-statistics-admin/src/prototypes/PrototypeReleaseNavigation8.tsx
- src/explore-education-statistics-admin/src/prototypes/PrototypeReleaseNavigation9.tsx
- src/explore-education-statistics-admin/src/prototypes/admin-api/PrototypePublicationSubjects.tsx
- src/explore-education-statistics-admin/src/prototypes/admin-api/components/PrototypePreviewExample.tsx
- src/explore-education-statistics-admin/src/prototypes/admin-api/components/PrototypePublicationSubject.tsx
- src/explore-education-statistics-admin/src/prototypes/admin-api/components/PrototypePublicationSubjectList.tsx
- src/explore-education-statistics-admin/src/prototypes/components/PrototypeToggleMoreDetails.tsx
- src/explore-education-statistics-admin/src/prototypes/page-view/PrototypeReleaseContent.tsx
- src/explore-education-statistics-admin/src/prototypes/page-view/PrototypeReleaseContentAccordionSection.tsx
- src/explore-education-statistics-admin/src/prototypes/page-view/PrototypeReleaseEditableBlock.tsx
- src/explore-education-statistics-admin/src/prototypes/page-view/PrototypeReleaseHeadlines.tsx
- src/explore-education-statistics-common/src/components/form/FormCheckboxGroup.tsx
- src/explore-education-statistics-common/src/components/form/rhf/FormProvider.tsx
- src/explore-education-statistics-common/src/hooks/__tests__/useAsyncCallback.test.ts
- src/explore-education-statistics-common/src/hooks/useAsyncCallback.ts
- src/explore-education-statistics-common/src/modules/table-tool/components/__tests__/Wizard.test.tsx
- src/explore-education-statistics-common/test/extend-expect/toHaveScrolledIntoView.ts
Fixes a bunch of linting warnings in the frontend.
> Fix lint warnings

- tests/robot-tests/tests/admin_and_public/bau/data_catalogue.robot
One liner change to fix a failing UI test
> EES-5060 Fix data_catalogue.robot

- src/explore-education-statistics-admin/src/prototypes/PrototypeHomepage.tsx
- src/explore-education-statistics-admin/src/prototypes/PrototypeHomepage2.tsx
- src/explore-education-statistics-admin/src/prototypes/PrototypeHomepage3.tsx
- src/explore-education-statistics-admin/src/prototypes/PrototypeHomepage4.tsx
- src/explore-education-statistics-admin/src/prototypes/PrototypeHomepage5.tsx
- src/explore-education-statistics-admin/src/prototypes/PrototypeHomepage6.tsx
- src/explore-education-statistics-admin/src/prototypes/PrototypeHomepageDashboard.tsx
- src/explore-education-statistics-admin/src/prototypes/PrototypeHomepageDashboard2.tsx
- src/explore-education-statistics-frontend/src/pages/index.tsx
- tests/robot-tests/tests/general_public/miscellaneous.robot
To apply consistent naming for education services.
> EES-5063: Update home page related service link text.

- src/GovUk.Education.ExploreEducationStatistics.Admin/Startup.cs
This PR fixes incorrectly formatted validation error responses, resulting in unrecognised API errors in the frontend during form submissions.
> EES-5084 Add ProblemDetailsResultFilter to admin

- src/explore-education-statistics-common/src/components/NotificationBanner.tsx
- src/explore-education-statistics-frontend/src/modules/data-catalogue/DataCataloguePageNew.tsx
> EES-4891 add notification banner to new data catalogue page

- src/GovUk.Education.ExploreEducationStatistics.Admin/Controllers/Api/Bau/DataSetFileMetaMigrationController.cs
A small change to the migration so it doesn't stop if it finds a data file with no observations.
> EES-4662 Make migration more robust

- infrastructure/templates/public-api/deploy-stage-template.yml
- infrastructure/templates/public-api/main.bicep
Set the Public Data Processor Function app `ContentDb` connection string setting
> EES-5093 Set Public Data Processor function app ContentDb connection string setting

- src/GovUk.Education.ExploreEducationStatistics.Admin/Controllers/Api/Bau/DataSetFileMetaMigrationController.cs
The migration failed to run on Test - it timed out and the change wasn't made. So this PR is to allow us to run the migration on batches of Files rather than do them all at once.
> EES-5151 Update migration to do it in batches

- src/explore-education-statistics-common/src/components/form/FormSelect.tsx
- src/explore-education-statistics-common/src/components/form/__tests__/FormSelect.test.tsx
- src/explore-education-statistics-common/src/components/form/__tests__/__snapshots__/FormSelect.test.tsx.snap
- src/explore-education-statistics-frontend/src/modules/data-catalogue/DataCataloguePageNew.tsx
- src/explore-education-statistics-frontend/src/modules/data-catalogue/__tests__/DataCataloguePage.test.tsx
- src/explore-education-statistics-frontend/src/modules/data-catalogue/components/Filters.tsx
- src/explore-education-statistics-frontend/src/modules/find-statistics/components/ThemesModal.tsx
Updates to the new data catalogue page:
- add the themes guidance modal to the themes filter
- banner text update
- change 'clear filters' to 'reset filters'
- add methodology related link
> EES-5175 and EES-5177 data catalogue updates

- infrastructure/templates/public-api/components/functionApp.bicep
- infrastructure/templates/public-api/deploy-stage-template.yml
- infrastructure/templates/public-api/main.bicep
- infrastructure/templates/public-api/validate-stage-template.yml
- infrastructure/templates/template.json
- src/GovUk.Education.ExploreEducationStatistics.Admin.Tests/Services/Public.Data/ProcessorClientTests.cs
- src/GovUk.Education.ExploreEducationStatistics.Admin/Services/Public.Data/ProcessorClient.cs
- src/GovUk.Education.ExploreEducationStatistics.Admin/Settings/PublicDataProcessorOptions.cs
- src/GovUk.Education.ExploreEducationStatistics.Admin/Startup.cs
- src/GovUk.Education.ExploreEducationStatistics.Public.Data.Processor/Functions/CreateInitialDataSetVersionFunction.cs
- src/GovUk.Education.ExploreEducationStatistics.Public.Data.Processor/ProcessorHostBuilder.cs
- src/GovUk.Education.ExploreEducationStatistics.Publisher/PublisherHostBuilderExtensions.cs
This PR:
* connects a manually-created App Registration to the Data Processor.
* whitelists the Admin App Service and managed identity to be able to access the Function App.
* adds access token requesting into Admin to allow it to authenticate with the Data Processor.
* enables temporary public network access to the Data Processor staging slot in order to be able to perform deploys.
As another prerequisite to running the pipeline, this App Registration must be set up firstly and its Id supplied as a Library variable for the Public API and a Release pipeline variable for the ARM deploy.
(it also needs to be added to the "template override variables" in the usual fashion for the "Validate" and "Deploy" stages.)
> EES-5119 - adding Managed Identity authentication to the Data Processor

- infrastructure/templates/template.json
Leaving Publisher connection as it works for Functions.
> EES-XXXX - changing connection string type to Custom for PSQL connection for Admin

- infrastructure/templates/public-api/main.bicep
Explain the **motivation** for making this change. What existing problem does the pull request solve?
You might also want to think about the following:
- How did you solve complex parts of the problem? Other contributors may benefit from knowing more about your solution.
- Are there any potential tradeoffs that need mentioning, or edge cases that have not been covered?
- Have you added a reusable piece of functionality? Consider including some code snippets to better illustrate its usage.
Are there any changes that were closely related to this change but not directly part of the main work e.g. refactoring, fixes, etc?
Are there any screenshots that help illustrate the change made?
> EES-XXXX - fix out of date app setting path

- src/GovUk.Education.ExploreEducationStatistics.Content.Api.Tests/Controllers/PublicationControllerTests.cs
Fixes the build error caused by the previous PR
> EES-XXXX - Fix dotnet build error

- src/GovUk.Education.ExploreEducationStatistics.Common.Tests/Extensions/TypeExtensionsTests.cs
- src/GovUk.Education.ExploreEducationStatistics.Common.Tests/Extensions/ValidationProblemViewModelTestExtensions.cs
- src/GovUk.Education.ExploreEducationStatistics.Common/Extensions/TypeExtensions.cs
- src/GovUk.Education.ExploreEducationStatistics.Common/ModelBinding/EmptyStringMetadataDetailsProvider.cs
- src/GovUk.Education.ExploreEducationStatistics.Common/Validators/ValidationMessages.cs
- src/GovUk.Education.ExploreEducationStatistics.Public.Data.Api.Tests/Controllers/DataSetsControllerGetQueryTests.cs
- src/GovUk.Education.ExploreEducationStatistics.Public.Data.Api.Tests/Filters/InvalidRequestInputFilterTests.cs
- src/GovUk.Education.ExploreEducationStatistics.Public.Data.Api/Extensions/MvcOptionsExtensions.cs
- src/GovUk.Education.ExploreEducationStatistics.Public.Data.Api/Filters/InvalidRequestInputFilter.cs
- src/GovUk.Education.ExploreEducationStatistics.Public.Data.Api/Startup.cs
This PR:
- Fixes query keys that are set to empty strings in the request being bound as null in the request model. For example, `?locations.eq=` would be bound as null instead of an empty string, resulting in unexpected behaviour in the API.
- Fixes invalid values not resulting in validation errors. These are typically where a value has been provided, but is the wrong type or format e.g. `?page=ten` (instead of `?page=10`). We now return `InvalidValue` errors in these cases.
- Fixes unknown fields in the request not resulting in validation errors. We now output an `UnknownField` error whenever these are encountered in the body or query parameters.
- Renamed the `RequiredField` error to `RequiredValue`.
- Changed `InvalidRequestInputFilter` to be an `IAsyncActionFilter` instead of …
> EES-4716 Fix various issues with data set query endpoint

- src/GovUk.Education.ExploreEducationStatistics.Admin.Tests/Controllers/Api/Public.Data/DataSetVersionMappingControllerTests.cs
- src/GovUk.Education.ExploreEducationStatistics.Admin/Controllers/Api/Public.Data/DataSetVersionMappingController.cs
- src/GovUk.Education.ExploreEducationStatistics.Admin/Requests/Public.Data/BatchMappingUpdateRequests.cs
- src/GovUk.Education.ExploreEducationStatistics.Admin/Services/Interfaces/Public.Data/IDataSetVersionMappingService.cs
- src/GovUk.Education.ExploreEducationStatistics.Admin/Services/Public.Data/DataSetVersionMappingService.cs
- src/GovUk.Education.ExploreEducationStatistics.Admin/ViewModels/Public.Data/BatchMappingUpdateViewModels.cs
This PR:
- adds in an endpoint for retrieving the current Location mappings.  This is in order for the Location mapping page to be able to render the current state of Location mappings.
Calling this endpoint will result in JSON of the form:
```json
{
"Levels": {
"Country": {
"Mappings": {
"source-location-1-key": {
"Type": "ManualNone",
"Source": {
"Code": "Source location 1 code",
"OldCode": null,
"Urn": null,
"LaEstab": null,
"Ukprn": null,
"Label": "Source location 1"
},
"CandidateKey": null
},
"source-location-3-key": {
"Type": "ManualMapped",
"Source": {
"Code": "Source location 3 code",
"OldCode": null,
"Urn": null,
"LaEstab": null,
"Ukprn": null,
"Label": "Source location 3"
},
"CandidateKey": "target-location-1-key"
}
},
"Candidates": {
"target-location-1-key": {
"Code": "Target …
```
> EES-5111 - endpoint to retrieve location mappings

- src/explore-education-statistics-frontend/src/pages/accessibility-statement.tsx
Updates the accessibility statement. Also:
- makes external links on the page open in a new tab and have 'opens in a new tab' in the link text to make them consistent with other external links
- removes unnecessary section elements.
> EES-5251 updated accessibility statement

- tests/robot-tests/scripts/create_snapshots.py
- tests/robot-tests/tests/snapshots/data_catalogue_snapshot.json
- tests/robot-tests/tests/snapshots/find_statistics_snapshot.json
This PR fixes snapshots after changes to the Find statistics and Data catalogue pages.
It also updates the snapshots.
> EES-5270 Fix snapshots

- tests/robot-tests/tests/general_public/prod_only/redirects.robot
- tests/robot-tests/tests/general_public/prod_only/statistics_page.robot
- tests/robot-tests/tests/general_public/redirects.robot
Updated UI tests scripts for prod only tests
> EES-5342-Prod only UI test failures

- src/explore-education-statistics-frontend/src/modules/data-catalogue/DataCataloguePage.tsx
Removes the 'This page has changed' banner as the page isn't new any more..
> EES-5364 remove notification banner on data catalogue

- src/GovUk.Education.ExploreEducationStatistics.Admin.Tests/Controllers/Api/Public.Data/DataSetVersionMappingControllerTests.cs
- src/GovUk.Education.ExploreEducationStatistics.Public.Data.Api.Tests/Controllers/DataSetsControllerTests.cs
- src/GovUk.Education.ExploreEducationStatistics.Public.Data.Model.Tests/Fixtures/DataSetVersionMappingGeneratorExtensions.cs
- src/GovUk.Education.ExploreEducationStatistics.Public.Data.Model.Tests/Fixtures/FilterMappingPlanGeneratorExtensions.cs
- src/GovUk.Education.ExploreEducationStatistics.Public.Data.Model.Tests/Fixtures/LocationMappingPlanGeneratorExtensions.cs
- src/GovUk.Education.ExploreEducationStatistics.Public.Data.Model.Tests/Fixtures/LocationMetaGeneratorExtensions.cs
- src/GovUk.Education.ExploreEducationStatistics.Public.Data.Model/DataSetVersionMapping.cs
- src/GovUk.Education.ExploreEducationStatistics.Public.Data.Processor.Tests/Functions/ImportMetadataFunctionTests.cs
- src/GovUk.Education.ExploreEducationStatistics.Public.Data.Processor.Tests/Functions/ProcessNextDataSetVersionMappingsFunctionTests.cs
- src/GovUk.Education.ExploreEducationStatistics.Public.Data.Processor/Services/DataSetVersionMappingService.cs
This PR:
- adds test data generators for DataSetVersionMapping.
- reworks existing tests to use new generators.
> EES-4954 - add test data generators

- src/GovUk.Education.ExploreEducationStatistics.Publisher.Tests/Services/PublishingServiceTests.cs
- src/GovUk.Education.ExploreEducationStatistics.Publisher/Services/PublishingService.cs
This PR is a  bugfix for https://github.com/dfe-analytical-services/explore-education-statistics/pull/5099 which inadvertently missed updating the configuration referent to the public storage account in `PublishingService`, affecting the copying of files between private and public storage.
> 🐛 EES-4930 EES-5377 Correct PublishingService reference to the public storage connection string

- src/explore-education-statistics-frontend/src/pages/privacy-notice.tsx
This PR fixes the privacy notice date.
> EES-5483 Fix privacy notice date

- tests/test-data/files/small-files/indicator_unit_test.csv
Fixing a small error in the indicator unit test data file.
> EES-5478 Fix indicator unit test data file

- infrastructure/templates/template.json
This PR merges Master branch back into dev .
> Merge Master into dev

- src/explore-education-statistics-common/src/components/Code.module.scss
- src/explore-education-statistics-common/src/components/CodeBlock.tsx
- src/explore-education-statistics-frontend/next.config.js
- src/explore-education-statistics-frontend/src/modules/data-catalogue/components/DataSetFileUsage.tsx
See [ticket 5464](https://dfedigital.atlassian.net/browse/EES-5464)  and [ticket 4723](https://dfedigital.atlassian.net/browse/EES-4723)
Following previous merge #5236,  
Notable changes include
- Add code theme to improve accessibility
- Add the previously forgotten rewrites to allow for nicer file download links
> EES-5464 improvements

- src/explore-education-statistics-common/src/components/Code.module.scss
- src/explore-education-statistics-frontend/next.config.js
- fix rewrite env var URL
- codeblock background contrast increased for improve readability
> EES-5464 increase contrast

- azure-pipelines.dfe.yml
- infrastructure/infrastructure-pipeline.yml
This PR adds `test` as a branch that can be used to create automated deploys.  It will be rolled out in conjunction with manual updates to the classic Release pipelines in DevOps which will allow deploys to the Test environment to be triggered from builds against the `test` branch.
> EES-5552 - adding test as an additional branch from which to perform deploys

- src/GovUk.Education.ExploreEducationStatistics.Public.Data.Api.Tests/Controllers/DataSetsControllerGetQueryTests.cs
- src/GovUk.Education.ExploreEducationStatistics.Public.Data.Api.Tests/Controllers/DataSetsControllerPostQueryTests.cs
- src/GovUk.Education.ExploreEducationStatistics.Public.Data.Api/Services/DataSetQueryService.cs
This fix appends an extra sort on the data's `id` column to ensure there is always a tie-break that can produce a deterministic order.
> EES-5524 Fix non-deterministic data set query sorting

- src/explore-education-statistics-common/src/components/form/FormSearchBar.module.scss
> EES-5306 fix high contrast style for search form

- global.json
This PR upgrades .NET sdk version to resolve failing builds on Dev
> Upgrade .NET SDK to 8.0.402

- infrastructure/templates/public-api/abbreviations.bicep
- infrastructure/templates/public-api/application/public-api/publicApiDocs.bicep
- infrastructure/templates/public-api/components/staticWebApp.bicep
- infrastructure/templates/public-api/main.bicep
- infrastructure/templates/public-api/parameters/main-prod.bicepparam
- infrastructure/templates/public-api/types.bicep
This PR adds an Azure Static Web App for the public API docs site.
> EES-5608 Add basic infrastructure for public API docs site

- src/explore-education-statistics-admin/src/pages/release/content/components/EditableKeyStat.tsx
- src/explore-education-statistics-admin/src/pages/release/content/components/EditableKeyStatDataBlock.tsx
- src/explore-education-statistics-admin/src/pages/release/content/components/EditableKeyStatDataBlockForm.tsx
- src/explore-education-statistics-admin/src/pages/release/content/components/EditableKeyStatPreview.tsx
- src/explore-education-statistics-admin/src/pages/release/content/components/EditableKeyStatText.tsx
- src/explore-education-statistics-admin/src/pages/release/content/components/EditableKeyStatTextForm.tsx
- src/explore-education-statistics-admin/src/pages/release/content/components/KeyStatistics.module.scss
- src/explore-education-statistics-admin/src/pages/release/content/components/KeyStatistics.tsx
- src/explore-education-statistics-admin/src/pages/release/datablocks/components/chart/ChartDataSetsConfiguration.module.scss
- src/explore-education-statistics-admin/src/pages/release/datablocks/components/chart/ChartDataSetsConfiguration.tsx
- src/explore-education-statistics-admin/src/pages/release/datablocks/components/chart/__tests__/ChartDataSetsConfiguration.test.tsx
- src/explore-education-statistics-common/src/modules/find-statistics/components/KeyStatTile.module.scss
- src/explore-education-statistics-common/src/modules/find-statistics/components/KeyStatTile.tsx
Changes chart data sets and key stats to use the `ReorderableList` component.
> EES-5586 use reordeable list in chart data sets and key stats

- src/explore-education-statistics-frontend/src/pages/index.tsx
Changes made:
- Updated homepage link related to schools and benchmarking
> EES-5695 Update Homepage Link

- tests/robot-tests/tests/general_public/miscellaneous.robot
Updated a link text on the homepage to a fix UI test failure in` miscellaneous.robot` file.
> EES-5711-Fixing a UI test failure in general_public suite

- src/explore-education-statistics-common/src/modules/table-tool/components/__tests__/TimePeriodDataTable.test.tsx
- src/explore-education-statistics-common/src/modules/table-tool/components/__tests__/__snapshots__/TimePeriodDataTable.test.tsx.snap
- src/explore-education-statistics-common/src/modules/table-tool/utils/__tests__/mapTableToJson.test.ts
- src/explore-education-statistics-common/src/modules/table-tool/utils/__tests__/optimizeFilters.test.ts
- src/explore-education-statistics-common/src/modules/table-tool/utils/optimizeFilters.ts
- Remove check to hide filter/multiple groups
- update tests to match new changes to tables
> EES-5149 remove check to hide filter groups

- infrastructure/templates/public-api/application/public-api/publicApiStorage.bicep
This PR:
- whitelists the Publisher subnet with the Public API storage account
> EES-5724 - grant the Publisher subnet access to the Public API storage

- src/explore-education-statistics-admin/src/pages/release/datablocks/ReleaseDataBlocksPage.tsx
- src/explore-education-statistics-admin/src/pages/release/datablocks/__tests__/ReleaseDataBlocksPage.test.tsx
Show the extra 'Create data block' link at the top of the Data Blocks page when there are more than 5 blocks in total, not just non-featured ones.
> EES-5457 show extra create data block link when more than 5

- src/explore-education-statistics-admin/src/components/form/FormEditor.module.scss
Removes the italic style from blockquotes within CK Editor.
> EES-5455 remove italics for blockquotes in ckeditor

- src/explore-education-statistics-frontend/src/modules/subscriptions/ConfirmSubscriptionPage.tsx
- src/explore-education-statistics-frontend/src/modules/subscriptions/ConfirmUnsubscriptionPage.tsx
- src/explore-education-statistics-frontend/src/modules/subscriptions/NewSubscriptionPage.tsx
Adds `role="status"` to the subscription pages to ensure that changes are announced to screen readers.
> EES-5300 announce subscription status messages to screen readers

- src/explore-education-statistics-common/src/modules/table-tool/components/TableHeadersForm.tsx
This PR updates the 'hint' text in reordering table headers section according to the acceptance criteria in EES-5458
> EES-5458 text update

- src/explore-education-statistics-admin/src/pages/bau/FeedbackPage.tsx
Wording correction to clarify button behaviour (improved UX).
> EES-5469: Change "Show read" button to "Show all".

- src/GovUk.Education.ExploreEducationStatistics.Admin/Services/Methodologies/MethodologyService.cs
- src/GovUk.Education.ExploreEducationStatistics.Content.ViewModels/PublicationSummaryViewModel.cs
- src/explore-education-statistics-common/src/services/publicationService.ts
Fix to optional latest release
> EES-5219 Fix to optional latest release

- tests/robot-tests/tests/general_public/data_set_page_absence_in_prus.robot
- tests/robot-tests/tests/general_public/prod_only/redirects.robot
- tests/robot-tests/tests/general_public/prod_only/statistics_page.robot
- tests/robot-tests/tests/general_public/redirects.robot
- tests/robot-tests/tests/general_public/statistics_page.robot
Ran `pnpm format:robot ` from the project root to format all the robot files.
> EES-Formatted all robot files

- src/explore-education-statistics-common/src/modules/charts/components/ChartRenderer.tsx
- src/explore-education-statistics-common/src/modules/charts/components/utils/getMapInitialBoundaryLevel.ts
- tests/robot-tests/.env.example
- tests/robot-tests/tests/admin_and_public_2/bau/maps_across_time.robot
- tests/robot-tests/tests/libs/charts.robot
Fixes maps across time to allow for the boundary footnote to update when the boundaries are changed in the map.
Also added a robot test to check both map boundaries and footnotes change when selecting data sets with different boundaries
> ees-5843 Dynamic boundary footnote bugfix & Maps across time robot test

- src/GovUk.Education.ExploreEducationStatistics.Data.Processor/Services/ImporterService.cs
- src/GovUk.Education.ExploreEducationStatistics.Data.Processor/Services/ValidatorService.cs
This PR fixes an error when two or more filter items with the same label were found under different groups.
This is achieved by adding a condition to identify the filter's parent group, and then assigning it as the auto-selection filter item.
The PR also adds some basic validation to prevent a data set from being imported which defines a `filter_default` column as well as a filter group hierarchy, as this is not yet supported.
> EES-5860: Add handling for multiple filter items with the same label.

- azure-pipelines-main.yml
- src/explore-education-statistics-api-docs/lib/govuk_tech_docs/path_helpers.rb
This PR fixes an issue in Public API infrastructure build -This unblocks deploying of Public API changes to Pre-production
> Merge Dev into Master-2

- src/GovUk.Education.ExploreEducationStatistics.Admin/Models/DataScreenerResponse.cs
- src/GovUk.Education.ExploreEducationStatistics.Admin/Models/DataScreenerTestResult.cs
- src/GovUk.Education.ExploreEducationStatistics.Admin/Requests/DataScreenerRequest.cs
This PR adds some initial classes which will be implemented once the screener integration gets under way. These models are subject to change as the screener logic is still being developed, but give an idea of the structure as it stands.
> EES-5882: Add Screener API response models.

- src/explore-education-statistics-api-docs/source/getting-started/building-api-integrations/index.html.md.erb
Quick one to fix an old typo we'd made and make clear our plans for a Python library too. I have edited direct in GitHub so will need someone else to run any building / generating if needed.
This PR from yesterday edited the same page - #5654
> Update API SDK docs

- src/explore-education-statistics-api-docs/source/getting-started/building-api-integrations/index.html.md.erb
Quick one to fix the last reviewed date on SDKs page of API docs
#5659
> Fix last reviewed date

- src/explore-education-statistics-api-docs/source/getting-started/building-api-integrations/index.html.md.erb
This PR merges master into the dev branch after the hotfix #5664 was merged.
> Merging master into dev after PR #5664

- src/GovUk.Education.ExploreEducationStatistics.Content.Search.FunctionApp.Tests/Clients/AzureBlobStorage/AzureBlobStorageClientIntegrationTests.cs
- src/GovUk.Education.ExploreEducationStatistics.Content.Search.FunctionApp.Tests/Clients/AzureBlobStorage/AzureBlobStorageIntegrationClient.cs
- src/GovUk.Education.ExploreEducationStatistics.Content.Search.FunctionApp.Tests/Clients/AzureBlobStorage/BlobTests.cs
- src/GovUk.Education.ExploreEducationStatistics.Content.Search.FunctionApp.Tests/Clients/ContentApi/ContentApiClientTests.cs
- src/GovUk.Education.ExploreEducationStatistics.Content.Search.FunctionApp/Clients/AzureBlobStorage/Blob.cs
- src/GovUk.Education.ExploreEducationStatistics.Content.Search.FunctionApp/Extensions/DictionaryExtensions.cs
- src/GovUk.Education.ExploreEducationStatistics.Content.Search.FunctionApp/Functions/HealthChecks/Strategies/AzureBlobStorageHealthCheckStrategy.cs
- src/GovUk.Education.ExploreEducationStatistics.Content.Search.FunctionApp/Functions/HealthChecks/Strategies/ContentApiHealthCheckStrategy.cs
- src/GovUk.Education.ExploreEducationStatistics.Content.Search.FunctionApp/Functions/HealthChecks/Strategies/HeathCheckResult.cs
Improve the logging around metadata when an upload fails.
Add details to successful health check results.
> ESS-5874 Search FunctionApp Tweaks

- src/explore-education-statistics-admin/src/pages/release/data/ReleaseApiDataSetChangelogPage.tsx
- src/explore-education-statistics-admin/src/pages/release/data/__tests__/ReleaseApiDataSetChangelogPage.test.tsx
Fixes public guidance note updating after submitting note update
> EES-5934 public guidance notes update fix

- src/GovUk.Education.ExploreEducationStatistics.Admin.Tests/MockBuilders/AdminEventRaiserMockBuilder.cs
- src/GovUk.Education.ExploreEducationStatistics.Admin.Tests/Services/AdminEventRaiserTests.cs
- src/GovUk.Education.ExploreEducationStatistics.Admin.Tests/Services/PublicationServicePermissionTests.cs
- src/GovUk.Education.ExploreEducationStatistics.Admin.Tests/Services/PublicationServiceTests.cs
- src/GovUk.Education.ExploreEducationStatistics.Admin.Tests/Services/ReleaseServicePermissionTests.cs
- src/GovUk.Education.ExploreEducationStatistics.Admin.Tests/Services/ReleaseServiceTests.cs
- src/GovUk.Education.ExploreEducationStatistics.Admin.Tests/Services/ThemeServicePermissionTests.cs
- src/GovUk.Education.ExploreEducationStatistics.Admin.Tests/Services/ThemeServiceTests.cs
- src/GovUk.Education.ExploreEducationStatistics.Admin.Tests/TestStartup.cs
- src/GovUk.Education.ExploreEducationStatistics.Admin/Services/AdminEventRaiser.cs
- src/GovUk.Education.ExploreEducationStatistics.Admin/Services/Interfaces/IAdminEventRaiser.cs
- src/GovUk.Education.ExploreEducationStatistics.Admin/Services/PublicationService.cs
- src/GovUk.Education.ExploreEducationStatistics.Admin/Services/ReleaseService.cs
- src/GovUk.Education.ExploreEducationStatistics.Admin/Services/ThemeService.cs
- src/GovUk.Education.ExploreEducationStatistics.Admin/Startup.cs
- src/GovUk.Education.ExploreEducationStatistics.Publisher.Tests/Builders/Services/EventRaiserMockBuilder.cs
- src/GovUk.Education.ExploreEducationStatistics.Publisher.Tests/Services/PublisherEventRaiserTests.cs
- src/GovUk.Education.ExploreEducationStatistics.Publisher.Tests/Services/PublishingCompletionServiceTests.cs
- src/GovUk.Education.ExploreEducationStatistics.Publisher/PublisherHostBuilderExtensions.cs
- src/GovUk.Education.ExploreEducationStatistics.Publisher/Services/Interfaces/IPublisherEventRaiser.cs
- src/GovUk.Education.ExploreEducationStatistics.Publisher/Services/PublisherEventRaiser.cs
- src/GovUk.Education.ExploreEducationStatistics.Publisher/Services/PublishingCompletionService.cs
In order to simplify a refactor PR I'm working with, I've separated out this rename into its own PR.
> Renamed all flavours of EventRaiserService to EventRaiser

- src/GovUk.Education.ExploreEducationStatistics.Common.DuckDb/GovUk.Education.ExploreEducationStatistics.Common.DuckDb.csproj
This PR reverts a DuckDB version downgrade for the common DuckDB project.
> EES-6048 - reverting DuckDB version downgrade for common DuckDB project

- src/GovUk.Education.ExploreEducationStatistics.Common/Services/EventGrid/ConfiguredEventGridClientFactory.cs
- src/GovUk.Education.ExploreEducationStatistics.Common/Services/EventGrid/EventGridClientFactory.cs
- src/GovUk.Education.ExploreEducationStatistics.Common/Services/EventGrid/EventRaiser.cs
- src/GovUk.Education.ExploreEducationStatistics.Common/Services/EventGrid/IEventRaiser.cs
- styleguides/events.md
Having recently added Events to Admin and Publisher, this is the first pass at documenting the new components and mechanism.
> First pass at some docs for events

- infrastructure/templates/template.json
To fix the invalid template.json after merging the initial EES-5977 PR.
> EES-5977 analyticsFileMountPath is a parameter

- src/GovUk.Education.ExploreEducationStatistics.Content.Search.FunctionApp/Extensions/LoggerConfigurationExtensions.cs
- src/GovUk.Education.ExploreEducationStatistics.Content.Search.FunctionApp/Extensions/ServiceCollectionExtensions.cs
- src/GovUk.Education.ExploreEducationStatistics.Content.Search.FunctionApp/Functions/HealthChecks/Strategies/LoggingHealthCheck.cs
I've added a Healthcheck that logs test messages.
The theory I want to test is whether logging from Serilog to App Insights works perfectly, but that it is set (for some reason) to a minimum log level of Warning.
> Further Log Troubleshooting

- src/GovUk.Education.ExploreEducationStatistics.Content.Search.FunctionApp.Tests/ProgramTests.cs
- src/GovUk.Education.ExploreEducationStatistics.Content.Search.FunctionApp/Extensions/ConfigurationExtensions.cs
- src/GovUk.Education.ExploreEducationStatistics.Content.Search.FunctionApp/Extensions/HostBuilderExtension.cs
> Log Troubleshooting

- src/GovUk.Education.ExploreEducationStatistics.Common.Tests/Cache/BlobCacheAttributeTests.cs
- src/GovUk.Education.ExploreEducationStatistics.Common.Tests/Cache/CacheAspectTests.cs
- src/GovUk.Education.ExploreEducationStatistics.Common.Tests/Cache/MemoryCacheAttributeTests.cs
- src/GovUk.Education.ExploreEducationStatistics.Content.Api.Tests/Controllers/PublicationControllerCachingTests.cs
- src/GovUk.Education.ExploreEducationStatistics.Content.Api.Tests/Controllers/ReleaseControllerCachingTests.cs
- src/GovUk.Education.ExploreEducationStatistics.Content.Api.Tests/Controllers/ReleaseControllerTests.cs
- src/GovUk.Education.ExploreEducationStatistics.Content.Api.Tests/Controllers/ThemeControllerCachingTests.cs
- src/GovUk.Education.ExploreEducationStatistics.Content.Services.Tests/Cache/GlossaryCacheServiceTests.cs
- src/GovUk.Education.ExploreEducationStatistics.Content.Services.Tests/Cache/MethodologyCacheServiceTests.cs
- src/GovUk.Education.ExploreEducationStatistics.Content.Services.Tests/Cache/PublicationCacheServiceTests.cs
- src/GovUk.Education.ExploreEducationStatistics.Content.Services.Tests/Cache/ReleaseCacheServiceTests.cs
- src/GovUk.Education.ExploreEducationStatistics.Data.Api.Tests/Controllers/TableBuilderMetaControllerTests.cs
Nulls needed casting. And so cast them I have.
> Fix returning nulls - need to be cast.

- src/GovUk.Education.ExploreEducationStatistics.Common/ModelBinding/SeparatedQueryModelBinder.cs
Part of the on-going mission to eradicate all of the build warnings.
> Tiny Fixes

- src/GovUk.Education.ExploreEducationStatistics.Admin.Tests/Controllers/Api/ReleaseVersionsControllerTests.cs
- src/GovUk.Education.ExploreEducationStatistics.Admin.Tests/MockBuilders/DataSetFileBuilder.cs
- src/GovUk.Education.ExploreEducationStatistics.Admin.Tests/Services/DataSetFileStorageTests.cs
- src/GovUk.Education.ExploreEducationStatistics.Admin.Tests/Services/ReleaseDataFileServicePermissionTests.cs
- src/GovUk.Education.ExploreEducationStatistics.Admin.Tests/Services/ReleaseDataFileServiceTests.cs
- src/GovUk.Education.ExploreEducationStatistics.Admin/Controllers/Api/ReleaseVersionsController.cs
- src/GovUk.Education.ExploreEducationStatistics.Admin/Services/DataSetFileStorage.cs
- src/GovUk.Education.ExploreEducationStatistics.Admin/Services/DataSetValidator.cs
- src/GovUk.Education.ExploreEducationStatistics.Admin/Services/IDataSetFileStorage.cs
- src/GovUk.Education.ExploreEducationStatistics.Admin/Services/Interfaces/IReleaseDataFileService.cs
- src/GovUk.Education.ExploreEducationStatistics.Admin/Services/ReleaseDataFileService.cs
- src/GovUk.Education.ExploreEducationStatistics.Admin/ViewModels/DataSetUploadResultViewModel.cs
- src/explore-education-statistics-admin/src/pages/release/data/ReleaseDataFileReplacePage.tsx
- src/explore-education-statistics-admin/src/pages/release/data/components/DataSetUploadModalConfirm.tsx
- src/explore-education-statistics-admin/src/pages/release/data/components/ReleaseDataUploadsSection.tsx
- src/explore-education-statistics-admin/src/pages/release/data/components/__tests__/ReleaseDataUploadsSection.test.tsx
- src/explore-education-statistics-admin/src/services/releaseDataFileService.ts
- tests/robot-tests/tests/admin/bau/upload_files.robot
- tests/robot-tests/tests/libs/admin-common.robot
- tests/robot-tests/tests/libs/tables-common.robot
This hotfix resolves duplicate replacements by cherry picking commits from dev which resolved the issue.
> EES-6189 hotfix

- src/GovUk.Education.ExploreEducationStatistics.Common/Cancellation/CancellationTokenTimeoutAttribute.cs
- src/GovUk.Education.ExploreEducationStatistics.Common/Converters/DateTimeToDateJsonConverter.cs
- src/GovUk.Education.ExploreEducationStatistics.Common/Extensions/TypeExtensions.cs
Eradicating build warnings, one warning at a time
> Tiny improvements

- src/explore-education-statistics-frontend/src/components/Page.tsx
- src/explore-education-statistics-frontend/src/modules/permalink/PermalinkPage.tsx
Removes the API data sets banner as it's not new any more.
> EES-6198 remove api banner

- src/GovUk.Education.ExploreEducationStatistics.Admin.Tests/Controllers/Api/Bau/FeedbackControllerTests.cs
- src/GovUk.Education.ExploreEducationStatistics.Admin.Tests/Controllers/Api/Methodologies/MethodologyControllerTests.cs
- src/GovUk.Education.ExploreEducationStatistics.Admin.Tests/Controllers/Api/Public.Data/DataSetVersionsControllerTests.cs
- src/GovUk.Education.ExploreEducationStatistics.Admin.Tests/Services/DataGuidanceServiceTests.cs
- src/GovUk.Education.ExploreEducationStatistics.Admin.Tests/Services/Methodologies/MethodologyAmendmentServiceTests.cs
- src/GovUk.Education.ExploreEducationStatistics.Admin.Tests/Services/ThemeServiceTests.cs
- src/GovUk.Education.ExploreEducationStatistics.Common.Tests/Cache/CacheAspectTests.cs
- src/GovUk.Education.ExploreEducationStatistics.Content.Services.Tests/MapperTests/MapperTests.cs
- src/GovUk.Education.ExploreEducationStatistics.Data.Services.Tests/Security/AuthorizationHandlers/ViewSubjectDataForPublishedReleasesAuthorizationHandlerTests.cs
If easier, review these one commit at a time.
Each commit message should provide the explanation - but all are super simple.
> Lots of Tiny fixes

- src/explore-education-statistics-frontend/__mocks__/@azure/search-documents.ts
- src/explore-education-statistics-frontend/src/modules/find-statistics/FindStatisticsPageAzure.tsx
- src/explore-education-statistics-frontend/src/modules/find-statistics/__tests__/FindStatisticsPageAzure.test.tsx
- src/explore-education-statistics-frontend/src/modules/find-statistics/__tests__/__data__/testFacetData.ts
- src/explore-education-statistics-frontend/src/modules/find-statistics/__tests__/__data__/testPublications.ts
- src/explore-education-statistics-frontend/src/modules/find-statistics/components/PublicationSummary.tsx
- src/explore-education-statistics-frontend/src/modules/find-statistics/components/__tests__/FiltersAzureSearch.test.tsx
- src/explore-education-statistics-frontend/src/modules/find-statistics/components/__tests__/PublicationSummary.test.tsx
- src/explore-education-statistics-frontend/src/services/__mocks__/azurePublicationService.ts
This PR adds Jest tests for the new azure search functionality and related components
> EES-6131 azure search unit tests

- infrastructure/parameters/prod.parameters.json
- infrastructure/templates/template.json
- src/explore-education-statistics-admin/src/pages/release/datablocks/components/DataBlockPageTabs.tsx
This PR merges master into the dev branch after the hotfix https://github.com/dfe-analytical-services/explore-education-statistics/pull/6000 was merged.
> Merging master into dev after PR #6000

- src/explore-education-statistics-admin/src/pages/release/datablocks/components/chart/__tests__/ChartBuilder.test.tsx
This skipped test will be unskipped in EES-6256
> EES-6257 Skip test intermittently failing in CI build

- src/explore-education-statistics-admin/src/pages/release/data/components/DataFilesTableUploadsRow.tsx
- src/explore-education-statistics-admin/src/pages/release/data/components/ScreenerResultsTable.tsx
- src/explore-education-statistics-admin/src/pages/release/data/components/__tests__/DataFilesTableUploadsRow.test.tsx
- src/explore-education-statistics-admin/src/services/releaseDataFileService.ts
Adds jest tests to EES-5999 work
Also makes some FE fixes and tweaks to aid testing and squash a couple of small bugs
> EES-5999 Jest tests

- infrastructure/templates/common/components/containerisedFunctionApp.bicep
- infrastructure/templates/screener/application/screenerContainerisedFunctionApp.bicep
- infrastructure/templates/screener/main.bicep
- infrastructure/templates/template.json
The Screener API requires access to the private temporary blob storage container in order to retrieve files for screening. These changes add the required settings to enable communication between these Azure services.
> EES-6185: Add core storage appsetting for Screener function.

- tests/robot-tests/tests/admin/bau/release_status.robot
- tests/robot-tests/tests/admin_and_public/bau/data_reordering.robot
- tests/robot-tests/tests/admin_and_public/bau/subject_reordering.robot
- tests/robot-tests/tests/admin_and_public_2/bau/publish_amend_and_cancel.robot
- tests/robot-tests/tests/admin_and_public_2/bau/publish_release_and_amend.robot
> EES-XXXX - updated various expectations in UI tests to reflect UI changes

- src/GovUk.Education.ExploreEducationStatistics.Admin.Tests/Services/Fixtures/DataSetFileStorageTestFixture.cs
Cleaning up warnings in the codebase.
> Cleaning up codebase

- src/GovUk.Education.ExploreEducationStatistics.Public.Data.Processor.Tests/Functions/CreateNextDataSetVersionMappingsFunctionTests.cs
- src/GovUk.Education.ExploreEducationStatistics.Public.Data.Processor.Tests/Functions/ProcessCompletionOfNextDataSetVersionFunctionsTests.cs
With about 1500 warnings to go, this might take a while. But slowly slowly.
> Cleaning up codebase 3

- src/explore-education-statistics-frontend/src/modules/table-tool/TableToolPage.tsx
- src/explore-education-statistics-frontend/src/modules/table-tool/components/TableToolFinalStep.tsx
- src/explore-education-statistics-frontend/src/modules/table-tool/components/__tests__/TableToolFinalStep.test.tsx
[See ticket 6357](https://dfedigital.atlassian.net/browse/EES-6357)
I had introduced a bug in the FE setup on [5976](https://dfedigital.atlassian.net/browse/EES-5976), so that's been rectified
> EES-6357 fixed missing table issue

- infrastructure/templates/template.json
- src/GovUk.Education.ExploreEducationStatistics.Data.Api/Requests/RecordPermalinkTableDownloadRequestBindingModel.cs
- src/GovUk.Education.ExploreEducationStatistics.Data.Api/Requests/RecordTableToolDownloadRequestBindingModel.cs
This PR:
- adds infra configuration to the ARM template for enabling analytics capture for the Data API.
> EES-6349 - adding analytics options to Data API, and mounting Analytics file path to Data API App Service

- styleguides/styleguide-frontend.md
Updating some of the testing guidance (probably should have done it ages ago).
Looks like more changes than it really is because of numbering and white space.
> Clarify some testing sections in FE styleguide

- tests/robot-tests/tests/admin_and_public/bau/release_reordering.robot
Fixing UI tests that failed in release_reordering.robot
> Fixing UI test failure
